### ISSUE TITLE
PHP Warning:  A non-numeric value encountered in \vendor\mpdf\mpdf\src\Tag\BlockTag.php on line 688

### ISSUE THREAD

**Issue by hjk0820** [mpdf/mpdf#1001]
PHP7.1 New E_WARNING and E_NOTICE errors have been introduced when invalid strings are coerced using operators expecting numbers (+ - * / ** % << >> | & ^) or their assignment equivalents. An E_NOTICE is emitted when the string begins with a numeric value but contains trailing non-numeric characters, and an E_WARNING is emitted when the string does not contain a numeric value.

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
