### ISSUE TITLE
"is_dir" warning

### ISSUE THREAD

**Issue by premekkoch** [mpdf/mpdf#101]
On production, php generates warning _File(..) is not within the allowed path(s)..._. I localized a problem, but I don't trust myself do do some kind of pullrequest here right. So I want to ask, if you can implement this fix, please:

In mpdf.php file on row nr. 7520 change conditions order this way:
`if (($file != "..") && ($file != ".") && (substr($file, 0, 1) !== '.') && ($file !='dummy.txt') && !is_dir($file) && ((filemtime(_MPDF_TEMP_PATH.$file)+$interval) < time())) { `

Thanks!

**Comment by finwe** [comment]
Hi, I believe that this is an issue of your server configuration. Are you sure that $file points within directories allowed in `open_basedir` php directive?

**Comment by premekkoch** [comment]
In my case $file variable always contain string "..". In fact, I don't know why but this is a reason, why is_dir function fail. How I wrote above, conditions order change resolves this problem.

**Comment by finwe** [comment]
As this is a matter of server configuration and not Mpdf, and will be solved in next major version by setting custom tmp dir, closing this as wontfix.
