### ISSUE TITLE
problem when I scan the library using veracode.com

### ISSUE THREAD

**Issue by almi9** [mpdf/mpdf#1014]
Dear 

I scan the library using http://www.veracode.com and it shows for me that:

Code Injection in src/Mpdf.php 9683

that is the code

	$os = preg_replace(['/\\\\/', '/\$/'], ['\\\\\\\\', '\\\\$'], $os);

				$this->pages[$n] = preg_replace('/(___HEADER___MARKER' . $this->uniqstr . ')/', "\n" . $os . "\n" . '\\1', $this->pages[$n]);

				$lks = $this->HTMLheaderPageLinks;

is that is a security issue? and can I delete that line because my manager request from me to remove any line that appears as a risk on the report

thank you

**Comment by finwe** [comment]
Given that $os is a PDF formatted string of the header, I doubt this is a security issue.

When removing the line, expect page headers to stop working or start behaving strangely at least.
