### ISSUE TITLE
Arabic font issue, is this a bug?

### ISSUE THREAD

**Issue by imannms** [mpdf/mpdf#1015]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug when non english word/font is used 
I tried to use Brunei Darussalam language or any other language with non-english word is used. And then mPDF throw error like this:

``` php
  ErrorException  : Undefined offset: 2

  at /var/www/prod/vendor/mpdf/mpdf/src/Otl.php:1538
  > 1538|    $nextGlyph = $this->OTLdata[$ptr + 1]['hex'];
  
```

``` php
  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 2", "/var/www/prod/vendor/mpdf/mpdf/src/Otl.php")
      /var/www/prod/vendor/mpdf/mpdf/src/Otl.php:1538

  2   Mpdf\Otl::_applyGSUBrulesIndic("locl ccmp nukt akhn rphf rkrf pref blwf half pstf vatu cjct", "gur2", "DFLT")
      /var/www/prod/vendor/mpdf/mpdf/src/Otl.php:637

```

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
```
mPDF v7.1.7
PHP 7.1.23-2+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 15 2018 11:36:43) ( NTS )
```

### This is a PHP code snippet I use

```
<?php


```

### This is a HTML/CSS code snippet I use

```

```

**Comment by finwe** [comment]
Not really helpful. That issue template is not there for nothing, you know. How do you initialize the Mpdf object? Are you using custom fonts? Can you share a small HTML snippet reproducing this behaviour?

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen, if still applicable on current version.
