### ISSUE TITLE
Composer mpdf directory bug

### ISSUE THREAD

**Issue by leubeem** [mpdf/mpdf#1017]
I found a bug in mpdf8 using php7.2.
In autoload_psr4.php the directory path for Mpdf was "$vendorDir . '/mpdf/mpdf/src'", but the correct directory to mpdf would be "$vendorDir . '/mpdf/src'".

I don't know whether this was my own fault or the composer did wrong work but please check it.

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
