### ISSUE TITLE
composer cross-dependncies with fpdi updating mpdf v7 - v8

### ISSUE THREAD

**Issue by barrycox** [mpdf/mpdf#1022]
I'm having trouble updating mpdf to v8.
when i use 'composer require mpdf/mpdf' i get:
` Problem 1
    - Installation request for mpdf/mpdf ^8.0 -> satisfiable by mpdf/mpdf[v8.0.0].
    - Conclusion: remove setasign/fpdi 1.6.2
    - Conclusion: don't install setasign/fpdi 1.6.2
    - mpdf/mpdf v8.0.0 requires setasign/fpdi ^2.1 -> satisfiable by setasign/fpdi[v2.1.0, v2.1.1, v2.2.0].
    - Can only install one of: setasign/fpdi[v2.1.0, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.1.1, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.2.0, 1.6.2].
    - Installation request for setasign/fpdi (locked at 1.6.2) -> satisfiable by setasign/fpdi[1.6.2].
`

so i read that as my fpdi needs to be v2.

so i do 'composer require setasign/fpdi'

but then i get: 
`Using version ^2.2 for setasign/fpdi
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mpdf/mpdf v7.1.9 requires setasign/fpdi 1.6.* -> satisfiable by setasign/fpdi[1.6.0, 1.6.1, 1.6.2] but these conflict with your requirements or minimum-stability.
    - mpdf/mpdf v7.1.9 requires setasign/fpdi 1.6.* -> satisfiable by setasign/fpdi[1.6.0, 1.6.1, 1.6.2] but these conflict with your requirements or minimum-stability.
    - mpdf/mpdf v7.1.9 requires setasign/fpdi 1.6.* -> satisfiable by setasign/fpdi[1.6.0, 1.6.1, 1.6.2] but these conflict with your requirements or minimum-stability.
    - Installation request for mpdf/mpdf (locked at v7.1.9, required as ^7.1) -> satisfiable by mpdf/mpdf[v7.1.9].
`
seems to be a cross-dependency that won't allow me to update either without updating both and i don't know how to update both at the same time...  sorry that this is probably a newbee question, but i couldn't find a solution anywhere.

**Comment by barrycox** [comment]
ok... DUH
composer require setasign/fpdi mpdf/mpdf
seemed to do the trick...  for the next newbe searching for this...

**Comment by godfreymakori** [comment]
@barrycox Thanks for the fix
