### ISSUE TITLE
mPDF Aesthetics especially in bullet & Numbering

### ISSUE THREAD

**Issue by SuikoHero38** [mpdf/mpdf#1029]
Dear all, 
We have found small issue in mpdf usage specifically in bullets & numbering. 
What we found is Aesthetics issue, that does not seem neat.

The example is attached:
On the left side of the picture is our document html-version and on the right side is the mpdf version of the left side document.

Please kindly to reconsider this issue.
![mpdf_neatless](https://user-images.githubusercontent.com/4024407/57118822-064df000-6d90-11e9-9c96-b199f78cbf6f.PNG)

Best Regards,

**Comment by jakejackson1** [comment]
Use `list-style-position` to place the bullet / number outside the content area.
