### ISSUE TITLE
Allow Base64 SVG Images

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#1031]
### I found this bug / would like to have this new functionality

Allow `svg+xml` image type when checking / retrieving for Base64-encoded image in https://github.com/mpdf/mpdf/blob/development/src/Image/ImageProcessor.php#L176

When dynamically generating an SVG image using PHP, I've a need to pass that directly to an `img` tag (which overrides the SVG's `viewBox` with the `img` width or height, allowing you to easily scale without distortions). To do this, I Base64 encode the SVG so I don't have to have any additional I/O overhead. 

This actually works successfully on most hosts, as `file_get_content` is converting a Base64 encoded image back to its original format. But I've found hosts with more restrictions in place that it doesn't work on. The simplest fix is to add `svg+xml` to the line linked about and skip `file_get_content` altogether.

Anyone see any problems with me adding this modification?

Running mPDF 8.0 on PHP7.2.

### This is a HTML/CSS code snippet I use

```
<img width="100%" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1OTUuMjggNzEuMzciPjxwYXRoIGZpbGw9IiMwOThGRkUiIGQ9Ik01OTUuMjggNzEuMzdWMEwxMDIuOTcgNzEuMzdoNDkyLjMxeiIvPjxwYXRoIGZpbGw9IiMzNDM0MzQiIGQ9Ik0wIDcxLjM3aDQwNy4yM0wwIDEyLjMzdjU5LjA0eiIvPjwvc3ZnPg==" />
```

**Comment by peterdevpl** [comment]
I think there won't be any problems. However, please prepare a good test case for this feature. It would be great to test if some simple shape from an SVG is rendered inside a PDF.
