### ISSUE TITLE
Fill Pdf Forms

### ISSUE THREAD

**Issue by deshario** [mpdf/mpdf#1036]
Can i fill pdf forms from this lib likka [PDFTK LIB](https://github.com/mikehaertl/php-pdftk) .. Actually in pdftk there is some problem about utf-8 characters(Utf8 chars are not visible in pdftk) ... So i wanna know that can i fill pdf fillable forms from this lib because mpdf supports utf8 fonts.

Image Below is the example of Filling forms from PDFTK
![image](https://user-images.githubusercontent.com/11426727/57480635-7dbcdb80-72ca-11e9-9f96-77a7cc556aa7.png)

**Comment by Klap-in** [comment]
Hi! Please use this issue tracker only for issues and feature requests, and please document them completely.

Your question read like a general support question, which fits better at https://stackoverflow.com/questions/tagged/mpdf

For an issue report it is needed to supply at least an example test case. Please consider that we cannot copy your text from an image, and we don't know your mpdf settings... For existing test cases I refer you to https://github.com/mpdf/mpdf/tree/development/tests/Issues
