### ISSUE TITLE
Div size ignored inside TD

### ISSUE THREAD

**Issue by christoferd** [mpdf/mpdf#1037]
### I found this bug
Div Width and Height appears to be ignored when inside TD
Note: the "div.div-width-height-40px" outside of the table is displayed correctly, while the one inside the TD is not.

This issue is similar to: https://github.com/mpdf/mpdf/issues/914

### Environment
This is mPDF v8.0.1 and PHP version 7.1 and environment (Windows, Apache 2) 

### This is a PHP code snippet I use
n/a 

### This is a HTML/CSS code snippet I use
```
.div-width-height-40px { background-color: orange; height: 40px; width: 40px; }

<div class="div-width-height-40px">&nbsp;</div>
    <table>
        <tbody>
        <tr>
            <td>
                <div class="div-width-height-40px">&#9679;</div>
            </td>
        </tr>
        </tbody>
    </table>
```

**Comment by finwe** [comment]
> Block-level tags (DIV, P etc) are ignored inside tables, including any CSS styles - inline CSS or stylesheet classes, id etc. To set text characteristics within a table/cell, either define the CSS for the table/cell, or use in-line tags e.g. <SPAN style=”…“>

See https://mpdf.github.io/tables/tables.html

**Comment by thedev8** [comment]
inside td make another table as div element apply css on that

**Comment by SamOxigen** [comment]
use `th` instead.
