### ISSUE TITLE
Update PHPUnit

### ISSUE THREAD

**Issue by MECU** [mpdf/mpdf#1038]
I would like to help the project by updating PHPUnit and updating tests.

Currently, the project supports PHP 5.6+.

PHP currently supports PHP 7.1+. https://www.php.net/supported-versions.php

PHPUnit requires PHP7.0 for ~v6.5, PHP7.1 for 7.0 and PHP7.2 for 8.0.

Are you fine with increasing the PHP version required to 7.0 or (my preference) 7.1? 

It would also resolve this warning when running `composer install` based on current reqs:
`Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.`

Based on your choice, I would increase the PHPUnit requirement accordingly.

**Comment by finwe** [comment]
See this conversation. https://github.com/mpdf/mpdf/issues/955

There is a significant user base with PHP 5.6, the PHP requirement will be raised no sooner than with mPDF v9.

Changing PHP requirements just for the sake of newer PHPUnit is not an option - current PHPUnit works OK.
