### ISSUE TITLE
Entire mPDF Manual Offline...

### ISSUE THREAD

**Issue by blueliquiddesigns** [mpdf/mpdf#104]
Looks like Ian has shut down the mPDF website: http://www.mpdf1.com/mpdf/index.php

It also appears the entire mPDF online documentation is now offline. What's the game plan? We need to have reliable online documentation. [I see there's a full PDF version of the docs](http://www.mpdfonline.com/repos/mpdfmanual.pdf) which will have to do for the moment, but it's not ideal.

**Comment by finwe** [comment]
I'd like to have the manual either as a https://readthedocs.org/ page or on Github pages https://mpdf.github.io/ in the future.

I don't exactly know what problems can be caused by the license of the docs, which was IIRC somehow restrictive.

**Comment by blueliquiddesigns** [comment]
I've always felt the Read the Docs features and format were better than Github Pages. 

Now the online docs are taken down I cannot check the original license it was under, but from memory it was a license that aloud someone to copy but not modify it. 

It would be very handy if someone could get in touch with Ian directly and discuss the online docs, its license ect.

**Comment by danielhjames** [comment]
Hi Jake, hi Matěj, I have an offline copy of the HTML version of the last manual. The license is http://www.opencontent.org/openpub/ which allows redistribution if the work is not substantially modified. I will make it available today.

**Comment by danielhjames** [comment]
@finwe please initialise https://github.com/mpdf/mpdf.github.io so I can fork it and make a pull request for the manual.

**Comment by danielhjames** [comment]
On the subject of ReadTheDocs vs. GitHub pages, I've used both, and while RTD definitely rules for Python projects which contain docstrings, I believe GitHub is just as good for a PHP project. GitHub has a slight edge because the docs can be read on the same platform as the source.

**Comment by marclaporte** [comment]
Can we ask copyright holder(s) to permit substantial changes?

**Comment by danielhjames** [comment]
The license says: "Substantive modification" is defined as a change to the semantic content of the document, and excludes mere changes in format or typographical corrections. So any changes to content require author permission.

My suggestion would be that we seek Ian's permission to maintain the manual online, while recognising him as primary author and acknowledging his copyright in any printed book which is produced. I will send Ian an email.

Also clause IV part 4 requires the location of the unmodified document to be identified. Since the original location is no longer available, I propose that the unmodified version is kept in a git branch such as 'upstream' and that any non-content changes go into master branch. This would also help with the requirement in clause IV part 2 that authors of modifications must be identified and modifications dated, since there would be a git log.

In the master branch, it would be good to get the search feature working, and fix up a few other things that no longer work (for example there is an admin login link to Ian's site).

By the way, it is not just the manual which is gone, the entire forum at http://www.mpdf1.com/forum/ along with all the answers to people's questions about mPDF has gone also.

**Comment by finwe** [comment]
@danielhjames When you write Ian, could you please also maybe ask for forum database? There may me many bug reports that would be lost.

**Comment by danielhjames** [comment]
I've just emailed Ian and cc'd you. I agree it would be very useful to have a copy of that database.

**Comment by Kovah** [comment]
Are there any news about the overall future of the project? At the moment I'm worried that the library may be not available in the future which would be horrible news for [InvoicePlane](https://github.com/InvoicePlane/InvoicePlane)...

**Comment by finwe** [comment]
The library stays available in this repository which became official. Future enhancements will be also made here.

**Comment by danielhjames** [comment]
Hi @Kovah I am glad to say that mPDF is released under the GNU GPL and that cannot be undone. The best way to ensure future availability is to support this community on GitHub, where active development is taking place.

**Comment by danielhjames** [comment]
In the meantime I have made the manual available at https://github.com/booktype/mpdf-manual

**Comment by blueliquiddesigns** [comment]
@danielhjames is this going to be classed as the official location for the documentation? Or just a temporary home?

**Comment by finwe** [comment]
I have published a mirror of the original documentation at https://mpdf.github.io/

**Comment by finwe** [comment]
Discussion about new online manual can be had at a separate issue. https://github.com/mpdf/mpdf/issues/108

**Comment by danielhjames** [comment]
Hi Jake, I think it belongs at https://mpdf.github.io/ since the whole community can contribute there.

**Comment by danielhjames** [comment]
I got no response from Ian yet, I think we can close this ticket.

**Comment by finwe** [comment]
I see now on mpdf1.com that the example PDF files are linked from mpdfonline.com domain which was registered by Ian on March 3rd. I don't know what to get from that.

**Comment by danielhjames** [comment]
http://www.mpdf1.com still says 'This mPDF website is now closed down.' Maybe Ian has other plans, but I heard nothing from him. Thanks for making the manual look so much better!

**Comment by adipurwan84** [comment]
Warning: Cannot modify header information - headers already sent by (output started at
how can i fixed?

**Comment by finwe** [comment]
@adipurwan84 Do not echo/print anything before calling $mpdf->Output() method.

**Comment by adipurwan84** [comment]
@finwe : this my code
	require_once("mpdf60/mpdf.php");
	$mpdf=new mPDF();
	$mpdf->WriteHTML("dsfds");
	$mpdf->Output();
	exit;
still not working

**Comment by finwe** [comment]
Is that your entire code after `<?php` tag? Is there anything before `<?php` tag?

Do you by any chance use Notepad in Windows, that would put BOM (hidden characters) to the start of your file?

**Comment by adipurwan84** [comment]
@finwe : sori
<?php
	require_once("mpdf60/mpdf.php");
	$html="souce";
	$mpdf=new mPDF();
	$mpdf->WriteHTML($html);
	$mpdf->Output();
	exit;
?>

**Comment by finwe** [comment]
You must have some output before the script, so I suggest you look into that.
Anyway, that is beyond mpdf and this thread.

**Comment by adipurwan84** [comment]
@finwe give me one exampel please...

**Comment by adipurwan84** [comment]
@finwe : i'll tried using in live server but not work

**Comment by adipurwan84** [comment]
@finwe : error 
require_once(__DIR__/../MpdfException.php)

**Comment by ssieb** [comment]
@adipurwan84, this issue is for a different topic.  Please open a new issue if you're still having a problem.  Look at the examples in the manual.  If you do open a new issue, attach a small example file that demonstrates the problem.

**Comment by adipurwan84** [comment]
@ssieb: sori....

**Comment by shaikhaffan** [comment]
Mpdf does not support display:inline ? i have agrid base design which i am converting to pdf, but it does not support inline css

**Comment by finwe** [comment]
@shaikhaffan https://mpdf.github.io/css-stylesheets/supported-css.html
Besides, you are off-topic here.

**Comment by shaikhaffan** [comment]
Hey it supports block but not inline, i tried, and which is the right place to comment, as you said it is off-topic

**Comment by finwe** [comment]
If display inline is not listed on the manual page, then it is not supported.

See https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md

**Comment by shaikhaffan** [comment]
Hey then What can i do to support that css, every pdf library has some drawback. But i found mpdf to be ausome. It would be great if u can help me out on this.

**Comment by finwe** [comment]
You are more than welcome to send a Pull Request adding that functionality. Or add a separate Issue requesting that, but there is no guarantee when or if someone will take that issue and add the feature.
