### ISSUE TITLE
Notice: Undefined index: miw in /var/www/html/vendor/mpdf/mpdf/src/Mpdf.php on line 19550

### ISSUE THREAD

**Issue by nimrod583** [mpdf/mpdf#1042]
### I found this bug / would like to have this new functionality
Notice: Undefined index: miw in /var/www/html/vendor/mpdf/mpdf/src/Mpdf.php on line 19550

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
PHP: 7.1.23  and 5.6.40
mPDF: 7.1.9

### This is a PHP code snippet I use

```
<?php
require_once '../vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf();

$stylesheet = file_get_contents('./scouts_style.css');

$mpdf->WriteHTML($stylesheet,1);
$new_html=str_replace("&nbsp", "", $html);
$mpdf->WriteHTML($new_html,2);

if ($mode=="F")
{
	$output_file="";
	$filename=$clubid.'-'.$eventid.'-'.$yp_surname.'-'.$yp_firstname.'.pdf';
	$path=$permission_slip_file_path;
	$output_file=$path.$filename;
	$mpdf->Output($output_file,'F');
}
else
{
	$mpdf->Output();
}
?>
```

### This is a HTML/CSS code snippet I use

[scouts_style css.txt](https://github.com/mpdf/mpdf/files/3244153/scouts_style.css.txt)

```

```

**Comment by finwe** [comment]
Please provide also your HTML code. And provide at least HTML/CSS code as possible that still reproduces this issue.

**Comment by nimrod583** [comment]
Here you go.

The error only occurs in the case that I create a file – mode ‘F’.

Thanks

**Comment by finwe** [comment]
I'm kind of missing the point of your last comment as you didn't provide the HTML example and didn't shorten the CSS code. Maybe something got lost in commenting via e-mail?

**Comment by nimrod583** [comment]
Here is the HTML example:

<table width=800><tr><td width=100 align=left><h2>Scout Group</h2></td><td width=* align=center><h2>Permission Slip - #732 (Tiny Ray)</h2></td><td width=150 align=right><img src="./images/logo-linear-purple-jpg.jpg" alt="Scout Logo" width="100px" height="35px"></td></table><hr><h3 align=left>Parent / Guardian Details (Emergency Contact)</h3><table border="0" cellspacing="0" cellpadding="0" width="650"><tr><td width=280 class="bodyText" align=right>Parents / Guardians First Name <font color="#FF0000">*</font></td><td align=left>Bobby</td></tr><tr><td width=280 class="bodyText" align=right>Parents / Guardians Surname <font color="#FF0000">*</font></td><td align=left>Ray</td></tr><tr><td width=280 class="bodyText" align=right>Section <font color="#FF0000">*</font></td><td align=left>Scouts</td></tr><tr><td class="bodyText" align=right>Relationship to the Young Person <font color="#FF0000">*</font></td><td align=left>Mother</td></tr><tr><td class="bodyText" align=right>EMail <font color="#FF0000">*</font></td><td align=left>eeeeee@hotmail.com</td></tr><tr><td class="bodyText" align=right>Emergency Contact Number <font color="#FF0000">*</font></td><td align=left>9999999</td></tr><tr><td colspan=2 align=center>&nbsp</td></tr></table><hr><h3 align=left>Young Persons Details</h3><table border="0" cellspacing="0" cellpadding="0" width="850"><tr><td width=280 class="bodyText" align=right>Young Persons First Name <font color="#FF0000">*</font></td><td align=left>Tiny</td></tr><tr><td width=280 class="bodyText" align=right>Young Persons Surname <font color="#FF0000">*</font></td><td align=left>Ray</td></tr><tr><td class="bodyText" align=right>Details of any disabilities, conditions, allergies, special needs or cultural needs that might affect this event</td><td align=left colspan=2>None</td></tr><tr><td class="bodyText" align=right>Shooting Approval</td><td align=left colspan=2>Shooting Agreed</td></tr><tr><td colspan=3 align=center>&nbsp</td></tr><tr><td class="bodyText" align=right>Details of any regular medications currently being taken</td><td align=left>None</tr><tr><td colspan=3 align=center>&nbsp</td></tr><tr><td class="bodyText" align=right>Emergency Medication</td><td align=left>None</td></tr><tr><td colspan=3 align=center>&nbsp</td></tr>   </table><br><table border="0" cellspacing="0" cellpadding="0" width="800"><tr><td align=left>If it becomes necessary for the above named young person to receive medical treatment and I cannot be contacted to authorise this, I hereby give my general consent to any necessary medical treatment and authorise the Leader in charge to sign any document required by the hospital authorities</td></tr><tr><td align=right>The above statement was read and acceptance confirmed</td></tr></table><br><h5>PERMISSION TO SHOOT</h5><table border="0" cellspacing="0" cellpadding="0" width="800"><tr><td colspan=2 align=left>The Scout Troop organises shooting as an activity from time to time. We are legally required to have a permission form for scouts to take part in this activity.</td></tr><tr><td colspan=2 align=left>&nbsp</td></tr><tr><td colspan=2 align=left>Section 21 of the Firearms Act 1968 prohibits the possession of a firearm and ammunition (under any circumstances), by any person who has been convicted of a crime and sentenced to a term of imprisonment (or its equivalent for young persons) of 3 months or more. The prohibition applies in all circumstances, including handling and firing at an approved shooting club or at a clay pigeon shoot where a certificate is not ordinarily required. It also applies to the possession or use of other categories of firearms and ammunition such as AIRGUNS or shot cartridges for which a certificate is not needed. A sentence of 3 months to 3 years attracts a 5 year prohibition, shorter ones no prohibition but a longer one means a life ban.</td></tr><tr><td colspan=2 align=left>&nbsp</td></tr></table><br><table border="0" cellspacing="0" cellpadding="0" width="800"><tr><td colspan=2 align=left><h5>Parent or Guardians consent</h5></td></tr><tr><td colspan=2 align=left>I, being the parent/guardian of the person named above, declare that he/she is not subject to restriction by virtue of Section 21 of the Firearms Act 1968 <br>(which applies only to persons who have served a term of imprisonment or youth custody)</td></tr><tr><td width="*" colspan=2 align=right><strong>The above statement was read and acceptance confirmed</strong></td></tr></table>

Here is the PHP code – the error remains the same without any CSS:

<?php
$yp_surname='0';
$yp_firstname='0';

$html='<table width=800><tr><td width=100 align=left><h2>Scout Group</h2></td><td width=* align=center><h2>Permission Slip - #732 (Tiny Ray)</h2></td><td width=150 align=right><img src="./images/logo-linear-purple-jpg.jpg" alt="Scout Logo" width="100px" height="35px"></td></table><hr><h3 align=left>Parent / Guardian Details (Emergency Contact)</h3><table border="0" cellspacing="0" cellpadding="0" width="650"><tr><td width=280 class="bodyText" align=right>Parents / Guardians First Name <font color="#FF0000">*</font></td><td align=left>Bobby</td></tr><tr><td width=280 class="bodyText" align=right>Parents / Guardians Surname <font color="#FF0000">*</font></td><td align=left>Ray</td></tr><tr><td width=280 class="bodyText" align=right>Section <font color="#FF0000">*</font></td><td align=left>Scouts</td></tr><tr><td class="bodyText" align=right>Relationship to the Young Person <font color="#FF0000">*</font></td><td align=left>Mother</td></tr><tr><td class="bodyText" align=right>EMail <font color="#FF0000">*</font></td><td align=left>eeeeee@hotmail.com</td></tr><tr><td class="bodyText" align=right>Emergency Contact Number <font color="#FF0000">*</font></td><td align=left>9999999</td></tr><tr><td colspan=2 align=center>&nbsp</td></tr></table><hr><h3 align=left>Young Persons Details</h3><table border="0" cellspacing="0" cellpadding="0" width="850"><tr><td width=280 class="bodyText" align=right>Young Persons First Name <font color="#FF0000">*</font></td><td align=left>Tiny</td></tr><tr><td width=280 class="bodyText" align=right>Young Persons Surname <font color="#FF0000">*</font></td><td align=left>Ray</td></tr><tr><td class="bodyText" align=right>Details of any disabilities, conditions, allergies, special needs or cultural needs that might affect this event</td><td align=left colspan=2>None</td></tr><tr><td class="bodyText" align=right>Shooting Approval</td><td align=left colspan=2>Shooting Agreed</td></tr><tr><td colspan=3 align=center>&nbsp</td></tr><tr><td class="bodyText" align=right>Details of any regular medications currently being taken</td><td align=left>None</tr><tr><td colspan=3 align=center>&nbsp</td></tr><tr><td class="bodyText" align=right>Emergency Medication</td><td align=left>None</td></tr><tr><td colspan=3 align=center>&nbsp</td></tr>   </table><br><table border="0" cellspacing="0" cellpadding="0" width="800"><tr><td align=left>If it becomes necessary for the above named young person to receive medical treatment and I cannot be contacted to authorise this, I hereby give my general consent to any necessary medical treatment and authorise the Leader in charge to sign any document required by the hospital authorities</td></tr><tr><td align=right>The above statement was read and acceptance confirmed</td></tr></table><br><h5>PERMISSION TO SHOOT</h5><table border="0" cellspacing="0" cellpadding="0" width="800"><tr><td colspan=2 align=left>The Scout Troop organises shooting as an activity from time to time. We are legally required to have a permission form for scouts to take part in this activity.</td></tr><tr><td colspan=2 align=left>&nbsp</td></tr><tr><td colspan=2 align=left>Section 21 of the Firearms Act 1968 prohibits the possession of a firearm and ammunition (under any circumstances), by any person who has been convicted of a crime and sentenced to a term of imprisonment (or its equivalent for young persons) of 3 months or more. The prohibition applies in all circumstances, including handling and firing at an approved shooting club or at a clay pigeon shoot where a certificate is not ordinarily required. It also applies to the possession or use of other categories of firearms and ammunition such as AIRGUNS or shot cartridges for which a certificate is not needed. A sentence of 3 months to 3 years attracts a 5 year prohibition, shorter ones no prohibition but a longer one means a life ban.</td></tr><tr><td colspan=2 align=left>&nbsp</td></tr></table><br><table border="0" cellspacing="0" cellpadding="0" width="800"><tr><td colspan=2 align=left><h5>Parent or Guardians consent</h5></td></tr><tr><td colspan=2 align=left>I, being the parent/guardian of the person named above, declare that he/she is not subject to restriction by virtue of Section 21 of the Firearms Act 1968 <br>(which applies only to persons who have served a term of imprisonment or youth custody)</td></tr><tr><td width="*" colspan=2 align=right><strong>The above statement was read and acceptance confirmed</strong></td></tr></table>';

require_once '../vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf();

$mpdf->WriteHTML($html,2);

$filename='./1-1.pdf';
$mpdf->Output($filename,'F');

?>

**Comment by finwe** [comment]
`*` is not a valid value for HTML `width` attribute. That's what is causing the error.

The notice will be fixed in future releases.

**Comment by nimrod583** [comment]
Thank you!
