### ISSUE TITLE
[fix provided] Output filename doesn't work when using progress bar

### ISSUE THREAD

**Issue by jangreis** [mpdf/mpdf#105]
output options "I" and "D" both return the filename as out.php which is very confusing for users. "S" works normally.

On a related (but significantly less important) note, when specifying progbar_altHTML, the javascript functions that are meant to control the default html are still called, resulting in thousands of
"Uncaught TypeError: Cannot set property 'innerHTML' of null" errors in the console.

**Comment by jangreis** [comment]
I managed to figure out a fix, looks like a wrong variable name. Change line 7 in out.php from $opname = $_REQUEST['opname'];
to
$name = $_REQUEST['opname'];
and it works.

**Comment by finwe** [comment]
Fixed in development branch.
