### ISSUE TITLE
SetColumns(2) throws an undefined index error

### ISSUE THREAD

**Issue by lourdas** [mpdf/mpdf#1051]
### This is a PHP code snippet I use

```
$mpdf->SetColumns(2);
```
The error is:
```
2019/06/25 21:58:14 [error] [php] Undefined offset: 1 (.................../components/mpdf/mpdf/mpdf/src/Writer/BaseWriter.php:205)
Stack trace:
#0 .................../components/mpdf/mpdf/mpdf/src/Mpdf.php(22332): Mpdf\Mpdf->Rect()
#1 .................../components/mpdf/mpdf/mpdf/src/Tag/Table.php(1121): Mpdf\Mpdf->_tableWrite()
#2 .................../components/mpdf/mpdf/mpdf/src/Tag.php(250): Mpdf\Tag\Table->close()
#3 .................../components/mpdf/mpdf/mpdf/src/Mpdf.php(13509): Mpdf\Tag->CloseTag()
```

**Comment by ruslanraupoff** [comment]
@lourdas did you fix it?

**Comment by lourdas** [comment]
> @lourdas did you fix it?

No.

**Comment by welinaldo** [comment]
Acredito que não seja um bug na versão ou no baseWriter.php line 205. Eu tive o mesmo erro e na verdade o problema era na estrutura de tabelas do meu html.

**Comment by Slayvin** [comment]
I still noticed the same bug with version 8.0.11.
I set `$mpdf->SetColumns(2)` and then added some padding to a cell (td) element, and this issue popped-up.
`$mpdf->ColDetails[$mpdf->CurrCol]` is undefined here :
https://github.com/mpdf/mpdf/blob/58322c5cf83a5f86e0c5e2109af1e1ce47685b5d/src/Writer/BaseWriter.php#L204

**Comment by finwe** [comment]
@Slayvin Please create a new Issue using the Bug report template.
