### ISSUE TITLE
Undefined index: inherit when using Bootstrap 4 and TD

### ISSUE THREAD

**Issue by shahimclt** [mpdf/mpdf#1060]
### I found this bug / would like to have this new functionality

When using with a 'td' tag and bootstrap 4, I get the following error:

> Notice: Undefined index: inherit in C:\xampp\htdocs\engage_web\vendor\mpdf\mpdf\src\Tag\Td.php on line 208

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

PHP version: 7
mPDF version: 8.0.2

### This is a PHP code snippet I use

    $mpdf->WriteHTML($this->load->view('survey/surveyReport_printable', $data));

Thats all I've been able to narrow down. I would like some workarounds and/or some pointers to help me fix it myself.

**Comment by ssieb** [comment]
Get the html output of
$this->load->view('survey/surveyReport_printable', $data)
Try viewing it in a web browser and try to reduce it to the minimum required to cause the error.  Particularly look for some CSS with "inherit" in it.  The developers can't do anything with no data.

**Comment by GabrielCNoble** [comment]
Linked is a simple example that triggers this problem.

[https://pastebin.com/r96ZL04b](url)

**Comment by GabrielCNoble** [comment]
This is enough to trigger the problem.

[pastebin.com/VaALc0Tz](url)

**Comment by Servietteski** [comment]
Bootstrap isn't supported by MPDF, it's annoying. Same issue

**Comment by thallesdaniell** [comment]
I detected this and decided to extract the bootstrap for the style tag and tested it until I reached that style and removing it worked for me
```
    th {
        text-align: inherit
    }
```

**Comment by MarkVaughn** [comment]
same breaking when parsing random emails containing `text-align: initial`

**Comment by finwe** [comment]
One-line comments without meaningful code example are not helpful. Even more so when the original issue is aslo missing full code example.

Please create separate issues with reproducible code samples to faster reproduce and therefore fix the issue.

**Comment by MarkVaughn** [comment]
From: 
https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
Here are possible values for text-align
```
/* Keyword values */
text-align: left;
text-align: right;
text-align: center;
text-align: justify;
text-align: justify-all;
text-align: start;
text-align: end;
text-align: match-parent;

/* Character-based alignment in a table column */
text-align: ".";
text-align: "." center;

/* Block alignment values (Non-standard syntax) */
text-align: -moz-center;
text-align: -webkit-center;

/* Global values */
text-align: inherit;
text-align: initial;
text-align: unset;
```

And \Mpdf\Tag\Tag only supports the values defined in the const
```
	const ALIGN = [
		'left' => 'L',
		'center' => 'C',
		'right' => 'R',
		'top' => 'T',
		'text-top' => 'TT',
		'middle' => 'M',
		'baseline' => 'BS',
		'bottom' => 'B',
		'text-bottom' => 'TB',
		'justify' => 'J'
	];
```
so whenever `self::ALIGN[$foo]`  is being called with valid values such as inherit/initial/start/end the `Notice: Undefined index:`  notice breaks applications that don't ignore notices. 
My PR #1194 prevents the notice from happening.
