### ISSUE TITLE
\Mpdf\Cache::clearOld Resource Temporarily Unavailable

### ISSUE THREAD

**Issue by naknak987** [mpdf/mpdf#1062]
### I found this bug / would like to have this new functionality
When `\Mpdf\Cache::clearOld()` is called it tries to clear out temp files that don't belong to it. 
![image](https://user-images.githubusercontent.com/24255404/62133660-29177400-b2ad-11e9-8ecf-0a2a8e33c129.png)
![image](https://user-images.githubusercontent.com/24255404/62133687-346a9f80-b2ad-11e9-981b-6252d5829a5d.png)
I'm sure that the `ExchangePerflog_ 88*****.dat` file does not belong to Mpdf.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF 8.0.x
PHP 3.3.2 CLI on Windows 10

### This is a PHP code snippet I use
I was trying to create a PDF using `\PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf`.

**Comment by jakejackson1** [comment]
[The mPDF temporary directory should be assigned to a folder](https://mpdf.github.io/installation-setup/folders-for-temporary-files.html) where only its files are stored, and not shared with any other applications.

**Comment by naknak987** [comment]
@jakejackson1 
Thank you for that. It appears that this is in fact an issue for PhpSpreadsheet then since the path to temporary would have been set in their code. My apologies for posting here.
