### ISSUE TITLE
Undefined index: data in ImageWriter.php line 96

### ISSUE THREAD

**Issue by tandang213** [mpdf/mpdf#1066]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug when first using mpdf
The case is when i am rendering pdf with looping, the second loop always return image error : Undefined index: data in ImageWriter.php line 96. I think that i have a problem with my temp folder permission. But i've check it and i have grant full access. 

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF : ^8.0 / ^7.0
PHP : 7.1.3

### This is a PHP code snippet I use

```
<?php

$pdf->Output('report.pdf', \Mpdf\Output\Destination::FILE);

```

### This is a HTML/CSS code snippet I use

```
<img src='https://ibidsmsfrontend-dev.azurewebsites.net/assets/img/ibid.png' class="img-content">
```

**Comment by ssieb** [comment]
You will need to provide more details than that.  You need to include a complete sample that can reproduce the issue.

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to reopen with all available details, especially a code example that actually reproduces the issue.

**Comment by sergiokessler** [comment]
same here:

`<b>Notice</b>:  Undefined index: data in <b>/var/www/html/mx/vendor/mpdf/mpdf/src/Writer/ImageWriter.php</b> on line <b>96</b><br />`

using it in a loop like:

```
$pdf = new \Mpdf\Mpdf($pdf_params);
$pdf->shrink_tables_to_fit = 1;
// autosize wins
$pdf->tableMinSizePriority = true;

while ($row = $st->fetch()) {
    $filename = $row['name'] . '.pdf';
    $output = "$base_dir/$filename";

    $html = \PIM\PdfHtml::htmlHeader() . $row['html'];
    // echo $html; exit;
    $pdf->WriteHTML($html);

    $pdf->Output($output, 'F');
}
```

**Comment by finwe** [comment]
@sergiokessler Not helpful unless you provide the actual code used to reproduce the issue.

**Comment by sergiokessler** [comment]
@finwe I understand I'm not being very helpful and you want a self-contained example.

but maybe this will help: 

- the `img href` in the html doesn't exist (is pointing to a 404), I _think_ the `undefined index` comes from that...

- if I change the code to:

```
while ($row = $st->fetch()) {
    $pdf = new \Mpdf\Mpdf($pdf_params);
    $pdf->shrink_tables_to_fit = 1;
    // autosize wins
    $pdf->tableMinSizePriority = true;

    $filename = $row['name'] . '.pdf';
    $output = "$base_dir/$filename";

    $html = \PIM\PdfHtml::htmlHeader() . $row['html'];
    // echo $html; exit;
    $pdf->WriteHTML($html);

    $pdf->Output($output, 'F');

    unset($pdf)
}
```

there is no warning **at all**  (the html is exactly the same)
(of course, the final pdfs lack the images)
