### ISSUE TITLE
mathjax not properly in two columns 

### ISSUE THREAD

**Issue by gajnini** [mpdf/mpdf#1068]
single column working perfect but coming dual columns set getting error bottom page over written in first page 

bottom page completely blank itself  
find in reference in below link 
[https://www.gurujobalert.com/img/CWegTiFI.png](https://www.gurujobalert.com/img/CWegTiFI.png)

**Comment by gajnini** [comment]
`$mpdf->WriteHTML($stylesheet, 1);
    $mpdf->SetColumns(2, 'J', 3);
	$mpdf->keepColumns = true;
	$mpdf->WriteHTML($html);
	$mpdf->Output();`

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
