### ISSUE TITLE
When i loop in and try creating pdf's it throws Notice saying - Undefined offset: 1  Filename: Tag/Td.php Line Number: 335

### ISSUE THREAD

**Issue by varshaan0sharma** [mpdf/mpdf#1071]
### I found this bug

A PHP Error was encountered
Severity: Notice

Message: Undefined offset: 1

Filename: Tag/Td.php

Line Number: 335

Backtrace:

File: /Applications/MAMP/htdocs/trinityndt_main/vendor/mpdf/mpdf/src/Tag/Td.php
Line: 335
Function: _error_handler

File: /Applications/MAMP/htdocs/trinityndt_main/vendor/mpdf/mpdf/src/Tag.php
Line: 243
Function: open

File: /Applications/MAMP/htdocs/trinityndt_main/vendor/mpdf/mpdf/src/Mpdf.php
Line: 13620
Function: OpenTag

File: /Applications/MAMP/htdocs/trinityndt_main/vendor/mpdf/mpdf/src/Mpdf.php
Line: 12250
Function: WriteHTML

File: /Applications/MAMP/htdocs/trinityndt_main/vendor/mpdf/mpdf/src/Mpdf.php
Line: 13155
Function: _getHtmlHeight

File: /Applications/MAMP/htdocs/trinityndt_main/application/views/export/rtexport.php
Line: 880
Function: WriteHTML

File: /Applications/MAMP/htdocs/trinityndt_main/application/controllers/Export.php
Line: 60
Function: view

File: /Applications/MAMP/htdocs/trinityndt_main/index.php
Line: 315
Function: require_once

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
php 7.1.16 and Mpdf 7.1.7
### This is a PHP code snippet I use
Here $headerArr is array of page html
```
<?php

    // echo "<pre>"; print_r($headerArr);exit;
    for($j=0;$j<count($headerArr);$j++){
        $mpdf = new \Mpdf\Mpdf(['default_font_size' => 9, 'debug' => true]);

        $mpdf->SetWatermarkImage(
                    'assets/img/watermarklogo.png', 
                    0.5, 
                    '', 
                    array(45,100)
                );
        $mpdf->showWatermarkImage = true;
        $mpdf->watermarkImageAlpha = 0.1;
        $mpdf->WriteHTML($headerArr[$j]);
        $mpdf->SetHTMLFooter($footer);
        $mpdf->Output('rtf_'.$j.'.pdf','F');
        unset($mpdf);
    }
```

**Comment by finwe** [comment]
Not entirely helpful. Can you share an actual HTML snippet reproducing this behaviour? Make it as small as possible, please.

**Comment by varshaan0sharma** [comment]
Hi, 

Thanks for the response.

Can access the complete file using below url.

[https://we.tl/t-Jz4SjY5OeN](url)

**Comment by ssieb** [comment]
Could you please try to reduce that to the part that causes the problem?

**Comment by varshaan0sharma** [comment]
Hi, The part which is creating this issue is added to the question. I tried displaying the result as HTML and it comes perfect. When I iterate I get this issue. What may be the cause of this notice?

**Comment by finwe** [comment]
Still not helpful. I cannot run the example file as I don't have $testData variable populated. Provide clean and as small HTML example as possible.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen, if still applicable on current version.
