### ISSUE TITLE
'Plus' not initialized on Mpdf.php

### ISSUE THREAD

**Issue by guicalabria** [mpdf/mpdf#1075]
On previous line 18439 I got a warning because it's not initialized. So I added
else { $this->OTLtags['Plus'] = ''; }
to start 'Plus'.

**Comment by guicalabria** [comment]
I don't have access to upload a test file.
This is the content I got the issue
https://www.heypasteit.com/clip/0IT706

**Comment by finwe** [comment]
You created a pull request. Add the test file to the pull request. Closing this as it duplicates the PR #1074
