### ISSUE TITLE
Error in count () in php 7.3 version

### ISSUE THREAD

**Issue by rusline18** [mpdf/mpdf#1078]
When uploading an image to convert it to pdf, an error occurs in php 7.3

mpdf/mpdf/classes/ttfontsuni.php
> count() Parameter must be an array or an object that implements Countable
`for($i = 0; $i < count($psName); $i++){`
I looked at what is in the variable $psName and there is a line.
can fix this bug.

**Comment by finwe** [comment]
Please, post your PHP/HTML code snippet causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by ywarnier** [comment]
I have the same issue with PHP 7.2
My code:
```
        $this->pdf = new mPDF(
            'UTF-8',
            'A4',
            '',
            '',
            15,
            15,
            30,
            30,
            8,
            8,
            'P'
        );
```

The (simplified) xdebug stack trace:
```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in [..]/vendor/mpdf/mpdf/classes/ttfontsuni.php on line 613
PHP Stack trace:
PHP   1. {main}() [..]/lp_controller.php:0
PHP   2. require() [..]/lp_controller.php:1579
PHP   3. PDF->__construct() [..]/lp_report.php:166
PHP   4. mPDF->__construct() [..]/inc/lib/pdf.lib.php:73
PHP   5. mPDF->SetDefaultFont() [..]/vendor/mpdf/mpdf/mpdf.php:1287
PHP   6. mPDF->SetFont() [..]/vendor/mpdf/mpdf/mpdf.php:13621
PHP   7. mPDF->AddFont() [..]/vendor/mpdf/mpdf/mpdf.php:4246
PHP   8. TTFontFile->getMetrics() [..]/vendor/mpdf/mpdf/mpdf.php:3880
PHP   9. TTFontFile->extractInfo() [..]/vendor/mpdf/mpdf/classes/ttfontsuni.php:202
```

**Comment by finwe** [comment]
@ywarnier Based on your constructor, you are using mPDF 6 which does not support higher versions of PHP. Upgrade to mPDF 8.0.

**Comment by finwe** [comment]
@rusline18 The same seem to apply for your code. Feel free to reopen if the issue persists in the last version of mPDF.
