### ISSUE TITLE
Update online manual at mpdf.github.io

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#108]
- use epub version of the manual
- preferrably use jekyll to build headers and footers

**Comment by danielhjames** [comment]
The biggest limitation of the current static copy is that the search feature doesn't work. However the old manual disabled external search, see http://www.mpdf1.com/robots.txt 
So we may get more traffic to the manual from search engines in future.

**Comment by blueliquiddesigns** [comment]
Is it safe to begin linking to specific pages in the manual? Or could the link structure fluctuate while we finalise the migration?

**Comment by finwe** [comment]
Links to pages WILL change, i would like to have a reasonable url structure.

I will make a warning on top of every page some time later today or tomorrow.

**Comment by finwe** [comment]
@danielhjames @blueliquiddesigns Could you please take a look at https://finwe.github.io/test-pages/ if you see any major mistakes or errors?

**Comment by danielhjames** [comment]
Looks great! My only comment is that I couldn't find the copyright page with the content from http://mpdf.github.io/index4574.html?page=copyright

As the copyright license on the documentation is rather restrictive for an open source project, I feel this notice should be prominent. I haven't heard anything from Ian.

**Comment by finwe** [comment]
Ok, thanks. I will create it somewhere - it is not linked from the tree menu, so it has eluded me.

**Comment by finwe** [comment]
OK, I've added the copyright page, implemented simple foldable menu and deployed to https://mpdf.github.io/. Additional issues can be added directly to the manual repository https://github.com/mpdf/mpdf.github.io
