### ISSUE TITLE
Add blank page if current page is ODD

### ISSUE THREAD

**Issue by speeduppoznan** [mpdf/mpdf#1081]
Hi
I have table in HTML, which will take sometimes one page, sometimes more. After add this to pdf I need check how many pages I have so far and add blank page if I have an odd number of pages.
After that I will add another content.

How can I do that?

**Comment by Klap-in** [comment]
Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting! 
Doing so, this issue tracker can be used for the real issues. If you have found an issue, please demonstrate it by adding a minimal html and php example.
