### ISSUE TITLE
Dates in information dictionary are not prefixed by "D:"

### ISSUE THREAD

**Issue by paulish** [mpdf/mpdf#1083]
PDFs which are created by Acrobat PDFMaker have CreationDate and ModDate dates prefixed by "D:"

An example: 
> /ModDate(D:20171222131004+03'00')

Dates generated by mPDF don't have this prefix.
An example: 
> /ModDate (20190906012700+00'00')

As result they don't pass PDF/A validation by [veraPDF](https://verapdf.org/home/#validation) library.

I fixed this locally by changing writeInfo of MetadataWriter.php:
`$this->writer->write('/CreationDate ' . $this->writer->string('D:'.date('YmdHis') . $offset));
$this->writer->write('/ModDate ' . $this->writer->string('D:'.date('YmdHis') . $offset));`

The [PDF reference](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf) also states in 3.8.3 that 'D:' is optional but strongly recommended.

**Comment by peterdevpl** [comment]
I made a PR for this :)
