### ISSUE TITLE
mPdf is not supporting for Hindi 

### ISSUE THREAD

**Issue by jssujin** [mpdf/mpdf#1084]
Hi,

mPdf is not supporting for many of Indian Languages including national language Hindi. It means it is working partially and unable to read the message.

Any one can help to fix it? Your help will be highly appreciated.

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by finwe** [comment]
Hindi is of course supported. See https://github.com/mpdf/mpdf-examples/blob/development/example29_multilingual_autofont.php
