### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#1092]
Work on this is in progress in https://github.com/mpdf/mpdf/pull/1091

Will test and merge no sooner than stable (or at least RC) 7.4 is available in Travis CI.

**Comment by snapshotpl** [comment]
7.4 is available in travis ci as `7.4snapshot`

**Comment by finwe** [comment]
Yes, playing with this now. Thanks.

**Comment by finwe** [comment]
Closed with #1091

Composer support will be added with stable PHP release.

**Comment by Eugentis** [comment]
@finwe What about creating some specific branch for applications with PHP 7.4? It can be more effective to avoid a lot of messages about php 7.4. compatibility

**Comment by finwe** [comment]
Use --ignore-platform-reqs in composer until PHP 7.4 stable is released.

**Comment by burakkocalar** [comment]
merhaba kütüphaneyi kullanırken 414 (Request-URI Too Long) böyle bir hata veriyor içine attıgım veriyi pdf yapamıyor 
attıgım veri :
<div class="well" id="well" data-fatura="B2B000000009250"> 

		<div class="row">
				<div class="col-md-8"></div>
				<div class="col-md-4">
					<table class="table custom-table">
						<thead>
							<tr>
								<td width="150"> GÖKOVA OTO ELEKTRYK - DEMET GÖKOVA </td>
								  <td width="150">  </td>
							</tr>
							<tr>
								
								<td width="150">  MU?LA/ORTACI </td>
						          <td width="150"> DO?AN ÇAKMAK </td>
							</tr>
							<tr>
								
								<td width="150"> SANAYY SYTESY  TEL: 0532 391 75 02 </td>
								  <td width="150"> 2020-04-02 00:00:00.0000000 </td>
							</tr>
							<tr>
								<td width="150">  </td>
								
							</tr>
						</thead>
					</table>
				</div>
			</div>
		</div>

		
			<table class="table table-bordered">
				<thead class="thead-dark">
					<tr>
						<th>#</th>
						<th scope="col">Stok Kodu</th>
						<th scope="col" width="200">Stok Adı</th>
						<th scope="col">Fiyatı</th>
						<th scope="col">Adet</th>
						<th scope="col">Tutar</th>
						<th scope="col">Bakiye</th>
					</tr>
				</thead>
				<tbody>
					
						<tr>
						<td>156</td>
						<td>MAKO-72365010</td>S
						<td>BURC (ORTA KAPAK) 12 VOLT TÜM ARAÇLARDA</td>
						<td>2.37410000₺</td>
						<td>10.00000000</td>
						<td>28.014380₺</td>
						<td>10.00000000</td>
						</tr>
						<tr>
						<td>157</td>
						<td>UNIP-SNLS678</td>S
						<td>UNYPOYNT MAR? OTOMATY?Y 12V MITSUBISHI L 300 / HYUNDAI H 100</td>
						<td>168.86550000₺</td>
						<td>5.00000000</td>
						<td>996.306450₺</td>
						<td>5.00000000</td>
						</tr>
						<tr>
						<td>158</td>
						<td>SFX-H4</td>S
						<td>H4 LED ZENON FAR AMPÜLÜ</td>
						<td>80.55000000₺</td>
						<td>4.00000000</td>
						<td>380.196000₺</td>
						<td>75.00000000</td>
						</tr>
						<tr>
						<td>159</td>
						<td>SFX-H7</td>S
						<td>H7 LED ZENON FAR AMPÜL</td>
						<td>62.65000000₺</td>
						<td>2.00000000</td>
						<td>147.854000₺</td>
						<td>155.00000000</td>
						</tr>
						<tr>
						<td>160</td>
						<td>WINWIN-RT205</td>S
						<td>REDÜKTÖR BOSCH/DELCO TYPY DAF XF CF SERYLERYNE SCANIA P.G.R.T SERYLERYNE 0 001 241 SERYSY MAR?LARA R</td>
						<td>196.70570000₺</td>
						<td>2.00000000</td>
						<td>464.225452₺</td>
						<td>2.00000000</td>
						</tr>
						<tr>
						<td>161</td>
						<td>GLOBE-3M</td>S
						<td>3M ELEKTRYK YZOLASYON BANDI 19MM</td>
						<td>2.20000000₺</td>
						<td>50.00000000</td>
						<td>129.800000₺</td>
						<td>3963.00000000</td>
						</tr>
						<tr>
						<td>162</td>
						<td>TKS-SF1DMINI</td>S
						<td>P.BA?.YASSI DY?Y MYNY TERMYNAL (500 ADET)</td>
						<td>0.05710000₺</td>
						<td>500.00000000</td>
						<td>33.649030₺</td>
						<td>13000.00000000</td>
						</tr>
						<tr>
						<td>163</td>
						<td>VALEO-594188</td>S
						<td>YEDEK PARÇA MAR? OTOMATY?Y D6RA</td>
						<td>0.00000000₺</td>
						<td>3.00000000</td>
						<td>0.000000₺</td>
						<td>3.00000000</td>
						</tr>
						<tr>
						<td>164</td>
						<td>WINWIN-SW894</td>S
						<td>MARS OTOMATIGI 12V ISKRA TIP DEUTZ AG (KHD) ATLAS COPCO BOMAGGEHL LIEBHERR VOLVO IS1073 16.907.894</td>
						<td>112.64110000₺</td>
						<td>1.00000000</td>
						<td>132.916498₺</td>
						<td>2.00000000</td>
						</tr>
						<tr>
						<td>165</td>
						<td>REM-STR6815</td>S
						<td>MAR? MOTORU BOSCH TYPY 12V 10 DY? 1.1 KWFORD FIESTA 1.4/1.6/1.6-16V 1995 -->2002FORD FOCUS 1.4-16V 9</td>
						<td>515.73250000₺</td>
						<td>1.00000000</td>
						<td>608.564350₺</td>
						<td>1.00000000</td>
						</tr>
						<tr>
						<td>166</td>
						<td>MEGA-SMI0699</td>S
						<td>MITS T.12V.HYUNDAI ACCENT/L-300/MAZD</td>
						<td>113.48600000₺</td>
						<td>2.00000000</td>
						<td>267.826960₺</td>
						<td>10.00000000</td>
						</tr>
						<tr>
						<td>167</td>
						<td>REM-SM002</td>S
						<td>MAR? OTOMATY?Y MITSUBISHI TYPY 12VCHEROKEE JEEPOEM NO:M371X62571SB665</td>
						<td>94.73940000₺</td>
						<td>2.00000000</td>
						<td>223.584984₺</td>
						<td>2.00000000</td>
						</tr>
						<tr>
						<td>168</td>
						<td>ZM-4698</td>S
						<td>12V MITSUBISHI L300 YENI MODEL / HYUNDAI ACCENT / MAZDA 323 (TEK FISLI YAN - 4 DELIK)</td>
						<td>151.96830000₺</td>
						<td>2.00000000</td>
						<td>358.645188₺</td>
						<td>26.00000000</td>
						</tr>
						<tr>
						<td>169</td>
						<td>REM-SM082</td>S
						<td>MAR? OTOMATY?Y MITSUBISHI TYPY 12VRENAULT KANGOO I 1.4 1997-2007 RENAULT MEGANE I 1.4 1999-2002 RENA</td>
						<td>99.81040000₺</td>
						<td>2.00000000</td>
						<td>235.552544₺</td>
						<td>2.00000000</td>
						</tr>
						<tr>
						<td>170</td>
						<td>MEGA-SMI2993</td>S
						<td>MITS T.12V.CLIO/KANGOO/DACIA LOGAN</td>
						<td>113.84400000₺</td>
						<td>2.00000000</td>
						<td>268.671840₺</td>
						<td>10.00000000</td>
						</tr>
						<tr>
						<td>171</td>
						<td>ZM-1761</td>S
						<td>12V FORD CONNECT / FIESTA / FOCUS / TRANSIT / MONDEO / KA (CBS-F203)</td>
						<td>145.45530000₺</td>
						<td>2.00000000</td>
						<td>343.274508₺</td>
						<td>18.00000000</td>
						</tr>
						<tr>
						<td>172</td>
						<td>REM-SF020</td>S
						<td>MAR? OTOMATY?Y MOTOCRAFT TYPY 12VFORD CONNECT/FORD RANGEROEM NO:	F3VY11390B/F4DZ11390A/SW2188SW2207/</td>
						<td>93.85850000₺</td>
						<td>2.00000000</td>
						<td>221.506060₺</td>
						<td>3.00000000</td>
						</tr>				</tbody>
			</table>
			<hr />
			<div class="row">
				<div class="col-md-8"></div>
				<div class="col-md-4">
					<table class="table" border="3">
						<thead>
							<tr>
								<th>Ara Toplam:</th>
								<td> 4102.22800000₺ </td>
							</tr>
							<tr>
								<th>İskonto:</th>
								<td> 0.00000000₺ </td>
							</tr>
							<tr>
							
								<th>KDV:</th>
								<td> 738.40020000₺ </td>
							</tr>
							<tr>
								<th>Genel Toplam:</th>
								<td> 4840.62820000₺ </td>
							</tr>

						</thead>
					</table >


					<table border="3">
			               	<tr>
								<td width="450"> SİPARİŞİ HAZIRLAYAN aa</td>
								<td width="100">KONTROL EDEN aa</td>
							</tr>

					</table>


				</div>
			</div>
		</div>

**Comment by looknear** [comment]
Well... Isn't it stable enough? :)

**Comment by jakejackson1** [comment]
Sure is https://github.com/mpdf/mpdf/commit/92200411ef05f0957c7a01e9f9f939bec6b68fdf
