### ISSUE TITLE
CSS 'drop-shadow' is not working

### ISSUE THREAD

**Issue by totoberg123** [mpdf/mpdf#1095]
Hi all,

At this moment I want mpdf to create a PDF-file from a html page. I have done this succesfully, however one thing is not working. It is not displaying the outer shadow of an image.

Example: http://jsfiddle.net/jaq316/EKNtM/

Is there a reason for this not to work, or is there any known workaround?

Edit:
- MPDF 8.0.0
- IIS Server 10
- PHP 7.2.7

**Comment by finwe** [comment]
See https://mpdf.github.io/css-stylesheets/supported-css.html
try box-shadow which should be supported on block elements.

**Comment by totoberg123** [comment]
I have tried the box-shadow on a div.

Random HTML tester result: 
![image](https://user-images.githubusercontent.com/1339475/65602185-bf150580-dfa3-11e9-8cdf-71379a61df42.png)

mPDF result: 
![image](https://user-images.githubusercontent.com/1339475/65602262-e23fb500-dfa3-11e9-9c17-360eed949929.png)

As you can see the 'glow' is only shown on the right side of the box.

CSS: 
`box-shadow: 0px 0px 20px 1px grey;`

**Comment by finwe** [comment]
Create a new issue with bug report, please. Just don't expect this to be fixed any time soon. See https://github.com/mpdf/mpdf/issues/399#issuecomment-509927758

**Comment by totoberg123** [comment]
https://github.com/mpdf/mpdf/issues/1096

**Comment by totoberg123** [comment]
@buzi Unfortunately, no. Check #1096.
