### ISSUE TITLE
Notice 'Undefined index: border_details' (packTableData+collapse+colspan)

### ISSUE THREAD

**Issue by ikeblaster** [mpdf/mpdf#1099]
First of all - **this seems to be fixed in _php74-support_ branch (48bd1322894bfaee1ac0e3ab4e278c0dcf66105d).** Not fixed in development branch.

---

### I found this bug

Combination of:
- `packTableData`
- `table[style="border-collapse: collapse"]`
- `td[colspan]` 

Causes: `Undefined index: border_details` (Mpdf.php:21422).

https://github.com/mpdf/mpdf/blob/ab0662606cc2396015616633946f3b8918d818a7/src/Mpdf.php#L21416-L21426

It's because `$adjc` is `0` and `_unpackCellBorder` then returns `[]`.

PHP 7.4 note: Even with `packTableData=false` it would raise a notice because `$celladj` can be 0. See [RFC](https://wiki.php.net/rfc/notice-for-non-valid-array-container) and [sandboxed case](https://3v4l.org/Qb01s). 

### This is a PHP code snippet I use

```
<?php

$mpdf = new \Mpdf\Mpdf();
$mpdf->packTableData = true;
$mpdf->WriteHTML($html);
```

### This is a HTML/CSS code snippet I use

```
<table style="border-collapse: collapse;">
	<tr>
		<td>col1</td>
		<td>col2</td>
	</tr>
	<tr >
		<td colspan="2">
			
		</td>
	</tr>
</table>
```

**Comment by mshYat** [comment]
Related bug. This html leads to crash:
```
<table><tbody><tr><td style="border-left-color: rgb(207, 207, 207);">test</td></tr></tbody></table>
<table><tbody><tr><td style="border-left-color: rgb(207, 207, 207);">test</td></tr></tbody></table>
```

**Comment by finwe** [comment]
@mshYat Unrelated, different notice. Please create separate issue.

**Comment by TheBnl** [comment]
I experience te same issue with php 7.4 (and higher) and mpdf 8.0.10.
I don't get the notice running php 7.3

**Comment by smirkos** [comment]
i've the same issue with php 7.4 and mpdf 8.0.12

```
1 exception(s):
Exception #0 (Exception): Notice: Trying to access array offset on value of type int in /Users/imac-mirko/Desktop/microfilla_jobs/camac/magento2/vendor/mpdf/mpdf/src/Mpdf.php on line 21441

Exception #0 (Exception): Notice: Trying to access array offset on value of type int in /Users/imac-mirko/Desktop/microfilla_jobs/camac/magento2/vendor/mpdf/mpdf/src/Mpdf.php on line 21441
<pre>#1 Mpdf\Mpdf->_fixTableBorders() called at [vendor/mpdf/mpdf/src/Tag/Table.php:649]
#2 Mpdf\Tag\Table->close() called at [vendor/mpdf/mpdf/src/Tag.php:247]
#3 Mpdf\Tag->CloseTag() called at [vendor/mpdf/mpdf/src/Mpdf.php:13703]
#4 Mpdf\Mpdf->WriteHTML() called at [app/code/Eadesigndev/PdfGeneratorPro/Helper/Variable/Processors/Output.php:186]
```

How can i solve?

**Comment by finwe** [comment]
@smirkos Unrelated, different notice. Please create separate issue.

**Comment by finwe** [comment]
Closing this as it attracts unrelated reports. Create separate issues with complete issue template.
