### ISSUE TITLE
No place to define external directory for graph_cache

### ISSUE THREAD

**Issue by sukhpalsingh** [mpdf/mpdf#11]
Currently paths for temoprary and ttffontdata directory can be defined so that they can be placed outside the library itself for security purpose. This is a nice feature.

However, the path for graph_cache folder is fixed and can not be changed to external directory.
Can this be added as a feature in the same way as the above two folders are defined as follows
define("_MPDF_TEMP_PATH", __DIR__.'/../permitted/mpdf/tmp/');
define("_MPDF_TTFONTDATAPATH", __DIR__.'/../permitted/mpdf/ttfontdata/');

**Comment by danielhjames** [comment]
Hi Sukhpal, 

Seems like JPGRAPH_PATH can also be defined in examples/example_test.php but just as for the variables you mention, there is a fallback in mpdf.php which points back to the mPDF installation directory:

if (!defined('_JPGRAPH_PATH')) define("_JPGRAPH_PATH", _MPDF_PATH.'jpgraph/')

It seems like a good idea to do the same for the graph_cache path, please try modifying graph.php lines 13-16:

if ($handle = opendir(_MPDF_PATH.'graph_cache'))
                while (false !== ($file = readdir($handle))) { 
                if (((filemtime(_MPDF_PATH.'graph_cache/'.$file)+$interval) < time()) && ($file != "..") && ($file != ".")) { 
                        @unlink(_MPDF_PATH.'graph_cache/'.$file);       // mPDF 4.0

and line 231:

$figure_file = "graph_cache/".rand(11111,999999999).".".$img_type;

and if it works OK, please send a pull request.

**Comment by finwe** [comment]
see https://github.com/mpdf/mpdf/issues/56
