### ISSUE TITLE
The class "PDO" is not cloneable.

### ISSUE THREAD

**Issue by moridianmess** [mpdf/mpdf#1109]
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
"mpdf/mpdf": "8.0.0"
"php": "7.2"

### This is a PHP code snippet I use

```
<?php
// Set TOC
$mpdf->TOCpagebreakByArray(array(
	'TOCuseLinking' => 1,
	'toc_preHTML' => $html,
	'resetpagenum' => 1,
	'toc-even-header-name' => 'html_TOCHeader',
	'toc-even-header-value' => 1,
	'toc-odd-header-name' => 'html_TOCHeader',
	'toc-odd-header-value' => 1,
));
```

The fix for this is quite simple, add the following to line 314 of src/TableOfContents.php:
```
$copier->skipUncloneable();
```

so the block should look like this:
```
if (!$this->tocTocPaintBegun) {
	$copier = new DeepCopy(true);
	$copier->skipUncloneable();
	$tocClassClone = $copier->copy($this);
	$tocClassClone->beginTocPaint();
	$tocClassClone->insertTOC();
	$this->_toc = $tocClassClone->_toc;
}
```

Please could this be implemented? I'm currently editing the TableOfContents,php file within my vendor folder, which isn't really best practice.

Thanks.

**Comment by finwe** [comment]
mPDF doesn't use PDO at all. The error is most likely in your part of code.

Feel free to reopen with additional information pointing this is indeed a mPDF issue.

**Comment by brysem** [comment]
I was experiencing the same issue in a project using Laravel, so I will leave my solution here for others looking up the same error.

Many `Model`s in frameworks have a reference to the underlying PDO object. These models are often used in a `View` class which has not been parsed to a string (HTML) yet. 

The solution is to convert your views to a string first. Problem solved.

Example:
```php
$content = (string) view('pdf', $data);
```
