### ISSUE TITLE
Internal links for mpdf

### ISSUE THREAD

**Issue by brittajaison** [mpdf/mpdf#111]
I am trying to create internal links to mpdf. Tried the below one, but it didn't work. Is there any other way to do internal linking within the pdf.  Thanks in advance.
<a name="#demo">Demo</a>
<div name="demo">Content</div>

**Comment by finwe** [comment]
Basic HTML anchors to element names/ids should work - see these [two](https://github.com/mpdf/mpdf/blob/development/examples/example01_basic.php#L30) [lines](https://github.com/mpdf/mpdf/blob/development/examples/example01_basic.php#L5) in basic example file.

**Comment by brittajaison** [comment]
Thanks much! This works !
