### ISSUE TITLE
Division by zero error after generating pdf

### ISSUE THREAD

**Issue by veerajongit** [mpdf/mpdf#1110]
I found a bug where after generating pdf I get this error in the generated pdf

<b>Warning</b>:  Division by zero in <b>vendor/mpdf/mpdf/src/Mpdf.php</b> on line <b>21815</b><br />

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
