### ISSUE TITLE
PHP 7.4 compatibiility

### ISSUE THREAD

**Issue by Eugentis** [mpdf/mpdf#1114]
Hi, I've detected some funny situation with your lib!

### I would like to have this new functionality
I am trying to install your lib and detected that if you have php 7.4 at server it installs mpdf ^6.1.
I suppose it is not correct behavior.

Release of php 7.4 is very soon. Could you fix your requirements?

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
Docker-container with php 7.4 container

**Comment by Eugentis** [comment]
P.S. I understood that it is possible you didn't test it yet with PHP v.7.4. 
But the issue mostly about not correct definition of requirements.

**Comment by Klap-in** [comment]
The development branch has changes for the PHP 7.4. However, it is not yet released.

**Comment by finwe** [comment]
See https://github.com/mpdf/mpdf/issues/1092
