### ISSUE TITLE
Text-shadow and CMYK colors, it just picks the default RGB color

### ISSUE THREAD

**Issue by lexilya** [mpdf/mpdf#1115]
I am running 8.0.3, but this was happening in older releases as well.

There seems to be an issue using CMYK colors with text-shadow.

What I am doing is something like this:

```
.my-h2-class {
  text-shadow: 2px 2px 0px cmyk(91, 79, 62, 97);
}
```

```
<h2 class="my-h2-class">My h2 text</h2>
```

And then build it normally. The cmyk colors work just fine for all other properties (e.g. text colors, gradient backgrounds, etc), but with text-shadow I end up with the default color specified here:

CssManager.php line 1145.
```
$new['col'] = $this->colorConverter->convert('#888888', $this->mpdf->PDFAXwarnings);
```

**Comment by lexilya** [comment]
I figured out that it has to do with spaces in the preg_replace that tries to extract the properties/values at https://github.com/mpdf/mpdf/blob/development/src/CssManager.php#L1121. 

Making the space optional solves the issue.

https://github.com/lexilya/mpdf/commit/c7ed89c9cceeaaaa5e41a59bffcc09e4e7935d13

Forcing no spaces is not an option, as when compiling SASS to CSS, it automatically adds spaces for CMYK values.

**Comment by finwe** [comment]
Fixed, thanks for figuring this out!
