### ISSUE TITLE
Umlauts in upper case are displayed as normal characters

### ISSUE THREAD

**Issue by spoonerWeb** [mpdf/mpdf#1119]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug / would like to have this new functionality

Trying to output upper case umlauts does not work. Lower case works.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

mPDF version: 8.0.3
PHP version: 7.2.22-fpm

### This is a PHP code snippet I use

```
<?php
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('<p>&Auml; &Ouml; does not work</p>');
$mpdf->WriteHTML('<p>&auml; &ouml; does work</p>');
$mpdf->Output('test.pdf', 'D');
exit;
```

### This is a HTML/CSS code snippet I use

I use nothing

**Comment by finwe** [comment]
Unable to reproduce.

![obrazek](https://user-images.githubusercontent.com/195675/68601688-1b28e000-04a5-11ea-95ce-00cd9b44d37d.png)
