### ISSUE TITLE
Which version is compatibile with php 5.2 ?

### ISSUE THREAD

**Issue by realtebo** [mpdf/mpdf#112]
I've an old app on a very old server.

```
# php --version
PHP 5.2.4-2ubuntu5.27 with Suhosin-Patch 0.9.6.2 (cli) (built: Mar 11 2013 14:14:48)
```

Which versione can I use?

**Comment by finwe** [comment]
See https://mpdf.github.io/about-mpdf/requirements-v5.html, you should be able to use any current version including v6.0
