### ISSUE TITLE
PHP7.4 syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by Noaber** [mpdf/mpdf#1138]
When using PHP 7.4  I get a "Message: Array and string offset access syntax with curly braces is deprecated"

Filename: src/Mpdf.php
Line Number: 2214

Seems that **$this->bodyBackgroundColor{0}** is not allowed anymore in PHP 7.4

https://stackoverflow.com/questions/59158548/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated

**Comment by finwe** [comment]
Not really helpful. That issue template is not there for nothing, you know. How do you initialize the Mpdf object? Are you using custom fonts? Can you share a small HTML snippet reproducing this behaviour?

**Comment by finwe** [comment]
Upgrade to 8.0.4, PHP 7.4 is not supported in lower versions.
