### ISSUE TITLE
Position absolute is not working

### ISSUE THREAD

**Issue by sumitof019** [mpdf/mpdf#1139]
Position absolute is not working in mpdf. Please help

<!DOCTYPE html>
<html>
<head>
<title>My Vitality</title>
</head>
<body style="font-family:sans-serif; font-size:13px; color:#3a424d;">
	<div class="warper" style="width:540px; margin:0 auto;">
	<table cellpadding="0" cellspacing="0" align="center"  style="font-family:arial; padding-bottom:0; width:540px;">
		<tr>
			<td>
				
				<table cellpadding="0" cellspacing="0" align="center" style="width:100%; padding:10px 0; background:#e5efed">
					<tr>
						<td style="padding:0 0 0 15px;">
							<img src="logo.png" alt="Aiungo" title="FitzMe" width="130px">
						</td>
						<td style="padding:0 15px; text-align:right;">
							<h1 style="font-size:21px; text-transform:uppercase; font-weight:normal; margin:0;">FITZME HEALTH CHECK</h1>
						</td>
					</tr>
				</table>
				<table cellpadding="0" cellspacing="0" align="center" style="width:100%; padding:10px 0;">
					<tr>
						<td style="padding:0 0 0 20px;">
							<p style="margin:0;">Ivo Mangelschots (IM)</p>
						</td>
						<td style="padding:0 20px; text-align:right;">
							<p style=" font-size:9px; color:#1d1d1b; margin:0;">Testdatum: 11/05/2020</p>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	<div style="width:540px; margin:0 auto;">
		<div style="width:540px; padding:0; background:#b3d9d5">
			<div style="width:255px; padding:15px 0 0 15px;">
				<p style="margin:0 0 20px 0; font-size:8px; text-transform:uppercase;">LEGENDA</p>
				
				<div style="margin:12px 0 25px 0; width:240px; text-align:center; color:#fff; height:20px; border-radius:20px; box-sizing: border-box; line-height:5px;">
					<div style="font-size:6px; line-height:19px; width:47px; height:20px; float:left; background:#e6301d; box-sizing: border-box; border-radius:20px 0 0 20px;">
						Risicovol
					</div>
					<div style="font-size:6px; line-height:19px; width:46px; height:20px; float:left; background:#ea5138; border-left:2px solid #fff; box-sizing: border-box;">
						Waarschuwing
					</div>
					<div style="font-size:6px; line-height:19px; width:46px; height:20px; float:left; background:#f08214; border-left:2px solid #fff; box-sizing: border-box;">
						Aandachtspunt
					</div>
					<div style="font-size:6px; line-height:19px; width:46px; height:20px; float:left; background:#a0c518; border-left:2px solid #fff; box-sizing: border-box;">
						Goed
						<div style="width:18px; height: 21px; margin-top:-36px;position:absolute;left:50px;">
							<div style="width:18px; height: 21px; background-image:url(bubble-grey.png); background-size: 100% 100%; font-size:5px; text-align:center; margin-left:-9px;">
								<div style="font-size:5px; margin-top:0px;">ratio</div>
							</div>
						</div>
					</div>
					<div style="font-size:6px; line-height:19px; width:46px; height:20px; float:left; background:#3fab35; border-left:2px solid #fff; box-sizing: border-box; border-radius:0 20px 20px 0;" >
						Uitstekend
					</div>
				</div>
			</div>
			<div style=" width:240px; padding:15px 15px 0 15px;">
				&nbsp;
			</div>
		</div>
	</div>
</div>
</body>
</html>

This is code

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details. Format your code. Better explain expected and actual result.

**Comment by finwe** [comment]
Also see https://mpdf.github.io/what-else-can-i-do/fixed-position-blocks.html
