### ISSUE TITLE
How to regenerate ttfontdata files ?

### ISSUE THREAD

**Issue by FeIix** [mpdf/mpdf#114]
Hi,
Sorry this is not an issue, I don't know if I can ask this here.

I'm using custom font and had to migrate my website.
There some php files corresponding to fonts, with a $ttffile variable inside.
 This variable contains the old site path.

Can I safely delete these php files ? Will they be regenerated ?
Or should I search&replace the path in all files ?

Thanks

**Comment by finwe** [comment]
Directory `ttfontdata` is a temporary directory and files in it are safe to delete, they will be autogenerated.
