### ISSUE TITLE
Empty page is added after TOCpagebreak <tocpagebreak>

### ISSUE THREAD

**Issue by AjayViknesh** [mpdf/mpdf#1146]
Hi!

I have added `<tocpagebreak>` with 3 Contents in `<tocentry>` but the export is giving me a blank extra page after the Table of Contents.

Table of Contents is the first page in my document.

Is there any options or attribute to specify not to export the extra blank page ?

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
