### ISSUE TITLE
Acrobat Reader DC can't open mpdf output

### ISSUE THREAD

**Issue by akcarlow** [mpdf/mpdf#115]
OS X's Preview opens OK, but the new Acrobat Reader DC gives an error. 

[13.pdf](https://github.com/mpdf/mpdf/files/218939/13.pdf)

![screen shot 2016-04-14 at 11 39 06](https://cloud.githubusercontent.com/assets/18461451/14525541/d6430896-0235-11e6-9f85-41b2ef56b508.png)

**Comment by finwe** [comment]
You have a plain HTML header in the beginning of your binary PDF file. Make sure you do not echo anything outside of mPDF when generating output or use different method of outputting PDF to a file (F output mode, see [Output() method manual page](https://mpdf.github.io/reference/mpdf-functions/output.html))

```
<!DOCTYPE html>
<html>
<head>
	<title>Ballinabranna Water Arrears</title>
	<meta name="generator" content="BBEdit 9.6" />
	<script language="javascript" src="calendar/calendar.js"></script>
	<link href="gws.css" rel="stylesheet" type="text/css">
</head>
<body>
```
