### ISSUE TITLE
Cannot use a pdf with a form as a template

### ISSUE THREAD

**Issue by kade99** [mpdf/mpdf#1167]
### This is a PHP code snippet I use

```
<?php
require 'mpdf/autoload.php';
$pdf = new \Mpdf\Mpdf(['useActiveForms' => true]);
$pdf->AddPage();
$pdf->setSourceFile('test.pdf');
$template = $pdf->importPage(1);
$pdf->useTemplate($template);
$pdf->Image('test.jpg', 100, 200, 150, 260);
$pdf->Output();
?>
```

The test.pdf file that's used as a template contains a form. However after it's used as a template, the output file does not contain form fields, but only the rest of the content.

**Comment by finwe** [comment]
This is the limitation of underlying FPDI library, see https://manuals.setasign.com/fpdi-manual/v2/limitations/
