### ISSUE TITLE
error on line 6394

### ISSUE THREAD

**Issue by TitorovD** [mpdf/mpdf#1169]
**When I try to render a PDF, I got this error:**
PHP Notice:  A non well formed numeric value encountered in ../vendor/mpdf/mpdf/src/Mpdf.php on line 6394,

**These are mPDF and PHP versions I am using**
PHP 7.2.24 with mpdf 7.1.9

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
