### ISSUE TITLE
Generator error - Compress

### ISSUE THREAD

**Issue by Ark-Lab** [mpdf/mpdf#117]
mPDF file generated successfully!
mPDF file size 1,112 kB

Parse error: syntax error, unexpected 'else' (T_ELSE) in C:\xampp\htdocs\reports\mpdf\mpdf.php on line 3052

The line number varies with each new generated file and different checked options.

Environment: Xampp with PHP 7.0.4

**Comment by finwe** [comment]
The compress.php script will eventually be removed, so there are no plans on fixing its output. Please use the entire original mPDF file.
