### ISSUE TITLE
Links not clickable in footers with pages oriented differently

### ISSUE THREAD

**Issue by bradenrayhorn** [mpdf/mpdf#1170]
### I found this bug

Links in a footer are not consistently clickable in the generated PDF in major browsers (tested in Chrome, Firefox, Safari).

This issue appears to occur when there are pages with different orientations.

The links are clickable in a local PDF reader. (I'm using the Preview app on MacOS, but I assume Adobe Acrobat would work as well)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

`PHP version 7.3.12`
`mPDF version 8.0.4`

### This is a PHP code snippet I use

In this example, only one of the links is clickable in major browsers.

```
<?php

$mpdf = new Mpdf([
    'orientation' => 'L',
    'format' => 'Letter-L',
]);

$mpdf->WriteHTML('
<html>
<body>
<htmlpagefooter name="footer" style="display:none">
  <a href="https://google.com" target="_blank">Test Link</a>
</htmlpagefooter>
<sethtmlpagefooter name="footer" value="on" />
</body>
</html>
');

$mpdf->AddPage('P'); // Changing this to a landscape page makes both links clickable

$mpdf->WriteHTML('page 2');
```

**Comment by bradenrayhorn** [comment]
Doing some investigation. It appears that `$this->hPt` is not set correctly for landscape pages when the `Link` function is called.

**Comment by AlbanRicherPro** [comment]
We have the same problem.

Did you find a solution?

At this moment, we only work with 'portrait' pages to not break the links.

**Comment by bradenrayhorn** [comment]
@AlbanRicherPro I never found a great solution. In my specific case, I had one link that was always in a fixed position placed on every page, essentially a footer. What that allowed me to do was position the link manually on each page:

```
$mpdf->Link($xOffset, $yOffset + ($mpdf->CurOrientation == 'P' ? $yOffset : 0), $linkWidth, $linkHeight, $linkUrl);
```

It just took some trial and error to find the appropriate offset values.
