### ISSUE TITLE
Rotate img inside div

### ISSUE THREAD

**Issue by JulioBFG** [mpdf/mpdf#1176]
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mpdf 5.3 php 5.6

### This is a HTML/CSS code snippet I use

```
.image {
transform : rotate(90deg)
}
```

i'm trying to use rotate in a div to make a barcode rotate 90°, but when i make the pdf itself,  it dont rotate, 

i actually just put the <img> into a <div>

![image](https://user-images.githubusercontent.com/36900887/75704919-06ad6500-5c99-11ea-988d-577472d65d67.png)

![image](https://user-images.githubusercontent.com/36900887/75704850-ebdaf080-5c98-11ea-858e-cff54ded0e2c.png)

**Comment by finwe** [comment]
Works for me in th mPDF 8.0.0. Upgrade to a newer version.
