### ISSUE TITLE
mPDF truncates after <: (less than symbol followed by colon)

### ISSUE THREAD

**Issue by oferu** [mpdf/mpdf#1177]
### I found this bug
Bug: mPDF truncates after <: (less than symbol followed by colon)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF 6.1.0
PHP > 7

### This is a PHP code snippet I use
```
<?php
        $mpdf = new mPDF('utf-8');
	$text = "<div>How are you <: I am fine</div>";
        $mpdf->WriteHTML($text);
        $mpdf->Output($file_name, "D");
        exit;
?>
```
Output:
PDF file with content: How are you

"I am fine" or anything following "<:" not shown.

**Comment by ssieb** [comment]
You need to provide more of the PHP than that.  Maybe it was cut off by formatting?  Edit your comment and use the code markup to wrap your code.

**Comment by finwe** [comment]
encode your characters. 

$text = "<div>How are you &lt;: I am fine</div>";

**Comment by oferu** [comment]
Thanks. I added htmlspecialchars().

**Comment by oferu** [comment]
Thank you! A rooky mistake :)
