### ISSUE TITLE
Footer not printed

### ISSUE THREAD

**Issue by Dexus** [mpdf/mpdf#1178]
### I found this bug 

All methods to set Footer will not work. As example https://github.com/mpdf/mpdf-examples/blob/development/example34_invoice_example.php the footer is never printed

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

mpdf 8.0.5; php 7.4.x cli/fpm

### This is a PHP code snippet I use

```
see https://github.com/mpdf/mpdf-examples/blob/development/example34_invoice_example.php
see https://mpdf.github.io/headers-footers/headers-footers.html
```

**Comment by finwe** [comment]
Unable to reproduce. With your PHP and mPDF versions the footer prints just fine. Feel free to reopen with additional information.
