### ISSUE TITLE
:after being ignored ?

### ISSUE THREAD

**Issue by Yamakasi** [mpdf/mpdf#118]
I have some css class which does an :after on a span. This works well in my browser but is ignored when creating my pdf.

Is this known ?

**Comment by blueliquiddesigns** [comment]
Hi,

`:after` isn't supported in mPDF. [See the manual for more details about what is and isn't supported](http://mpdf.github.io/css-stylesheets/supported-css.html).

**Comment by Yamakasi** [comment]
Hi,

OK thanks!
