### ISSUE TITLE
{PAGENO} and {nb} always "1" on header, correct number on footer

### ISSUE THREAD

**Issue by macl** [mpdf/mpdf#1181]
### I found this bug 
I tried to write page numbers on both headers and footers, and it just updates on the footer. I use a simple format: {PAGENO} / {nb} on both places. I'm not sure this is a bug, maybe I'm doing something wrong, but I can't wonder what.

This is the header on page 2 of a 3 pages pdf (and on any other page):

![image](https://user-images.githubusercontent.com/1528824/76681057-e5306f80-65ee-11ea-9010-170b60998fb8.png)

And this is the footer on the same page:

![image](https://user-images.githubusercontent.com/1528824/76681061-01cca780-65ef-11ea-9333-f83998159107.png)

Both blocks are HTML, and set using the only way that worked for me (docs are quite confusing about this):

## Relevant CSS used
```
@page {
  size: 210mm 297mm;
  header: html_quizH;
  footer: html_quizF;
  marks: cross;   
  background-color: white;						
  margin-top: 2.7cm;  
  margin-header: 1mm; 
  margin-footer: 5mm;
}

.questionblock {
	page-break-inside: avoid;
}
```
## PHP Declaration
```
	$header = '<htmlpageheader name="quizH" style="display:none">
				<table width="100%" style="background-color: white; border-bottom: 1px solid #000000; vertical-align: bottom; font-family:
				serif; font-size: 9pt; color: #000088; margin:0; padding: 5pt;"><tr>
					<td width="50%" align="left"><img src="images/'.$logo.'" height="70px" alt="QGT - by MACL" /></td>			
					<td width="50%" align="right" valign="middle">
						<span style="font-size:11pt; color:black;">'.$texto." - Página {PAGENO} / {nb}</span></td>".'
				</tr></table>
				</htmlpageheader>
			';

	$mpdf->DefHTMLHeaderByName('quizH',$header);
	$mpdf->DefHTMLFooterByName('quizF',"<hr>&copy; Miguel Ángel Campos - Página {PAGENO} / {nb}");
```
BTW, I am not using AddPage() or similar, just some CSS to avoid page breaks in certain blocks, which works fine. I just let content flow through pages, expecting the footer behaviour.

Any ideas? Does anyone have a similar problem? I went through the issues, but found nothing like this. 

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF 6.1 running on Apache2.4/PHP 5.2 - Also tested with PHP7.2

**Comment by macl** [comment]
Solved. Seems It wasn't a good idea to use the tag "htmlpageheader" and then declare it by $mpdf->DefHTMLHeaderByName, as it get parsed twice (I cloudn't manage to use it by simply writing the <htmlpageheader> block to the template.

**Comment by finwe** [comment]
Will keep this open for potential future warnings.
