### ISSUE TITLE
"Checked" on checkbox does not work correctly

### ISSUE THREAD

**Issue by Kota-M** [mpdf/mpdf#1183]
I am trying to create a fillable PDF (PDF form), but checkbox does not work correctly.
Could you please help me to make it works?

The problem is that the attribute of "checked" does not work.
I found that it must be checked="checked", but the result is not changed.

PHP: ver 7.4.4
mPDF: ver 8.0.4

```
<?php
$html = '
<body>
	<label for="s44_1"><input type="checkbox" name="s44_1" id="s44_1" value="1" /> 1</label><br />
	<label for="s44_2"><input type="checkbox" name="s44_2" id="s44_2" value="2" /> 2</label><br />
	<label for="s44_3"><input type="checkbox" name="s44_3" id="s44_3" value="3" checked="checked" /> 3</label><br />
	<label for="s44_4"><input type="checkbox" name="s44_4" id="s44_4" value="4" /> 4</label><br />
	<label for="s44_5"><input type="checkbox" name="s44_5" id="s44_5" value="5" /> 5</label>
</body>
</html>
';

//==============================================================
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->useActiveForms = true;
$mpdf->SetTitle("Sample_Fillable");

// OUTPUT
$mpdf->WriteHTML($html);
$mpdf->Output('Sample_Fillable.pdf', 'D');

exit;
?>
```

**Comment by finwe** [comment]
Works for me. Is possibly a lack of support in used PDF reader.

**Comment by Kota-M** [comment]
My PDF reader is Adobe Acrobat Reader DC 20.6.20042.43423.

**Comment by finwe** [comment]
Everything works as expected for me in Acrobat Reader DC with your example code. Can you share your generated PDF?

**Comment by Kota-M** [comment]
Thank you for helping me. Here it is.
[Sample_Fillable-29.pdf](https://github.com/mpdf/mpdf/files/4356950/Sample_Fillable-29.pdf)

**Comment by finwe** [comment]
Share more details about your setup. Your file indeed does not work, but the file I generated with your code sample works as expected.

Also, please generate and share the file with 

```
$mpdf = new \Mpdf\Mpdf([
    'mode' => 'c',
]);
$mpdf->SetCompression(false);
```

**Comment by Kota-M** [comment]
I added that code, but the checkbox is still not checked.
[Sample_Fillable-30.pdf](https://github.com/mpdf/mpdf/files/4359923/Sample_Fillable-30.pdf)

**Comment by finwe** [comment]
You didn't share your whole mPDF settings. You are generating PDF 1.6 instead of default 1.4. Share your entire mPDF settings.

**Comment by Kota-M** [comment]
This is all the code about mPDF setting on this PDF.
There is no change except for the additional code you sent me.

And I have not changed my mPDF settings at all.
Actually I cannot even find where is the config file.

	```
$mpdf = new \Mpdf\Mpdf([
		'mode' => 'c',
	]);
	$mpdf->SetCompression(false);
	$mpdf->useActiveForms = true;
	$mpdf->SetTitle("Sample_Fillable");

```

**Comment by finwe** [comment]
And you have unaltered mPDF 8.4 from packagist? I doubt that and am afraid something smells here - Your generated PDF is version 1.6, unless you set it from outside, mPDF does not by itself.

**Comment by Kota-M** [comment]
Actually I have installed mPDF to another PC, and I copied to here.

In addition, I checked the PDF's version, and it is 1.4.
![20200320](https://user-images.githubusercontent.com/35779299/77179886-8744d180-6a9f-11ea-8698-75f7c0320b56.jpg)

**Comment by finwe** [comment]
The file you posted above is 1.6.

**Comment by Kota-M** [comment]
I have just found that once I save it with Adobe Acrobat DC, the PDF's version is changed from 1.4 to 1.6.

**Comment by finwe** [comment]
Both of them. Also, you didn't answer the question, do you really have an unaltered version of mPDF? I have a reason to believe you don't.

**Comment by finwe** [comment]
Well, that doesn't really help sharing files that have been altered by another program, does it?

**Comment by Kota-M** [comment]
I cannot find "unaltered" in the download page, but I am sure that my mPDF is ver 8.0.4.

**Comment by finwe** [comment]
What download page? There is no official download page, official installation method is via composer.

Install mPDF with composer and try again. The worksforme label stands.

**Comment by Kota-M** [comment]
I have installed mPDF with composer again.
However, the same problem still happens.

**Comment by finwe** [comment]
Shame.

**Comment by shajushahjalal** [comment]
Just Write 
<input type="radio" checked="checked">
This is worked for me.
