### ISSUE TITLE
The encrypted PDF file is very easily deciphered.

### ISSUE THREAD

**Issue by emresaracoglu** [mpdf/mpdf#1184]
With the code below, I encrypt the PDF file with 128 Bit encryption. However, the online decoder sites can be decoded very easily.

`$mpdf->SetProtection(array('copy', 'print-highres'), '', 'test123456&&987%654', 128);`

For example, this website:

[This site](https://smallpdf.com/unlock-pdf)

Is there a 256 or different method?

**Comment by finwe** [comment]
Not with mPDF.
