### ISSUE TITLE
Cropped template example is broken

### ISSUE THREAD

**Issue by JapSeyz** [mpdf/mpdf#1192]
### I found this bug / would like to have this new functionality
The example for cropping a pdf before using it as a page-template is broken, and I can't seem to find the functionality in any of the other methods.
(https://mpdf.github.io/reference/mpdf-functions/usetemplate-v8.html)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
FPDF 8.0.5, MacOS, PHP 7.4.3 (cli)

### This is a PHP code snippet I use

```
<?php
 $mpdf = new \Mpdf\Mpdf();
 $pagecount = $mpdf->setSourceFile(resource_path('samples/original.pdf'));
 $tplId = $mpdf->importPage($pagecount, 50, 50, 100, 100);
 $mpdf->UseTemplate($tplId, '', '', 100, 100);
```

Exception
```
Tests:  1 failed

   InvalidArgumentException 

  Box name is invalid: "50"

  at vendor/setasign/fpdi/src/FpdiTrait.php:248
    244| 
    245|         // for backwards compatibility with FPDI 1
    246|         $box = \ltrim($box, '/');
    247|         if (!PageBoundaries::isValidName($box)) {
  > 248|             throw new \InvalidArgumentException(
    249|                 \sprintf('Box name is invalid: "%s"', $box)
    250|             );
    251|         }
    252| 

      +1 vendor frames 
  2   app/Models/PDF.php:56
      Mpdf\Mpdf::importPage()
```

I get that this is an FPDITrait exception, but it seems mPDF uses it behind the scenes.

**Comment by finwe** [comment]
Try the `useImportedPage` instead of UseTemplate method. Also please file this issue in the [documentation repository](https://github.com/mpdf/mpdf.github.io).

```
<?php
 $mpdf = new \Mpdf\Mpdf();
 $pagecount = $mpdf->setSourceFile(resource_path('samples/original.pdf'));
 $tplId = $mpdf->importPage($pagecount);
 $mpdf->useImportedPage($tplId, 50, 50, 100, 100);
```

**Comment by finwe** [comment]
Hm, that's not it. $mpdf->useTemplate uses useImportedPage internally. Please, share the entire stack trace of the error.

**Comment by finwe** [comment]
You are using incorect parameters in your importPage call. See https://mpdf.github.io/reference/mpdf-functions/importpage-v8.html - there are no boundaries set there. That is what causes the error.

**Comment by JapSeyz** [comment]
> ~Try the `useImportedPage` instead of UseTemplate method. Also please file this issue in the [documentation repository](https://github.com/mpdf/mpdf.github.io).~
> 
> Remove second and further parameter from importPage call. The crop is set in useTemplate call.
> 
> ```
> <?php
>  $mpdf = new \Mpdf\Mpdf();
>  $pagecount = $mpdf->setSourceFile(resource_path('samples/original.pdf'));
>  $tplId = $mpdf->importPage($pagecount);
>  $mpdf->useTemplate($tplId, 50, 50, 100, 100);
> ```
> 
> I've fixed the documentation.

Alright

> ~Try the `useImportedPage` instead of UseTemplate method. Also please file this issue in the [documentation repository](https://github.com/mpdf/mpdf.github.io).~
> 
> Remove second and further parameter from importPage call. The crop is set in useTemplate call.
> 
> ```
> <?php
>  $mpdf = new \Mpdf\Mpdf();
>  $pagecount = $mpdf->setSourceFile(resource_path('samples/original.pdf'));
>  $tplId = $mpdf->importPage($pagecount);
>  $mpdf->useTemplate($tplId, 50, 50, 100, 100);
> ```
> 
> I've fixed the documentation.

Hmm, this seems to just write the entire template at the x/y specified, and then stretching it to fix into width/height, rather than cropping it.

**Comment by finwe** [comment]
This might have changed with FPDI 2: @JanSlabon Would you have an idea, please?

**Comment by JanSlabon** [comment]
That's the issue I described in #480 and also noted in #899. The old implementation was already faulty. After more than a year this is the first report regarding this BC break. I didn't knew that there's a demo for but the current behaviour isn't cropping but simply resizing.

Is this now a required feature or is it only a demo that is not working (anymore)?

It may require simliar methods which are add in FPDF by [this](http://fpdf.org/en/script/script78.php) script. Maybe there are already methods like this available?

**Comment by JapSeyz** [comment]
> That's the issue I described in #480 and also noted in #899. The old implementation was already faulty. After more than a year this is the first report regarding this BC break. I didn't knew that there's a demo for but the current behaviour isn't cropping but simply resizing.
> 
> Is this now a required feature or is it only a demo that is not working (anymore)?
> 
> It may require simliar methods which are add in FPDF by [this](http://fpdf.org/en/script/script78.php) script. Maybe there are already methods like this available?

I believe that by using the script linked, it will include the full PDF, but only display part of it. In my case, I need to split the same PDF up into three parts of a new PDF. This would cause the filesize to increase by 300%.

I guess clipping and cropping are two different things, I just thought the old functionality was to actually crop?

**Comment by JanSlabon** [comment]
It was called "cropping" but under the hood it was the same as clipping... the whole page was imported throughout. The page bounding box was simply overwritten/manually defined. But this logic wasn't relative to an existing boundary box or page rotation which could have resulted in unexpected or wrong results. Using such clipping logic is more easier than calculating all these offsets/rotations.

**Comment by JapSeyz** [comment]
> It was called "cropping" but under the hood it was the same as clipping... the whole page was imported throughout. The page bounding box was simply overwritten/manually defined. But this logic wasn't relative to an existing boundary box or page rotation which could have resulted in unexpected or wrong results. Using such clipping logic is more easier than calculating all these offsets/rotations.

Alright, I am better off creating an image from the sections of the PDF I need, and then importing the images.

I've just had some issues w/ maintaining the correct colorspace that way, and was hoping to maintain it correctly if the entire image-step was skipped.

**Comment by JanSlabon** [comment]
I'm not really sure what you want to do: Do you need to create 3 different documents displaying only a part of one existing page? Or do you need to create one document with 3 pages where each page displays a part of an existing page? In the first version you will end up in 3 documents including all informations of the imported page. The later one, will only have the information of the imported page once.

**Comment by iMusicJJ** [comment]
> I'm not really sure what you want to do: Do you need to create 3 different documents displaying only a part of one existing page? Or do you need to create one document with 3 pages where each page displays a part of an existing page? In the first version you will end up in 3 documents including all informations of the imported page. The later one, will only have the information of the imported page once.

So this exact use case, is taking one existing single page pdf, which had 3 sections that I want to distance from each other.

So I want to use section a, b, c from the same imported page, but in different locations onthe new mpdf

**Comment by JapSeyz** [comment]
So this exact use case, is taking one existing single page pdf, which had 3 sections that I want to distance from each other.
So I want to use section a, b, c from the same imported page, but in different locations onthe new mpdf

**Comment by JanSlabon** [comment]
This will not increase the size by 300% but it is the same page that is simply reused. Something simliar to the linked [script](http://fpdf.org/en/script/script78.php) should do the job.
