### ISSUE TITLE
Mpdf - undeclared property ktForms

### ISSUE THREAD

**Issue by jeromeurban** [mpdf/mpdf#1195]
I have got this error :
```
Cannot read an undeclared property Mpdf\Mpdf::$ktForms
vendor/mpdf/mpdf/src/Form.php (line 1197)
```

Context : Symfony 3.4 Mpdf 8.0.5

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
