### ISSUE TITLE
$headerpgwidth is not defined

### ISSUE THREAD

**Issue by lekoala** [mpdf/mpdf#1198]
when using printers_info : true, there is an undefined variable

https://github.com/mpdf/mpdf/blob/3cb9ee18f2e9c51467c09bc650ede31fd4765f6c/src/Mpdf.php#L12890

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
