### ISSUE TITLE
$headerpgwidth is never defined

### ISSUE THREAD

**Issue by lekoala** [mpdf/mpdf#1199]
### I found this bug

when using printers_info : true, there is an undefined variable : $headerpgwidth.

it's easy to check: search for $headerpgwidth in source code, you only find this line:
https://github.com/mpdf/mpdf/blob/3cb9ee18f2e9c51467c09bc650ede31fd4765f6c/src/Mpdf.php#L12890

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

php 7.3, mpdf v8.0.5

### This is a PHP code snippet I use

```
<?php
  $mpdf = new Mpdf([
                'printers_info' => true,
            ]);
            $mpdf->WriteHTML('some html');
            $mpdf->Output();
?>

```

**Comment by finwe** [comment]
Thanks for reporting!
