### ISSUE TITLE
MPDF not taking stylesheet

### ISSUE THREAD

**Issue by zhampu** [mpdf/mpdf#1202]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug / would like to have this new functionality
based on [this example](https://mpdf.github.io/real-life-examples/pdf-from-every-page-of-website.html) I will like to create a PDF from every page of my site.
Im having no luck at getting my CSS stylesheet or font to work.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
Kirby 3.x
Plugin creator
### This is a PHP code snippet I use

```
<?php

use Mpdf\Mpdf;
@include_once __DIR__ . '/vendor/autoload.php';
Kirby::plugin('getkirby/pluginkit', [
    'routes' => [
        [
            'pattern' => 'en/makepdf',
            'action' => function () {
                $url = urldecode($_REQUEST['url']);
                if (count($_POST) > 0) {
                    $ch = curl_init($url);
                    curl_setopt($ch, CURLOPT_HEADER, 0);
                    curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1 );
                    foreach($_POST as $name => $post) {
                        $formvars = array($name => $post . " \n");
                    }
                    curl_setopt($ch, CURLOPT_POSTFIELDS, $formvars);
                    $html = curl_exec($ch);
                    curl_close($ch);

                } elseif (ini_get('allow_url_fopen')) {
                    $html = file_get_contents($url);

                } else {
                    $ch = curl_init($url);
                    curl_setopt($ch, CURLOPT_HEADER, 0);
                    curl_setopt ( $ch , CURLOPT_RETURNTRANSFER , 1 );
                    $html = curl_exec($ch);
                    curl_close($ch);
                }
                $mpdf = new \Mpdf\Mpdf(['debug' => true]);
                $mpdf->CSSselectMedia='mpdf'; // assuming you used this in the document header
                $mpdf->setBasePath($url);
                $mpdf->WriteHTML($html);
                $mpdf->Output();
            }
        ]
    ]
]);


```

### This is a HTML/CSS code snippet I use

```
<?= css(['assets/css/style.css', '@auto']) ?>
    <?= css(['assets/css/responsive.css', '@auto']) ?>
    <?= css('assets/css/print.css', ['media' => 'mpdf']) ?>
```

**Comment by ssieb** [comment]
You need to explain what the problem is more specifically.  You also need to include the resulting html and css data reduced to the minimum required to reproduce the issue.

**Comment by finwe** [comment]
Please note that the Issue tracker serves mainly as a place to report bugs and request new features as noted in [Contributing guidelines](https://raw.githubusercontent.com/mpdf/mpdf/development/.github/CONTRIBUTING.md). Please do not abuse it as a general questions or troubleshooting location.
