### ISSUE TITLE
Undefined offset: 1 in ..../mpdf/src/Tag/BlockTag.php on line 176

### ISSUE THREAD

**Issue by thomstark** [mpdf/mpdf#1208]
I'm getting the above notice referring to this line of BlockTag.php:

`switch ($this->mpdf->listtype[$this->mpdf->listlvl]) {`

Not sure what's triggering it. There are hundreds of pdf templates on our production server and we have several thousand customers, so haven't pinpointed it yet.

**Comment by finwe** [comment]
Not really helpful. That issue template is not there for nothing, you know. How do you initialize the Mpdf object? Are you using custom fonts? Share a small HTML snippet reproducing this behaviour.

**Comment by thomstark** [comment]
Clearly the issue is the code isn't checking to see if the index is set before it references the index. It's not a complicated problem. 

I already stated that I do not know how to reproduce the behavior. We have thousands of users and several hundred pdf templates. I see the notice in the log, but I don't know which template triggered it on which site under what conditions. 

The point is the code isn't checking if the index exists. It simply assumes it's valid. 

No I'm not using custom fonts.

**Comment by finwe** [comment]
It's not a complicated problem. But I'd rather not just throw an isset condition around a code block unless I understand what went wrong and where and unless I know there is no better way of solving this.

Feel free to reopen when you find out how to reproduce this. Be sure to add additional details along with the HTML/PHP sample: mpdf version, at least.

**Comment by thomstark** [comment]
It is impossible for me to reproduce the issue excepting I win the lottery.  You can be more helpful than this if you choose to. 

Version 8.0.5.
PHP 7.4.4.

**Comment by finwe** [comment]
No, I cannot be helpful without means to reproduce this issue. And when I cannot reproduce the issue, I cannot fix it properly. Therefore the issue does not make much sense open.

**Comment by thomstark** [comment]
A cursory review of lines 139-176 of BlockTag.php indicate to me that an orpahned LI tag would be trying to access `$this->mpdf->listtype[1]` but `$this->mpdf->listtype[1]` is only set if there's a UL or OL (lines 139-40, 148, 150, 153, 155). So an orphaned LI would see `$this->mpdf->listlvl` iterated to "1" on line 164 without `$this->mpdf->listtype[1]` ever having been set. Line 176 therefore references an index that doesn't exist. 

That's just on a logical reading.

**Comment by thomstark** [comment]
I mean your comment on line 163 flat out says you're iterating listlvl in order to mitigate malformed html. But your solution just creates the notice referenced at the top.

**Comment by ecrode** [comment]
Run into this issue, besides the PHP notice(s), the PDF generated looks on par with what crome would render. I've simply fixed the issue with adding suppressor @ within the line 178:

`switch (@$this->mpdf->listtype[$this->mpdf->listlvl]) {`
