### ISSUE TITLE
Need for custom font data

### ISSUE THREAD

**Issue by georgetanasa** [mpdf/mpdf#121]
Hello,

Can you tell me when this commit will be merged into the master branch?
https://github.com/mpdf/mpdf/commit/eb1d4de1f2330f398c4d05f39dfbf87f2105c99e

I really need this feature for my project, but is still in the development branch.

Thank you!

**Comment by finwe** [comment]
Hi, I hope I will get to release the 6.1 version until end of April.

**Comment by georgetanasa** [comment]
thank you!
