### ISSUE TITLE
Problem installing mpdf with php 7.4.3

### ISSUE THREAD

**Issue by kolorete78** [mpdf/mpdf#1210]
I found a bug installing mpdf via composer with php 7.4.3

`pablo@rafiki:/var/www/html/fenix$ composer require mpdf/mpdf
Using version ^8.0 for mpdf/mpdf
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mpdf/mpdf v8.0.3 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v8.0.2 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v8.0.1 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - mpdf/mpdf v8.0.0 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.3) does not satisfy that requirement.
    - Conclusion: don't install mpdf/mpdf v8.0.5
    - Conclusion: don't install setasign/fpdi v2.3.3
    - Installation request for mpdf/mpdf ^8.0 -> satisfiable by mpdf/mpdf[v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.0.5].
    - Conclusion: remove setasign/fpdi 1.6.2
    - mpdf/mpdf v8.0.4 requires setasign/fpdi ^2.1 -> satisfiable by setasign/fpdi[v2.1.0, v2.1.1, v2.2.0, v2.3.0, v2.3.1, v2.3.2, v2.3.3].
    - Can only install one of: setasign/fpdi[v2.1.0, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.1.1, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.2.0, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.3.0, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.3.1, 1.6.2].
    - Can only install one of: setasign/fpdi[v2.3.2, 1.6.2].
    - Installation request for setasign/fpdi (installed at 1.6.2) -> satisfiable by setasign/fpdi[1.6.2].

Installation failed, deleting ./composer.json.
`

**Comment by tsdogs** [comment]
Yes, please do a new release, as commit has already been done 5 months ago.
