### ISSUE TITLE
mpdf is trimming values

### ISSUE THREAD

**Issue by ebofi** [mpdf/mpdf#1214]
Hi ,

We are using the MPDF to create a PDF

`<?php
$orderid = $_GET['id'];

require_once __DIR__ . '/vendor/autoload.php';
//$mpdf = new \Mpdf\Mpdf();

$mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8', 'format' => [80, 250]]);
//$mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8', 'format' => [250, 800]]);

$mpdf->SetDisplayMode('real');

$mpdf->AddPage('P','','','','',1,7,1,'','','');
$FinalURL = 'http://oursite.com/gprint/Print?id='.$orderid.'&backend=true';
//$url = $_GET['url']; // http://example.com/
$url = $FinalURL ;
$html = file_get_contents($url);
//echo $html;
$mpdf->WriteHTML($html);
$mpdf->Output();
`

Above $FinalPage is loading a HTML Page from a external website, all works good expect. Below part.

**Actually Results**
<img src="https://i.imgur.com/EjxeW7a.png">

**CODE RESPONSIBLE FOR THIS CLASS**
`
		     <div class="item-order-list item-row"><div class="a">1</div><div class="b">Tandoori Chicken(Quarter)<p class="uk-text-small"><span class="base-price">Rs.95</span></p></div><div class="manage"><div class="c"></div><div class="d">Rs.95</div></div><div class="clear"></div></div><div class="item-order-list item-row"><div class="a">1</div><div class="b">Chicken 65(8 Pcs)<p class="uk-text-small"><span class="base-price">Rs.170</span></p></div><div class="manage"><div class="c"></div><div class="d">Rs.170</div></div><div class="clear"></div></div><div class="item-order-list item-row"><div class="a">1</div><div class="b">Singapore Non-veg Fried Rice<p class="uk-text-small"><span class="base-price">Rs.0</span></p></div><div class="manage"><div class="c"></div><div class="d">Rs.0</div></div><div class="clear"></div><div class="a"></div><div class="b uk-text-success">Rice</div><div class="clear"></div><div class="a">1x</div><div class="b uk-text-muted">150 Chicken</div><div class="manage"><div class="d">Rs.150</div></div><div class="clear"></div></div><div class="summary-wrap"><div class="row"><div class="col-md-6 col-xs-6 text-right ">Sub Total</div><div class="col-md-6 col-xs-6 text-right cart_subtotal">Rs.415</div></div><div class="row"><div class="col-md-6 col-xs-6 text-right ">Delivery Fee</div><div class="col-md-6 col-xs-6 text-right ">Rs.0</div></div><div class="row cart_total_wrap bold"><div class="col-md-6 col-xs-6  text-right">Total</div><div class="col-md-6 col-xs-6  text-right cart_total">Rs.415</div></div><input type="hidden" value="415" name="subtotal_order" id="subtotal_order"><input type="hidden" value="415" name="subtotal_order2" id="subtotal_order2"><input type="hidden" value="" name="subtotal_extra_charge" id="subtotal_extra_charge">		  
		   </div>
		  `

**Expected Result**
<img src="https://i.imgur.com/LpIYKmh.png">

The HTML PAGE loading to variable $FinalPage

http://test.gangiz.com/gprint/Print?id=532&backend=true

**Comment by ebofi** [comment]
Hi,

Upon further investigation i found that only digits or alphabets of length max 3 is taken all other is broken to next line .

Example if the amount is $5000. then the MDF fill show only $50 and on next 
line 00

If i remove the $ from the value then the MDF will show 500 and keep the balance on next line as 0

**Comment by finwe** [comment]
If you try to squeeze too long text to too narrow element, it is broken to multiple lines. This is not an issue of mPDF. Look for line-breaking properties of CSS and fiddle with those.

**Comment by ebofi** [comment]
> If you try to squeeze too long text to too narrow element, it is broken to multiple lines. This is not an issue of mPDF. Look for line-breaking properties of CSS and fiddle with those.
@finwe 
Hi,

So you are saying that if we reduce the size of a element to too small it will.break to two lines.?

**Comment by ebofi** [comment]
Fixed @finwe  Thanks
