### ISSUE TITLE
Cache.php / clearOld cleaning up global tempDir

### ISSUE THREAD

**Issue by jfiala** [mpdf/mpdf#1215]
Cache.php clearOld is currently cleaning up all directories/files in the tempDir.
If mpdf is using the global tempdir (/tmp) this will clean up files of any other application using the global tempdir.

Error message if Mpdf is trying to clean up a file of another application:
unlink(/tmp/...): Operation not permitted
Cache.php: 95

I assume it is suggested to use a a dedicated mpdf tempDir per webserver?
(if yes, that could be added to the docs - https://mpdf.github.io/installation-setup/folders-for-temporary-files.html).

Suggestions for improvements:
* For a shared (/tmp) pattern it would be great if mpdf is doing the housekeeping only for directories it creates itself (like ttfontdata).

* Additionally, it would it be helpful to add an option to turn off the Cache housekeeping completely?

* clearOld() routine could be using a semaphore to support parallel invocations

**Comment by finwe** [comment]
Closing with a12491d

**Comment by jfiala** [comment]
Great, thx alot!
