### ISSUE TITLE
A PHP Error was encountered Severity: Warning  Message: A non-numeric value encountered  Filename: mpdf/mpdf.php  Line Number: 32512

### ISSUE THREAD

**Issue by minitrouble** [mpdf/mpdf#1223]
I changed  my old mpdf version to mpdf 5.7 from `https://github.com/kbs1/mpdf-5.7-php7` still it doesnt work and gives the above error 
can anyone help me please 
m using php 7.2.6

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by finwe** [comment]
- this is not a support channel for external mPDF forks
- mPDF 5.7 does not support PHP 7.2
- upgrade to newer mPDF using composer
- see support table at https://github.com/mpdf/mpdf#php-versions-and-extensions

**Comment by didik08** [comment]
I have php version 7.1.33 and I'm using mpdf 5.7
I have the same issue ..with php error on mpdf.php line 32511
Any solution for that ? 🙂
