### ISSUE TITLE
Error parsing temporary file  created with GD library to parse PNG image

### ISSUE THREAD

**Issue by DarkRiDDeR** [mpdf/mpdf#1224]
Hello. I have a problem:

```
[Mpdf\MpdfImageException] E_ERROR
Error parsing temporary file (/tmp/mpdf//_tempImgPNG6e026e50552771f4883cbab954709d425027.png) created with GD library to parse PNG image (img/top-bg.png) (0)
/var/www/bitrix/local/vendor/mpdf/mpdf/src/Image/ImageProcessor.php:1409
#0: Mpdf\Image\ImageProcessor->imageError
	/var/www/bitrix/local/vendor/mpdf/mpdf/src/Image/ImageProcessor.php:763
#1: Mpdf\Image\ImageProcessor->getImage
	/var/www/bitrix/local/vendor/mpdf/mpdf/src/Mpdf.php:8716
#2: Mpdf\Mpdf->Image
	/var/www/bitrix/local/vendor/mpdf/mpdf/src/Mpdf.php:2158
#3: Mpdf\Mpdf->SetBackground
	/var/www/bitrix/local/vendor/mpdf/mpdf/src/Tag/BlockTag.php:770
#4: Mpdf\Tag\BlockTag->open
	/var/www/bitrix/local/vendor/mpdf/mpdf/src/Tag.php:243
#5: Mpdf\Tag->OpenTag
	/var/www/bitrix/local/vendor/mpdf/mpdf/src/Mpdf.php:13628
```

mpdf: 8.0.4
PHP 7.4.5

The problem is most likely associated with the new version of php, since when you use 7.4.0, then everything works.

**Comment by finwe** [comment]
Share the code and assets to allow to reproduce the issue.

**Comment by DarkRiDDeR** [comment]
example bug in docker environment:
https://github.com/DarkRiDDeR/mpdf-bug
The error occurs when the default is php:
```mbstring.func_overload = 2```


In nginx the paranemets "mbstring.func_overload"   is overridden:
```
location = /test_bug.php {
     ...
    fastcgi_param	PHP_ADMIN_VALUE	"mbstring.func_overload = 0;";
}
``

**Comment by finwe** [comment]
This seems like a PHP/environment related error rather than mPDF issue. Solution? Use lower PHP version.

**Comment by DarkRiDDeR** [comment]
The problem with PHP from the repository from Ondřej Surý. It shows on different versions. I checked on the official docker container, everything is fine there https://hub.docker.com/_/php

**Comment by finwe** [comment]
I have the same version from the same repository outside Docker locally and I am not experiencing any issues with your example code.

**Comment by DarkRiDDeR** [comment]
An error occurs when overriding mbstring.func_overload in nginx with PHP from the repository from Ondřej Surý.  At least when I installed the php from the official docker, then there was no such error
