### ISSUE TITLE
mPDF PDF/A file size thirty times as large as same content in e.g. MS Word PDF/A

### ISSUE THREAD

**Issue by cleeev** [mpdf/mpdf#1225]
### I found this bug / would like to have this new functionality
When creating a simple PDF with only one word in it, and adding another word in bold, the file generated by mPDF has a file size of 754 KiB. Generating a document with the same contents with e.g. MS Word leads to a PDF with a file size of 28 KiB. In other words, the content-wise same PDF is almost 30 times as large when generated with mPDF.
I suspect a font subsetting issue, as adding more words (with different characters) only leads to a small increase in file size for the mPDF PDF/A file.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF v8.0.5
PHP Version 7.4.2
Apache

### This is a PHP code snippet I use

```
<?php
$mpdf = new Mpdf([
	'mode' => 'utf-8',
	'format' => 'A4',
	'orientation' => 'P',
	'autoPageBreak' => true,
	'tempDir' => ...,
	'PDFA' => true,
	'exposeVersion' => false,
	'percentSubset' => 100,
	'defaultfooterline' => 0,
	'defaultfooterfontstyle' => 'B',
	'default_font' => 'dejavusans',
	'default_font_size' => 11,
]);
$mpdf->SetFooter('{PAGENO}/{nbpg}');
$mpdf->WriteHTML('Test', \Mpdf\HTMLParserMode::HTML_BODY);
$mpdf->Output('', \Mpdf\Output\Destination::INLINE);
```

PDF Files:
[PDF generated by mPDF 754 KiB](https://github.com/mpdf/mpdf/files/4656776/download.pdf)
[PDF generated by MS Word 28 KiB](https://github.com/mpdf/mpdf/files/4656799/MSWord.pdf)

**Comment by jakejackson1** [comment]
Thanks for providing those samples.

mPDF can only generate PDF version 1.4 compatible documents, while MSWord can generate 1.7 compatible documents which uses better compression techniques. 

This isn't a bug. Just lack of a feature.
