### ISSUE TITLE
mpdf 6.0 - Notice: Undefined offset: 0 in /...../mpdf_bug/mpdf_6.0/mpdf.php on line 7224

### ISSUE THREAD

**Issue by stosef** [mpdf/mpdf#123]
MPDF doesn't render my HTML Code correctly and I get a lot of notices.
I have attached the code that is problematic, please look into content.html for comments  
[mpdf_bug.tar.gz](https://github.com/mpdf/mpdf/files/238572/mpdf_bug.tar.gz)

**Comment by stosef** [comment]
Same with Mpdf 6.1

**Comment by stosef** [comment]
Well. I work too much :-) Error was in my html code. I mixed up some <tr>, <td> and <table> tags

**Comment by finwe** [comment]
Glad you worked it out. Please note that possibly until next major version it is not entirely safe (for the sake of generated notices) to change error reporting after including mPDF.
