### ISSUE TITLE
MPDF is not accepting my css file

### ISSUE THREAD

**Issue by civram00** [mpdf/mpdf#1231]
i just recently experienced this error while converting a HTML file to PDF. im suspecting that MPDF is not accepting my css file, can someone help me with this??
![image](https://user-images.githubusercontent.com/51841380/83242704-6a2f2c00-a1cf-11ea-8d0a-ddd9820817eb.png)

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
