### ISSUE TITLE
"ruby/rt/rb" characters

### ISSUE THREAD

**Issue by kanujbhatnagar** [mpdf/mpdf#1234]
### I found this bug / would like to have this new functionality
Does mPDF support these characters (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rt) in the PDF? Attaching sample code below, which generates these characters inline, instead of on top, like HTML does.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
php: 7.1
mPDF: 8.0.x 
### This is a PHP code snippet I use

```
<?php
$pdf = new \Mpdf\Mpdf();
$pdf->WriteHTML(file_get_contents("sample.html"));
$pdf->Output();

```

### This is a HTML/CSS code snippet I use

```
<html lang="en" class=""><head>
<meta charset="UTF-8">
<title>ruby/rt/rb</title>
</head>
<body>
<ruby>
漢 <rt>Kan</rt>
字 <rt>ji</rt>
</ruby>
</body></html>
```

**Comment by kanujbhatnagar** [comment]
[mpdf.pdf](https://github.com/mpdf/mpdf/files/4709889/mpdf.pdf)

Sample PDF generated from mPDF.

**Comment by finwe** [comment]
No, it does not.
