### ISSUE TITLE
Add new config variable curlUserAgent

### ISSUE THREAD

**Issue by pdscopes** [mpdf/mpdf#1242]
### I would like to have this new functionality
The ability to set the user agent used by `src/RemoteContentFetcher.php:34`.  I would imagine that it would continue to default to the current value of `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:13.0) Gecko/20100101 Firefox/13.0.1` but this could be overridden by using a new config variable called `curlUserAgent`. The end result would be:

```php
    $this->logger->debug(sprintf('Fetching (cURL) content of remote URL "%s"', $url), ['context' => LogContext::REMOTE_CONTENT]);

    $ch = curl_init($url);

    curl_setopt($ch, CURLOPT_USERAGENT, $this->mpdf->curlUserAgent);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_NOBODY, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $this->mpdf->curlTimeout);
```

The reason is that some remote servers throttled/block requests based on User Agent. Specifically, https://www.staples.co.uk. This would allow me to create a work around.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
I'm using mPDF v8.0.5 and PHP 7.3.15

**Comment by finwe** [comment]
This is already solved by https://github.com/mpdf/mpdf/pull/1229. Use dev-development until a new version is released.

**Comment by pdscopes** [comment]
That is literally what I was looking for, sorry I missed that in my issue search.

**Comment by finwe** [comment]
It's OK, it is just a few days old and not released yet :)
