### ISSUE TITLE
Add htaccess password support (code suggestion)

### ISSUE THREAD

**Issue by mangopulp** [mpdf/mpdf#1244]
I have some image requests which need user and password (.htaccess) to get access. I used the method "$mpdf->setBasePath(https://user:pass@domain.tld)" to set the user and password. I wonderd why it does not work. I got the follwing error message.

> Error parsing image file - image type not recognised, and not supported by GD imagecreate 

 I found, that user and password information are ignored in method "GetFullPath" of file "/mpdf/src/Mpdf.php". In the elseif section "// It is a local link" The path is generated without respecting user and password. It would be nice to include the following code suggestion to include user and password in the generated path.

```
 		} elseif ((strpos($path, ":/") === false || strpos($path, ":/") > 10) && !is_file($path)) { // It is a local link

			if (substr($path, 0, 1) == "/") {

				$tr = parse_url($basepath);

				// mPDF 5.7.2
				$root = '';
				if (!empty($tr['scheme'])) {
					$root .= $tr['scheme'] . '://';
				}

				/* ¯\/¯ Include user and password if set ¯\/¯  */
				if (!empty($tr['user']) && !empty($tr['pass'])) {
					$root .= $tr['user'] . ':' . $tr['pass'] . '@';
				}
				/* _/\_ Include user and password if set _/\_ */

				$root .= isset($tr['host']) ? $tr['host'] : '';
				$root .= ((isset($tr['port']) && $tr['port']) ? (':' . $tr['port']) : ''); // mPDF 5.7.3

				$path = $root . $path;

			} else {
				$path = $basepath . $path;
			}
		}
```

Thanks and have a nice day

**Comment by finwe** [comment]
See also https://github.com/mpdf/mpdf/issues/868

**Comment by jakejackson1** [comment]
You can also use absolute paths to images instead of URLs. It'll be faster to render, and bypass the password protection you've in place.

**Comment by mangopulp** [comment]
Thank you @finwe and @jakejackson1 for your feedback! The problem is, that the image resources are located on a different server. I think about a solution copying all resources to the server where the pdf generation happens and keep them synchronised. I did some tests. With "$mpdf->setBasePath()" I only can set an URL and no web root path fragment. Or do I have to prefix all the image-src with the web root path in the html like this?

> Example: /web/root/path + /images/image-1.jpg

Set "$mpdf->setBasePath('/web/root/path')" does not work. Is there an other function to set it? I could not find in the documentation. Prexfixing the local absoluet server path to each resource in the html would be possible but laborious and not that elegant : )

Thank you!!!

**Comment by finwe** [comment]
The thing is that the base path is applied only to local paths. When using http-based srcs for images, you need to specify the full path in the attribute as you would normally do in a HTML page. Especially when the sources are on a different host.

    When you do <img src="https://user:pass@domain.tld/image.png">, mPDF will load the external resource correctly via cURL.

I am going to close this as trying to solving nonexisting/unrelated issues.

**Comment by finwe** [comment]
I'd very much like to replace/simplify the basepath magic in future versions, see the mentioned issue above.
