### ISSUE TITLE
Undefined offset at page-break-inside (PHP 7.4)

### ISSUE THREAD

**Issue by itrack** [mpdf/mpdf#1245]
When I use **style="page-break-inside:avoid**" the following error is displayed **Undefined offset: 2** at **mpdf/mpdf/src/Writer/BaseWriter.php:246**

<img width="866" alt="Screenshot 2020-06-17 at 08 52 08" src="https://user-images.githubusercontent.com/2368391/84860998-cbcd1280-b078-11ea-988e-c5893fb4335d.png">

Environment:
**PHP 7.4**

**Comment by finwe** [comment]
Not really helpful. Add *your textual* code sample to allow us to reproduce the issue.

**Comment by itrack** [comment]
Hi,
I managed to replicate the bug:

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML("
<html>
<head>
    <style>
        .test-break {
          page-break-inside: avoid;
        }

        .test-float {
          float:left;
        }
    </style>
</head>
<body>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vehicula elementum velit, feugiat hendrerit nulla eleifend ut. Pellentesque et convallis enim. Quisque bibendum libero vitae ligula tincidunt, eu varius augue tincidunt. Aenean nec lacus massa. Morbi ac ante vehicula, ultricies nulla eu, lacinia odio. Integer sit amet luctus ex, in maximus nibh. Aliquam nec lorem erat. Cras pellentesque, diam non suscipit feugiat, sem tellus tincidunt sapien, ut molestie diam nisi eget sapien. Suspendisse elementum iaculis scelerisque. Proin ac mi eu orci tempus rutrum. Nulla tempus tincidunt tempus. Proin at gravida diam. Ut tristique sem eu convallis vestibulum. Cras gravida ullamcorper sem quis pulvinar. Aliquam ac convallis elit, a accumsan urna. Morbi et metus nec quam pellentesque sagittis id suscipit tellus.
    Maecenas vitae risus purus. Ut a interdum libero, bibendum aliquam turpis. Cras malesuada semper neque vel auctor. Quisque et neque non sem tempus tempus. Integer aliquam mollis urna, pretium ullamcorper tellus facilisis in. Curabitur massa tortor, ullamcorper eget condimentum sed, ultricies non lacus. Mauris sit amet nisl tincidunt, tristique magna quis, blandit elit. Sed id auctor nunc. Phasellus vel auctor libero. Sed dignissim augue eget enim scelerisque, sit amet mattis urna tempor. In nec elit sapien. Pellentesque vitae ex nunc. Mauris tempus iaculis ipsum.
    Sed eu elit luctus, euismod massa non, laoreet lorem. Maecenas facilisis viverra metus ut scelerisque. Proin quis commodo urna. Integer a quam id lacus pretium convallis. Proin venenatis, augue id gravida tempor, urna magna feugiat odio, vel laoreet magna ante eu purus. Fusce eget viverra nibh. Sed varius nisl nunc, vel rhoncus sapien convallis nec. Ut et justo volutpat, feugiat sem et, auctor urna. Aenean quis metus at lacus aliquam euismod in sit amet sem. Aenean feugiat porta odio, quis condimentum leo sollicitudin sed. Duis consectetur est nec arcu blandit vehicula. Morbi sit amet feugiat odio, in viverra felis. Integer nec aliquet urna, vitae rutrum magna. Praesent egestas blandit ex, in aliquam nisl tristique at. Suspendisse et nunc nec lacus consectetur gravida. Nunc tristique diam augue, id bibendum justo laoreet eget.
    Pellentesque gravida blandit purus. Aliquam nec elementum turpis, sed vehicula nisl. Curabitur cursus urna eu odio varius imperdiet. Aliquam in consectetur enim. Aliquam mi lectus, accumsan in ligula nec, commodo vehicula quam. Curabitur bibendum ipsum ante, a malesuada sem mollis nec. Pellentesque eget placerat urna, eu convallis dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas nec tellus arcu. Etiam convallis dapibus vestibulum.
    Vestibulum maximus ut est id feugiat. Maecenas scelerisque neque at tellus varius dapibus. In tellus urna, lobortis at arcu tempus, blandit interdum felis. Integer suscipit sed nulla vitae porta. Integer sodales justo sit amet enim placerat vulputate. Pellentesque quis dictum nulla, fermentum elementum elit. Sed ac suscipit risus. Curabitur ac elementum sapien, ut facilisis est.
    Nulla nisi tortor, malesuada vitae odio at, placerat aliquam felis. Quisque molestie blandit viverra. Donec laoreet faucibus nibh, ac efficitur urna placerat vel. Sed ut congue metus. Pellentesque sit amet ante sit amet nunc feugiat pharetra. Ut sapien tortor, placerat vitae odio nec, vehicula fermentum odio. Nulla a maximus orci. Ut id facilisis lacus, in suscipit enim. Proin ultricies sed eros eu efficitur. In elit elit, finibus in pretium ac, rutrum vel erat. Aliquam erat volutpat. Maecenas dignissim massa nisl. Duis eget sem gravida, ornare lorem in, rhoncus diam. Fusce tincidunt facilisis risus, eget ultrices est vehicula iaculis.
    Vestibulum maximus ut est id feugiat. Maecenas scelerisque neque at tellus varius dapibus. In tellus urna, lobortis at arcu tempus, blandit interdum felis. Integer suscipit sed nulla vitae porta. Integer sodales justo sit amet enim placerat vulputate. Pellentesque quis dictum nulla, fermentum elementum elit. Sed ac suscipit risus. Curabitur ac elementum sapien, ut facilisis est.

    <div class='test-break'>
        Vestibulum maximus ut est id feugiat. Maecenas scelerisque neque at tellus varius dapibus. In tellus urna, lobortis at arcu tempus, blandit interdum felis. Integer suscipit sed nulla vitae porta. Integer sodales justo sit amet enim placerat vulputate. Pellentesque quis dictum nulla, fermentum elementum elit. Sed ac suscipit risus. Curabitur ac elementum sapien, ut facilisis est.
        <div class='test-float'>
            Vestibulum maximus ut est id feugiat. Maecenas scelerisque neque at tellus varius dapibus. In tellus urna, lobortis at arcu tempus, blandit interdum felis. Integer suscipit sed nulla vitae porta. Integer sodales justo sit amet enim placerat vulputate. Pellentesque quis dictum nulla, fermentum elementum elit. Sed ac suscipit risus. Curabitur ac elementum sapien, ut facilisis est.
            Vestibulum maximus ut est id feugiat. Maecenas scelerisque neque at tellus varius dapibus.Vestibulum maximus ut est id feugiat. Maecenas scelerisque neque at tellus varius dapibus.Vestibulum maximus ut est id feugiat. Maecenas scelerisque neque at tellus varius dapibus.
        </div>
    </div>
</body>
</html>
        ");


return $mpdf->Output();

**Comment by SlimDeluxe** [comment]
@itrack I am having the same issue. Did you manage to find a workaround?

**Comment by itrack** [comment]
Unfortunately I didn't find anything

**Comment by finwe** [comment]
@itrack I was unable to replicate the bug with your code example. PHP 7.4, last development version of mPDF.

**Comment by SlimDeluxe** [comment]
@finwe the problem appears to be fixed in PR #1296 but it's not merged. I guess it's also waiting for a repeatable example :)

**Comment by andersdn11** [comment]
I'm experiencing the same error when trying to make mpdf smart about page breaks. mpdf version 8.013

Notice the section styling page-break-inside that throws the error:

`

                $html .= '<section class="block paragraph_container" style="page-break-inside:avoid;">';
                $html .=    '<div class="block_paragraph root">';
                $html .=        '<div class="content">'. $this->process_html($block->content, $status) . '</div>';
                $html .=    '</div>';

                if( isset($block->blocks) ) {
                    foreach ($block->blocks as $block_key_lvl1 => $block_lvl1) {
                    $html .= '<div class="block_paragraph lvl1">';
                    $html .= '<div class="content">'. $this->process_html($block_lvl1->content, $status) . '</div>';
                    $html .= '</div>';

                        if( isset($block_lvl1->blocks) ) {
                            foreach ($block_lvl1->blocks as $block_key_lvl2 => $block_lvl2) {
                            $html .= '<div class="block_paragraph lvl2">';
                            $html .= '<div class="content">'. $this->process_html($block_lvl2->content, $status) . '</div>';
                            $html .= '</div>';

                            }
                        }
                    }
                }
                $html .= '</section>';

`

**Comment by andersdn11** [comment]
Managed to solve it by using tables, trs and tds instead of divs. Bit harder to style, but got it working.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
