### ISSUE TITLE
cant Rotate table headers

### ISSUE THREAD

**Issue by arcanisgk** [mpdf/mpdf#1247]
cant Rotate table headers. need angle of 30°

```
$mpdf  = new \Mpdf\Mpdf([
				'mode'          => 'utf-8',
				'format'        => 'L',
				'margin_left'   => 5,
				'margin_right'  => 5,
				'margin_top'    => 20,
				'margin_bottom' => 10,
				'margin_header' => 5,
				'margin_footer' => 5,
				'forcePortraitHeaders' => true
			]);
```
this not an issue; is a feature:
i want to set this html code example and make output a pdf file with same structure/layout:

https://codepen.io/pablojgarea/pen/XbMEjR

Is this posible?

**Comment by finwe** [comment]
https://mpdf.github.io/css-stylesheets/supported-css.html text-rotate is supported in table rows with 0-90 angles.
