### ISSUE TITLE
Open anchor links in new page.

### ISSUE THREAD

**Issue by ghiamar** [mpdf/mpdf#125]
Hi! I have a simple anchor link like

`<a href="link to web page" target="_blank">click here</a>`

But the links does not open in new page if the PDF is loaded from website and oppened with default browser PDF reader (in my case FF 46). Is it possible to indicate mpdf that links must be open in new page?

Thanks!

**Comment by finwe** [comment]
Hi, I don't think this is possible in "plain" PDF files as PDF readers do not expect readers to have tabs.

In FF's pdfjs reader you can open links to a new tab by middle mouse button click or with ctrl+click as you would do with standard HTML, but users of embedded Acrobat Reader will not have this option.

You could use some JS in the PDF [as hinted here](https://answers.acrobatusers.com/How-I-open-hyperlinks-inside-embedded-pdf-window-q2104.aspx) but this is beyond scope of mPDF.
