### ISSUE TITLE
Uncaught Error: Class Mpdf\QrCode\Output\Mpdf not found

### ISSUE THREAD

**Issue by zonehun** [mpdf/mpdf#1250]
I got this error:

PHP Fatal error: Uncaught Error: Class Mpdf\\QrCode\\Output\\Mpdf not found in /var/www/os/base_test/framework/addons/mpdf7/src/Mpdf.php:7339

I'm using mPDF 8.1 and PHP 7.4 version.

### This is a PHP code snippet I use

```
<?php
$mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8', 'format' => 'A4']);
$mpdf->allow_output_buffering = true;
$mpdf->WriteHTML($css, 1);
$mpdf->WriteHTML($html, 2);
$mpdf->Output();


```

### This is the HTML
```
<barcode code='BBBBB' size='0.8' type='QR' error='M' />
```

All of the other types of barcodes are working (the built in ones). I can not figure out why my system can not find the above mentioned class. 

If you have any suggestions I would be appreciated.

Thank you.

**Comment by finwe** [comment]
QR code library has to be installed manually as a dependency, it is not bundled with mPDF. Use

    composer require mpdf/qrcode

**Comment by neoacevedo** [comment]
It isn't in the documentation. More than 2 years ago, the Qr Code generator was inside this package and we could use it.

**Comment by finwe** [comment]
![obrazek](https://user-images.githubusercontent.com/195675/102591456-50751800-4112-11eb-94b1-177b22d755af.png)

**Comment by finwe** [comment]
Also, when upgrading to a higher major version, a quick scan through release and upgrade notes is useful

![obrazek](https://user-images.githubusercontent.com/195675/102591553-7dc1c600-4112-11eb-9e68-637dbea76ab5.png)
