### ISSUE TITLE
wrong array index

### ISSUE THREAD

**Issue by netpsirit72** [mpdf/mpdf#1254]
https://github.com/mpdf/mpdf/blob/67aafe72fad8182b60288564d032e0a4f8c0ff73/src/Mpdf.php#L12528

Instead of
$html .= ' font-size: ' . $arr['L']['font-size'] . 'pt;';
it should be
$html .= ' font-size: ' . $arr['C']['font-size'] . 'pt;';

**Comment by Klap-in** [comment]
Could you please add an example of the html and php code that can be used to trigger this case? Then it can be added as test case to the code, thanks!

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by netpsirit72** [comment]
code for testing:
`require_once 'vendor/autoload.php';
	$mpdf = new \Mpdf\Mpdf();
	$mpdf->DefHeaderByName("header", array(
		'L'=>array(),
		'C'=>array(
			'content'=>"{PAGENO}",
			'font-style' => 'B',
			'font-size' => 13
		),
		'R'=>array()
	));

	$html = "
		<style>
			@page {
				header: header;
			}
		</style>
	";
	$mpdf->WriteHTML($html);
	$mpdf->Output("test.pdf",'D');`
