### ISSUE TITLE
It´s not possible to hide an checkbox and label

### ISSUE THREAD

**Issue by zonky2** [mpdf/mpdf#1255]
Hi,

I have a checkbox and label at page to to control whether a DIV should be printed or not. This controls the visibility via CSS.

Both are built in without form tag.

```
<div>
    <div class="print-check pdf-break">
        <input type="checkbox" id="print_test" class="print_condition d-print-none d-pdf-none" value="test" checked="checked">
        <label for="print_test" class="d-print-none d-pdf-none">mit drucken</label>

        <div id="test" class="ce_bs_panel_single card d-print-none">...</div>

    </div>
</div>
```

with CSS to control to print to paper

```
  .print_condition:checked ~ div.d-print-none {
    display: block !important;
  }
```

It is not possible for me to hide the two input elements in the PDF - even with inline CSS they are printed :(

I try a own CSS class "d-pdf-none" (display: none;) - unsuccessfully

I try inline CSS...

```diff
<div>
    <div class="print-check pdf-break">
-        <input type="checkbox" id="print_test" class="print_condition d-print-none d-pdf-none" value="test" checked="checked">
+        <input type="checkbox" id="print_test" class="print_condition d-print-none d-pdf-none" value="test" style="display: none;" checked="checked">
        <label for="print_test" class="d-print-none d-pdf-none">mit drucken</label>

        <div id="test" class="ce_bs_panel_single card d-print-none">...</div>

    </div>
</div>
```

... unsuccessfully.

I see "[x] mit drucken" in every PDF :(

**Comment by Klap-in** [comment]
The css currently supported by the mpdf library is listed at https://mpdf.github.io/css-stylesheets/supported-css.html. You are sure these examples are listed?

**Comment by finwe** [comment]
Not really helpful. That issue template is not there for nothing, you know. How do you initialize the Mpdf object? Are you using custom fonts? Can you share a small HTML snippet reproducing this behaviour?

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
