### ISSUE TITLE
A PHP Error was encountered - Undefined index: group

### ISSUE THREAD

**Issue by elvisef** [mpdf/mpdf#1259]
Hello, I have two problems:

![13072020_16:07:44_Zaznaczenie](https://user-images.githubusercontent.com/25976749/87314171-22682800-c523-11ea-9e13-907d052e952c.png)
![13072020_16:07:57_Zaznaczenie](https://user-images.githubusercontent.com/25976749/87314174-2431eb80-c523-11ea-92dc-0bf6973bbde0.png)

Any help please, how to fix these ?

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by elvisef** [comment]
I don't know if I undersand You correctly. But all I do is executing this code:

`		require_once 'vendor/autoload.php';
		
		$format = ($orientation=='L') ? 'A4-L' : 'A4';

  	$mpdf =  new \Mpdf\Mpdf(
  		[
		    'mode' => 'utf-8',
		    'format' => $format,
		    'orientation' => $orientation
		]	
	); 

	$mpdf->ignore_invalid_utf8 = true;
	$mpdf->WriteHTML($html,\Mpdf\HTMLParserMode::HTML_BODY);
	$mpdf->Output($file, $mode);  	
`

Where $mode is set to "F".
I am not using any templates, just executing the code to make mpdf save a page into a file.
It worked for 5.4, and it doesn't for 8.x (after change from 5.x to 8.x).

As much as I can see, from the PHP error/notice, there are two variables that are not defined, "group" and "GPOSinfo".
Can You please write me some more info ? Do I need to open a new issue to replicate this issue ?

**Comment by Klap-in** [comment]
For every issue a test case is made, to check if all details are covered and to prevent reappearing. Like these https://github.com/mpdf/mpdf/tree/development/tests/Issues. So providing a complete example helps to speed up this process significantly.
e.g. `$html=''` is enough to reproduce your case? if specific html is needed, please provide a small example.

**Comment by elvisef** [comment]
Alright, I've checked the code and found a problematic line. Take a look:

This works well:
 

>        <div class=\"field\"><label for=\"testme-140ac\" class=\"left required\">Test me
>         <span class=\"required\">*</span>
>         </label><textarea name=\"testme\" cols=\"40\" rows=\"10\" id=\"testme-140ac\"></textarea>
>         </div>

But this not:

>         <div class=\"field\"><label for=\"testme-140ac\" class=\"left required\">Test me
>         <span class=\"required\">*</span></label><textarea name=\"testme\" cols=\"40\" rows=\"10\" id=\"testme-140ac\"></textarea>
>         </div>


I have just changed the code by adding a break line in one place (just after a closing span tag) and it worked.
It seems that mpdf didn't recognize the structure, did't find some tags ?

**Comment by elvisef** [comment]
Is the issue solved now ?
