### ISSUE TITLE
php >=7.2 count(null), self closing HTML tags 

### ISSUE THREAD

**Issue by owenBeresford** [mpdf/mpdf#1261]
First thank you for running this HUGE project.  its a lot of work you have all done.

**cause:**
When using newer versions of PHP, count(null) raises an error rather than returning 0.
Older  PHP just returned 0.
This is documented at https://www.php.net/manual/en/function.count.php

On a production machine, with the version of **mpdf 7** that was available 2y ago in composer (important: the version with namespaces), if you feed-in a HTML template including &lt;br&gt; , MPDF will crash with the detail.

"Warning: count(): Parameter must be an array or an object that implements Countable"

**solution:**
this can be suppressed with  
vendor/mpdf/mpdf/src/Otl.php line 5799  method trimOTLdata
(at first line of function)
 +  if($cOTLdata ===null) { return; }

 IMO, if there is no data, there is nothing to trim; so this makes sense

background:
if you would like me to make this ticket longer with a php unittest I can (after work today).
I didn't spot any tickets already stating this fault.  Sorry if dup.

**Comment by finwe** [comment]
This is most likely fixed in the latest version. Upgrade to 8.0.7 and if still present, create a new Issue with a code example causing this (or a PR with a test).

As we have not removed PHP versions support yet and upgrades are relatively easy, we do not backport fixes to older versions.

**Comment by owenBeresford** [comment]
This comment does not change the ticket status
pls read https://github.com/mpdf/mpdf/issues/562 
issue should be closed by newer version.

I have written bits of a test; but the boundaries on my  fail criterion is quite long (and I need to exhaustively remove irrelevant details, like my employers trade secrets)

**Comment by owenBeresford** [comment]
Upgrading to 8.0.7 does remove issue.
