### ISSUE TITLE
Bootstrap 4.5 results in 11 blank pages

### ISSUE THREAD

**Issue by Xites** [mpdf/mpdf#1266]
When I execute the following code, the text is not shown. Only 11 empty pages is the result. Using a different css is working correctly.
I've tried to increase memory to 1024M and try/catch doesn't catch anything. Bootstrap 4.0 has the same result, but 3 does work.

mpdf 8.0.7
php 7.3.20

```
<?php

$mpdf = new \Mpdf\Mpdf();
$html = "<link rel=\"stylesheet\" media=\"all\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">";
$html .= "Test";
$mpdf->WriteHTML($html);
$mpdf->Output();

```

**Comment by finwe** [comment]
mPDF is not compatible with Bootstrap. Especially with newer versions using more and more CSS3 features. See https://mpdf.github.io/css-stylesheets/supported-css.html for more details.

**Comment by Xites** [comment]
I figured out a workaround.
When you disable the print styles in the _variables.scss it does work.

`
$enable-print-styles:                         false !default;
`

**Comment by simontaurus** [comment]
Using mpdf on mediawiki (via Extension:Mpdf) you could also use a compatible skin w. o. bootstap only for PDF-printing, e.g.
https://<somewiki>/w/index.php?title=Main_Page&useskin=vector&action=mpdf
