### ISSUE TITLE
large margin in column

### ISSUE THREAD

**Issue by drzz1** [mpdf/mpdf#127]
How to remove that space (blue square) after red element, that space always matches elements height

``` html
$mpdf->SetColumns(2);
$mpdf->WriteHTML('a');
$mpdf->AddColumn();
$mpdf->WriteHTML('<div style="height:200px;background-color:red;margin:0px;padding:0px;margin-bottom:0px;">a</div>');   
$mpdf->SetColumns(0);
$mpdf->WriteHTML('<hr />');
$mpdf->WriteHTML('<div style="height:200px;background-color:red;margin:0px;padding:0px;margin-bottom:0px;">a</div>');
```

![pdfrender](https://cloud.githubusercontent.com/assets/12299863/15038963/4bd92dd4-12b1-11e6-9779-acc99f94b999.PNG)

**Comment by drzz1** [comment]
can anybody help?

**Comment by bunya** [comment]
Hello.
Try to set
`$mpdf->lasth = 0;`
before
`$mpdf->SetColumns(0);`

It's hack, but it's working

**Comment by chejnik** [comment]
Yes, it helps. Thank you.
