### ISSUE TITLE
ksort is NULL in Otl.php Line 4390

### ISSUE THREAD

**Issue by fabianwohlfart** [mpdf/mpdf#1278]
### I found this bug & would like to fix it
In Otl.php in line 4391 ksort() can be NULL if $tableCount or $GlyphCount is zero length. ($tableCount should also be Uppercase I guess)
If its NULL it throws an error.

The fix would be to do 
`if ($GlyphByClass) ksort($GlyphByClass);`

I would make a pull request but I am not familiar with it and do not want to make a mistake.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
"mpdf/mpdf": "^8.0"

Best,
F

**Comment by finwe** [comment]
Feel free to reopen with a code example to reproduce the issue.

**Comment by fabianwohlfart** [comment]
It took me a while to understand it.
It's a warning from the script of a font file which does not meet the requirements of _getClassDefinitionTable
If I turn display_errors off the PDF gets generated, its not mandatory a bug, but more an improvement.

With display_errors on I also get some more Notices and Warnings.
For example
`Notice: A non well formed numeric value encountered in /vendor/mpdf/mpdf/src/Mpdf.php on line 6833`
But I think you are aware of this.

Anyways.
If you look closely to Otl.php and the _getClassDefinitionTable you will see that...

`
private function _getClassDefinitionTable($offset)
	{

		if (isset($this->LuDataCache[$this->fontkey][$offset])) {
			$GlyphByClass = $this->LuDataCache[$this->fontkey][$offset];
		} else {
			$this->seek($offset);
			$ClassFormat = $this->read_ushort();
			$GlyphClass = [];
			
			//      $GlyphByClass = array(0=>array());  // NB This forces an index[0]
`
... here was something before.
If you cast an empty array there, as you did with $GlyphClass everything is fine, NULL is the problem.

`$GlyphByClass = []`

Because $GlyphByClass will only be set if the Fontfile has a $GlyphCount or $TableCount.
`for ($i = 0; $i < $GlyphCount; $i++) {` [4376]
`for ($i = 0; $i < $tableCount; $i++) {` [4386]

Let me know what you think.

I also documented it, in case anybody else runs into this ksort problem, and is not aware that some dev put display_errors in a random php file and did not remove it afterwards :)

**Comment by finwe** [comment]
This is all nice, but I just need as piece of "userland" code (PHP+HTML/CSS) that reproduces this issue.

**Comment by fabianwohlfart** [comment]
Alright
PHP

```

error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once __DIR__ . '/vendor/autoload.php';

$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
$fontDirs = $defaultConfig['fontDir'];

$defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
$fontData = $defaultFontConfig['fontdata'];

$mpdf = new \Mpdf\Mpdf(
  [
    'fontDir' => array_merge([
       __DIR__ . '/fonts',
    ], $fontDirs),
    'fontdata' => $fontData + [
      'maison_neue_book' => [
          'R' => 'MaisonNeue-Book.ttf',
          'useOTL' => 0xFF
      ]
    ],
   'default_font' => 'maison_neue_book',
  ]
);
$mpdf->WriteHTML('<p style="font-family: maison_neue_book;"> . . . . . . . . . . . . . . . . . . . . . . . . . . . .</p>', \Mpdf\HTMLParserMode::HTML_BODY);
$mpdf->Output();
```

Funnily it must be at least _somehow_ 46 characters inside the <p> separated by a space.
If its less then 46 characters the pdf just wont load: »Due to an error«.
If no spaces between the dots it will work and show the pdf.
But it breaks with some other characters aswell, currency signs, interpunction... 
I have no clue how to narrow it down.

Also its bound to the particular font, not sure what it means in terms of font engineering.
But I cannot send the font file to you public due to copyright, maybe private per pm if you are interested.
