### ISSUE TITLE
Error: module is already loaded (zbarcode)

### ISSUE THREAD

**Issue by nitinsbuzz** [mpdf/mpdf#128]
I have an Apache server for hosting a php5 website using zbarcode and mpdf. It gives an error when trying to generate a new pdf file. This error happens after uploading a picture and finding its barcode using zbarcode. The pdf error occurs without any data used from zbarcode (seperate requests).

**Comment by finwe** [comment]
What version of mPDF are you using? Are you using composer? Can you provide a code example?

**Comment by nitinsbuzz** [comment]
I am using mPDF 6.0.0 downloaded with composer. I cannot generate the error at will (it occurs randomly). 

`$mpdf = new \mPDF('utf-8','A4');
            
            $mpdf->debug = true;
            $mpdf->WriteHTML($css, 1);
            $mpdf->WriteHTML($text, 2);
            $mpdf->Output($fileLocation);

        header($_SERVER["SERVER_PROTOCOL"] . ' 200 OK');
        header('Content-type: application/pdf');
        header('Content-Disposition: attachment: filename="' . basename($file) . '"');
        header('Content-Transfer-Encoding: binary');    
        header('Content-Length: ' . filesize($fileLocation));
        header('Accept-Ranges: bytes');  
        
Using zbarcode:
$image = new \ZBarCodeImage($imageLoc);
            
            /* Create a barcode scanner */
            $scanner = new \ZBarCodeScanner();
            
            /* Scan the image */
            $barcodes = $scanner->scan($image);`

**Comment by nitinsbuzz** [comment]
Error message detected - PDF file generation aborted.

Module 'zbarcode' already loaded
File: Unknown
Line: 0

**Comment by finwe** [comment]
This seems having nothing to do with mPDF - you just happen to load the `zbarcode` module on multiple places and mPDF just prevents unpredictable behaviour by "catching" this error it gets from error_get_last() (at the beginning of the `Output` method).

Closing this.

**Comment by nitinsbuzz** [comment]
You are right! Zbarcode module was being loaded twice on the server (compiled and dynamic extension in php.ini). Thanks you very much!
