### ISSUE TITLE
Allow more up to date version of deep-copy

### ISSUE THREAD

**Issue by ecofishrcr** [mpdf/mpdf#1280]
### I would like to have this new functionality

Currently mpdf requires deep-copy ^1.7 (Oct 20, 2017). I have some other libraries that are requiring a newer version of deep-copy. Would it be possible to update the version or allow more up to date versions. According to their release notes it looks like it has just been bug fixes, no breaking changes.

**Comment by finwe** [comment]
Current version of DeepCopy, `1.10.1`, is allowed with current constraint `^1.7`. The problem will probably be in your locked dependencies.

https://jubianchi.github.io/semver-check/#/^1.7/1.10.1
