### ISSUE TITLE
mPDF hangs on image not found instead of showing a [x]

### ISSUE THREAD

**Issue by willypuzzle** [mpdf/mpdf#1281]
I found this bug when I provide an image URL that doesn't exist. When I provide a path or a URL to an image that not exist, mPDF hangs the server instead of showing a [x]. The hanging is so brutal that I have to kill the server and start it again. So I cannot test in production.

My mPDF version is 8.0.7 and the PHP version is 7.4.9. My environment is the test server provided by laravel with "php artisan serve" command.

The PHP code I use is quite complex because I built a library to generate pdf from a config file. However, I have a custom font (Arial), an empty footer and header and I use Output($filename, 'I') method.

The snippet of Html is simply an image with a likely wrong path in src, wrapped in an HTML page with some CSS inside the page.

**Comment by finwe** [comment]
https://github.com/mpdf/mpdf#known-server-caveats

**Comment by willypuzzle** [comment]
Thanks for the answer, it is exactly what I was looking for.

**Comment by bestiony** [comment]
@willypuzzle 
use :
public_path() 
instead of :
asset() 

this solved the problem for me . because  asset makes the website call itself but public path give the server the path inside the server so that it uses the images and produces the pdf for you
