### ISSUE TITLE
Text displays like a black spot

### ISSUE THREAD

**Issue by Christian-Vasilev** [mpdf/mpdf#1286]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

When I try to render the .svg file to .pdf all the text is displayed as black spots and It's not readable.
The php version I'm using is 7.4 with a XAMPP 1.8.3 version. I'm using mPDF version 8.0.5.

I used the [following way](https://github.com/mpdf/mpdf/issues/450#issuecomment-644279152) to export the .svg file from illustrator 

[Image](https://i.imgur.com/95PsFXh.png)

```
<?php
 // Load the default configuration variables so we can merge them afterwards
        $defaultConf = (new ConfigVariables())->getDefaults();
        $fontDirs = $defaultConf['fontDir'];
        // Load the default font variables so we can merge them afterwards
        $defaultFontConfig = (new FontVariables())->getDefaults();
        $fontData = $defaultFontConfig['fontdata'];

        // Create a new mpdf instance and merge the needed data with the default config.
        $this->mpdf = new Mpdf([
            'fontDir' => array_merge($fontDirs, $fontsDirectory),
            'fontdata' => array_merge($fontData, $fonts),
            'default_font' => $defaultFont,
            'mode' => '',
            'format' => 'A4',
            'orientation' => 'P',
        ]);

        // Directory that files will be stored/retrieved from.
        $this->storeDirectory = $storeDirectory;
        $this->mpdf->SetFooter([], 'E');

        // Default Metadata
        $this->mpdf->SetTitle('Dineout');
        $this->mpdf->SetAuthor('Dineout');
        $this->mpdf->SetCreator('Dineout');
        $this->mpdf->SetDisplayMode('fullpage');

```

### This is a HTML/CSS code snippet I use

```
<html>
    <body style="position: relative;">
        <img src="data:image/svg+xml;base64,{{ base64_encode($template) }}"/>
    </body>
</html>

```

**Comment by finwe** [comment]
Try your file in the last mPDF version, SVG handling was improved there. The issue will not be addressed in mPDF 6 anyway.

If the trouble persists, please provide the source PDF.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
