### ISSUE TITLE
Subscript tag is not aligned with the superscript tag, and providing any CSS to align it, doesn't have any effect

### ISSUE THREAD

**Issue by kanujbhatnagar** [mpdf/mpdf#1287]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug / would like to have this new functionality

Subscript tag is not aligned with the superscript tag, and providing any CSS to align it, doesn't have any effect. I've tried providing left attribute to the sub tag, and while it modifies its position in the HTML, it doesn't have any effect on the generated PDF.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF: 8.0
PHP: 7.2
### This is a PHP code snippet I use

```
<?php
require_once __DIR__ . '/vendor/autoload.php';

$pdf = new Mpdf\Mpdf();
$main_style = file_get_contents('try.css');
$pdf->WriteHTML($main_style, 1);
$pdf->WriteHTML(file_get_contents("try.html"));
$pdf->Output();
```

### This is a HTML/CSS code snippet I use

```
<html>

<head>
    <style type="text/css">
        .music_meter_signature,
        .music_figured_bass {
            display: inline-block;
            position: relative;
            bottom: 3px;
            left: 3px;
        }
        
        .music_meter_signature sup,
        .music_meter_signature sub,
        .music_figured_bass sup,
        .music_figured_bass sub {
            float: left;
        }
        
        sub,
        sup {
            font-size: 100%;
            line-height: 0;
            position: relative;
            vertical-align: baseline;
        }
        
        sup {
            top: -0.5em;
        }
        
        sub {
            bottom: -0.25em;
            color: mediumseagreen;
            /* left: -0.5em; */
        }
    </style>
</head>

<body>
    <table width="100%" cellpadding="2" class="nobr" autosize="1">
        <tbody>
            <tr>
                <td width="5%" style="vertical-align:middle;">A</td>
                <td width="95%">
                    <p class="choice_paragraph">Loren ipsum <span class="music_figured_bass"><sup>6</sup><sub>4</sub></span> chord lorem ipsum.</p>
                </td>
            </tr>
        </tbody>
    </table>
</body>

</html>
```

**Comment by kanujbhatnagar** [comment]
The color of the text in the sub tag doesn't modify either in the generated PDF.

**Comment by finwe** [comment]
Positioning is not supported for inline elements https://mpdf.github.io/css-stylesheets/supported-css.html

Styles inside block elements are generally ignored inside tables: https://mpdf.github.io/tables/tables.html
