### ISSUE TITLE
upperCase.php - failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by accgit** [mpdf/mpdf#1298]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug / would like to have this new functionality

I don't know if it's a bug

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

php 7.4, mpdf 8.0.7

### This is a PHP code snippet I use

after installing the composer it tells me this

require(C:\xampp\htdocs\new-intranet\vendor\mpdf\mpdf\src/../data/upperCase.php): failed to open stream: No such file or directory

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('<h1>Hello world!</h1>');
$mpdf->Output();

```

### This is a HTML/CSS code snippet I use

I didn't even get to that
```

```

**Comment by finwe** [comment]
and... does the file exist?

**Comment by accgit** [comment]
does not exist, not in the package

"$this->upperCase = require __DIR__ . '/../data/upperCase.php';"

line: 1116 file: Mpdf.php

**Comment by finwe** [comment]
Then it's a composer/data issue, the file is part of the package. https://github.com/mpdf/mpdf/blob/development/data/upperCase.php
