### ISSUE TITLE
Can't create image while subdomain in url

### ISSUE THREAD

**Issue by baselbers** [mpdf/mpdf#13]
ImageCreate error: image type not recognised, and not supported by GD imagecreate

**Comment by niekoost** [comment]
I guess that you're trying to create a PDF that points to an image on a non-public location. For instance an online image that is password protected on another domain OR trying to use an online password protected image in a command line script.

**Comment by baselbers** [comment]
I thought so to, but converting the image url to base64 did the [trick](https://github.com/baselbers/woocommerce-pdf-invoices/blob/master/functions.php).
