### ISSUE TITLE
HTML ("&le";   ≤) entity not showed

### ISSUE THREAD

**Issue by RafaelLinux** [mpdf/mpdf#1301]
Despite we searched in StackOverflow, there is no mention to this issue.
PHP 5.6.40-0+deb8u12
mpdf/mpdf     v7.1.7  

We publish some documents with mathematical symbols. HTML source is in UTF-8 and stored in UTF-8. However, we discovered that while most symbols are being showed in mPDF generated PDF files, this symbol is not visible:

```
<p>UNICODE     U+02264</p>
<p>HEX CODE    &#x2264;</p>
<p>HTML CODE   &#8804;</p>
<p>HTML ENTITY &le;</p>
<div>
	<p>UNICODE     U+02264</p>
	<p>HEX CODE    &#x2264;</p>
	<p>HTML CODE   &#8804;</p>
	<p>HTML ENTITY &le;</p>
</div>
```

![imagen](https://user-images.githubusercontent.com/13048959/96257754-3789a280-0fbb-11eb-8183-8dd634102657.png)

Could you help us?

Thank you

**Comment by finwe** [comment]
Screenshot from clean mPDF instantiation:

![obrazek](https://user-images.githubusercontent.com/195675/96273570-c6a0b580-0fcf-11eb-9e42-5f61e48f8280.png)

Your font probably does not support these characters.

**Comment by RafaelLinux** [comment]
We use OpenSans font in HTML web page and in mPDF. Browser shows correctly all content, but mPDF ignore all "non-ascii" characters, as you can see in attached screenshots. At this point, despite you closed my thread, what's the issue then?.

Thank you

Firefox screenshot
![imagen](https://user-images.githubusercontent.com/13048959/96707532-49db5600-1398-11eb-976c-be3af71fce34.png)

PDF (generated with mPDF) screenshot
![imagen](https://user-images.githubusercontent.com/13048959/96707373-126ca980-1398-11eb-8fda-7000a0c125e1.png)

PDF fonts properties
![imagen](https://user-images.githubusercontent.com/13048959/96707038-a5591400-1397-11eb-8ecd-f0f8fddeb2bb.png)

**Comment by finwe** [comment]
You are missing the example code of how you initialize and configure mPDF.

**Comment by RafaelLinux** [comment]
Please, I don't know if this is enough code to show how we are initializing:

style.css:
```
@font-face
{
	font-family:"Open Sans";
	src:url("./fonts/OpenSans-Regular.ttf") format("truetype"),
	url("./fonts/OpenSans-Regular.eot?") format("eot"),
	url("./fonts/OpenSans-Regular.woff") format("woff"),
	url("./fonts/OpenSans-Regular.svg#OpenSans") format("svg");
	font-weight:normal;
	font-style:normal;
}

@font-face
{
	font-family:"Open Sans Light";
	src:url("./fonts/OpenSans-Light.ttf") format("truetype"),
	url("./fonts/OpenSans-Light.eot?") format("eot"),
	url("./fonts/OpenSans-Light.woff") format("woff"),
	url("./fonts/OpenSans-Light.svg#OpenSans-Light") format("svg");
	font-weight:normal;
	font-style:normal;
}

@font-face
{
	font-family:"Open Sans Condensed Light";
	src:url("./fonts/OpenSans-CondLight.ttf") format("truetype"),
	url("./fonts/OpenSans-CondLight.eot?") format("eot"),
	url("./fonts/OpenSans-CondLight.woff") format("woff"),
	url("./fonts/OpenSans-CondLight.svg#OpenSans-CondensedLight") format("svg");
	font-weight:normal;
	font-style:normal;
}

html, body
{
	font-family: 'Open Sans', sans-serif;
}
```

PHP initialization:
```
$stylesheet1= file_get_contents('style.css');
 
$html_portada1= '<!DOCTYPE html>
<html lang="es" xml:lang="es">
	<head>
		<title>B.O.P. nº.'.$NumeroBoletin.' - '.$FechaEnLetras.'</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="author"	content="Diputación de Badajoz"/>
		
	</head>
<body>';

....

	$mpdf_Completo= new \Mpdf\Mpdf(['mode' => 'utf-8','format' => 'A4', 'default_font_size' => 9.25, 'default_font' => 'opensans','aliasNbPg' => '[pagetotal]']);
	$mpdf_Completo->WriteHTML($stylesheet1.$stylesheet2,1);
$mpdf_Completo->WriteHTML($html_portada1.$html_portada2.$html_portada2_1.$html_portada2_2);
	$mpdf_Completo->WriteHTML($html_footer.$html_sumario.$html_completo);

```

Fonts are accesible by mPDF, so we guess mPDF is using them. They are just the same fonts used to render in HTML.

Do you need any other info?

Thank you

**Comment by finwe** [comment]
`font-face` is not officialy supported and may not work as intended. Link fonts as indicated in the documentation.

https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html

Working code and generated document:

```php
$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
$fontDirs = $defaultConfig['fontDir'];

$defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
$fontData = $defaultFontConfig['fontdata'];

$mpdf = new \Mpdf\Mpdf([
    'fontDir' => array_merge($fontDirs, [
        __DIR__ . '/fonts',
    ]),
    'fontdata' => $fontData + [
        'open-sans' => [
            'R' => 'OpenSans-Regular.ttf',
            'I' => 'OpenSans-Italic.ttf',
        ]
    ],
    'default_font' => 'open-sans'
]);


$mpdf->WriteHtml('

<p>UNICODE     U+02264</p>
<p>HEX CODE    &#x2264;</p>
<p>HTML CODE   &#8804;</p>
<p>HTML ENTITY &le;</p>
<div>
	<p>UNICODE     U+02264</p>
	<p>HEX CODE    &#x2264;</p>
	<p>HTML CODE   &#8804;</p>
	<p>HTML ENTITY &le;</p>
</div>

');

$mpdf->Output('example000.pdf', 'F');
```

[example000.pdf](https://github.com/mpdf/mpdf/files/5415408/example000.pdf)

**Comment by RafaelLinux** [comment]
We were guessing that mPDF will show some kind of warning or error if unable to get some font, but we were wrong then.
Well, that means we need to modify and break apart some coding, something that we were just avoiding. I don't understand index letters assigned to fonts are for, but I imagine is documented (we only need regular and condensed formats).

Thank you very much for your immediate answer to our messages, as always do.

**Comment by finwe** [comment]
There is a `debugfonts` config variable that could maybe help. But given that at least a part of the font is being included from font-face definition... ¯\_(ツ)_/¯

**Comment by RafaelLinux** [comment]
"Who knows!" XD
ok

Best regards and thank you again

**Comment by RafaelLinux** [comment]
Still can't get "extended" characters from OpenSans font to be showed. Curiosly, even loading or not OpenSans from CSS or with mpdf directives, same results. "Arial" or "Times News Roman" fonts shows "extended" characters, but I even not loading that fonts (must be fonts installed on server). What do you think about this issue?

This is the PDF result:
![imagen](https://user-images.githubusercontent.com/13048959/98088690-0ac20000-1e82-11eb-90a6-bf5d0d4309fb.png)

**Comment by finwe** [comment]
Those are pretty special characters. I doubt that OpenSans TTF from Google Fonts contains them.

**Comment by finwe** [comment]
Anyway, you are probably doing something incorrectly with the le entity. Please keep in mind this is not a support forum and this issue is closed.

**Comment by RafaelLinux** [comment]
Ok, I'll ask in other place, I'm sorry. Thank you

**Comment by RafaelLinux** [comment]
For anyone interested. The issue is solved simply adding:
`$this->useSubstitutions = true;`
And it does the magic
