### ISSUE TITLE
WriteText () writes to other languages fonts are not displayed

### ISSUE THREAD

**Issue by pengjinhj** [mpdf/mpdf#1306]
$mpdf = new Mpdf();

  $mpdf->autoScriptToLang = true;
  $mpdf->autoLangToFont = true;
          $mpdf->WriteText('42', 34.6, '101010101010');

The generated PDF fonts are not displayed

![image](https://user-images.githubusercontent.com/34464737/97415002-a530b980-193f-11eb-8341-424232817b06.png)

**Comment by finwe** [comment]
Feel free to reopen with all details required by the issue template.
