### ISSUE TITLE
PHP 7.4 MPDF v8.0.7 Error

### ISSUE THREAD

**Issue by kieran82** [mpdf/mpdf#1308]
I'm using the most recent version of mpdf and my web server was upgraded to php 7.4 and since i upgraded i've been getting all these errors in my logs from the vendor mpdf directory. here are the errors. The file still creates but all the errors are appearing all the time.

[mpdf_errors.txt](https://github.com/mpdf/mpdf/files/5468969/mpdf_errors.txt)

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
