### ISSUE TITLE
Broken composer installation of cache directories

### ISSUE THREAD

**Issue by tyranron** [mpdf/mpdf#131]
In version `v6.0.0` after running `composer install` we have:
![scc9_1](https://cloud.githubusercontent.com/assets/7114909/15136858/e5bdeba8-168d-11e6-8566-bf50070ac8e3.png)
That's okay.

But starting from version `v6.1.0` we have:
![scc9_2](https://cloud.githubusercontent.com/assets/7114909/15136875/17b94896-168e-11e6-901b-cb9ee84029be.png)
`.gitignore` files are missed after installing now.

It causes problems for some deploy scenarios when empty directories are ignored, so not included into final release, and as the result causes errors when `mpdf` library expects these directories to be present.

**Comment by finwe** [comment]
You are right. There was a `.gitignore export-ignore` line in .gitattributes file. I have removed it for future releases, in the meantime, it is merged in both `development` and `master` branches.

**Comment by tyranron** [comment]
@finwe thank you!
