### ISSUE TITLE
very huge size package !!

### ISSUE THREAD

**Issue by vahidalvandi** [mpdf/mpdf#1311]
hi , we have big problem in download package with composer because size of each tag more than 30 MB !!!
maybe it contain .git files and unnecessary  file

**Comment by vahidalvandi** [comment]
why closed this ??

**Comment by finwe** [comment]
Read contribution guidelines.

Furthermore, the package size is already being discussed in 
https://github.com/mpdf/mpdf/issues/552 and answered in https://github.com/mpdf/mpdf/issues/1246. Another poorly formulated issue will not help in addressing this.

**Comment by finwe** [comment]
(and no, there are no _.git and unnecesary file_ in the package).
