### ISSUE TITLE
Undefined variable: glyphIDtoUni

### ISSUE THREAD

**Issue by sergiokessler** [mpdf/mpdf#1312]
```
<b>Notice</b>:  Undefined variable: glyphIDtoUni in <b>...\app\vendor\mpdf\mpdf\src\Mpdf.php</b> on line <b>3961</b><br />
```

is this a bug ?

I don't see any problem in the generated PDF AFAICT...

mPDF 8.0.x

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
