### ISSUE TITLE
Table of content is breaking line for page number.

### ISSUE THREAD

**Issue by sumon01914** [mpdf/mpdf#1314]
Hello,
I am facing a problem for large table of content which is creating dynamically. But problem is when large text the page number breaking the line. It is not showing in same line it is comes up with text. Attachment is available.
![2](https://user-images.githubusercontent.com/6293134/98911683-2fa41c00-24ef-11eb-81db-97559cbb4ee5.PNG)

Also here is my css code. 
div.mpdf_toc {line-height: 1.5;font-style: normal; white-space: nowrap!important;page-break-inside: avoid!important;overflow: wrap;}
a.mpdf_toc_a {text-decoration: none;color: black;font-size:10px!important;}
div.mpdf_toc_level_0 {line-height: 1.5; margin-left: 0; padding-right: 0em;}
span.mpdf_toc_t_level_0 {font-weight: normal;}span.mpdf_toc_p_level_0 {font-weight: normal;}
div.mpdf_toc_level_1 {margin-left: 2em;padding-right: 0em;text-indent:0em}
span.mpdf_toc_t_level_1 {font-style:normal;font-weight: normal;}
span.mpdf_toc_p_level_1 {font-weight: normal;}
div.mpdf_toc_level_2 {margin-left: 4em;padding-right: 0em;text-indent:0em}
span.mpdf_toc_t_level_2 {font-weight: normal;}span.mpdf_toc_p_level_2 {font-weight: normal;}
div.mpdf_toc_level_3 { margin-left: 6em;padding-right:0em;text-indent:0em }
span.mpdf_toc_t_level_3 {font-weight: normal;}span.mpdf_toc_p_level_3 {font-weight:normal;white-space: nowrap;}
div.mpdf_toc_level_4 { margin-left: 8em;padding-right: 0em;text-indent: 0em}
span.mpdf_toc_t_level_4 {font-weight: normal;}span.mpdf_toc_p_level_4 {font-weight:normal;} 

I called toc function dynamically.
 $mpdf->TOC_Entry("Toc1", 1);

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by finwe** [comment]
How hard it is to fill out the issue template? This issue cannot be reproduced with provided code sample.
