### ISSUE TITLE
Ignore pcre.backtrack_limit with value  "-1"

### ISSUE THREAD

**Issue by OleksandrKrupnyk** [mpdf/mpdf#1316]
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
php x64 v7.4.9
Library version 8.0.7
### This is a PHP code snippet I use

```
<?php
...
\ini_set("pcre.backtrack_limit", '-1');
$mpdf->WriteHTML($htmContent);
...
```

### See error
Function AdjustHTML() return error.
```
The HTML code size is larger than pcre.backtrack_limit -1. You should use WriteHTML() with smaller string lengths
```

**Comment by finwe** [comment]
-1 is not a safe value to set `pcre.backtrack_limit` to. Set your limit to a positive integer.
