### ISSUE TITLE
Alternative ways to sponsor the project

### ISSUE THREAD

**Issue by NicolasCARPi** [mpdf/mpdf#1319]
Hello,

Since a few years now I'm using the mpdf project in my electronic lab notebook software [eLabFTW](https://github.com/elabftw/elabftw).

I would like to sponsor this project through monetary donations. Unfortunately you only propose to do so through PayPal and I really dislike this company and want to avoid giving them money.

I suggest looking into GitHub sponsors or maybe OpenCollective or Liberapay or Patreon as alternatives to PayPal (while still retaining the option to go through PayPal if desired).

Cheers and thanks for this great project!

~Nico

**Comment by jfiala** [comment]
I donated for the project recently - is is possible to get an invoice for specific issues/features?

**Comment by finwe** [comment]
It's not, sorry.

**Comment by jfiala** [comment]
That's sad because we'd need better support to include svg maps (based on d3js / topojson) and would like to sponsor in case you can improve that, but we'd need an invoice as otherwise I'd have to sponsor privately...

**Comment by jfiala** [comment]
Right now we work around that limitation using PNG....

**Comment by finwe** [comment]
I've said it before an I will repeat it: I will not do the donation -> feature workflow, because that would make working on mPDF a job and ultimately would take the little remaining pleasure I have in it away.

**Comment by jfiala** [comment]
I understand that, it's a great product anyway!
