### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by MohamedQabbani** [mpdf/mpdf#132]
Related to issue #109

**Comment by finwe** [comment]
Provide additional data.

**Comment by MohamedQabbani** [comment]
The issue in <img src="data:{{ $signature_img_data['size']['mime'] }};base64,{{ $signature_img_data['base64'] }}" style="display: block; margin: 0 auto; height: 900px;" />

signature_img_data is array has two keys size and base64

array:2 [▼
  "size" => array:7 [▼
    0 => 2550
    1 => 3507
    2 => 2
    3 => "width="2550" height="3507""
    "bits" => 8
    "channels" => 3
    "mime" => "image/jpeg"
  ]
  "base64" => """
    /9j/4AAQSkZJRgABAQEBLAEsAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a\r\n
    HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy\r\n
    MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCA2zCfYDASIA\r\n
    AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA\r\n
    AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3\r\n
    ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm\r\n
    p6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA\r\n
    AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx\r\n
    BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK\r\n
    U1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3\r\n
    uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDyUKBG\r\n

**Comment by MohamedQabbani** [comment]
I can not copy full base 64 because it is very large

**Comment by finwe** [comment]
Please, attach a HTML snippet and an actual PHP error message with stack trace (from PHP error log or output with php errors enabled and printed).

**Comment by MohamedQabbani** [comment]
[genPDF.html.tar.gz](https://github.com/mpdf/mpdf/files/256838/genPDF.html.tar.gz)

**Comment by MohamedQabbani** [comment]
I Upload html file which try to use in $mpdf->WriteHTML($signature, 2);

**Comment by MohamedQabbani** [comment]
[image.html.tar.gz](https://github.com/mpdf/mpdf/files/256855/image.html.tar.gz)

**Comment by finwe** [comment]
mPDF is not able to handle HTML chunks of this size. Either resize the image to be significantly smaller to be able to render it as base64 (I guess 2MB image file is too large for the PDF anyway), or use alternative way of linking the image to the HTML (i'd suggest local path).

See also: manual page for images https://mpdf.github.io/what-else-can-i-do/images.html

Closing this.

**Comment by MohamedQabbani** [comment]
Thanks
