### ISSUE TITLE
Feature Request - Skip Rendering or Ignore HTML Code

### ISSUE THREAD

**Issue by iamjohnsimeon** [mpdf/mpdf#1321]
I see that there are custom tags with mPDF, is there one that can be created so that the code between said tag does not get rendered into the PDF.

I know there are HTML Comments that can achieve this but my USE case is an HTML page that can be viewed and also made as PDF and some details are not necessary to show up on the HTML Page.

Or perhaps a case where the header & footer are defined using `<htmlpageheader></htmlpageheader>` `<htmlpagefooter></htmlpagefooter>` at the top of the page and still want to be previewed by HTML at the top and bottom of the page.

**Comment by finwe** [comment]
This can already be achieved by @print CSS media or a custom stylesheet with `display: none` used only in PDF creation. I'd rather not add any new proprietary HTML tags.

**Comment by jakejackson1** [comment]
This is probably what you are looking for https://mpdf.github.io/html-support/custom-html-tags.html

**Comment by iamjohnsimeon** [comment]
I know about `@print` CSS and even regular HTML `<!-- --!>`. However, those are outside of mPDF. They are workarounds.
But you're the boss. Thank you guys for your response and this awesome project.
