### ISSUE TITLE
The barcode function cuts the string code and passes an error as valid.

### ISSUE THREAD

**Issue by arcanisgk** [mpdf/mpdf#1332]
**This is mPDF and PHP version and environment (server/fpm/cli etc) I am using**
7.4 php lastest mpdf

I found this bug in barcode functionality:

i have this bad code: **'0048200115438'** that mean like a UPCA, and i use it in the tag:

`<barcode code="0048200115438" type="UPCA" height="0.3" style="margin:2px" />`

the problem is that feature cut the string code to create the barcode, output:

![image](https://user-images.githubusercontent.com/1207306/101247867-cc6e6980-36e9-11eb-8ce0-d0026d6145a1.png)

first of all the script has an adverse effect on where; cut / delete the last number of the code to generate the barcode; when in fact the code never had to be validated as correct; **Where did the number 8 go?**

**Comment by finwe** [comment]
UPC-A codes have 12 characters, your code has 13 characters (are you sure it is nou UPC-13?).

The code is cropped to the expected length of the given barcode type, so to 12 characters.

This behaviour cannot be changed until the next major release, as throwing an exception would be a BC break.

The validation is prepared in 2c260d4

**Comment by arcanisgk** [comment]
I did it on purpose in a test setting.
The idea was to verify what happens if a user places a wrong barcode and adds a zero to the start by mistake (This can happen in manual / digital environments).

I am clear that the original and valid barcode is: `048200115438` of 12 characters.

but what happens when you send: `0048200115438 `to the mPDF and the TAG `<barcode>` has the property `type="UPCA"`; the result of the mPDF validation is that for some reason it cuts the string (which it should not do, Manipulate the Data); and it generates a bar code that can cause errors when trying to read it in any process that uses the document that comes out of Mpdf.

I'm even thinking of extracting the evaluation that mPDF does, in an external library, honestly, the validation that mPDF does to generate the barcodes is very extensive, but the problem is that it does it when generating the PDF; being in an external library I can validate the string without consuming resources, that's what I think.

**Comment by Klap-in** [comment]
See https://github.com/mpdf/qrcode further reasoning around this library is better explained by @finwe .

**Comment by arcanisgk** [comment]
> See https://github.com/mpdf/qrcode further reasoning around this library is better explained by @finwe .

but the problem is not with QRcode... you read the post?

**Comment by Klap-in** [comment]
Ah, I’m sorry. I mixed the barcode and qrcode. My purpose was to attend you on work that was already done. Your proposal sounds like doing something similar for the barcode, with easy validation options.

**Comment by finwe** [comment]
Closing Issue in favor of PR #1334
