### ISSUE TITLE
PHP8?

### ISSUE THREAD

**Issue by omexlu** [mpdf/mpdf#1337]
Hello,

I wanted to ask if the current version is compatible with PHP8 and if not for when that is expected to be the case?

Thanks in advance.

**Comment by Klap-in** [comment]
I’m sorry, do you have some spare time? Then it might be interesting to scroll a bit downward the issue list... There is already an issue regarding the PHP8, you might read it .. ;-)  #1263

**Comment by michaljusiega** [comment]
`composer require mpdf/mpdf:dev-php8-support`
