### ISSUE TITLE
$table['l'] is not assigned - yields undefined index at 20039

### ISSUE THREAD

**Issue by sunnyjayjay** [mpdf/mpdf#1339]
This may be a bug - only happens with tables which contain images. 

    $totalatextlength += $table['l'][$i];

Undefined index: l

Any suggestions for work around?

**Comment by Klap-in** [comment]
Please provide a small as possible example of your php and html code which let others reproduce your case. This case will be added as unit test to the test suite of this library as well. Thanks in advance for your effort of posting such an small example.

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
