### ISSUE TITLE
Is there support/workaround for CSS attribute selectors like a[href="string"]?

### ISSUE THREAD

**Issue by dhaupin** [mpdf/mpdf#134]
I am trying to target an `a` by using its `href` attribute - `a[href="string"]`, but its not working in mpdf. Is there support or a workaround for selecting via attrib? None of these work: `=`, `^=`, `*=`, `$=`.

The data I want to target needs removed across thousands of pages with various kinds of `a`. The OP's are not developers so its not reliable to assume that there will be a class on these `a` to target with then or in the future, but the links always go to the same destination.

Any thoughts are appreciated. Thanks!

**Comment by jakejackson1** [comment]
No. There's not support for that particular selector in mPDF at this time.

My advice is to pre-parse the DOM and make any modifications you need before sending it to mPDF. [I use Querypath](https://github.com/technosophos/querypath) myself but Symphony also [has components](http://symfony.com/doc/current/components/css_selector.html) to do that.

**Comment by dhaupin** [comment]
@jakejackson1 Figured that was the case. Thank you man, never heard of querypath. Seems useful in fringe cases such as this.
