### ISSUE TITLE
PHP 8 - Composer downgrades mpdf to version 6.1.3 

### ISSUE THREAD

**Issue by gpoehl** [mpdf/mpdf#1340]
### I found this bug / would like to have this new functionality
Using php 8 and executing 'composer update' will downgrade mpdf to version 6.1.3. 
This is because Mpdf 6.1.3 requires 
php: >=5.4.0
This is the latest version which matches the request.

Mpdf versions greater than 6.1.3 requires this php versions: 
"php": "^5.6 || ^7.0",

Please change line 34 in composer.json file to allow php 8.0 as well.

**Comment by finwe** [comment]
See pinned issue regarding PHP 8 support
