### ISSUE TITLE
Problem with PNG Images

### ISSUE THREAD

**Issue by gperler** [mpdf/mpdf#1341]
Mpdf\Image\ImageProcessor

In line 1088
`if (function_exists('gd_info')) // creates an error if the gd library is actually installed`

Changing it to:
`if (!function_exists('gd_info')) `
solved my problem.

I created a PR, but can't push it (missing permission)

**Comment by Klap-in** [comment]
Please use the issue template. Please share your minimal example of php and html that reproduce your situation. If you can create your pull request, please add also an unit test made from that example that shows that before the fix your unit test fails, and after your fix it is solved. Thanks!
Existing tests could serve as example for such a test https://github.com/mpdf/mpdf/tree/development/tests/Issues

Which versions of php, mpdf, gd, web server,etc, do you use?

**Comment by gperler** [comment]
You dont to Fix the bug? Ok for me...

Read the Ticket at least - you will underdstand the Problem Right away

Happy Christmas

Matěj Humpál <notifications@github.com> schrieb am Sa. 26. Dez. 2020 um
17:42:

**Comment by finwe** [comment]
Fixed in 0d95f19. Next time follow contribution guidelines.

**Comment by gperler** [comment]
Thank you very much. I couldnt Open pr because of missing permissions.

Happy Christmas

Matěj Humpál <notifications@github.com> schrieb am Sa. 26. Dez. 2020 um
17:50:

**Comment by finwe** [comment]
You have to fork the project and create the PR from the forked project. Thanks for the catch, anyway.
