### ISSUE TITLE
mpdf concatenate html and php inside  $html

### ISSUE THREAD

**Issue by Franck112** [mpdf/mpdf#1342]
I'm newbie...
My problem is that I have choosed the solution :
$html='mycode'';
$mpdf->WriteHTML($html);

inside mycode I have both php and html code, if I need to concatenate a variable is simple 
i.e. <p>'.$variable.'</p>
also if I need to include an if , I use the the ternary operator i.e.
<p>'.($age = ($age >= 18) ? true : false;).'</p>

but if I need to include a php cicle for what   can I do that ? 
many thanks to everybody  in advance !

**Comment by Franck112** [comment]
why closed?

**Comment by finwe** [comment]
Did you read the issue template before you deleted it?

**Comment by Franck112** [comment]
I found myself the solutions  concatenate tag html with the following syntax i.e.
<h1>word</h1>'; code php without open and close tag <?php and ?> and contatenate a variable string

**Comment by Franck112** [comment]
thanks a lot byez
