### ISSUE TITLE
Uninitialized string offset: 0 in file /Mpdf.php on line 16558

### ISSUE THREAD

**Issue by malikabi** [mpdf/mpdf#1343]
ErrorException: Uninitialized string offset: 0 in file /home/ambadmin/laravel-nova-and-api/vendor/mpdf/mpdf/src/Mpdf.php on line 16558
Stack trace:
  1. ErrorException-&gt;() /home/ambadmin/laravel-nova-and-api/vendor/mpdf/mpdf/src/Mpdf.php:16558
  2. Illuminate\Foundation\Bootstrap\HandleExceptions-&gt;handleError() /home/ambadmin/laravel-nova-and-api/vendor/mpdf/mpdf/src/Mpdf.php:16558
  3. Mpdf\Mpdf-&gt;_setBorderLine() /home/ambadmin/laravel-nova-and-api/vendor/mpdf/mpdf/src/Mpdf.php:16785
  4. Mpdf\Mpdf-&gt;PaintDivBB() /home/ambadmin/laravel-nova-and-api/vendor/mpdf/mpdf/src/Tag/BlockTag.php:1125
  5. Mpdf\Tag\BlockTag-&gt;close() /home/ambadmin/laravel-nova-and-api/vendor/mpdf/mpdf/src/Tag.php:250
  6. Mpdf\Tag-&gt;CloseTag() /home/ambadmin/laravel-nova-and-api/vendor/mpdf/mpdf/src/Mpdf.php:13662
  7. Mpdf\Mpdf-&gt;WriteHTML() /home/ambadmin/laravel-nova-and-api/app/Http/Controllers/Admin/AirWayBill/AirWayBillMenifestController.php:1274
  8. App\Http\Controllers\Admin\AirWayBill\AirWayBillMenifestController-&gt;exportAirwayBillInvoicesAll() /home/ambadmin/laravel-nova-and-api/vendor/laravel/framework/src/Illuminate/Routing/Controller.
  
  
  I have added !empty($b['c']) check to fix this issue on line number 16558 mpdf.php
  if(!empty($b['c'])){
	if ($b['c'][0] == 5) { // RGBa
		$this->SetAlpha(ord($b['c'][4]) / 100, 'Normal', false, 'S'); // mPDF 5.7.2
	} elseif ($b['c'][0] == 6) { // CMYKa
		$this->SetAlpha(ord($b['c'][5]) / 100, 'Normal', false, 'S'); // mPDF 5.7.2
	}
}

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
