### ISSUE TITLE
Bug in Mpdf.php in setting $TTCfontID results in TTCfontID 1 being embedded repeatedly

### ISSUE THREAD

**Issue by mikaelsheikh** [mpdf/mpdf#1351]
### I found this bug

Mpdf.php line 3859 (v7.1.9) is:

$TTCfontID = isset($this->fontdata[$family]['TTCfontID'][$stylekey]) ? isset($this->fontdata[$family]['TTCfontID'][$stylekey]) : 0;

The isset in the then clause is incorrect -- results in $TTCfontID = 1 assignment

Corrected:

$TTCfontID = isset($this->fontdata[$family]['TTCfontID'][$stylekey]) ? $this->fontdata[$family]['TTCfontID'][$stylekey] : 0;

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

mPDF 7.1.9 and 8.0.8
PHP version is irrelevant

### This is a PHP code snippet I use

not relevant

### This is a HTML/CSS code snippet I use

not relevant

**Comment by finwe** [comment]
The PHP code is relevant for testing purposes. Please add.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
