### ISSUE TITLE
Failed when composer downloading mpdf 

### ISSUE THREAD

**Issue by mhaitsam18** [mpdf/mpdf#1354]
C:\xampp\htdocs\presensi\vendor>composer require mpdf/mpdf
Using version ^8.0 for mpdf/mpdf
./composer.json has been updated
Running composer update mpdf/mpdf
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading mpdf/mpdf (v8.0.10)
  - Downloading mpdf/mpdf (v8.0.10)
  - Downloading mpdf/mpdf (v8.0.10)
  - Downloading mpdf/mpdf (v8.0.10)
    **Failed to download mpdf/mpdf from dist: curl error 28 while downloading https://codeload.github.com/mpdf/mpdf/legacy.zip/1333a962cd2f7ae1a127b7534b7734b58179186f: Operation timed out after 300000 milliseconds with 25825474 out of 46573935 bytes received
    Now trying to download from source**
  - Installing mpdf/mpdf (v8.0.10): Cloning 1333a962cd
    Install of mpdf/mpdf failed

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

  [RuntimeException]
  **Failed to clone https://github.com/mpdf/mpdf.git, git was not found, check that it is installed and in your PATH en
  v.  'git' is not recognized as an internal or external command,
  operable program or batch file.**

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

**Comment by ssieb** [comment]
How is this a bug with mpdf?

**Comment by ntgraph** [comment]
same issue with my laravel project, when hit composer update, mpdf is the one that is not updated

**Comment by ds620107** [comment]
I have the same issue, did anyone find a solution for this problem??
