### ISSUE TITLE
border "inset 1.0pt" Exception (invalid color input)

### ISSUE THREAD

**Issue by timglabisch** [mpdf/mpdf#1356]
There is an exception when parsing: `border-left:inset 1.0pt;`
MSOffice may generate such html when copy & pasting from it.

there are multiple issues here:

-  [CssManager.php](https://github.com/mpdf/mpdf/blob/13d70e778eb8c78dd3ff8dbc60d7736e92e88c76/src/CssManager.php#L527) is not able to parse "inset 1.0pt"
- The ColorConverter [may returns an empty string](https://github.com/mpdf/mpdf/blob/13d70e778eb8c78dd3ff8dbc60d7736e92e88c76/src/Color/ColorConverter.php#L53) but for example the lighten functions [expects the color to be a binaryColor](https://github.com/mpdf/mpdf/blob/13d70e778eb8c78dd3ff8dbc60d7736e92e88c76/src/Color/ColorConverter.php#L65).

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mpdf version: 1333a96 
PHP 7.4.13

### This is a PHP code snippet I use

```php
$mpdf = new Mpdf();
$mpdf->WriteHTML('<table><tbody><tr><td style="border-left:inset 1.0pt;"><br></td></tr></tbody></table>');
$mpdf->Output();

```

### This is a HTML/CSS code snippet I use

```html
<table><tbody><tr><td style="border-left:inset 1.0pt;"><br></td></tr></tbody></table>
``` 

<img width="1071" alt="Screen Shot 2021-01-18 at 15 49 28" src="https://user-images.githubusercontent.com/689269/104929895-c6d09880-59a4-11eb-9a67-f13b58b0d588.png">

**Comment by finwe** [comment]
If I understand the [border definition](https://developer.mozilla.org/en-US/docs/Web/CSS/border) correctly, the expected order of parameters is width-style, which the `inset 1.0pt` does not comply to. Does this error persist with `1.0pt inset`?

**Comment by finwe** [comment]
Please create separate issues for separate bugs (which the unexpected color output is)

**Comment by timglabisch** [comment]
you are right, "inset 1.0pt" is malformed. i am going to close this issue and create a new one.
