### ISSUE TITLE
Can't download from Composer

### ISSUE THREAD

**Issue by lgruz** [mpdf/mpdf#1360]
Hi!
I'm trying to install mPDF with Composer, but download stay at 0%. I can install any other package, and even I can download mPDF manually. What's the problem?

Thanks

**Comment by lgruz** [comment]
@finwe Why are you closing all issues related with this problem?

**Comment by finwe** [comment]
None of them are directly related to mPDF. None of them follow contribution guidelines.

**Comment by finwe** [comment]
See #1362
