### ISSUE TITLE
mpdf SetSourceFile Issue

### ISSUE THREAD

**Issue by jacklovebella** [mpdf/mpdf#1364]
$mpdf=new \Mpdf\Mpdf();

$mpdf->SetSourceFile("./13_55_1002_2.pdf");

file address: http://dzjd.54gujie.site/static/case/2021/13_55_1002_2.pdf

problem：The watermark on the first page will disappear when the PDF file is regenerated from the reference template

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details.
