### ISSUE TITLE
Producer Tag Manipulate

### ISSUE THREAD

**Issue by aditya-the-pro** [mpdf/mpdf#1371]
There should be producer tag changer config param also as seen in src/Metadatawriter changing on line 154 and $producer in line 54 we can change it.
why not make it as a feature?

**Comment by aditya-the-pro** [comment]
For Example :- $mpdf->SetProducer('Lorem Ipsum');

**Comment by finwe** [comment]
From PDF Reference:

> *Producer* text string _(Optional)_ If the document was converted to PDF from another format, the name of the application (for example, Acrobat Distiller) that converted it to PDF.

The application name converting the document *is* mPDF.

**Comment by aditya-the-pro** [comment]
> From PDF Reference:
> 
> > _Producer_ text string _(Optional)_ If the document was converted to PDF from another format, the name of the application (for example, Acrobat Distiller) that converted it to PDF.
> 
> The application name converting the document _is_ mPDF.

I know but, I just thought to customize it.
