### ISSUE TITLE
Line breaks are not being rendered in pdf file

### ISSUE THREAD

**Issue by neeket** [mpdf/mpdf#1372]
In database (MariaDB), text is saved in column (datatype: text) like:
apple
mango
ball

But while rendering using PHP/Codeigniter, PDF output is as: applemangoball.

Line breaks are not rendered. Same thing happened with more than one spaces but solved that issue.

Tried using nl2br() function in PHP, but doesn't work.
Any idea how to fix this?

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
