### ISSUE TITLE
Configuration option for CURLOPT_TIMEOUT

### ISSUE THREAD

**Issue by pdscopes** [mpdf/mpdf#1376]
At the moment the library allows you to specify the connection timeout for cURL requests via the `curlTimeout` configuration option. However, I have encountered an issue when downloading images from certain websites (e.g., staples[dot]co[dot]uk) which allow the connection but never actually send any data for the image.

I would like to add a new configuration option to specify `CURLOPT_TIMEOUT` and I am happy to create a PR for this however I cannot think of a good name as `curlTimeout` is already taken and I don't want to introduce backwards incompatibility into the library. If we did introduce backwards incompatibility it'd look something like this:

```diff
diff --git a/src/Mpdf.php b/src/Mpdf.php
--- a/src/Mpdf.php
+++ b/src/Mpdf.php

	/**
-	 * Set connection for cURL
+	 * Set connection timeout for cURL
	 *
	 * @var int
	 */
-	var $curlTimeout;
+	var $curlConnectTimeout;
+
+	/**
+	 * Set timeout for cURL
+	 *
+	 * @var int
+	 */
+	var $curlTimeout;
```

```diff
diff --git a/src/Config/ConfigVariables.php b/src/Config/ConfigVariables.php
--- a/src/Config/ConfigVariables.php
+++ b/src/Config/ConfigVariables.php

			'curlCaCertificate' => '',
+			'curlConnectTimeout' => 5,
-			'curlTimeout' => 5,
+			'curlTimeout' => null,
			'curlProxy' => null,
```

```diff
diff --git a/src/RemoteContentFetcher.php b/src/RemoteContentFetcher.php
--- a/src/RemoteContentFetcher.php
+++ b/src/RemoteContentFetcher.php


		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
-		curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $this->mpdf->curlTimeout);
+		curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $this->mpdf->curlConnectTimeout);
+
+		if ($this->mpdf->curlTimeout) {
+			curl_setopt($ch, CURLOPT_TIMEOUT, $this->mpdf->curlTimeout);
+		}

		if ($this->mpdf->curlFollowLocation) {
			curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
		}

**Comment by finwe** [comment]
This is a reasonable change, but as the whole remote content fetching is to be reviewed and revised for the next major version (with configurable adapters), and this is would be a breaking change, therefore applicable to the next major release, it does not make sense to rush this. Maybe a temporary undecomented configuration variable with non-conflicting name could be used in the meantime as there is not an ETA for the next major version.

**Comment by pdscopes** [comment]
Thank you for your quick response!

> the whole remote content fetching is to be reviewed and revised for the next major version (with configurable adapters
That is really exciting to hear!

I'm happy to make a PR using the non-conflicting name `curlExecutionTimeout`, would that be okay?

**Comment by finwe** [comment]
Yes, thanks.
