### ISSUE TITLE
annotation feature

### ISSUE THREAD

**Issue by arcanisgk** [mpdf/mpdf#1379]
https://mpdf.github.io/reference/html-control-tags/annotation.html

i am implementing annotation feature in line tag; 
but i only find example with icon add like this:

`some text <annotation content="text inside popup" />`

output in google chrome (it doesn't look very pretty when used inside tables.):

![image](https://user-images.githubusercontent.com/1207306/106783785-ab5ac400-6619-11eb-92a3-fb156b7d4651.png)

**_Is there a way to use the text as an icon and wrap it with an annotation, and avoid using icons. the idea is that when you pass the cursor in the text, the annotation popup appears?_**

example:
`<annotation content="text inside popup" icon="none">some text</annotation>`

or add suppot custom tags like:

`<span data-annotation="content:text inside popup; icon:none" >some text</span>`

**Comment by arcanisgk** [comment]
@finwe  did you close it without saying anything ???

**Comment by finwe** [comment]
You are not new here. General questions and troubleshooting do not belong here. Read the issue template and contribution guidelines.

**Comment by arcanisgk** [comment]
> You are not new here. General questions and troubleshooting do not belong here. Read the issue template and contribution guidelines.

When I entered to request feature, git hub redirect me to this:

![image](https://user-images.githubusercontent.com/1207306/106805724-0c43c580-6635-11eb-94c4-60b9c2f656c7.png)

**Comment by finwe** [comment]
This is not a feature request, this is a general troubleshooting. There is not even the heading from the issue template left indicating this should be a feature request. The wording is a simple question, not a plea, not a suggestion, not a request.

**Comment by arcanisgk** [comment]
> This is not a feature request, this is a general troubleshooting. There is not even the heading from the issue template left indicating this should be a feature request. The wording is a simple question, not a plea, not a suggestion, not a request.

Look, I'm not having any problems with the `annotation()` function or the` <annotation>` tag.

since I don't have a problem, I don't know what you are basing on to suppose or say that it is a general problem.

I am asking if there is currently the option to wrap a text with the html` <annotation>` tag.

If this option does not exist, I ask you if you can improve the current function (request Feature enhancement) that uses `<annotation>` tag to wrap text instead of insert a icon.

If you don't have the ability to understand the scenario of what I'm asking, we leave it there ... I don't have time to argue with unfriendly people.

**Comment by finwe** [comment]
> I am asking if there is currently the option to wrap a text with the html <annotation> tag.

Yes, therefore your Issue is not a feature request, but a general question. Not belonging here.

> If this option does not exist, I ask you if you can improve the current function

Yes, you are asking for a feature just now, there was nothing resembling a feature request until this last message.

Yes, let's leave it here.
