### ISSUE TITLE
Row borders not shown in table

### ISSUE THREAD

**Issue by jimAC2016** [mpdf/mpdf#138]
I'm making a Wordpress module to reserve a room. Now I use mPDF to create the contracts of the reservations automatically.

mPDF has problems with creating tables with on every row a border line. When I create the table and view it in html everything looks fine. But when I create a PDF with mPDF the does not show me the row bottom border.

This is the html code that I use to generate the pdf:

`.logo
{
    display: inline-block;
    width: 130;
    height: 146;
    align: left;
    hspace: 12;
}

.headerText
{
    display:inline-block;
    text-align: right;
    float:right;
}

.header{
    padding-bottom: 20px;
}

.table{
    border-left: thin solid;
    border-right: thin solid;
    border-bottom: thin solid #000000;
    border-top: thin solid;
}

.table{
    margin-top: 10px;
    margin-bottom: 10px;
    border-collapse: collapse;
}

table tr {
    border-bottom: 1px solid black;
}

table tr:last-child { 
    border-bottom: none; 
}

.Cell
{

    width: 300px;
}

.firstCell
{
    border-left: thin;
    border-right: thin solid;
    border-bottom: thin;
    border-top: thin;
}

.smallCell
{
    width:150px;
}

.largeCell
{
    width: 450px;
}

.row
{
    display: block;
}

.koninklijkeLogo
{
    width: 30px;
}

.maxSize
{
    width: 600px;
}`

` <table class="table">
            <tr class="row">
                <td class="smallCell firstCell">Naam:</td>
                <td class="largeCell">{%name%}</td>
            </tr>
            <tr class="row">
                <td class="smallCell firstCell">Adres:</td>
                <td class="largeCell">{%adres%}</td>
            </tr>
            <tr class="row">
                <td class="smallCell firstCell">Telefoonnummer:</td>
                <td class="largeCell">{%phone%}</td>
            </tr>
            <tr class="row">
                <td class="smallCell firstCell">E-mailadres:</td>
                <td class="largeCell">{%mail%}</td>
            </tr>
        </table>`

**Comment by finwe** [comment]
mPDF cannot display border for table row, not even for `collapse` `border-collapse`. Give the border to table cells instead of rows:

```
table tr td {
	border-bottom: 1px solid black;
}

table tr:last-child td {
	border-bottom: none;
}
```

Also, it is not a good idea to override table row display to `block`.
