### ISSUE TITLE
could not generate pdf

### ISSUE THREAD

**Issue by robinvibs10** [mpdf/mpdf#1380]
### I found this bug

I am getting this error message.

![image](https://user-images.githubusercontent.com/18256271/106928973-c2e79900-674e-11eb-9751-4ed09a1ca8e1.png)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

php version 7.3
mpdf version 7.1.7

### This is a PHP code snippet I use

```
<?php

require('mpdf/vendor/autoload.php');

                        $mpdf = new \Mpdf\Mpdf();
                        $mpdf = new \Mpdf\Mpdf(['debug' => true]);

                        $mpdf->Bookmark('Start of the document');
                        $mpdf->WriteHTML('<div>Section 1 text</div>');
                        
                        $mpdf->Output();


```

### This is a HTML/CSS code snippet I use

```

```

**Comment by Klap-in** [comment]
Please note that troubleshooting should not be done in this issue tracker, please use the Stackoverflow instead.

And why did you ignore the template? Without your information we aren't able to reproduce your case...
Please provide a small as possible example of the html and php code with which you can trigger this situation.

**Comment by robinvibs10** [comment]
> Please note that troubleshooting should not be done in this issue tracker, please use the Stackoverflow instead.
> 
> And why did you ignore the template? Without your information we aren't able to reproduce your case...
> Please provide a small as possible example of the html and php code with which you can trigger this situation.

done updating it.

**Comment by ssieb** [comment]
How is that screenshot an error message?  You need to provide more details on what isn't working and what you expect.

**Comment by finwe** [comment]
https://mpdf.github.io/troubleshooting/strange-character-output-in-browser.html
