### ISSUE TITLE
PHP 8.1 Deprecations

### ISSUE THREAD

**Issue by oleibman** [mpdf/mpdf#1383]
### I found this bug
PHP8.1 has changed to deprecate passing null to certain built-in functions where a string is expected. The following code around line 6564 in src/Mpdf.ph triggers a problem:
```php
		if (isset($font[count($font) - 1])) {
			$lastfontreqstyle = (isset($font[count($font) - 1]['ReqFontStyle']) ? $font[count($font) - 1]['ReqFontStyle'] : '');
			$lastfontstyle = (isset($font[count($font) - 1]['style']) ? $font[count($font) - 1]['style'] : '');
		} else {
			$lastfontreqstyle = null;
			$lastfontstyle = null;
		}
		if ($blockdir == 'ltr' && strpos($lastfontreqstyle, "I") !== false && strpos($lastfontstyle, "I") === false) { // Artificial italic
```
Rather than setting lastfontreqstyle and lastfontstyle to null, setting them to a null string should eliminate that problem. I don't know that such a change won't cause regression problems elsewhere, nor do I know whether this is the full extent of the problem.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
This is a problem only with the most recent version of PHP 8.1.

**Comment by finwe** [comment]
There will be many more incompatibilities with PHP 8.1 and they will be addressed all at once. There is not much point creating issues for each of these separately.

PHP 8.1 support will at the soonest be addressed as the release date approaches.
