### ISSUE TITLE
Cache read permission error when running mpdf by different users (www-data and other)

### ISSUE THREAD

**Issue by deadkrolik** [mpdf/mpdf#1386]
### I found this bug
When I run console command, which creates PDF document, and then run http-endpoint which creates another PDF document. They both use the same cache directory {TMP}/mpdf/ttfontdata/. Because nginx running by www-data user, and console command started by another user they can't just read cache, which created by another user. Clear cache after run is a bad idea for me.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
v8.0.10, but the same code is in development branch

In src/Cache.php on line 75 we have a method write() which calls file_put_contents() to save file. My suggestion is to add chmod(666) for this file, as in method createDirectory(), to ensure that this file will be readable for other users. Or create config option for such chmod mask. And then, cache files will be be shared by different users without problems.

**Comment by finwe** [comment]
Not a bug. It is your responsibility to set up filesystem privileges for temp files be accessible by all users running mPDF.
