### ISSUE TITLE
Undefined variable: glyphIDtoUni 

### ISSUE THREAD

**Issue by josemarneri** [mpdf/mpdf#1392]
### I found this bug
I am creanting a pdf file by  \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Mpdf'), 
but I had this error:
ErrorException
Undefined variable: glyphIDtoUni 

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
C:\wamp64\www\sge\vendor\mpdf\mpdf\src\Mpdf.php:3963

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
version ^8.0 for mpdf/mpdf

### This is a PHP code snippet I use

```
<?php


```

### This is a HTML/CSS code snippet I use

```
Anyone can help me?

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by inubayuaji** [comment]
I got same error, I don't know why this error happen.
For quick solution I change code `'glyphIDtoUni' => $glyphIDtoUni,` to `'glyphIDtoUni' => null,` at file `vendor\mpdf\mpdf\src\Mpdf.php` line 3990. I know this is not good solution but for now I will use this.

**Comment by saurabhbcadev** [comment]
go to .....\vendor\mpdf\mpdf\src\ Mpdf.php line number 3989 and replace the existing code with - 
	'glyphIDtoUni' => isset($glyphIDtoUni) ? $glyphIDtoUni : '',
