### ISSUE TITLE
File attachments as annotations doesn't work with digital signature

### ISSUE THREAD

**Issue by Lzolcsi** [mpdf/mpdf#1393]
Hi there,

I have the following scenario: I create invoices and generate a PDF version of them with mPDF. Then I need to attach an XML file to it. I'm using Annotation to do that, by appending the following to the end of the HTML code:
<annotation file="sample.xml" content="Sample XML" />
The PDF then gets generated and everything seems fine. But I also need to sign this PDF with a digital signature and add a timestamp to it. I'm using SetaPDF-Signer to do that. However, after signing Adobe Reader gives me an error, that the file was altered and the Annotation was added after signing the document. Normally I would say this might be an issue with the signer, however I found an interesting workaround:
I generate and save the PDF with mPDF without any annotations. Then using FPDI and FPDF I open that generated PDF file. After that, I use the following script to add the XML attachment: http://www.fpdf.org/en/script/script95.php. And after that I use SetaPDF to sign and timestamp the document and everything works perfectly. 
But of course this is a bit tedious and unneccessary. So I thought maybe you could shed some light for me on what is different with the attachment handling using the two methods and maybe make it possible to use the same method in mPDF?

Thanks,
Zoltan

**Comment by finwe** [comment]
Closing as this is neither a bug report or a feature request.
