### ISSUE TITLE
Problem with SVG and PHP 8

### ISSUE THREAD

**Issue by fabiochelly** [mpdf/mpdf#1395]
Since my webserver has upgraded from PHP 7.4 to PHP 8, I get a fatal error when I try to draw an SVG picture on a PDF:

`Uncaught TypeError: Unsupported operand types: string * float in /.../vendor/mpdf/mpdf/src/Image/Svg.php:1477`

The problem is caused by this line:
```php
$arr .= sprintf('%.3F %.3F ', $d[$i] * $this->kp, $d[$i + 1] * $this->kp);
```

where $d[$i] and $d[$i + 1] both contain the string "none"

I fixed it like this:
```php
$arr .= sprintf('%.3F %.3F ', (float)$d[$i] * $this->kp, (float)$d[$i + 1] * $this->kp);
```

**Comment by finwe** [comment]
Not really helpful. That issue template is not there for nothing, you know. How do you initialize the Mpdf object? Share a small HTML/SVG snippet reproducing this behaviour.

**Comment by fabiochelly** [comment]
Here is my example code and the SVG that provokes the fatal error:
[image.zip](https://github.com/mpdf/mpdf/files/6078092/image.zip)

```php
$mpdf = new Mpdf\Mpdf();
$mpdf->AddPage();
$mpdf->WriteHTML('<img src="' . __DIR__ . '/image.svg" />');
$mpdf->Output(__DIR__ . '/test.pdf', 'F');
```

**Comment by satish123satish123** [comment]
I am using latest mpdf version 8.2 still getting same error. I fixed issue same as @fabiochelly .
