### ISSUE TITLE
Undefined offset: 1 in Mpdf.php:27096

### ISSUE THREAD

**Issue by kikig1** [mpdf/mpdf#1400]
With mpdf 8.0 i try to set only some values in an existing pdf and save it with another name.

`
        $mpdf = new \Mpdf\Mpdf();
        $mpdf->percentSubset = 0;

        $search = array(
            '{baustellestr}'
        );
        
        $replacement = array(
            "Donaldweg 13"
        );
        $vorlage = public_path() . '/img/Fachbauleitererkl.pdf';
        $ausgabe = public_path() . '/img/'. $projekt->projekt . "_FachbauLeiterErkl.pdf";
        var_dump(file_exists($vorlage));
        $mpdf->OverWrite($vorlage, $search, $replacement, 'F', $ausgabe ) ;        
        return redirect()->back()->with('success', 'Vorschau erstellt');
`
with hthis code i get the error.
![grafik](https://user-images.githubusercontent.com/33813116/111615757-63ff5000-87e1-11eb-85c9-2b5bbb9ef0e9.png)

in $pdf there is a lot of stuff for example
![grafik](https://user-images.githubusercontent.com/33813116/111615989-a759be80-87e1-11eb-967c-72c74f5e28fa.png)

and 
![grafik](https://user-images.githubusercontent.com/33813116/111616021-afb1f980-87e1-11eb-9879-dc08ceb362c6.png)

and 
![grafik](https://user-images.githubusercontent.com/33813116/111616517-42eb2f00-87e2-11eb-9fdf-92d22b911e6f.png)

 What can i change or what is wrong?

Thanks for any Tip :)

**Comment by finwe** [comment]
Closing as missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
