### ISSUE TITLE
radio button and checkboxes

### ISSUE THREAD

**Issue by godara-ravi** [mpdf/mpdf#1403]
### I found this bug: Radio button and checkboxes are not filled in the saved pdf output.

I tried to fill out here and save with my changes. Someone can look into this?

https://osuch.com/formtools/exp/mpdfexp/project_mpdf/pdfb04_basic_active_form.php

My saved pdf output:
[pdfb04_basic_active_form.php.pdf](https://github.com/mpdf/mpdf/files/6241310/pdfb04_basic_active_form.php.pdf)

Thanks.

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by godara-ravi** [comment]
If i am open downloaded pdf in browser then its showing but if i am open this directly then radio button and checkbox not working as they should. Please look into this!
[Screenshot 2021-04-01 at 10 21 55 PM](https://user-images.githubusercontent.com/47026411/113327872-19c9b300-9339-11eb-9d09-47951de25f36.png)
