### ISSUE TITLE
Making the variable placeholder {} configurable

### ISSUE THREAD

**Issue by Moongazer** [mpdf/mpdf#1406]
# Feature request

I'd suggest to make the variable placeholders `{}` e.g. for `{nb}` and `{PAGENO}` configurable. The reason behind this is, that these placeholders are also used widely in certain template engines. We're using [Fluid](https://typo3.org/fluid) for example for creating the HTML code used in mpdf. The variable placeholder in Fluid are `{myVarable}`, which means its impossible to use the mpdf variables in such templates, as `{PAGENO}` will be replaced by an empty string during the template rendering (input for mpdf).

```
// example implementation: setVariablePlaceholder() will split the parameter at | into an opening and closing part
$mpdf->setVariablePlaceholder('{|}'); // default: will replace {PAGENO}
$mpdf->setVariablePlaceholder('[|]'); // will replace [PAGENO]
$mpdf->setVariablePlaceholder('###|###'); // will replace ###PAGENO###
```
Instead of using such method, the option can also be defined in the mpdfConfig as it should be static (there is no need to change it during runtime I guess).

**Comment by Klap-in** [comment]
Please see https://mpdf.github.io/what-else-can-i-do/replaceable-aliases.html For some of the replaceable variables there are aliases.

**Comment by Moongazer** [comment]
I know, but this applies only for `{nb​}` and `{nbpg​}` and not for the much more useful `{PAGENO}`, that's why IMO its a bit useless if its not possible to change ALL placeholders to an alias.

**Comment by finwe** [comment]
This does not make much sense IMHO. Surely the template engine must have some sort of escaping to get the expected string into mPDF.
