### ISSUE TITLE
MarkGlyphSets error using SIL's "Schehezade" font

### ISSUE THREAD

**Issue by JasonPamir** [mpdf/mpdf#1408]
### **MarkGlyphSets error when using SIL Schehezade font**

> Uncaught Mpdf\Exception\FontException: This font scheherazade contains MarkGlyphSets - Not tested yet in .../vendor/mpdf/mpdf/src/TTFontFile.php:2963

**Code to reproduce** (using either the font Schehezade or Schehezade New, from SIL):

```
        <?php 
        require_once 'lib/vendor/autoload.php';
	// Get existing font data (to which we will append our fonts)
	$defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
	$fontData = $defaultFontConfig['fontdata'];

	$pdf = new Mpdf\Mpdf([
		'mode' => 'utf-8', 
		'format' => [90,180],
		'fontdata' => $fontData + [
			'scheherazade' => [
				'R' => 'Scheherazade-Regular.ttf',
				'B' => 'Scheherazade-Bold.ttf',
				'useOTL' => 0xFF,
				'useKashida' => 75,
			]
		],
		'default_font' => 'scheherazade'
	]);
        ?>
```

**Other info**
"Schehezade" produces the MarkGlyphSets error mentioned above, and "Schehezade New" produces the same error with additional non-fatal notices:  

> Notice: Undefined offset: in /mpdf/mpdf/src/TTFontFile.php on line 3190.

**Attaching fonts: (also available from SIL)**
[Scheherazade-2.100.zip](https://github.com/mpdf/mpdf/files/6290154/Scheherazade-2.100.zip)
[ScheherazadeNew-3.100.zip](https://github.com/mpdf/mpdf/files/6290155/ScheherazadeNew-3.100.zip)

**Comment by fglueck** [comment]
I have the same problem with notosansdis.
The sign with make the problem was the backtick before 25: "Drive  ́25"

`This font [notosansdis] contains MarkGlyphSets - Not tested yet`

**Comment by finwe** [comment]
This does not seem to be as a bug, given the error, fonts with MarkGlyphSets are just not supported. Changed the exception message to be more descriptive.
