### ISSUE TITLE
add image support for OverWrite

### ISSUE THREAD

**Issue by BernhardBaumrock** [mpdf/mpdf#1411]
# Feature request

Would it be possible to add support for images in `OverWrite()` ? That would be absolutely great, because I'm developing some kind of dynamic PDF contract tool and there I do not only need to fill placeholders by values but I'd also like to add a signature to that PDF at a position specified by the client.

```
Curabitur blandit mollis lacus.
In ac felis quis tortor malesuada pretium.

{signature}
{date}
```

The image could have predefined dimensions of course :)

Thx for considering!

**Comment by finwe** [comment]
Overwrite is limited by definition and format of PDF file. It is far beond its scope to alter the binary contents of a PDF document to alter images, it sometimes fails even with simple text. So, no, sorry.

**Comment by BernhardBaumrock** [comment]
Ok thx for the clear statement 👍
