### ISSUE TITLE
Mb_regex_encoding on mamp windows

### ISSUE THREAD

**Issue by khairilazizee** [mpdf/mpdf#1413]
Hi. I am using mamp on windows. When i try to load the mpdf. I got error mb_regex_encoding. I already enable gd and mbstring extension. 

I am using mpdf in laravel 6. 

What else should i look at?

**Comment by damncorwell** [comment]
Got the same problem and still don't know what to do.

**Comment by hantc** [comment]
Same here - my colleague has this particular problem. Btw why this issue was closed?

**Comment by Klap-in** [comment]
This sounds, so far, more like troubleshooting than a real bug in the mpdf library. Please use https://stackoverflow.com/questions/tagged/mpdf for troubleshooting.

Further, if it appears to be a real bug, you could create a new bug report here. Please include in the issue the versions of the softwares, the smallest php+html example that demonstrates the case and the actual error messages. With current issue report, someone has to guess a lot before he could reproduce the case. Thanks for the effort!

**Comment by finwe** [comment]
See https://stackoverflow.com/a/67653441/819007
