### ISSUE TITLE
PHP 8.0 Version Problem

### ISSUE THREAD

**Issue by zahidmzhmm** [mpdf/mpdf#1420]
Problem 1
    - mpdf/mpdf[v8.0.0, ..., v8.0.3] require php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your php version (8.0.3) does not satisfy that requirement.
    - mpdf/mpdf[v8.0.4, ..., v8.0.7] require php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 -> your php version (8.0.3) does not satisfy that requirement.
    - mpdf/mpdf[v8.0.8, ..., v8.0.9] require php ^5.6 || ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
    - mpdf/mpdf v8.0.10 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - Root composer.json requires mpdf/mpdf ^8.0 -> satisfiable by mpdf/mpdf[v8.0.0, ..., v8.0.10].

To enable extensions, verify that they are enabled in your .ini files:
    - H:\Server2.0\php\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.

**Comment by HarshitAranya** [comment]
i have the same issue. is there any solution ?

**Comment by alimalek80** [comment]
I have same issue.
