### ISSUE TITLE
{colsum} format

### ISSUE THREAD

**Issue by meruemer** [mpdf/mpdf#1424]
### I found this bug
I am unable to format the number total of function {colsum}, it always shows no comma separator for large amounts.

### This is a PHP code snippet I use
<td class="row-item-no" name="subTotal" style="border-right:blank;border-top:1px solid black;"><b>{colsum2}</b></td>
```
<?php
![Screenshot 2021-05-05 085244](https://user-images.githubusercontent.com/31300356/117086711-ee931300-ad7f-11eb-919e-20785e6455fe.png)


```

```

**Comment by finwe** [comment]
Not a bug, decimal separator is not supported. If you need more control over the format, provide the formatted number from your code.

**Comment by meruemer** [comment]
Sorry for taking it as a bug. Thank you for your response.

**Comment by acdona** [comment]
> ### I found this bug
> I am unable to format the number total of function {colsum}, it always shows no comma separator for large amounts.
> 
> ### This is a PHP code snippet I use
> {colsum2} ``` ` `
Search for $rep in the Mpdf.php file and add it below: 
```
$rep = number_format($rep, 2, '.', ',');
```
There are two lines to be added

**Comment by meruemer** [comment]
Thanks, I'll check it out.
