### ISSUE TITLE
Quiet zones customization

### ISSUE THREAD

**Issue by vincenzo-mennella-shippypro** [mpdf/mpdf#1430]
# Feature request

Hi,
I need to created a mixed barcode made up of mixed `EAN128B` and `EAN128C`. 

Putting 
```html
<barcode code="1234" type="EAN128B" /><barcode code="5678" type="EAN128C" />
```
works but two quiet zones are added around each barcode which, of course, I don't need since it must look like a single barcode.

Is it possible to add a quiet zone customization functionality?

Thank you!

**Comment by vincenzo-mennella-shippypro** [comment]
Hi! Do you have any feedback on this? Do you think this will be implemented? Any workaround to suggest?

Thank you!

**Comment by finwe** [comment]
Note the help wanted tag. If you need this implemented, find a developer to propose a pull request.

**Comment by vincenzo-mennella-shippypro** [comment]
> Note the help wanted tag. If you need this implemented, find a developer to propose a pull request.

Hi, I sent PR #1439 which implements this feature
