### ISSUE TITLE
Create temp files as 664 or 644 insted of 600

### ISSUE THREAD

**Issue by realtebo** [mpdf/mpdf#1431]
# Feature request

When mPDF creates temp files for ttf fonts, files are being create with 600 as pemissions.

This creates a big problem when we use mPdf both from current user (because of script executed from command line) and both from web sites.

If mpdf executed first into a command line script, we come into situation where files are created a user:user and permission 600; so www-data cannot read these files.

If otherwise it executed first as www-data, files are owned by www-data:www-data with 600, and so from command line we have an exception  becase shell user cannot read these files.

Consider this a problem because we're doing automatic deploying and autoscaling. We cannot do a manual run after each composer install only to alter permissions to 664 or 644

**Comment by finwe** [comment]
Changed in 57f8c89 and released as v8.0.11.
