### ISSUE TITLE
PDF preamble repeated at start of file

### ISSUE THREAD

**Issue by hituro** [mpdf/mpdf#1433]
### The PDF preamble (version string) is repeated at the start of the file.

I am outputting a simple DF using writehtml(). At the start of the file, the version string is repeated five times: (Not sure how to re-open my previous post, which lacked the working example, so here's a new version)

```
%PDF-1.4
%‚„œ”
```
e.g.
```
%PDF-1.4
%‚„œ”
%PDF-1.4
%‚„œ”
%PDF-1.4
%‚„œ”
%PDF-1.4
%‚„œ”
%PDF-1.4
%‚„œ”
3 0 obj
<</Type /Page
```

This isn't causing me any problems, but at the same time I'm pretty sure that it isn't intentional either. 

My feeling is that it is to do with the <htmlpageheader> tags.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

MPDF 8.0.10, PHP 7.3.27

### The following minimal example produces this behaviour

```
<?php
require_once __DIR__ . '/vendor/autoload.php';

        $mpdf = new \Mpdf\Mpdf([
            'format' => 'A5-P'
        ]);
        $mpdf->WriteHTML("<!DOCTYPE html>
                <head>
                <title>Test</title>
                </head>
                <body>
                <htmlpageheader name=\"firstpageheader\" style=\"display:none\">
                </htmlpageheader>
                
                <htmlpagefooter name=\"firstpagefooter\" style=\"display:none\">
                </htmlpagefooter>
                
                <htmlpageheader name=\"otherpageheader\" style=\"display:none\">
                </htmlpageheader>
                
                <htmlpagefooter name=\"otherpagefooter\" style=\"display:none\">
                    <div class='footer'>{PAGENO}</div>
                </htmlpagefooter>
                <h3>Hello World</h3></body>
                </html>");
        $mpdf->Output();
```

**Comment by finwe** [comment]
Thanks for clarification. Sorry for the confusion with reopening, I just found out that the issue author cannot reopen, I was under the impression this was possible.
