### ISSUE TITLE
Call to undefined function Mpdf\mb_regex_encoding()

### ISSUE THREAD

**Issue by damncorwell** [mpdf/mpdf#1438]
### I found this bug

I get this error when I'm trying to create new mPDF instance. Both mbstring and mbregex are enabled.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

mPDF version is 8.0.11, PHP is 7.4.19. I'm using yii2 and MAMP for local service (in phpInfo it says that mbstring, mbregex and gd are enabled).

### This is the PHP code snippet I use

```
<?php


namespace app\modules\v1\controllers;


use Mpdf\Mpdf;

    public function actionConfirm() {
                $mpdf = new Mpdf();
}
```

### This is the HTML/CSS code snippet I use

```

```

**Comment by finwe** [comment]
This error means your environment is not set up correctly. Not an issue of mPDF.
