### ISSUE TITLE
Fixed font Garuda.ttf problem with "k" character

### ISSUE THREAD

**Issue by mean-cj** [mpdf/mpdf#1440]
Hi 

This Garuda font maybe print is problem.
![2021-05-20_143552](https://user-images.githubusercontent.com/1191385/118938396-cc50e600-b978-11eb-9f65-fc0e7744ea78.gif)

Could your please update Garuda font,
problem only with "k" character

![2021-05-20_143046](https://user-images.githubusercontent.com/1191385/118937890-37e68380-b978-11eb-8212-365fea874589.gif)

**Font fixed "Garuda.ttf" "k" cha , i'm not sure does it work.**
[Garuda.zip](https://github.com/mpdf/mpdf/files/6513952/Garuda.zip)

Thank.

**Comment by finwe** [comment]
Please provide a code sample to reproduce this behaviour. Are other styles of Garuda font also affected?

**Comment by finwe** [comment]
I am going to close this as it seems that the font in distribution is not even Garuda, just Arial without ext-ascii characters. Not worth the effort.

Thanks for the try anyway.

**Comment by finwe** [comment]
I understand the usecase now, reopening. Please provide a code sample to reproduce this behaviour. Are other styles of Garuda font also affected?

**Comment by mean-cj** [comment]
Hi finwe  

i see a problem only with font Garuda - [k] character.

- Download https://github.com/mpdf/mpdf/files/6513952/Garuda.zip
- Replace font on \mpdf\mpdf\\ttfonts
- Remove cache on \mpdf\mpdf\tmp\ttfontdata

now [k] format is not black on paper print.
