### ISSUE TITLE
File handles not closed, possible memory leak (+ solution)

### ISSUE THREAD

**Issue by bilogic** [mpdf/mpdf#1447]
### I found this bug

Where file handles of imported PDFs are not closed after performing `->output()`, nor does there seem to be a way to close them.
This blocks me from deleting my source PDFs with the following exception `unlink(xGf23CbyXDm3HKy8baZ8p2iITjgxWPGZIN6SoM6m.pdf): Text file busy`

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mpdf/mpdf v8.0.11  
PHP 7.4.13 (cli) (built: Nov 24 2020 10:03:34) ( NTS )

### This is the PHP code snippet I use

I also found the solution here https://github.com/Setasign/FPDI/blob/cddf43dcfe57337bbdc687cb929021174e6696da/src/FpdiTrait.php#L90-L107

If I manually call this `->cleanUp()`, I can delete my PDF without exceptions.
However, there is another `->cleanup()` method in `Mpdf.php`
https://github.com/mpdf/mpdf/blob/58322c5cf83a5f86e0c5e2109af1e1ce47685b5d/src/Mpdf.php#L1549-L1553

So I'm not sure where is the best place to add and call this new `->cleanUp()` method.

**Comment by bilogic** [comment]
@greew 

I would like to propose adding a `fpdiCleanUp()` below `src/Mpdf.php`'s `cleanup()`, would you accept this PR?
Thank you.

**Comment by bilogic** [comment]
Sorry should have been @finwe thanks

**Comment by finwe** [comment]
@bilogic I guess, I wasn't able to find a better solution. Please create a PR for docs (import & cleanup parts) too.

**Comment by bilogic** [comment]
@finwe 

Ok great! 

Let me make the `fpdiCleanUp()` available as a first step, I'm not confident of touch `cleanUp()` yet due to a lack of understanding mpdf's internals. Perhaps `cleanUp()` can call `fpdiCleanUp()` or something.

Thank you.

**Comment by finwe** [comment]
As you will have to duplicate fpdi cleanup functionality, why not just duplicate it in the mpdf cleanup() method directly?

**Comment by bilogic** [comment]
Yea ok, I think I will do that.

**Comment by bilogic** [comment]
@finwe done thanks!

**Comment by finwe** [comment]
Closed by #1476
