### ISSUE TITLE
div Tag causes line break after bullet point in PDF

### ISSUE THREAD

**Issue by arjay54** [mpdf/mpdf#1449]
### I found this bug

![grafik](https://user-images.githubusercontent.com/79190983/119952745-9d9cc600-bf9d-11eb-9ccb-eab2efb4bd4d.png)

I am using DokuWiki for documentation of our electronic devices. We have safety advices and other information that is shown in tables. Documents are exported through the Bookcreator Plugin which again uses mpdf.

When using DokuWiki syntax for lists in a table an unexpected line break appears after the bullet point. I used to use a workaround with an inline HTML list. But this is somehow not what I want.

Inspecting the generated HTML code showed that a div-Tag within the li-Tag causes the line break after the bullet point. This behaviour can also be induced by adding a div to the workaroud inline HTML.

The div Tag should not cause a line break. Does this behaviour come from mpdf? Can it be avoided by CSS? 

### This is the HTML/CSS code snippet I use

![grafik](https://user-images.githubusercontent.com/79190983/119952601-7b0aad00-bf9d-11eb-82be-4e03dad498aa.png)

**Comment by finwe** [comment]
http://idownvotedbecau.se/imageofcode
