### ISSUE TITLE
div Tag causes line break after bullet point in PDF

### ISSUE THREAD

**Issue by arjay54** [mpdf/mpdf#1450]
### I found this bug
![grafik](https://user-images.githubusercontent.com/79190983/119955641-86aba300-bfa0-11eb-94d4-ab707b6e0265.png)

I am using DokuWiki for documentation of our electronic devices. We have safety advices and other information that is shown in tables. Documents are exported through the Bookcreator Plugin which again uses mpdf.

When using DokuWiki syntax for lists in a table an unexpected line break appears after the bullet point. I used to use a workaround with an inline HTML list. But this is somehow not what I want.

Inspecting the generated HTML code showed that a div-Tag within the li-Tag causes the line break after the bullet point. This behaviour can also be induced by adding a div to the workaroud inline HTML.

The div Tag should not cause a line break. Does this behaviour come from mpdf? Can it be avoided by CSS?

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF 8.0.x

### This is the HTML/CSS code snippet I use
```html
<table class="infobox exttable">
<tr>
<td rowspan="2"><img src="/lib/exe/fetch.php?w=100&amp;tok=915f05&amp;media=media:common:iso_7010_w001.png" class="mediacenter" title=" Warning " alt=" Warning " width="100" /> </td>
<th class="danger">Signal Word</th>
</tr>
<tr>
<td> <strong>Type of danger and source</strong> <br/>
<br/>
Consequence of the danger <br/>
<br/>

</p>
<ul>
<li class="level1"><div class="li">Line break after bullet point</div>
</li>
</ul>

<p>

<ul>
<li>HTML workaround</li>
<li><div>DIV element inserted</li>
<li>Instruction to avoid the danger</li>
</ul>

</td>
</tr>
</table>
```

**Comment by perencinmarco** [comment]
any update on this?
in my case it happens in all the lists inserted in a table like this: 
td - ul - li - p
![wrong-ul-li](https://user-images.githubusercontent.com/51480007/182553042-7d90dc87-f7e3-49b4-bc7e-1b6cea6fd51a.png)

**Comment by finwe** [comment]
@perencinmarco If you don't see any update, there is no update. See below for further explanation.

@arjay54 Please note that inside tables, block elements are not behaving correctly and their support is limited. This is expected, albeit faulty, behaviour. It is not likely to change.

Outside of tables, divs in LI behave as expected (when you fix your flipped tags and missing closing div.

Closing this as "expected behaviour"
