### ISSUE TITLE
Allow multiple font directories in fontDir config variable

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#146]
For future splitting of the package, the library has to be able to look for fonts in multiple directories.

**Comment by finwe** [comment]
Closing (done in 80d80fd).

**Comment by marclaporte** [comment]
Fantastic.  Thanks!!!

**Comment by strider72** [comment]
Could you please tell us HOW to use it?

**Comment by Klap-in** [comment]
See https://mpdf.github.io/reference/mpdf-functions/addfontdirectory.html and https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html
