### ISSUE TITLE
[SOLUTION] Undefined index: current on vendor/mpdf/mpdf/src/Tag/BlockTag.php#315

### ISSUE THREAD

**Issue by gcdsm12** [mpdf/mpdf#1460]
hello i get this error on generate PDF.

To solution in my case, i get file BlockTag.php#315 and change line 315

from:
} elseif ($this->mpdf->page_box['current'] != $pagesel) {

to:
} elseif (isset($this->mpdf->page_box['current']) && $this->mpdf->page_box['current'] != $pagesel) {

**Comment by gcdsm12** [comment]
hello you not change code of MPDF of my solution in code development github?

**Comment by Klap-in** [comment]
As you have probably read, an small example of php and html code is requested. From this small example an unit test is made and added to the test suite, to confirm the fix and prevent side effects. Thanks for the effort.

**Comment by finwe** [comment]
https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
