### ISSUE TITLE
allow a string containing the image as image

### ISSUE THREAD

**Issue by lublak** [mpdf/mpdf#1466]
# Feature request

currently the `Image($file)` method only allows a file path.
If you generate your image dynamicly with Imagick or GD you can't add it to your pdf.
It would be nice to have some method for it without saving to image to a temp file.

**Comment by finwe** [comment]
See https://mpdf.github.io/what-else-can-i-do/images.html#dynamically-generated-images

**Comment by lublak** [comment]
@finwe thanks. I hadn't found it, apparently. :thumbsup:
