### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by rubelamir** [mpdf/mpdf#1467]
Problem 1
    - mpdf/mpdf[v8.0.0, ..., v8.0.3] require php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your php version (8.0.3) does not satisfy that requirement.
    - mpdf/mpdf[v8.0.4, ..., v8.0.7] require php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 -> your php version (8.0.3) does not satisfy that requirement.
    - mpdf/mpdf[v8.0.8, ..., v8.0.9] require php ^5.6 || ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
    - mpdf/mpdf[v8.0.10, ..., v8.0.11] require ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - Root composer.json requires mpdf/mpdf ^8.0 -> satisfiable by mpdf/mpdf[v8.0.0, ..., v8.0.11].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
### This is the PHP code snippet I use

```
<?php


```

### This is the HTML/CSS code snippet I use

```

```

**Comment by rubelamir** [comment]
Problem 1
    - mpdf/mpdf[v8.0.0, ..., v8.0.3] require php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your php version (8.0.3) does not satisfy that requirement.

**Comment by MarinKodKode** [comment]
Hi, I had the same problem. You can fixed it modifying the php.ini, just enable the gd extension

**Comment by Halimict** [comment]
Thanks

**Comment by ng-hoangnam** [comment]
@MarinKodKode tks you, i spent half of my best day to fix this shit
