### ISSUE TITLE
attribute a[target="_blank"]

### ISSUE THREAD

**Issue by NikMG** [mpdf/mpdf#1469]
I was trying to set target '_blank' inside tag a. But i was wondered, when discovered that this is impossible for mpdf. If in the future will be this feature or maybe there are done issues for this problem ?

**Comment by finwe** [comment]
you can set target '_blank' for an anchor. It having no effect is caused by the PDF format. I assume you intend to open links from the PDF in a new window/tab when viewing in a browser, but it cannot be fully achieved https://stackoverflow.com/a/39763562/819007
