### ISSUE TITLE
Dynamically generated images not showing in PDF

### ISSUE THREAD

**Issue by ohtwadi** [mpdf/mpdf#1474]
```<img src="myImage.php" />``` tag does not add the image to generated PDF. Docs say this should work - https://mpdf.github.io/what-else-can-i-do/images.html#dynamically-generated-images

### Versions
PHP v7.3.28. 
I saw this behavior while generating PDFs in SuiteCRM which uses mPDF v5.7.1. I have since confirmed this behavior still occurs in mPDFv8.0.11 as well.

### myImage.php - This successfully displays the image in browser
```
<?php
header("Content-type:image/jpg");
readfile("upload/image.jpg");
```

### PDF generation code
```
<?php
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('<img src="myImage.php" />');

$mpdf->Output();
?>
```

I am not sure if this is a bug or I need a different mechanism to load the image file.

**Comment by finwe** [comment]
This is not an issue of mPDF - if you provide correct path with correctly generated image, it will be used in the PDF.

Try using an absolute URL for the image, it is likely that mPDF does not run the request through the server and implies the image to be local, thus not processed by PHP.

**Comment by ohtwadi** [comment]
Thanks @finwe .
Looks like I needed to use the full path to myImage.php inside the <img> tag. 
```
<img src="http://localhost/myImage.php"/>
```
The docs mention a relative URL, would be great if that can be updated. Thanks!

**Comment by finwe** [comment]
Relative url also do work with correct environment, as in the [Images example](https://github.com/mpdf/mpdf-examples/blob/development/example04_images.php). Just tested.

There is no reason for changing the docs (plus, there is an absolute URI in the docs, beginning with `/`).

I understand this path handling behaviour is a bit confusing, there are [plans to streamline it](https://github.com/mpdf/mpdf/issues/868).
