### ISSUE TITLE
Chinese text rendering in MPDF is not same as in html

### ISSUE THREAD

**Issue by ngokila** [mpdf/mpdf#1475]
**_I found this bug_**
We are using mpdf to convert the html to pdf . We have encountered an alignment text issue for Chinese text in mpdf.
Attached is the url https://ibb.co/RCq4J2H for the image file for the comparison of text in HTML and pdf.
Please advise resolve this issue

**_This is mPDF and PHP version and environment (server/fpm/cli etc) I am using_**
I am using mpdf version 8.0, PHP version 7.4, and laravel version 8.0 and custom chinese font - FZSSK.TTF

**This is the PHP code snippet I use**

                   $mPdf = new Mpdf([
                    'fontDir' => array_merge($fontDirs, [
                        $publicFolder . "/fonts/ChineseFonts",
                        $publicFolder . "/fonts/EnglishFonts"
                    ]),
                    'fontdata' => $fontData + [
                        'classifiedinterstate' => [
                            'R' => 'classifiedinterstate.ttf',
                            'I' => 'classifiedinterstatei.ttf',
                            'B' => 'classifiedinterstateb.ttf',
                            'BI' => 'classifiedinterstatebi.ttf',
                        ],
                        'fzshusong-z01' => [
                            'R' => 'FZSSK.ttf'
                        ]
                    ],
                    'default_font' => 'classifiedinterstate',
                    'mode' => 'utf-8'
                ]);
                $mPdf->showImageErrors = true;
                $mPdf->backupSubsFont = ['dejavusanscondensed'];
               $mPdf->WriteHTML($Html);               
               $mPdf->Output( "test.pdf", Destination::FILE);

**This is the HTML/CSS code snippet I use**

        <html>
         <head>
          <style>
                @page { 
                    sheet-size: 3.7cm 3cm; 
                    margin: 0;   
                    } 
                    .ad-layout{
                        position: absolute;
                        overflow: hidden;
                    }
                 .editor_preview { letter-spacing: 1px; line-height: normal;}
                .editor_preview--CN { font-family: 'fzshusong-z01'; font-size: 10pt;}
                 .w-full { width: 100% !important; }  
                .mx-auto {margin-left: auto!important;margin-right: auto!important;}           
                    </style>
          </head>
         <body>
                <div class="ad-layout  mx-auto " style="width: 3.7cm; height: 3cm;">
                 <div class="editor_preview editor_preview--CN w-full" id="editorPrev">现任学校教师、研究生/本科生、全职教师。熟 
                    悉学校教学大纲。电话/短信：97269156 $
                    </div>
                  </div>
           </body>
          </html>

**Comment by finwe** [comment]
Please _describe_ what _exactly_ is the alignment issue.

**Comment by ngokila** [comment]
Hi,

Please refer to the image for the text alignment issue( https://imgbb.com/RCq4J2H ) and I have the copy the text below for your reference

**_chinese text in PDF_**
现任学校教师、研究
生/本科生、全职教师。
熟悉学校教学大纲。
电话/短信：97269156
$

**_chinese text in HTML_**
现任学校教师、研究
生/本科生、全职教
师。熟悉学校教学大
纲。电话/短信：
97269156 $

Example of an alignment issue
1st line - text match in  both pdf and HTML
2nd line - 生/本科生、全职教师。in pdf but HTML has 生/本科生、全职教(last two chars are in 3rd line)
and so on 

2,3,4 and 5th line text are not matching.

Please help me to resolve this text alignment issue. Thanks in advance.

**Comment by finwe** [comment]
And how do you tell the browser to make line breaks exactly at these points? When I create a sample HTML with your code, I have all characters on a single line. This is a non-issue, IMHO, just play with containing div width, font size, and if you need line breaks at specific places, use HTML <br> tag.

**Comment by ngokila** [comment]
Actually i am setting the height and width for the outer div - style="width: 3.7cm; height: 3cm;".so i am expecting the same text alignment behavior in pdf also 

<div class="ad-layout  mx-auto " style="width: 3.7cm; height: 3cm;">
             <div class="editor_preview editor_preview--CN w-full" id="editorPrev">现任学校教师、研究生/本科生、全职教师。熟 
                悉学校教学大纲。电话/短信：97269156 $
                </div>
              </div>

**Comment by finwe** [comment]
Don't expect the output in PDF be exactly the same, the "rendering engine" is different.

**Comment by ngokila** [comment]
ok noted thanks
