### ISSUE TITLE
is_file() warning

### ISSUE THREAD

**Issue by maradt** [mpdf/mpdf#1478]
In production server MPDF generate warning `is_file(): open_basedir restriction in effect.` on row https://github.com/mpdf/mpdf/blob/v8.0.10/src/Mpdf.php#L11458. 

- PHP version 7.4.21
- Mpdf version 8.0.10

It happens if IMG tag contains local URL like `src="/img/image.jpg"`.

In my case it can be resolved by add `@` before `is_file()` function this way:

```
<?php
...
} elseif ((strpos($path, ":/") === false || strpos($path, ":/") > 10) && !@is_file($path)) { // It is a local link
...
```

**Comment by forgie1** [comment]
@finwe any comment on this issue?

The notice is quite annoying. An proper picture path is set on the following row: https://github.com/mpdf/mpdf/blob/v8.0.10/src/Mpdf.php#L11473 so the notice is useless.

**Comment by finwe** [comment]
https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
