### ISSUE TITLE
4 Fonts = 50mb?

### ISSUE THREAD

**Issue by CheshireC4t** [mpdf/mpdf#1484]
# Feature Request

I suggest removing a lot of the fonts and recommending people download what font they want to use themselves. The reason I mention this, is because you have 4 font files that take up 50+MB. I understand you're just doing that to include every language on the planet, but this repo is larger than 40 of my other repos combined. :grimacing:

If you don't like that idea, maybe add the below line in the readme file:

>If you want to use your own fonts, you can free up 87MB by adding the below command in Composer:
`
        "post-update-cmd": [
            "php -r \"array_map('unlink', glob('vendor/mpdf/mpdf/ttfonts/*.*'));\"",
        ],
`

**Comment by Klap-in** [comment]
There is already some work done and discussions happening. Please see https://github.com/mpdf/mpdf/pull/841
