### ISSUE TITLE
export pdf as text

### ISSUE THREAD

**Issue by vaskovasilev** [mpdf/mpdf#1489]
# Feature request

Hello all,
I am using pdf import to read a pdf file:

`$pagecount = $mpdf->SetSourceFile('test.pdf');
$tplId = $mpdf->importPage($pagecount);
$mpdf->useTemplate($tplId);`

Is it possible to export this as a text , or xml or whatever, that can be stored in database for example?

thank you !

**Comment by finwe** [comment]
That's the exact oposite of mPDFs purpose. Use a tool dedicated to this, there are plenty around.

**Comment by vaskovasilev** [comment]
Yes, this is the question :) can it be done also with mpdf.. not to use 10 tools.

**Comment by finwe** [comment]
(it could, theoretically, using non-public APIs, but it is not and will not be an official feature).
