### ISSUE TITLE
Update documentation and README to new namespaced format, remove dropped features

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#149]
See https://github.com/mpdf/mpdf.github.io/issues/7

**Comment by finwe** [comment]
Also remove pages with deprecated/removed features.

**Comment by RCMainak** [comment]
@finwe The current readme file is outdated. To be specific the example in the [Usage](https://github.com/mpdf/mpdf#usage) section is wrong.

**Comment by finwe** [comment]
@RCMainak Please specify, outdated how?

**Comment by RCMainak** [comment]
I maybe wrong but seems like `$mpdf = new \Mpdf\Mpdf();` doesn't work. All though if I try `$mpdf = new mPDF();` according to [the guide](https://mpdf.github.io/getting-started/creating-your-first-file.html) then works fine. Maybe we need to update the readme?

**Comment by finwe** [comment]
No. See #269 and #254.

**Comment by Klap-in** [comment]
Maybe an idea to prevent this kind of quick reading troubles/questions, is mentioning the version before the example?
e.g.
`The simplest usage of the library would be as follows:`
to 
`The simplest usage of the library (mPDF >= 7.0 ) would be as follows:`

**Comment by finwe** [comment]
@Klap-in That's a good idea. Will do.

**Comment by RCMainak** [comment]
@Klap-in that's a nice idea.

@finwe Sorry, for wasting your time :)
