### ISSUE TITLE
Child elements not using parent style

### ISSUE THREAD

**Issue by heintze-entwicklung** [mpdf/mpdf#1490]
I think i found a bug in mpdf version 8.0.12.

Envoinment: php 7.4, nginx, linux

The child elemnts not using the parent style eg font-family, font-size or color.
The child element is using the default font family, size and color.

Html:
```
<div parentElement style="font-size: 12px; color: black">
     <div childElement>Test</div>
</div>
```

Is this an issue?

**Comment by finwe** [comment]
Probably not. `<div childElement>` is a weird markup.

**Comment by finwe** [comment]
(and it works with your markup anyway)

**Comment by heintze-entwicklung** [comment]
child or parentelement was only an example. Its not a markup. 

```
<div style="font-size: 12px; color: black">
     <div>Test</div>
</div>
```

**Comment by finwe** [comment]
> (and it works with your markup anyway)
