### ISSUE TITLE
CSS inline styles get lost in PDF output

### ISSUE THREAD

**Issue by christophbee** [mpdf/mpdf#1512]
### I found this bug
Inline CSS properties are ignored when rendering HTML as PDF
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
the latest mPDF version (8.0.0) inside a TYPO3 extension. I included the necessary files inside the TYPO3 Classes structure. PHP v 7.4.23 
### This is the PHP code snippet I use

```
<?php
$mpdf = new Vendor\Plugin\Helper\Mpdf\Mpdf(array('mode' => 'c','format'=>'A4','default_font_size' => '8','default_font'=>'Tahoma'));

$html = '<html><body><style>td{color:red;}</style>
<table style="width:100%;">
            <tr>
                <td colspan="2" style="padding-left: 30px;"><h1>Lorem ipsum/h1></td>
            </tr>            
        </table> <br>       
        ';
[...]
$html .= '</table></body></html>';
$mpdf->WriteHTML($html,2);
$mpdf->Output('veranstaltungen.pdf', 'I');
```
When I make a `var_dump($html).die();` before `$mpdf->Output('veranstaltungen.pdf', 'I');` then it shows the HTML content with correct CSS styling:
![Bildschirmfoto 2021-09-23 um 13 38 34](https://user-images.githubusercontent.com/22295289/134500562-27485043-9c82-48de-9610-6bc4cf5cc618.png)

But when I create the PDF all CSS styles get lost, also the content from my <style> Tag is visible as plain text in PDF content as td{ color:red; }
![Bildschirmfoto 2021-09-23 um 13 40 13](https://user-images.githubusercontent.com/22295289/134500694-81b798cc-5ec6-478f-b793-b2fa4e21b46e.png)

**Comment by ssieb** [comment]
`<style>` tags go in `<head>`, not `<body>`

**Comment by christophbee** [comment]
You're right but that won't solve my problem that inline CSS styles in body get ignored.

**Comment by finwe** [comment]
See https://mpdf.github.io/reference/mpdf-functions/writehtml.html, parameter $mode

**Comment by christophbee** [comment]
I tried all possibilites for $mode: 0 and 2 but both does not work

**Comment by finwe** [comment]
Then create a QA discussion. There must be an overlooked setting or something. I created a PDF where the padding is applied quite simply just by omitting the mode parameter.

[example000.pdf](https://github.com/mpdf/mpdf/files/7283742/example000.pdf)
