### ISSUE TITLE
cannot generate PDF/A-3, I get validation error when I try to validate the output

### ISSUE THREAD

**Issue by MohamedMagdy109** [mpdf/mpdf#1532]
<?php

require_once __DIR__ . '../../vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf([
	'PDFA' => true,
	'PDFAauto' => true,
]);

$mpdf->SetAssociatedFiles([[
	'name' => 'ZUGFeRD-invoice.xml',
	'mime' => 'text/xml',
	'description' => 'some description',
	'AFRelationship' => 'Alternative',
	'path' => __DIR__ . '/TaxInvoice.xml'
]]);

$rdf  = '<rdf:Description rdf:about="" xmlns:zf="urn:ferd:pdfa:CrossIndustryDocument:invoice:1p0#">'."\n";
$rdf .= '  <zf:DocumentType>INVOICE</zf:DocumentType>'."\n";
$rdf .= '  <zf:DocumentFileName>ZUGFeRD-invoice.xml</zf:DocumentFileName>'."\n";
$rdf .= '  <zf:Version>1.0</zf:Version>'."\n";
$rdf .= '  <zf:ConformanceLevel>BASIC</zf:ConformanceLevel>'."\n";
$rdf .= '</rdf:Description>'."\n";

$mpdf->SetAdditionalXmpRdf($rdf);

$html = '
<h1>This is a Heading</h1>
';

$mpdf->WriteHTML($html);
$mpdf->Output("mypdf.pdf","D");

**Comment by MohamedMagdy109** [comment]
can I get help  to generate PDF/A-3 with mpdf


‫في الاثنين، 18 أكتوبر 2021 في 1:21 م تمت كتابة ما يلي بواسطة ‪Matěj
Humpál‬‏ ***@***.***‬‏>:‬

**Comment by finwe** [comment]
https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
