### ISSUE TITLE
PDFs are completely unstyled in PHP Scoped Version of mPDF 

### ISSUE THREAD

**Issue by tkfv** [mpdf/mpdf#1535]
### I found this bug

When using mPDF after scoping its namespace with [PHP Scoper](https://github.com/humbug/php-scoper) the resulting PDFs are completely unstyled.

Compare the following results. Below mPDF is not scoped:

![image](https://user-images.githubusercontent.com/92856336/138075510-cc5e42cd-b011-4e26-9f2e-b398f910dcad.png)

Below mPDF is scoped. Notice how the paragraphs seems to be rendered inline now. (you can find the HTML code at the bottom)

![image](https://user-images.githubusercontent.com/92856336/138075529-b75867ff-f2ba-45f7-854a-da1cb2c11847.png)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

mPDF 8.0.13
PHP 8.0.11 cli run with the -S localhost:8080 option.

### This is the PHP code snippet I use

```
<?php
		$mpdf = new \Mpdf\Mpdf([
			'tempDir' => sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'mpdf',
			'fontDir' => $font_dirs,
			'fontdata' => $font_data,
			'default_font' => 'ctimes',
			'format' => $post_data[ self::FIELD_FORMAT ] . '-' . $post_data[ self::FIELD_ORIENTATION ],
		]);
		$mpdf->WriteHTML( $code );
		return $mpdf->Output( null, $return_string ? 'S' : null );

```

The scoping is simply done this way: `php-scoper.phar add-prefix -d source -o dest`

### This is the HTML/CSS code snippet I use

```
<head>
<style>
	.red {
		background-color: red;
	}
</style>
</head>
<body>
<p>
	hello
</p>
<p class="red">
	this is a test
</p>
</body>
```

**Comment by finwe** [comment]
This is not an issue of Mpdf when its code is being altered.

**Comment by tkfv** [comment]
I understand, I added this because other PHP projects care about PHP Scoper compatibility and accept this kind of issues.

**Comment by tkfv** [comment]
Please let me know if you have any suggestion for what to look for or what test to do in the code. I can do try to work this out myself.

**Comment by finwe** [comment]
I have no experience with scopers, so I am unfortunately unable to point you in the right direction. I don't exactly understand how changing the namespace of the code would change behaviour of css rendering. One thing that comes to mind might be relative paths in the code.

**Comment by jakejackson1** [comment]
@tkfv I use `php-scoper` with mPDF without any issues. The key is to write a patcher to fix a couple of namespace references in strings.  

Here's the config file: https://github.com/GravityPDF/gravity-pdf/blob/development/.php-scoper/mpdf.php

Good luck!
