### ISSUE TITLE
Isolated Arabic letters in cell and write functions.

### ISSUE THREAD

**Issue by PHPism** [mpdf/mpdf#1538]
MPDF v8.0.13
php7.4
I'm building a certificates system that use a predefined PDF file then print student name in selected area.
It's working fine in English students name, but printing Arabic names isn't working as expected.
How it appear: ناموش ىفطصم
While it should appear like: مصطفى شومان

My Code:
```
require_once ("/libraries/mpdf/vendor/autoload.php");
			
$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
$fontDirs = $defaultConfig['fontDir'];

$defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
$fontData = $defaultFontConfig['fontdata'];

$mpdf_config = array(
	'mode' => 'utf-8',
	'tempDir' => "/temp",
	'fontDir' => array_merge($fontDirs, ["/fonts",]),
	'fontdata' => $fontData + [
		'droidnaskh' => ['R' => 'droidnaskh/DroidArabicNaskh-Bold.ttf','useOTL' => 0xFF,'useKashida' => 75,],
		'neue_haas_bloomberg' => ['R' => 'Neue_Haas_Bloomberg_Regular.7d7dfd9.ttf','useOTL' => 0xFF,'useKashida' => 75,]
	],
	'default_font' => 'arial'
);
$mpdf = new \Mpdf\Mpdf($mpdf_config);
$mpdf->autoLangToFont = true;

$mpdf->AddPage();
$mpdf->setSourceFile('/source.pdf');
$tplIdx = $mpdf->importPage(1);
$page_data = $mpdf->getImportedPageSize($tplIdx);
$mpdf->useTemplate($tplIdx, 0, 0, $page_data['width'], $page_data['height'], true);
$mpdf->SetAutoPageBreak(false);

$mpdf->SetXY(10, 10);
$fullname= "مصطفى شومان";
$mpdf->Cell(100, 0, $name, 0, 0, "C");
$mpdf->SetXY(10, 20);
$OTLdata = true;
$mpdf->Cell(100, 0, $name, 0, 0, "C", 0, "", 0, 0, 0, 'M', 0, false, $OTLdata);
$mpdf->SetXY(10, 30);
$mpdf->Write(0, $fullname);

$mpdf->Output('newfile.pdf', 'F');
```
I tried 
- Using Arabic fonts.
- disabling custom fonts .
- Both Write and Cell functions.
- Disabling source file and use write and cell on blank page.
- $mpdf->SetDirectionality('rtl'); after $mpdf->autoLangToFont = true;

I hope you can help.
Best Regards

**Comment by jakejackson1** [comment]
`Cell` is an FPDF method that isn't UTF-8 aware. Use `WriteCell` instead, or `WriteHTML` https://mpdf.github.io/write-directly-to-document/direct-writing-to-document.html

**Comment by PHPism** [comment]
> 
> 
> `Cell` is an FPDF method that isn't UTF-8 aware. Use `WriteCell` instead, or `WriteHTML` https://mpdf.github.io/write-directly-to-document/direct-writing-to-document.html

This fixed my issue.
Thank you for the note <3
