### ISSUE TITLE
svg image inside <svg> not show

### ISSUE THREAD

**Issue by mean-cj** [mpdf/mpdf#1543]
### I found this bug
svg image inside svg tag is not show

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mpdf 7.1.9 - 8.0
php 7.4 - 8.0 

### This is the PHP code snippet I use
```
<?php
$mpdf = new \Mpdf\Mpdf([
   'mode' => 'utf-8', //'allow_output_buffering' => true,
   'format' => 'A4',
   //'default_font_size' => 18,
   'default_font' => 'garuda',
   'margin_left' => 8,
   'margin_right' => 8,
   'margin_top' => 8,
   'margin_bottom' => 8,
   'margin_header' => 0,
   'margin_footer' => 0,
   'orientation' => 'P'
]);
$mpdf->SetDisplayMode('fullpage');
$mpdf->useAdobeCJK = true;
$mpdf->WriteHTML($pdf_content_buffer);
$mpdf->Output();
```

### This is the HTML/CSS code snippet I use
svg image not work  both attribute xlink:href and href
```
$pdf_content_buffer = 
<html><body>
<svg viewBox="0 0 100 100">
    <image x="10" y="20" width="80" height="80" xlink:href="https://upload.wikimedia.org/wikipedia/commons/5/5b/Marilyn_Monroe_Signature.svg" />
    <text x="16" y="72"  font-size="6">Q641122563-2021-11-03</text>
</svg>
</body></html>
```

### pdf output blank of svg image
![2021-11-03_141601](https://user-images.githubusercontent.com/1191385/140021476-3da7d4a2-818f-4677-a143-f035b0c7de60.png)

### html show svg image with text is normally
![2021-11-03_141007](https://user-images.githubusercontent.com/1191385/140021017-1983146e-6006-408e-9f79-031ad4ee94e4.png)

Thank you very much , for this project a long time

**Comment by finwe** [comment]
Support of SVG in mPDF is only partial. Find a workaround.

https://mpdf.github.io/what-else-can-i-do/images.html#svg-images
