### ISSUE TITLE
Border between column

### ISSUE THREAD

**Issue by tomymohan-powercms** [mpdf/mpdf#1545]
For one of my project, i want to generate pdf with 2 columns with a border line between the columns. i created the border but facing some issue if there is more that one page.

If there is only one page, border is creating properly. But if there is multiple pages, then border is not coming for first page and for other pages border is coming properly.

I need to add the border between the columns in the first page also. 

Is there any solution for this? 

My current condition on PDF generation:
If there is only one page: border between column is creating.
If there is multiple pages, border between column is **not coming for the first page.**

**Comment by tomymohan-powercms** [comment]
I didn't any solution yet. @finwe Why did you closed the issue? 
Is there any duplicate issue exist?

**Comment by finwe** [comment]
https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
