### ISSUE TITLE
Table not positioned right in PDF but does in HTML

### ISSUE THREAD

**Issue by fearless359** [mpdf/mpdf#1546]
This issue was reproduced on both a windows system using xampp, and a Linux based shared hosting system.

Windows info: Win 10 updates current, xampp/PHP v7.4.11, MPDF v8.0.14.

Linux info: Apache v2.4.51, PHP v7.4.24, MPDF v8.0.13

```
<?php
$mpdf = new Mpdf();
$myhtml =
'<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        .right { float: right; }
    </style>
    <title>Table position test</title>
</head>
<body>
<br/>
<div>
    <table class="right">
        <tr>
            <th>This should position on the right</th>
        </tr>
    </table>
    <table>
        <tr>
            <th>This should position on the left</th>
        </tr>
    </table>
</div>
</body>
</html>';
$mpdf->WriteHTML($myhtml);
$pdfString = $mpdf->Output($pdfname, $destination);
return $pdfString;
?>
[HTML_ExpectedResult.pdf](https://github.com/mpdf/mpdf/files/7476239/HTML_ExpectedResult.pdf)

```
Note that the HTML file I used to show expected result is taken directly from the code in the PDF example above.
[HTML_ExpectedResult.pdf](https://github.com/mpdf/mpdf/files/7476246/HTML_ExpectedResult.pdf)
[MPDF_ErrorResult.pdf](https://github.com/mpdf/mpdf/files/7476247/MPDF_ErrorResult.pdf)

**Comment by finwe** [comment]
mPDF does not support floating on tables. https://mpdf.github.io/css-stylesheets/supported-css.html
