### ISSUE TITLE
Unnecessary page breaks with image tags

### ISSUE THREAD

**Issue by oleprinds** [mpdf/mpdf#1548]
### I found this bug
With <img> in the html, there are unnecessary page breaks, when there is less than double the image height remaining on the page. The wrapper is then extended to hold the image on the top of the next page, but the image is displayed at the position, it was supposed to be displayed on the first page - but on the second page, outside the wrapper. Regular page breaks from images that are large than the available space works as normal.

This is what it looks like in the pdf. (The image used in the example is by [Taryn](https://www.flickr.com/people/8635903@N03). More info here https://commons.wikimedia.org/wiki/File:Typography_wallpaper.jpg)
![Screenshot from 2021-11-07 01-34-34_cropped](https://user-images.githubusercontent.com/5653474/140646794-f8f0de9d-b3de-4619-ba42-a95ee000ef4d.png)

This is what it is supposed to be.
![Screenshot from 2021-11-07 10-03-58_cropped](https://user-images.githubusercontent.com/5653474/140646784-4bc4414d-33fa-4208-b208-14cfe9087280.png)

The bug is probably related or the same as #1544
This works in 8.0.13.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF 8.0.14
PHP version 7.4 
Ubuntu/apache2

### This is the PHP code snippet I use

I created a minimal example. I've tried many different combinations of html tags, but the result is the same.
```
<?php
require_once "vendor/autoload.php";

$mpdf = new \Mpdf\Mpdf([
  'format' => 'A4',
  'tempDir' => "/tmp/"]
);
$mpdf->WriteHTML("html,body{margin:0;} div{background:rgba(255,0,0,0.1);padding:10px;margin:10px;border:1px solid black;}",1);
$html = <<<EOF

<div><p>First image, is displayed as intended.</p>
  <img src="https://upload.wikimedia.org/wikipedia/commons/8/8a/Typography_wallpaper.jpg" alt=""/>
</div>
<div><p>Second image.. Image is displayed at correct position, but on next page. The div wrapper expands to next page, as if there is a page break before the image.</p>
  <img src="https://upload.wikimedia.org/wikipedia/commons/8/8a/Typography_wallpaper.jpg" alt=""/>
</div>

EOF;

$mpdf->WriteHTML($html);
$mpdf->Output('test' . '.pdf', 'I'); 

```

### This is the HTML/CSS code snippet I use

```
html is included in php code
```

**Comment by martingebhardt** [comment]
Downgrading to version 8.0.13 helped for me.

**Comment by finwe** [comment]
Released 8.0.15 fixing this.

**Comment by PaulodoPorto** [comment]
Thank you so much @finwe !

**Comment by finwe** [comment]
$ composer info mpdf/mpdf

or

    echo \Mpdf\Mpdf::VERSION;

**Comment by Linus-Grote-liqid** [comment]
Thank you so much!
