### ISSUE TITLE
Warning: A non-numeric value encountered in mpdf/src/Mpdf.php on line 4285 and 11015

### ISSUE THREAD

**Issue by Laci357** [mpdf/mpdf#1554]
Hi guys! 

I experience following error message below if debugging is turned on and php errors are allowed. However, the pdf document is successfully generated.

The error message says:
> Warning: A non-numeric value encountered in /var/www/testEnvironment/tools/vendor/mpdf/mpdf/src/Mpdf.php on line 4285
> 
> Warning: A non-numeric value encountered in **/var/www/testEnvironment/tools/vendor/mpdf/mpdf/src/Mpdf.php on line 11015
> Error detected. PDF file generation aborted: A non-numeric value encountered

The attached .zip file includes my folder structure, the html input file and .php file utilizing the mpdf library.I did not pack the entire "vendor" directory, since that would result in a 44MB zip file. 

**My environment**:
Debian 11
PHP version: 8.0.12

[testEnvironment.zip](https://github.com/mpdf/mpdf/files/7522856/testEnvironment.zip)

If you need any further information, let me know. 
Thank you for your help in advance.

**Comment by finwe** [comment]
Thanks. Please, provide a minimal code example free of any nonrelated calls and with as small HTML example causing this as possible.

**Comment by finwe** [comment]
Per documentation: 

> default_font_size
> 
>     Sets the default document font size in points (pt)

specify `default_font_size` in constructor as an integer and the error will go away. Further config variables checking is a complex topic out of scope of this issue, so I will close this as resolved.

**Comment by Laci357** [comment]
Thank you, @finwe, your advice worked!
