### ISSUE TITLE
Mpdf throws an error when some tags are present in the HTML but font-family is not set in the CSS.

### ISSUE THREAD

**Issue by tkfv** [mpdf/mpdf#1562]
### I found this bug

Even if a default font is set, some tag (for example `<code>`) explicitly require setting a font in the css, otherwise Mpdf will throw the following error.

```
PHP Fatal error:  Uncaught Mpdf\MpdfException: Unsupported font type:  () in /home/dn/mpdftest/vendor/mpdf/mpdf/src/Writer/FontWriter.php:438
```

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

mPDF 8.0.13
PHP 8.0.11 cli run with the -S localhost:8080 option.

### This is the PHP code snippet I use

```
<?php
		$mpdf = new \Mpdf\Mpdf([
			'tempDir' => sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'mpdf',
			'fontDir' => $font_dirs,
			'fontdata' => $font_data,
			'default_font' => 'ctimes',
			'format' => $post_data[ self::FIELD_FORMAT ] . '-' . $post_data[ self::FIELD_ORIENTATION ],
		]);
		$mpdf->WriteHTML( $code );
		return $mpdf->Output( null, $return_string ? 'S' : null );

```

### This is the HTML/CSS code snippet I use

This doesn't work:

```
<code>test</code>
```

while the following works:

```
<p>test</p>
```

This works:

```
<style>
code {
font-family: ccourier;
}
</style>
<code>test</code>
```

**Comment by finwe** [comment]
Not enough example code to reproduce this. Add details about your setup and this can potentially be addressed as a QA in Discussions.

**Comment by tkfv** [comment]
hi @finwe . I tried with a simple setup. The trick is settings the fonts config to a null array, (to rely only on core fonts, I cannot ship the font dir):
This is the minimal setup you can use it to reproduce:

```
require_once __DIR__ . '/vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf([
'tempDir' => sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'mpdf',
'fontDir' => [],
'fontdata' => [],
'default_font' => 'ctimes',
]);
$mpdf->WriteHTML( '<code>hello</code>' );
return $mpdf->Output( '/tmp/out.pdf' );
```

**Comment by finwe** [comment]
Of course that when you remove all information about available fonts with a "trick", mPDF will have problems locating and using fonts. Furthermore, the error for your second code example is different from the error described in the first place. 

use `"mode" => "c"` in config to rely only on core fonts.

**Comment by finwe** [comment]
Yes, it does. But removing default fonts, you need to reset all their default usage in mPDF, in both code and default CSS. Again, this is not a bug, but a general QA, continue according to contribution guidelines.
