### ISSUE TITLE
Images from Amazon S3

### ISSUE THREAD

**Issue by dvelopin** [mpdf/mpdf#1577]
I downloaded the latest files from the repo a few minutes ago and still have the issue. This is executed from the web.

Essentially I have a PDF I am making which loads several images from an Amazon S3 bucket. So a simple `<img src=""/>` tag in the html.

I keep getting the following PHP error:

`fopen(https://s3.us-east-2.amazonaws.com/link-to-image.jpeg): failed to open stream: no suitable wrapper could be found`

The file is vendor/mpdf/mpdf/src/Image/ImageProcessor.php and line number 227.

Is there a better way to load an image from Amazon S3?

**Comment by dvelopin** [comment]
May I ask why you closed this without any information?

**Comment by finwe** [comment]
Sure, https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md

**Comment by dvelopin** [comment]
Thank you. I'm sorry, I figured I gave enough information for the issue. I'll get more information on this later.

**Comment by finwe** [comment]
Primarily, this is not an issue, it is general troubleshooting.
