### ISSUE TITLE
Project is dead or still in development ?

### ISSUE THREAD

**Issue by dvdknaap** [mpdf/mpdf#1584]
The last version release is from Mar 15, 2019 and 32 open pull requests.

So will there be a update in de near feature or can i better look for another project ?

**Comment by Klap-in** [comment]
Without any insight in your requirements, it is difficult to react with an useful answer. 

Current development is visible at https://github.com/mpdf/mpdf/commits/development

Latest version is 8.0.15, released at 2011-11-10…..
https://packagist.org/packages/mpdf/mpdf

**Comment by finwe** [comment]
Se notice in the readme.

**Comment by marclaporte** [comment]
Here is a relevant notice in README:
https://github.com/mpdf/mpdf/commit/8107f1103639c14726e865298eb9a00eac23ab2a

PHP 8.5 support was added so still maintained:
https://github.com/mpdf/mpdf/commit/356709089b9d2551f243c2f8f0ea44ebc7c38066

2.3 million downloads in the last 30 days so obviously useful to a lot of developers :-)
https://packagist.org/packages/mpdf/mpdf/stats

I shared the good news here: https://github.com/mpdf/mpdf/discussions/2211
