### ISSUE TITLE
CSS "float" style seems not working

### ISSUE THREAD

**Issue by vsirghii** [mpdf/mpdf#1586]
### I found this bug
mPDF doesn't handle the "float: right|left" CSS property as expected.
According to mPdf docs it supports "floating" (https://mpdf.github.io/css-stylesheets/supported-css.html)
Looking at old posts in https://stackoverflow.com/, it looks like it was working before according to some screenshots.
On my pdf result it seems partially ignoring the float property: it pushes the element to left|right fine, but then it doesn't flow the text around the floating element (please see the sample html bellow).
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPdf v. 8.0, php v. 7.4.22
### This is the PHP code snippet I use

```
<?php
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML($htmlString);
$mpdf->Output();
```

### This is the HTML/CSS code snippet I use
$htmlString is the following string of a very simple html to test:
```
'
<!DOCTYPE html><html><head></head>
<body>
  <div id="floated-address" style="background-color: yellow; float: right;  width: 4.13in; height: 0.93in;">
  </div>
  <div id="preview-message" style="width: 6.20in; height: 5.65in; overflow: clip; padding: 30px 10px 0 40px; word-wrap: break-word;">Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text Test text  
  </div>
</body></html>'
'
```
This html renders fine in the browser, but in the pdf doc, rendered as the result, the text doesn't flow around the floating div (yellow background), text goes underneath the floating element instead of surrounding it. 
I tried different css, but the above html is the simplest possible to test which mPdf doesn't handle right.

In the browser:
<img width="512" alt="CaptureBrowser" src="https://user-images.githubusercontent.com/26068474/147401255-de26ed46-7e0c-424e-a68c-a5e554af0140.PNG">

In the PDF
<img width="348" alt="CapturePdf" src="https://user-images.githubusercontent.com/26068474/147401256-535e8414-18a0-443a-a5c2-cb45cee24915.PNG">

**Comment by finwe** [comment]
I don't think text overflowing like this ever worked in mPDF, even version 6.1 creates the same result. I was only able to create a "faux" text flowing around using separate paragraphs (see example below), the whole block element will stay on the side of the floated element if its height is lower than the height of the floated element and its width allows.

Please note that float possibilities in mPDF are documented as limited.

```
<div>
    Some text to start with

    <div style="float: right; width: 60%;">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec arcu quis lacus tincidunt aliquam quis at mi. Suspendisse ut ante lectus. Vestibulum quis nulla nisi. Suspendisse a bibendum tellus. In varius egestas dolor sit amet imperdiet. Morbi maximus augue ac elementum hendrerit. In iaculis eleifend mauris. Suspendisse vitae placerat orci, non fringilla nulla.</p>
        <p>Donec a ultricies purus. Nulla non varius ipsum. Vivamus sagittis massa vel nisl suscipit, a tincidunt justo egestas. Vivamus arcu nisi, accumsan sed finibus a, laoreet in enim. Aliquam aliquet, velit in feugiat pulvinar, augue nunc gravida mauris, tincidunt vulputate diam erat quis elit. Morbi ut sem vestibulum augue hendrerit congue. Vestibulum a eleifend lorem, non tincidunt risus. Nullam bibendum nisi vitae eros gravida blandit. Duis in libero euismod, hendrerit nunc ut, ornare ligula. In vestibulum efficitur tortor sit amet rhoncus. Fusce quis massa leo. Cras sit amet mi lorem. Curabitur eget purus at sapien faucibus euismod ac ut neque.</p>
    </div>

    <p>Fusce eu neque sed urna porta fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam maximus placerat porta. Vestibulum placerat cursus metus, ut molestie ex consectetur sed. Vestibulum eget tincidunt metus. In hac habitasse platea dictumst. Donec augue ex, lacinia in est nec, luctus hendrerit diam. Vestibulum sagittis commodo magna, eget ullamcorper lorem iaculis vitae. Phasellus volutpat quam rhoncus mi elementum, ut tempus nunc laoreet.</p>
    <p>Phasellus eleifend metus a odio varius, id consequat velit tristique. Sed gravida suscipit neque ut feugiat. Donec lacinia tellus ac erat tincidunt finibus. Cras viverra semper erat at suscipit. Pellentesque condimentum orci a malesuada volutpat. Fusce in nunc mauris. Sed facilisis, ligula quis tristique suscipit, ligula tortor convallis sem, nec facilisis eros elit non tellus. Vivamus orci neque, gravida quis tincidunt a, vehicula id velit.</p>
    <p>Integer porta augue ac sagittis pharetra. Mauris nec massa eget nulla mollis semper ut ut lorem. Aliquam accumsan egestas turpis in convallis. Curabitur ullamcorper dapibus dolor, at rutrum leo. Mauris consequat velit ut libero finibus finibus. Ut consequat felis ac velit auctor molestie. Duis sit amet enim non erat aliquet facilisis. Phasellus tincidunt rutrum diam feugiat congue. Quisque id odio eget felis varius hendrerit quis ac nisi. Donec ut porttitor felis. Pellentesque nulla sem, faucibus ac tincidunt non, aliquam at quam. Morbi mauris purus, euismod sit amet tellus venenatis, commodo vulputate lectus. Fusce varius dignissim tortor. Praesent lobortis dolor et turpis rhoncus, a iaculis ipsum tincidunt. </p>

    <div style="clear: both; margin: 0pt; padding: 0pt; "></div>

    This is text that follows the clear:both.
</div>
```

**Comment by p-drolima** [comment]
just in case someone is still at this issue like me. I tried everything but float was always leaving me with padding-left forced by mPDF so the only way I could get this working was by using tables

`<table class="mpdf_index_entry" style="width:100%;border-bottom:1px solid #8F837E;padding-bottom:2mm">
                        <tr>
                            <td style="color:#8F837E;width:97%;font-family:'kievitpro-regular';font-weight:normal">{{$p['productName']['short2']}}</td>
                            <td style=""><a class="mpdf_index_link" href="#page{{$k + 5}}"><img src="{{ asset('images/expand.png') }}" /></a></td>
                        </tr>
                    </table>`

**Comment by rohankumar1524** [comment]
Is there any update on this issue, using the div and floating properties? I have exactly the same issue while using the MPDF?
Also I have tried @finwe solution but in my case the text is dynamic so it breaks the required design.
Tried the piece of code which works on https://jsfiddle.net/rohankumar1524/5krnah2d/ but not with MPDF. 
However the left box background takes full width but not the text.

![Image](https://github.com/user-attachments/assets/7c8eb2c3-4d43-4c1a-9854-88811158da23)

**Comment by finwe** [comment]
@rohankumar1524 This issue is closed with summary given [on Apr 6, 2002](https://github.com/mpdf/mpdf/issues/1586#issuecomment-1089984645).

To reiterate: 

> Please note that float possibilities in mPDF are documented as limited.

**Comment by rohankumar1524** [comment]
One more solution with the image background and the positioning for inside text

   <div style="position:absolute;left:470px;top:80px;width:190px;">Lorem ipsum dolor sit amet, consetetur sadipscing
        elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore aliquyam erat</div>
    <div style="width:80%;margin:0 auto">
        <?php
        $img = imagecreate(width: 235, height: 150);
        imagecolorallocate($img, 255, 255, 0);
        ob_start();
        imagepng($img, null, 0);
        ?>
        <?php echo sprintf('<img src="data:image/png;base64,%s"/ style="float:right" width="235">', base64_encode(ob_get_clean())) ?>

        <div>
            Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
            invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
            dolores et ea
            rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor
            sit
            amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna
            aliquyam erat, sed diam Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
            tempor
            invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        </div>
    </div>

![Image](https://github.com/user-attachments/assets/53b2dddc-c253-4711-8c23-0512efb951da)
