### ISSUE TITLE
Interlace handling should be turned on

### ISSUE THREAD

**Issue by VARGA-Peter** [mpdf/mpdf#1589]
Suddenly, I receive the below error message. What happened, how can I fix it?

`Warning (2): imagecreatefromstring(): gd-png: libpng warning: Interlace handling should be turned on when using png_read_image [ROOT/vendor/mpdf/mpdf/src/Image/ImageProcessor.php, line 552]`

Running under PHP 8.0.14

**Comment by Klap-in** [comment]
Could it be that you used these interlaced pictures not before? so that the code does not change, but the stuff processed by the code?

Here a result from some googling:
https://mixable.blog/png-deactivate-interlace-to-avoid-libpng-warning-interlace-handling-should-be-turned-on-when-using-png_read_image/

(Please note, it is better to post troubleshooting questions in the Discussions section or at StackOverflow.)

**Comment by VARGA-Peter** [comment]
> Could it be that you used these interlaced pictures not before? so that the code does not change, but the stuff processed by the code?
> 
> Here a result from some googling: https://mixable.blog/png-deactivate-interlace-to-avoid-libpng-warning-interlace-handling-should-be-turned-on-when-using-png_read_image/
> 
> (Please note, it is better to post troubleshooting questions in the Discussions section or at StackOverflow.)

Nope, nothing changed. Suddenly I receive the warning. I ran the code last time in September. Very strange.

**Comment by VARGA-Peter** [comment]
I could localise the PNG image which causes this warning. It hasn't been changed since I am using mpdf and the last time in September there wasn't this warning. Can I post somewhere _privately_ the link to the image so you can check it?

**Comment by VARGA-Peter** [comment]
Due to the fact the image didn't change since I use mpdf I suspect some change in the PHP settings which causes the warning to be shown. However, I fixed it using [ImageMagick](https://imagemagick.org/index.php) running this command found on [SO](https://stackoverflow.com/a/19742588/3179492):

`magick convert -interlace none interlaced.png uninterlaced.png`

**Comment by dragosprotung** [comment]
This error is because of this change in PHP itself https://github.com/php/php-src/pull/7615

**Comment by marnickmenting** [comment]
Resolved in [aabfaee](https://github.com/mpdf/mpdf/commit/aabfaeead028225c7bb4e4fb37d05c9b8a6f004c)
