### ISSUE TITLE
Composer version 2.2.3 and php 8.0.10 can not install mpdf 8.0.15

### ISSUE THREAD

**Issue by MisaghMi** [mpdf/mpdf#1593]
I've tried to install latest version of mpdf (8.0.15) on my project but it stuck at downloading mpdf file.
Please help me.

-----------------------------

my PHP version: 8.0.10
my Composer version: 2.2.3

![mpdf](https://user-images.githubusercontent.com/24317465/147875200-58ba1526-dc88-479b-acfd-7c0118ec8969.PNG)

**Comment by MisaghMi** [comment]
So you don't have anything for helping me ? :(

**Comment by finwe** [comment]
- this is not an issue of mPDF
- issue tracker does not serve for general troubleshooting

follow contribution location
