### ISSUE TITLE
TypeError : Unsupported operand types: int + string, when converting 'colspan=\"9\"'

### ISSUE THREAD

**Issue by ArtemGoutsoul** [mpdf/mpdf#1597]
### I found this bug
`TypeError : Unsupported operand types: int + string` when converting `'colspan=\"9\"'`

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
PHP 8.0, mpdf 8.0.15

The same piece of code does not break in PHP 7.4

### PHP + HTML code

```
<?php
$mpdf = new Mpdf\Mpdf();
$mpdf->WriteHTML('<table><tr><td colspan=\"9\"></td></tr></table>');
```

This is what I get:
```
TypeError : Unsupported operand types: int + string
 /var/www/nexus/lib/vendor/mpdf/mpdf/src/Tag/Td.php:403
 /var/www/nexus/lib/vendor/mpdf/mpdf/src/Tag.php:240
 /var/www/nexus/lib/vendor/mpdf/mpdf/src/Mpdf.php:13812
...
```

Seems like this place is the issue:
https://github.com/mpdf/mpdf/blob/v8.0.15/src/Tag/Td.php#L401
```
		if (isset($attr['COLSPAN']) && $attr['COLSPAN'] > 1) {
			$cs = $this->mpdf->cell[$this->mpdf->row][$this->mpdf->col]['colspan'] = $attr['COLSPAN'];
		}
```
should be:
```
		if (isset($attr['COLSPAN']) && $attr['COLSPAN'] > 1) {
			$cs = $this->mpdf->cell[$this->mpdf->row][$this->mpdf->col]['colspan'] = (int)$attr['COLSPAN'];
		}
```

**Comment by finwe** [comment]
Why would you escape double quotes in a string enclosed in single quotes? Without the escaping the code works as intended.

The cast will not work anyway, because the colspan is parsed out to be a backslash.

**Comment by ArtemGoutsoul** [comment]
Good point! My suggestion was useless.

Not sure why the HTML was escaped like that, probably a typo. It was just something that I found in some old tests in our codebase and I noticed the tests breaking  when I started migration to PHP 8 :)

But good that it won't explode anymore!
