### ISSUE TITLE
Laravel 9 compatibility

### ISSUE THREAD

**Issue by webmastervinay** [mpdf/mpdf#1603]
### 8.0.15 and PHP version 8.1

Laravel 9 is about to release in 4-5 days. I tried with Laravel dev version and found that it doesn't support.

``` 
composer require mpdf/mpdf
```

throws error as following:

mpdf/mpdf[v8.0.14, ..., v8.0.15] require psr/log ^1.0 || ^2.0 -> found psr/log[1.0.0, ..., 1.1.4, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Do you plan to update the dependency?

**Comment by finwe** [comment]
Laravel does not enforce psr/log 3.x. mPDF cannot use psr/log 3.x because of return types and PHP <7 compatibility. Force your psr/log to version 2.x to maintain cross-compatibility.

**Comment by abotariq2010** [comment]
> Laravel does not enforce psr/log 3.x. mPDF cannot use psr/log 3.x because of return types and PHP <7 compatibility. Force your psr/log to version 2.x to maintain cross-compatibility.

How ??
