### ISSUE TITLE
png-image display corrupted for one specific image

### ISSUE THREAD

**Issue by j-engel** [mpdf/mpdf#1605]
### I found this bug
I have one specific png-image (attached below) that gets corrupted when included in a pdf file - resulting pdf-file attached also below. The problem is only with this specific file - we have lots of other - very similiar files - that can be included without problems.....

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPdf v. 8.0 (tried 8.0.4 and 8.0.17), php v. 7.4.18 and 7.1.33

### This is the PHP code snippet I use

```
<?php 
require_once __DIR__ . '/php/vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('<img src="FO_Ebs_3064_2_zweck.png">');
$mpdf->Image('FO_Ebs_3064_2_zweck.png', 10, 100);
$mpdf->Output('test','D');

```

### This is the referenced png:
![FO_Ebs_3064_2_zweck](https://user-images.githubusercontent.com/11960069/150564636-6d4ddc15-634e-4c89-accd-39594fbddf39.png)

### This is the resulting pdf:
[test.pdf](https://github.com/mpdf/mpdf/files/7915240/test.pdf)

### This is how the image is displayed in the resulting pdf:
![grafik](https://user-images.githubusercontent.com/11960069/150565429-65864a35-8061-4ff7-89de-407e13a97ab6.png)

Anybody an idea what might be going wrong? Corrupted color palette?

**Comment by finwe** [comment]
Closing as a general troubleshooting. Did you try to re-save the PNG?
