### ISSUE TITLE
svg with @import font not showing the right font

### ISSUE THREAD

**Issue by alanbqs** [mpdf/mpdf#1612]
### I found this bug
I have an SVG that references a googleapi font, but when trying to generate a PDF with the SVG included (via an img tag), then the text is shown but the font is wrong (it looks like it's showing Arial or some basic font)

The SVG is:
```
<svg width="1695" height="817" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" overflow="hidden">
   <defs> 
       <style> @import url("https://fonts.googleapis.com/css?family=Imperial+Script"); </style> 
       <clipPath id="clip0"><rect x="210" y="464" width="1695" height="817"/></clipPath>
    </defs><g clip-path="url(#clip0)" transform="translate(-210 -464)"><text font-family="'Imperial Script', cursive" font-weight="700" font-stretch="semi-expanded" font-size="257" transform="matrix(1 0 0 1 499.688 764)">Lorem Ipsum<tspan font-size="257" x="-135.483" y="277">Delor</tspan></text></g></svg>
```
and the HTML put into mpdf is:
```
 <img style='height:80px; width:auto; max-width:155px' src='../images/tmp/4.xxx.svg'>
```
(the folder this sits in is visible to the webserver, and the SVG is fine if rendered through a http://localhost/images/tmp/4.xxx.svg type request)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF v8.0.0
PHP v7.4.27

**Comment by finwe** [comment]
Not a bug. mPDF has only a partial SVG support, this usage of fonts in SVG is not supported.
