### ISSUE TITLE
PHP 8.1 uses HTML parsing functions in other way

### ISSUE THREAD

**Issue by panvid** [mpdf/mpdf#1616]
See: https://www.php.net/manual/en/function.htmlspecialchars.php

> 8.1.0 | flags changed from ENT_COMPAT to ENT_QUOTES \| ENT_SUBSTITUTE \| ENT_HTML401.

https://github.com/mpdf/mpdf/blob/development/src/Tag/BlockTag.php#L1005

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
