### ISSUE TITLE
Error in setSourceFile()

### ISSUE THREAD

**Issue by random-webdeveloper** [mpdf/mpdf#1617]
### I found this bug
using $mpdf->setSourceFile($pathToPdf) on the attached pdf produced the error "Uncaught setasign\Fpdi\PdfParser\Type\PdfTypeException: Numeric value expected."
Havent found any issues on here related to this.
It works flawlessly with other pdfs. Pdf-viewers can open it

[Ansicht_Süd-West.PDF](https://github.com/mpdf/mpdf/files/8078887/Ansicht_Sud-West.PDF)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

PHP 8.0.8 fpm and php 7.4 server (both have the same issue)
mPDF newest version (8.0.17)

### This is the PHP code snippet I use

```
<?php
 $mpdf->setSourceFile($pathToPdf)

```

**Comment by finwe** [comment]
The error originates from setasign/fpdi, not mPDF.

**Comment by finwe** [comment]
(You could have saved others' time debugging had you attached the entire stack trace of the error. Or looked at it yourself, for that matter.)

**Comment by random-webdeveloper** [comment]
You should probably add a stack trace section in your bug report template then. i thought this was enough

**Comment by finwe** [comment]
OMG, a stack trace is *error* reporting 101. Even including the file/line of the actual error would show the error is not coming from mPDF. But no, rushing to create an issue straight away is apparently the easier option.

**Comment by finwe** [comment]
Sorry for being so cranky.
