### ISSUE TITLE
Undefined variable $mamp

### ISSUE THREAD

**Issue by vmartins** [mpdf/mpdf#1619]
### I found this bug
```
Undefined variable $mamp {"exception":"[object] (ErrorException(code: 0): Undefined variable $mamp at vendor/mpdf/mpdf/src/Mpdf.php:9658)
```
[Mpdf.php#L9658](https://github.com/mpdf/mpdf/blob/v8.0.17/src/Mpdf.php#L9658)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF v8.0.17
PHP without mbstring extension

**Comment by Klap-in** [comment]
How is Mpdf instantiated in your setup?
Which html is feeded into mPDF, such that it triggers this error?  (please provide a complete, but small as possible html example)

This is needed for reproducing your case, and allows to create the unit test for this issue. Thanks!

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
