### ISSUE TITLE
setImportUse() no longer supported?

### ISSUE THREAD

**Issue by jonathan-dejong** [mpdf/mpdf#162]
### I have this problem
Maybe related: https://github.com/mpdf/mpdf/issues/28

So I've tried reverting all the way back to v6.0 but I can't get setImportUse to work. 
Using 6.0 I get the following error:
`PHP Fatal error:  Call to undefined method mPDF::SetImportUse() in /srv/www/projects/sdab-deklaration/htdocs/wp-content/plugins/generate-declarations/admin/class-generate-declarations-admin.php on line 351`

With 7.0 I instead see an issue saying I need to run composer update etc. etc. 

I've set `enableImports` to true in config.php. 

Does mpdf require the use of composer now? 

### These are mPDF and PHP versions I am using
Tried both 6.0, 6.1 and 7.0 with PHP versino 5.6.21

### Function used to merge pdfs

```
<?php
private function merge_PDFs( $files, $path ){

		$pdf = new mPDF('', '', 0, '', 15, 15, 6, 12, 9, 9, 'P');
		$pdf->enableImports = true;
		foreach( $files as $file ){
		    $pdf->SetImportUse();

			$pagecount = $pdf->SetSourceFile($file);
			for ($i=1; $i<=($pagecount); $i++) {
			    $pdf->AddPage();
			    $import_page = $pdf->ImportPage($i);
			    $pdf->UseTemplate($import_page);
			}
		}

		$pdf_name = date('Y-m-d_His') . '.pdf';
		$pdf_path = $path . $pdf_name;

		//Make sure path exists
		if (!file_exists($path)) {
		    mkdir($path, 0777);
		}

		$pdf->Output($pdf_path, 'F');
		unset($pdf);
		return $pdf_path;

	}

```

**Comment by jonathan-dejong** [comment]
Nvm I'm so f*ing tired today.. I had forgotten to enable imports in compress.php for 6.0.

**Comment by Klap-in** [comment]
Please don't start new, not related, discussions in this old and closed issue. Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting. Thanks!
