### ISSUE TITLE
Temprary directory does not take into account Windows directory separator

### ISSUE THREAD

**Issue by tkfv** [mpdf/mpdf#1620]
In the ServiceFactory.php file there is this line: `$cacheBasePath = $config['tempDir'] . '/mpdf';`. The code is using the Unix directory separator `/`. But in Windows this will result in a broken path like this: `C:\Windows\TEMP\mpdf/mpdf`.

It seems that the correct code should be:

`$cacheBasePath = $config['tempDir'] . DIRECTORY_SEPARATOR . 'mpdf';`

**Comment by finwe** [comment]
This works, windows accepts forward slash as a directory separator.
