### ISSUE TITLE
I am getting a Fatal error for PHP version 8.1.3 and Latest version of mpdf

### ISSUE THREAD

**Issue by s1k3** [mpdf/mpdf#1621]
### Error Message I am Receiving

```

PHP Fatal error:  Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void in /home/robin/Projects/test/vendor/mpdf/mpdf/src/Mpdf.php on line 1569

```

### This is the HTML/CSS code snippet I use

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>
<body>
<p>This is test</p>
</body>
</html>
```

**Comment by finwe** [comment]
your dependencies are off, mPDF is not compatible with psr/log 3.x which you have (except 8.0.16 by mistake, which is not the latest version)

**Comment by coffeeyoghurt** [comment]
For anyone looking in this topic, set your composer version to at least 8.0.17. `"mpdf/mpdf": "^8.0.17"`. If you have `8.0.16` installed you will not be able to upgrade to `8.0.17` by just calling `composer update` because your system already has PSR 3.0 installed and PSR 3.0 is not supported in `8.0.17`

**Comment by plezan** [comment]
I have exactly the same error using 
- php 8.1.3
- mpdf 8.0.17
- psr/log 2.0.0
Do you know if downgrading to an older version could fix that ?

**Comment by finwe** [comment]
This is not a troubleshooting location. You cannot get this error if you really have the versions you are describing.
