### ISSUE TITLE
PHP 7.1 compatibility

### ISSUE THREAD

**Issue by blacksheep-dev** [mpdf/mpdf#163]
mPDF is now working with PHP 7.1

I'm using mPDF 7.0.x-dev f316a8b

<?php
$pdf->WriteHTML($html);
?>

causes:

ErrorException in cssmgr.php line 1302:
Illegal string offset 'ID'.

The only workaround I found is:

error_reporting(E_ERROR);

**Comment by finwe** [comment]
Please, attach a HTML snippet you are using.

mPDF does not support PHP 7.1 so you will have to wait for a newer version.

**Comment by blacksheep-dev** [comment]
<!DOCTYPE html>
<html>
<head>
</head>

<body>

</body>

</html>

**Comment by finwe** [comment]
Notices and warnings from PHP 7.1 on HTML snippets from examples repository were fixed in ac56fae.

**Comment by StalkAlex** [comment]
Here's problem incompatible problem too https://github.com/mpdf/mpdf/issues/288

**Comment by gpsingh159** [comment]
in mpdf.php file change this
$errorlevel = error_reporting($errorlevel & ~(E_NOTICE|E_WARNING));
i fixed this issue like this.
khalsasoft

**Comment by mksaini-77** [comment]
SAME ISSUE ON MY PROJECT 
ONLY A HTML TAG MAYBE NOT CLOSE PROPERLY CHECK AGAIN !!

**Comment by mksaini-77** [comment]
SAME ISSUE ON MY PROJECT
ONLY A HTML TAG MAYBE NOT CLOSE PROPERLY CHECK AGAIN !!

 ERROR - 2022-08-26 06:57:16 --> Severity: Warning --> Illegal string offset 'ID' /home/atwogroups/a2rms.testwebs.in/application/third_party/mpdf/classes/cssmgr.php 1334

ERROR - 2022-08-26 06:57:16 --> Severity: Warning --> Illegal string offset 'LANG' /home/atwogroups/a2rms.testwebs.in/application/third_party/mpdf/classes/cssmgr.php 1334

**Comment by finwe** [comment]
@mksaini-77 This issue is closed and your mPDF version is outdated and not supported. Update first and if still experiencing problems, create a new issue or a discussion thread.
