### ISSUE TITLE
SVG images are crumbled in the generated PDF document 

### ISSUE THREAD

**Issue by Laci357** [mpdf/mpdf#1653]
### I found this bug
SVG image shows flawless in browsers. When PDF is generated, the image is crumbled. 
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF version:  8.0.17
PHP version: 8.0.17

### This is the PHP code snippet I use
```
<?php
require __DIR__ . '/../vendor/autoload.php';
use mpdf\mpdf;

$mpdf = new \Mpdf\Mpdf([
	'showImageErrors' => true,
	'mode' => 'utf-8',
	'format' => 'A4',
	'tempDir' => __DIR__ . '/temp'
]);

$pathToFinalPDFfile = __DIR__.'/../../pdf/test.pdf';
$mpdf->writeHTML('<p class="p_Normal" style="text-align: center;"><img alt="test" width="539" height="482" src="./test.svg"/></p>');
$mpdf->Output($pathToFinalPDFfile, \Mpdf\Output\Destination::FILE)
?>



```

### This is the HTML/CSS code snippet I use
![test](https://user-images.githubusercontent.com/44972342/165509267-c1318c4d-1eca-4a3d-8652-09a2de7372a1.svg)

```
[test.pdf](https://github.com/mpdf/mpdf/files/8571604/test.pdf)

```

**Comment by finwe** [comment]
- Support for SVG is [declared as partial only](https://mpdf.github.io/what-else-can-i-do/images.html#svg-images)
- Not even Firefox can [directly interpret your SVG file](https://user-images.githubusercontent.com/195675/165510370-03ac1df5-e7dd-4b4f-903f-d50256e445ad.png)
- The same as with document HTML in mPDF is also valid for SVG code: custom tweaking may be necessary for the file to be rendered correctly.

**Comment by Laci357** [comment]
Thanks for the quick response. 

> "Not even Firefox can [directly interpret your SVG file](https://user-images.githubusercontent.com/195675/165510370-03ac1df5-e7dd-4b4f-903f-d50256e445ad.png)"

That's weird. I've just tried to right-click the .svg image and select **Open with** > **Firefox**. The image opened properly.
