### ISSUE TITLE
Possible bug with img tag where src with url to dynamicly generated image on backend

### ISSUE THREAD

**Issue by MactepDark** [mpdf/mpdf#1658]
### Controller:
```
* $this - instance of Yii2 Controller component
* $params - array with some data for displaying in pdf

public function actionPdfTemplate() {
    $mpdf = new Mpdf(['tempDir' => '/tmp']);
    $mpdf->WriteHTML($this->render('pdf-template', ['params' => $params]));
    return $mpdf->Output('pdf-template.pdf', Destination::INLINE);
}
```

### Part of pdf-template.php view file:
```
<div>
    <div>
        <img src="/getFileByID/1954.jpeg" alt="generated file" />
    </div>

    <div>
        <img src="/test_cat.jpeg" alt="physical file" />
    </div>
</div>
```

Result: 
![image](https://user-images.githubusercontent.com/10241885/168560977-0b404c1d-2063-490c-9f08-c9434b4d295b.png)

All is working fine, but not some style properties and this very strange bug...
Try to analyze response headers to find a difference && making its identicaly - not working anyway. In browser both url's working good - showing the cat :)

![image](https://user-images.githubusercontent.com/10241885/168567409-b94117a7-5106-4697-a5cd-82392df49d61.png)

Left window of devtools is physically existing image file
Right window of devtools is dynamicly generated image file. No matter how this is generated - it's worked - image content delivered to user by requested link with proper headers.

p.s. Trying to make dynamic url "to be like" an a physical file, adding an extension - nothing to change. E.g. from /getFileByID/1234 to /getFileByID/1234.jpg

p.p.s. sorry for my english.

**Comment by v-vovk** [comment]
+1

**Comment by zinchenko1** [comment]
+1

**Comment by zrayev** [comment]
+1

**Comment by finwe** [comment]
What mPDF version? Do you see any interesting information when you implement [logging](https://mpdf.github.io/installation-setup/logging.html) and debugging?

I suspect the second file is loaded by filesystem, not by a HTTP request. Do you run mPDF through a HTTP request, or a CLI? Does something change the other? Or when you use absolute URLs?

**Comment by MactepDark** [comment]
> 

mPDF 8.1.1

mPDF running through HTTP, its a part of project, loaded via composer autoloader
second file - its a http request to backend, **Request URL: http://spec-com-service.loc:88/getFileByID/1954.jpeg**
absolute or relative url in img src don't have a difference.

**Comment by MactepDark** [comment]
Sorry for issue, problem is found. And it not in mPDF.
