### ISSUE TITLE
Cannot read pseudo :after tag

### ISSUE THREAD

**Issue by sardiabuzubayr** [mpdf/mpdf#1663]
Hello,,

I am create line with "cut here" text in the middle. That i create using pseudo :after tag, when i use that and write using WriteHTML, the text "cut here" isn't showing.

This is my css :
.cut{
        width: auto;
        overflow: visible;
        padding: 0;
        border: none;
        border-top: 0.5px dashed #333;
        color: #333;
        text-align: center; 
        font-style: italic;
    }
    .cut:before{
        content: "Cut here";
        display: inline-block;
        position: relative;
        font-size: 10px;
        padding: 0 0.25em;
        background: white;        
        font-style: italic;
    }
 
Then i use it in hr tag isn't showing. And then i change hr to div tag but isn't showing too.

Is there somethings wrong?
<img width="577" alt="image" src="https://user-images.githubusercontent.com/39526377/169741200-e40af474-be35-4377-a392-800ffb0ccddb.png">

**Comment by finwe** [comment]
:after and other pseudo elements are not supported. https://mpdf.github.io/css-stylesheets/supported-css.html
