### ISSUE TITLE
WriteText() align text

### ISSUE THREAD

**Issue by m-dastagir** [mpdf/mpdf#1675]
# Feature request

I would like to use align text "Left, Right, Center" with WriteText() function. Currently only "Left" alignment is possible. Can this feature be added please?

`$pdf->WriteText(10, 10, "This is a text"); `

**Comment by finwe** [comment]
WriteText writes text to a specified position. There is no alignment in this use case. You want to use [WriteCell](https://mpdf.github.io/reference/mpdf-functions/writecell.html).

**Comment by m-dastagir** [comment]
yes but can't we have similar feature also for WriteCell(). I am asking only for the alignment to be added as an optional property.

**Comment by finwe** [comment]
That does not make any sense. WriteText writes a single line of text to a specified location, you cannot align that otherwise than changing the location.
