### ISSUE TITLE
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: host' in \vendor\mpdf\mpdf\src\CssManager.php:2304 Stack trace:

### ISSUE THREAD

**Issue by jose1894** [mpdf/mpdf#1677]
### I found this bug
Hi, I was using this code snippet using mPDF version 8.0.12 and it works!, but I have upgraded to new versions with composer, it installed mPDF 8.1.1, and all my reports are failed by this bug. 

PHP Notice 'yii\base\ErrorException' with message 'Undefined index: host' in C:\wamp64\www\fact\vendor\mpdf\mpdf\src\CssManager.php:2304 Stack trace: #0 C:\wamp64\www\fact\vendor\mpdf\mpdf\src\CssManager.php(2304): yii\web\ErrorHandler->handleError() #1 C:\wamp64\www\fact\vendor\mpdf\mpdf\src\CssManager.php(161): Mpdf\CssManager->normalizePath() #2 C:\wamp64\www\fact\vendor\mpdf\mpdf\src\Mpdf.php(13241): Mpdf\CssManager->ReadCSS() #3 C:\wamp64\www\fact\controllers\PedidoController.php(534): Mpdf\Mpdf->WriteHTML() #4 C:\wamp64\www\fact\vendor\yiisoft\yii2\base\InlineAction.php(57): app\controllers\PedidoController->actionPedidoRpt() #5 C:\wamp64\www\fact\vendor\yiisoft\yii2\base\InlineAction.php(57): ::call_user_func_array:{C:\wamp64\www\fact\vendor\yiisoft\yii2\base\InlineAction.php:57}() #6 C:\wamp64\www\fact\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams() #7 C:\wamp64\www\fact\vendor\yiisoft\yii2\base\Module.php(552): app\controllers\PedidoController->runAction() #8 C:\wamp64\www\fact\vendor\yiisoft\yii2\web\Application.php(103): yii\web\Application->runAction() #9 C:\wamp64\www\fact\vendor\yiisoft\yii2\base\Application.php(384): yii\web\Application->handleRequest() #10 C:\wamp64\www\fact\web\index.php(12): yii\web\Application->run() #11 {main}

### This is mPDF and PHP version and environment (server/fpm/cli etc) 
I am using
mPDF version: 8.1.1
PHP version: 7.3.21
SO: Windows 10 64 bits
### This is the PHP code snippet I use

```
/* Begin pedidoRpt view file content */
  <table class="table table-stripped" style="font-size:0.6rem;">
    <thead>
      <tr>
        <td class="left mayus bold">#</td>
        <td class="left mayus bold"><?= Yii::t('pedido','Code')?></td>
        <td class="left mayus bold"><?= Yii::t('pedido','Description')?></td>
        <td class="left mayus bold"><?= Yii::t('pedido','U.M.')?></td>
        <td class="left mayus bold"><?= Yii::t('pedido','Qtty')?></td>
        <!--td class="left mayus bold"><?= Yii::t('pedido','G.Price')?></td>
        <td class="left mayus bold">% <?= Yii::t('pedido','Disc')?></td-->
        <td class="right bold mayus"><?= Yii::t('pedido','N.Price')?></td>
        <td class="right bold mayus"><?= Yii::t('pedido','Total')?></td>
      </tr>
    </thead>
    <tbody>
    <?php
      foreach ($pedido->detalles as $key => $value) {
        // code...
        echo "<tr>";
        echo "<td style='width:5%;'>" . ($key + 1) . "</td>";
        echo "<td style='width:12%;'>{$value->productoPdetalle->cod_prod }</td>";
        echo "<td style='width:46%;word-wrap: break-word;'>{$value->productoPdetalle->des_prod }</td>";
        echo "<td style='width:7%;' class='right'>{$value->productoPdetalle->umedProd->des_und }</td>";
        echo "<td style='width:6%;' class='right'>{$value->cant_pdetalle }</td>";
        //echo "<td style='width:6%; text-align:right'>{$value->plista_pdetalle }</td>";
        //echo "<td style='width:8%; text-align:right'>{$value->descu_pdetalle }</td>";
        echo "<td style='width:8%;' class='right'>{$value->precio_pdetalle }</td>";
        echo "<td style='width:8%;' class='right'>{$value->total_pdetalle}</td>";
        echo "</tr>";
      }
    ?>
    </tbody>
  </table>
<?php
$this->registerCssFile("@rptcss/rptCss.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
    'media' => 'print',
], 'css-print-theme');
/* End pedidoRpt file content*/

/*Begin rptCss.css content file*/
body{
  font-family: 'Arial';
  font-size: 9px;
}

.center {
  text-align: center;
}

.right {
  text-align: right;
}

.left {
  text-transform: left;
}

.bold {
  font-weight: bold;
}

.datos-cliente {
  font-size: 17px;
  /*border-bottom:1px solid black;*/
}

.celdas {
  padding: 3px 5px;
}

.mayus {
  text-transform: uppercase;
}

.enc-fechas{
  width: 100%;
  border: 1px solid red;
  padding; 0 350px 0 0;
}

table {
  width: 100%;
}

.documento_enc{
  font-family: Arial;
}

.datos-emp{
  font-size: 16px;
}

.datos_documento {
  font-family: Arial;
  border-collapse: collapse;
  border: 1px solid black;
  margin-top: 10px;
}

.detalle_documento{
  font-family: Arial;
  font-size:11px;
}
.sumatoria_documento{
  font-family: Arial;
  font-size:14px;
  font-weight: bold;
  float: right;
  margin: 10px 10px;
}
.detalle_documento > tr > td {
  margin: 100px auto;
  padding:255px 0;
}

/*End rptCss.css content file*/

<?php
public function actionPedidoRpt($id) {
    Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
    $modelPedido = Pedido::findOne($id);
    $this->layout = 'reports';

    $content = $this->render('pedidoRpt', [
      'pedido' => $modelPedido,
    ]);     
    
    $sheet = file_get_contents(Yii::getAlias('@rptcss') . '/rptCss.css');
    $mpdf->WriteHTML($sheet, 1);

    $mpdf->SetHTMLHeader($header); // call methods or set any properties
    $mpdf->WriteHtml($content); // call mpdf write html
    $mpdf->SetHTMLFooter($footer);
    $titulo = $modelPedido->cod_pedido . '-' . $tipoPedido . '-' . $modelPedido->cltePedido->nombre_clte . '.pdf';
    $mpdf->SetTitle($titulo);
    $mpdf->Output($titulo, 'I'); // call the mpdf api output as needed
}
```

**Comment by finwe** [comment]
Your code example is missing reproducible HTML/CSS code. Please update.

**Comment by jose1894** [comment]
I've already updated my code example. Hope it helps to help me. Thanks!

**Comment by Klap-in** [comment]
Please note that this is not yet something anyone copy and run, without having your whole installation.
Please let PHP temporary print out the content of the variables $sheet, $content, $header, $footer and $titular, just for the point they are used in mpdf and paste their content here instead of the PHP script where we don’t know the variables/functions called.

**Comment by jose1894** [comment]
Thanks so much, I found a solution. I had to remake the function that renders the HTML content, and it works so.

Before, I sent a view with a layout with all headers to the mPDF writeContent function, and it recevied all this content and displayed as a report.

**Comment by finwe** [comment]
Closing as resolved/non-reproducible
