### ISSUE TITLE
Have problem with SetImportUse on php7.0

### ISSUE THREAD

**Issue by lisham** [mpdf/mpdf#168]
Hi,

### I have this problem/would like to have this functionality

When I tried to merge some pdfs using SetImportUse, the browser shown me this:
"The localhost page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500"
I'm familiar with this words since I've had to migrate to php7 but in this case I've no idea what should I do
Anyone has any Idea?

### These are mPDF and PHP versions I am using
mPDF: 6.1
PHP:  7.0.4-7ubuntu2.1

### This is a PHP code snippet I use

```
<?php
...
include("../../../mpdf/mpdf.php");
$mpdf=new mPDF('','A4-L', 0, '', 0, 0, 0, 0, 0, 0);
//$mpdf=new mPDF('',array(420,210), 0, '', 0, 0, 0, 0, 0, 0);
$mpdf->autoScriptToLang = true;
$mpdf->baseScript = 1;	// Use values in classes/ucdn.php  1 = LATIN
$mpdf->autoVietnamese = true;
$mpdf->autoArabic = true;

$mpdf->SetImportUse();

$the_pages = 'mpdf.pdf';

$pagecount = $mpdf->SetSourceFile($the_pages);
...
```

**Comment by finwe** [comment]
Either turn on error reporting or check errorlogs to see what exactly went wrong. It can also come in handy to [surround your code with a `try`/`catch` block](https://raw.githubusercontent.com/mpdf/mpdf.github.io/development/troubleshooting/blank-screen.md) as mPDF 6.1 throws an exception on errors.

**Comment by lisham** [comment]
Many thanks
I added "require_once '/var/www/html/mpdf/vendor/autoload.php';" and it worked
but I had to remarked "$mpdf->WriteHTML($html);" because of the same error.
Apparently in this case it is not necessary to be used.
Regards
