### ISSUE TITLE
Rewriting files with php 8 functions

### ISSUE THREAD

**Issue by Mehran-tr** [mpdf/mpdf#1695]
# Feature request

I found that these files in mpdf v8.0.10 and above use a switch statement, we can rewrite it with PHP 8 match expression 
these are files:
src/Barcode.php
src/Sharper/Sea.php
src/color/ColorSpaceRestrictor.php
src/color/ColorConverter.php

**Comment by finwe** [comment]
mPDF still supports PHP 5.6, so no.
