### ISSUE TITLE
Error "Trying to access array offset on value of type int" when generating PDF from PHPSpreadsheet

### ISSUE THREAD

**Issue by aylasyahirah** [mpdf/mpdf#1698]
Hello, I've recently encounter an error "Trying to access array offset on value of type int" when trying to generate PDF file from PHPSpreadsheet.
Currently I'm on PHP 7.4.

Attached is the screenshot of error.
<img width="435" alt="image" src="https://user-images.githubusercontent.com/9003015/183668977-7d3e4b55-977a-4bb4-b45a-ff959e850474.png">

After going through the code, it seems it occurs on the $cells[$i - 1][$j]['border'] variables, where I need to check that this variable is set or not first to make it go through as follow.
<img width="770" alt="image" src="https://user-images.githubusercontent.com/9003015/183669397-02de4b5a-acfa-407e-9fd9-6b03b0344430.png">

And one more the same error occur at line 21453 on variable $celladj['border_details']['L']['w'].

For the time being I commented it out the line 21453 until 21456 on my local machine to make it work.

**Comment by ssieb** [comment]
You deleted the issue template and didn't include any of the information that was asked for.

**Comment by m-paniez9292** [comment]
Hi,
I have the same problem after an upgrade to PHP 7.4 and I confirm this method to solve my problem.
My mPDF version is 7.1.9.

Thanks

**Comment by finwe** [comment]
PHP 7.4 is supported since mPDF v8.0.4
