### ISSUE TITLE
Image Path with Space in Filename Fails to Load

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#1700]
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

PHP 7.4 and latest development branch [fa54fd7](https://github.com/mpdf/mpdf/commit/fa54fd7f478bc347b7e3a5e94ba2da8fa5b0e592)

### This is the PHP code snippet I use

```
<?php

$mpdf = new \Mpdf\Mpdf(['mode' => 'c']);
$mpdf->WriteHTML('<img src="' . __DIR__ . '/image file.jpg" />');
$mpdf->Output();

```

**Comment by ssieb** [comment]
Don't the path and filename have to be url encoded?

**Comment by jakejackson1** [comment]
@ssieb URLs should, and are, URL encoded by mPDF. Filesystem paths should not be.
