### ISSUE TITLE
PHP 8.1 mbstring error

### ISSUE THREAD

**Issue by Vacman** [mpdf/mpdf#1706]
PHP Fatal error:  Uncaught Mpdf\MpdfException: mbstring extension must be loaded in order to run mPDF

Not sure what I need to change. If load up PHP 8.0 it works just fine. If I load 8.1 it crashes.

**Comment by Vacman** [comment]
From the error log:
[16-Aug-2022 16:20:10 UTC] PHP Fatal error:  Uncaught Mpdf\MpdfException: mbstring extension must be loaded in order to run mPDF in 
/home/xxx/public_html/xxx/mpdf/vendor/mpdf/mpdf/src/Mpdf.php:9669

**Comment by Klap-in** [comment]
Please google a bit, first hit is already your answer. https://www.google.com/search?q=mbstring+extension+must+be+loaded+in+order+to+run+mPDF+in 

_Further, in the issue template you are asked to ask troubleshooting question on stackoverflow. If everybody does, there is one place to find this kind of questions..._
