### ISSUE TITLE
Allow the ability to specifiy the CURLOPT_HTTP_VERSION when fecthing an image

### ISSUE THREAD

**Issue by oriongunning** [mpdf/mpdf#1714]
# Feature request

It would be great to be able to specify / overwrite additional CURL options when fetching images: 

For ex: 
curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);

Cheers, 
Orion

**Comment by finwe** [comment]
In 8.1, you can specify your own whole HTTP client behaving exactly as you want. https://github.com/mpdf/mpdf/releases/tag/v8.1.0
