### ISSUE TITLE
psr/log dependency breaks in PHP<8

### ISSUE THREAD

**Issue by taylorvance** [mpdf/mpdf#1716]
https://github.com/mpdf/mpdf/blob/f321f75c0a36214d17ba53134217e841d9b4d096/composer.json#L31

[Your docs](https://mpdf.github.io/about-mpdf/requirements-v7.html) say that PHP 7.4 is supported in mPDF 8.0.4. I am running PHP 7.4.30 and including mpdf ~8.0.4 in my composer.json. When I run the following simple example, I get this error from the psr/log package: `Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/vendor/psr/log/src/NullLogger.php on line 26`

```
$mpdf = new \Mpdf\Mpdf;
$mpdf->WriteHTML("<i>hello</i>");
echo $mpdf->Output('', 'S');
```

Looking at the source for NullLogger, it's using a [union type](https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.composite.union) which is **only supported as of PHP 8**.

In your composer.json, you specify psr/log `"^1.0 || ^2.0"`. If I include psr/log 1.1.4 in my own composer.json, all is well (as 1.1.4 only requires PHP 5.3). But if I inherit 2.0 from your package, it breaks, because [2.0 requires PHP 8](https://packagist.org/packages/psr/log#2.0.0).

**Comment by taylorvance** [comment]
In a nutshell, your docs say PHP 7.4 is supported, but your dependencies require PHP 8.0.

Easiest solution (but I'm not sure of side effects): remove `|| ^2.0` from your composer.json and just use the ^1.0 log version.

**Comment by jakejackson1** [comment]
Sounds like when you are running `composer install` in the CLI it is using a version of PHP 8.0 or higher and so it will install v2+ of the PSR Log package. You then run the code in a PHP7.4 environment and it breaks. 

The easiest fix for you is to update your `composer.json` configuration and [manually set the platform to the minimum version you want to support](https://github.com/GravityPDF/gravity-pdf/blob/development/composer.json#L8-L10). Then it doesn't matter if you run composer install with a later version of PHP.
