### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by that-guy-iain** [mpdf/mpdf#1719]
# Feature request

It would be good to have PHP 8.2 support. 

If you're wondering why I'm asking for 8.2 support when it's not out. I have a project using this library, and I'm starting the compatibility checks for 8.2, and this is why I've noticed it's not using it yet.

**Comment by finwe** [comment]
mPDF works with 8.2 fairly well (judging based on examples repo), apart from a single deprecated utf8_decode call, which could be omitted/replaced with iconv, need to research further.

Official support will of course also depend on dependencies compatibility and CI runner compatibility, but I hope support could be finished before 8.2.0 stable is out.

Additional testing and fixes and problematic code examples are always welcome.

**Comment by finwe** [comment]
CI is also OK with --ignore-platform-reqs https://github.com/mpdf/mpdf/actions/runs/3077081316/jobs/4971690024

**Comment by scholtz** [comment]
I am getting error with PHP8.2: 

```
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /app/vendor/mpdf/mpdf/mpdf.php on line 2349
```

I am using "mpdf/mpdf": "*", in composer

**Comment by finwe** [comment]
@scholtz 
1) you are off-topic here
2) PHP 8.2 is not officially supported yet, composer then installs v6.1.3 which is the last version that is not limited by the highest PHP supported version. You need to constraint your version and use --ignore-platform-reqs to install the last mPDF with PHP 8.2
