### ISSUE TITLE
TOCpagebreak - Added extra blank pages #1730

### ISSUE THREAD

**Issue by vijayasanthi1993** [mpdf/mpdf#1731]
TOCpagebreak - Added extra blank pages #1730

I tried to add a TOC but adds the blank pages

_Originally posted by @vijayasanthi1993 in https://github.com/mpdf/mpdf/discussions/1723#discussioncomment-3785301_

**Comment by finwe** [comment]
What are you trying to accomplish by spamming every possible category here?

**Comment by vijayasanthi1993** [comment]
Sorry,
I have added TOCpagebreak into my mpdf creation.
After adding this code the toc addes empty page before and after toc content.
Code: $this->m_pdf->pdf->TOCpagebreak();
How can i rectify this issue.

**Comment by Klap-in** [comment]
Please read the manual https://mpdf.github.io/reference/html-control-tags/tocpagebreak.html, and place all troubleshooting questions (such as your question) on stackoverflow https://stackoverflow.com/questions/tagged/mpdf. Be sure to add a small but _complete_ example if you ask a question on stackoverflow.
