### ISSUE TITLE
Incorrect pagination values with resetpagenum config

### ISSUE THREAD

**Issue by 4unkur** [mpdf/mpdf#1734]
### I found this bug

The pagination is wrong when used `resetpagenum` config in `WriteHtml()` 

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

PHP 8.0.24
mpdf/mpdf": "^8.1

### This is the PHP code snippet I use

```
<?php

require __DIR__ . '/../vendor/autoload.php';
ob_start();
include 'view.php';
$html = ob_get_clean();
$mpdf = new Mpdf\Mpdf();
$mpdf->WriteHTML($html);
$mpdf->Output();

```

### This is the HTML/CSS code snippet I use

```
<!DOCTYPE html>
<html>
<head>
    <title>Example</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        @page {
            margin-top: 20mm;
            footer: page-footer;
            resetpagenum: 3;
        }
    </style>
</head>

<body>

<?php for ($i = 0; $i < 100; $i++): ?>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet cumque delectus deleniti distinctio dolor dolore dolores enim magni molestiae molestias mollitia, provident quae quidem quo repellendus repudiandae tenetur vitae voluptatem?</p>
<?php endfor ?>

<htmlpagefooter name="page-footer">
    Page {PAGENO} of {nbpg}
</htmlpagefooter>

</body>

</html>

```

In the resulting PDF file it displays  
> Page 3 of 3
on each page.

**Comment by finwe** [comment]
`resetpagenum` should be only used with `:first` pseudoselector, see https://mpdf.github.io/css-stylesheets/supported-css.html

This behaviour makes sense, it resets the page number on _every_ page when used like this.

**Comment by 4unkur** [comment]
@finwe Thanks!  

Sorry to bother, but I have another somewhat related question:  
Is there any chance to set the total pages number manually?

In short, I have 3 PDF files: 1st one is not generated by mpdf, 2nd one is generated by mpdf and the third is also non-mpdf generated.  
At the end all 3 PDF files are merged into one, so I need to somehow adjust the total number because of the 3rd file (pages count is known). Explaining the situation, maybe there are other ways to solve it.
