### ISSUE TITLE
Should support psr/log 3.0

### ISSUE THREAD

**Issue by mrunalpittalia** [mpdf/mpdf#1741]
https://github.com/mpdf/mpdf/blob/0db129a868557016614132e2adc67f9e4c048d5e/composer.json#L31

I would be helpful if mpdf can have support to "psr/log": "^1.0 || ^2.0 || ^3.0"

**Comment by finwe** [comment]
Can not #1622

**Comment by mrunalpittalia** [comment]
Oh, that's sad!
Lot of Laravel 9 applications will not be able to continue with such in demand PDF generation library. 😞

**Comment by finwe** [comment]
Not true, Laravel 9 does not enforce psr/log 3.

**Comment by mrunalpittalia** [comment]
Yup, true. It does not forces but by default it installs psr/log 3.
So, I just tried to set it with psr/log 2 & successfully installed mpdf. 🤞🏻 I hope its the correct way.

Thanks.
