### ISSUE TITLE
Undefined array key "boxbottom"

### ISSUE THREAD

**Issue by hsmfawaz** [mpdf/mpdf#1745]
### I'm facing this bug  **Undefined array key "boxbottom"** 
it's a temporary bug because it occurs randomly with the same content provided sometimes it work and sometimes its not working and I cant find any reason why this bug appear

`
Undefined array key \"boxbottom\" at /www/wwwroot/project/vendor/mpdf/mpdf/src/Mpdf.php:11403
`

### This is mPDF:8.1.2 and PHP 8.0.20 version and environment (server/fpm/cli etc) I am using
server : ubuntu 20
fpm: yes

**Comment by leakeung** [comment]
I have a problem too!  Can anyone resolve it?  
sometimes it work and sometimes its not working

**Comment by hsmfawaz** [comment]
I fixed it in this fork
https://gitlab.com/hisham_fawaz/mpdf
