### ISSUE TITLE
Page numbering : adding a new parm 'nbpgGroup' in AddPage 

### ISSUE THREAD

**Issue by arena94** [mpdf/mpdf#1746]
# Feature request

I have a report with 3 group of pages : first group, second group, third group, ... 
first group as no page number,
Second has {PAGENO}/{nbpg} which works great 

Now i need to put on first page of first group that specific {nbpg} from the second group

I was considering adding a new parm in AddPage that could be named  'nbpgGroup'
and working like that when adding pages :

$mpdf->AddPageByArray( [ ... , 'nbpgGroup' => '{{my2ndgroup}}',  ] );

and then adding {{my2ndgroup}} in the text of the first group (in fact first page) would replace the computed number of pages belonging to that group ...

Besides PAGENO, nb and nbpg there should be an array memorizing the number of pages for different groups of pages.

Thank you for your comments (and guidelines).

Regards

**Comment by finwe** [comment]
This is so specific I don't think it is worth including to mPDF, sorry.

**Comment by arena94** [comment]
ok, found a turnaround anyway (first pass storing page number, second pass using it)
Thank you for your answer !
