### ISSUE TITLE
Incompatibility on PHP 8.1 (PHP 8.0 works fine)

### ISSUE THREAD

**Issue by oldrichpospisilik** [mpdf/mpdf#1747]
Hello,

**I found this issue:**
Its happened when:
$mpdf->AddPage(mgr: null)

strlen(): Passing null to parameter #1 ($string) of type string is deprecated
on line / file: [Mpdf.php:10261]

PHP 8.1, MPDF 8.1.2

Snippet of code o Mpdf.php:
```
// strlen()>0 is used to pick up (integer) 0, (string) '0', or set value
if ((strlen($mgl) > 0 && $this->DeflMargin != $mgl) || (strlen($mgr) > 0 && $this->DefrMargin != $mgr) ||
```
Thank you for solving issue in advance.

**Comment by finwe** [comment]
Share a reproducing code example, the issue can then be reopened.

**Comment by finwe** [comment]
Why would you pass a null to a string type parameter?

**Comment by oldrichpospisilik** [comment]
There is no type definition of this parameter, sorry if i am wrong. There is only default value. If i have overlooked this, sorry and please close the issue.

**Comment by finwe** [comment]
I was finally able to look at the code. I think passing null to a page margin does not make much sense - if needed, just pass an empty string, same as the default. It is ugly, yes, but given the age of the method signature "fixing" this in userland is quite simple. 

Making the parameters better typed and/or better named can be an improvement for the future, but with an unlikely gain in terms of DX and BC.
