### ISSUE TITLE
error undefined offset 

### ISSUE THREAD

**Issue by Bekzaat17** [mpdf/mpdf#1751]
https://github.com/mpdf/mpdf/blob/0db129a868557016614132e2adc67f9e4c048d5e/src/Mpdf.php#L20677

must be 					$extH = max($extH, $colH[$m] ?? $extH); // mPDF 6

**Comment by umangnine** [comment]
I completely agree with @Bekzaat17. This issue shouldn't be closed. It is still open in latest version 8.2 as well. Kindly fix this issue ASAP!

**Comment by finwe** [comment]
Kindly provide all issue requirements as per contribution guidelines. Until then, the issue will stay closed. @umangnine
