### ISSUE TITLE
Barcode EAN-13 strange character

### ISSUE THREAD

**Issue by shinnlu** [mpdf/mpdf#1754]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I am using the barcode tag to output EAN-13
`<barcode code="697173702913" type="EAN13" height="0.66" text="0"/>`
but i found there is strange character in barcode, then i execute the mpdf-examples/example37_barcodes.php, got the same result
![image](https://user-images.githubusercontent.com/570246/199184680-4a803a06-20b9-418c-a612-f29a801c082a.png)

mpdf-examples/example43_MPDFI_booklet.php
![image](https://user-images.githubusercontent.com/570246/199185050-e59160d1-43e3-42d4-958f-f423c1b6107e.png)

### mPDF version

8.1

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

php 8.0.16 + apache 2.4.47

### Reproducible PHP+CSS+HTML snippet suffering by the error

`<barcode code="697173702913" type="EAN13" height="0.66" text="0"/>`
or
mpdf-examples/example37_barcodes.php
mpdf-examples/example43_MPDFI_booklet.php

**Comment by finwe** [comment]
This is correct and according to specification. See [this answer at SO](https://stackoverflow.com/a/55510279/819007)
