### ISSUE TITLE
Some problem downloading PDF inside iframe

### ISSUE THREAD

**Issue by tiagocaus** [mpdf/mpdf#1755]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

PDF downloads without records from DB

### mPDF version

8.0

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

7.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

I'm generating a PDF inside an IFRAME. So far so good, all the data coming from the BD appears.

But when I right click to save, the data coming from the BD is blank.

**NOW....**
If I open the same screen outside of IFRAME, I can save the file with the data normally.

Do you have to activate something to be able to save the document coming from the iframe?

Thanks. 

````
<?php
//exit;
$html = ob_get_clean();
$mpdf = new Mpdf();

$mpdf->WriteHTML($html);
$arquivo = "Fatura para seguradora - Contrato " . $row['codigo'] . ".pdf";
$mpdf->Output($arquivo, Destination::INLINE);
?>
````

**Comment by finwe** [comment]
This is not a bug of mPDF.
