### ISSUE TITLE
How to flip /mirror text in mpdf

### ISSUE THREAD

**Issue by vishnupriya325** [mpdf/mpdf#1757]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

i need to flip/mirror html elements in mpdf. giving text-rotate:90 is rotating but i need to flip the text like mirrror image.how to do that in mpdf

### mPDF version

1.1.0

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 7.3.27 

### Reproducible PHP+CSS+HTML snippet suffering by the error

.horizontal-flip {
  -moz-transform: scale(-1, 1);
  -webkit-transform: scale(-1, 1);
  -o-transform: scale(-1, 1);
  -ms-transform: scale(-1, 1);
  transform: scale(-1, 1);
}

**Comment by vishnupriya325** [comment]
Isuue is not resolved.Could you please give solution

**Comment by finwe** [comment]
This is not an issue, it is a general troubleshooting and belongs to Discussions. Therefore it was closed directly based on contribution guidelines.

`transform` CSS property is supported only on images. https://mpdf.github.io/css-stylesheets/supported-css.html

To my knowledge, this cannot be currently done in mPDF.

**Comment by vishnupriya325** [comment]
ok thanks .can we do it with any other pdf libray in laravel.
