### ISSUE TITLE
Barcode tag with JSON object

### ISSUE THREAD

**Issue by hejplis12** [mpdf/mpdf#1761]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Not possible to send Json as code parameter in mPdf tag `<barcode>`
E.g. `{"t":1,"d":5}`
This text is skipped after first quotation mark and QR code displays only `{`

### mPDF version

v8.1.2

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 8.0, Windows Server

### Reproducible PHP+CSS+HTML snippet suffering by the error

`<barcode code="{"t":1,"d":5}" type="qr"/>`
`<barcode code='{"t":1,"d":5}' type="qr"/>`
neither works

**Comment by ssieb** [comment]
`<barcode code="{\"t\":1,\"d\":5}" type="qr"/>` ?

**Comment by hejplis12** [comment]
> `<barcode code="{\"t\":1,\"d\":5}" type="qr"/>` ?

The barcode tag is written in HTML. There is not possible to escape chars like that.

**Comment by ssieb** [comment]
Right, so then you would need to use entities or it's not valid html anyway.

**Comment by benjaminpick** [comment]
Valid HTML would be `<barcode code="{&quot;t&quot;:1,&quot;d&quot;:5}" type="qr"/>`, did you try that?
