### ISSUE TITLE
DivisionByZeroError

### ISSUE THREAD

**Issue by Ab-Alselwi** [mpdf/mpdf#1762]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I have use the library to generate pdf file from laravel blade with Arabic text, sometime FontSizePt returns zero, so it needs to check variable value to ignore Division By Zero Error.
error code :
$charspacing = ($this->charspacing * 1000 / $this->FontSizePt);
$wordspacing = ($this->ws * 1000 / $this->FontSizePt) ;

the following code fix the issue  : 
$charspacing = ($this->FontSizePt > 0 ) ? ($this->charspacing * 1000 / $this->FontSizePt) : 0;
$wordspacing = ($this->FontSizePt > 0) ? ($this->ws * 1000 / $this->FontSizePt) : 0;

### mPDF version

v8.0.13

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

php v8.1.0 , Apache 2.4.51, laravel 9.19

### Reproducible PHP+CSS+HTML snippet suffering by the error

error code :
$charspacing = ($this->charspacing * 1000 / $this->FontSizePt);
$wordspacing = ($this->ws * 1000 / $this->FontSizePt) ;

the following code fix the issue  : 
$charspacing = ($this->FontSizePt > 0 ) ? ($this->charspacing * 1000 / $this->FontSizePt) : 0;
$wordspacing = ($this->FontSizePt > 0) ? ($this->ws * 1000 / $this->FontSizePt) : 0;

**Comment by ssieb** [comment]
Why are you getting a 0 for font size?
