### ISSUE TITLE
PHP Warning: Undefined array key at Mpdf.php:_tableGetMaxRowHeight

### ISSUE THREAD

**Issue by pudovmaxim** [mpdf/mpdf#1765]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

If the table contains the cell with rowspan attribute with value greater than the amount of rows in first table group, it may result in the following PHP warning, which breaks the PDF generation: 

```` 
PHP Warning: Undefined array key 1 in /vendor/mpdf/mpdf/src/Mpdf.php line 20796
````

### mPDF version

8.1.3

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.1.13 (cli)

### Reproducible PHP+CSS+HTML snippet suffering by the error

````
<table>
        <tbody>
                <tr>
                        <td></td>
                        <td></td>
                </tr>
        </tbody>
        <tfoot>
                <tr>
                        <td rowspan="2"></td>
                </tr>
        </tfoot>
</table>
````

**Comment by pudovmaxim** [comment]
Here PR
#1766 https://github.com/mpdf/mpdf/pull/1766#issue-1468608950

**Comment by finwe** [comment]
Merged.
