### ISSUE TITLE
v8.1.3 does not handle large tables the same way as v8.1.2

### ISSUE THREAD

**Issue by nd4c** [mpdf/mpdf#1776]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

In version 8.1.3, if a table is long enough that it needs to be broken into two or more pages it will place a "New Page" after each and every single \</tr\> tag.

Version 8.1.2 would handle this correctly, fill the page and then place the "New Page" after the appropriate \</tr\> tag.

### mPDF version

8.1.3

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 8.0.26, Apache/2.4.54 (Ubuntu)  Also tested on Centos.

### Reproducible PHP+CSS+HTML snippet suffering by the error

Simply create a long table that would require at least two pages to print.

The configuration that works for me in version 8.1.2 is:
```
	'mode' => 'UTF-8',
	'format' => 'Letter',
	'default_font' => 'Arial',
	'tempDir' => {an accessible temp directory}
	'shrink_tables_to_fit' => 1,

```

**Comment by nd4c** [comment]
Fine, have it your way - on to headless Chrome...

**Comment by finwe** [comment]
Closing in favor of #1777
