### ISSUE TITLE
Does MPDF work with PHP built-in server?

### ISSUE THREAD

**Issue by mtangoo** [mpdf/mpdf#178]
OS: Ubuntu
PHP: 
```
~$ php -v
PHP 5.6.11-1ubuntu3.4 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

```

Code

```php
$mpdf = new \Mpdf\Mpdf();
$mpdf->writeHTML('<h1>Hello world!</h1>');
$mpdf->Output();
```

When I run the file, it just hangs. I find that in Apache it works fine.
In known issue there is no mention of Built in server not working. I have not found any issue on that.

So, is MPDF supposed to work fine with PHP Built in server?

**Comment by finwe** [comment]
mPDF is not tested with internal PHP server, so officially not supported.

**Comment by finwe** [comment]
However when I start the server in the examples repository, examples render as expected, so I guess it works (PHP 7.0.8)

**Comment by mtangoo** [comment]
It works but not stable. Sometimes it just stops without any error or notice!

So it mostly works

```
PHP 7.1.17 (cli) (built: Apr 26 2018 22:04:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.17, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

```

**Comment by Klap-in** [comment]
In the repo is a note about single-threaded servers (no idea if that fits to your case):
https://github.com/mpdf/mpdf#requirements

Not sure if this is documented at https://mpdf.github.io/ as well.

**Comment by mtangoo** [comment]
>>mPDF has some problems with fetching external HTTP resources with single threaded servers such as php -S.

Great note. But I wonder what does external refer to? Another different HTTP server or even within the server? What is considered external and what is not? I guess clarifying that will help a lot

**Comment by mtangoo** [comment]
Am asking because in logs I find lines like this and hangs the server
`[2018-05-30 06:27:35] name.DEBUG: Fetching (cURL) content of remote URL "http://localhost:8080/uploads/profile/image.png" {"context":"remote_content"} []`

**Comment by jakejackson1** [comment]
The built-in web server that ships with PHP [is single-threaded](https://secure.php.net/manual/en/features.commandline.webserver.php). Those CURL requests in your log would be blocking requests.

**Comment by Klap-in** [comment]
e.g. if images or other sources are requested that are loaded from the current page that is served.
Please see also the issue which let @finwe add this note https://github.com/mpdf/mpdf/issues/485

**Comment by mtangoo** [comment]
OK thanks. So in short, loading images is one of those cases where MPDF cannot work with builtin server. Thanks a lot!
