### ISSUE TITLE
Errore of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger)

### ISSUE THREAD

**Issue by ferasat** [mpdf/mpdf#1786]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

It gives the following error and stops working.

`Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void`

Please help me so that I can solve the problem.

php version 8.0.2
laravel version 9.45.1

### mPDF version

4.1

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.0.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

`[D:\xampp\htdocs\cms\*******\vendor\mpdf\mpdf\src\Mpdf.php : 1569](phpstorm://open?file=D%3A%5Cxampp%5Chtdocs%5Ccms%5Csnap_app%5Csnap_app%5Cvendor%5Cmpdf%5Cmpdf%5Csrc%5CMpdf.php&line=1569)

		// this will free up the readers, based on code from Setasign's FpdiTrait::cleanUp()

		foreach ($this->createdReaders as $id) {

			$this->readers[$id]->getParser()->getStreamReader()->cleanUp();

			unset($this->readers[$id]);

		}

		$this->createdReaders = [];

	}

	/**

	 * @param \Psr\Log\LoggerInterface

	 *

	 * @return \Mpdf\Mpdf

	 */

	public function setLogger(LoggerInterface $logger)

	{

		$this->logger = $logger;

		foreach ($this->services as $name) {

			if ($this->$name && $this->$name instanceof \Psr\Log\LoggerAwareInterface) {

				$this->$name->setLogger($logger);

			}

		}

		return $this;

	}

	private function initConfig(array $config)

	{`

**Comment by finwe** [comment]
https://stackoverflow.com/questions/74433569/mpdf-mpdf-loggerawareinterface-incompatibility-with-psr-log-in-php-8-1-12/74442440#74442440

**Comment by finwe** [comment]
How did you end up with incompatible versions installed? Composer should not allow you to do that.
