### ISSUE TITLE
Memory exhausted error when including a small PNG image

### ISSUE THREAD

**Issue by wq9578** [mpdf/mpdf#1789]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Memory is exhausted when trying to include a very small PNG image (a QR code).

Including a bigger PNG image (created with the mpdf/qrcode library) works, as well as using the barcode tag.

### mPDF version

8.1.1

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.2.0

### Reproducible PHP+CSS+HTML snippet suffering by the error

Files (PNG, PDF) attached below.

**PHP source code**

`    $mpdf->PDFA = true;
`

```
    $use_external_qrencode = true;
    $url = 'https://github.com/mpdf/mpdf';

    if ($use_external_qrencode) {
        // https://formulae.brew.sh/formula/qrencode
        $qrcode_png = '/tmp/qrcode_external_qrencode.png';
        exec('/opt/homebrew/bin/qrencode' . ' -o ' . escapeshellarg($qrcode_png) . ' ' . escapeshellarg($url), $output, $result_code);
    } else {
        $qrcode_png = '/tmp/qrcode_mpdf_qrcode.png';
        $qrCode = new QrCode($url);
        // Save black on white PNG image 100 px wide to filename.png. Colors are RGB arrays.
        $output = new Png();
        $data = $output->output($qrCode, 100, [255, 255, 255], [0, 0, 0]);
        file_put_contents($qrcode_png, $data);
    }

    system('ls -al ' . escapeshellarg($qrcode_png));
    $mpdf->Image($qrcode_png, 100, 100, 20, 20, '', $url);
```

**Error message**

```
   PHPUnit\Framework\ExceptionWrapper 

  PDFA/PDFX warnings generated. See log for further details

  at lib/others/pdf-a/mpdf/vendor/mpdf/mpdf/src/Mpdf.php:9557
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in [...]/vendor/nunomaduro/collision/src/Highlighter.php on line 212

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in [...]/vendor/nunomaduro/collision/src/Highlighter.php on line 212
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in [...]/vendor/filp/whoops/src/Whoops/Util/Misc.php on line 1

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in [...]/vendor/filp/whoops/src/Whoops/Util/Misc.php on line 1
```

**Files**

Small PNG (348 bytes) causing error:
![qrcode_external_qrencode](https://user-images.githubusercontent.com/121522862/211916743-9c5462a2-a95c-487c-a4e3-d68837f89926.png)

Medium-size PNG (30 KB) working well:
![qrcode_mpdf_qrcode](https://user-images.githubusercontent.com/121522862/211916818-0a613e58-671b-4304-89d8-9c25401a2743.png)

PDF produced with medium-size PNG:
[mpdf_image_test.pdf](https://github.com/mpdf/mpdf/files/10395948/mpdf_image_test.pdf)

**Comment by finwe** [comment]
Unable to reproduce, the small PNG file works just fine (except that with PDFA set to true, the generating fails because PDFA does not allow transparency in PNG images). 
Your example is not quite reproducible by itself, is it?

**Comment by wq9578** [comment]
Running the script (below) separately, the memory exhausted error indeed disappears.
The memory exhaustion seems to be a problem of the framework I am using, not of mpdf.

However, there are still two problems:
1. There is no clear error message pointing to transparency as the problem (`PDFA/PDFX warnings generated. See log for further details `). I couldn't find any other log than that for PHP.
2. Are you sure that the image has transparency? When placing it over another image (e.g., in Apple Preview or Adobe Photoshop), the background appears white, not transparent. However, I am not an export on this.

**Error message**

```
Fatal error: Uncaught Mpdf\MpdfException: PDFA/PDFX warnings generated. See log for further details in [...]/vendor/mpdf/mpdf/src/Mpdf.php:9557
Stack trace:
#0 [...]/mPDFTest.php(33): Mpdf\Mpdf->Output('mpdf_image_test...', 'F')
#1 {main}
  thrown in [...]/vendor/mpdf/mpdf/src/Mpdf.php on line 9557
```

**Script**

```
<?php
require __DIR__ . '/vendor/autoload.php';

use Mpdf\Mpdf;
use Mpdf\Output\Destination;
use Mpdf\QrCode\Output\Png;
use const Tests\Feature\PDF_SOURCE_PATH;

$use_external_qrencode = true;
$pdfa = true;

$url = 'https://github.com/mpdf/mpdf';

$mpdf = new Mpdf(['margin_left' => 25, 'margin_right' => 25, 'margin_top' => 25, 'margin_bottom' => 25]);

$mpdf->PDFA = $pdfa;

if ($use_external_qrencode) {
    // https://formulae.brew.sh/formula/qrencode
    $qrcode_png = '/tmp/qrcode_external_qrencode.png';
    exec('/opt/homebrew/bin/qrencode' . ' -o ' . escapeshellarg($qrcode_png) . ' ' . escapeshellarg($url), $output, $result_code);
} else {
    $qrcode_png = '/tmp/qrcode_mpdf_qrcode.png';
    $qrCode = new \Mpdf\QrCode\QrCode($url);
    // Save black on white PNG image 100 px wide to filename.png. Colors are RGB arrays.
    $output = new Png();
    $data = $output->output($qrCode, 100, [255, 255, 255], [0, 0, 0]);
    file_put_contents($qrcode_png, $data);
}

$mpdf->Image($qrcode_png, 100, 100, 20, 20, '', $url);

$mpdf->Output('mpdf_image_test.pdf', Destination::FILE);
```

**Comment by wq9578** [comment]
I split the problem into three parts:
1. The memory exhaustion problem is obviously not caused by mPDF.
2. https://github.com/mpdf/mpdf/issues/1792
3. https://github.com/mpdf/mpdf/issues/1793
