### ISSUE TITLE
Add hyperlink option to function WriteFixedPosHTML()

### ISSUE THREAD

**Issue by wq9578** [mpdf/mpdf#1791]
### Please describe the new functionality as best as you can.

I am trying to print a clickable text rotated by 90 degrees, with rotation defined in the CSS provided to WriteFixedPosHTML() with the $html parameter shown below.
Placing an `<a>` HTML tag inside the $html parameter didn't work.
Therefore a hyperlink option should be added (as [suggested](https://github.com/mpdf/mpdf/issues/1790) also for the barcode tag).

```
$html = '<div style="font-size:12px; position: absolute; rotate: -90; text-align: left; width: 100mm;">
    Some text <br>
    Some further text </div>';
```

**Comment by finwe** [comment]
Using `<a>` in the HTML works normally. Create a discussion first with a code example if you are not sure the error is not on your part.
[mpdf.pdf](https://github.com/mpdf/mpdf/files/10399045/mpdf.pdf)

**Comment by wq9578** [comment]
You are correct. It works now.
The problem was caused by a program layer modifying the PDF later on.
