### ISSUE TITLE
PDFA/PDFX warnings not available

### ISSUE THREAD

**Issue by wq9578** [mpdf/mpdf#1792]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

The PDFA/PDFX warnings announced are not available.
For details see no.1 at: https://github.com/mpdf/mpdf/issues/1789#issuecomment-1379580895

### mPDF version

8.1.1

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

See link above.

**Comment by finwe** [comment]
See https://mpdf.github.io/installation-setup/logging.html and [Mpdf::$PDFAXwarnings] property (https://mpdf.github.io/what-else-can-i-do/pdf-x-1a-compliance.html#warnings)
