### ISSUE TITLE
Including a small PNG image fails for PDF/A generation

### ISSUE THREAD

**Issue by wq9578** [mpdf/mpdf#1793]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Details are described here: https://github.com/mpdf/mpdf/issues/1789#issuecomment-1379580895

The image obviously doesn't contain any transparency.

I have placed it over another picture in both Apple Preview and Adobe Photoshop, and it has a white background.
For comparison, I also placed a PNG with a transparent background, and the background was transparent.

Also, when opening the color table in Photoshop (Image > Mode > Color Table, as described [here](https://helpx.adobe.com/photoshop/using/customizing-indexed-color-tables.html)), only two colors (black and white) are shown, and only these are used in the image, which consists only of a few pixels.

### mPDF version

8.1.1

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

See link above.

**Comment by finwe** [comment]
The image has the alpha channel as noted in the previous Issue.

```
identify -format '%A' qr.png
True
```

**Comment by wq9578** [comment]
Thanks, you are right.

I solved it by using a different QR code utility.

My output:

```
➜  identify -format '%A' qr-small.png 
Blend%                                                                          
➜  identify -format '%A' qr-medium.png 
Undefined%                                                                      
```

`%A | image transparency channel. Values include Undefined (no transparency channel), Blend, Copy, or Update.` ([Link](https://imagemagick.org/script/escape.php))
