### ISSUE TITLE
Using a second font fails

### ISSUE THREAD

**Issue by wq9578** [mpdf/mpdf#1797]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Using a second font fails.

The first WriteHTML() call (see below) uses _OpenSans-Bold_, as desired.
The second WriteHTML() call uses _DejaVuSansMono_ instead of the desired _Courier New_.

I followed the instructions at https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html

### mPDF version

8.1.4

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
        $defaultConfig = (new ConfigVariables())->getDefaults();
        $fontDirs = $defaultConfig['fontDir'];

        $defaultFontConfig = (new FontVariables())->getDefaults();
        $fontData = $defaultFontConfig['fontdata'];

        $mpdf = new Mpdf([
            'fontDir' => array_merge($fontDirs, [
                resource_path('fonts'),
                '/System/Library/Fonts/Supplemental'
            ]),
            'fontdata' => $fontData + [ // lowercase letters only in font key
                    'opensans' => [
                        'R' => 'OpenSans-Regular.ttf',
                        'B' => 'OpenSans-Bold.ttf',
                    ],
                    'courier' => [
                        'R' => 'Courier New.ttf',
                    ],
                ],
            'default_font' => 'OpenSans',
            'default_font_size' => 9,
            'margin_left' => 25,
            'margin_right' => 25,
            'margin_top' => 25,
            'margin_bottom' => 25,
        ]);

        $mpdf->PDFA = true;

        $mpdf->WriteHTML(
            '<b>Test</b><br>' .
            '<hr>');

        $mpdf->WriteHTML('<br><pre style="font-family: courier">' . json_encode($this->parameters, JSON_PRETTY_PRINT) . '</pre>');
```

**Comment by finwe** [comment]
use a different font key than `courier`, that works.

**Comment by wq9578** [comment]
Thanks, it works perfectly!
Maybe this information should be included in the instructions linked above.
