### ISSUE TITLE
Protocol "file" not supported or disabled in libcurl after upgrading from v7 to v8

### ISSUE THREAD

**Issue by 37Rb** [mpdf/mpdf#1803]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I'm upgrading a site from mPDF 7.1.9 to 8.1.4 because the servers are being upgraded and the older version isn't working with PHP 8. It solved the PHP 8 problems but the background image isn't showing up in the generated PDF anymore. When I enable debug I get this error.

```
PHP Fatal error: Uncaught Mpdf\MpdfException: cURL error: "Protocol "file" not supported or disabled in libcurl" in .../vendor/mpdf/mpdf/src/Http/CurlHttpClient.php:90
```

Here is the part of my HTML template that uses file protocol and worked in mPDF 7 but isn't working anymore.

```
	body {
		background-image: url(file:///public/html/images/My-Background-Image.png);
		background-image-resize: 6; /* custom mpdf style */
		font-family: monserrat;
		font-size: 14pt;
	}
```

Are file:// URLs no longer supported for background images? If not, is there another way to use a local file as the background image?

### mPDF version

8.1.4

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 8.1.14 (cli) (built: Jan 13 2023 10:43:22) (NTS) Copyright (c) The PHP Group Zend Engine v4.1.14, Copyright (c) Zend Technologies     with Zend OPcache v8.1.14, Copyright (c), by Zend Technologies

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
<html>
<head>
<title>Hello</title>
<style>
	body {
		background-image: url(file:///public/html/images/My-Background-Image.png);
		background-image-resize: 6; /* custom mpdf style */
		font-family: monserrat;
		font-size: 14pt;
	}
	.myfixed {
    position: absolute;
    overflow: visible;
    left: 0;
    right: 0;
    width: 100%;   /* you must specify a width */
    margin-top: auto;
    margin-bottom: auto;
    margin-left: auto;
    margin-right: auto;
    text-align: center;
}
</style>
</head>
<body>
```

**Comment by finwe** [comment]
This is not an issue of mPDF but rather of your setup.

**Comment by 37Rb** [comment]
Oh I see the library in mPDF just uses the system cURL so they must have disabled file protocol when they upgraded the server. Makes sense. Thanks!
