### ISSUE TITLE
Return types error with version 2.0.0?

### ISSUE THREAD

**Issue by johnrodwell-affinity** [mpdf/mpdf#1804]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

So I've seen your correspondence re: lack of support for psr/log version 3 with return types for campatibility (fine by me!) and I've therefore downgraded our project to version 2.0.0 so we can still use mPDF. The problem is I'm still getting an error though:

`PHP Fatal error:  Declaration of Mpdf\\Mpdf::setLogger(Psr\\Log\\LoggerInterface $logger) must be compatible with Psr\\Log\\LoggerAwareInterface::setLogger(Psr\\Log\\LoggerInterface $logger): void in [PATH REMOVED]/Mpdf.php on line 1587, referer: [URL REMOVED]`

Well, you might say, he's obviously still got version 3.0.0 installed. But not so. The LoggerAwareInterface class in the vendor directory looks like this:

`<?php

namespace Psr\Log;

/**
 * Describes a logger-aware instance.
 */
interface LoggerAwareInterface
{
    /**
     * Sets a logger instance on the object.
     *
     * @param LoggerInterface $logger
     *
     * @return void
     */
    public function setLogger(LoggerInterface $logger);`

There is no void return type in that code. This doesn't make any sense to me. Have I missed something obvious? Has anyone got any ideas?

Thank You! I will cross post to psr/log repo and stackoverflow for full coverage and will link if I get any response.

### mPDF version

Latest

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 8.1 Apache

### Reproducible PHP+CSS+HTML snippet suffering by the error

`PHP Fatal error:  Declaration of Mpdf\\Mpdf::setLogger(Psr\\Log\\LoggerInterface $logger) must be compatible with Psr\\Log\\LoggerAwareInterface::setLogger(Psr\\Log\\LoggerInterface $logger): void in [PATH REMOVED]/Mpdf.php on line 1587, referer: [URL REMOVED]`

**Comment by finwe** [comment]
I doubt the version in vendor directory is being loaded then. Maybe opcache is the culprit and apache should be reloaded? Anyway, I don't see this as an issue of mPDF itself.
