### ISSUE TITLE
User Deprecation for LoggerAwareInterface

### ISSUE THREAD

**Issue by dev-kat** [mpdf/mpdf#1806]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I get the following error message when I use the constructor to create a new PDF.
"User Deprecated: Method "Psr\Log\LoggerAwareInterface::setLogger()" might add "void" as a native return type declaration in the future. Do the same in implementation "Mpdf\Writer\MetadataWriter" now to avoid errors or add an explicit @return annotation to suppress this message."

### mPDF version

8.1.4

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.1

### Reproducible PHP+CSS+HTML snippet suffering by the error

$mpdf = new Mpdf([
                             'mode'          => 'de-DE',
                             'format'        => 'A4',
                             'margin_left'   => 25,
                             'margin_right'  => 10,
                             'margin_top'    => 54,
                             'margin_bottom' => 34,
                             'margin_header' => 9,
                             'margin_footer' => 9,
                             'orientation'   => 'P'
                         ]);``

**Comment by finwe** [comment]
How did you install the psr/log 3 along with mPDF? They are incompatible by composer.json dependencies definition. See https://stackoverflow.com/questions/74433569/mpdf-mpdf-loggerawareinterface-incompatibility-with-psr-log-in-php-8-1-12/74442440#74442440

**Comment by finwe** [comment]
Oh, I get it now. But this is caused by an external library, not mPDF or PHP itself, is it?
