### ISSUE TITLE
PDF opening without password when using Finder on Mac

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#181]
One of my users reported an issue with Finder on Mac. They say they can open a PDF generated with mPDF 6.1 without a password even though the PDF is password protected. I can't verify this claim as I run Windows, and Adobe Reader (and other programs I tested) all show the password prompt correctly. I even checked it's working on my iPhone. 

[Here's a link to the document](http://clients.blueliquiddesigns.com.au/document.pdf), and the password is: STLC-Web-2016

Can anyone with a Mac test this out and report back?

I'll find out the OS the user is running too and post that info here when able.

**Comment by jakejackson1** [comment]
Here's the OS details: Mac OS 10.11.5 El Capitan on a MacBook Pro 15 inch, early 2011, 2.2 Ghz processor with 16 Gb RAM.

**Comment by finwe** [comment]
Confirmed, filed as a bug. Feel free to investigate.

**Comment by jakejackson1** [comment]
That's quite a problem! Between this and #171 it does suggest an underlying problem with the security implementation in mPDF. I guess it's time to [review the PDF reference manual again](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf) and compare that to mPDF's implimentation...

**Comment by finwe** [comment]
I have recently refactored the PDF protection for 7.0 to separate classes set, so I hope it will be easier to find a problem and fix it. And backport to 6.x later.

**Comment by jakejackson1** [comment]
I'll do a few test PDFs with mPDF's encryption - using both 40 and 128 bit encryption - tomorrow, then duplicate those, strip the encryption and reapply it with Adobe Acrobat across the test documents.  I'll then supply those here for testing with Finder / Gmail (or you can create and supply them to me if you have the time). 

Hopefully the Acrobat PDF passwords work correctly and we'll have a good baseline comparison between the docs.

**Comment by finwe** [comment]
Ghostscript itself will also process the document without need for a password.

**Comment by jakejackson1** [comment]
[samples.zip](https://github.com/mpdf/mpdf/files/360638/samples.zip)

Attached is a bunch of sample PDFs I generated for testing. I was going to convert them with Adobe Acrobat for testing purposes but the version I have spits out PDF 1.6 instead of 1.4 and uses a higher encryption version. Instead I generated PDFs with TCPDF. It produces PDF 1.7 documents but uses the same encryption we do (plus since parts of mPDF are from TCPDF we can use their codebase as a guide). 

The TCPDFs work fine with Gmail, so they'll likely work in Finder as well. 

The zip file also includes the scripts I used to generate the files if you want to generate them again.

I also tried to replicate the Ghostscript issue you mentioned, but the latest version for Windows (9.19) appeared to work correctly with mPDF.

I'll start diving into the code and see what I can find. P.S just took a look at the codebase in the latest dev branch. You've been busy! Keep up the good work.

**Comment by jakejackson1** [comment]
Further investigation has revealed the cause of the problem: if you have a password on the document but the master password is set to an empty string Finder / Ghostscript will ignore the password and show the document. 

This issue stems from the `setprotection()` [documentation](http://mpdf.github.io/reference/mpdf-functions/setprotection.html) which states that if the owner password is omitted "A random password is generated by mPDF". In this case "omitted" means `null` and not an empty string. I'll update the documentation to reflect this information.

**Comment by finwe** [comment]
Cannot we change the setprotection signature to prevent this kind of confusion by design?

**Comment by jakejackson1** [comment]
I'd like to see setprotection() depreciated in 7.0 in favour of setting each property individually:

```php
$mpdf->setPassword('my password')
          ->setOwnerPassword('owner password')
          ->setPrivilege([ 'print', 'copy' ])
          ->setEncryption(128);
```

That way if one isn't provided (like the owner password) the default is used.
