### ISSUE TITLE
Add custom font from outside the composer package

### ISSUE THREAD

**Issue by adam1658** [mpdf/mpdf#182]
### I would like to add the 'free 3 of 9' font without having to modify the contents of the 'mpdf' directory under 'vendor'

Is it possible to configure mPDF (add fonts, etc.) without modifying the composer package directory? I'd like to add the font, but don't want to have to manually edit composer packages every time I deploy.

### These are mPDF and PHP versions I am using
- mPDF v6.1.1
- php 7.0.6 (it's a zend framework 3 application)

### This is a PHP code snippet I use
```
<?php
	// in config_fonts.php - can it be elsewhere instead, and use a font outside of the directory?
	"code39" => array(
		'R' => 'FRE3OF9X.TTF'
	),

```

**Comment by finwe** [comment]
In 6.1.1 you can define a _MPDF_TTFONTPATH where fonts will be searched for (you will probably need to mirror the vendor fonts directory there).

Since 7.0 it is/will be possible to specify multiple directories (see #146).

**Comment by shark0der** [comment]
I've added an answer with a couple more details on how I achieved it here: http://stackoverflow.com/a/41539351/539153
