### ISSUE TITLE
can't download file with OutputHttpDownload

### ISSUE THREAD

**Issue by WaelMz** [mpdf/mpdf#1820]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Issue: trying to download file with OutputHttpDownload method put nothing happened ... even with debug activated

my code 

            $html = view('pdfs.notes', ['data' => $data, 'headers' => $headers]);
            $mpdf = new \Mpdf\Mpdf();
            $mpdf->WriteHTML($html);
            $mpdf->OutputHttpDownload('notes-report.pdf');

response headers from browser

Request URL: http://127.0.0.1:8000/dashboard/reports/notes
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:8000
Referrer Policy: strict-origin-when-cross-origin

Cache-Control: public, must-revalidate, max-age=0
Connection: close
Content-Description: File Transfer
Content-Disposition: attachment; filename="notes-report.pdf"
Content-Transfer-Encoding: binary
Content-Type: application/pdf
Date: Fri, 10 Feb 2023 07:44:50 GMT
Expires: Sat, 26 Jul 1997 05:00:00 GMT
Host: 127.0.0.1:8000
Last-Modified: Fri, 10 Feb 2023 07:44:50 GMT
Pragma: public
X-Generator: mPDF 8.1.4
X-Powered-By: PHP/7.4.26

### mPDF version

8.1.4

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

7.4.26

### Reproducible PHP+CSS+HTML snippet suffering by the error

            $mpdf = new \Mpdf\Mpdf();
            $mpdf->WriteHTML($html);
            $mpdf->OutputHttpDownload('notes-report.pdf');

**Comment by finwe** [comment]
Unable to reproduce. The headers seem alright, there must be something in your environment preventing the download itself. Have you tried different browsers or a proper web server?
