### ISSUE TITLE
Hyphenation before dash adds another dash

### ISSUE THREAD

**Issue by HKandulla** [mpdf/mpdf#1831]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Hi, I noticed that when breaking words before a dash, another dash is added.
In my fork, I fixed this by changing Mpdf.php::8251:

    if ($type == 'hyphen') {
        $currContent .= '-';
        if (!empty($cOTLdata[(count($cOTLdata) - 1)])) {
          $cOTLdata[(count($cOTLdata) - 1)]['char_data'][] = ['bidi_class' => 9, 'uni' => 45];
          $cOTLdata[(count($cOTLdata) - 1)]['group'] .= 'C';
        }
    }

To:

    if ($type == 'hyphen') {
        if (mb_substr($currContent, -1) !== '-') {
            $currContent .= '-';
        }
        if (!empty($cOTLdata[(count($cOTLdata) - 1)])) {
          $cOTLdata[(count($cOTLdata) - 1)]['char_data'][] = ['bidi_class' => 9, 'uni' => 45];
          $cOTLdata[(count($cOTLdata) - 1)]['group'] .= 'C';
        }
    }

Which fixes this exact case.
Shall I create a PR for this including tests, changelog. Or do you think there is a better place to fix this behaviour?

Best, Hannes

### mPDF version

8.1.0

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 8.1

### Reproducible PHP+CSS+HTML snippet suffering by the error

`<div class="ad">
        <p><strong><span><span data-no-wordbreak="true" class="no-wordbreak">Testevent</span></span></strong></p>31.03. bis 27.03.2023: <strong><span>Testevent</span></strong> gtg<br>https://testevent-testevent.com, Tel. 0173-110110, mail@testevent.com, Grindel-allee 27c<span class="no-hyphens">, Mo</span>
    </div>`

![testevent](https://user-images.githubusercontent.com/489901/222396219-cd86626c-cc15-4323-a69c-ec89896bab68.png)

[testevent.pdf](https://github.com/mpdf/mpdf/files/10870006/testevent.pdf)

**Comment by finwe** [comment]
Unable to reproduce with given code example.

**Comment by finwe** [comment]
I have made it so that the hyphen of the word is shifted to the next line as I believe it should be done. May remove the next hyphen later if I find evidence it should not be done like that.

**Comment by HKandulla** [comment]
@finwe , thanks! Definetely an improvement. Best, Hannes
