### ISSUE TITLE
Ln() function is not working ...

### ISSUE THREAD

**Issue by NicoMachado** [mpdf/mpdf#1832]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I'm using mPdf with the basic commands, WriteCell and WriteText, I'm not using WriteHTML.
I have a code that works on previous versions, and on PHP 5, now I need to migrate to PHP 7, so I'm in PHP7.2. with mPDF version 7.1.19

Sorry if the snippet is not reproducible, I'm using Yii Framework 1.1+
Best Regards

### mPDF version

7.1.19

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

7.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

$mpdf = Yii::app()->ePdf->mpdf(['win-1252', 'A4', '', '', 10, 10, 2, 2, 0, 0]);
//$mpdf->useOnlyCoreFonts = true;    // false is default //php 7.2
$mpdf->SetProtection(array('print'));
$mpdf->SetTitle("CEIA");
$mpdf->SetAuthor("CEIA");
$mpdf->SetDisplayMode('fullpage');
$mpdf->SetFont('Courier','',8);

$margen_izq = 12.0;
$offset=102.0;

$primerLinea = 10;
$letras = new ImporteALetras ;
$salida = 'I'; //inline o F file

$beca_ini_y = 0;

$mpdf->WriteCell(30, 10, 'Celda 1,1');
$mpdf->WriteCell(30, 10, 'Celda 1,2');
$mpdf->WriteCell(30, 10, 'Celda 1,3');

// Agregar un salto de línea para avanzar al siguiente renglón
$mpdf->Ln();

// Escribir la segunda fila de la tabla
$mpdf->WriteCell(30, 10, 'Celda 2,1');
$mpdf->WriteCell(30, 10, 'Celda 2,2');
$mpdf->WriteCell(30, 10, 'Celda 2,3');

// Agregar otro salto de línea para finalizar la tabla
$mpdf->Ln();

$mpdf->Output();

**Comment by NicoMachado** [comment]
Sorry, this is the error:
Undefined offset: 0
(C:\laragon\www\sga_v2\protected\vendor\mpdf\mpdf\src\Mpdf.php:9220)
Stack trace:
#0 C:\laragon\www\sga_v2\protected\views\recibo\printer.php(31):
Mpdf\Mpdf->Ln()
#1 C:\laragon\www\yii-1.1.25\framework\web\CBaseController.php(126):

**Comment by finwe** [comment]
Unable to reproduce with given example and the last version of mPDF.

**Comment by finwe** [comment]
(hint: you can use mPDF 8.1 with PHP 7.2. Constructor parameter changed in 7.0, you will need to pass a associative array of configuration directives. See https://mpdf.github.io/installation-setup/installation-v7-x.html#upgrading-from-older-mpdf-versions)
