### ISSUE TITLE
Latin characters appear in bold in Japanese texts

### ISSUE THREAD

**Issue by SeriousJ55** [mpdf/mpdf#1834]
### Guidelines

- [x] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I use MPDF 8 to generate PDFs in Japanese. The problem is that Latin characters appear in bold.

Here is a [screenshot of the ouput PDF.](https://www.dropbox.com/s/zdet5muu33pznvr/capture.PNG?dl=0)

### mPDF version

8.0

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP Version 8.1.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

**This is the source HTML:**

```
<html><body>
<p style="text-align:justify">&#12486;&#12473;&#12488;&#12486;&#12461;&#12473;&#12488;&#65306;abc</p> 
</body></html>
```

**This is how I configure MPDF:**

```
$mpdf = new \Mpdf\Mpdf([
  'mode' => 's', 
  'format' => 'A4', 
  'default_font_size' => '12', 
  'default_font' => 'SJIS',
]);

$mpdf->autoScriptToLang = true;
$mpdf->autoLangToFont = true;
```

I tried many other configurations, but nothing works.

**Comment by finwe** [comment]
Unable to reproduce, the output of the example code here looks like this

![obrazek](https://user-images.githubusercontent.com/195675/224831655-a6db7ced-300f-4734-9f9e-43f48ce7bbc3.png)
