### ISSUE TITLE
How to embeded Digital Signature ?

### ISSUE THREAD

**Issue by muswanto** [mpdf/mpdf#184]
Hai, I'm new using mPdf, good library and faster than the other. I have a question right now, how to embeded digital signature to pdf file (this's parsing html to pdf using WriteHTML) ?
Thank you..

**Comment by finwe** [comment]
Signing PDF documents is not supported with mPDF. You can always generate the document and sign it with an some external tool.

**Comment by muswanto** [comment]
ok, i'll try another tool to achieve that. Thank you..:)

**Comment by StalkAlex** [comment]
@muswanto it's an old issue I understand, but by any chance haven't you found another tool?

**Comment by finwe** [comment]
@StalkAlex try http://jsignpdf.sourceforge.net/

**Comment by StalkAlex** [comment]
@finwe Thank you! I give it a try.

**Comment by filt3rek** [comment]
Hej,

Idk if I've well understood the question but I don't want mPDF to sign the PDF but just to render a adobe signature field. What is the html tag to get a signayture field or something like that please ?

Thanks for your answer

**Comment by jura120596** [comment]
Please, help. I am trying to sign a pdf generated with mpdf. But the result sign is incorrect. When i try to check the sign for other pdf files - i get the correct sign. How to make a pdf with mpdf library for a checkable digital sign.

**Comment by razvanphp** [comment]
> Idk if I've well understood the question but I don't want mPDF to sign the PDF but just to render a adobe signature field. What is the html tag to get a signayture field or something like that please ?

I have the same "need". After the user signs and sends the document back, I indeed want to apply a digital signature using a cert and private key.

I understand mPDF is dated piece of software, but we are in 2025 and signing PDFs becomes the norm. I still like the easy of use of mPDF and have some legacy CRMs using it.

I could try to implement this with help from AI, theoretically should be possible with crypto functions of modern PHP.

PS: saw this [project](https://github.com/evandro-morini/PHP-PDF-Signature), so I assume it's doable, unless somebody knowing the architecture of mPDF can already tell me this is a dead end.
