### ISSUE TITLE
Compatibility with PHP 8.1

### ISSUE THREAD

**Issue by skills-up** [mpdf/mpdf#1847]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Getting the error below while trying to generate a PDF using mPDF
```
Undefined array key "current" in /home/nginx/domains/example.com/vendor/mpdf/mpdf/src/Tag/BlockTag.php:315
Stack trace:
#0 /home/nginx/domains/example.com/vendor/mpdf/mpdf/src/Tag/BlockTag.php(315): yii\base\ErrorHandler->handleError()
#1 /home/nginx/domains/example.com/vendor/mpdf/mpdf/src/Tag.php(240): Mpdf\Tag\BlockTag->open()
#2 /home/nginx/domains/example.com/vendor/mpdf/mpdf/src/Mpdf.php(13892): Mpdf\Tag->OpenTag()
#3 /home/nginx/domains/example.com/vendor/kartik-v/yii2-mpdf/src/Pdf.php(369): Mpdf\Mpdf->WriteHTML()
#4 /home/nginx/domains/example.com/controllers/TestController.php(744): kartik\mpdf\Pdf->output()
```

I believe it is because the key `current` doesn't exist in `$this->mpdf->page_box`, resulting in an Exception for code `$this->mpdf->page_box['current']` due to stringent requirements of PHP 8.1

### mPDF version

8.1.x

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.1.14

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
$pdf = new \kartik\mpdf\Pdf([
    'mode' => \kartik\mpdf\Pdf::MODE_CORE,
    'format' => \kartik\mpdf\Pdf::FORMAT_A4,
    'orientation' => \kartik\mpdf\Pdf::ORIENT_PORTRAIT,
    'destination' => \kartik\mpdf\Pdf::DEST_FILE,
    'filename' => $path,
    'content' => $content,
]);

$pdf->output($content, $path, 'F');
```

**Comment by skills-up** [comment]
I've fixed the issue on my installation, and [raised a PR ](https://github.com/mpdf/mpdf/pull/1848) for the same. Kindly pull and merge.

**Comment by finwe** [comment]
Closed by https://github.com/mpdf/mpdf/commit/865bca6d212486a7541270d27fc3f648805b12f4
