### ISSUE TITLE
word-spacing in absolutly positioned element not working

### ISSUE THREAD

**Issue by Muenchen-Michi** [mpdf/mpdf#185]
When an element is positioned absolutely, then the word-spacing doesn't work.
Here's a html-snippet:

```
<div style="position:absolute; letter-spacing:2.5mm; word-spacing:40mm;">This is my text</div>
```

When I remove `position:absolute` the word-spacing works as expected.

My mPDF-version is 6.1

Michael

**Comment by finwe** [comment]
Styling is limited in absolutely positioned elements. This is a documented behaviour which will probably not change.
