### ISSUE TITLE
Mpdf 8.1.4 returns only one-line links

### ISSUE THREAD

**Issue by michalpruszynski** [mpdf/mpdf#1851]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Mpdf in version 8.1.4 can return links only when them is in one line, if i try to `overflow: wrap` the table and split link into multiple lines it returns only first one as a 'href'.

Is it a bug? Or maybe i couldn't found anything in docs. I can't write `<a href=" long link...">Short link</a>` - it returns an error.

`<a name="...">...</a>` works but it does not return a clickable link.

### mPDF version

8.1.4

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

Docker php:8.1-apache

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
$mpdf->WriteHTML("<a href='https://www.google.pl/'> Google </a>");  

$mpdf->output();
```

**Comment by finwe** [comment]
Unable to reproduce with given code snippet, it works as expected. Provide a concrete copy-pastable example code and also mention specific errors you are getting.

**Comment by finwe** [comment]
Also please note that 
* styling and handling nested elements inside of tables is limited.
* `overflow: wrap` is a nonstandard css definition in mPDF that is intended for `table` element only and may not work as you expect.

**Comment by michalpruszynski** [comment]
@finwe
not it does not work as expected - `$mpdf->WriteHTML("<a href='https://www.google.pl/'> Google </a>");` causing "Warning: Undefined array key 1"

If i put link without `a href` it works, but as i mention in topic - only in single line. If it breaks into 2 or more lines - https://imgur.com/JC9TKnn

**Comment by finwe** [comment]
No, simple `$mpdf->WriteHTML("<a href='https://www.google.pl/'> Google </a>");` does not cause me any errors. Provide a complete code example to reproduce the behavior you mention.

**Comment by finwe** [comment]
Bootstrap is not supported in mPDF, especially not the latest one as it contains CSS definitions mPDF cannot handle.

**Comment by finwe** [comment]
See also https://github.com/mpdf/mpdf/issues/1053 and other css variables-related issues.

**Comment by finwe** [comment]
The CSS variables related errors could be resolved (by ignoring) with https://github.com/mpdf/mpdf/commit/ef90b4c104bb6b9c9f66884fa2afe8d62a18f429 in the last 8.1.5 release, can you test it?

**Comment by michalpruszynski** [comment]
Yes, i've tested it - it works well. Does not return any error and links works as expected. Good job :+1:
