### ISSUE TITLE
Upgrade support for PSR/LOG 3.0.0

### ISSUE THREAD

**Issue by valentinasbitcat** [mpdf/mpdf#1852]
### Please describe the new functionality as best as you can.

Psr/Log 3.0.0 is newest version, but mpdf/mpdf requires psr/log 1.0.0 or 2.0.0 and 3.0.0 is not supported.

Is there any time soon that this will be implemented?

![image](https://user-images.githubusercontent.com/129482368/229997516-7e5e2d01-95cf-48ba-9777-8b2b97b29e62.png)

**Comment by finwe** [comment]
No. #1622

**Comment by finwe** [comment]
Hint: you can also downgrade on your part to 2.0, unless some of your packages require 3.0 only.

**Comment by finwe** [comment]
psr/log 3.0 is supported as of just released v8.1.6
