### ISSUE TITLE
hello in thaifont i can remove this?

### ISSUE THREAD

**Issue by silasakk** [mpdf/mpdf#186]
### I have this problem/would like to have this functionality

font garuda it ok but thaisan not work

![document](https://cloud.githubusercontent.com/assets/1897050/16861017/219df340-4a67-11e6-9145-3857b52d6e50.png)
### These are mPDF and PHP versions I am using

6.1
### This is a PHP code snippet I use

```
<?php

"garuda" => array(/* Thai */
        'R' => "Garuda.ttf",
        'B' => "Garuda-Bold.ttf",
        'I' => "Garuda-Oblique.ttf",
        'BI' => "Garuda-BoldOblique.ttf",
        'useOTL' => 0xFF,
    ),
    "thaisan" => array(
        'R' => "ThaiSansNeue-Regular.ttf",
        'B' => "ThaiSansNeue-Bold.ttf",
        'useOTL' => 0x0FF,
    ),

```
### This is a HTML code snippet I use

```

```

**Comment by deshario** [comment]
@silasakk does it still support in latest library ...
ใน lib ล่าสุด ยัง support ภาษาไทยยุปะครับ ... ข้อดูตัวอย่างหาร set font thai หน่อยได้มัยครับ ขอบคุณครับ

**Comment by finwe** [comment]
Closing as stale and missing code example.
