### ISSUE TITLE
Last version of library requires psr/log 1.0 or 2.0 but my laravel project psr/log version is 3.0. I am not able to install library because of this issue.

### ISSUE THREAD

**Issue by arslonbeksaidov** [mpdf/mpdf#1862]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Last version of library requires psr/log 1.0 or 2.0 but my laravel project psr/log version is 3.0. I am not able to install library because of this issue.

### mPDF version

8.1.5

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.1.11

### Reproducible PHP+CSS+HTML snippet suffering by the error

![image](https://user-images.githubusercontent.com/25222390/234867542-922cecae-d991-4169-8a1e-486b0ba0bf15.png)

**Comment by finwe** [comment]
#1622

**Comment by finwe** [comment]
psr/log 3.0 is supported as of just released v8.1.6
