### ISSUE TITLE
Variable to change color of watermark text

### ISSUE THREAD

**Issue by Ian-Robinson1** [mpdf/mpdf#1866]
### Please describe the new functionality as best as you can.

The watermark text color cannot be changed with a variable when a pdf is created. Currently, the only way to change it is to directly edit src/Mpdf.php line 10598, such as:

$this->SetTColor($this->colorConverter->convert(0, $this->PDFAXwarnings));

To:

$this->SetTColor($this->colorConverter->convert('red', $this->PDFAXwarnings));

Being able to change the color with a variable would be very helpful

**Comment by v1har** [comment]
### 1. Need to define the variable:
_var $watermark_color;_


### 2. Set default in _construct:
_$this->watermark_color = 0;_


### 3. Create setter function
_function setWatermarkColor($watermark_color = 0){
$this->watermark_color = $watermark_color;
}_


### 4. Use variable in line 10484
_$this->SetTColor($this->colorConverter->convert($this->watermark_color, $this->PDFAXwarnings));_

**Comment by v1har** [comment]
I am not a pro user of github so I thought it's easier to tell you the idea so you can implement / add pull request. I just tried to help because I need this functionality too. :)
