### ISSUE TITLE
Please release a new version for php 8.2

### ISSUE THREAD

**Issue by realtebo** [mpdf/mpdf#1870]
### Please describe the new functionality as best as you can.

I see master is compatible with php8.2

But lat release is only 8.1.0  (https://github.com/mpdf/mpdf/releases ) and it's only 8.1 compatible.

**Comment by finwe** [comment]
No, the last release is 8.1.6 https://packagist.org/packages/mpdf/mpdf

**Comment by realtebo** [comment]
.. please release also here on github, long story ...

**Comment by finwe** [comment]
That a tag is not listed here in releases does not mean it is not a released version.
