### ISSUE TITLE
Fatal error: Array and string offset access syntax with curly braces is no longer supported in

### ISSUE THREAD

**Issue by NathanApps** [mpdf/mpdf#1877]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I am trying to use this libary file using the example code shown on the example page.

I am currently using mpdf-8.1.0 with php 8.2 and all i get is the error message 
Fatal error: Array and string offset access syntax with curly braces is no longer supported in /home/domains/vol4/142/2506142/user/htdocs/back-end/Backend-API/vendor/mpdf/mpdf/src/Mpdf.php on line 2213 any ideas whats causing this?

### mPDF version

8.1.0

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.2

### Reproducible PHP+CSS+HTML snippet suffering by the error
   $mpdf = new \Mpdf\Mpdf();
   $mpdf->WriteHTML('<h1>Test</h1>}');
   $mpdf->Output();

**Comment by finwe** [comment]
How did you install mPDF 8.1.0 with PHP 8.2?

> PHP 8.2 is supported as of mPDF v8.1.3

install at least mPDF 8.1.3
