### ISSUE TITLE
Version 6.1: Undefined indexes reporting

### ISSUE THREAD

**Issue by nikto1** [mpdf/mpdf#188]
Full report:

```
Undefined index: y0  on line 2959
Undefined index: y0  on line 2962 
Undefined index: width  on line 19373
Undefined index: width on line 19497 x0 on line 3014
```

I use an external stylesheet + an html template with placeholders which are replaced dynamically by php - if there is such an information. E.g. if $_POST['tax'] => show this div.

Html layout is very simple and on the div where it gives an error there's no float, no nothing.
Just replacing an invisible class 
**< div class="no-display" >< /div >** // additional spaces just to paste it here on github
 with 
**< div class="tax" >6%< /div >** // additional spaces just to paste it here on github

If i turn  the error reporting off all is rendered fine without problems, but that's just a quick hack.
Any  solutions?

**Comment by finwe** [comment]
The library is full of such unsanitized places, we try to fix them one at a time. The only viable suggestion for now would be to keep the error reporting disabled for the time the PDF is generated.

Thanks for the notice, will fix these for future versions.

**Comment by kristi5** [comment]
+1 vote for sanitize the code for this undefined index reports.
