### ISSUE TITLE
Unable to write द्वितीय in PDF

### ISSUE THREAD

**Issue by ccpplinux** [mpdf/mpdf#1883]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I am unable to write the hindi word द्वितीय in the PDF file generated by mpdf. When I am trying to display द्वितीय then it is being displayed as दिवतीय in the PDF file. So can any one help me to fix this issue so that I can correctly display the hindi word द्वितीय in the PDF file.

### mPDF version

8.1.0

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

7.4

### Reproducible PHP+CSS+HTML snippet suffering by the error

`<?php
require_once __DIR__ . '/mpdf/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->autoScriptToLang = true;
$mpdf->baseScript = 1;
$mpdf->autoVietnamese = true;
$mpdf->autoArabic = true;
$mpdf->autoLangToFont = true;

$html=
"
<html>
    <head>
        <style>
            body { font-family: sans; text-align: justify; }
            p { font-family: sans; }
            div { font-family: sans; }
            h1 { font-family: sans; }
            td { font-family: sans; }
        </style>
    </head>
    <body>
        Result is द्वितीय
    </body>
</html>
";
$mpdf->WriteHTML($html);
$mpdf->Output();
?>
`

**Comment by finwe** [comment]
Reopened #1881
