### ISSUE TITLE
DejaVuSansCondensed font file is corrupted and cannot be read with the last Adobe Reader

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#189]
## Issue

https://stackoverflow.com/questions/38392837/adobe-reader-cant-retrieve-embedded-font-from-pdf-generated-with-mpdf

## Fix

https://forums.adobe.com/message/8879248

**Comment by KacerCZ** [comment]
Tested, was working fine.
Thanks for quick fix.
