### ISSUE TITLE
unserialize error in PHP 8.3

### ISSUE THREAD

**Issue by brainfoolong** [mpdf/mpdf#1895]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I'm testing php 8.3 and one of our unit tests contains MPDF, and it fails.
It fails because starting with PHP 8.3, unserialize will throw an error if additional data after the end of the serialized string comes.

Error in MPDF is:

Test "Issue339Test" aready shows the same issue.
https://github.com/mpdf/mpdf/blob/development/tests/Issues/Issue339Test.php#LL10C27-L10C27

```
unserialize(): Extra data starting at offset 292 of 295 bytes
 D:\mpdf\src\Mpdf.php:9103
 D:\mpdf\src\Mpdf.php:16239
 D:\mpdf\src\Tag\BlockTag.php:1124
 D:\mpdf\src\Tag.php:247
 D:\mpdf\src\Mpdf.php:13810
 D:\mpdf\tests\Issues\Issue339Test.php:27
```
This string it internally has contains 2 of those 3 characters explode sequence, one at the start and one at the end.

Changing this line
https://github.com/mpdf/mpdf/blob/0c554d55e3659abdb00d3a5759bafc5c84199c62/src/Mpdf.php#L9097
to this
`$c = explode("\xbb\xa4\xac", $t, 3);`
would fix it.

This fix just increase the explode limit to 3, so it never comes to the point where maybe 2 separators exist in the given string.

I don't have time to properly write test cases for this, as it happens in a complicated pdf here which i can't easily reproduce.

### mPDF version

current

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

windows 10 php 8.3alpha1

### Reproducible PHP+CSS+HTML snippet suffering by the error

Sorry. Dont have it yet.

**Comment by finwe** [comment]
Can reopen with the example code.

**Comment by brainfoolong** [comment]
Found a testcase. Test "Issue339Test" aready shows the same issue.

```
unserialize(): Extra data starting at offset 292 of 295 bytes
 D:\mpdf\src\Mpdf.php:9103
 D:\mpdf\src\Mpdf.php:16239
 D:\mpdf\src\Tag\BlockTag.php:1124
 D:\mpdf\src\Tag.php:247
 D:\mpdf\src\Mpdf.php:13810
 D:\mpdf\tests\Issues\Issue339Test.php:27
```

**Comment by finwe** [comment]
Can confirm, will try to research what is the cause.

**Comment by brainfoolong** [comment]
I "guess" it was always like that, but serialization errors have been updated in PHP 8.3. https://php.watch/versions/8.3/unserialize-E-WARNING

**Comment by finwe** [comment]
I have fixed this by trimming the object identifier from the end of the value as it it seemed less likely to create unexpected states as `$c = explode("\xbb\xa4\xac", $t, 3);` would.

**Comment by brainfoolong** [comment]
Awesome, thx @finwe  for the ongoing work in this project.

**Comment by gbrits** [comment]
I'm confused, I'm on v8.2.2 on PHP 8.2 and I'm getting this error?

**Comment by gbrits** [comment]
Sorry @finwe, I forgot I commented, turned out I was on Laravel Nova and I created a tool which has its own composer, so I had to update the Mpdf there, rather than in the parent project. My bad.

**Comment by sarangtc** [comment]
this fix `$k = explode("\xbb\xa4\xac", $t, 3);` works and is backward compatible, I tested all the way back to php7.4. I have no idea why it makes no breaking difference in older versions, but it works.

**Comment by anjanesh** [comment]
Same issue : 
```
[16-Oct-2024 11:15:20 America/New_York] PHP Warning:  unserialize(): Extra data starting at offset 420 of 423 bytes in /home/username/public_html/vendor/mpdf/mpdf/src/Mpdf.php on line 8953
```

PHP 8.3.12
```
cat composer.json
{
    "require": {
        "mpdf/mpdf": "^8.0",
        "phpseclib/mcrypt_compat": "^1.0",
        "mobiledetect/mobiledetectlib": "^2.8",
        "geoip2/geoip2": "^2.10",
        "swiftmailer/swiftmailer": "^6.0",
        "ianw/quickchart": "^1.2"
    }
}
```

**Comment by finwe** [comment]
@anjanesh then report to a new issue with all required details.

**Comment by anjanesh** [comment]
Will the problem be solved if I've update composer.json file with "mpdf/mpdf": "^8.2.4",
And run `composer update mpdf/mpdf` ?

**Comment by finwe** [comment]
I don't know. I don't have your code. Why not just try it?

**Comment by anjanesh** [comment]
It looks like everything worked now with mpdf 8.2.4 and PHP 8.3. Thanks.
