### ISSUE TITLE
Need extra curl settings in `CurlHttpClient`

### ISSUE THREAD

**Issue by greew** [mpdf/mpdf#1897]
### Please describe the new functionality as best as you can.

I need to be able to set a value in the `CURLOPT_NOPROXY` curl option, and I would like to contribute with the setting, but I need to know how you would me to add it to the code (if you want it at all, of course :)).

Option 1:
Just add a `private ?string \Mpdf\Mpdf::curlNoProxy = null;` just like the other curl options in `Mpdf` and the `CurlHttpClient`

Option 2: 
Add `private ?array \Mpdf\Mpdf::curlExtraOptions = null;` such that it's possible to add any other curl option to the client.

Option 3: 
Create an extra method in `\Mpdf\Http\CurlHttpClient` that takes the `$ch` variable and is just an empty method, but can then be overridden via a new `httpClient` in the ServiceFactory container.

**Comment by finwe** [comment]
Precisely for this use case you can implement your own httpclient and pass it to the mpdf service container. See https://github.com/mpdf/mpdf/releases/tag/v8.1.0

**Comment by finwe** [comment]
Options 1 and 2 go directly against the reasoning for the container which is adding more and more configuration options to mPDF.

I don't exactly understand the explanation of 3 - there has not to be any relation between the `\Mpdf\Http\CurlHttpClient` and the "overriding" class, they are both only an implementation of the interface.

**Comment by greew** [comment]
> Precisely for this use case you can implement your own httpclient and pass it to the mpdf service container. See https://github.com/mpdf/mpdf/releases/tag/v8.1.0

Yeah, I know :smile: I just wanted to avoid having to copy the entire `\Mpdf\Http\CurlHttpClient` class and just add one single line. 

But I guess, I can do that :wink:
