### ISSUE TITLE
Heading blocks show behind floated divs

### ISSUE THREAD

**Issue by jonnybradley** [mpdf/mpdf#190]
### I have this problem

Where a heading block such as H2 or H3 has a background or border and is constrained on a page by a floated (right) DIV, in the browser it appears as expected but in the PDF the H2 block extends under the floated DIV - and if the background of the DIV is set (to white) then the background-color of the H2 is successfully hidden, but the border still shows (see example page below).

Have tried many other CSS fixes but cannot seem to work round this one.
### These are mPDF and PHP versions I am using

mPDF 6.1 and PHP 5.5.9 (although it has been seen on other versions of PHP)
### This is a HTML code snippet I use

Example page can be found here https://promusa15.alsawiki.com/mPDF+Heading+bug+test and the link to the generated PDF is https://promusa15.alsawiki.com/tiki-print.php?page=mPDF+Heading+bug+test&display=pdf (or click on the PDF icon top left)

_Thanks in advance..._

**Comment by finwe** [comment]
Closing as the example document no longer exists. Feel free to reopen with HTML/PHP example, preferrably uploaded or pasted here directly.
