### ISSUE TITLE
Inline Output Different Behavior Windows vs Linux

### ISSUE THREAD

**Issue by ddevsr** [mpdf/mpdf#1904]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I have tested on Local Windows and Dev Server Ubuntu

Windows :
![image](https://github.com/mpdf/mpdf/assets/97607754/9d599c07-1b8f-43c2-9c8c-449206d134df)

Linux (Ubuntu) :
![image](https://github.com/mpdf/mpdf/assets/97607754/ae60400d-6cba-4e75-af6c-e75b5ff2d4b4)

In above image, i am using Chrome version `114.0.5735.199` and my firefox is OK.

I have tested too with 3 another device using chrome and firefox, with result expected `Dokumen_Sertifikat_GADAI0000207.pdf` :
1. Chrome : NOT OK, Firefox: OK (Latest version browser)
2. Chrome : NOT OK, Firefox: NOT OK (Latest version browser)
3. Chrome : NOT OK, Firefox: NOT OK (Latest version browser)

### mPDF version

8.1.6

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.2.8

### Reproducible PHP+CSS+HTML snippet suffering by the error

```php
// Location Folder CSS
$dirLocationStyle  = WRITEPATH . 'uploads/';
$titleDocument     = 'Dokumen Sertifikat - ' . $declareId;
$titleFileDocument = 'Dokumen_Sertifikat_' . str_replace('.', '', $declareId);

$data = [
    'meta_tag'   => $this->meta_tag,
    'dataDetail' => $sertifikatData['r_data'],
];

$headerHTML = view('templates/document/header', $data);
$bodyHTML   = view('templates/document/index', $data);
$footerHTML = view('templates/document/footer');

$mpdf = new Mpdf([
    'mode'          => 'utf-8',
    'format'        => 'A5',
    'orientation'   => 'L',
    'margin_left'   => 15,
    'margin_right'  => 15,
    'margin_top'    => 10,
    'margin_bottom' => 10,
    'margin_header' => 2,
    'margin_footer' => 2,
]);

$mpdf->SetTitle($titleDocument);

$mpdf->WriteHTML(file_get_contents($dirLocationStyle . 'Template/sertifikat.css'), HTMLParserMode::HEADER_CSS);
$mpdf->SetHTMLHeader($headerHTML);
$mpdf->SetHTMLFooter($footerHTML);
$mpdf->WriteHTML($bodyHTML, HTMLParserMode::HTML_BODY);

// Set Header to PDF
$this->response->setHeader('Content-Type', 'application/pdf');

// Output
return $mpdf->Output($titleFileDocument . '.pdf', Destination::INLINE);
```

**Comment by ddevsr** [comment]
@finwe What missing sample? html view?

**Comment by finwe** [comment]
Is your code example reproducible? No, it isn't.
