### ISSUE TITLE
Problem with HTTP reponse code 2XX

### ISSUE THREAD

**Issue by macuevas** [mpdf/mpdf#1926]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

When I add an image for a remote server which reponses 201 I get an error. Every response from 2XX is a successful response, the library shouldn't raise an exception with 201 responses or any response different than 200.

I change the following lines to fix the error.

**File:  /src/AssetFetcher.php**

Original Line ():
`if ($response->getStatusCode() !== 200) {`

Change line :
`if (((int)($response->getStatusCode() / 100)) !== 2) {`

**File:  /src/HTTP/CurlHttpClient.php**

Original Line (88):
`if (isset($info['http_code']) && $info['http_code'] !== 200) {`

Change line:
`if (isset($info['http_code']) && (((int)($info['http_code'] / 100)) != 2)) {`

Can some one change these line for getting resource where the server return 2XX and not only 200.

### mPDF version

v8.1.4

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 8

### Reproducible PHP+CSS+HTML snippet suffering by the error

see description of the bug

**Comment by finwe** [comment]
Not entirely true that every 2XX response is applicable, upwards from 201 there is no expectation of (complete) content.

Anyway the code is now accepting all 2XX responses (in a somewhat cleaner manner).
