### ISSUE TITLE
useSubstitutions have problem when there is page-break-inside: avoid

### ISSUE THREAD

**Issue by omasfok** [mpdf/mpdf#193]
hi all, 

I face this problem in both v6.0 and v6.1.
v6.0 => php 5.1.6
v6.1 => php 5.4
### My problem is

I  found the output is not correct when using "page-break-inside: avoid" together with useSubstitutions.

I am using TimesNewRoman for all content in my document.
For any Chinese Character, I will use mingliu.ttc (common Chinese font).

if input is '中文Chinese' , output will become 中文中文Chinese
But the first 中文 will become a rectangle (as same as direct output Chinese with English font).
### Here is my Code

```
<?php
require_once("mpdf/mpdf.php");

$pdf = new mPDF();
$pdf->backupSubsFont = array('mingliu');
$pdf->useSubstitutions = true;

$css = '<style>body { font-family : "timesnewroman"; font-size:10px;}</style>';
$html .= "<div style='page-break-inside: avoid;'>
        <table border='1'>
            <tr>
                <td>中文Chinese</td>
                <td>Enlgish英文</td>
            </tr>
        </table></div>";
$pdf->WriteHTML($css);
$pdf->WriteHTML($html);
$pdf->Output('aa.pdf', 'I');
?>
```

Is it a bug or a usage problem ?
thanks a lot~

**Comment by finwe** [comment]
Closing as stale.

If still applicable, feel free to create a new discussion/issue for the last mPDF version according to current contribution guidelines.
