### ISSUE TITLE
Can't connect to hosts with non-standard port

### ISSUE THREAD

**Issue by developeregrem** [mpdf/mpdf#1931]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

After upgrading from mpdf 8.1.6 to 8.2.0 my images that are fetched from an internal non-standard port are not fetched any more and not visible in rendered PDFs.

It seems to be a problem in the return type of `filterPort` in https://github.com/mpdf/psr-http-message-shim/blob/1cf4c0b68b8461cea27411ff961482ce7687e34f/src/Uri.php#L268 which comes with psr-http-message-shim 2.0.0

It will end up in the type [bool for the port](https://github.com/mpdf/psr-http-message-shim/blob/1cf4c0b68b8461cea27411ff961482ce7687e34f/src/Uri.php#L52) and not the actual port anymore. Therefore, the following curl error is shown:

`cURL error: "Failed to connect to web port 1 after 2 ms: Couldn't connect to server"`

### mPDF version

8.2.0

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 8.2

### Reproducible PHP+CSS+HTML snippet suffering by the error
```
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf(['debug' => true]);

$mpdf->WriteHTML('<p><img src="http://web:8080/image.jpg" alt="" width="120" height="150"></p>');
$mpdf->Output();
```

**Comment by finwe** [comment]
True. Should be fixed in psr-http-message-shim:2.0.1, update.
