### ISSUE TITLE
Combination of a space apended to a <br /> tag and both enclosed with <strong> tag generates error.

### ISSUE THREAD

**Issue by ashishrao390** [mpdf/mpdf#1935]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

We are using mPDF[8.0.0] in Yii2[2.0.45] php framework and PHP[8.0]

Combination of a space apended to a br tag and both enclosed with `<strong>` tag generates error. We tried few permutations combinations and only this pattern generates error.

I couldn't find any solution in different forums, can you please explain this senario.

### mPDF version

8.0.0

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

Yii2[2.0.45] php framework and PHP[8.0]

### Reproducible PHP+CSS+HTML snippet suffering by the error

    <strong> <br /></strong>

**Comment by finwe** [comment]
What error?

**Comment by finwe** [comment]
Unable to reproduce.
