### ISSUE TITLE
Limit the PDF to three pages

### ISSUE THREAD

**Issue by riyash** [mpdf/mpdf#1938]
### Please describe the new functionality as best as you can.

Hello,
I am using dynamic content to display in pdf. Everything is working fine but I just want to display 3 pages of PDF regardless of content. It is not necessary to fit the full content in 3 pages. Just need to display 3 pages in pdf and other content can be deleted or hidden.

```
$pdf = new \Mpdf\Mpdf();
$stylesheet = file_get_contents(get_stylesheet_directory_uri().'/style.css'); // external css

$pdf->SetHTMLHeader('<div class="pdf-header" style="margin-bottom:10px;background-color:#0095DB;text-align:center;"><img src="'.$image[0].'" style="width:18%;padding-top:10px;padding-bottom:20px;"></div>');
$pdf->AddPage('', // L - landscape, P - portrait 
        '', '', '', '',
        2, // margin_left
        2, // margin right
       30, // margin top
       10, // margin bottom
        2, // margin header
        2); // margin footer

$pdf->WriteHTML($stylesheet,1);
$pdf->WriteHTML($html,2); 

$pdf->TOC_Entry("content",0);

ob_end_clean();
$pdf->Output();
```

This is the code I am using right now. Please respond as soon as possible

**Comment by riyash** [comment]
@finwe 
How can you close this? without answering?

**Comment by finwe** [comment]
This is general troubleshooting and you already asked in Discussions where the question is still open.

**Comment by riyash** [comment]
@finwe 
But no one is responding there. so  I posted here.
