### ISSUE TITLE
Unable to find xref table

### ISSUE THREAD

**Issue by nicdnepr** [mpdf/mpdf#194]
### I have this problem

I try to merge pdf files and get such error `Unable to find xref table`. Problem pdf begins with line `%PDF-1.4`. Other pdf begins with line `%PDF-1.5^M` and merge correct
### These are mPDF and PHP versions I am using

mPDF last version from composer, php 5.5
### This is a PHP code snippet I use

```
<?php
$pdf = new \mPDF();
$pagesInFile = $pdf->SetSourceFile($file);

```

**Comment by jakejackson1** [comment]
Are you sure it's not the other way around? That PDFs with PDF-1.5 are the problem, and PDF-1.4 work correctly? 

Mpdf uses the free version of FPDI to import PDFs and this version can only import PDFs that are v1.3 or 1.4. Anything above this won't work unless you [purchase and use their premium version](https://www.setasign.com/products/fpdi-pdf-parser/details/#p-228).

**Comment by nicdnepr** [comment]
here is screens of pdf content, I checked pdf one more time
correct merge
![2016-07-21-071818_1651x889_scrot](https://cloud.githubusercontent.com/assets/2581487/17011152/572abccc-4f13-11e6-8b98-f5cafc0f7240.png)

error merge
![2016-07-21-071901_1651x889_scrot](https://cloud.githubusercontent.com/assets/2581487/17011164/6c78cd80-4f13-11e6-95b6-c146fef45e58.png)

**Comment by jakejackson1** [comment]
Can you upload the problem PDF here so I can take a closer look?

**Comment by nicdnepr** [comment]
check it https://drive.google.com/file/d/0B3UfldSD39xGVk1TZ2xOTEdoNDA/view?usp=sharing

**Comment by jakejackson1** [comment]
Thanks. My tools show that PDF contents is in hex (might be a Google Drive thing) so I couldn't check for the correct version / xref table. 

In any case, re-convert the PDF to 1.4 or 1.3 and mPDF will start working again.

**Comment by nicdnepr** [comment]
check it
[адресная справка.pdf](https://github.com/mpdf/mpdf/files/375156/default.pdf)

**Comment by jakejackson1** [comment]
Thanks. I could correctly open that one. 

The document looks 1.4 compliant. [I'd open a ticket upstream](https://github.com/Setasign/FPDI) with the FPDI package as that's where the error is coming from.

**Comment by nicdnepr** [comment]
thanks, can you give some info-as I understand FPDI merge only pdf 1.3 and 1.4? it's old versions of pdf? and pdf 1.5 and later not merge because it's new versions of pdf? and no solutions only buy paid FPDI?

**Comment by jakejackson1** [comment]
That's correct. The company that released FPDI offers a free version for older PDFs and a paid version for newer PDFs. As far as I'm aware they have cornered the market for this particular functionality.

**Comment by nicdnepr** [comment]
and there is no another solution\library for merging pdf except for FPDI?

**Comment by nicdnepr** [comment]
may be any solution to repair  corrupt pdf? for example here is site https://www.pdf-online.com/osa/repair.aspx and it restore xref in pdf
