### ISSUE TITLE
Centering content

### ISSUE THREAD

**Issue by nidhinprathap** [mpdf/mpdf#1948]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I'm trying to convert the html in [JSFIDDLE](https://jsfiddle.net/sxb0gkmf/) to pdf using mpdf. 
The cintent has to be centered horizontally and vertically. but when generating pdf it doesnt happen. see the the output attached.

Actual Output
<img width="593" alt="Screenshot 2023-11-02 at 1 17 22 PM" src="https://github.com/mpdf/mpdf/assets/21108668/70299999-8ce9-4aa8-8ea5-375aacb9146d">

The whole content also is not getting aligned vertically centered
Where ami i going wrong here. it looks fine in browser

### mPDF version

^8.2

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8

### Reproducible PHP+CSS+HTML snippet suffering by the error

HTML
[JSFIDDLE](https://jsfiddle.net/sxb0gkmf/)

PHP 
`
 $this->mpdf = new Mpdf([
            'mode' => 'utf-8',
            'format' => 'A4',
            'orientation' => 'P'
        ]);
$this->mpdf->WriteHTML($html);
$pdfContent = $this->mpdf->Output('', 'S'); // Get PDF content as a string
file_put_contents($filename, $pdfContent);
`

**Comment by nidhinprathap** [comment]
Why was this closed?  I still haven't found resolution or nothin was answered

**Comment by finwe** [comment]
@nidhinprathap this is general troubleshooting and therefore does not belong in issues.

**Comment by nidhinprathap** [comment]
> @nidhinprathap this is general troubleshooting and therefore does not belong in issues.

I tried putting there but didnt get any support.
