### ISSUE TITLE
Watermark Font Size

### ISSUE THREAD

**Issue by rikgirbes** [mpdf/mpdf#1951]
### Please describe the new functionality as best as you can.

The font size for a Water Mark is statically set to 120.

(Lines 13233-13235 in Mpdf.php)
```php
if (($this->watermarkText) && ($this->showWatermarkText)) {
     $this->watermark($this->watermarkText, $this->watermarkAngle, 120, $this->watermarkTextAlpha); // Watermark text
}
```

Adding a Watermark through the WatermarkText object, should also be able to change the font size imo.

So quite an easy fix I'd say, add a parameter to the WatermarkText object (fontSize), set it default to 120, then it is changeable.

**Comment by finwe** [comment]
WatermarkText object already has a size parameter, this was just overlooked.

**Comment by rikgirbes** [comment]
Size parameter however is not working, at least not for the Text-Watermark.
The only thing that can make it smaller or bigger would be the font size. Which is fixed to 120.

**Comment by finwe** [comment]
No, since commit https://github.com/mpdf/mpdf/commit/d748f1e90eb98a3f61d8a5ae8035ba1972ef268c it is not.

**Comment by rikgirbes** [comment]
Ah, awesome 😊 thanks!

Side question: when is a new release planned?

**Comment by finwe** [comment]
When I feel that it is justified.
