### ISSUE TITLE
UTF-8 error when I use ctimes

### ISSUE THREAD

**Issue by Goang14** [mpdf/mpdf#1975]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

help me fix utf8 error when using ctimes
![image](https://github.com/mpdf/mpdf/assets/107413554/9bb9d5dd-f486-41c7-86f3-5ee56e41bbc7)

### mPDF version

8.2

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

7.4.33

### Reproducible PHP+CSS+HTML snippet suffering by the error

k

**Comment by ssieb** [comment]
You already created a discussion and I gave you an answer.  I'm pretty sure this isn't an mpdf issue.
You didn't even provide the information asked for when creating an issue.
