### ISSUE TITLE
Hyphenation of words with hyphens not as expected

### ISSUE THREAD

**Issue by eiswurm** [mpdf/mpdf#1988]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

The hyphenation of words which are connected with a hyphen does not work as expected. 

Original:
Schupfnudel-Gemüse-Pfanne 

PDF:
Schupfnudel-Gemüse-P-
fanne 

maybe this is related to #1831

### mPDF version

8.2

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

language is set via $pdf->SHYlang = 'de';

**Comment by finwe** [comment]
The code example is not exactly reproducible by copy-paste, is it? Can you update it?

**Comment by eiswurm** [comment]
Sorry for that. We use mPDF as part of a cms bundle [https://github.com/do-while/contao-mpdf-template-bundle](url). So the code is somehow different.

**Comment by finwe** [comment]
OK, closing, can reopen when a reproducible code example is added.
