### ISSUE TITLE
Add security reporting feature to the repo

### ISSUE THREAD

**Issue by anargam** [mpdf/mpdf#1990]
After [issue 1625](https://github.com/mpdf/mpdf/issues/1624) you created a security policy that tells reporters to leave a note and a way to get in contact (so you don't have your details revealed). I think GitHub introduced their reporting feature some time after that. It might make it easier to keep track of bugs, allow for collaboration on mitigations, share reports between developers, etc.

I believe this might be the relevant help page: [Configuring private vulnerability reporting for a repository](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)

**Comment by finwe** [comment]
great suggestion, thanks! enabled now.
