### ISSUE TITLE
There are some bugs related to border-collapse and padding and border with tables

### ISSUE THREAD

**Issue by unluckychild** [mpdf/mpdf#1992]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

There are some bugs related to these 3, and/or around table. I tried to add css directly to table via style=""... but result is bugged

### mPDF version

8.1.3

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
 $style='
<style>
    table{
		border-collapse:collapse
	}
    td {
		border:1px solid;
		padding:10px;
    }

</style> 
';
 $template='
<body>
		<table style="">
			<tr>
				<td>123</td>
				<td>123</td>
				<td>123</td>
			</tr>
		</table>
 </body> ';

 $mpdf = new Mpdf\Mpdf();
 $mpdf->use_kwt = true; 
 $mpdf->WriteHTML($style, 1);
 $mpdf->WriteHTML($template, 2);
 $mpdf->Output(); 
```

**Comment by finwe** [comment]
What does "bugged" mean exactly? Please elaborate.

Also note that the correct css border definition is `<br-width> || <br-style> || <color>` as mentioned in [this SO answer](https://stackoverflow.com/a/49554085/819007)

**Comment by unluckychild** [comment]
Code above, border-collapse:collapse doesnt work. Works when i delete style tags
