### ISSUE TITLE
Undefined array key "VALUE"

### ISSUE THREAD

**Issue by fglueck** [mpdf/mpdf#2000]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

If an SELECT-OPTION have no value attribute, there will throw:
Undefined array key "VALUE"

/srv/www/html/cockpit/inc/vendor/mpdf/mpdf/src/Tag/Option.php
Line: 30

Sample:

### mPDF version

current

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 8.0 + 8.3

### Reproducible PHP+CSS+HTML snippet suffering by the error

      <select id="contact" style="width: 130px" data-mail_body="..."  data-subject=".." onchange="/* */">
      <option selected="true" disabled="disabled">@ Mailanfrage zu:</option>
      <option value="..."         data-subject="Kaufvertragsdaten"            data-body_add="">Kaufvertragsdaten</option>
      </select>

**Comment by finwe** [comment]
This already has a fix here https://github.com/mpdf/mpdf/pull/1934 which I have forgotten about. Will revisit.
