### ISSUE TITLE
Document structure is invalid or damaged

### ISSUE THREAD

**Issue by wq9578** [mpdf/mpdf#2005]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

When producing a PDF/A-1B document, the following lines create an invalid document:

```
            $mpdf->Rect(
                x: self::BBOX[0],
                y: self::BBOX[1],
                w: self::BBOX[2],
                h: self::BBOX[3],
                style: 'F'
            );
```

The file can be opened and displayed, but the "Preflight" function for validating a PDF/A-1B document in Adobe Acrobat reports either one of these two errors:

1. Document structure is invalid or damaged.
2. Unknown mistake (unknown error condition).

The mPDF version is v8.2.2.
The Acrobat version is Adobe Acrobat Pro (Mac) 2024.001.20643.

I suggest waiting for a later Acrobat version in order to exclude the case that the error is caused by Acrobat.
If the problem persists, I might create a minimum working example (MWE) to reproduce the bug.

### mPDF version

v8.2.2

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.3.1

### Reproducible PHP+CSS+HTML snippet suffering by the error

            $mpdf->Rect(
                x: self::BBOX[0],
                y: self::BBOX[1],
                w: self::BBOX[2],
                h: self::BBOX[3],
                style: 'F'
            );

**Comment by wq9578** [comment]
Same problem with an old version from 2021: Adobe Acrobat Pro (Mac) 2021.001.20155.
So the produced PDF is the problem.

**Comment by finwe** [comment]
The code example is not exactly reproducible, is it?

**Comment by wq9578** [comment]
I will try to supply a minimum working example soon.
(As this is not trivial, it might take some time.)

**Comment by wq9578** [comment]
Steps to reproduce:

1. Create file `pdfa_bug.php`:

```
<?php

require('vendor/autoload.php');

$mpdf = new Mpdf\Mpdf();

$mpdf->PDFA = true;

$mpdf->Rect(x: 10, y: 10, w: 10, h: 10, style: 'F');

$mpdf->Output('pdfa_bug.pdf', Mpdf\Output\Destination::FILE);
```

2. Run `composer require mpdf/mpdf`.
3. Run `php pdfa_bug.php`.
4. Open the newly created PDF file `pdfa_bug.pdf` in Acrobat and verify PDF/A conformity. For details, use the preflight menu (verify PDF/A-1b) available in Adobe Acrobat Pro.

In both the 2021 and 2024 versions of Adobe Acrobat Pro (Mac), preflight fails with:
> Document structure is invalid or damaged.

**Comment by finwe** [comment]
PDF/A-1b compatibility was fixed in commit above by matching XMP and document metadata string.

As for the "Document structure is invalid or damaged" in your example, you have to call AddPage first manually unless you are writing into the document by any other method than WriteHTML().

**Comment by wq9578** [comment]
Works well now.
Thank you!

> As for the "Document structure is invalid or damaged" in your example, you have to call AddPage first manually unless you are writing into the document by any other method than WriteHTML().

This information is placed very hidden at the bottom of this page: https://mpdf.github.io/reference/mpdf-functions/addpage.html
I would suggest adding a section "minimum code requirements" displayed more prominently.
