### ISSUE TITLE
SELECT don't show selected element

### ISSUE THREAD

**Issue by fglueck** [mpdf/mpdf#2028]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

![grafik](https://github.com/mpdf/mpdf/assets/3225774/e55c9b5f-e3d2-4c43-b7af-190d8b244f00)

The selected element is not shown in PDF.

### mPDF version

8.2.4

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.0, 8.1, 8.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
$html = <<<HTML
<html lang="de">
   <head></head>  
   <body>
      <select name="k1" disabled>
         <option value="not_selected">bitte w&auml;hlen</option>
         <option value="A">A</option>
         <option value="B" selected>B</option>
         <option value="C">C</option>
      </select>
      <select name="k2">
         <option value="not_selected">bitte w&auml;hlen</option>
         <option value="A">A</option>
         <option value="B" selected>B</option>
         <option value="C">C</option>
      </select>
      <select name="k3">
         <option value="">bitte w&auml;hlen</option>
         <option value="A">A</option>
         <option value="B"  selected="selected">B</option>
         <option value="C">C</option>
      </select>
   </body>
</html>
HTML;
```

**Comment by finwe** [comment]
Your example code produces an empty PDF.

**Comment by fglueck** [comment]
sorry, shorten the names for example and kill a "

**Comment by finwe** [comment]
I fixed that and it does not help.

**Comment by finwe** [comment]
Anyway, looking at the result of [forms example file](https://github.com/mpdf/mpdf-examples/blob/development/example09_forms.php), it works, at least with `selected="selected"`

**Comment by fglueck** [comment]
Sorry, true.
Example works, tidy shorten selected="selected" to selected only.
And this don't work.
Must have all attributes allways have a ="xxx" to work with mpdf?

**Comment by finwe** [comment]
Probably, I don't know. Just use the variant that works :)
