### ISSUE TITLE
Unable to layer images or divs

### ISSUE THREAD

**Issue by tifischer** [mpdf/mpdf#203]
### I have this problem/would like to have this functionality

The documentation says that this should be possible, however, there is no working example of how to implement the ability to layer images or divs.
### These are mPDF and PHP versions I am using

mPDF 6.1.2 & PHP 5.5.31
### This is a PHP code snippet I use

```
<?php
$mpdf->open_layer_pane = true;
$mpdf->layerDetails[1]['state']='hidden'; // Set initial state of layer - "hidden" or ""
$mpdf->layerDetails[1]['name']='Correct Answers'; 
$mpdf->layerDetails[2]['state']='hidden';
$mpdf->layerDetails[2]['name']='Wrong Answers';
```

**Comment by finwe** [comment]
Please, post your PHP/HTML code snippet causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
