### ISSUE TITLE
Documentation Update Needed for Margin Property Syntax Change in mPDF Version 8

### ISSUE THREAD

**Issue by Sanufaith** [mpdf/mpdf#2038]
In the documentation, the margin properties are described using hyphens (e.g., margin-top, margin-bottom). However, upon working with mPDF version 8, I discovered that the correct syntax for these properties has changed to using underscores (e.g., margin_top, margin_bottom). This change seems to have been implemented starting from version 8, but the documentation does not reflect this update.

This inconsistency might lead to confusion among users, particularly those who are upgrading from previous versions where hyphens were used. The absence of information about this change in the official documentation could result in unnecessary troubleshooting and misunderstandings.

To help users adapt to this change smoothly, I recommend updating the documentation to accurately describe the correct syntax for margin properties in version 8. Providing clear and precise information will greatly assist users in avoiding potential issues during their migration to the newer version.

@finwe @palmic @jayvdb @markdorison @jamescarlos

**Comment by finwe** [comment]
Where? In the [constructor doc](https://mpdf.github.io/reference/mpdf-functions/construct.html), there are underscored array keys and IIRC there always been.

Anyway, feel free to propose a PR in the [correct doc repository](https://github.com/mpdf/mpdf.github.io).
