### ISSUE TITLE
Background image is squashed after upgrading to 6.1.2

### ISSUE THREAD

**Issue by tifischer** [mpdf/mpdf#204]
### I have this problem/would like to have this functionality

The background image use to span the whole div area such that other divs could lay on top.  Now the background image gets squashed.
### These are mPDF and PHP versions I am using

mPDF 6.1.2 and PHP 5.5.31
### This is a PHP code snippet I use

```
$tableData = "    <div id=\"cardLogo\" style=\"width:3.325in;height:2.125in;margin:0.125in; background-image: url('logo.jpg'); background-repeat:no-repeat; background-size: 2in 3.25in; background-position: center;  \"> 
    <div style=\"float:left; margin-left:.4in; height:1.125in; width: .875in; padding-top:.8in; \"><img src=\"logo2.jog\" /></div>
    <div style=\"float:left; margin-left:.05in; width:.7in; padding-top:.75in;\">
    <table>
            <tr>
                <td></td>
                       </tr>
       </table>
      </div>
      </div>";
```

**Comment by finwe** [comment]
What was the version you upgraded from?

**Comment by tifischer** [comment]
I upgraded from mpdf51.  That version would not squash the background image however, when opening the PDF in firefox, the background image would also appear blurry.

**Comment by finwe** [comment]
5.1 is sure a big change. Do you experience the same with 5.7 and/or 6.0?

**Comment by tifischer** [comment]
I have not tried those.  6.1.0 is suppose to be the stable release was my understanding.

**Comment by finwe** [comment]
It is. I'm just trying to pinpont where this regression showed up for the first time. Can you please try 5.7 and 6.0 how they behave?

**Comment by tifischer** [comment]
I appologize but I do not have the time to test this for you with multiple versions.

**Comment by finwe** [comment]
Closing as stale.
