### ISSUE TITLE
mPDF Package Incompatibility with Swoole in Laravel Octane (Streaming/Download Issue)

### ISSUE THREAD

**Issue by bmrbehnam** [mpdf/mpdf#2054]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

The mPDF package is not functioning as expected when using the stream() or download() (mpdf->Output($filename, 'I') , mpdf->Output($filename, 'D')) in a Laravel Octane environment with the Swoole driver. When attempting to stream or download the generated PDF, the output is corrupted and contains unreadable characters. However, saving the PDF (mpdf->Output($filename, 'F')) to a file path works correctly without any issues.

Environment Details
Laravel Version: 11
Swoole Version: 5.1.3
mPDF Version: 8.2
PHP Version: 8.3
Code Example
Here is a simple route used for testing:
```
$mpdf->Output($filename, 'I')
```
Output
Instead of streaming a readable PDF, the output looks like the following:
```
%PDF-1.4
%����
3 0 obj
<</Type /Page
/Parent 1 0 R
/MediaBox [0 0 595.280 841.890]
...
```

Steps to Reproduce
Install Laravel Octane with Swoole as the driver.
Set up the mpdf/mpdf package to generate PDFs.
Create a route that generates and streams a PDF using PDF::loadView()->stream().
Access the route and observe the corrupted output.
Expected Behavior
The generated PDF should be streamed or downloaded correctly, as it does when saving to a file path.

Workaround
Saving the PDF using save() works without any issues:
```
$mpdf->Output($filename, 'D');
```
However, using stream or download leads to the corrupted output.
Additional Information
Clearing cache and reloading the Octane server did not resolve the issue.
The issue only occurs when attempting to stream or download the PDF in Octane with Swoole. Running the same code outside of Octane works fine.

### mPDF version

8.2

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.3

### Reproducible PHP+CSS+HTML snippet suffering by the error

%PDF-1.4
%����
3 0 obj
<</Type /Page
/Parent 1 0 R
/MediaBox [0 0 595.280 841.890]
/TrimBox [0.000 0.000 595.280 841.890]
/Resources 2 0 R
/Group << /Type /Group /S /Transparency /CS /DeviceRGB >> 
/Contents 4 0 R>>
endobj
4 0 obj
<</Filter /FlateDecode /Length 143>>
stream
x�=��
�@D�����R���b<l�H'nR�Z#�/���o8܋p�,�̛����]�l�F�wD���|[[�g�8�A�@��dud0/��r���d�Ж]̈́��}���w�2�_����I�&��'}�{3@:�Ne�"y+�
endstream
endobj
1 0 obj
<</Type /Pages
/Kids [3 0 R ]
/Count 1
/MediaBox [0 0 595.280 841.890]
>>
endobj
5 0 obj
<</Type /ExtGState
/BM /Normal
/ca 1
/CA 1
>>
endobj
6 0 obj
<</Type /Font
/Subtype /Type0
/BaseFont /MPDFAA+IRANSansWeb-Medium
/Encoding /Identity-H
/DescendantFonts [7 0 R]
/ToUnicode 8 0 R
>>
endobj
7 0 obj
<</Type /Font
/Subtype /CIDFontType2
/BaseFont /MPDFAA+IRANSansWeb-Medium
/CIDSystemInfo 9 0 R
/FontDescriptor 10 0 R
/DW 534
/W [ 32 [ 283 268 350 658 613 792 689 182 407 422 477 600 237 353 301 427 ]
 48 57 613 58 [ 286 257 548 603 561 524 964 717 680 703 704 610 592 733 766 304 598 680 583 943 765 744 689 744 673 650 654 703 697 948 682 657 649 295 450 295 460 487 347 583 607 564 608 578 382 611 598 275 270 563 275 938 600 613 607 612 379 557 358 599 533 801 542 525 542 362 270 362 717 ]
 160 [ 283 285 605 634 757 657 267 670 ]
 169 169 844 171 171 523 173 [ 353 844 520 ]
 180 180 351 183 183 304 187 187 523 215 215 575 247 247 615 1605 1605 520 65166 65166 271 65169 65169 289 65256 65256 307 65260 65260 437 ]
/CIDToGIDMap 11 0 R
>>
endobj
8 0 obj
<</Length 346>>
stream
/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CIDSystemInfo
<</Registry (Adobe)
/Ordering (UCS)
/Supplement 0
>> def
/CMapName /Adobe-Identity-UCS def
/CMapType 2 def
1 begincodespacerange
<0000> <FFFF>
endcodespacerange
1 beginbfrange
<0000> <FFFF> <0000>
endbfrange
endcmap
CMapName currentdict /CMap defineresource pop
end
end

endstream
endobj
9 0 obj
<</Registry (Adobe)
/Ordering (UCS)
/Supplement 0
>>
endobj
10 0 obj
<</Type /FontDescriptor
/FontName /MPDFAA+IRANSansWeb-Medium
 /CapHeight 713
 /XHeight 517
 /FontBBox [-533 -507 2196 1039]
 /Flags 4
 /Ascent 1039
 /Descent -507
 /Leading 0
 /ItalicAngle 0
 /StemV 109
 /MissingWidth 534
 /Style << /Panose < 0 0 2 4 5 3 5 2 1 2 2 3> >>
/FontFile2 12 0 R
>>
endobj
11 0 obj
<</Length 331
/Filter /FlateDecode
>>
stream
x���GN�FћX���
�!b{���/�ĸa��������-k��ִ�u�oC��H�mnK[���v��]�nO{k_��o��t���;��t���u���T�;���u�]�R���ծ5����|7����t�{��A=�Q�{�Ӟ����U�{�����}�S���׾�����R���iŠ���������������������������������������������������������������������������������������������������������������������������m��]5�����]9�
�����
endstream
endobj
12 0 obj
<</Length 8217
/Filter /FlateDecode
/Length1 11172
>>
stream
x��zXTG����e鰴UQܥ,V����X��.

**Comment by finwe** [comment]
Explicitly setting the Content-type header solves this

    return response($pdf->output('document.pdf'))->header('Content-Type', 'application/pdf');

**Comment by bmrbehnam** [comment]
> Explicitly setting the Content-type header solves this

Thanks, this works.
