### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by tree28** [mpdf/mpdf#2058]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Hello,

There seems to be an error in [ [this](https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html) ] documentation.
ie.
`new Mpdf\Config\ConfigVariables()`
vs.
`new \Mpdf\Config\ConfigVariables()`

Where the first does not include a leading slash (ie. `\`) thus returning an error, while the second that includes a slash works.

Several references on the page should be changed.

### mPDF version

7

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
$fontDirs = $defaultConfig['fontDir'];
```

**Comment by finwe** [comment]
No, the code example has no namespace by itself, so the code is valid.

Sure, the initial backslash is be more safe to copy/paste, I changed it.
