### ISSUE TITLE
How set up custom page size?

### ISSUE THREAD

**Issue by nicdnepr** [mpdf/mpdf#206]
### I have this problem

I use A4 by default, but some pdf has A3 format
When I add A3 with AddPage it not fit size and go out of borders
Is it possible to create pdf with different page size, some page with A4 and some pages with A3?
### This is a PHP code snippet I use

```
<?php

$pdf = new \mPDF();
        $pdf->SetImportUse();


        if ($this->watermark) {
            $pdf->showWatermarkImage = true;
            $pdf->SetWatermarkImage($this->watermark, $this->alpha, [50, 30], $this->position);
        }

        $pagesInFile = $pdf->SetSourceFile($resPdf);

        for ($i = 1; $i <= $pagesInFile; $i++) {

            $tplId = $pdf->ImportPage($i);
            $s = $pdf->getTemplatesize($tplId);
            $pdf->AddPageByArray([
                'orientation' => $s['w'] > $s['h'] ? 'L' : 'P',
                'sheet-size'=>'A3'
            ]);

            $pdf->UseTemplate($tplId);

        }

        $pdf->Output($resPdf);
```

**Comment by jakejackson1** [comment]
It looks like you get the PDF page size before adding the new page to Mpdf (`$s = $pdf->getTemplatesize($tplId);) so why don't you set a custom sheet size based on those dimensions?

**Comment by finwe** [comment]
Closing as stale.
