### ISSUE TITLE
"Uninitialized string offset 0" warnings

### ISSUE THREAD

**Issue by tree28** [mpdf/mpdf#2060]
### Guidelines

- [x] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Hello,

I am a new Mpdf user. Really appreciating it but I have encountered the warning:

`Uninitialized string offset 0 in ... vendor/mpdf/mpdf/src/Mpdf.php on line 16724`

I posted this within a discussion [ [here](https://github.com/mpdf/mpdf/discussions/2059) ] and was instructed to repost with code that produces the error as an issue.

The below HTML should produce the above warning when processed. I believe the empty div used to draw a css line (ie a separator between content) causes the warning to be issued.

### mPDF version

v8.2.4

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

ubuntu 24.04 lts

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style type="text/css">
.my_class {
width: 100%;
border-bottom: 1px solid #d9d9d9;
margin: 40px auto 20px auto
}
</style>
<div>
    <p>Hello World</p>
    <p>Thank you for reading this.</p>
    <div class="my_class"></div>
</div>
```

**Comment by finwe** [comment]
Unable to reproduce with this code example, everything is generated correctly. Feel free to update the code to one that actually causes the error, I will then reopen.

By the line of the error, it seems you use a non well-formed color somewhere.

**Comment by tree28** [comment]
Note that the case was with reference to PHP Warnings, not an error.

**Comment by finwe** [comment]
Yes, there is no warning either.
