### ISSUE TITLE
border-radius  not working on th td in table 

### ISSUE THREAD

**Issue by phpbaba22** [mpdf/mpdf#2076]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

th, td { border-width: 1.50px; padding: 0.3em; position: relative; }
th, td { **border-radius: 0.18em; border-style: solid;  }**
th { background: #e6e6e6df; border-color: #787878; vertical-align: middle;	}
td { border-color: #787878; }

### mPDF version

mpdf/mpdf": "^8.0

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

php": "^8.1

### Reproducible PHP+CSS+HTML snippet suffering by the error

html { font: 14px/1 'Open Sans', sans-serif; overflow: auto; padding: 0.5in; }
html { background: #898888; cursor: default; }

body { box-sizing: border-box; height: 11.5in; margin: 0 auto; overflow: hidden; padding: 20px; width: 8.0in;   }
body { background: #FFF; border-radius: 1px; box-shadow: 0 0 1in -0.25in rgba(0, 0, 0, 0.5); }

table {  table-layout: fixed; width: 100%; }

th, td { border-width: 1.50px; padding: 0.3em; position: relative; }
th, td { border-radius: 0.18em; border-style: solid;  }
th { background: #e6e6e6df; border-color: #787878; vertical-align: middle;	}
td { border-color: #787878; }

**Comment by finwe** [comment]
https://mpdf.github.io/css-stylesheets/supported-css.html
