### ISSUE TITLE
Aborting the PDF render if connection is closed

### ISSUE THREAD

**Issue by bencun** [mpdf/mpdf#208]
I'm using mPDF to generate huge PDF documents and while the performance is relatively fine I'd like to be able to quit generating the PDF if the user disconnects in order to prevent the wasting of the server resources.

My frontend is written in Angular and I'm using AJAJ and POST methond to pass the data to the PHP script that generates the HTML document, renders it and then returns the file which is then offered as a download to the end-user.

What I've noticed on my development machine (using WAMP) is that when I close the tab or interrupt the request in any way the Apache server is still consuming a lot of resources while the PDF is rendering and releases them only when the script is finished rendering the document ($mpdf->Output(); function).

Is there any way to abort the rendering if the user is disconnected? I know that there is no way for PHP to detect that without sending that data but as I can't interfere with what Output() does under the hood there is no way for me to try and detect the user disconnect and the script is stuck there. If there's a way to abort the rendering on user disconnect that would be great but I didn't find any built-in mechanism while sifting through the documentation.

**Comment by jakejackson1** [comment]
This isn't an Mpdf issue. All PHP scripts act this way (they just usually aren't long-running).

I recommend [you review some of these articles](https://www.google.com.au/search?q=abort+PHP+using+ajax&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=DyypV-OWEdHN8gfv4bCwAg) for information about the major challenges of trying to do this.

If you wanted to hack something together I would look at [interval polling](http://stackoverflow.com/questions/6835835/jquery-simple-polling-example), combined with [sub-processing](http://symfony.com/doc/current/components/process.html) which your [main process can stop](http://symfony.com/doc/current/components/process.html#stopping-a-process) if it doesn't receive the poll within a certain timeout period.

**Comment by bencun** [comment]
Yes, I'm aware of that this isn't the mPDF issue but I couldn't think of a way to do it without tinkering with the mPDF's source code.
I was researching the issue for a couple of days before posting here. It would really be a **great** functionality to have inside the library itself. I hope it's implemented efficiently one day.

Thank you for the links and the information provided, I hope I'll come up with something!
