### ISSUE TITLE
Table and automatic page break

### ISSUE THREAD

**Issue by mwitzmann** [mpdf/mpdf#214]
### I have this problem/would like to have this functionality

I would like to automatically slice a table, if it doesn't fit on a page. Currently the table is being shrunk by mpdf. I tried to set "shrink_tables_to_fit" to "0" or "1" or use the attribute "autosize=1" in the table.
### These are mPDF and PHP versions I am using

I'm using mpdf 6.0

**Comment by RonakParmar** [comment]
Hi There,
I am also using mpdf library to generate pdf. I have same kind of issue, in pdf table is being divided in two pages and pdf output looks very bad. Is there any solution for this? like auto page break if table is being divided in two table then apply page break and display whole table in one page.
Thank you in advance.

**Comment by RonakParmar** [comment]
I have used this line and now my table structure is not being divided in two pages. This works great for me. hope this will help you.
$mpdf->autoPageBreak = false;
$mpdf->WriteHTML($html);

**Comment by supun151515** [comment]
I have table in mpdf and I want to break the table when rows are not fit with the page size.
I have tried table {page-break-after: always;}
I it is not breaking the table. It is moving whole table to next page

**Comment by mrtuvn** [comment]
@RonakParmar your trick only work with document fit in one page. If content more than one you will lose document content

**Comment by rtwent** [comment]
`<table style="page-break-inside:avoid">...</table>`
Fixed my problem

**Comment by finwe** [comment]
Please see

> (Note that mPDF will always resize tables if it is the only way to fit a row or whole table onto a full page.)

On the [Tables documentations page](https://mpdf.github.io/tables/tables.html#page-break-insideavoid).

As this issue is older and became somewhat shattered by discussion, I'm going to close it. If your problem persists, feel free to file a new issue providing all details to easier reproduce the behaviour, especially PHP/HTML snippet used and expected result.

**Comment by hairullana** [comment]
> 

but it will be 1 page and hide the rest of the text

**Comment by hairullana** [comment]
> page-break-inside:avoid

but it will take a table with long text in 1 page, the text looks very small
