### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by Tsyklop** [mpdf/mpdf#217]
### I have this problem/would like to have this functionality

error occurred while accessing the file http://localhost:25565/mPDF/mpdf.php : 

```
Warning: require_once(D:\BitrixWeb\www\mPDF\classes/../MpdfException.php) [function.require-once]: failed to open stream: No such file or directory in D:\BitrixWeb\www\mPDF\classes\indic.php on line 3

Fatal error: require_once() [function.require]: Failed opening required 'D:\BitrixWeb\www\mPDF\classes/../MpdfException.php' (include_path='.') in D:\BitrixWeb\www\mPDF\classes\indic.php on line 3
```

I did not find the file MpdfException.php

And this if i try view example:

```
Warning: require_once(D:\BitrixWeb\www\mPDF\examples/../vendor/autoload.php) [function.require-once]: failed to open stream: No such file or directory in D:\BitrixWeb\www\mPDF\examples\example05_tables.php on line 996

Fatal error: require_once() [function.require]: Failed opening required 'D:\BitrixWeb\www\mPDF\examples/../vendor/autoload.php' (include_path='.') in D:\BitrixWeb\www\mPDF\examples\example05_tables.php on line 996
```

### These are mPDF and PHP versions I am using

laset release mPDF, PHP 5.3.2

### This is a PHP code snippet I use

```
<?php


```

### This is a HTML code snippet I use

```

```

**Comment by finwe** [comment]
How did you install mPDF? Via composer, or via ZIP download? What is the "last release"?

**Comment by Tsyklop** [comment]
@finwe last release from the tab `releases` in mpdf project.

I download ZIP from the tab `releases` and unpack.

**Comment by finwe** [comment]
Which ZIP?

**Comment by Tsyklop** [comment]
@finwe this ZIP: https://github.com/mpdf/mpdf/archive/v6.1.2.zip

**Comment by Tsyklop** [comment]
http://localhost:25565/mpdf/mpdf.php work fine now. But an error with examples still there.

**Comment by finwe** [comment]
This ZIP does not contain pre-generated autoload files. 

Use composer or use own autoloader or load all required files manually.

**Comment by Tsyklop** [comment]
Where get required files?

**Comment by Klap-in** [comment]
If you use the composer (a tool that installs stuff as defined in a configuration file), than all stuff is obtained and installed.

Installation instruction: https://github.com/mpdf/mpdf/blob/development/README.md
(Definition: https://github.com/mpdf/mpdf/blob/development/composer.json)
