### ISSUE TITLE
IMAGE Error: Error parsing temporary file

### ISSUE THREAD

**Issue by Tsyklop** [mpdf/mpdf#218]
### I have this problem/would like to have this functionality

Generating PDF. On Windows, everything is fine, no errors. I put the same on Linux and this error appears when generating:

[error](http://pastebin.com/VnKJ0eRW)

And another problem is that Linux PDF is generated with the error - it can not be opened after. But on Windows, with the same code everything works fine.

### These are mPDF and PHP versions I am using
mPDF 6.1.2
### This is a PHP code snippet I use

 [php code](http://pastebin.com/RvgURgXX)

generated pdf:
[329.pdf](https://github.com/mpdf/mpdf/files/422698/329.pdf)

**Comment by finwe** [comment]
Not mPDF fault, the GD library on Linux cannot process somewhat faulty PNG image.
