### ISSUE TITLE
$list_item_marker

### ISSUE THREAD

**Issue by ram-you** [mpdf/mpdf#22]
Undefined variable: list_item_marker.
Variable $list_item_marker seems to be uninitialized.
(mpdf.php v6.0    Line: 19446)
SOLUTION:
Line 19446 : 
```javascript
$objattr['text'] = $list_item_marker; 
```
have to be commented or deleted.

**Comment by finwe** [comment]
There are thousands of similar issues in the code. It is interesting that only this one should cause you any trouble. Fixing these issues would require a lot more work.

mPDF should override error_reporting settings to ignore notices and strict warnings. Do you by any chance change error_reporting after including mPDF?
