### ISSUE TITLE
Class 'Mpdf\Mpdf' not found

### ISSUE THREAD

**Issue by weichenlin** [mpdf/mpdf#226]
### I have this problem/would like to have this functionality
when I following the instruction of usage, I got error:
```
$ php mpdf.php
PHP Fatal error:  Uncaught Error: Class 'Mpdf\Mpdf' not found in /home/user/php_pdf_lab/mpdf.php:5
Stack trace:
#0 {main}
  thrown in /home/user/php_pdf_lab/mpdf.php on line 5

Fatal error: Uncaught Error: Class 'Mpdf\Mpdf' not found in /home/user/php_pdf_lab/mpdf.php:5
Stack trace:
#0 {main}
  thrown in /home/user/php_pdf_lab/mpdf.php on line 5
```

### These are mPDF and PHP versions I am using
in composer.lock:
```
"name": "mpdf/mpdf",
"version": "v6.1.2",
"source": {
    "type": "git",
    "url": "https://github.com/mpdf/mpdf.git",
    "reference": "da078bc2669d3f98553ac41f920ead4c17c951ad"
},
```

php -v
```
PHP 7.0.5 (cli) (built: Apr 19 2016 12:28:46) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

### This is a PHP code snippet I use

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('<h1>Hello world!</h1>');
$mpdf->Output();
```

### This is a HTML code snippet I use

```
running on cli, no html
```

**Comment by finwe** [comment]
In 6.1, there is no \Mpdf\Mpdf class, that is v7+. use new mPDF();

**Comment by weichenlin** [comment]
test with 7.0.x-dev, the issue is still there, same code, same error.
in composer.lock:
```
"name": "mpdf/mpdf",
"version": "7.0.x-dev",
"source": {
    "type": "git",
    "url": "https://github.com/mpdf/mpdf.git",
    "reference": "f316a8be3969d5772260b6f0709470af2004c5e1"
},
```

**Comment by finwe** [comment]
use `dev-development` for namespaced 7.0 version.

**Comment by weichenlin** [comment]
dev-development works

thanks

**Comment by MarkehMe** [comment]
Someone should update the README usage

**Comment by Klap-in** [comment]
Please be more specific. Thanks. Some questions:
Where do you read the readme?
What do you try to achieve?
Which improvement would you propose?

**Comment by MarkehMe** [comment]
The readme usage is here on GitHub https://github.com/mpdf/mpdf#usage

Because its changed to `new \mPDF();` not `new \Mpdf\Mpdf();`

**Comment by finwe** [comment]
- "Someone should"? PR or STFU.
- Did you read the little note above usage example in the readme?
- And no. See #254 or #269

**Comment by MarkehMe** [comment]
That was really rude. "**pull request or shut the fuck up**" is not a nice way to approach that. If I made a PR it would probably have been rejected so why even suggest that? 

Are we not supposed to report _potential_ errors in documentation or make suggestions? 

There are multiple questions about it - it's obviously not being understood by people new to the library, so perhaps you should make it clear that there is an alternative usage that uses a different method than what is visible to us... instead of being a flat-out dickhead and suggesting that we go find your faintly visible message notifying us that the development branch is set as default. It is very misleading and that is not an excuse for you to be a dickhead. 

👎

**Comment by finwe** [comment]
It was, you are completely right. I hope this ambiguity will be eventualy resolved when 7.0 is released as stable.

**Comment by janstieler** [comment]
Hi,
I had the same problems with `new \MPDF\MPDF();` on version 7.
For everybody who have the same problems I solved it with `new \mPDF();`.

Cheers

**Comment by cdmathukiya** [comment]
@janstieler can you describe all the steps from scretch.
i am using php 7.1.13

**Comment by janstieler** [comment]
@cdmathukiya I have used it on the normal way.
First include the autoloader or the class directly and than when you make the new instance of the mPDF object, use `new \mPDF();` instead of `new \MPDF\MPDF();`.

Here with autoloader and some parameters for mPDF:

```
    require_once __DIR__ . '/vendor/autoload.php';

    $mpdf = new \mPDF('utf-8','A4','');
```

**Comment by suthra** [comment]
Add 
use mpdf;
on top of the controller.

then create object using

           $pdf = new \Mpdf\Mpdf();
            $pdf->SetHeader('header');
            $pdf->WriteHTML('Hello World');
            $pdf->SetFooter('footer');
            $pdf->Output('MyPDF.pdf', 'D')
where,
SetHeader - used to add header 
WriteHTML - is the pdf content
SetFooter- used to add footer
then the output will download the pdf as MyPDF.pdf

**Comment by ihemantkumar** [comment]
Did anyone found the solution? I am stuck on the same issue. I am using PHP 7.4 on Ubuntu with Yii1. I am trying to add the view using renderPartial(). 
     ```
  $mPDF1 = Yii::app()->ePdf->mpdf();
        # You can easily override default constructor's params
        $mPDF1 = Yii::app()->ePdf->mpdf('', 'A5');
        $stylesheet = file_get_contents(Yii::app()->baseUrl .'/css/style.css?v='.date('YmdHis'));
        $mPDF1->WriteHTML($stylesheet, 1);
        $mPDF1->WriteHTML($this->renderPartial('pdf', array(), true));
        $mPDF1->Output();
```
The plugin in returning me this error: "PHP Fatal error:  Trait 'Mpdf\\Strict' not found in /vendors/mpdf/src/Mpdf.php on line 39
