### ISSUE TITLE
Add configuration settings for tmp directories

### ISSUE THREAD

**Issue by Preclowski** [mpdf/mpdf#232]
Hi, i think keeping tmp files in vendor location is bad idea. If this settings will be moved to constructor etc. it could be easily changed eg. in symfony bundle. And will not cause any compatibility issues.

**Comment by finwe** [comment]
There are constants for that in `<7.0`

```
define("_MPDF_TEMP_PATH", __DIR__.'/../storage/framework/pdf/');
define("_MPDF_TTFONTDATAPATH", __DIR__.'/../storage/framework/pdf/fonts/');
```

And a `tempDir` configuration option in 7.0+

See [documentation](https://mpdf.github.io/installation-setup/folders-for-temporary-files.html).
