### ISSUE TITLE
LIMIT IN NUMBER OF FILES

### ISSUE THREAD

**Issue by yuli06** [mpdf/mpdf#233]
Hi, I´m trying to generate a PDF file with the data of a table from my database
so I run a query and get the results by a foreach cycle and I call the mpdf class inside the cycle
it work fine but my problem is that the code only can create 60 files and at that point stop despite of the query returns more rows 
I´ve tried without call mpdf method and the cycle return all the rows correct

I am using mpdf v6.0 an php 5.5
I don´t get any error and i don´t have idea about what can be happen

This is a part of my php code
```
<?php
foreach($result as $row){
$mpdf=new mPDF('c','Letter','','',10,10,10,10,16,13); 
$mpdf->AddPage('P','','','','',10,10,10,10,18,12);
$mpdf->SetDisplayMode('fullpage');
$mpdf->list_indent_first_level = 0; // 1 or 0 - whether to indent the first level of a list
$mpdf->WriteHTML($stylesheet,1);  
$mpdf->WriteHTML($content,2);
$mpdf->Output('file.pdf','F');
}
?>
```
I hope someone can help me
thanks in advance

```

```

**Comment by ShutUpMagda** [comment]
Did you tried to make the same thing with a FOR? 

This always works for me:

for ($i=0; $i < count($Array); $i++) {
	$ObjNome = $Array[$i]['name'];
	$ObjNum = $Array[$i]['num'];
	$ObjHtml = $Array[$i]['html'];
	$mpdf=new mPDF();
	$mpdf->WriteHTML($ObjHtml);
	$mpdf->Output("output/file".$ObjNum.".pdf",'F');
}

**Comment by finwe** [comment]
How does the program _stop_? With an error? Does it seem like an issue of mPDF?

**Comment by yuli06** [comment]
Thanks for your answers :)

I tried with FOR but the same... in that cycle I also create a text file is I comment the lines where I use mPDF the cycle works fine and make all the text files, I comment code that makes txt files but just creste 2 or 3 more pdf files
I don´t know how much resources mPDF require but I don´t think it can be about resources... I have a good server

don´t get any error just the page finish of load and stopped creating files

**Comment by finwe** [comment]
Closing this as it seems unrelated to mPDF. Feel free to reopen if you find out mPDF causes the loop to stop.

**Comment by yuli06** [comment]
I have just another question
there is a way to show is an error occurs, only to be sure that the problem is not related to mPDF
thanks
