### ISSUE TITLE
Parse error in main Mpdf class

### ISSUE THREAD

**Issue by jbisg** [mpdf/mpdf#235]
This line, `const SCALE = 72 / 25.4;` in Mpdf.php is causing a parse error

I am using the dev-development version of mpdf and PHP 5.6.25

Replacing this line with the calculated value allows the file to be parsed.

**Comment by finwe** [comment]
Are you sure about your PHP version? Everything is OK in [PHP 5.6 travis build](https://travis-ci.org/mpdf/mpdf/jobs/159551638) and evaluated class constants are supported since PHP 5.6.0.

**Comment by jbisg** [comment]
This may be an issue with my machine.  I tried it on a Vagrant machine, same version of PHP, and no issue.
