### ISSUE TITLE
Restore page style when TOC inserted

### ISSUE THREAD

**Issue by garybarnes995** [mpdf/mpdf#236]
### I have this problem/would like to have this functionality

I have an application which creates a PDF then imports other PDF files as appendices. The import works fine as long as I set the page size to match the incoming file, and I remove any headers and footers. The problem is that when the completed file is written the Table of Contents page has the format of the last inserted PDF. Is there a way to save a page style (margins, size, orientation, headers) then re-instate it just before writing the file (which then writes the TOC at the tocpagebreak tag)?
### These are mPDF and PHP versions I am using

mPDF version 6.0
php version 5.5.19

**Comment by garybarnes995** [comment]
Updated to mPDF version 7.0, no change.

**Comment by garybarnes995** [comment]
I've fudged this by adding a page at the end with the settings which I save when I encounter the <tocpagebreak> tag. This corrects the TOC page, but now I'm left with a blank page at the end which I can't remove. The only way I can see round this is to save the PDF, create a new document, import n-1 pages from the original. A PAGE DELETE option might be useful.

**Comment by tungtrinh** [comment]
This issue is really disturbing

**Comment by finwe** [comment]
Please, post your PHP/HTML code snippet and/or files used causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
