### ISSUE TITLE
TOC showing wrong pagenumbers

### ISSUE THREAD

**Issue by nikowiegand** [mpdf/mpdf#237]
Hello everybody,

I am using mpdf to create a PDF file from data extracted from databases. I use $mpdf->TOC_Entry in a loop to create the different entries depending of the data.
Now the ToC is generated, but each time I use it in a loop, I get only the first pagenumber instead of the correct number of the page the entry appears. 
### PHP version is 5.5 and mpdf version is 6.0

i use the toc entry like this:

```
 $mpdf->TOC_Entry($headline, 1);
```

Any suggestions?
Greetings Rakvak

**Comment by Rakvak** [comment]
Has nobody a solution for this?

**Comment by finwe** [comment]
Please, post your entire PHP/HTML code snippet causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
