### ISSUE TITLE
BarCode Example 37 generating error

### ISSUE THREAD

**Issue by nsidev** [mpdf/mpdf#238]
### I have this problem/would like to have this functionality
When running the barcode example, an error is being generated. 
"Can't open file ../ttfdata/dejavussascondensed.GSUBGPOStable.dat in ../classes otl.php line 297"

Essentially, the file was supposed to have been created and it is not.

Stack Trace is as follows:
#0: mpdf.php (16212: otl->applyOTL ('Page 1 of 1',255)
#1: mpdf.php(15105): mpdf->WriteHTML('#2 ../mpdf.php(16073):mpdf->getHtmlHeight ('#3 

I just installed (updated) MPDF to 6.1 and am trying to get the barcode functionality working.

### These are mPDF and PHP versions I am using
Latest MPDF V 6.1, PHP 5.6.
### This is a PHP code snippet I use
None. just ran the "MPDF/examples/example37_barcodes.php" that ws supplied.
[mpdf error from example37.docx](https://github.com/mpdf/mpdf/files/490593/mpdf.error.from.example37.docx)

**Comment by finwe** [comment]
Do you have write permissions for ttfontdata directory?

**Comment by nsidev** [comment]
Yes, set it to 775. Lots of other files created.

Sent from my iPhone

On Sep 24, 2016, at 6:55 AM, Matěj Humpál <notifications@github.com> wrote:



	Do you have write permissions for ttfontdata directory?

**Comment by jakejackson1** [comment]
Try delete everything in the 'ttfontdata' directory and run your script again. Mpdf only checks for the existence of one "group" file for each font to determine if it should build the cache, so, like in your case, if that checked file generates but one of the others fails you get an error.

**Comment by nsidev** [comment]
I had to set permissions to 777 for it to work.

I will keep playing with permissions to find the right balance.

**Comment by finwe** [comment]
If you run your scripts in a browser, it is possible that the user trying to write to the directory is www-data or apache (the one of the web server) and if your user is not in servers group or the other way around, 775 permissions simply won't suffice.

**Comment by nsidev** [comment]
Seems reasonable.

 

Please update your documentation then.

 

R

**Comment by finwe** [comment]
775 will be still recommended temp dir mode. It is generally frowned upon to keep 777 as your directory permissions, the issue can be solved by other means - eg by groups, where 775 will be OK.

I agree we can add a notice about those kinds of problems, yes.
