### ISSUE TITLE
Whatever be page size, document size is fixed @ 8.5 inches width

### ISSUE THREAD

**Issue by madhur77** [mpdf/mpdf#245]
### I have this problem/would like to have this functionality
I have chosen width as 80mm, so the printed area is 80mm, but there is a lot of white space and document remains 290mm always.......
### This is a PHP code snippet I use

```
<?php

$mpdf=new mPDF('utf-8', array(80,236),'', 0, 0, 0, 0, 0, 0, '');
```

**Comment by finwe** [comment]
Your code works for me in 6.1.2. Closing, feel free to reopen with additional information and code.
