### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#25]
It would be good in the near future to start writing unit tests for mPDF and breaking down some of the methods into smaller, more manageable chunks. I had understood v6 was the last major release Ian was going to work on. If mPDF is to move forward as a community effort the first step would be to refractor the software. Writing unit tests would be stage 1 of this process. 

Thoughts?

**Comment by finwe** [comment]
I'd see unit tests as stage 2 after forcing some coding standard on the project. But altogether I definitely agree.

**Comment by blueliquiddesigns** [comment]
Sounds good (and I see there is already a few pull requests addressing the coding standards). Identifying which standards that should be applied first and opening a new 'issue' ticket for each is probably the best course, as it would allow multiple users to work concurrently (unless you think it would be better handled by a single user).

**Comment by finwe** [comment]
Closing - individual unit test should be discussed under concrete PRs/issues
