### ISSUE TITLE
Table row problem

### ISSUE THREAD

**Issue by nyxp1** [mpdf/mpdf#250]
I have this problem in mpdf. I have two tables, one table consist of two rows. The first row consist of small text and the other one with large text. When I generate the pdf, the first row displayed in the first page and the other one display on the next page since it consist of large text. There are too much space in the first page, I want to cut the row into two parts to occupy the space in the first page. Is this possible?

The other table didn't display in the pdf since it composed of one row with large data that don't fit in one page.

**Comment by gabsprates** [comment]
@nyxp1 see the #164 , i guess it's the same problem. Anyway, have you made any progress?

**Comment by finwe** [comment]
Closing partially as stale, partially as missing example code, partially as duplicate.

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.
