### ISSUE TITLE
MPDF Debug Class

### ISSUE THREAD

**Issue by R1W2** [mpdf/mpdf#255]
I find that the main problem that I have is converting older reports that are missing closing HTML tags. I try to clean those up before I switch to mPDF, but some slip through, or are introduced during changes. I have written a bare bones debug class for mPDF, such that I just change the included file from mpdf.php to mpdf_debug.php. I can then review the produced html from my code to clean it up in order to make mPDF 'happy' and work. Perhaps this would be of use to others.

### This is a PHP code snippet I use, file name: mpdf_debug.php

```
<?php

// This is the simple mpdf debug class. Replace the include statement mpdf class with this file. It will output HTML for review.
class mpdf {
	
	public function __construct($Param1,$Param2) {
		//echo "mpdf construct<br>";
		//echo "Param1 = " . $Param1 . ';Param2=' . $Param2 . "\r\n";
   	}
	
	public function WriteHTML($HTML,$Param2) {
		echo $HTML . "\r\n";
	}
	public function Output($Filename,$Param2) {
		echo "Request to write File to:" . $Filename . "<BR>" . "\r\n";
		echo "Output Param2=" . $Param2 . "<BR>" . "\r\n";
	}
	public function SetHTMLHeader($Header){
		echo "\r\n" ."HTML Header Set to: " . $Header . "<br>" . "\r\n";
	}
	public function SetHTMLFooter($Footer){
		echo "\r\n" ."HTML Footer Set to: " . $Footer . "<br>" . "\r\n";
	}

}	// End of class mpdf_debug

require_once (__ROOT__ . 'includes' . DIRECTORY_SEPARATOR . 'mPDF60' . DIRECTORY_SEPARATOR . 'mpdf_debug.php');

```
Enjoy!

**Comment by finwe** [comment]
These debug outputs can go to the `\Psr\Log\LoggerInterface` calls in `development` as `\Mpdf\Mpdf` implements `\Psr\Log\LoggerAwareInterface`
