### ISSUE TITLE
to cache or not to cache

### ISSUE THREAD

**Issue by 1manfactory** [mpdf/mpdf#257]
### I have this problem/would like to have this functionality

Right now I am building a little MD->PDF factory with the help of mpdf and of course I am doing changes on the code by the minute. I came across a very disturbing behavior of my PDF reader (PDF Exchange 2.5 on Windows 7) which works pretty normal most of the time.

Until today when I was changing stuff in my code so fast and created new PDF files that PDF Exchange Reader did now show differences as long as the file name does not change. It took about 3-5 minutes until I open the same(!) file again and finally see the differences. This was really driving me nuts, I can tell you. The software is caching the PDF, can you believe this?!?

I started creating the files with partly random names:

> $mpdf->Output('./name'.md5(mt_rand()).".pdf");

But there has to be a smarter way. There is no such thing as a cache setting in PDF Exchange.

### These are mPDF and PHP versions I am using

mPDF: 6.1
PHP Version 5.4.45-0+deb7u5

**Comment by finwe** [comment]
Closing as unrelated to mPDF. I'm afraid there is no better solution than yours generating random file names. Maybe better with microtime to keep them in order.
