### ISSUE TITLE
Lora Font not working at all

### ISSUE THREAD

**Issue by 1manfactory** [mpdf/mpdf#258]
### I have this problem/would like to have this functionality

Trying to get Lora Font working [https://fonts.google.com/specimen/Lora](https://fonts.google.com/specimen/Lora)

### These are mPDF and PHP versions I am using

mPDF 6.1
PHP Version 5.4.45-0+deb7u5

### This is my part in config_fonts.php

```
$this->fontdata = array(
    "lora" => array(
		'R' => "Lora-Regular.ttf",
		'B' => "Lora-Bold.ttf",
		'I' => "Lora-Italic.ttf",
		'BI' => "Lora-BoldItalic.ttf",
		),
```

All 4 font files have been copied to the ttfonts folder. I can see files being generated in ttfontdata folder: lora.cgm, lora.cw, loraB.gid.dat and so on

When trying to convert this:

`<p style="font-family:lora;">Hello Word!</p>`

The pdf document is generated but the font stays default.

This (right now) only happens with Lora font, not with other fonts. Other fonts work, even a very simply font I created myself just for fun.

What am I doing wrong?

**Comment by jakejackson1** [comment]
Not sure what you are doing wrong but I had no issue displaying the Lora Font in my version of Mpdf. 

Try set the font family on the `body` tag and see if that helps.

**Comment by 1manfactory** [comment]
I tried to define it almost everywhere: body, p, inline - did not work.

Just tried it with another font: Gentium Basic - everything is fine.

I even download Lora from the source again. Still no success.

By the way: Comic Sans MS - (yeah I know, sucks) as well does not work. I use this font to fast check if any changes on my style sheet really took affect.

**Comment by Klap-in** [comment]
Maybe you could share a complete literal example which shows the troubles for you.

**Comment by 1manfactory** [comment]
I will pack something together (including my generated results) tomorrow. I am too tired now and wife demands some family time.
Thanks for listening so far.

**Comment by 1manfactory** [comment]
Ok, looks like ist was my fault. It was a fatal combination of different circumstances:

- working 10 h non stop
- overseen a **\<link rel="stylesheet" type="text/css" href="stylesheet.css" />** which was constantly in battle with the definitions inside **$mpdf->WriteHTML($stylesheet,1);**
- Lora looking so damn similar to the default font. Really, you have to zoom in to spot differences.
- and above all the stupid habit of PDF Exchange caching PDF files with similar names for 3 minutes (no joke) so that sometimes I was checking the same results over and over again.

Thanks very much for responding so fast. That gives me confidence in choosing mpdf - after checking out Pandoc, Ghostscript, commandline soffice, wkhtmltopdf, fpdf, dompdf and tcpdf
