### ISSUE TITLE
Initial Drop Caps fail

### ISSUE THREAD

**Issue by 1manfactory** [mpdf/mpdf#259]
### I have this problem/would like to have this functionality

I tried to create initial drop caps (which always looks fine on HTML) with help of this article https://www.smashingmagazine.com/2012/04/drop-caps-historical-use-and-current-best-practices/

But somehow the only changes applied to the initial letter are color and size. All other settings took no affect: margin-top, margin-right etc.

### These are mPDF and PHP versions I am using
mPDF 6,1
PHP Version 5.4.45-0+deb7u5

### This is a PHP code snippet I use

```
<?php
require_once '../../mpdf61/mpdf.php';
$html = '
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de">
<head>
<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
<title>Initialen</title>
    <style>
      h1 { color: green; }
	  
.dropcap{
    float:left;
    font-size:400%;
    margin-top:14px;
    margin-right:5px;
    color:#8C8273;
    }	  

    </style>
</head>
<body>
<h1>Initial Drop Caps</h1>
<p><span class="dropcap">H</span>istorically, initial caps were not just decorative elements. Scribes used them to mark where a new section—a new idea—started in the text. This in turn helped “readers” find their place in a text. ÄÖÜ</p>
</body>
</html>
';


$mpdf=new mPDF('', 'A5'); 
$mpdf->SetDisplayMode('fullpage');
$mpdf->WriteHTML($html);
$mpdf->Output('./initialen'.md5(mt_rand()).'.pdf');
?>


```

See the results in the attached file.
[initialen3d97fbabfe57265ea0043a62264145c4.pdf](https://github.com/mpdf/mpdf/files/573112/initialen3d97fbabfe57265ea0043a62264145c4.pdf)

**Comment by 1manfactory** [comment]
Hello,
I have to bringt that up again because it's been 25 days without any reaction and I would really see this to be fixed.
Is there anybody working on it or has anybody accepted this as a problem at all?

**Comment by jakejackson1** [comment]
Based on your report and your code snippet, what you have described is the current expected behaviour. [Please refer to the Mpdf documentation](http://mpdf.github.io/css-stylesheets/supported-css.html) for supported CSS on inline elements (i.e your span tag).
