### ISSUE TITLE
Code cleanup - Coding standard

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#26]
Before all orher code enhancements, I would like to enforce a coding standard on the project.

PSR-2 may be a nice choice, of course with some exceptions to maintain backwards compatibility.

**Comment by Verron** [comment]
I can assist you with this. IMO, integrating some sort of way of checking through workflow automation (grunt/gulpjs) would make it easier for contributors as well, and lay some ground work for modernized development flows involving various forms of testing..
