### ISSUE TITLE
Emoji's not recognised 

### ISSUE THREAD

**Issue by cbxiii** [mpdf/mpdf#261]
I am aware this has already been mentioned in a previous issue. However that issue was closed and there was no clear resolution. 

Here is an example of the results I am getting:

```
include("../mpdf.php");

$html = "<div style='font-family:times;'>Lorem ipsum 😇</div>";

$mpdf=new mPDF('utf-8', array(153,234)); 

$mpdf->SetDisplayMode('fullpage');

$mpdf->WriteHTML($html);

$mpdf->Output();
```

If I use the reference code such as `&#x1F3E1` I also get the same result. 

The resulting PDF looks like this: 
[mpdf-example-noemoji.pdf](https://github.com/mpdf/mpdf/files/575529/mpdf-example-noemoji.pdf)

How can I get the library to encode these emojis correctly?

**Comment by finwe** [comment]
This is not a question of encoding but more of a character support in used font.

You need to explicitly use a font that supports emoji characters. Default DejaVu font apparently does not.
