### ISSUE TITLE
A page started without a number 57?

### ISSUE THREAD

**Issue by netdragoon** [mpdf/mpdf#262]
### This is a PHP code snippet I use

You can print a numbering of a page with a specific value, for example: a page started without a number 57.

Do you have this feature?

**Comment by Klap-in** [comment]
You mean this?
https://mpdf.github.io/paging/page-numbering.html
Or provide an example please.

**Comment by netdragoon** [comment]
@Klap-in  No
No

Start the page with a certain number, example 5 and go numbering from there (6,7,8 ...)

That is, I choose the number that starts the page count

**Comment by jakejackson1** [comment]
@netdragoon you want to use the `resetpagenum` option when adding the page with either [`$mpdf->addPage()`](https://mpdf.github.io/reference/mpdf-functions/addpage.html) or [`$mpdf->addPageByArray()`](https://mpdf.github.io/reference/mpdf-functions/addpagebyarray.html) (preferred).

**Comment by netdragoon** [comment]
@jakejackson1 
I want to put numbering started in any number. Example does not start 1,2,3, I want it to be started 56,57,58?

**Comment by finwe** [comment]
@netdragoon See [this StackOverflow Question and Answer](https://stackoverflow.com/questions/40471263/mpdf-start-page-numbering-from-number-10-on-the-first-sheet/40482390#40482390)

**Comment by netdragoon** [comment]
Thank you @finwe
