### ISSUE TITLE
6.1 vs. 7.0 - no differences in archive repository

### ISSUE THREAD

**Issue by 1manfactory** [mpdf/mpdf#264]
I just downloaded 7.0 from https://github.com/mpdf/mpdf/tree/7.0 (https://github.com/mpdf/mpdf/archive/7.0.zip)

But this file's content is byte equal to 6.1 (https://github.com/mpdf/mpdf/archive/6.1.zip)

Am I missing something?

**Comment by finwe** [comment]
You are right. I have removed the `7.0` branch to prevent confusion. Use `development` to test 7.0 in early versions.
