### ISSUE TITLE
Please create releases for 6.1.1 and 6.1.2

### ISSUE THREAD

**Issue by jcnventura** [mpdf/mpdf#265]
It seems that you've only created a release for 6.1.0.. For the sake of anyone not running composer, it would be nice to have releases for all other tags, but at least for 6.1.2.

**Comment by 1manfactory** [comment]
Have to agree.

I don't like composer. They say it ought to run simple and smoothly - but most of the time it does not. There is always something wrong with rights setting or something missing.

**Comment by Klap-in** [comment]
At this page just above the bigger description of 6.1.0 releases you find the downloads for the tags of the other two releases:
https://github.com/mpdf/mpdf/releases
