### ISSUE TITLE
Suspicious function in MPDF.PHP

### ISSUE THREAD

**Issue by abushoaib** [mpdf/mpdf#266]
### I have this problem/would like to have this functionality
I have used mpdf in wordpress to generate pdf. With some wordpress security plugins are reporting that mpdf.php files contains suspicious functions. Then i tried to find suspicious function i see  http://www.screencast.com/t/TOuibaR6J  

PHP pack and unapck function i
![2016-11-16_1818](https://cloud.githubusercontent.com/assets/6826751/20347501/b058b4e6-ac2b-11e6-9121-9026f4b3e5b6.png)
s treating as suspicious function. is there any alternative of php pack and upnpack function to get ride of security warning. 
### These are mPDF and PHP versions I am using
6.1
### This is a PHP code snippet I use

```
<?php


```

### This is a HTML code snippet I use

```

```

**Comment by finwe** [comment]
`un`/`pack` is needed to generate and parse binary font data. No simple solution can be used to replace these functions and they are no security threat by themselves, so they will be left in the source.
