### ISSUE TITLE
Total page number is not replaced

### ISSUE THREAD

**Issue by Dgame** [mpdf/mpdf#267]
We've updated from version 5.* to the latest and now the total page number is not replaced anymore. How can I fix that?
![demv-pdf-bug](https://cloud.githubusercontent.com/assets/2406877/20428816/7125b4fc-ad8b-11e6-84f6-40c2b80495b8.png)

I've already tried several other versions and can assure that version 5.7.4 is the latest version where it works correctly.
I would like to show you a short example or snippet but the code is an absolute mess, so it is impossible for me to get a reduced example, I'm sorry. I hope you can get me a hint anyway.

**Comment by Klap-in** [comment]
According https://mpdf.github.io/what-else-can-i-do/replaceable-aliases.html the `{nb}` (or its replacement if set via `AliasNbPages()` ) works only in the header since mPDF 6.0. So it was intentional changed. 

@kenowessels So the examples at the `AliasNbPages()` function page needs an update https://mpdf.github.io/reference/mpdf-functions/aliasnbpages.html#examples

It is difficult to find in the code what was changed between mPDF 5 and 6, because version 5 is not in this repository. So I have sofar no idea if it is difficult or easy to introduce it again.

**Comment by ctrlaltca** [comment]
To workaround this issue, I tested the following code:
```
$m = new mPDF('c');
// disable compression to produce a pdf with intelligible plaintext
$m->SetCompression(false);
$m->WriteHTML("your html code");
...
myMpdfOutput($m, $filename);
```

`myMpdfOutput` is a small reimplementation of mpdf's `Output` method in "I" mode that:

1. ensure the parser is closed;
2. gets the total number of pages from mPdf;
3. sends browser headers;
4. replaces all occurrences of `{nbpg}` in the pdf with the actual number of pages.

```
	function myMpdfOutput($mpdf, $name)
{
	if ($mpdf->state < 3)
		$mpdf->Close();

	$numpages = $mpdf->docPageNumTotal();

	//We send to a browser
	header('Content-Type: application/pdf');
	if (!isset($_SERVER['HTTP_ACCEPT_ENCODING']) OR empty($_SERVER['HTTP_ACCEPT_ENCODING'])) {
		// don't use length if server using compression
		header('Content-Length: ' . strlen($this->buffer));
	}
	header('Content-disposition: inline; filename="' . $name . '"');
	header('Cache-Control: public, must-revalidate, max-age=0');
	header('Pragma: public');
	header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');
	header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT');

	echo str_replace('{nbpg}', $numpages, $mpdf->buffer);
}
```

This workaround is fragile and introduces a lot of possible inconveniences:
 * the string replacement changes the number of pages, so the returned number is incorrect;
 * the string replacement changes unrelated parts of the pdf, so you get a corrupted file;
 * the produced pdf is not compressed.

Still, it's the only solution I've found working for the simple pdf I had to produce.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
