### ISSUE TITLE
Mpdf change timezone even if timezone is set

### ISSUE THREAD

**Issue by kravcik** [mpdf/mpdf#27]
I made some step-by-step test, where is problem with timezone on production server. 

1.
Server setting timezone "Europe\Prague"
date_default_timezone_get(); //Europe/Prague

2.
Framework (Nette) setting timezone "Europe\Prague"
date_default_timezone_get(); //Europe/Prague

3.
Loading mPdf by autoload
date_default_timezone_get(); //Europe/London

4.
Comment lanes:
//if(function_exists("date_default_timezone_set")) {
	//if (ini_get("date.timezone")=="") { date_default_timezone_set("Europe/London"); }
//}
date_default_timezone_get(); //Europe/Prague

**Comment by rzds** [comment]
I have the same problem with mPDF.
Can you please explain why you need to set a default timezone inside the library?

**Comment by finwe** [comment]
I don't know the reason that the original author of the library had. This really is a bug (or better an undesirable behaviour) and entire timezone alteration by the library will be removed in the future versions.

**Comment by culunvb** [comment]
hi all, i have the same problem, create a new variable with date("Y-m-d") before i defined mpdf class, it work's fine.

maybe this help u all
thx
