### ISSUE TITLE
Time is changed when PDF is generating

### ISSUE THREAD

**Issue by 1manfactory** [mpdf/mpdf#270]
### I have this problem/would like to have this functionality
I am logging all my generating processes to keep track of errors. I came across a jump back in time when mpdf is called.

### These are mPDF and PHP versions I am using
mPDF 6.1
PHP 5.4.45

### This is a PHP code snippet I use

```
$started=date("H:i:s");
print $started."<br>\n";

require_once '../../mpdf61/mpdf.php';

$mpdf = new Mpdf();
$mpdf->WriteHTML('<p style="font-size:4em;">Started: '.$started.'</p>');
$mpdf->WriteHTML('<p style="font-size:4em;">Now: '.date("H:i:s").'</p>');
$mpdf->Output('./time.pdf');

print date("H:i:s")."<br>\n";
?>

```
This is the output on my screen:
```
19:40:30
18:40:30
```

It's the same in the attached file.
[time.pdf](https://github.com/mpdf/mpdf/files/609724/time.pdf)

And to make it worse, the process keeps it's now wrong time so even when I am finished with generating PDF files I am still on the wrong time.

**Comment by 1manfactory** [comment]
Ok. I had to fix it with setting the time zone back again immediately after including mpdf. But it's still strange.

> require_once '../../mpdf61/mpdf.php';
> date_default_timezone_set('Europe/Berlin');

**Comment by finwe** [comment]
Yes, mPDF up to 6.1 changes the timezone to prevent warnings about the timezone not being set. This is now removed in development.
