### ISSUE TITLE
Fatal error: Call to undefined function mb_internal_encoding()

### ISSUE THREAD

**Issue by baselbers** [mpdf/mpdf#272]
It seems like mPDF is depending on `php-mbstring` module. Unfortunately this is a non-default module. Would it be possible to use mPDF without having to install it?

**Comment by finwe** [comment]
No, sorry. mbstring module is crucial for working with UTF-8 input which is one of the main mPDF advantages.

**Comment by jakejackson1** [comment]
If you want to ensure your software runs on hosts that don't include MB String [I recommend the MB String Polyfill](https://github.com/symfony/polyfill-mbstring).
