### ISSUE TITLE
 background image and radius border

### ISSUE THREAD

**Issue by cretace** [mpdf/mpdf#274]
Version 6.1 (and 6.0)
Using background image and putting a radius border on it to produce a circular ring border fails at small sizes.
It works sometimes but there seems to be a minimum size - under about 12mm it draws the top and bottom quadrants and leaves out the left and right quadrants - apart from showing a very thin line.
css: 
height:14mm;
width:12mm;
padding:0;
background-size:contain;
border-radius:12mm;
background-position: center;
background-repeat: no-repeat;
border:1.5mm solid #ee00ee;
background-image: url('impath');

Don't ask me why width and height are not the same like proper css - that's what is needed to produce a circle in MPDF.

**Comment by finwe** [comment]
Please, try the last version and if the problem persist, add a new Issue with all details asked for in the Issue template, especially with a reproducible HTML/PHP code sample.
