### ISSUE TITLE
PHP7: Fatal Error with multiple "default" clauses

### ISSUE THREAD

**Issue by Ju1jan** [mpdf/mpdf#277]
Hi.
Thanks for your extension. It's helpful.
But I'd like to report about fatal error, kind of blooper in the code.

PHP Fatal error:  Switch statements may only contain one default clause in 
vendor/mpdf/mpdf/mpdf.php on line 1424

### Possible solution
Just remove one of default clause (imho, the first one should be removed) in switch statement.
It helped for me at least.

### I have this problem/would like to have this functionality
Error 500, no records in the application logs,
I got errors in apache logs.

### These are mPDF and PHP versions I am using
mPDF 5.7.2
PHP 7.0.8

### This is a PHP code snippet I use

```
<?php
Yii::$app->response->format = 'pdf';
// without this line in the Controller everything is fine
```

Thanks.

**Comment by finwe** [comment]
mPDF 5.7.2 is not fully PHP7 compatible. Please upgrade to the last version, that should fix your problem.

**Comment by Ju1jan** [comment]
Yep. It helped. Works fine. Thank you.
Sorry for bothering.

**Comment by TomasVotruba** [comment]
I look for the commit that solved this issue, to solve mine similar.
But I can't find in the huge diffs after 5.7.2, neither in issues or PR looking for "default" and "PHP 7 upgrade".

Could you link me to it? Thank you

**Comment by TomasVotruba** [comment]
Maybe this one https://github.com/franzliedke/wp-mpdf/commit/9dc489215fbd1adcb514810653a73dea71db8e99#diff-2f1f4a51a2dd3a73ca034a48a67a2320L1373 ?

**Comment by finwe** [comment]
@TomasVotruba https://github.com/mpdf/mpdf/commit/f9a374c7ea975ce8c795cec4dfd17ef55addac9c#diff-e01de6fe0cd59f869a1b31d775b88168L1383

**Comment by finwe** [comment]
the method was entirely reworked after, though, now its array key lookup instead of a switch.

**Comment by TomasVotruba** [comment]
Awesome, thanks! :+1: 

So technicaly it was a BC break - because only last `default` was applied - see https://3v4l.org/i7t4i, so `false` is always the value on non-existing format.
But you've decided to corret in a way it was probably design to work?

**Comment by finwe** [comment]
Unknown formats now throw a MpdfException.

**Comment by TomasVotruba** [comment]
The goal of instant upgrade tool is to keep BC.

For this case it looks like this:  https://github.com/rectorphp/rector/pull/842/commits/32565e128bffed7fe4d525c327d30c5c0ee81e0c#diff-c6c17b22afbf57de5b59613938c17570
