### ISSUE TITLE
PHP 7.1 errors

### ISSUE THREAD

**Issue by Zyntes** [mpdf/mpdf#278]
### I have this problem/would like to have this functionality

I  get the following errors when using with PHP 7.1 (stable):

`
PHP Warning:  Illegal string offset 'ID' in /home/user/domains/domain.com/public_html/vendor/mpdf/mpdf/classes/cssmgr.php on line 1302
`

`
PHP Warning:  Cannot assign an empty string to a string offset in /home/user/domains/domain.com/public_html/vendor/mpdf/mpdf/classes/cssmgr.php on line 1302
`

`
PHP Warning:  Illegal string offset 'LANG' in /home/user/domains/domain.com/public_html/vendor/mpdf/mpdf/classes/cssmgr.php on line 1307
`

`
PHP Warning:  Cannot assign an empty string to a string offset in /home/user/domains/domain.com/public_html/vendor/mpdf/mpdf/classes/cssmgr.php on line 1307
`

`
PHP Warning:  A non-numeric value encountered in /home/user/domains/domain.com/public_html/vendor/mpdf/mpdf/Tag.php on line 1889
`

### These are mPDF and PHP versions I am using
PHP 7.1.0
mPDF 7.0.0

**Comment by maggsweb** [comment]
Hi Zyntes
I had the same issues on 7.10, and have modified the files to prevent any errors.  I haven't fully tested my changes with all options, but have resolved the errors.  My modifies files are attached.  Changes are marked @CM 2016-12-11
Hope these help.
[cssmgr.php.txt](https://github.com/mpdf/mpdf/files/644736/cssmgr.php.txt)
[mpdf.php.txt](https://github.com/mpdf/mpdf/files/644737/mpdf.php.txt)

**Comment by maggsweb** [comment]
Zyntes
I have the same issues with 7.1.0
I modified the following files... 

[cssmgr.php.txt](https://github.com/mpdf/mpdf/files/644763/cssmgr.php.txt)
[mpdf.php.txt](https://github.com/mpdf/mpdf/files/644764/mpdf.php.txt)

all changes are commented @CM...
Hope these help.

**Comment by jakejackson1** [comment]
@maggsweb a PR with the changes you made would be more suitable.

**Comment by maggsweb** [comment]
@jakejackson1 
The 'Illegal string offset...' errors look like they have been addressed in #271 
I'll do a PR for the 'A non-numeric value...' issues

**Comment by finwe** [comment]
Created v6.1.3 from mentioned PR.

**Comment by Zyntes** [comment]
Thanks! Tested it successfully on PHP 7.1 and I have no more errors.

**Comment by Balakumar-B** [comment]
I have face failed to load PDF document 
@maggsweb

**Comment by gpsingh159** [comment]
in mpdf.php file change this
$errorlevel = error_reporting($errorlevel & ~(E_NOTICE|E_WARNING));
i fixed this issue like this.
khalsasoft
