### ISSUE TITLE
Remove elements from ToC

### ISSUE THREAD

**Issue by 1manfactory** [mpdf/mpdf#281]
I am using `h2toc` to automatically build my table of content.

How can I remove certain elements of this ToC before it is printed to page?

Let's say I have an array of heading captions which I would like to remove from the ToC like "Acknowledgement" or "Copryright"

How can I achieve this?

**Comment by 1manfactory** [comment]
Solved it myself by converting <h1> to <p class="h1a"> of all sections not to be inserted in the toc.

**Comment by umairm638** [comment]
@1manfactory how can we create custom TOC page having header and footer and some other content too in it. Also how to give correct page numbers in it when data is dynamic and we don't know where the second and third chapter will occur. Can you please guide me. Thanks

    https://stackoverflow.com/questions/45707375/insert-mpdf-toc-with-page-number-for-dynamic-data-php

**Comment by finwe** [comment]
@umairm638 Stop spamming all remotely related issues.
