### ISSUE TITLE
preg_split() expects parameter 2 to be string, array given otl.php Line: 6158

### ISSUE THREAD

**Issue by neonwired** [mpdf/mpdf#282]
Error message detected - PDF file generation aborted. preg_split() expects parameter 2 to be string, array given File: /vendor/mpdf/mpdf/classes/otl.php Line: 6158

mPDF 6.1.0

I'm getting this on one domain but not another with the same code. What can cause this?

**Comment by finwe** [comment]
What is your PHP version? What is your PHP and HTML code? What differences are there between the domains or their platforms? You know, that Issue template is not here for nothing.

**Comment by finwe** [comment]
Closing as stale.
