### ISSUE TITLE
Undesired mouseover effect on links in PDF

### ISSUE THREAD

**Issue by travelfish** [mpdf/mpdf#283]
Latest version of Chrome (Version 55.0.2883.95 (64-bit)) 
Mac OSX 10.10.5
MPDF 5.7.3

With a Chrome upgrade am now seeing an ugly yellow box appear on mouseover of all links in generated PDFs. The PDFs are fine in other browsers and native viewers, but not so hot in Chrome

I've attached a screenshot of the behaviour. It happens in new PDFs as well as ones created previously, so is Chrome related. Any thoughts on what could be causing it?

![pdfwot](https://cloud.githubusercontent.com/assets/5599626/21172637/0259e5ec-c20e-11e6-85b1-f720f8209c8f.png)

**Comment by danielhjames** [comment]
I can reproduce this issue and I think it needs fixing. My best guess is that it relates to http://mpdf.github.io/reference/html-control-tags/annotation.html

**Comment by danielhjames** [comment]
My mPDF version is 6.1.2 on Debian jessie. Seems similar to https://productforums.google.com/forum/#!topic/chrome/dSzZOneqhNc

**Comment by danielhjames** [comment]
Here is a simple test example from mPDF 6.1.2:

[yellow-box-in-chrome.pdf](https://github.com/mpdf/mpdf/files/663921/yellow-box-in-chrome.pdf)

**Comment by danielhjames** [comment]
I've reported the issue to Google and linked to this GitHub issue. Pop-ups for annotations are also oversized relative to the content. If the pop-ups were fitted to the size of the link or annotation text and in less bright colours, as in Evince, I think this would make the PDF more readable in Chrome.

**Comment by travelfish** [comment]
Right, we're having the highlighting box (as per screenshot above) appear on all linked text - only on Chrome, and didn't used to happen - and we're not using any annotations, which I guess means this is something driven from Chrome's end. 

Cheers

**Comment by danielhjames** [comment]
Because the yellow box on links looks exactly like the annotation box (please see example above) I think it likely that Chrome's PDF viewer is treating every link as an annotation, even when the document does not contain any annotations.

**Comment by travelfish** [comment]
Yes, but if you look at this PDF (made in Open Office) Chrome doesn't behave the same way. https://www.travelfish.org/sumbawa/example.pdf

**Comment by danielhjames** [comment]
Thanks for your example, it does seem to be related to mPDF then.

**Comment by jakejackson1** [comment]
If it works without any issues in Adobe Reader it's the Google Chrome PDF viewer that should be updated.

**Comment by kentct** [comment]
I had this problem as well but was able to fix it by removing the /Contents portion of the annotation generator since I don't need the yellow annotations box and can't think of any reason why I would need it.  I'm using mpdf 5.7.4.  In mpdf/mpdf.php I located this line and commented it out:
$annot .= ' /Contents '.$this->_UTF16BEtextstring($pl[4]);

**Comment by danielhjames** [comment]
Hi Kent, thanks for the workaround :-) Jake, I got no response from Google on the issue I reported, I doubt they are going to change Chrome because only PDFs made with mPDF seem to have the issue.

**Comment by morelazers** [comment]
I got here from google, I'm actually using html2pdf, started getting the unsightly yellow boxes a little while ago.

@kentct's solution was still applicable, comment out the lines that denote the '/Contents' for the annotation. 👍

**Comment by danielhjames** [comment]
Thanks Tom, please file an issue on https://github.com/spipu/html2pdf/issues and link to this issue. Looks like there is some common ancestry from FPDF? Maybe the two projects can work together, I see they have an active community with a number of pull requests pending.

**Comment by travelfish** [comment]
Thanks for the fix Kent - now I just need to go regenerate 200 pdfs ;-)

**Comment by SMissot** [comment]
I am having the same issue as described above.

Thanks for coming up with a fix Kent, unfortunately this won't work in my case since editing vendor files in production is a no-go in my environment.

**Comment by nawlbergs** [comment]
Have same issue with TcPDF 5.8.007

**Comment by WaqasBukhary** [comment]
same issue in tcpdf 6.2 , php

**Comment by jakejackson1** [comment]
@danielhjames can you link to the Google Issue you created for this issue? I wasn't able to find it when searching Chrome's support forum.

**Comment by danielhjames** [comment]
Hi Jake, I definitely reported it via Chrome feedback but it seems this is not the same thing as filing an issue at the upstream project https://bugs.chromium.org/p/chromium/issues/list

**Comment by jakejackson1** [comment]
@danielhjames the way I helped get the [Gmail PDF Viewer Encryption issue fixed](https://productforums.google.com/forum/#!topic/gmail/mwVR9ydiP-A;context-place=mydiscussions) was to [open a topic in the Chrome Help Forums](https://productforums.google.com/forum/#!forum/chrome). It took a bit of time but it happened eventually.

**Comment by marclaporte** [comment]
The yellow box on external links: indeed, I would prefer it removed.

But the yellow box has a use case for things like mouseovers. ex.: https://doc.tiki.org/PluginMouseover

Thanks!

**Comment by spipu** [comment]
merge request for https://github.com/tecnickcom/TCPDF/pull/60 for this issue

**Comment by esclim** [comment]
> Hi Jake, I definitely reported it via Chrome feedback but it seems this is not the same thing as filing an issue at the upstream project https://bugs.chromium.org/p/chromium/issues/list

Most likely: https://bugs.chromium.org/p/chromium/issues/detail?id=856331
