### ISSUE TITLE
mapping arial und helvetica to chelvetica

### ISSUE THREAD

**Issue by kaystrobach** [mpdf/mpdf#284]
### I have this problem/would like to have this functionality

normally we use arial for rendering pdfs, currently mpdf falls back to `Dejavu font`, but should fallback to `cheltica`

### These are mPDF and PHP versions I am using

6.x

### This is a HTML code snippet I use

fix should be done here, will provide a patch if you agree ...

https://github.com/mpdf/mpdf/blob/master/config_fonts.php#L38

**Comment by finwe** [comment]
Is that an erroneous behaviour or do you just want to change the configuration? In the latter case you should just override configuration locally.

I see that when installing via composer that is not a viable option, but changing default configuration in closed branch of project is a no-go.

**Comment by kaystrobach** [comment]
I use composer and it is really anoying, maybe you can change it for the next 6.x pachlevel ...

**Comment by finwe** [comment]
You can override these values in a file specified in the `_MPDF_SYSTEM_TTFONTS_CONFIG` constant. See line 1160 (or around) in mpdf.php.
