### ISSUE TITLE
Problem with embedded fonts

### ISSUE THREAD

**Issue by caraffa** [mpdf/mpdf#285]
### I have this problem

Warning: preg_replace(): Compilation failed: regular expression is too large at offset 36048 in /web/htdocs/www.gaingridltd.com/home/wp-content/themes/alpha-theme/inc/mpdf61/classes/cssmgr.php on line 209

with

/url\(data\:application\/font\-woff;charset\=utf\-8;base64,d09GAAAAGYMAA4AAAAAowAAAQAA...

### These are mPDF and PHP versions I am using

mpdf 6.1 and PHP 5.6/7.0

### This is a PHP code snippet I use

```
<?php
$mpdf = new mPDF();

$url = urldecode($_REQUEST['url']);

if (!preg_match('/^http:\/\/www\.gaingridltd\.com/', $url)) {
  die("Access denied");
}

$opts = array(
  'http'=>array(
    'header'=>"Cookie: {$_SERVER['HTTP_COOKIE']}",
  )
);

$context = stream_context_create($opts);
$html = file_get_contents($url, false, $context);
$mpdf = new mPDF();

$mpdf->useSubstitutions = true; // optional - just as an example
$mpdf->SetHeader($url . "\n\n" . 'Page {PAGENO}');  // optional - just as an example
$mpdf->CSSselectMedia='mpdf'; // assuming you used this in the document header
$mpdf->setBasePath($url);
$mpdf->WriteHTML($html);

$mpdf->Output();

```

### This is a HTML code snippet I use

```

```

Apparently cssmgr has problems dealing with embedded fonts

**Comment by finwe** [comment]
This is not a problem of embedded fonts as such, but mPDF cannot process so large base64 data.

Anyway, closing as stale. Will gladly reopen with reproducible example to at least gracefully ignore this, if still applicable on current version.
