### ISSUE TITLE
Question: mpdf vs Prince. Diferencies

### ISSUE THREAD

**Issue by colomet** [mpdf/mpdf#286]
I would like to ask the mayor diferences between mPDF and [Prince](https://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=7&cad=rja&uact=8&ved=0ahUKEwjk4Ky-5_bQAhVFChoKHQvcDKwQFghRMAY&url=https%3A%2F%2Fwww.princexml.com%2F&usg=AFQjCNFrGegRSm5HqSGWQFk3tWH7Qs1cbA&sig2=CeT-uW0rUqfH7LD5iojg3w). Thanks

**Comment by jakejackson1** [comment]
That's like comparing apples and oranges. For starters, mPDF is open source, while Prince is a commercial application. mPDF is designed for the web and can run where ever PHP is, Prince needs to be installed on your machine.

**Comment by colomet** [comment]
I would like to know from the end user point of view. With the possibility of editing the CSS of the pdf. 

Not about the technical infraestructure or the freedom of an open source.

thanks for your time.
