### ISSUE TITLE
Warning: preg_replace(): Compilation failed: regular expression is too large at offset 36048 in /mpdf/classes/cssmgr.php on line 209

### ISSUE THREAD

**Issue by crazyserb** [mpdf/mpdf#287]
I am getting this error:

Warning: preg_replace(): Compilation failed: regular expression is too large at offset 36048 in /mpdf/classes/cssmgr.php on line 209

Any idea what might be causing this? As it just popped up all of a sudden, as we haven't changed anything and everything worked just fine up until now.

Is this related to any sort of PHP.ini settings or something? Because that might have changed in the background, possibly.

**Comment by finwe** [comment]
What is your PHP version? What is your PHP and HTML code? What differences are there between the domains or their platforms? You know, that Issue template is not here for nothing.

**Comment by finwe** [comment]
And yes, it can be caused by `pcre.backtrack_limit` PHP INI setting. Especially when you try to pass a HTML chunk larger than this value.

**Comment by crazyserb** [comment]
PHP 5.6, mPDF 6.1.3 and 7 (in 7 I get Warning: preg_replace(): Compilation failed: regular expression is too large at offset 36048 in /vendor/mpdf/mpdf/src/CssManager.php on line 233) so same thing, I assume.

and most of the PHP/HTML code is quite long and irrelevant, but this is the mPDF part:

	$mpdf = new \Mpdf\Mpdf();
	$mpdf->CSSselectMedia='mpdf';
	$mpdf->WriteHTML($html);

	$content = $mpdf->Output('', 'S');
	$content = chunk_split(base64_encode($content));

// Put the html into a temporary file
	$tmpfile = time().'.html';
	file_put_contents($tmpfile, $excel);

// Read the contents of the file into PHPExcel Reader class
	$reader = new PHPExcel_Reader_HTML;
	$objPHPExcel = $reader->load($tmpfile);

// Pass to writer and output as needed
	header('Content-Type: application/vnd.ms-excel');
	header('Content-Disposition: attachment;filename="'.$filename.'.xls"');
	header('Cache-Control: max-age=0');
	$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
	$excel_filename = 'orders/'.$filename.'.xls';
	$objWriter->save($excel_filename);
	fclose($tmpfile);
	unlink($tmpfile);

	$mpdf->Output('orders/'.$filename.'.pdf','F'); //F, I


That's the gist of it... 

I also checked the backtrack_limit setting, tried increasing it by a lot and that didn't make any difference.

**Comment by crazyserb** [comment]
Yeah, definitely something in that CSSManager.php in that block around line 233 interfering with the HTML (or vice versa) that I pass onto it... because as soon as I comment that last preg_replace() block out, everything starts working properly, just fine. Hmm...

**Comment by glensc** [comment]
no really solvable by increasing runtime settings: https://stackoverflow.com/a/31173022/2314626

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
