### ISSUE TITLE
Php 7.1 is not compatible. Math expressions.

### ISSUE THREAD

**Issue by StalkAlex** [mpdf/mpdf#288]
No, MPDF is not compatible with PHP 7.1. There are a lot of expressions like 

```php
f (($setwidth + $currblk['margin_left'] + $currblk['margin_right'] + $bdl + $pdl + $bdr + $pdr) > $maxw || ($maxw - ($currblk['margin_right'] + $currblk['margin_left'] + $bdl + $pdl + $bdr + $pdr)) < (2 * $this->mpdf->GetCharWidth('W', false))) {
```
and in case where variable is not number it will throw incompatible types exception. In this example $pdr and $pdl can be 0 or "auto".

**Comment by StalkAlex** [comment]
Temp solution as usual 
`error_reporting(E_ERROR);`

**Comment by finwe** [comment]
Feel free to propose a Pull Request with a fix and an appropriate unit test. It is nearly impossible to find all these expressions without appropriate code samples hitting these code branches.

**Comment by StalkAlex** [comment]
Ok, I'll do my best, but there is nothing special about this problem, it can be done just taking and converting any html page.

**Comment by finwe** [comment]
I wouldn't be too hasty with _any_ HTML page - all pages in examples repository are being converted just fine without any notices, warnings or exceptions with PHP 7.1.

**Comment by StalkAlex** [comment]
Ok, here's example
```html
<html>
    <head>
    </head>
    <body>
<ul>
	<li>aa</li>
</ul>
</body>
</html>
```

**Comment by finwe** [comment]
No errors. Are we both talking about the latest `development` branch commit? There is no planned PHP 7.1 support for 6.x versions.

**Comment by StalkAlex** [comment]
No, I'm talking about last stable realease.

**Comment by finwe** [comment]
Oh. Then, no, there is no planned PHP 7.1 support for the last stable release.

**Comment by StalkAlex** [comment]
Ok, thanks for clarification!
