### ISSUE TITLE
Base path for images

### ISSUE THREAD

**Issue by StalkAlex** [mpdf/mpdf#289]
Is there any way to specify **image** base path where it should look during pdf generation?

**Comment by finwe** [comment]
Does [SetBasePath()](https://mpdf.github.io/reference/mpdf-functions/setbasepath.html) help?

**Comment by StalkAlex** [comment]
Yep, that's what I needed. It works  in this case when base path is `/some/dir ` and  link is `<img src="image.jpg"/>` , but we have a little bit different situation. Base is the same, but links are `<img src="/subdir/image.jpg">. In this case it's not working unfortunately.

**Comment by StalkAlex** [comment]
Want to clarify situation. If base path is `http://domain.com/dir1/dir2` and image path is `/dir3/image.jpg`, MPDF interpret it in Linux way from root. So final path become `http://domain.com/dir3/image.jpg`, but it's not correct way, because in HTML `/dir3/image.jpg` is still relative path. How can I make MPDF to treat links in HTML way?

**Comment by finwe** [comment]
What you are describing is correct path handling. Even in (plain) HTTP/HTML, paths beginning with `/` are absolute. Thus link `/dir3/image.jpg` on page `http://domain.com/dir1/dir2/page.html` will lead to `http://domain.com/dir3/image.jpg`.

There is no other way that I know of to make mPDF behave the way you need.

**Comment by StalkAlex** [comment]
Sorry, my fault, you're correct. We have https with certificates access only, so in case of absolute url it can't get image due to simple http request?

**Comment by finwe** [comment]
That's possible.

**Comment by StalkAlex** [comment]
Any chance you could give a hint?

**Comment by finwe** [comment]
No idea, sorry. The safest way to handle images for PDFs with mPDF was to use base64 data as src, but that is, I guess, out of question when you want to use the same HTML for PDF and browser.

**Comment by StalkAlex** [comment]
Why you answered that it was possible then?

**Comment by finwe** [comment]
I meant is is possible that the image cannot be fetched due to simple http request as you hinted. Didn't mean anything else by that.

**Comment by rgpublic** [comment]
Simple solution for anyone wondering how to solve this after all these years. Simply subclass MPDF:

```
class MyPDF extends \Mpdf\Mpdf {

    public function GetFullPath(&$path, $basepath = '') {
        if (substr($path,0,1)=='/') $path=substr($path,1);
        return parent::GetFullPath($path, $basepath);
    }

}
```
