### ISSUE TITLE
Can't find PDF examples from previous mPDF website

### ISSUE THREAD

**Issue by baselbers** [mpdf/mpdf#290]
Do you still have the (invoice) [examples](http://mpdf1.com/manual/index.php?tid=366)? Can't find them in [GitHub documentation page](https://mpdf.github.io).

**Comment by finwe** [comment]
There is a separate [examples repository](https://github.com/mpdf/mpdf-examples). You can find an [invoice example](https://github.com/mpdf/mpdf-examples/blob/development/example34_invoice_example.php) there.

**Comment by baselbers** [comment]
Thanks for your quick answer!
