### ISSUE TITLE
mpdf duplex printing issue.

### ISSUE THREAD

**Issue by mkhalid20** [mpdf/mpdf#292]
### I have this problem/would like to have this functionality
I am generating pdf using mpdf library. When i print this pdf it goes duplex side either i uncheck the printing option in printer settings as well. can anyone help me?

### This is a PHP code snippet I use
    $mpdf = new mPDF('','A4', '12', '', 0, 0, 5, 10, 9, 9);
    $mpdf->mirrorMargins  = true;
    $mpdf->SetDisplayMode('fullpage');
    $mpdf->autoLangToFont = true;
    //$mpdf->defaultPageNumStyle = 'arabic-indic';$mpdf->debug = true;
    $mpdf->watermark_font = 'DejaVuSansCondensed';
    $mpdf->showWatermarkText = false;
    
    $mpdf->SetHTMLFooter('<table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt; color: #000000; font-weight: bold; font-style: italic;">
    <tr style="border-top:2pt solid black;">
    <td width="33%"><span style="font-weight: bold; font-style: italic;">&nbsp;</span></td>
    <td width="33%" align="center" style="font-weight: bold; font-style: italic;">&nbsp;</td>
    <td width="33%" style="text-align: right; ">{PAGENO}/{nbpg}</td>
    </tr></table>');  // Note that the second parameter is optional : default = 'O' for ODD

	$mpdf->SetHTMLFooter('<table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt; color: #000000; font-weight: bold; font-style: italic;">
    <tr style="border-top:2pt solid black;">
    <td width="33%"><span style="font-weight: bold; font-style: italic;">&nbsp;</span></td>
    <td width="33%" align="center" style="font-weight: bold; font-style: italic;">&nbsp;</td>
    <td width="33%" style="text-align: right; ">{PAGENO}/{nbpg}</td>
    </tr></table>', 'E');

    $mpdf->WriteHTML($html);

**Comment by cmllr** [comment]
I'm facing quite the same issue, but setting `mirrorMargings` to `false` seems to fix the issue

**Comment by hituro** [comment]
Enabling missorMargins writes the following to the PDF

```/Duplex /DuplexFlipLongEdge```

This is supposed to only set the default duplex orientation, but actually overrides the printer duplex settings.

For some reason MetadataWriter.php actually has a line to set ShortEdge flip for portrait, but it has always been commented out. I think this is a bug.

```
			if ($this->mpdf->mirrorMargins && !$this->mpdf->PDFA && !$this->mpdf->PDFX) {
				// if ($this->mpdf->DefOrientation=='P') $this->writer->write('/Duplex /DuplexFlipShortEdge');
				$this->writer->write('/Duplex /DuplexFlipLongEdge'); // PDF v1.7+
			}
```

I had the same problem trying to print a booklet from Acrobat on a document with mirrorMargins, and this duplex setting overrides Acrobat's settings and makes it important. Changing the PDF to have /DuplexFlipShortEdge fixed the issue.

**Comment by finwe** [comment]
Closing as outdated by #292
