### ISSUE TITLE
Output D (Donwload) not working

### ISSUE THREAD

**Issue by werdlv** [mpdf/mpdf#295]
### I have this problem

I want to force PDF download but passing `D` as destination parameter to `Output()` method acts the same as `I` (output in browser).

It works as expected using TCPDF.

### These are mPDF and PHP versions I am using

mPDF - `dev-development` installed using Composer
PHP - `7.0.14`

### This is a PHP code snippet I use

```
<?php

use Mpdf\Mpdf;
use Mpdf\Output\Destination;

$pdf = new Mpdf();
$html = '...';
$pdf->writeHTML($html);
$pdf->Output('file.pdf', Destination::DOWNLOAD);
die;
```

**Comment by finwe** [comment]
This code works for me, albeit the file is being downloaded with an incorrect filename. Can you please list response headers you are getting from the HTTP request?

**Comment by finwe** [comment]
Oh, I see now Chrome does this as well as IE11. I guess their PDF viewers are so "smart" they override standard HTTP header set. Didn't find a way to bypass it except for disabling the viewer on the user side in browser preferences. Firefox works just fine.

Anyway, I am closing this as this seems not to be a mPDF issue - the headers for download are specified correctly in the response.

**Comment by werdlv** [comment]
@finwe I would say it's mPDF issue because it works fine using stable version 6.*

**Comment by finwe** [comment]
Oh, you're right. Fixed in development now, thanks for the catch.

**Comment by dhermawan215** [comment]
i am using mpdf version 8.0, the Output "D" already to use
