### ISSUE TITLE
Method SetBasePath has incorrect condition to check whether is server HTTPS or not

### ISSUE THREAD

**Issue by Sofiosko** [mpdf/mpdf#297]
### method SetBasePath has incorrect condition to check whether is server https or not. isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] should also have clause if $_SERVER['HTTPS'] containts "on" or "off"

```
<?php
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] && strtolower($_SERVER['HTTPS']) == 'on') {
    $currpath = 'https://' . $host . $currentPath . '/';
} else {
    $currpath = 'http://' . $host . $currentPath . '/';
}
```

**Comment by finwe** [comment]
This works, except for [*Note that when using ISAPI with IIS, the value will be off if the request was not made through the HTTPS protocol.*](https://secure.php.net/manual/en/reserved.variables.server.php)

Marking as an enhancement for 7.x, and the actual condition will be slightly different (`!== 'off'`)

**Comment by Sofiosko** [comment]
Thank you very much for clarification and quick response.
