### ISSUE TITLE
Composer post-install-cmd fails to set permissions properly on temp folders

### ISSUE THREAD

**Issue by dxdc** [mpdf/mpdf#298]
Seems the `post-install-cmd` scripts fail to work, perhaps because we need relative references here?

https://github.com/mpdf/mpdf/blob/master/composer.json#L46
```json
	"scripts": {
		"post-install-cmd": [
			"php -r \"chmod('./ttfontdata', 0777);\"",
			"php -r \"chmod('./tmp', 0777);\"",
			"php -r \"chmod('./graph_cache', 0777);\""
		]
	}
```

When using `composer require mpdf/mpdf` and a more strict umask, these post-install scripts are not correctly applied.

Also, I would suggest these should be set to 0775 instead of 0777 by default.

Also the `php -r` seems unnecessary. Perhaps, something like the below version would work. Let me know if this is suitable I can submit a PR:

```json
	"scripts": {
		"post-install-cmd": [
			"chmod 755 mpdf/ttfontdata",
			"chmod 755 mpdf/tmp",
			"chmod 755 mpdf/graph_cache"
		]
	}
```

**Comment by edgaraafelix** [comment]
When will this be fixed? 

We are getting "failed to open stream: Permission denied" for every file that mPDF tries to create on these temp folders.

(with the problem it's not possible to continue using mPDF).

**Comment by dxdc** [comment]
@edgaraafelix you can just chmod these folders manually in the meantime, but I agree, it should be fixed in the package.

**Comment by edgaraafelix** [comment]
Yes, I know that. But I don't want to do that when deploying our code in production.

**Comment by dxdc** [comment]
Agreed...

**Comment by finwe** [comment]
@edgaraafelix Set a custom temporary files directory you have in your control using MPDF configuration constants (or config parameters for `7.x` branch) See [Folders for temporary files](https://mpdf.github.io/installation-setup/folders-for-temporary-files.html) in the manual.

@dxdc `chmod` calls through PHP are necessary for the post install script to run and not to fail on Windows. `777` was decided to make this "fool proof". Advanced users can surely tweak this to their liking.

Generally, in mPDF `7.x` there may be no predefined temporary directories and the user may have to set the custom writable one manually.

**Comment by dxdc** [comment]
@finwe thanks for the clarification. I've see the link you shared regarding folders, and agree it's a more robust solution.

In the meantime, you might consider tweaking the `post-install-cmd` so it will work on Windows/Linux properly. Perhaps something like the following? I think the current directory is probably not being reported properly when using `composer` install.

```
	"scripts": {
		"post-install-cmd": [
			"php -r \"chmod( __DIR__ . '/mpdf/ttfontdata', 0777);\"",
			"php -r \"chmod( __DIR__ . '/mpdf/tmp', 0777);\"",
			"php -r \"chmod( __DIR__ . '/mpdf/graph_cache', 0777);\""
		]
	}
```

**Comment by edgaraafelix** [comment]
@finwe In the meantime I will use a custom temporary folder. Anyway, you should tweak the post-install script like @dxdc suggested.

**Comment by finwe** [comment]
I am closing this - when unable to set correct permissions inside vendor directory, setting custom temporary directory is possible and recommended. 

That will also be possible and strongly advised in the future versions.
