### ISSUE TITLE
PHP 7.1 issues with mpdf 6.1.3

### ISSUE THREAD

**Issue by heldchen** [mpdf/mpdf#300]
### I have this problem/would like to have this functionality
using mpdf 6.1.3 with php 7.1 produces several of the following warnings:
```
WARNING: Illegal string offset 'html' (/var/www/shared/lib/mpdf/mpdf.php:14991)
WARNING: Illegal string offset 'h' (/var/www/shared/lib/mpdf/mpdf.php:14992)
WARNING: Illegal string offset 'html' (/var/www/shared/lib/mpdf/mpdf.php:15139)
WARNING: Illegal string offset 'html' (/var/www/shared/lib/mpdf/mpdf.php:15055)
WARNING: Illegal string offset 'h' (/var/www/shared/lib/mpdf/mpdf.php:15056)
WARNING: A non-numeric value encountered (/var/www/shared/lib/mpdf/mpdf.php:30648)
```
this seems to be related to headers/footers, the generated pdf has "0" outputted in place of the actual headers. the same html can be successfully rendered to pdf with php 7.0.x using the same mpdf version

### These are mPDF and PHP versions I am using
mpdf 6.1.3
php 7.1.0-5

the warning messages are similar to what was reported in #278

**Comment by heldchen** [comment]
the illegal string warnings can be fixed easily by adding checks as done in the other compatibility fixed, for example on line 14991:

```
			if ($Hhtml) {
			    if (empty($this->HTMLHeader)) $this->HTMLHeader = array();
				$this->HTMLHeader['html'] = $Hhtml;
				$this->HTMLHeader['h'] = $height;
			} else {
				$this->HTMLHeader = '';
			}
```

the "A non-numeric value encountered" warning is in the function `ConvertSize`. this function tries to multiply / add float values to strings. in my case, `$size` seems to be either `` (empty string) or `n`, both causing the problems. I think `$numsize = floatval($size);` and use this variable in the different calculations could fix the problem... some calculations still do not make sense then tho. for example for `$size == 'x-large'` the resulting size would be `0`. maybe the intention was to use `$this->default_font_size` as the base size in such cases? either way this function  looks quite broken (not only for php 7.1). 

[here](https://github.com/mpdf/mpdf/files/690481/issue300-patch.txt) is an "experimental" patch based on tag 6.1.3. this fixes my problems and, improves the `ConvertSize` function a bit.

**Comment by finwe** [comment]
6.* will not fully support PHP 7.1 - additional compatibility fixes will not be accepted anymore. 

All PHP 7.1 fixes are to be directed to current 7.x development branch. Many PHP 7.1 related errors are already fixed in `development`.

**Comment by bluemanos** [comment]
@finwe do you know when mpdf 7.* will be released?

**Comment by finwe** [comment]
After all issues in its milestone are resolved. 

There is no ETA, I get to working on mPDF only when time allows and there are no other serious contributors.

**Comment by fmasa** [comment]
@finwe Would you consider at least tagging something like `v7.0.0-alpha1`? There is no need to rush for final release, though having a tag as version of dependency would be neat :smile:

**Comment by finwe** [comment]
@fmasa You can always use `dev-development` or `7.0-dev` (which is its branch alias).

**Comment by fmasa** [comment]
@finwe Sure, but the advantage of tag is that when i pull `v7.0.0-alpha1`, I'll always get the same version. `dev-development` may differ.

**Comment by finwe** [comment]
Then use a hash with git tag (current 7.0-dev below):

```
"require": {
    "mpdf/mpdf": "7.0-dev#042f2d2"
}
```

I do not want to bloat the repo with alpha tags as that could mean I would have to create a tag for almost every new commit.

**Comment by fmasa** [comment]
@finwe I know about that one, but still prefer tags :grin: But I understand your point of view. Thanks anyway.

**Comment by gpsingh159** [comment]
in mpdf.php file change this
$errorlevel = error_reporting($errorlevel & ~(E_NOTICE|E_WARNING));
i fixed this issue like this.
khalsasoft
