### ISSUE TITLE
compress.php not working on v 6.1

### ISSUE THREAD

**Issue by diegopego86** [mpdf/mpdf#306]
I've been trying to generate a compressed version of the library using compress.php but the compressed file is corrupt.

I tried unchecking only ENCRYPTION, IMPORTS, PROGRESS-BAR and OTL and i get the following:

**Parse error: syntax error, unexpected 'else' (T_ELSE) in ../Mpdf.php on line 16314**

How you can check this. Cheers

**Comment by finwe** [comment]
`compress.php` is "deprecated" and is removed in current development version. You can try to fix the compressed file manually or I'd recommend not using the compress script.
