### ISSUE TITLE
Which (vendor) dependencies needed on live site?

### ISSUE THREAD

**Issue by baselbers** [mpdf/mpdf#307]
Some files like mpdf/vendor/webmozart/assert/appveyor.yml showing up on WordPress "virusscan" plugins.

Which libraries/dependencies are only for development? Can I delete all dependencies for live site except `setasign`?

**Comment by jakejackson1** [comment]
Composer is used to manage dependencies and correctly includes production and development packages. So running `composer install --no-dev` after cloning this repo will give you a production-ready build. [Refer to the composer docs for more details](https://getcomposer.org/doc/03-cli.md#install).
