### ISSUE TITLE
Compress doesn't work

### ISSUE THREAD

**Issue by franko108** [mpdf/mpdf#310]
### I have this problem/would like to have this functionality
Compress mpdf
### These are mPDF and PHP versions I am using
mPDF v.7
PHP 5.6.29

Hello, 
When creating a new mpdf.php via script compress.php (default settings - enabled  HTML-CSS, TABLES, IMAGES-CORE , IMAGES-BMP) I get error:
`Parse error: syntax error, unexpected 'else' (T_ELSE) in /var/www/html/app/application/libraries/mpdf/vendor/mpdf/mpdf/mpdf.php on line 3052`
Looking at the line of file, there are several non closed brackets before else, also, below there are `else` statement, and afterwards `elseif` which throws another error.

mPDF library is being used with Codeigniter 3, but, without compress, it works properly.

**Comment by finwe** [comment]
See https://github.com/mpdf/mpdf/issues/306
