### ISSUE TITLE
html entities in image src are left as is

### ISSUE THREAD

**Issue by bkdotcom** [mpdf/mpdf#313]
### I have this problem/would like to have this functionality

`<img src="http://someurl.com/path?param1=foo&amp;param2=bar" />`

html entities are never decoded ([html_entity_decode()](http://php.net/manual/en/function.html-entity-decode.php)) on the url

mpdf literally tries to fetch "http://someurl.com/path?param1=foo&amp;param2=bar" rather than "http://someurl.com/path?param1=foo&param2=bar"

### These are mPDF and PHP versions I am using
mpdf 5.3
(cursory look at latest source indicates issue still exist)

**Comment by rgpublic** [comment]
Still happens for me. This is especially problematic since PHP's DOMDocument automatically creates entities when settings an image's SRC attribute.

**Comment by finwe** [comment]
@rgpublic With which version? Just tested with 8.0.13 and with code

    $mpdf->WriteHTML('<img src="http://localhost/?foo=bar&amp;baz=bat">');

the line in access log is 

    127.0.0.1 - - [10/Sep/2021:13:59:14 +0200] "GET /?foo=bar&baz=bat HTTP/1.1" 200 101589 "-" "-"

So I take this as solved.

**Comment by rgpublic** [comment]
@finwe Um, I'm on 8.0.12, but I thought more about sth. like this:
```
$mpdf->WriteHTML('<img src="%C3%BC.jpg">');
```
and a file called "ü.jpg". Does this also work for you?

**Comment by finwe** [comment]
OK, reopening. Could have mentioned this exact example in the first place :)

**Comment by rgpublic** [comment]
@finwe: You are right, of course. Should have explicitly mentioned this. Sorry!

**Comment by finwe** [comment]
Reference https://github.com/mpdf/mpdf/issues/868
