### ISSUE TITLE
Broken URL in documentation.

### ISSUE THREAD

**Issue by KhArtNJava** [mpdf/mpdf#316]
Hello.
In the bottom of the page https://mpdf.github.io/reference/mpdf-functions/setprotection.html there is broken link with text 
See Also
**SetUserRights()**
It has broken link to https://mpdf.github.io/reference/mpdf-functions/indexaf79.html?tid=193 (404 page).

**Comment by Klap-in** [comment]
(Minor note: documentation is actually maintained at https://github.com/mpdf/mpdf.github.io)

**Comment by finwe** [comment]
Thanks, linked method was deprecated and archived. Fixed in https://github.com/mpdf/mpdf.github.io/commit/28cfa2a4e79c7f67bcb7337dcaebe0944de37e18
