### ISSUE TITLE
Images with Relative Paths That are Pointing to Root Do not Display

### ISSUE THREAD

**Issue by matt-elliott** [mpdf/mpdf#327]
Hello, I am using this tool to render a pdf of owned products you mark as such on the site and then click a "render to pdf" button. Then the pdf of the images of the products you own is generated.

My issue is if I use a relative path that points back to the root folder of our site (ie: /includes/images/products/product_1.jpg) the image does not display (get a red x in a box). Funny thing is if I render the page as html the images will show or if I remove the first forward slash (ie: includes/images/products/product_1.jpg) it behaves as if the forward slash is there, goes to the root and finds the correct path to the image.

Looking to understand why this is - it seems backwards from how paths are usually handled.

Thanks!

**Comment by finwe** [comment]
mPDF supports pure filesystem paths for assets, therefore has to take that into consideration.

Furthemore, eg. when running in console, it has no knowledge about the HTTP root whatsoever.

So the path handling is a combination of approaches.

There is the [SetBasePath()][1] method with which you can alter path handling, eg. with setting your domain.

[1]:https://mpdf.github.io/reference/mpdf-functions/setbasepath.html

**Comment by matt-elliott** [comment]
Thanks finwe - that ended up being my solution as well. Thanks for the explanation about the path handling - it helps I have something to tell the boss.
