### ISSUE TITLE
Undefined offset in cssmgr.php on line 1174

### ISSUE THREAD

**Issue by sachilaRanawaka** [mpdf/mpdf#329]
while i am creating pdf template i came across this error. 

> Notice:  Undefined offset: -1 in /var/www/html/services/helpers/mpdf/classes/cssmgr.php on line 1174

is this meaning i have a error in my css file.?

These are mPDF and PHP versions I am using

php - version 5.5.9
mpdf - version 6.0

**Comment by Klap-in** [comment]
This happens at this line: https://github.com/mpdf/mpdf/blob/v6.0.0/classes/cssmgr.php#L1174

Do mpdf 6.1 and development version 7 reproduces this as well?
Do you have a PHP/html snippet to let others reproduce this?

**Comment by sachilaRanawaka** [comment]
i only tried this on 6.0 version.

**Comment by sachilaRanawaka** [comment]
i only tried this on version 6.0

**Comment by finwe** [comment]
Please post a CSS/HTML snippet which causes this. It is likely caused by some invalid markup.

**Comment by finwe** [comment]
Closing as stale. Feel free to reopen with additional information.

**Comment by mgatto00** [comment]
Good Morning.

I'm having this same error.

I'm uploading the font for analize
[variavel.zip](https://github.com/mpdf/mpdf/files/964436/variavel.zip)

ps. sory for bad english

**Comment by Klap-in** [comment]
Which version of mPDF do you use?
Eventually you could test the development version (version 7) to see if the issue is already solved?

**Comment by mgatto00** [comment]
I'm using version 6.1.3
After upgrading to dev-master the problem continues to occur.
"8 - Undefined offset: -1 in /var/www/html/systems/bootstrap/mpdf/vendor/mpdf/mpdf/src/CssManager.php on line 1372"

**Comment by Klap-in** [comment]
Do you have the html that is fed into mPDF?

**Comment by Klap-in** [comment]
Or could you please try to make an minimal example that shows this behaviour as well?
