### ISSUE TITLE
font issue with autoLangToFont enabled

### ISSUE THREAD

**Issue by wingchiutong** [mpdf/mpdf#330]
Hello,

I am having issue with the font when enabling the parameter - autoLangToFont.

I am using mpdf version 6.

If I set autoLangToFont to false, then the font use would follow my CSS - "noto sans", and "open sans".

But when I set autoLangToFont to true, the "noto sans" and "open sans: will be ignored, and being replaced with something else.

Any idea why this is happening? I am trying to support Chinese character in this case.

Here's the code on PHP side.

```
<?php
    // adjust the POST header
if(isset($_SERVER['CONTENT_TYPE']) AND stripos($_SERVER["CONTENT_TYPE"], "application/json") === 0) {
	$_POST = json_decode(file_get_contents("php://input"), true);
}

$inputJsonHtml = $_POST['data'];
$htmlData = json_decode($inputJsonHtml);

include("mpdf/mpdf.php");
$mpdf=new mPDF('+aCJK','A4','','',15,10,16,10,10,10);//A4 page in portrait for landscape add -L.
$stylesheet = file_get_contents('css/pdf.css'); // external css
$mpdf->autoLangToFont = true; // required to display Chinese characters
$mpdf->allow_charset_conversion = false;
$mpdf->WriteHTML($stylesheet,1);
$mpdf->SetDisplayMode('fullpage');
ob_start();
?>
<?php
echo $htmlData;

//This is your php page ?>
<?php
$html = ob_get_contents();
ob_end_clean();
$mpdf->WriteHTML($html);
$mpdf->Output();
exit;
```

Thank you so much for anyone's help on this.

**Comment by ziaongit** [comment]
Hi Can you please check my code. I can not save Chinese to pdf

**Comment by finwe** [comment]
Closing as stale and missing a proper code example. If appropriate, feel free to create a new issue for the last mPDF version according to current contribution guidelines.
