### ISSUE TITLE
fail on require

### ISSUE THREAD

**Issue by daddyy** [mpdf/mpdf#334]
when I using autoload, and i'm trying print pdf under 5.6, there is an issue for 
require_once(): Failed opening required '/var/www/engine/libs/mpdf/classes/../MpdfException.php' (include_path='.:/usr/share/php')

File: .../libs/mpdf/vendor/mpdf/mpdf/classes/indic.php:3
3:    require_once __DIR__ . '/../MpdfException.php';

my engine is on symlink

**Comment by finwe** [comment]
And is there a /var/www/engine/libs/mpdf/MpdfException.php file? Has it correct file permissions?

**Comment by daddyy** [comment]
This fail is realy curious.
I've got two same wildcars on nginx to projects on php-fpm (5,6 and 7) for subdomains.
projects are on /var/www/projects/$project
engine is in /var/www/engine/ and is linked to $project dir
When I'm calling from nginx and socket for 5.6  without subdomain on project, everythink is working, when I use subdomain i ve'got this fail, maybe the problem is on this relative call.

**Comment by finwe** [comment]
Anyway, closing as not related to MPDF.

**Comment by daddyy** [comment]
oh now i see
require_once(): Failed opening required '/var/www/engine/libs/mpdf/**classes**/../MpdfException.php' (include_path='.:/usr/share/php')
the right path on without **classes**
