### ISSUE TITLE
Arabic font issue

### ISSUE THREAD

**Issue by umairali** [mpdf/mpdf#335]
Arabic font not connected and its showing like this

![captdddure](https://cloud.githubusercontent.com/assets/5318005/23338065/39f0cd72-fc1a-11e6-9847-6456efe60218.PNG)

The right word is
الإسم

**Comment by umairali** [comment]
To fix this issue with just add 2 new parameters in fonts array

```
'useOTL' => 0xFF,
'useKashida' => 75,
```

```
 'arabic-font' => [
            'R'  => 'arabic-font.ttf',    // regular font
            'B'  => 'arabic-font.ttf',          // optional: bold font
            'I'  => 'arabic-font-Light.ttf',    // optional: italic font
            'BI' => 'arabic-font.ttf',           // optional: bold-italic font
            'useOTL' => 0xFF,
            'useKashida' => 75,
        ]
```

**Comment by finwe** [comment]
Thanks. Will look into it. I've reopened the old issue, so I will close this one.

**Comment by pradeepnew** [comment]
Its working fine in magento2.2 but not working in magento2.3.0
If I have added 'useOTL' => 0xFF then its showing error. Anyone suggest solution.

**Comment by Klap-in** [comment]
@pradeepnew  Please, reproduce your case with a small as possible case. If you found a small example case you can best open a new issue. Please share in this new issue the instantiation of the mpdf library and the exact minimal html example. 
(See for examples of test cases: https://github.com/mpdf/mpdf/tree/development/tests)

Without real example it is not possible to reproduce your case, or even expand our test suite to prevent it in the future.
