### ISSUE TITLE
OverWrite Function Not Working

### ISSUE THREAD

**Issue by timyounes** [mpdf/mpdf#336]
I am using MPDF library for creating and manipulating PDF files and I want to replace specific string in the existing pdf file but the OverWrite function is not working it returned corrupted pdf output. What would I do to fix this?

**Comment by Klap-in** [comment]
Please provide an example php/html to reproduce this behaviour.

**Comment by timyounes** [comment]
I have existing PDF file and i want to replace a text inside that PDF file I already fix the corrupted output but the text inside the PDF file that I want to replace is not replacing

**Comment by finwe** [comment]
Closing as stale and possible duplicate of #268
