### ISSUE TITLE
Undefined index in Tag.php

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#345]
### I have this problem/would like to have this functionality

    ErrorException in Tag.php line 2005:
    Undefined index: current

### These are mPDF and PHP versions I am using

dev-development

### This is a HTML code snippet I use

```
<p style="right:16mm; bottom:4mm; font-size:7pt; line-height:14pt; position: absolute; text-align:right">Some text here</p>
```

**Comment by jbrooksuk** [comment]
> Curious. Created #345, thanks for reporting. Does that happen with the HTML snippet above?

@finwe it happens with the same setup. I've updated to use the `Mpdf\Mpdf` namespace and immediately got that error, even removing all the setup code.

**Comment by jbrooksuk** [comment]
Ah, specifically it fails with:

```php
$mpdf->AddPage('', '', '', '', '', '16', '16', '12.7', '12.7', '', '', '', '', '', '', 1, 0, 1, 0);
```

Which I assume is because something has failed?

**Comment by finwe** [comment]
@jbrooksuk I am unable to reproduce this. Can you please provide a [MVCE](http://stackoverflow.com/help/mcve)?

**Comment by jbrooksuk** [comment]
I'm just setting up Mpdf, adding a page and it fails immediately.

**Comment by finwe** [comment]
That is not a MVCE. Besides, works for me. using PHP 7.1.2. What exact revision of mPDF are you using?

**Comment by finwe** [comment]
Closing. Feel free to reopen with additional information.

**Comment by crarau** [comment]
I'm getting this issue with the 7.0.3 version. I had to revert back to 6.*. I tried to debug the issue but unable to figure out what's going on. My generated PDF is quite complicated. I'm tried to reproduce it using a simpler HTML.

**Comment by finwe** [comment]
7.0.2 was OK or not?

**Comment by crarau** [comment]
I upgraded directly from 6. I’ll give it a try.
