### ISSUE TITLE
Load custom fonts

### ISSUE THREAD

**Issue by jbrooksuk** [mpdf/mpdf#347]
I'm trying to load custom fonts in the `development` branch but it's not working.

Here is my code:

```php
$mpdf = new Mpdf([
    'fontDir' => [
        storage_path().'/mpdf/ttfonts',
        base_path().'/vendor/mpdf/mpdf/ttfonts',
    ],
]);

$mpdf->fontdata['arial'] = [
    'R'  => storage_path().'/mpdf/ttfonts/Arial.ttf',
];

$mpdf->SetDefaultFont('arial');
```

So basically, I'm adding our custom font path then trying to load Arial in, but my PDF just never uses the font.

**Comment by finwe** [comment]
`fontdata` property accepts only font name as a value, not the whole path. See [https://mpdf.github.io/fonts-languages/fonts-in-mpdf-6-x.html](Fonts in mPDF 6.x) for the general idea.

**Comment by jbrooksuk** [comment]
@finwe hmm, I've done that and the ofnts load, but the PDF still isn't rendering with Arial.

**Comment by jbrooksuk** [comment]
Actually, Arial is a core font, how can I get the dev branch to load core fonts?

**Comment by jbrooksuk** [comment]
Got it:

`$mpdf->onlyCoreFonts = true`.

**Comment by finwe** [comment]
new Mpdf(['mode' => 'c']);

But based on a little googling, Arial is not a core font.

**Comment by jbrooksuk** [comment]
Hmm, according to the docs it is:

> PDF files have certain standard fonts: Arial/Helvetica, Times and Courier in the win-1252 character set, and Zapfdingbats and Symbol character sets. These fonts should be available to any PDF reading program, and do not need to be embedded in the PDF document.

https://mpdf.github.io/fonts-languages/choosing-a-configuration-v6-x.html#core-non-embedded-fonts

**Comment by finwe** [comment]
Well, Helvetica is. https://tcpdf.org/docs/fonts/

**Comment by finwe** [comment]
Fixed in 9da7df9. Initialization with original fontdata can be seen [in unit test](https://github.com/mpdf/mpdf/blob/9da7df98cc0cc2ff158ba7207a1324db222f04ee/tests/Mpdf/ConfigurationTest.php#L47).

Direct access to `$mpdf->fontdata` property will eventually be restricted in favor of setter ("adder").

**Comment by jbrooksuk** [comment]
👍

**Comment by Klap-in** [comment]
In the code there are some assumptions that corefonts appear to be included in the corefont subset. 
e.g. https://github.com/mpdf/mpdf/search?utf8=%E2%9C%93&q=arial+helvetica 
However, I don't understand the conditions exactly, it shows kind of twice 'chelvetica' vs 'helvetica'.

Maybe useful to add some other unit tests to prove the exact behaviour?
I intend to update the documentation accordingly, but first I'm wondering for the real behavior. (In the docs the Arial font is mentioned regularly as core font.)
