### ISSUE TITLE
Conflict function dd

### ISSUE THREAD

**Issue by budirec** [mpdf/mpdf#350]
### I have this problem
Conflict function dd

### These are mPDF and PHP versions I am using
dev-master

The current dev-master seems to conflict with illuminate on function dd()

Will be better to check for if function available or not before declaring it, especially when declaring it in the / namespace

**Comment by finwe** [comment]
Closed in b521ae4

**Comment by finwe** [comment]
I strongly discourage you from using `dev-master` directly. Use a tag, version constraint or a fixed revision with `#` syntax.
