### ISSUE TITLE
PHP Warning : Unlink Is a directory (and the fix)

### ISSUE THREAD

**Issue by NicolasCARPi** [mpdf/mpdf#352]
Hello,

### I have this problem
The _MPDF_TEMP_PATH I use is shared with the tmp folder of Twig, and so has folder inside. During the cleanup, mpdf deletes (old) files in this folder, but the logs show a warning on the directories. By looking at the code, we can see that it checks with `is_dir`, but this check will always be false.

Here is the actual code, line 9460 of mpdf.php:

~~~php
if (($file != "..") && ($file != ".") && !is_dir($file) && ((filemtime(_MPDF_TEMP_PATH . $file) + $interval) < time()) && (substr($file, 0, 1) !== '.') && ($file != 'dummy.txt')) { // mPDF 5.7.3
~~~

And here is the code that actually works by adding _MPDF_TEMP_PATH to the is_dir parameter:

~~~php
if (($file != "..") && ($file != ".") && !is_dir(_MPDF_TEMP_PATH . $file) && ((filemtime(_MPDF_TEMP_PATH . $file) + $interval) < time()) && (substr($file, 0, 1) !== '.') && ($file != 'dummy.txt')) { // mPDF 5.7.3
~~~

### These are mPDF and PHP versions I am using
PHP version 7.1.2, mPDF version 6.1.3

Does that sounds good, and if yes, please include this change in the next release :)

Thanks for maintaining this very useful library and keep up the good work!

Regards,
~Nico

**Comment by finwe** [comment]
The 6.x branch of the project is frozen in favor of development 7.x branch. So no fixes there, sorry.

In any case, I recommend you using an aptly name subdirectory of your twig cache directory, or an entirely different directory as a mpdf temporary files storage to prevent this issue. 

I guess it is not a desired result to let mPDF clear your twig temporary files.

**Comment by NicolasCARPi** [comment]
Ok I see, you are right :)
