### ISSUE TITLE
Make annotation tags disabled by default 

### ISSUE THREAD

**Issue by h0ng10** [mpdf/mpdf#356]
During a  security test I was able to inject HTML code into a PDF document that was
generated by mPDF. By abusing the <annotation> tag, it was possible to extract senstive files/source code from the application backend.

The following HTML example includes the file "/etc/passwd" into the generated PDF document. 
```
The PDF is dark and full of attachments  
 <annotation file="/etc/passwd" content="/etc/passwd"  icon="Graph" title="Attached File: /etc/passwd" pos-x="195" />
```
I recommend that the support for the <annoation> tag should be disabled by default as many users don't know of the possible impact that this feature can have. 

### These are mPDF and PHP versions I am using
mPDF 6.0

**Comment by finwe** [comment]
I am not sure whether it is not a concern for system administrator to prevent PHP from being able to read files system-wide (by setting `open_basedir` or similar directive accordingly).

Basically, the library does not attempt anything evil by itself.

But OK, the annotation tags could be disabled by default.

**Comment by h0ng10** [comment]
Thanks

I don't think that a solution like "open_basedir" is sufficient here. The attacker could still gain access to sensitive files that belong to the PHP application.

**Comment by finwe** [comment]
You're right. I'll make attached files available only with a special new config flag enabled. The annotation tag itself will remain available without additional settings.
