### ISSUE TITLE
 transform: rotate(90deg); is not working

### ISSUE THREAD

**Issue by vtulse** [mpdf/mpdf#357]
### These are mPDF and PHP versions I am using

###The data is inside table head tag <th> but it not rotating text 

    <th class=''><span class='verticalhead'>Offer No.</span></th>

**Comment by finwe** [comment]
`transform` css property is not supported. You can use `text-rotate` [custom attribute](https://github.com/mpdf/mpdf-examples/blob/development/example05_tables.php#L836) or [CSS style](https://github.com/mpdf/mpdf-examples/blob/development/example05_tables.php#L885).

Also see [Supported CSS attributes - stylesheets or in-linePermalink](https://mpdf.github.io/css-stylesheets/supported-css.html)

**Comment by vtulse** [comment]
It rotating all the td element just want to rotate 3 between all
How we can do this?

Please help me.

**Comment by finwe** [comment]
You can apply the `text-rotate` attribute only to specific `td` tags in which you want to rotate the text.

**Comment by vtulse** [comment]
Waaaaaw.....! working fine

Thank you very much for help.

**Comment by abdulqadir88** [comment]
@finwe Thanks that worked like a **charm**.
