### ISSUE TITLE
ErrorException: Undefined index...  (*2)

### ISSUE THREAD

**Issue by CODEheures** [mpdf/mpdf#358]
### I have this problem
ErrorException: Undefined index: css_set_width in /vendor/mpdf/mpdf/src/Tag.php:2179
ErrorException: Undefined index: y1 in /vendor/mpdf/mpdf/src/Image/Svg.php:906

### These are mPDF and PHP versions I am using
I use dev-master (f3bbfc7133aed4b7bbdc22b243883bf552558211) on php7

To pass errors I add isset() tests

**Comment by finwe** [comment]
What is your PHP and HTML/CSS code?

**Comment by CODEheures** [comment]
Find all in this file: http://destockeurope.progress/bugmpdf.txt

**Comment by CODEheures** [comment]
Find it here: https://codeheures.fr/bugmpdf.txt

**Comment by finwe** [comment]
I am missing the SVG image, can you upload it as well, please?

**Comment by CODEheures** [comment]
Ok, the logo is here: https://codeheures.fr/logopdf.svg

**Comment by CODEheures** [comment]
Thank You very much
