### ISSUE TITLE
mpdf current development error on generating pdf from html output

### ISSUE THREAD

**Issue by OliverLeitner** [mpdf/mpdf#360]
i am trying to generate a pdf of a html5 website containing images/stylesheets and tables.

up until 7.0 everything worked like expected, the pdfs are being generated and delivered inline to the user.

starting with git pulls this week i am getting the following error on generating the pdf:

`
Fatal error: Uncaught Error: Call to undefined method Mpdf\Mpdf::_get_file() in path\to\webapp\libs\mpdf-new\src\CssManager.php:143 Stack trace: #0 path\to\webapp\libs\mpdf-new\src\Mpdf.php(14478): Mpdf\CssManager->ReadCSS('<!Doctype html>...') #1 path\to\webapp\libs\class.fileops.php(112): Mpdf\Mpdf->WriteHTML('<!Doctype html>...') #2 path\to\webapp\admin\apdf.php(57): fileOps->writePDF(Array, '<!Doctype html>...', 'pdfs/file_...', Array, '-string', 'I') #3 {main} thrown in path\to\webapp\libs\mpdf-new\src\CssManager.php on line 143
`
writePDF is defined as follows:

```
	public function writePDF($pdfconfig,$data,$savepath,$var,$addstr="",$pdftype=""){
		$mpdf = new \Mpdf\Mpdf([
			'mode' => '',
			'format' => 'A4',
			'default_font_size' => 12,
			'default_font' => 'verdana'
		]);

		foreach($pdfconfig AS $key => $value){
			$mpdf->$key($value);
		}
		$mpdf->SetCompression(true);
                **//this is, where stuff breaks...
		$mpdf->WriteHTML($data);**

		$pdf_root = preg_replace("/[^a-zA-Z0-9]+/","_",$var['String'])."-".$var['date']."-";

		if($pdftype == ''){
			$pdftype = 'F';
			$pdf_root = $savepath.preg_replace("/[^a-zA-Z0-9]+/","_",$var['String'])."-";
		}

		if($pdftype == 'S'){
			$out = $mpdf->Output('','S');
			return $out;
		} else {
			$mpdf->Output($pdf_root.$var['otherstring'].$addstr.".pdf",$pdftype);
		}
	}
```
-----------------------------------------------------------------------------------------------------

part of the html "template":

```
<!Doctype html>
<html lang="de">
	<head>
		<meta charset="ISO-8859-15">
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-15">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Title</title>
		<link href="scripts/lightbox2/dist/css/lightbox.min.css" rel="stylesheet">
		<link href="scripts/fileuploader/src/jquery.fileuploader.css" type="text/css" rel="stylesheet" />
		<!--link href="scripts/fileuploader/src/jquery.filer-dragdropbox-theme.css" type="text/css" rel="stylesheet" /-->
		<link rel="stylesheet" href="/styles/css.php" type="text/css">
		<!--[if IE]>
		<link rel="stylesheet" href="styles/ie.css">
		<![endif]-->
		<link rel="stylesheet" href="/styles/pdf.css">
		<script type="text/javascript" src="/scripts/jquery-3.2.1.min.js"></script>
		<script src="scripts/customjs.php" type="text/javascript"></script>
		<link rel="shortcut icon" type="image/ico" href="images/favicon.ico">
		<link rel="home" type="text/html" title="Startseite" href="/">
...
...
	</head>
	<body>
		
	<!-- start page wrap -->
	<div id="page-wrap">
		<div id="header">
			<div id="logo">...</div>
...
...
			<div id="printme">
				<a href="javascript:window.print()"><img alt="Seite Ausdrucken" src="/images/printme.png"/></a>
			</div>
			<footer>
				<small>&copy; ...</small>
			</footer>
		</div>			
	</body>
</html>
```
---------------------------------------------------------

This runs on a Windows PC/Server (7, 2008 Server...), german Language.

I tried to narrow it a bit down (i think...) in that, if i try to use the writeHTML modes and load the styles separate and then the body it first breaks because its not utf-8, on utf8-ting things, it breaks on not recognizing the images paths.

Thanks in advance for any kind of idea/tip or possible fix that might solve this.

**Comment by finwe** [comment]
It was just a forgotten call after moving a private method. Fixed in development branch, thanks for reporting.
