### ISSUE TITLE
Issue in using css filters

### ISSUE THREAD

**Issue by triusdeeepak** [mpdf/mpdf#362]
### Hi Everyone,

Hope you are doing great. I have created a website with functionality of creating telegrams. The telegrams can be made by using css filters like blur, saturation, sepia etc. So the issue is that I'm not able to get the effects in pdf file. So it would be better if someone has done it before or someone has knowledge about this.

Thanks
Deepak

### These are mPDF and PHP versions I am using
"mpdf/mpdf":"*"
### This is a PHP code snippet I use

```
<?php

  public function actionMpdf(){
        $mpdf=new mPDF();
        $site_url = Url::base();
        $stylesheet = file_get_contents($site_url.'/css/bootstrap.min.css');
        $stylesheet .= file_get_contents($site_url.'/css/style.css');        
        $stylesheet .= file_get_contents($site_url.'/css/responsive.css');        
        $stylesheet .= file_get_contents($site_url.'/css/jquery-ui.css');        
        $stylesheet .= file_get_contents($site_url.'/css/dj.css');        
        $mpdf->WriteHTML($stylesheet,1);
        $mpdf->WriteHTML($this->renderPartial('index'));
        $mpdf->Output();
        exit;
    }
```

### This is a HTML code snippet I use

```
<div class="pdf-viewer-Container">
    <div class="pdf-box">
        <div class="row top-area">
            <div class="half_me">
                <img class="img-responsive pull-left" src="http://www.triusind.com/940/images/pdf/logo.jpg">
            </div>
            <div class="half_me" style="text-align: right;">
                <img class="img-responsive pull-right" widyh="100px" src="http://www.triusind.com/940/images/pdf/stamp.jpg">
            </div>
            <div class="clear"> </div>
        </div>
             
            <div class="row pdf-container">
                <div class="half_me bdr"> To:<span> Lorem Ipsum </span></div>
                <div class="half_me bdr bdr-left"> From: <span> Dummy ever </span> </div>
                <div class="clear"> </div>        
                <p style="font-family : "></p>
            </div>        
            <div class="row pdf-container text-center">
                <div class="box"><div class="b1" style="width:100%; height:560px"><img class="dj_rot" src="/940/images/photos.png" style="filter: sepia(1);"></div> </div>            </div>           
            </div>
</div>
```

**Comment by triusdeeepak** [comment]
Hi Everyone,

Hope you are doing great. I have created a website with functionality of creating telegrams. The telegrams can be made by using css filters like blur, saturation, sepia etc. So the issue is that I'm nota ble to get the effects in pdf file. So it would be better if someone has done it before or someone has knowledge about this.

Thanks
Deepak

**Comment by finwe** [comment]
CSS filters are not supported in mPDF.

See [Supported CSS](https://mpdf.github.io/css-stylesheets/supported-css.html) page in the manual.

**Comment by triusdeeepak** [comment]
Can you please suggested of which php library I can use for css filters.?

**Comment by finwe** [comment]
There is none in pure PHP that I know of.
Try using [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf) - it needs to be installed, but uses Chromium rendering engine so it should produce similar output as Chrome does.
