### ISSUE TITLE
Poor security in example code

### ISSUE THREAD

**Issue by strider72** [mpdf/mpdf#363]
On this Manual page [https://mpdf.github.io/real-life-examples/pdf-from-every-page-of-website.html](url) , there is the following:

```
// To prevent anyone else using your script to create their PDF files
if (!preg_match('/^http:\/\/www\.mydomain\.com/', $url)) {
  die("Access denied");
}
```

This would still allow somebody to call you script with http://www.mydomain.com.evildomain.com/

You can fix it by checking for the domain-end slash:
`preg_match('#^http:\/\/www\.mydomain\.com\/#', $url)`

(Personally, I also permitted https in case I ever get that cert going...
`preg_match('#^http[s]?:\/\/www\.mydomain\.com\/#', $url)`

**Comment by finwe** [comment]
Cool, fixed in [mpdf/mpdf.github.io#¨](https://github.com/mpdf/mpdf.github.io) repository in commit 4505783 where the documentation is held. Thanks for reporting.
