### ISSUE TITLE
The compress.php creates a mpdf.php with an error

### ISSUE THREAD

**Issue by maofree** [mpdf/mpdf#365]
### I have this problem/would like to have this functionality
The compress.php creates a mpdf.php with an error around "else" it is due because it is missing the close curly bracket. Fixed it the new file continues to give errors

bye
### These are mPDF and PHP versions I am using
mPDF 6.1 and php 5.6 on debian linux
### This is a PHP code snippet I use

```
<?php


```

### This is a HTML code snippet I use

```

```
I report another little issue, the height of a div with inside an image is not considered only the width works
bye

**Comment by finwe** [comment]
See #306 

Given the second issue - please fill in a separate Issue with appropriate PHP/HTML/CSS examples.

**Comment by maofree** [comment]
ok for the height, I'll open a new ticket, but for the compress error?
this error appears after the creation of the new file, so I think you should reproduce it easily

bye

**Comment by finwe** [comment]
For the compress error, see the explanation in #306
