### ISSUE TITLE
Border in QrCode

### ISSUE THREAD

**Issue by yasirdocs** [mpdf/mpdf#368]

**Comment by finwe** [comment]
There is currently no way to achieve this with standard mPDF use.

**Comment by poliander** [comment]
And why not treating this as a feature request then? The border around a QR code could be disabled by calling QRcode::disableBorder(), or in HTML syntax using e.g. <barcode border="0" ... />

**Comment by finwe** [comment]
@poliander Yes, why did you not treat this as a feature request and did not submit a PR? It's  a [7-line change in the code](https://github.com/mpdf/mpdf/commit/02ce57bff3755f4a0a9b3bdf3f3ef7599b82fa6d).
