### ISSUE TITLE
Blank PDF

### ISSUE THREAD

**Issue by bipinacellere** [mpdf/mpdf#369]
Hello Team
I am getting blank page for PDF in PHP 7, It showing only footer only. 
However it is working with small amount of rows in table. It is getting blank after adding one more row.

It is working fine with PHP 5.6.

I am using mPDF 6.1 with Yii2. I also tried mPDF 7.0 but still same result.

Can you help me to solve out this issue asap?

**Comment by finwe** [comment]
Send your code asap.

**Comment by bipinacellere** [comment]
Controller Code:

$output = $this->renderPartial('@backend/modules/product/views/composition/article_pdf', $params);
define('_MPDF_TTFONTPATH', Yii::getAlias('@frontend/web/css/fonts/'));
define('_MPDF_TTFONTDATAPATH', Yii::$app->params['UPLOAD_DIR']);
define('_MPDF_TEMP_PATH', Yii::$app->params['UPLOAD_DIR']); 

$footerHtml = $this->renderPartial('@backend/modules/product/views/composition/_footer_pdf', array('userId' => $userId));

$pdf = new \kartik\mpdf\Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => $type,
            // your html content input
            'content' => $output,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            //'cssFile' => '@frontend/web/css/pdf.css',
            // any css to be embedded if required
            //'cssInline' => '',
            // set mPDF properties on the fly
            'options' => ['title' => 'XYZ'],
            // call mPDF methods on the fly
            'methods' => [
                'SetFooter' => [$footerHtml],
            ]
        ]);

        $pdf->filename = $path . $name;


View File:

$view = isset($_GET['view'])?$_GET['view']:'pdf';
<div class="container content-<?php echo $view;?>-view">
    
    <table width="100%" style="margin-bottom: 70px;">
        <tr>
            <?php if(isset($_GET['view']) && $_GET['view']=='html' && false) { ?>
            <td>
                <ul class="list-inline">
                    <li><?php echo Html::a(Yii::t('app', 'Download PDF'), 'javascript:;', array('class' => 'js-file-download', 'data-type-id' => isset($_GET['ids'])?$_GET['ids']:'', 'data-type' => 'D')); ?></li>
                </ul>
            </td>
            <?php } ?>
            <td style="float:right;text-align: right;">
                <?php echo Html::img($baseUrl.'/images/ag_company_logo_placeholder_01.svg', array( 'style'=>'text-align:right;')); ?>
            </td>
        </tr>
    </table>
    <?php
        $sender   = CompanyAddress::find()->where(['company_id' => $companyId])->andWhere(['is_cart' => 1])->one();
        $receiver = Company::find()->where(['user_id' => $userId])->one();
        $project  = Project::find()->where(['company_id' => $companyId])->one();

        $date = isset($project->invoice_dt)?$project->invoice_dt:'';
        $doc  = isset($project->document_type)?$project->document_type:'';
        ?>
        <table width="100%" style="margin-bottom: 30px;">
            <tr>
                <td width="50%" style="vertical-align: top;">
                    <?php
                    if(!empty($sender))
                    {
                        $senderAddress = ', '.$sender->street.' '.$sender->zip.', '.$sender->city;
                        ?>
                        <table>
                        <tr><td><p style="font-size: 10px;"><b><?php echo (isset($sender->company->name) ? $sender->company->name : '').$senderAddress;?></b><p></td></tr>
                        </table>
                        <?php
                    }
                    ?>
                    <table>
                    <?php
                        if(!empty($receiver))
                        {
                            ?>
                            <tr><td><?php echo $receiver->name;?></td></tr>
                            <?php
                            $companyAddresses = $receiver->companyAddresses;
                            if($companyAddresses)
                            {
                                $companyAddress = $companyAddresses[0];
                                ?>
                                <tr><td><?php echo $companyAddress->street?></td></tr>
                                <tr><td><?php echo $companyAddress->zip.', '.$companyAddress->city?></td></tr>
                                <?php
                            }
                        }?>
                    </table>
                </td>
                <?php if($project) {?>
                <td width="50%" style="vertical-align: top; padding-left: 100px;">
                    <table>
                        <?php if(!empty($date)){?>
                        <tr><td><p><b><?php echo Yii::t('app','Date');?></b><p><?php echo Utils::getDate($date,'php:d.m.yy');?></td></tr>
                        <?php }?>
                    </table>
                    <table>
                        <tr><td><p><b><?php echo Yii::t('app','Project');?></b><p></td></tr>
                        <tr><td><?php echo $project->name;?></td></tr>
                        <tr><td><?php echo $project->street;?></td></tr>
                        <tr><td><?php echo $project->zip.', '.$project->city;?></td></tr>
                    </table>
                </td>
                <?php }?>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center; padding-top: 4px;">
                    <h3><b><?php echo ($doc == 'offer') ? Yii::t('app', 'Offer') : Yii::t('app', 'Request');;?></b><h3>
                </td>
            </tr>
        </table>
    

    <div id="article-table-container">
        <div class="title" style="font-size: 16px; margin-bottom: 5px;">
            <?php echo Yii::t('app','Article overview');?>
        </div>
        <table id="article-table">
            <thead>
                <tr>
                    <th><?php echo Yii::t('app','Number');?></th>
                    <th><?php echo Yii::t('app','Qty');?></th>
                    <th><?php echo Yii::t('app','Units');?></th>
                    <th colspan="2"><?php echo Yii::t('app','Description');?></th>
                    <?php if($doc == 'offer') {?>
                    <th class="price"><?php echo Yii::t('app','Amount');?></th>
                    <th class="price"><?php echo Yii::t('app','Total amount');?></th>
                    <?php }?>
                </tr>
            </thead>
            <tbody>
            <?php
            $subTotal = 0;
            foreach($articles as $i=>$cartArticle)
            {
                $number = ++$i;

                $qty = isset($cartArticle->quantity)?$cartArticle->quantity:0;
                $unit = isset($cartArticle->unit)?$cartArticle->unit:'';
                $isPDF = isset($cartArticle->is_pdf)?$cartArticle->is_pdf:1;
                if($isPDF && ($articleType=='all' || $articleType==$cartArticle->product->type_id))
                {
                ?>
                
                <tr class="primary-row1">
                    <td style="border-right:1px solid #ccc;"><?= $number; ?></td>
                    <td class="font-normal">
                        <?php
                        echo $qty;
                        ?>
                    </td>
                    <td class="font-normal">
                        <?php echo isset($unit)?$unit:''; ?>
                    </td>
                    <td class="placeholder-column" style="width:16px;">
                        <?php echo $cartArticle->product->getFirstProductImage($view,array('style'=>'width:16px;'),true); ?>
                    </td>
                    <td>
                        <span><?php echo $cartArticle->product->name;?></span><br/>
                        <span><?php echo $cartArticle->product->article_id;?></span>
                    </td>
                    <?php
                    if($doc == 'offer')
                    {
                        $price = isset($cartArticle->price)?$cartArticle->price:0;
                        $itemPrice = $price*$qty;
                        $subTotal += $itemPrice;
                        ?>
                        <td class="price"><?php echo $utils->formatCurrency($price); ?></td>
                        <td class="price"><?php echo $utils->formatCurrency($itemPrice); ?></td>
                        <?php
                    }?>
                </tr>
                <?php
                }

                $query = Cart::find();
                $query->andWhere(['IN', 'cart.user_id', $cartArticle->user_id]);
                $query->andWhere(['cart.parent_id'=>$cartArticle->id]);
                $query->join('INNER JOIN', 'product', 'product.id=cart.product_id');
                $query->orderBy('cart.id asc');
                $secondaryArticles = $query->all();

                ## direct articles
                foreach($secondaryArticles as $j=>$secondaryArticle)
                {
                    $qty = isset($secondaryArticle->quantity)?$secondaryArticle->quantity:0;
                    $unit = isset($secondaryArticle->unit)?$secondaryArticle->unit:'';
                    $isPDF = isset($secondaryArticle->is_pdf)?$secondaryArticle->is_pdf:1;

                    $append = '.'.++$j;
                    if($isPDF && ($articleType=='all' || $articleType==$secondaryArticle->product->type_id))
                    {
                    ?>
                    
                    <tr class="secondary-row1">
                        <td style="border-right:1px solid #ccc;"><?php echo $number.$append;?></td>
                        <td>
                            <?php
                            echo $qty;?>
                        </td>
                        <td>
                            <?php echo isset($unit)?$unit:''; ?>
                        </td>
                        <td class="placeholder-column">
                            <?php
                            echo $secondaryArticle->product->getFirstProductImage($view,array('style'=>'width:16px'),true);?>
                        </td>
                        <td>
                            <span><?php echo $secondaryArticle->product->name;?></span><br/>
                            <span><?php echo $secondaryArticle->product->article_id;?></span>
                        </td>
                        <?php
                        if($doc == 'offer')
                        {
                            $price = isset($secondaryArticle->price)?$secondaryArticle->price:0;
                            $itemPrice = $price*$qty;
                            $subTotal += $itemPrice;
                            ?>
                            <td class="price"><?php echo $utils->formatCurrency($price); ?></td>
                            <td class="price"><?php echo $utils->formatCurrency($itemPrice); ?></td>
                        <?php }?>
                    </tr>
                    <?php
                    }

                    $query = Cart::find();
                    $query->andWhere(['IN', 'cart.user_id', $secondaryArticle->user_id]);
                    $query->andWhere(['cart.parent_id' => $secondaryArticle->id]);
                    $query->join('INNER JOIN', 'product', 'product.id=cart.product_id');
                    $query->orderBy('cart.id asc');
                    $ternaryArticles = $query->all();

                    ## suggested articles
                    $k = 0;
                    foreach($ternaryArticles as $ternaryArticle)
                    {
                        $qty = isset($ternaryArticle->quantity)?$ternaryArticle->quantity:0;
                        $unit = isset($ternaryArticle->unit)?$ternaryArticle->unit:'';
                        $isPDF = isset($ternaryArticle->is_pdf)?$ternaryArticle->is_pdf:1;

                        if($isPDF && ($articleType=='all' || $articleType==$ternaryArticle->product->type_id))
                        {
                            $append2 = '.'.++$k;
                        ?>
                        
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                <?php echo $number.$append.$append2;?>
                            </td>
                            <td>
                                <?php echo $qty; ?>
                            </td>
                            <td>
                                <?php echo isset($unit)?$unit:''; ?>
                            </td>
                            <td class="placeholder-column">
                                <?php
                                echo $ternaryArticle->product->getFirstProductImage($view,array('style'=>'width:16px'),true);?>
                            </td>
                            <td>
                                <span><?php echo $ternaryArticle->product->name;?></span><br/>
                                <span><?php echo $ternaryArticle->product->article_id;?></span>
                            </td>
                            <?php
                            if($doc == 'offer')
                            {
                                $price = isset($ternaryArticle->price)?$ternaryArticle->price:0;
                                $itemPrice = $price*$qty;
                                $subTotal += $itemPrice;
                                ?>
                                <td class="price"><?php echo $utils->formatCurrency($price); ?></td>
                                <td class="price"><?php echo $utils->formatCurrency($itemPrice); ?></td>
                            <?php }?>
                        </tr>
                        <?php
                        }
                    }
                }
            }
            ?>
            </tbody>
            <?php
            if($doc == 'offer')
            { ?>
            <tfoot class="summary">
                <tr class="subtotal">
                    <td colspan="6"><b><?php echo Yii::t('app','Subtotal');?></b></td>
                    <td class="subtotal-amount"><?php echo $utils->formatCurrency($subTotal);?><?php //echo $utils->formatCurrency($subTotal); ?></td>
                </tr>
                <?php
                if(isset($isVat) && $isVat==='true')
                {
                    $vatPercent = 19;
                    $vat = ($subTotal * $vatPercent) / 100;
                    $total = $subTotal + $vat;
                ?>
                <tr class="vat">
                    <td colspan="6"><b><?php echo Yii::t('app','VAT');?> (<span id="vatPer"><?php echo $vatPercent;?>%</span>)</b></td>
                    <td class="vat-amount"><?php echo $utils->formatCurrency($vat);?><?php //echo $utils->formatCurrency($vat); ?></td>
                </tr>
                <tr class="total">
                    <td colspan="6"><b><?php echo Yii::t('app','Grand total');?></b></td>
                    <td class="total-amount"><?php echo $utils->formatCurrency($total);?><?php //echo $utils->formatCurrency($total); ?></td>
                </tr>
                <?php
                }
                ?>
            </tfoot>
            <?php }?>
        </table>
    </div>
</div>

Let me know if you need more details

**Comment by finwe** [comment]
Can you post a final static HTML you send to mPDF? I cannot possibly get it from this.

**Comment by bipinacellere** [comment]
Final output HTML is:

It will work if you remove 4-5 rows from html

> <div class="container content-pdf-view">
    
    <table width="100%" style="margin-bottom: 70px;">
        <tr>
                        <td style="float:right;text-align: right;">
                <img src="/var/www/html/agan/frontend/web/images/ag_company_logo_placeholder_01.svg" alt="" style="text-align:right;">            </td>
        </tr>
    </table>
            <table width="100%" style="margin-bottom: 30px;">
            <tr>
                <td width="50%" style="vertical-align: top;">
                                            <table>
                        <tr><td><p style="font-size: 10px;"><b>Bipsy Jumpy, Paffrather Str. 12 51465, Bergisch Gladbach</b><p></td></tr>
                        </table>
                                            <table>
                                        </table>
                </td>
                                <td width="50%" style="vertical-align: top; padding-left: 100px;">
                    <table>
                                                <tr><td><p><b>Datum</b><p>21.03.2017</td></tr>
                                            </table>
                    <table>
                        <tr><td><p><b>Projekt</b><p></td></tr>
                        <tr><td>Project 1</td></tr>
                        <tr><td>Bremen</td></tr>
                        <tr><td>28195, Bremen</td></tr>
                    </table>
                </td>
                            </tr>
            <tr>
                <td colspan="2" style="text-align: center; padding-top: 4px;">
                    <h3><b>Anfrage</b><h3>
                </td>
            </tr>
        </table>
    
        
    <div id="article-table-container">
        <div class="title" style="font-size: 16px; margin-bottom: 5px;">
            Artikel-Übersicht        </div>
        <table id="article-table">
            <thead>
                <tr>
                    <th>Pos.</th>
                    <th>Menge</th>
                    <th>Einh.</th>
                    <th colspan="2">Beschreibung</th>
                                    </tr>
            </thead>
            <tbody>
                            
                <tr class="primary-row1">
                    <td style="border-right:1px solid #ccc;">1</td>
                    <td class="font-normal">
                        12                    </td>
                    <td class="font-normal">
                                            </td>
                    <td class="placeholder-column" style="width:16px;">
                        <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px;">                    </td>
                    <td>
                        <span>Betonstürze - 11,5 x 7,1 cm 1,00m</span><br/>
                        <span>MT00993</span>
                    </td>
                                    </tr>
                                
                <tr class="primary-row1">
                    <td style="border-right:1px solid #ccc;">2</td>
                    <td class="font-normal">
                        0                    </td>
                    <td class="font-normal">
                                            </td>
                    <td class="placeholder-column" style="width:16px;">
                        <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_comp_01.svg" alt="" style="width:16px;">                    </td>
                    <td>
                        <span>Wand verputzen innen, fachgerecht, in der Oberflächenqualität Q2</span><br/>
                        <span>GL00015</span>
                    </td>
                                    </tr>
                                    
                    <tr class="secondary-row1">
                        <td style="border-right:1px solid #ccc;">2.1</td>
                        <td>
                            0                        </td>
                        <td>
                                                    </td>
                        <td class="placeholder-column">
                            <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_serv_01.png" alt="" style="width:16px">                        </td>
                        <td>
                            <span>Wand verputzen innen - fachgerecht, vollflächig, mit geeignetem Putz in der Oberflächenqualität Q2</span><br/>
                            <span>EL02128</span>
                        </td>
                                            </tr>
                                            
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                2.1.1                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Gips-Maschinenputz - für Innen, 30kg pro Sack</span><br/>
                                <span>MT00778</span>
                            </td>
                                                    </tr>
                                                
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                2.1.2                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Rührer - 140mm, für flüssige und cremige Materialien</span><br/>
                                <span>MT04714</span>
                            </td>
                                                    </tr>
                                                
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                2.1.3                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Glättekelle ungezahnt 28x13cm, gehärteter Bandstahl</span><br/>
                                <span>MT02744</span>
                            </td>
                                                    </tr>
                                        
                <tr class="primary-row1">
                    <td style="border-right:1px solid #ccc;">3</td>
                    <td class="font-normal">
                        0                    </td>
                    <td class="font-normal">
                                            </td>
                    <td class="placeholder-column" style="width:16px;">
                        <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_serv_01.png" alt="" style="width:16px;">                    </td>
                    <td>
                        <span>Stürze in einschaligen Porenbeton - Außenwänden 36,5cm</span><br/>
                        <span>EL00971</span>
                    </td>
                                    </tr>
                                
                <tr class="primary-row1">
                    <td style="border-right:1px solid #ccc;">4</td>
                    <td class="font-normal">
                        0                    </td>
                    <td class="font-normal">
                                            </td>
                    <td class="placeholder-column" style="width:16px;">
                        <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_comp_01.svg" alt="" style="width:16px;">                    </td>
                    <td>
                        <span>Trockenbauwand - 75mm, Gesamtstärke, einfach beplankt, erstellen</span><br/>
                        <span>GL00009</span>
                    </td>
                                    </tr>
                                    
                    <tr class="secondary-row1">
                        <td style="border-right:1px solid #ccc;">4.1</td>
                        <td>
                            0                        </td>
                        <td>
                                                    </td>
                        <td class="placeholder-column">
                            <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_serv_01.png" alt="" style="width:16px">                        </td>
                        <td>
                            <span>Trockenbauwand - erstellen, 75mm Breite, einfach beplankt </span><br/>
                            <span>EL02104</span>
                        </td>
                                            </tr>
                                            
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                4.1.1                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Trennwandplatten TW 1 50 mm dick, 7,813 m²/Pak=10 Platten 125x62,5 cm</span><br/>
                                <span>MT01175</span>
                            </td>
                                                    </tr>
                                                
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                4.1.2                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Cuttermesser - mit Abbrechklinge, 18mm, Feststellrad</span><br/>
                                <span>MT02811</span>
                            </td>
                                                    </tr>
                                        
                <tr class="primary-row1">
                    <td style="border-right:1px solid #ccc;">5</td>
                    <td class="font-normal">
                        0                    </td>
                    <td class="font-normal">
                                            </td>
                    <td class="placeholder-column" style="width:16px;">
                        <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_comp_01.svg" alt="" style="width:16px;">                    </td>
                    <td>
                        <span>Trockenbauwand -100mm, Gesamtstärke, doppelt beplankt, erstellen</span><br/>
                        <span>GL00010</span>
                    </td>
                                    </tr>
                                    
                    <tr class="secondary-row1">
                        <td style="border-right:1px solid #ccc;">5.1</td>
                        <td>
                            0                        </td>
                        <td>
                                                    </td>
                        <td class="placeholder-column">
                            <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_serv_01.png" alt="" style="width:16px">                        </td>
                        <td>
                            <span>Trockenbauwand - erstellen, 100mm Breite, doppelt beplankt </span><br/>
                            <span>EL02106</span>
                        </td>
                                            </tr>
                                            
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                5.1.1                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Trennwandplatten TW 1 50 mm dick, 7,813 m²/Pak=10 Platten 125x62,5 cm</span><br/>
                                <span>MT01175</span>
                            </td>
                                                    </tr>
                                                
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                5.1.2                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Gipskartonplatten, 200  x  125 cm, 12,5 mm stark</span><br/>
                                <span>MT01432</span>
                            </td>
                                                    </tr>
                                                
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                5.1.3                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Schnellbauschrauben mit Feingewinde  , 3,9x25 1000ST/PAK</span><br/>
                                <span>MT03621</span>
                            </td>
                                                    </tr>
                                        
                <tr class="primary-row1">
                    <td style="border-right:1px solid #ccc;">6</td>
                    <td class="font-normal">
                        0                    </td>
                    <td class="font-normal">
                                            </td>
                    <td class="placeholder-column" style="width:16px;">
                        <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_comp_01.svg" alt="" style="width:16px;">                    </td>
                    <td>
                        <span>New Composition for lawyer1</span><br/>
                        <span>GL00018</span>
                    </td>
                                    </tr>
                                
                <tr class="primary-row1">
                    <td style="border-right:1px solid #ccc;">7</td>
                    <td class="font-normal">
                        0                    </td>
                    <td class="font-normal">
                                            </td>
                    <td class="placeholder-column" style="width:16px;">
                        <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px;">                    </td>
                    <td>
                        <span>Lehmkleber , Haft- & Armiermörtel trocken 30 KG/SA</span><br/>
                        <span>MT00852</span>
                    </td>
                                    </tr>
                                
                <tr class="primary-row1">
                    <td style="border-right:1px solid #ccc;">8</td>
                    <td class="font-normal">
                        0                    </td>
                    <td class="font-normal">
                                            </td>
                    <td class="placeholder-column" style="width:16px;">
                        <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_comp_01.svg" alt="" style="width:16px;">                    </td>
                    <td>
                        <span>Bodenplatte abdichten nach DIN 18195 Teil 6</span><br/>
                        <span>GL00001</span>
                    </td>
                                    </tr>
                                    
                    <tr class="secondary-row1">
                        <td style="border-right:1px solid #ccc;">8.1</td>
                        <td>
                            0                        </td>
                        <td>
                                                    </td>
                        <td class="placeholder-column">
                            <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_serv_01.png" alt="" style="width:16px">                        </td>
                        <td>
                            <span>Schweißbahn vollflächig auf Bodenplatte aufbringen </span><br/>
                            <span>EL00740</span>
                        </td>
                                            </tr>
                                            
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                8.1.1                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Feuerzeug - Werbeartikel Kunststoff Piezo Zündung 500 Stk. mit eigenem Logo bedruckbar </span><br/>
                                <span>MT04603</span>
                            </td>
                                                    </tr>
                                                
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                8.1.2                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Anwärmbrenner und Abflammgerät - Set mit Schlauch, Flammentemperatur bis 1060Grad</span><br/>
                                <span>MT03888</span>
                            </td>
                                                    </tr>
                                                
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                8.1.3                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Schweißbahn - G200, S4</span><br/>
                                <span>MT01867</span>
                            </td>
                                                    </tr>
                                                
                        <tr class="tertiary-row1">
                            <td style="border-right:1px solid #ccc;">
                                8.1.4                            </td>
                            <td>
                                0                            </td>
                            <td>
                                                            </td>
                            <td class="placeholder-column">
                                <img type="image/svg" class="img-logo" src="/var/www/html/agan/frontend/web/images/agan_pdf_icon_mat_01.svg" alt="" style="width:16px">                            </td>
                            <td>
                                <span>Bitumengrundierung  - 3 K 30-Lt-Gebinde</span><br/>
                                <span>MT01791</span>
                            </td>
                                                    </tr>
                                    </tbody>
                    </table>
    </div>
</div>

**Comment by finwe** [comment]
Close your h3 tag and the document appears magically.

**Comment by bipinacellere** [comment]
OMG!!!
It works magically. Thx a lot.
