### ISSUE TITLE
Cleaner directory structure (maybe with some PSR compliancy)

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#37]

**Comment by bunya** [comment]
Good day. May I get directory structure:
* **config** (if necessary) for default configs
* **example** for module usage examples
* **resource** for externals resources (for example, format configs, static things, etc)
* **src**
  * **Mpdf**
    *  \<classes by namespaces with PSR-4 structure\>
* **test**
  * **Mpdf**
    *  \<tests by namespaces same as classes in src\>
