### ISSUE TITLE
Can't config a custom font

### ISSUE THREAD

**Issue by theoarena** [mpdf/mpdf#371]
### I have this problem

My client want his PDF to have the SEGOE UI font. 
No matter what i do, i just can't get this font working, it always shows the standard fonts!

### These are mPDF and PHP versions I am using

MPDF version 6.1 with PHP 5.6

### This is a PHP code snippet I use

```
<?php
-- config_fonts.php (the font file is in the 'ttfonts' folder)
$this->fontdata = array(
	"segoe" => array(
		'R' => "segoeui.ttf",			
	)
(...)

-- in my Controller:
$mpdf = new mPDF('c','A4', 0, 'segoe', 10, 10, 24, 9, 5, 2, 'P');

(...)

$mpdf->WriteHTML('print.css',1);

```

### This is a HTML code snippet I use

```
-- print.css file( it's being loaded correctly, and i've tried all the combinations on the selectors):
body,html,p,a{font-family:'segoe'}

-- in my View:
<p style="font-family: segoe">Report</p>
```

What could be wrong??

Thanks in advance!

**Comment by theoarena** [comment]
The problem was in the constructor:

``
$mpdf = new mPDF('c','A4', 0, '', 10, 10, 24, 9, 5, 2, 'P');
``

The 'c' parameter blocks any custom config for FONTS. Removing it made my code to work, maybe it's an issue?

**Comment by finwe** [comment]
That is actually a documented feature. `c` mode means "use PDF core fonts". See [documentation](https://mpdf.github.io/fonts-languages/choosing-a-configuration-v6-x.html#core-non-embedded-fonts)
