### ISSUE TITLE
Error while inserting a watermark

### ISSUE THREAD

**Issue by dextErlan** [mpdf/mpdf#372]
### I have this problem
When I add a watermark, an error occurs in the MPdf class on line 24946 
```
// mPDF 5.7.3
// If a shading dictionary is in an object (tpl) imported from another PDF, it needs to be included
// in the document resources, as well as the object resources
// Otherwise get an error in some PDF viewers
if ($this->enableImports && count($this->tpls)) {
	foreach ($this->tpls as $tplidx => $tpl) {
		if (isset($tpl['resources'])) {
			$this->current_parser = $tpl['parser'];
			reset($tpl['resources'][1]);
			while (list($k, $v) = each($tpl['resources'][1])) {
				if ($k == '/Shading') {
					while (list($k2, $v2) = each($v[1])) {
```
**while (list($k2, $v2) = each($v[1]))** 
In $v[1] a number comes instead of an array.
### These are mPDF and PHP versions I am using
PHP 7.1.1
mPDF 7.0
### This is a PHP code snippet I use

```
<?php
        $pdf->SetImportUse();
        $pdf->SetSourceFile($file);
        $tplId = $pdf->ImportPage(1);
        $pdf->UseTemplate($tplId);
        if ($this->watermark) {
            $pdf->$mpdf->SetWatermarkImage('http://www.yourdomain.com/images/logo.jpg', 1, '', array(160,10));
            $pdf->showWatermarkImage = true;
        }
        $pdf->Output($file);

```

### This is a HTML code snippet I use

```

```

**Comment by finwe** [comment]
I am not able to reproduce this. Can you debug this further and reopen with additional information? Thanks!

I have added a test case with your code that passes to the development branch, you can elaborate on that.

**Comment by dextErlan** [comment]
<a href='http://download.files.namba.net/files/89830221'>Нарушение тишины  Советы юристов.pdf</a>
With this file I get error, described above

**Comment by finwe** [comment]
Can you please upload directly here? The site you linked is very, very slow. Thanks.

**Comment by finwe** [comment]
No, even with this PDF the test passes on PHP 7.1.7.

**Comment by KirDE** [comment]
We faced the same issue and discovered, that in ResourceWriter.php:199 is missing a check if concent of '/Shading' first element is array.

We suggest following change (line 198)
`							if ($k === '/Shading' && is_array($v)) {
								foreach ($v[1] as $k2 => $v2) {
									$this->writer->write($k2 . ' ', false);
									$this->mpdf->pdf_write_value($v2);
								}
							}`

content of $tpl['resources'][1]: 
`[
    5,
    [
        '/ProcSet' => [
            6,
            [
                [
                    2,
                    '/PDF',
                ],
                [
                    2,
                    '/ImageC',
                ],
                [
                    2,
                    '/Text',
                ],
            ],
        ],
        '/ColorSpace' => [
            8,
            74,
            0,
        ],
        '/ExtGState' => [
            8,
            75,
            0,
        ],
        '/Pattern' => [
            8,
            76,
            0,
        ],
        '/Shading' => [
            8,
            77,
            0,
        ],
        '/XObject' => [
            8,
            78,
            0,
        ],
        '/Font' => [
            8,
            79,
            0,
        ],
    ],
]`
'/Shading' is simple array here

**Comment by finwe** [comment]
Please, provide a test sample code influenced by this change.
