### ISSUE TITLE
Compoaser Alternative

### ISSUE THREAD

**Issue by clintre** [mpdf/mpdf#373]
### I have this problem/would like to have this functionality
Security for environment does not allow for the use of Composer. The organization that I am using, or would like to, use mPDF in does not allow the use of Composer due to past security issues they had. Unfortunately since it seems that mPDF has moved to requiring it, this has forced me to use the 6.1.0 release and thus causes a potential issue in the future.

I understand the thought of moving to a system like that, but it does unfortunately move mPDF out as a option for more than a few organizations (with similar requirements) that I am working with, where Composer is on their banned list.

Is there anyway for a situation like this to build a custom auto-load script for PHP to run?

### These are mPDF and PHP versions I am using
6.1.0

**Comment by finwe** [comment]
Sure, just clone mPDF and each of its dependencies manually and use a standalone autoloader to load all necessary classes.

There are many available, such as [Nette's RobotLoader](https://github.com/nette/robot-loader), you can surely somehow use standalone composer's autoloader, or you can find [many other on packagist](https://packagist.org/search/?search_query%5Bquery%5D=autoload).

Can you elaboerate on "Past security issues they had"? I am not aware of any too serious and with the usage of composer I would be more concerned with using any other one-man autoloader project than to use composer.

You can always pre-prepare your package locally with composer and commit your vendor folder to the repository after review so you can avoid composer in production.
