### ISSUE TITLE
Page break avoid in tables and columns

### ISSUE THREAD

**Issue by Blaztix** [mpdf/mpdf#375]
I have a PHP script that prints several tables, when I put two columns, the tables are cut when there is no more space (even if it's just a line), instead when I just put a column, read the configuration well and the table goes to the following Page, also that thead is not repeated in the second column.

![image](https://cloud.githubusercontent.com/assets/4962591/25060987/a338840a-2181-11e7-8788-b9e041bd2293.png)

php code is very large...

**Comment by finwe** [comment]
Please, post your PHP/HTML code snippet causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
