### ISSUE TITLE
Problem with Hindi Font

### ISSUE THREAD

**Issue by rkahar** [mpdf/mpdf#376]
### I have this problem/would like to have this functionality
I am using "FreeSans" font for Hindi Language. When I am using some words like **में, सीमेंट, पैंतालीस** It shows **मे ं, सीमेटं, पैतांलीस,** i.e. it shifts the position of dot(ं) character
### These are mPDF and PHP versions I am using
mPDF 6.0 & PHP 5.6.19
### This is a PHP code snippet I use

```
<?php


```

### This is a HTML code snippet I use

```

```

**Comment by shuBomb** [comment]
Did you find any solution?

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
