### ISSUE TITLE
Rotate table headers by 90deg

### ISSUE THREAD

**Issue by andyts93** [mpdf/mpdf#379]
Is there a way to rotate a table header by 90°? I've tried these two methods but I still have an horizontal header

```
$mpdf->WriteHTML('<table><tr><th style="transform:rotate(-90deg)">TEST</th></tr></table>');

$mpdf->WriteHTML('<table><tr><th><div style="transform:rotate(-90deg)">TEST</div></th></tr></table>'
```

**Comment by finwe** [comment]
Use `<tr text-rotate="45">` proprietary attribute. `rotate` CSS property could also work.

See https://mpdf.github.io/css-stylesheets/supported-css.html
