### ISSUE TITLE
anchor tag not working while generating single PDF from Multiple PDF files using mPDF

### ISSUE THREAD

**Issue by hardikpanseriya** [mpdf/mpdf#382]
I have three PDF files. I want to integrate three PDF files into a single PDF file. I have used mPDF library to generate single PDF file from multiple PDF files.

```
<?php
$mpdf = new mPDF('en', 'A4-L');
$mpdf->SetSourceFile("1.pdf");
$tplId = $mpdf->ImportPage(1);
$mpdf->UseTemplate($tplId);
$mpdf->SetSourceFile("2.pdf");
$tplId = $mpdf->ImportPage(1);
$mpdf->UseTemplate($tplId);
$mpdf->SetSourceFile("3.pdf");
$tplId = $mpdf->ImportPage(1);
$mpdf->UseTemplate($tplId);
$mpdf->Output("output.pdf", "D");
?>
```

When generating a single PDF file, I can not see anchor URL into the text in PDF file. 
[Sample PDF File Here](http://simbanic.com/_projects/demo/pdf/1.pdf)

**Comment by machour** [comment]
Hi @hardikpanseriya, it seems that your sample PDF file is 404 now.

Can you provide a sample repository with the 3 PDF files and your script, further explaining what you are trying to achieve? What anchor URL are you expecting to see?

**Comment by finwe** [comment]
Closing as stale. Feel free to open a new Issue providing all details wanted in the Issue template, especially example source PDF files.
