### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by BlaDrzz** [mpdf/mpdf#386]
### This is a PHP code snippet I use

```
    public function actionPdf() {
    	
  	$model = new Modelname();
    	$model->load(Yii::$app->session['calculation']);
    	$model->makeCalculations();
  		
    	$pdf = new Mpdf();

        $pdf->SetHeader('SiteName||on: ' . strftime('%A %d %B %Y', strtotime(date('Y-m-d'))));
        $pdf->writeHTML($this->renderPartial('outputform', ['model' => $model, 'tab' => 1]));
        $pdf->SetFooter('https://www.example.com||p. {PAGENO}|');

        return $pdf->output();
    }
```
It only makes a pdf when I have ```error_reporting(0);``` on the first line of the mpdf.php file. So everything works and looks good apart from my error log getting spammed with the abovementioned error.

**Comment by finwe** [comment]
Are you sure you are using PHP 7.1.3? Variadic arguments are supported as of PHP 5.6

**Comment by BlaDrzz** [comment]
phpinfo() tells me that I am on 7.1.3...

**Comment by BlaDrzz** [comment]
phpinfo() on our server: http://hrtd.be/info.php

**Comment by finwe** [comment]
It seems as some quirk with some setups, as hinted here: https://github.com/laravel/framework/issues/16674

Anyway, mPDF code is correct and there is nothing I can do to help you from the maintaner point of view.
