### ISSUE TITLE
css_set_width in 6.1 and v7.0.0-beta2

### ISSUE THREAD

**Issue by jonny7** [mpdf/mpdf#387]
### I have this problem
I installed via composer package 7.0.0-beta2 for my Yii2 project. I'm trying to render a full page so the css is bootstrapped in automatically. But I get a notice error:

`Undefined index: css_set_width` in the file `vendor\mpdf\mpdf\src\Tag.php` ln: 2179. I just edited the source in vendor using array_key_exists and it worked. So I forked your package so I could do a pull request. But I couldn't see the branch for 7.0.0-beta2 in your git repo?

I don't use github much so I'm sure it's my mistake on how to proceed. But if you can let me know what I need to do.

### These are mPDF and PHP versions I am using

7.1.1

**Comment by Klap-in** [comment]
The 7.0.0-beta2 is a tag (kind of snapshot) of the development branch at that moment.
https://github.com/mpdf/mpdf/releases
So pull requests could be done against current development branch.

Could you maybe find the specific part of the css that trigger this error?

**Comment by jonny7** [comment]
@Klap-in Yes, it's line 2179 is `Tag.php` from the package I installed using composer (`"mpdf/mpdf": "~7.0.0-beta2"`). The fork I created was from the development branch I just checked and this seems to have addressed that particular issue in the code :+1:

**Comment by jonny7** [comment]
Can we get a new tag (v7.0.0-beta3) for the development branch on packagist?
