### ISSUE TITLE
Text alignment at form input fields

### ISSUE THREAD

**Issue by konstmal** [mpdf/mpdf#390]
### I have this problem/would like to have this functionality
When I add text alignment to an `<input type="text">`, the value is no longer transmitted.

### These are mPDF and PHP versions I am using
Version 6.1.3

### This is a HTML code snippet I use

```
<input type="text" name="bill_number" style="text-align: center value="12" /> - input element is empty
<input type="text" name="bill_number" value="12" /> - input element contains "12"

```
I fixed this issue by adding $val = $objattr['text']; at line 165 in mpdfform.php:

```
if (isset($objattr['text_align']) && $objattr['text_align']) {
	$fieldalign = $objattr['text_align'];
        $val = $objattr['text'];  // <== add this line
} else {
	$val = $objattr['text'];
}
```

**Comment by finwe** [comment]
Thanks!
