### ISSUE TITLE
Fonts folder - google fonts

### ISSUE THREAD

**Issue by colomet** [mpdf/mpdf#395]
### I would like to have this functionality
Is not possible to have a folder without fonts and to use Google fonts or simmilar cloud system of fonts? we have 10 mb or code and 90 mb of fonts.

thanks

### These are mPDF and PHP versions I am using
mPDF 6.1.0
PHP 7.0.18

**Comment by finwe** [comment]
You can set a custom font folder (in 6.1 with `_MPDF_TTFONTPATH` constant). The fonts are now embedded in the repository to simplify working with the library, i plan to separate them in the future.

Unfortunately, I don't think it is possible to use remote fonts at the current version.
