### ISSUE TITLE
composer require mpdf/mpdf installs 6.1 instead of 7.0

### ISSUE THREAD

**Issue by peyman-mohamadpour** [mpdf/mpdf#396]
### These are mPDF and PHP versions I am using

PHP: 7.1

### This is a PHP code snippet I use

```
<?php
composer require mpdf/mpdf

```

**Comment by peyman-mohamadpour** [comment]
Thanks, it was just confusing looking at [documentation home](https://github.com/mpdf/mpdf), as it bolds the **mPDF 7.0** without saying its beta at all

**Comment by peyman-mohamadpour** [comment]
Is there any due date for 7.0 milestone?

**Comment by finwe** [comment]
Answered in #398
