### ISSUE TITLE
Line alignment after break in list

### ISSUE THREAD

**Issue by eduardodallmann** [mpdf/mpdf#397]
### I have this problem/would like to have this functionality
I want to align with the previous line after the line break. Indicated in the image.
![alig](https://cloud.githubusercontent.com/assets/7562936/26020054/aca1dbce-3750-11e7-915f-8229e97958db.jpg)

Can I align this in any way?

### These are mPDF and PHP versions I am using
mPDF 6.1.0 released
PHP 5.6.30

### This is a HTML code snippet I use

```
<table cellspacing="0" cellpadding="2" class="dataChart">
<thead>
  <tr class="caption">
    <th>Norma</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="mce-content-body"><ol>
      <li><strong>Na preparação da atividade</strong>:
        <ol>
        <li>Só será liberado o trabalho em manutenção após a emissão da&nbsp;<strong>OS.</strong></li>
        <li>Antes de iniciar a tarefa, certifique-se que esteja utilizando todos os <strong>EPI's</strong>.</li>
        <li>Somente será realizada por <strong>trabalhadores Habilitados, Qualificados, Capacitados e autorizados </strong>para função.</li>
        <li>Verificar as condições <strong>do local</strong>, se existe algum<strong> risco</strong> adicional a atividade a ser executada.</li>
 ........


```

**Comment by peyman-mohamadpour** [comment]
One simple obvious workaround would be to go with table.

**Comment by eduardodallmann** [comment]
@peyman-mohamadpour  Sorry, it's not obvious to me. Could you give an example?

**Comment by peyman-mohamadpour** [comment]
```
<table>
<tr>
<td>1.</td><td colspan="2">Na preparacao da ...</td>
</tr>
<tr>
<td></td>
<td>1.1.</td>
<td>So sera liberado ...</td>
</tr>
<tr>
<td></td>
<td>1.2.</td>
<td>Antes de iniciar ...</td>
</tr>
</table>
```

**Comment by eduardodallmann** [comment]
I use tinymce as the text editor, and after edited it goes to PDF. Tinymce uses LI tag for lists.

**Comment by peyman-mohamadpour** [comment]
So you are limited by your environment and table is not a way to go.

**Comment by chavash17** [comment]
eduardodallmann can you get solution of this problem?
I want to align with the previous line after the line break. Indicated in the image.

**Comment by chavash17** [comment]
@eduardodallmann  can you get solution of this problem?
I want to align with the previous line after the line break. Indicated in the image.

**Comment by eduardodallmann** [comment]
@chavash17 I did not find a solution

**Comment by finwe** [comment]
Closing as stale.

Seems this should be solved with a `list-style-position` CSS property.

If `list-style-position` does not work, feel free to create a new discussion/issue for the last mPDF version according to current contribution guidelines.
