### ISSUE TITLE
Why mPDF7.0 has no due date?

### ISSUE THREAD

**Issue by peyman-mohamadpour** [mpdf/mpdf#398]
### I have this problem/would like to have this functionality
Thanks for this nice work, I am still eager to know the due date for this milestone. Milestones with no due date tend to take long time to get released.

### These are mPDF and PHP versions I am using
mPDF 7.0 Beta
PHP7.1

**Comment by finwe** [comment]
It has no due date because it is being developed in free time on voluntary basis and release/review iterations take longer.

As 7.0 is a significant codebase change, I would like to be sure there are as few missed quirks and errors as possible.

**Comment by peyman-mohamadpour** [comment]
How could we engage in development process?

**Comment by finwe** [comment]
Test `development` branch on your HTML/CSS/PHP snippets. Compare outputs. Find reasons of regressions noted in [7.0 milestone issues](https://github.com/mpdf/mpdf/milestone/2). If able, send PRs fixing these bugs. Review `development` branch of [the documentation](https://github.com/mpdf/mpdf.github.io). Options are many.

**Comment by marclaporte** [comment]
mPDF 7.0 has been released!
https://github.com/mpdf/mpdf/releases/tag/v7.0.0

Congrats @finwe !!
