### ISSUE TITLE
Problem with crop marks and custom footers

### ISSUE THREAD

**Issue by aerkalov** [mpdf/mpdf#40]
I have been trying to get PDF file with crop marks and custom headers on front matter and content pages. I have put all of my experiments (with code and output PDF files) here - https://github.com/booktype/mPDF-examples

My output files either have no visible page numbers or ToC is broken without page numbers for my chapters.

I am expecting to get this from the output:
- PDF has visible crop marks
- Front Matter (before and including ToC) not to show page numbers
- ToC to show page numbers for my chapters
- Content to show page number on each page

I will also post message to Forum (I applied for an account) and see if someone had similar issue.

**Comment by danielhjames** [comment]
This was a configuration issue, rather than a bug in mPDF. See the fixed example https://github.com/booktype/mPDF-examples/blob/master/01_current.pdf

I think this issue could be closed now.
