### ISSUE TITLE
Must I use composer to get mpdf?

### ISSUE THREAD

**Issue by lewinray** [mpdf/mpdf#403]
### I have this problem/would like to have this functionality
Acrobat Reader 5.0 cannot open my pdf file， which is downloaded through firefox。But I  could print it out directly from firefox.  Further more,  when I use chrome or IE, the pdf could even not be loaded,  it tells to reload the file, but clicking reload dose not help and displays the same problem.

mbstring,mbregex, gd .etc  have been enabled in php

### These are mPDF and PHP versions I am using
mPDF6.0
PHP version 7.0.0

### This is a PHP code snippet I use

```
<?php
	include("../mpdf.php");
	$mpdf = new mPDF(); 


	$mpdf->WriteHTML('<h1>hello world</h1>');
	$mpdf->Output();
	exit;
?>

any problem ? why ????

**Comment by lewinray** [comment]
I got the mpdf6.0 from http://www.mpdf1.com/mpdf/index.php. but package with new version must be installed through composer,   mpdf downloaded from github doesnot include 'autoload.php', which is mostly used in the examples from online manual.

**Comment by finwe** [comment]
There is no need to use composer, you can download mPDF from Github, but you then have to use some standalone autoloader or require classes manually.

Using composer is however much easier.

See #373
