### ISSUE TITLE
Table page-break not working

### ISSUE THREAD

**Issue by supun151515** [mpdf/mpdf#408]
page with header and footer;

Middle has 2 tables.

One table has more data than a page size; The whole table moves to next page. But I want to display rows as much as page can view and jump remaining rows to next page with table headers as well. 

I am using mPDF 6, PHP 5.6

table { page-break-inside:always } NOT WORKING

**Comment by daudmalik06** [comment]
@supun151515  well there is a new library which uses chrome headless as a back-end so no more these kind of problems , give it a try very easy to install and use 
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by exetera** [comment]
I got the same error , and I just found that the problem was on my html code (_thead_ tag not correctly closed)

**Comment by finwe** [comment]
page-break-inside:always is not supported by mPDF. See https://mpdf.github.io/css-stylesheets/supported-css.html
