### ISSUE TITLE
PHP Fatal error:  Cannot redeclare dd()  (Laravel)

### ISSUE THREAD

**Issue by vedmant** [mpdf/mpdf#410]
It looks like mpdf is trying redeclare dd() method that's already declared in Laravel, in needs to be wrapped in ! funciton_exists() condition.

```
HP Fatal error:  Cannot redeclare dd() (previously declared in vendor/laravel/framework/src/Illuminate/Support/helpers.php:510) in vendor/mpdf/mpdf/src/functions.php on line 239
```

### These are mPDF and PHP versions I am using
7.0-beta1

### This is a PHP code snippet I use
on composer require

**Comment by giftnuss** [comment]
In HEAD it is already wrapped with `function_exists`. Please see https://github.com/mpdf/mpdf/blob/master/src/functions.php#L231
