### ISSUE TITLE
Undefined index: cellLineStackingShift

### ISSUE THREAD

**Issue by mikaelz** [mpdf/mpdf#411]
In sentry.io the following error occurs sometimes
![screen shot 2017-05-29 at 08 01 34](https://cloud.githubusercontent.com/assets/454800/26538239/a0f13e6c-4445-11e7-9c11-b850e7e6dac8.png)

mpdf version: 6.1.3
PHP version: 7.0.15

Code:
```
<?php

        $pdf = new mPDF('', 'A4', 9, 'dejavusans', 10, 10);
        $pdf->SetHTMLFooter(
            $this->render('AppCoreBundle:Document:pdf_footer.html.twig', [
            'document' => $document,
            'language' => $language,
            ])->getContent()
        );
        $pdf->cacheTables = true;
        $pdf->shrink_tables_to_fit = true;
        $pdf->WriteHTML($html);  // error is reported at this line


```

**Comment by Klap-in** [comment]
Could you reproduce these errors with the latest development version (mpdf 7) as well? This mpdf version has already a lot of improvements for these kind of errors.

If you could still reproduce it with mpdf 7, could you please look which part of your html trigger these errors? And could you share that html here? Thanks!

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
