### ISSUE TITLE
How to get min version of mpdf v6 ?

### ISSUE THREAD

**Issue by abude** [mpdf/mpdf#416]
Hi,

### I have this problem/would like to have this functionality
I'm using mpdf library in my project via kartik-v/yii2-mpdf wrapper.
PHP version : 5.4, mpdf version : 6.1.0

The issue is that i just realised that there's a ttfonts folder in my vendor containing fonts with a total size of 105MB, which it's pretty much for my project.

Is there a way, to use mpdf library with minimum fonts? so at the end i won't have that size for fonts.

Thank you for your time!

**Comment by finwe** [comment]
Hi, not with composer and its dependency system. Only by downloading 6.1.0 from Github release, there already is a ZIP with fonts ommited.
