### ISSUE TITLE
"Compress" Functionality generating syntax errors

### ISSUE THREAD

**Issue by youvtr** [mpdf/mpdf#417]
### I have this problem/would like to have this functionality
The "compress" on "Reducing Memory usage" topic of online guide not works as expected. 
This may generate a new mpdf.php with various sintax error of "if's" and "else's" with no close brackets "}"

### These are mPDF and PHP versions I am using
mPDF 6.1
PHP 7.0.10 (wamp server)
Windows 7 64bits

### Steps to Reproduce

1. open a terminal and install mPDF via composer with command "composer require mpdf/mpdf"
2. rename /<root>/vendor/mpdf/mpdf/mpdf.php to <root>vendor/mpdf/mpdf/mpdf_source.php
3. Point your browser to http://<domain>/vendor/mpdf/mpdf/compress.php
4. Click on "generate" button at bottom of page

The page responds with "Parse error: syntax error, unexpected 'else' (T_ELSE) in C:\wamp7\www\pdf\vendor\mpdf\mpdf\mpdf.php on line 3052"

Opening new generated file at 3052 line, there are no closing ("}") bracket on opened of "if" steatment.

And i think the "compress" functionality not works  becouse the new file still over 1MB

**Comment by finwe** [comment]
See #306, #310, #365
