### ISSUE TITLE
How to create multiple PDFs?

### ISSUE THREAD

**Issue by vickyraj1521** [mpdf/mpdf#418]
I have two functions. 1st for creating a Debit Note and 2nd for creating Invoice. I call Debit Note Function first and then Invoice function. The content of both files appears to be Debit Note. However the file names seems to be correct for both the files.

When I call Invoice function 1st and then Debit Note function. The content of both the files appears to be Invoice and the file names seems to be correct for both the file.

PS: I am calling both the functions together.

$this->mpdf->setAutoTopMargin = 'stretch';
$this->mpdf->setAutoBottomMargin = 'stretch';
$this->mpdf->SetHTMLHeader($this->pdftemplate->Header());
$this->mpdf->SetHTMLFooter($this->pdftemplate->Footer());
$html = $this->pdftemplate->debitNote($debitNoteNo, $narration, $amount);
$this->mpdf->WriteHTML($html);
$url = "/temp/dn/" . $debitNoteNo . ".pdf";
$this->mpdf->Output($url, "F");

$this->mpdf->setAutoTopMargin = 'stretch';
$this->mpdf->setAutoBottomMargin = 'stretch';
$this->mpdf->SetHTMLHeader($this->pdftemplate->Header());
$this->mpdf->SetHTMLFooter($this->pdftemplate->Footer());
$html = $this->pdftemplate->invoice($invoiceNo, $narration, $amount);
$this->mpdf->WriteHTML($html);
$url = "/temp/invoice/" . $invoiceNo . ".pdf";
$this->mpdf->Output($url, "F");

Can anyone help me with this? Thanks for reading the question and your valuable answers.

**Comment by finwe** [comment]
Create a separate clear `new mPDF()` object for each generated file.

**Comment by vickyraj1521** [comment]
Appreciate your help. Thanks a lot.

**Comment by blacktornado** [comment]
thanks for the help
