### ISSUE TITLE
Problem with config_fonts.php

### ISSUE THREAD

**Issue by FZ253** [mpdf/mpdf#42]
I have imported mpdf class with composer (including it in **composer.json**) and I tried to use my own TrueType Fonts.
I know that I can modify config_fonts.php and copy my fonts to ttfonts directory, but when I tried to work with a repository (Here is where I needed composer.json) I couldn't find a solution to use my fonts. 
I tried to solve this by the definition of the constants MPDF_SYSTEM_TTFONTS, MPDF_TTFONTPATHand MPDF_TTFONTDATAPATH but it didn't helped because my problem was config_fonts.php.
Then, I put this:

```
$pdf = new mPDF('utf-8','A4','','Foco',0,0,23,0,0,0,'');
$pdf->fontdata = array(
	"foco" => array(
		'R' => "Foco_Rg.ttf",
		'B' => "Foco_0.ttf",
		'I' => "Foco_Lt.ttf",
		),
	);
```

But when I tried to export my pdf file I got this error:

**mPDF Error - Font is not supported - dejavusanscondensed**

I searched but I didn't found how to solve it.

**Comment by blueliquiddesigns** [comment]
You don't want to override the entire `fontdata` array (which is what you are doing). Instead, add your new record on the end of it.

`
$pdf->fontdata['foco'] = array(
        'R' => "Foco_Rg.ttf",
        'B' => "Foco_0.ttf",
        'I' => "Foco_Lt.ttf",
); 
`

Then ensure your TTF font files are stored in the `ttfonts` directory.
