### ISSUE TITLE
Need to write pdf under SFTP owner

### ISSUE THREAD

**Issue by vtulse** [mpdf/mpdf#426]
### I have this problem/would like to have this functionality
Is it possible to write the pdf using SFTP?
$mpdf->Output( drupal_realpath($path)."/".$filename, 'F');

This will create file but under owner of Apache group.

We want to create the file under owner our SFTP group.

Someone with Apache group can delete the file which I have to prevent by creating our SFTP.

**Comment by finwe** [comment]
You would probably have to write via SFTP connection. See https://stackoverflow.com/questions/4689540/how-to-sftp-with-php

**Comment by vtulse** [comment]
Thank you

**Comment by vtulse** [comment]
Sorry for irrelevant question but how to print special charecter like cent,
we are geting problem to print in pdf it coming eg À


On Tuesday, June 27, 2017, vipul tulse <vipultulse1@gmail.com> wrote:
> Thank you
>
> On Tue, Jun 27, 2017 at 6:12 PM, Matěj Humpál <notifications@github.com>
wrote:
>>
>> Closed #426.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/QZ_Ca2xyp6_KtLncY1HIiY9SLI2zOnT3OqCHiRtktVfdemhpR9WX97K8WP_NeWjSBEC6VbEPwnNYAoECpqfGgZSiy_YEuW-_r6BKg78oWWrKRQ76bnm-OFsyhtgSby_KeVXn-U0r4rCsPvCHBckIryU97AI2Ow=s0-d-e1-ft#https://github.com/notifications/beacon/AZXmcz232MnzzurD-u0Fwd0uG-8Vx11Yks5sIPjPgaJpZM4OGhBa.gif
>
>

**Comment by finwe** [comment]
Is your input in UTF8? Does the font you are using support the character?

**Comment by vtulse** [comment]
Im using arial font and the special character symbol is cent symbol

On Wednesday, June 28, 2017, Matěj Humpál <notifications@github.com> wrote:
> Is your input in UTF8? Does the font you are using support the character?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/Nys04A-kyiWasBqGZDQigsE48auxAcCdWiUaeDVuAutnnexYysSUX8ivjPicOY6AFLwoLUkCO1CbU_BzGXCTTpRDANTpiBmQWyjU1dm0cc4yn_2x99La2RpaauvmG7xcjSxoAZFP25buXXVXpDmIGiyVjfuwGw=s0-d-e1-ft#https://github.com/notifications/beacon/AZXmc7QngLf_U7rn1Q3Vxw6bI87P0Jliks5sIekygaJpZM4OGhBa.gif>
