### ISSUE TITLE
Not able to print the spacial character into pdf 

### ISSUE THREAD

**Issue by vtulse** [mpdf/mpdf#427]
### I have this problem/would like to have this functionality

Not able to print the spacial character into pdf 
Tried with utf8_encode()
I'm trying to print ¢ and using Arial font

![06 27 17 overnight pdf](https://user-images.githubusercontent.com/26601075/27627608-117f4cc4-5c0a-11e7-8708-5ce9b1787bb3.png)

**Comment by Klap-in** [comment]
Please provide more information for others to reproduce/understand your situation. Thanks!

    ### These are mPDF and PHP versions I am using
    
    ### This is a PHP code snippet I use

    ```
    <?php
    
    
    ```
     
    ### This is a HTML code snippet I use
    
    ```
    
    ```

**Comment by vtulse** [comment]
$mpdf->WriteHTML(utf8_encode($html))

printing simple html but the data from database contain the ¢ symbol.
When "am generating the pdf the symbol come with Â¢

**Comment by vtulse** [comment]
Removed utf8_encode() now working fine.
Tank you Gerrit Uitslag
