### ISSUE TITLE
P Margin

### ISSUE THREAD

**Issue by johnw6761** [mpdf/mpdf#431]
No matter what CSS use I cant seem to apply a margin to my P elements therefore there is no spacing between them?

mPDF 6.1.0

![a1](https://user-images.githubusercontent.com/9976925/27835185-eaf08934-60d1-11e7-8810-4e22abea9555.PNG)
![a2](https://user-images.githubusercontent.com/9976925/27835184-eaefafb4-60d1-11e7-8de2-7f0cf377583e.PNG)

**Comment by HKandulla** [comment]
I had the same problem and I think it only occours for elements inside a table.

**Comment by daudmalik06** [comment]
@johnw6761 @HKandulla well there is a new library which uses chrome headless as a back-end so no more these kind of problems , give it a try very easy to install and use 
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by lebreRafael** [comment]
At the [Limitations](https://mpdf.github.io/about-mpdf/limitations.html) section of the documentation we can find the phrase below.

> Block elements (e.g. DIV or P) are not supported inside tables. The content is displayed, but any CSS properties which apply to block elements are ignored (e.g. borders, padding, margins etc).
