### ISSUE TITLE
Table heading issue

### ISSUE THREAD

**Issue by vtulse** [mpdf/mpdf#433]
### I have this problem/would like to have this functionality

How we can ovoid such type of wrapping of table heading repeat and second page table heading alignment
Please see image. 
![pdf image](https://user-images.githubusercontent.com/26601075/27857333-e81c0c52-618e-11e7-873d-111bacc85fe4.JPG)

**Comment by daudmalik06** [comment]
@vtulse well there is a new library which uses chrome headless as a back-end so no more these kind of problems , give it a try very easy to install and use 
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen, if still applicable on current version.
