### ISSUE TITLE
Class 'mpdf' not found in laravel 5.4

### ISSUE THREAD

**Issue by aitldev5** [mpdf/mpdf#436]
I am user "mpdf/mpdf": "^6.1". in  laravel 5.4 project. This shows up when i am using this code

`$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('<h1>Hello world!</h1>');
$mpdf->Output();`

and i don't know how to required_once mpdf in laravel. 

![screencapture-localhost-whitebazar-public-admin-payment-export-1499494065825](https://user-images.githubusercontent.com/29995818/27983092-53b6819c-63d6-11e7-8a06-29ab2e73eed4.png)

Thanks.

**Comment by finwe** [comment]
`$mpdf = new mPDF();` for version 6.1.

**Comment by aitldev5** [comment]
Thanks for your help. Its working now.
