### ISSUE TITLE
strange character displayed

### ISSUE THREAD

**Issue by JohnZakaria** [mpdf/mpdf#437]
![2017-07-09_112336](https://user-images.githubusercontent.com/71310/27992619-38ef05a0-6499-11e7-8720-8318a0fa6f1a.jpg)
### hi dears i have a problem when creating PDF it gives for me like the attached print screent and give loading only for page and dont create the file

any idea?

**Comment by finwe** [comment]
You are probably resetting page content-type to text/html after calling mPDF::Output().

**Comment by db-dzine** [comment]
Check that mbstring extension for PHP is installed.

**Comment by finwe** [comment]
Closing as not-a-bug and stale.
