### ISSUE TITLE
Error failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by dogrocker** [mpdf/mpdf#44]
I just use the Getting start from

http://mpdf1.com/manual/index.php?tid=106

```
$mpdf=new mPDF();
$mpdf->WriteHTML('<p>Hallo World</p>');
$mpdf->Output();
exit;
```

and got this error.

```
include(/var/www/svn_data/skeletonapp/mpdf/ttfontdata/dejavuserifcondensed.mtx.php): failed to open stream: No such file or directory
```

**Comment by blueliquiddesigns** [comment]
Check your server can write to the `/var/www/svn_data/skeletonapp/mpdf/ttfontdata/` directory. Once it can you should be able to generate the PDF.

**Comment by dogrocker** [comment]
@blueliquiddesigns,

This is my perm on `ttfontdata`

```
drwxrwxrwx 1 www-data www-data     102 Aug 13 14:11 ttfontdata/
```

**Comment by dogrocker** [comment]
All of my folder in `vendor/mpdf` is now chmod to `777`.

But it got the same error.

**Comment by blueliquiddesigns** [comment]
Very strange. Maybe one of the other devs can shed some light on the issue.

**Comment by dogrocker** [comment]
I think this is issue only on devs that use `linux or unix`. Because I try to use it on `Windows` and it work!.

But my dev tools is mac, So now it very hard for me to code with this libs.

**Comment by blueliquiddesigns** [comment]
I'm glad you've been able to get it working. 

I have my doubts about it being specific to Linux / Unix (I use the software exclusively on this platform). The error still suggests a misconfiguration or permissions problems at play here.

**Comment by dogrocker** [comment]
Hello @blueliquiddesigns , I fixed this problem by using version 6.0.

**Comment by lizbanach** [comment]
I have the same issue. Why is this closed when there is no solution?

**Comment by MGParisi** [comment]
The latest version, and the permissions change seems to be the solution people gave.  

I believe I abandoned the library and the idea and urged the client to NOT use PDF's.  I tried 3 solutions and none of them presented very good results.   The pages we needed them on would of needed massive rewrites as they often used GRIDs and other things.  

We use to do it for printing, and I got a client using DKPDF, but I will be wise and advise only the people who want to spend the cost for a custom version to be written.  Its often what has been needed.

Also,  Chrome support for PDF's is VERY broken leaving most users with white pages.  There are fixes if you turn off "Accelerated Browsing" or if you download a 3rd party plugin.  But Im finding the tech is hurting.  These PDF's generators don't help the problem and even for printing they do not provide the save feature as the @print tags in CSS.  I looked for commercially available products and they where as restrictive.  

Its best to write the actual PDF, and not an interpretation off the rendering of some command line browser on the Linux platforms we run.  

I suspect though that there maybe better solutions in .NET.

And there really is nothing very good available for PDF generations.

**Comment by divinecodes** [comment]
Currently experiencing same issue with laravel 8 and mpdf 8: Fixed By adding the public folder to the export location file name 

` $pdf = new \Mpdf\Mpdf([
                'margin_left'=> 3,
                'margin_right'=> 3,
                'margin_top'=> 5, 
                'margin_bottom'=> 5,
                'margin_header'=> 5, 
                'margin_footer'=> 5, 
                'orientation'=> $orientation,
                'mode'=> 'utf-8',
                'tempDir' => __DIR__.'/temp'
            ]);
    
            $pdf->setTitle($title); 
            $pdf->setDisplayMode('fullpage');
    
            $pdf->WriteHTML($html); 
            $filename ="exports/pdf/".time().".pdf";
            $exportLocation = "public/".$filename;
            
            $pdf->Output($exportLocation, \Mpdf\Output\Destination::FILE); 
            
            return asset("/$filename");`

**Comment by divinecodes** [comment]
Currently experiencing same issue with laravel 8 and mpdf 8: Fixed By adding the public folder to the export location file name
` $pdf = new \Mpdf\Mpdf([
                'margin_left'=> 3,
                'margin_right'=> 3,
                'margin_top'=> 5, 
                'margin_bottom'=> 5,
                'margin_header'=> 5, 
                'margin_footer'=> 5, 
                'orientation'=> $orientation,
                'mode'=> 'utf-8',
                'tempDir' => __DIR__.'/temp'
            ]);
    
        $pdf->setTitle($title); 
        $pdf->setDisplayMode('fullpage');
    
        $pdf->WriteHTML($html); 
        $filename ="exports/pdf/".time().".pdf";
        $exportLocation = "public/".$filename;
            
       $pdf->Output($exportLocation, \Mpdf\Output\Destination::FILE); `

**Comment by divinecodes** [comment]
Currently experiencing same issue with laravel 8 and mpdf 8: Fixed By adding the public folder to the export location file name
`$pdf = new Mpdf(['orientation'=> $orientation]);
 $pdf->setTitle($title); 
 $pdf->setDisplayMode('fullpage');
    
 $pdf->WriteHTML($html); 
 $filename ="exports/pdf/".time().".pdf";
 $exportLocation = "public/".$filename;
            
 $pdf->Output($exportLocation, \Mpdf\Output\Destination::FILE); 
            
 return asset("/$filename");`

**Comment by divinecodes** [comment]
Currently experiencing same issue with laravel 8 and mpdf 8: Fixed By adding the public folder to the export location file name
` 
           $pdf->setTitle($title); 
            $pdf->setDisplayMode('fullpage');
    
            $pdf->WriteHTML($html); 
            $filename ="exports/pdf/".time().".pdf";
            $exportLocation = "public/".$filename;
            
            $pdf->Output($exportLocation, \Mpdf\Output\Destination::FILE); `

**Comment by Klap-in** [comment]
And $html, $orientation, $title  could be anything, e.g. `$html='<p>Hallo World</p>'`?
Could tell a bit about the permissions of the folder. Does this subfolder has different permissions  then its parent?

is everybody in this thread with this issue using laravel?

**Comment by finwe** [comment]
Please, stop resurrecting ancient closed threads with most likely unrelated information.
