### ISSUE TITLE
Issue while trying to print 0 in pdf

### ISSUE THREAD

**Issue by rathodakshay** [mpdf/mpdf#442]
There is an issue when I tried to push html having value 0 in span it ignores that span see my my below code.

I am using mPDF : 6.1 and PHP : 5.6
`
<span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">You have </span><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">0</span><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;"> public records. </span></div>`

This output as

> You have  Public records

If I use below code it works well
`
<span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">You have </span><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;">$0</span><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline;"> public records. </span></div>`

This output as

> You have $o public records

 which is fine. Am I missing anything?

**Comment by finwe** [comment]
This is fixed in current development version.

**Comment by rathodakshay** [comment]
Okay so is that released? or we need to wait more for this?

**Comment by finwe** [comment]
Not yet and it does not have a release date. You could use dev version (or 7.0.0-beta2) version, however there are still faily critical bugs - mainly broken fixed and absolute positioned elements.

**Comment by rathodakshay** [comment]
Great. Thanks for sharing this @finwe .
