### ISSUE TITLE
Using mpdf/mpdf (v7.0.0-beta1) with Laravel 5.2 - redeclaring method dd()

### ISSUE THREAD

**Issue by gthedev** [mpdf/mpdf#445]
When installing/using mpdf v7.0.0-beta1 with Laravel 5.2 I get the following error:

> Fatal error: Cannot redeclare dd() (previously declared in \vendor\laravel\framework\src\Illuminate\Support\helpers.php:510) in \vendor\mpdf\mpdf\src\functions.php on line 239

Is there any config available to avoid declaring global functions, or at least to check that they don't exist before declaring them?

**Comment by finwe** [comment]
If you have problems with redeclared dd function, commit https://github.com/mpdf/mpdf/commit/bf523b775ea0203a17085f1d50d3103e01486ba9 should help you - the function is then loaded only in composer dev environment. there is no release including this fix yet, though.
