### ISSUE TITLE
Psr\Log\LoggerAwareInterface not found

### ISSUE THREAD

**Issue by didiergm** [mpdf/mpdf#448]
I can't generate a pdf using writehtml. 
Linux Mint; Php 7.1;

mPDF 7.0 Development branch uploaded today,  July 21st; 

Error message 
Fatal error: Interface 'Psr\Log\LoggerAwareInterface' not found

This is not listed in the requirements and I can't find anything in the Zip file, so I am not sure what to do next

**Comment by finwe** [comment]
Dependencies are listed in composer.json file.

If not using composer, you have to include libraries listed in `require` field manually.

**Comment by didiergm** [comment]
Thanks, what confused me is that the manual does not list all the dependencies, I had to manually look into the composer.json file
