### ISSUE TITLE
All my svg images get filled with black color

### ISSUE THREAD

**Issue by Samz3n** [mpdf/mpdf#450]
Hi all,

When I try to embed an image-tag with a svg file
`<img src="/path-to-image/logo.svg">`

It will get filled with black color when exported to PDF.

The fill-color get overruled by the construct function in "/classes/svg.php"
`$this->svg_style = array(
	array(
		'fill' => 'black',
		...
	)
);`

How can I avoid it from happen? My logo has multiple color.

**Comment by Samz3n** [comment]
I found a working solution.
It is working when I save my .svg files from Inkscape. 
More complex vector files won't work when saving from Illustrator. 

- I tried testing it a little bit more. 
I succeeded to save to working logos in right colors from Illustrator (however I had to modify the code a little bit for one of them).

I also have a more complex vector image with a lot of shapes. I cannot save a working .svg file for this vector from Illustrator but it works when I save from Inkscape.

**Comment by finwe** [comment]
can you please provide examples of both working and faulty svg files?

**Comment by Samz3n** [comment]
It is working when I save .svg files from Inkscape.

**PDF examples generated with mpdf:**
Because I changed:
`$this->svg_style = array( array( 'fill' => 'black', ... ) );` to `'fill' => 'yellow'`
You will see yellow shapes instead of black :)

**From Illustrator:**
// Different export settings (inline style, presentation attributes and tried to "Save As" and "Export As")
[1.pdf](https://github.com/mpdf/mpdf/files/1175992/1.pdf)
[2.pdf](https://github.com/mpdf/mpdf/files/1175993/2.pdf)
[3.pdf](https://github.com/mpdf/mpdf/files/1175990/3.pdf)
[4.pdf](https://github.com/mpdf/mpdf/files/1175991/4.pdf)

**From Inkscape:** 
// I needed to clean up the vector (outline text and release elements from compound path)
[5.pdf](https://github.com/mpdf/mpdf/files/1175994/5.pdf)


I also had some trouble with two different logos from Illustrator. 
I managed to get the colors right by using the inline-style option.

**Comment by treedbk** [comment]
I had a similar problem where my company's logo was rendering in all black instead of the color specified in the svg file. This svg file was also exported from Illustrator. For some reason mpdf doesnt seem to recognize the color specified by the CSS in the svg file.

I fixed the problem by adding inline styles for each <g> tag. 

Each opening`<g>` tag needs to have an inline fill attribute: 

`<g style="fill: rgb(0,94,184);">` 

Or whatever color you need to appear. This worked fine for me since our logo is all one color. Images with more colors, this might not be the best solution. 

I just wanted to share in case anyone else has a similar problem.

**Comment by Klap-in** [comment]
If you could share example svgs (working and not working), these are very welcome!
That helps for quickly creating tests for this case. Thanks!

**Comment by Jako** [comment]
I send a working/not working logo by mail. The main difference between those are a style section + classes for the paths (not working) and direct fill attributes for the paths (working).

```
<style type="text/css">
	.st0{fill:#E30613;}
</style>
<path class="st0" d="M303.9,54.9c-2.5,10.8-5.1,13.2-13.5,13.2h-8.3c-5.9,0-7.4-1.3-7.4-6.5V35.7h16.5c4.4,0,5.9,2.3,6.2,8.8h2.1
		V24h-2.1c-0.3,7.1-1.5,8.7-6.2,8.7h-16.5V3.2h16.3c7,0,9.2,2.2,11.9,12h2l-1.4-15h-44.6v2.1c7.6,0.6,8.7,1.5,8.7,6.9V62
		c0,5.5-1.1,6.3-8.7,7v2h45l2.1-16.1H303.9L303.9,54.9z"/>
```
vs.
```
<path fill="#E30613" d="M303.9,54.9c-2.5,10.8-5.1,13.2-13.5,13.2h-8.3c-5.9,0-7.4-1.3-7.4-6.5V35.7h16.5c4.4,0,5.9,2.3,6.2,8.8
		h2.1V24h-2.1c-0.3,7.1-1.5,8.7-6.2,8.7h-16.5V3.2h16.3c7,0,9.2,2.2,11.9,12h2l-1.4-15h-44.6v2.1c7.6,0.6,8.7,1.5,8.7,6.9V62
		c0,5.5-1.1,6.3-8.7,7v2h45l2.1-16.1H303.9L303.9,54.9z"/>
```

Exporting the logo in Illustrator as Tiny SVG 1.2 did the trick.

**Comment by dustingraham** [comment]
Can confirm, received an SVG from our marketing department, it had the <style> tags, and everything was black. Manually editing the file in a text editor, and adding the fill to the path, now shows the correct color in the mpdf generated pdf.

**Comment by zhil** [comment]
+1 for this issue
trying to use chart library http://topnew.net/chart/#main21 , but styles are not working for SVG

**Comment by Klap-in** [comment]
@zhil You are sure your case is covered by the examples from above? If not, please add your examples.

**Comment by frerova91** [comment]
I also have a lot problems exporting svg from Adobe XD with css properties for web embed. the solution was simple when you export your files individually. you need to be careful and have a eye on the css class because the program will export your files with the same css class.

inside of svg on the tags <style>, and inside of the <path> where is assigned the class. I was playing with css grid when i see the problem here is the pen if anyone want to see the html svg.

https://codepen.io/unrealgraw/pen/omdaGL

**Comment by kritikaperiwal12** [comment]
Hello,
While showing SVG file on view using Pocket SVG Framework it is showing black color filled. Please tell me the reason behind it.

**Comment by greta87** [comment]
We found that version inkscape didn't work on our Macs but Figma worked great and Sketch might too for saving svgs. So yes it seems to be an Adobe Illustrator issue for complicated svgs. Thanks for this post it helped.

**Comment by antman3351** [comment]
Hello, I've patched the issue ( I simply added a function that copies the styles from the style block to an inline style ). Only thing is I'm clueless on how to make a pull request.

P.s also I didn't write a unit test because I'm not sure how to test the issue.

**Comment by bitsvital** [comment]
In Adobe Illustrator all you need to do is:
File-->Export for Screens
Choose SVG
Click the settings "gear" icon on the opposite side of "Format"
Choose SVG
For Styling choose: Inline Style
For Font choose: Convert to outline
Click "Save Settings"
Export the SVG
Bingo! There ya go :) A working SVG in Musescore.
Hope that helps!

**Comment by mplusdaya** [comment]
How to apply above solution to <img> tag with .svg file

**Comment by mplusdaya** [comment]
I'm getting black box filled for img tag with .svg image.?? how to solve this in mpdf

**Comment by Klap-in** [comment]
Please use first https://stackoverflow.com/questions/tagged/mpdf for investigation, discussion and troubleshooting your situation

If you found by this effort a case that is not supported correctly by mpdf, please share then your case _with_ a small as possible example of your tested php + html + SVG-file. Thanks for the effort.

**Comment by mudi256** [comment]
Use https://vecta.io/nano It can remove the unsupported tags such as and compress the svg file at certain level

**Comment by walataza** [comment]
Incase some still comes across this error

<embed name="xxx" id="xxxxx" src="img/xxxx.svg" idth="145" height="131">

works perfectly, after i used the embed tag, the black background goes off. I believe this is because PNGs are transparent hence.
 But i believe this should work

**Comment by vijaykesavan-ads** [comment]
not at all working
