### ISSUE TITLE
useSubstitutions not working for CJK characters?

### ISSUE THREAD

**Issue by BjrnS** [mpdf/mpdf#452]
Hi, 
we are working with texts that can occasionally have a mix of different languages in them, for example German and Traditional Chinese.
My understanding from the mPDF docu was that the setting useSubstitutions = true; should be enough to pull the missing glyphs from the backupSIPFont.

I just pulled the latest mPDF via composer (6.1) , my test server is a ubuntu 16.04 with PHP 7.0

I used basically the default settings (which means, there is a backupSIPFont defined) and made just this change in config.php:
```
<?php 

$this->useSubstitutions = true;

```
my test code boils down to this:
```
<?php

$mpdf = new mPDF('UTF-8');
//$html = 'some ÄÜmlautß and traditional Chinese: ' . "\xe6\x86\x82\xe9\xac\xb1";
$html = 'some ÄÜmlautß and traditional Chinese: 憂鬱';
$mpdf->WriteHTML($html); 
$mpdf->Output();
?>
```
the resulting PDF file shows just two rectangles instead of the chinese characters.

strangly (for me) the PDF renders correctly if I use the auto lang settings (in config.php):

```
<?php

$this->autoScriptToLang = true; 
$this->autoLangToFont = true; 

$this->useSubstitutions = true; // true or false makes no difference in this case

?>
```

**Comment by milansimek** [comment]
This also doesn't work for me. Chinese characters are not substituted.

**Comment by milansimek** [comment]
Found a fix for the problem (by reading the comments in config_fonts.php):

In config_fonts.php change the following line:

`$this->backupSubsFont = array('dejavusanscondensed', 'freeserif'); `

Into:

`$this->backupSubsFont = array('dejavusanscondensed','arialunicodems','sun-exta');	`

**Comment by vever001** [comment]
Thank you very much for this! Saved my day ;)
I used this:
```
$mpdf = new mPDF('UTF-8', $format);
$mpdf->useSubstitutions = TRUE;
$mpdf->autoScriptToLang = TRUE;
$mpdf->autoLangToFont = TRUE;
$mpdf->allow_charset_conversion = TRUE;
$mpdf->backupSubsFont = array(
  'dejavusanscondensed',
  'arialunicodems',
  'sun-exta',
);
```

**Comment by finwe** [comment]
Sun extra was added as a default backupsups font a while ago. Closing.
