### ISSUE TITLE
The each() function is deprecated in PHP7.2.

### ISSUE THREAD

**Issue by ildar-aim** [mpdf/mpdf#453]
### I have this problem/would like to have this functionality
The each() function is deprecated in PHP7.2.
https://wiki.php.net/rfc/deprecations_php_7_2#each
http://php.net/each

### These are mPDF and PHP versions I am using
php7.2beta1 mPDF6.1

### This is a PHP code snippet I use

```
<?php

./setasign/fpdi/fpdi.php:562:                while (list($k, $v) = each($value[1])) {
./mpdf/mpdf/mpdf.php:10894:		while (list($file, $info) = each($this->images)) {
./mpdf/mpdf/mpdf.php:13040:		while (list($file, $info) = each($this->formobjects)) {
./mpdf/mpdf/mpdf.php:26351:						while (list($k, $v) = each($tpl['resources'][1])) {
./mpdf/mpdf/mpdf.php:26353:								while (list($k2, $v2) = each($v[1])) {
./mpdf/mpdf/mpdf.php:31096:				while (list($k, $v) = each($value[1])) {

```

**Comment by finwe** [comment]
Fixed in development branch. For fpdi you will however have to fill a separate issue in Setasign/FPDI repository.

**Comment by craigcarnell** [comment]
@finwe Still get this issue even now? Version is mPDF 7.1.x

**Comment by finwe** [comment]
@craigcarnell not helpful, without error file and line, and/or example code. doubt about 7.1, there is no each present in the codebase. if convinced you're right, create a new issue.

**Comment by craigcarnell** [comment]
@finwe 

```
[2018-12-12 10:51:35] report.ERROR: Deprecated Functionality: The each() function is deprecated. This message will be suppressed on further calls in lib/internal/mPdf/mpdf.php on line 9666 [] []
```

I take it back, apologies, it appears my application has both mpdf 7.1 and also an older version.. I'll remove it :)
