### ISSUE TITLE
Index - Letters not sorted

### ISSUE THREAD

**Issue by db-dzine** [mpdf/mpdf#455]
### These are mPDF and PHP versions I am using
PHP 7.0
MPDF 6

![index-mixed](https://user-images.githubusercontent.com/3169388/28637019-5bd9ef08-7240-11e7-90f8-5797324e9df7.png)

**Comment by db-dzine** [comment]
Any idea here? This only happens when there are multiple "tocentry" ...

**Comment by Klap-in** [comment]
Do you have an reduced example of your php and html that reproduce this case? thanks!

**Comment by db-dzine** [comment]
Nevermind ... we defined a cmp function in our script. This CMP function has overwritten the one from mPDF. Sorry.
