### ISSUE TITLE
[PHP 7.1] Another numeric value error

### ISSUE THREAD

**Issue by sebastianblum** [mpdf/mpdf#457]
### I have this problem/would like to have this functionality
With our PDF files, we get this error.

Warning: A non-numeric value encountered in /Users/xxx/PhpstormProjects/xxx/vendor/mpdf/mpdf/mpdf.php on line 25843

Warning: A non-numeric value encountered in /Users/xxx/PhpstormProjects/xxx/vendor/mpdf/mpdf/mpdf.php on line 25848

### These are mPDF and PHP versions I am using
7.0.0-beta2
dev-master (f3bbfc7133aed4b7bbdc22b243883bf552558211)

### This is a PHP code snippet I use

```
<?php

require __DIR__.'/../vendor/autoload.php';

$pdfDir = '/Users/xxx/Downloads/pdfs';

$pdfFilePaths = glob(sprintf('%s/*.pdf', $pdfDir));

$mpdf = new  \Mpdf\Mpdf();
$mpdf->debug = true;
$mpdf->SetImportUse();

foreach ($pdfFilePaths as $pdfFilePath) {
    $pagecount = $mpdf->SetSourceFile($pdfFilePath);

    for($i=0; $i < $pagecount; $i++){
        $mpdf->AddPage();
        $template = $mpdf->importPage($i+1, $pdfFilePath);
        $mpdf->useTemplate($template);
    }
}

$mpdf->Output();
```

### This is a HTML code snippet I use
no HTML files

We open existing PDF-files with 1 or several pages and merge them together to one pdf file.

### Solution
I will create a pull request later with unit-tests.

**Comment by sebastianblum** [comment]
here was 1 error:

1) Issues\Issue457Test::testMergePdfFilesWithPHP71
A non-numeric value encountered

/Users/sebiprivat/PhpstormProjects/mpdf/src/Mpdf.php:24416
/Users/sebiprivat/PhpstormProjects/mpdf/src/Mpdf.php:24882
/Users/sebiprivat/PhpstormProjects/mpdf/src/Mpdf.php:11236
/Users/sebiprivat/PhpstormProjects/mpdf/src/Mpdf.php:1976
/Users/sebiprivat/PhpstormProjects/mpdf/src/Mpdf.php:9119
/Users/sebiprivat/PhpstormProjects/mpdf/tests/Issues/Issue457Test.php:21


I can reproduce it with an unit-test now and will now work on the pull request.

**Comment by JanSlabon** [comment]
I just stumbled over this issue... could you please share the resulting PDF document?
Did you checked the values you're casting to float? What were their type and content before their were casted?

**Comment by sebastianblum** [comment]
@JanSlabon in our case the values are empty strings. The PDF document is attached in the unit-test.
why do you ask this question? do you have problems or do you prefer another solution as floatval?

**Comment by JanSlabon** [comment]
@sebastianblum I do not have any problem but FPDI is developed by our company and this code is related to its functionalities.
An empty string looks like another issue for me and we should resolve where and why a bounding box (which describes the bounding box of the imported page) has non-numeric values instead of the correct values instead of simply casting them to floats.
I've actually no time but maybe in the coming days I can check this more deeper.

**Comment by sebastianblum** [comment]
@JanSlabon I googled a lot and found other forks where the problem was solved by the floatval function. So I also used the floatval code.

To reproduce I added this unit-test case with pdf file:
https://github.com/sebastianblum/mpdf/blob/f35ea6b32b0896abf8d2accecc95eeb5b195ede4/tests/Issues/Issue457Test.php
https://github.com/sebastianblum/mpdf/blob/f35ea6b32b0896abf8d2accecc95eeb5b195ede4/tests/data/pdfs/2-Page-PDF_1_3.pdf (I found in the internet - the file was really small)

**Comment by JanSlabon** [comment]
As I guessed it is not a problem of the code in mPDF but you are simply passing an invalid parameter to the importPage() method:

    $template = $this->mpdf->importPage($i, $pdfFilePath); // you pass a string as the 2nd parameter

While the signature is:

    function ImportPage($pageno = 1, $crop_x = null, $crop_y = null, $crop_w = 0, $crop_h = 0, $boxName = '/CropBox')

@finwe You should remove this "fix" asap, because it only hides an invalid passed argument.

**Comment by finwe** [comment]
@JanSlabon Reverted. Thanks a lot for looking into this!

**Comment by sebastianblum** [comment]
Oh sorry, this unit-test is really wrong and used the wrong signature.

**Comment by sebastianblum** [comment]
@JanSlabon thank you very much for checking this stupid pull request.
Now I found a new solution to solve my initial problem.

The unit-test showed the same behaviour like my initial problem, but was totally wrong.

**Comment by JanSlabon** [comment]
@sebastianblum You're welcome!

**Comment by Klap-in** [comment]
The unit tests prove again to be useful ;-)

**Comment by JanSlabon** [comment]
@Klap-in Not this one ;-)

**Comment by sebastianblum** [comment]
@Klap-in I will create a new unit-test because I found new problems. This unit-test used the wrong method signature.

**Comment by tabassumaara** [comment]
![capture](https://user-images.githubusercontent.com/24587040/42096187-42f53730-7bd2-11e8-891e-3a4853b51c9a.PNG)
HOW TO SOLVE  MY ERROR

**Comment by sebastianblum** [comment]
@tabassumaara can you please post the HTML to generate the PDF

**Comment by finwe** [comment]
First upgrade to the last mPDF version and see if the error persists.

**Comment by tabassumaara** [comment]
<?php 
defined('BASEPATH') OR exit('No direct script access allowed');
  // include("design/header.php");
 ?>

 <!DOCTYPE html>
<html lang="en">
<head>
  <title>Generate Pdf</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
<div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" style="background-color: #303030;">
   			


    <table>
    
   
    <tr>
<td></td>
        <td><img src="<?= base_url() ?>assets/img/foot_logo.png" class=" head_table"></img>
        <td  style="color:#FFFFFF; text-align: right;" class="#7CFC00" >+61 1300 370 470<br/>
																		info@travego.com.au<br/>
																		travego.com.au
        	                            
        </th>
        <td style="color:#FFFFFF; text-align: right;" class="#7CFC00">Travego<br/>
                                             NSW , State, Australia<br/>
                                              2206
                                        </th>
        </td>
    </td>
    </tr>
    
</table>
    </div></br>

<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}
</style>
<?php      	$vehicle_tax=0;
			$extra_tax=0;
			$veh_total=0;
			$ex_total=0;
			foreach ($v_tax_res as $key => $v_tax_res_value) {
			$vehicle_tax += $v_tax_res_value['tax'];
			$veh_total +=$v_tax_res_value['total'];
				
			}
			foreach ($ex_tax_res as $key => $ex_tax_res_value) {
				$extra_tax += $ex_tax_res_value['tax_amt'];
				$ex_total += $ex_tax_res_value['total'];
			}
			$tax=$extra_tax+$vehicle_tax;
			$total=$veh_total+$ex_total;

			$this->db->where('f_name',$cus_data_row['first_name']);
			$this->db->where('l_name',$cus_data_row['sur_name']);
			$addr_sql=$this->db->get('customer');
			$address=$addr_sql->row_array();

			$this->db->where('order_id',$_GET['order_id']);
			$stop_ret=$this->db->get('return_stop');
            $stop=$stop_ret->result_array();
            $stop_row=$stop_ret->num_rows();

            

		 ?>
<table  style="margin-top: 25px;">
  <tr>
    <th >Billed To </th>
    <th>Invoice Number</th>
    <th align="right">Invoice Total</th>
  </tr>
  <tr>
    <td><?php echo $cus_data_row['first_name'].'  '.$cus_data_row['sur_name']; ?><br/></td>
    <td><?php echo str_pad($_GET['order_id'],0,"0",STR_PAD_LEFT);?></td>
   
    <td style="color: #c99c3f;  font-size: 23px; text-align: right;" >&#36;<?php echo number_format($cus_order_row['total'],2);?></td>
  </tr>


	<tr>
	<td><?php echo $address['address'];?> </td>	
  	<th>Date Of Issue</th>
  	<th></th>
  	
  </tr>
<tr>
	<td></td>
	<td><?php echo date('d-m-Y',strtotime($cus_data_row["date_booking"]));?></td>
	<td></td>
	
</tr> 
</table>
	<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
		<table class="table table-striped">

		    <thead>
		      <tr>
		        <th colspan="4">Description</th>
		        <th>Tax</th>
		        <th>Amount</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td>Pickup Location</td>
		        <td><?php echo $cus_data_row['pick_location']; ?></td>
		        <td>Drop-off Location</td>
		        <td><?php echo $cus_data_row['dropp_location']; ?></td>
		        <td><?= $tax; ?></td>
		        <td><?= $total; ?></td>
		      </tr>
		     
		      
           </tbody>
        </table>
	</div>
	<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
		<table class="table table-striped">
		    <thead>
		      <tr>
		        <th colspan="4">Booking Details</th>
		        <th>Tax</th>
		        <th>Amount</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td>Pickup&nbsp;Date</td>
		        <td><?php echo $cus_data_row["pick_date"];?></td>
		        <td>Drop-off&nbsp;Date</td>
		        <td ><?php echo $cus_data_row["pick_date"];?></td>
		        <td><?= $tax; ?></td>
		        <td><?= $total;?></td>
		      </tr>
		      <tr>
		        <td>Time</td>
		        <td><?php echo $cus_data_row["pick_time"];?></td>
		        <td>Time</td>
		        <td>-</td>
		        <td></td>
		        <td></td>
		      </tr>
		      <tr>
		        <td>Location</td>
		        <td><?php echo $cus_data_row["pick_location"];?></td>
		        <td>Location</td>
		        <td><?php echo $cus_data_row["dropp_location"];?></td>
		        <td></td>
		        <td></td>
		      </tr>
           </tbody>
        </table>
	</div>
	<?php 
	if($stop_row)
	{
	?>
	<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
		<table class="table table-striped">
		    <thead>
		      <tr>
		        <th colspan="4">Booking Breakage</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<tr>
			      <td>Stop Location</td>
			      <td></td>
			      <td></td>
			      <td>Stop Hour</td>
		      	</tr>
		    <?php
		    foreach ($stop as $key => $stop_loc_value) {
             $stop_loc=$stop_loc_value['stop_loc'];
             $stop_hrs=$stop_loc_value['stop_hrs'];
		    ?>
		    	
		      	<tr> 
			     <td><?php echo wordwrap($stop_loc,50,"<br>\n");?></td>
			     <td></td>
			      <td></td>
			      <td><?php echo $stop_hrs;?></td>
		      	</tr>
		      	<?php } ?>
            </tbody>
 		</table>
	</div>
	<?php } ?>
	<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" style="background-color: #303030; text-align: center; padding: 20px;">
	    <img src="<?= base_url()?>assets/img/credit/visa.png">
	    <img src="<?= base_url()?>assets/img/credit/mastercard.png">
	    <img src="<?= base_url()?>assets/img/credit/paypal2.png">
	    <img src="<?= base_url()?>assets/img/credit/american-express.png">
	</div>
</div>
</div>
</body>
</html>
<style type="text/css">
	th {
    font-size: 18px;
    color: #c99c3f;

}
th {
    font-weight: bold;
    text-align: -internal-center;
}
td, th {
    display: table-cell;
    vertical-align: inherit;
}
.head_table{

	color: #ffffff;
}
.head_row{
	margin: 10px;
	padding-top: 10px;

}
.secon_head{
    color: #c99c3f;
}
</style>

**Comment by tabassumaara** [comment]
<?php 
defined('BASEPATH') OR exit('No direct script access allowed');
  // include("design/header.php");
 ?>

 <!DOCTYPE html>
<html lang="en">
<head>
  <title>Generate Pdf</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
<div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" style="background-color: #303030;">
   		

    <table>
    
   
    <tr>
<td></td>
        <td><img src="<?= base_url() ?>assets/img/foot_logo.png" class=" head_table"></img>
        <td  style="color:#FFFFFF; text-align: right;" class="#7CFC00" >+61 1300 370 470<br/>
									
        </th>
        <td style="color:#FFFFFF; text-align: right;" class="#7CFC00">Travego<br/>
                                             NSW , State, Australia<br/>
                                              2206
                                        </th>
        </td>
    </td>
    </tr>
    
</table>
    </div></br>

<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}
</style>
<?php      	$vehicle_tax=0;
			$extra_tax=0;
			$veh_total=0;
			$ex_total=0;
			foreach ($v_tax_res as $key => $v_tax_res_value) {
			$vehicle_tax += $v_tax_res_value['tax'];
			$veh_total +=$v_tax_res_value['total'];
				
			}
			foreach ($ex_tax_res as $key => $ex_tax_res_value) {
				$extra_tax += $ex_tax_res_value['tax_amt'];
				$ex_total += $ex_tax_res_value['total'];
			}
			$tax=$extra_tax+$vehicle_tax;
			$total=$veh_total+$ex_total;

			$this->db->where('f_name',$cus_data_row['first_name']);
			$this->db->where('l_name',$cus_data_row['sur_name']);
			$addr_sql=$this->db->get('customer');
			$address=$addr_sql->row_array();

			$this->db->where('order_id',$_GET['order_id']);
			$stop_ret=$this->db->get('return_stop');
            $stop=$stop_ret->result_array();
            $stop_row=$stop_ret->num_rows();

            

		 ?>
<table  style="margin-top: 25px;">
  <tr>
    <th >Billed To </th>
    <th>Invoice Number</th>
    <th align="right">Invoice Total</th>
  </tr>
  <tr>
    <td><?php echo $cus_data_row['first_name'].'  '.$cus_data_row['sur_name']; ?><br/></td>
    <td><?php echo str_pad($_GET['order_id'],0,"0",STR_PAD_LEFT);?></td>
   
    <td style="color: #c99c3f;  font-size: 23px; text-align: right;" >&#36;<?php echo number_format($cus_order_row['total'],2);?></td>
  </tr>


	<tr>
	<td><?php echo $address['address'];?> </td>	
  	<th>Date Of Issue</th>
  	<th></th>
  	
  </tr>
<tr>
	<td></td>
	<td><?php echo date('d-m-Y',strtotime($cus_data_row["date_booking"]));?></td>
	<td></td>
	
</tr> 
</table>
	<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
		<table class="table table-striped">

		    <thead>
		      <tr>
		        <th colspan="4">Description</th>
		        <th>Tax</th>
		        <th>Amount</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td>Pickup Location</td>
		        <td><?php echo $cus_data_row['pick_location']; ?></td>
		        <td>Drop-off Location</td>
		        <td><?php echo $cus_data_row['dropp_location']; ?></td>
		        <td><?= $tax; ?></td>
		        <td><?= $total; ?></td>
		      </tr>
		     
		      
           </tbody>
        </table>
	</div>
	<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
		<table class="table table-striped">
		    <thead>
		      <tr>
		        <th colspan="4">Booking Details</th>
		        <th>Tax</th>
		        <th>Amount</th>
		      </tr>
		    </thead>
		    <tbody>
		      <tr>
		        <td>Pickup&nbsp;Date</td>
		        <td><?php echo $cus_data_row["pick_date"];?></td>
		        <td>Drop-off&nbsp;Date</td>
		        <td ><?php echo $cus_data_row["pick_date"];?></td>
		        <td><?= $tax; ?></td>
		        <td><?= $total;?></td>
		      </tr>
		      <tr>
		        <td>Time</td>
		        <td><?php echo $cus_data_row["pick_time"];?></td>
		        <td>Time</td>
		        <td>-</td>
		        <td></td>
		        <td></td>
		      </tr>
		      <tr>
		        <td>Location</td>
		        <td><?php echo $cus_data_row["pick_location"];?></td>
		        <td>Location</td>
		        <td><?php echo $cus_data_row["dropp_location"];?></td>
		        <td></td>
		        <td></td>
		      </tr>
           </tbody>
        </table>
	</div>
	<?php 
	if($stop_row)
	{
	?>
	<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
		<table class="table table-striped">
		    <thead>
		      <tr>
		        <th colspan="4">Booking Breakage</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<tr>
			      <td>Stop Location</td>
			      <td></td>
			      <td></td>
			      <td>Stop Hour</td>
		      	</tr>
		    <?php
		    foreach ($stop as $key => $stop_loc_value) {
             $stop_loc=$stop_loc_value['stop_loc'];
             $stop_hrs=$stop_loc_value['stop_hrs'];
		    ?>
		    	
		      	<tr> 
			     <td><?php echo wordwrap($stop_loc,50,"<br>\n");?></td>
			     <td></td>
			      <td></td>
			      <td><?php echo $stop_hrs;?></td>
		      	</tr>
		      	<?php } ?>
            </tbody>
 		</table>
	</div>
	<?php } ?>
	<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" style="background-color: #303030; text-align: center; padding: 20px;">
	    <img src="<?= base_url()?>assets/img/credit/visa.png">
	    <img src="<?= base_url()?>assets/img/credit/mastercard.png">
	    <img src="<?= base_url()?>assets/img/credit/paypal2.png">
	    <img src="<?= base_url()?>assets/img/credit/american-express.png">
	</div>
</div>
</div>
</body>
</html>
<style type="text/css">
	th {
    font-size: 18px;
    color: #c99c3f;

}
th {
    font-weight: bold;
    text-align: -internal-center;
}
td, th {
    display: table-cell;
    vertical-align: inherit;
}
.head_table{

	color: #ffffff;
}
.head_row{
	margin: 10px;
	padding-top: 10px;

}
.secon_head{
    color: #c99c3f;
}
</style>
I  ALREDY UPGRADE mPDF VERSION BUT ERROR IS SAME

**Comment by JanSlabon** [comment]
So this issue is hijacked and you all ask for more details? Seriously?

**Comment by sebastianblum** [comment]
@tabassumaara first of all, don't use bootstrap to generate pdf files. For pdf files a responsive framework is overpowered. Then you have errors like classnames with an hash  <td style="color:#FFFFFF; text-align: right;" class="#7CFC00">Travego<br/>

You can debug it if you start from scratch and add every line separately until the error occurs again.

For me it looks like your html & css is broken and contains errors.
