### ISSUE TITLE
6.0 > undefined offset (2x)

### ISSUE THREAD

**Issue by osworx** [mpdf/mpdf#46]
Using latest mPDF (6.0) is displaying 2 notices:
```Undefined offset: 16 in mpdf.php on line 21162```
This because ```$arrayaux[$i][16]``` does not exist.
And
```Undefined offset: 1 in mpdf.php on line 21193```
Nearly the same: ```$arrayaux[$i]```

Disabling any error output will work, but cannot be the solution.

**Comment by gustavobhz** [comment]
The error still persists!

**Comment by TomK** [comment]
Could you provide a snippet of HTML which will reproduce this please?

**Comment by finwe** [comment]
Closing. Feel free to reopen along with a snippet of HTML code causing this.

**Comment by fialhoFabio** [comment]
i got the same error message when i wrote a lot of line in mpdf
