### ISSUE TITLE
Insert mpdf TOC with page number for dynamic data PHP

### ISSUE THREAD

**Issue by umairm638** [mpdf/mpdf#469]
I am using mpdf to create PDF files from data extracted from a database. There are three sections in pdf which i need to display in TOC with their page number on which they are appearing. They can appear on separate page or on a single page as well when data is too short. Below is my code currently using:

    $mpdf = new \Mpdf\Mpdf();
    $mpdf->SetFont('avenirnext');
    $mpdf->SetTitle($title);
    $mpdf->SetAuthor('Blavatnik');
    $mpdf->WriteHTML($stylesheet, 1);
    $mpdf->WriteHTML($stylesheet2, 1);
    $mpdf->WriteHTML($stylesheet3, 1);
    $mpdf->setAutoTopMargin = 'stretch';
    $mpdf->SetHtmlHeader($header, 'OE');
    $mpdf->SetHTMLFooter($footer, 'OE');
    $mpdf->AddPage('', // L - landscape, P - portrait 
            '', '', '', '', 20, // margin_left
            20, // margin right
            5, // margin top
            25, // margin bottom
            10, // margin header
            10); // margin footer
    $mpdf->WriteHTML($html);
    $mpdf->Output($title . '.pdf', 'd');

**I need to display TOC on first page and it also has some designing as show in below screenshot, so I think it has to be done via html**

Please see this screenshot: http://prntscr.com/g982kr

**Comment by finwe** [comment]
See https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md. Closing.

**Comment by umairm638** [comment]
@finwe what's this? it's just showed contributing.md page showing how to pull and information.

**Comment by finwe** [comment]
I guess you read it?

> The Issue tracker serves mainly as a place to report bugs and request new features. Please do not abuse it as a general questions or troubleshooting location.
