### ISSUE TITLE
Portrait and landscape ortientation in one document not working

### ISSUE THREAD

**Issue by dadepl** [mpdf/mpdf#470]
Hi, I have problem when generating document in which I need to make one page in landscape format and others in portrait.

I'm running **mPDF version 6.1.**

Sample code I use:

```
$mpdf = new mPDF('utf-8', 'A5', '', '', 0, 0, 0, 0, 0, 0, 'P');
$mpdf->WriteHTML('<div>some html on first page</div>');
$mpdf->AddPage('L', '', '', '', '', 0, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, 'second', 'A4-L');
$mpdf->WriteHTML('<div>landscape a4? no</div>);
$mpdf->AddPage('P', '', '', '', '', 0, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, 'third', 'A5');
$mpdf->WriteHTML('<div>some html on third page</div>');
$mpdf->AddPage('P', '', '', '', '', 0, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, 'fourth', 'A5');
$mpdf->WriteHTML('<div>some html on fourth page</div>');
```

With code above I'm getting everything in portrait mode with second page A4 size and others A5 size.
What am I doing wrong? Thanks for help.

**Comment by finwe** [comment]
It is definitely possible, just maybe not the way you are trying to achieve this. See https://github.com/mpdf/mpdf-examples/blob/development/example23_orientation.php example file which generates differently oriented pages correctly.

**Comment by dadepl** [comment]
Thanks for answer.
The case is that I'm already using `->addPage('L', ...)` code. But for some reason it's ignoring it and adding A4 in portrait orientation.
I figured out, that when I change last parameter of `addPage()` from `A4-L` to `[296, 210]` it started to work and I'm getting my four page PDF file just like I want it to be - A5-P, A4-L, A5-P, A5-P.
I just don't know why and it's confusing (and right now I can't upgrade to mPDF v.7 to check).

**Comment by finwe** [comment]
Will check the -L -P formats, thanks for the catch.

**Comment by finwe** [comment]
@dadepl Can you try the last development branch commit? There was a PR fixing some behaviour on this matter.

**Comment by haifahrul** [comment]
Hi, any progress?

**Comment by finwe** [comment]
This works OK (in current development), the size not applying is due to usage of the $pagesel parameter which does not match any defined named `@page`.
