### ISSUE TITLE
aliasNbPg and aliasNbPgGp not supported as config parameter in constructor

### ISSUE THREAD

**Issue by Klap-in** [mpdf/mpdf#482]
### I found this bug
If setting the config variables `aliasNbPg` and `aliasNbPgGp` in constructor, these are not used.

Using `$mpdf->AliasNbPageGroups('[pagegrouptotal]');` or 
`$mpdf->aliasNbPgGp = '[pagegrouptotal]';` is working as expected.

### These are mPDF and PHP versions I am using
`"require": {
        "mpdf/mpdf": "dev-development"
    }`
### This is a PHP code snippet I use

```
<?php
// Require composer autoload
require_once __DIR__ . '/vendor/autoload.php';

//$mpdf = new \Mpdf\Mpdf(['aliasNbPgGp' => '[pagegrouptotal]']);
$mpdf = new \Mpdf\Mpdf([
    'aliasNbPg' => '{pagetotal}',
    'aliasNbPgGp' => '{pagegrouptotal}',
    'nbpgPrefix' => 'WORKS:'
]);

//$mpdf->AliasNbPageGroups('[pagegrouptotal]');
//$mpdf->aliasNbPgGp = '[pagegrouptotal]';
$mpdf->SetHeader('a{pagetotal}b{pagegrouptotal}c[pagegrouptotal]d{nbpg}e{nb}f');
$mpdf->WriteHTML("Hello World");

$mpdf->Output();

```

**Comment by finwe** [comment]
Fixed in 0c29908, thanks for the catch!

**Comment by Klap-in** [comment]
I'm wondering: is a configuration parameter only working in the constructor if it is listed in `src/Config/ConfigVariables.php` (or another config file in `src/Config/`)?

**Comment by finwe** [comment]
Both files in `src/Config/` are processed explicitly - see Mpdf methods `initConfig` and `initFontConfig` - so no, no other files are processed. And yes, for configuration key to work, it has to be listed in one of those files.
