### ISSUE TITLE
Filemtime error

### ISSUE THREAD

**Issue by samuelexyz** [mpdf/mpdf#483]
### I found this bug 

[172.31.23.118][63][gm0h2gm1878upc69qh8ps0f1q1][error][Mpdf\MpdfException:1]
Mpdf\MpdfException: Error detected. PDF file generation aborted:
filemtime(): stat failed for
/var/app/current/runtime/cache/c2/c2fcbd9c1a9d54fb2341aedc19eaa436.bin
in /var/app/current/vendor/yiisoft/yii2/caching/FileCache.php:113

### These are mPDF and PHP versions I am using

7.0

### This is a PHP code snippet I use

$html= $this->renderPartial('pdfhtml', [
            'model' => $model,
        ]);

        $param = [
            'mode' => '',
            'format' => 'A4',
            'default_font_size' => 0,
            'default_font' => '',
            'margin_left' => 2,
            'margin_right' => 2,
            'margin_top' => 0,
            'margin_bottom' => 0,
            'margin_header' => 0,
            'margin_footer' => 0,
            'orientation' => 'P',
        ];
        $mpdf = new Mpdf($param);

        $mpdf->incrementFPR1 = 4;

        // Write some HTML code:
        $mpdf->debug = true;
        $mpdf->useSubstitutions=false;
        $mpdf->simpleTables = true;

        $mpdf->WriteHTML($html);

        $mpdf->Output('../runtime/pdf/'.$namefile.'.pdf','F');

### This is a HTML/CSS code snippet I use

```

```

**Comment by finwe** [comment]
This is an error outside mPDF caused with your Yii code. Given that you have `$mpdf->debug = true;` mPDF then stops PDF creation.

Options:

- fix your yii code
- do not set mpdf debug to true
- catch the mpdf exception
