### ISSUE TITLE
Feature Request: SVG QR Code Rendering

### ISSUE THREAD

**Issue by 20Fourteen** [mpdf/mpdf#489]
`mpdf 6.1` `PHP 5.5`

Hi,

I have encountered an issue with printing QR codes generated via mpdf, as the codes are rendered using HTML tables, there is a very faint line visible between each square. This is much more noticeable when printing, even though it does not affect the decoding of the QR code in any way, it's an aesthetic  anomaly.

Therefore I ask whether it would be possible to create SVG QR codes, which do not suffer from this issue.

Below you can see an example of what I mean:
![4](https://user-images.githubusercontent.com/8763290/30604258-3c1e9a18-9d62-11e7-9122-6a3f1b17dd73.png)

Many thanks in advance

**Comment by 20Fourteen** [comment]
Looking at [TCPDF ](https://github.com/tecnickcom/TCPDF)I see it supports SVG, does the license allow modification for mpdf?

**Comment by finwe** [comment]
This is not a high priority thing. Also, there sure are third-party libraries generating SVG QR codes, why not make a use of them instead of bloating mPDF further? https://github.com/endroid/QrCode

**Comment by 20Fourteen** [comment]
Some experimenting proved that this is only an issue when printing with low DPI, high DPI prints are fine.
