### ISSUE TITLE
apapche restart required- memory overflow

### ISSUE THREAD

**Issue by almaruf** [mpdf/mpdf#497]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md

### I found this bug / would like to have this new functionality
PHP Warning:  preg_match() expects parameter 2 to be string, array given in /var/www/vhosts/curryhunter.com/zf_projects/almaruf/vendor/mpdf/mpdf/mpdf.php on line 1184, 

PHP Warning:  strlen() expects parameter 1 to be string, array given in /var/www/vhosts/curryhunter.com/zf_projects/almaruf/vendor/mpdf/mpdf/mpdf.php on line 1193

PHP Warning:  substr() expects parameter 1 to be string, array given in /var/www/vhosts/curryhunter.com/zf_projects/almaruf/vendor/mpdf/mpdf/mpdf.php on line 1201

PHP Warning:  substr() expects parameter 1 to be string, array given in /var/www/vhosts/curryhunter.com/zf_projects/almaruf/vendor/mpdf/mpdf/mpdf.php on line 1204

PHP Warning:  substr() expects parameter 1 to be string, array given in /var/www/vhosts/curryhunter.com/zf_projects/almaruf/vendor/mpdf/mpdf/mpdf.php on line 1207

PHP Warning:  preg_split() expects parameter 2 to be string, array given in /var/www/vhosts/curryhunter.com/zf_projects/almaruf/vendor/mpdf/mpdf/config_lang2fonts.php on line 20

### This is a PHP code snippet I use

```
<?php
require_once CORE_MODULES_PATH . '/../vendor/autoload.php';
        $mpdf = new mPDF([
            'mode' => 'c',
            'margin_left' => 42,
            'margin_right' => 15,
            'margin_top' => 67,
            'margin_bottom' => 67,
            'margin_header' => 20,
            'margin_footer' => 15
        ]);
        $st = "Test Text";
        $mpdf->SetTitle($st);
        $mpdf->SetSubject($st);
        $mpdf->SetAuthor("Test");
        $mpdf->WriteHTML($html);
        $mpdf->Output();
        die();

```

### This is a HTML/CSS code snippet I use

```

<table width='100%' cellspacing='0' cellpadding='10'  style='line-height:19px; border:1px solid #EEEEEE;'>
--
  | <tr>
  | <td colspan='8' style='text-align:left;'>
  | <h2>XYZ NAME</h2>
  | <p>Shelton Street<br/>
  | WC2H 9JQ<br/>
  | London, UK<br/>
  | Company no. 9999999<br/>
  | Phone: +440999999</p>
  | </td>
  | <td></td>
  | </tr>
  | <tr>
  | <td colspan='4' valign='top' style='text-align:left;'>
  | <p>
  | <b>Invoice no.</b>: 1003<br/>
  | <b>Invoice date</b>: 01-09-2017<br/>
  | <b>Invoice period</b>: August, 2017<br/>
  | </p>
  | </td>
  | <td></td>
  | </tr>
  | <tr>
  | <td>
  | <h2>Khanz Camber</h2>
  | <p>65 Lydd Road, TN31 7RJ, Camber Sands</p>
  | </td>
  | <td></td>
  | </tr>
  | </table>
  |  
  | <table width='100%' cellspacing='0' cellpadding='10' style='line-height:19px; border:1px solid #EEEEEE;'>
  | <thead>
  | <tr>
  | <th colspan='8' style='text-align:right; border:1px solid #DDDDDD;'>Details</th>
  | <th colspan='4' style='text-align:right; border:1px solid #DDDDDD;'>Amount</th>
  | </tr>
  | </thead>
  | <tbody>
  | <tr><td colspan='8' style='text-align:right; border:1px solid #DDDDDD;'>10% Commission on total sales of �530.00</td><td colspan='4' style='text-align:right; border:1px solid #DDDDDD;'>£53</td></tr><tr><td colspan='8' style='text-align:right; border:1px solid #DDDDDD;'>Admin Fee (8 card orders X �0.00)</td><td colspan='4' style='text-align:right; border:1px solid #DDDDDD;'>£0</td></tr><tr><td colspan='8' style='text-align:right; border:1px solid #DDDDDD;'>Subtotal </td>
  | <td colspan='4' style='text-align:right; border:1px solid #DDDDDD;'>£53</td></tr>
  | <tr><td colspan='8' style='text-align:right; border:1px solid #DDDDDD;'><b>Total </b></td>
  | <td colspan='4' style='text-align:right; border:1px solid #DDDDDD;'><b>£53.00</td></b></tr>
  | </tbody>
  | </table>
  | <br/>
  | <img src='../images/ch/logo_1.png' style='opacity: 0.3;filter: alpha(opacity=30);'/>



```

**Comment by finwe** [comment]
Your instatiation of the Mpdf object is incorrect, you are using an array from v 7 with the class of version 6. Either upgrade or use the [old style constructor](https://mpdf.github.io/reference/mpdf-functions/mpdf.html)
