### ISSUE TITLE
[Feature Request] Flush Output Buffer Page by Page

### ISSUE THREAD

**Issue by vzool** [mpdf/mpdf#503]
### I would like to have this new functionality

Hi, I'm looking for a way to flush output while you generate a large PDF with more than 1000 pages.
Current situation is generate all pages in ram and after that write to disk, this is consuming a lot of ram while we have a limited resources on production.
I think flush output page by page is scalable & best practice. Is there already a way to do that and I'm not aware of?

Thanks for your nice job

**Comment by finwe** [comment]
Not entirely sure that this is possible, considering that HTML content on later pages could potentialy influence content on previous pages. Keeping open for furure reference.

**Comment by finwe** [comment]
Closing as wontfix. 

You can always generate many small documents and concatenate them after with eg. GhostScript.
