### ISSUE TITLE
Images are not displaying in the PHPV7.0

### ISSUE THREAD

**Issue by younas-bangash** [mpdf/mpdf#504]
### I found this bug 
I use the below code in order to display watermark it was working fine on phpV5.6 but when I update the PHP version so now it is not working cross is displaying instead of images

### This is a PHP code snippet I use

```
<?php
$mpdf=new mPDF(); 
$mpdf->autoScriptToLang = true;
$mpdf->baseScript = 1;
$mpdf->autoVietnamese = true;
$mpdf->autoArabic = true;
$mpdf->autoLangToFont = true;
$mpdf->showWatermarkImage = true;
$mpdf->SetWatermarkImage('IMageLink', 0.2, 'F');
$mpdf->WriteHTML($htmltext,2);
$mpdf->Output('output.pdf','F');
 // htmltext text contain html code and inside that images tags are used and those images also not display in phpV7.0
```

**Comment by Klap-in** [comment]
I guess you are using the mpdf 6.x version, it isn't?
This version doesn't support php7.

If you need php7 support, than you better try the recent release candidates of mPDF 7.

**Comment by younas-bangash** [comment]
How can I download the mPDF7 i try on the method which explain in readme but it was not working

**Comment by younas-bangash** [comment]
I successfully install mPDF7 version but now it give an error 

`Fatal error: Uncaught Error: Class 'Mpdf\Mpdf' not found in /var/www/html/genrate_pdf.php:380 Stack trace: #0 {main} `

**Comment by younas-bangash** [comment]
I solved that issue by `$mpdf=new mPDF(['debug' => true]); `
