### ISSUE TITLE
Error interpreting tags

### ISSUE THREAD

**Issue by gfrodriguez** [mpdf/mpdf#511]
mpdf: 1.6.4

I have an error, all the titles are shown well except one, I already reviewed the HTML and it is fine, however it is not displayed correctly.

It looks like this:

![firefox_2017-10-16_22-44-33](https://user-images.githubusercontent.com/12382314/31645821-c2ca7570-b2c3-11e7-8836-fee6e9fc3783.png)

It should look like this:

![firefox_2017-10-16_22-44-45](https://user-images.githubusercontent.com/12382314/31645833-d01b9862-b2c3-11e7-9710-29aa920fc714.png)

**Comment by finwe** [comment]
Please, post your PHP/HTML code snippet causing this. Without it, we are unable to fix this correctly.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen, if still applicable on current version.
