### ISSUE TITLE
Request: __toString() function, or hints how to make one

### ISSUE THREAD

**Issue by strider72** [mpdf/mpdf#514]
I would love the ability to return the raw HTML of a PDF as a string (the various HTML passed into `::writeHTML()`).  It would allow me to Preview a document before producing a PDF.

In the meantime, could you please tell me where this data is stored so I might roll my own?  I've tried parsing out writeHTML, but it's an extremely complex routine and I can't quite decipher what happens to the HTML passed in to it.

(I know i can extend the mpdf class and push snippets into one big string as they come in; but if I can avoid duplicating data I'd like to. No need eating up resources with giant redundant strings.)

**Comment by finwe** [comment]
There is no such thing as a _raw HTML of a PDF as a string_. The only HTML input is from the user, and as a user you already have it.

In the document, body, headers, footers and eg. a TOC is translated directly from input HTML to strings by PDF specification, there is no _other_ HTML being created internally by mPDF.

This would be work over the intentions of converting HTML **to** PDF.

**Comment by strider72** [comment]
Cool, that answers the question at least.
