### ISSUE TITLE
Dollar sign in footer causes issues (mode 'c')

### ISSUE THREAD

**Issue by andrews05** [mpdf/mpdf#520]
When using mode 'c', mpdf seems to be doing something special with dollar signs in the footer. A dollar sign followed by 1 or 2 digits will not be displayed. I've tried all 4 methods of setting the footer with the same result. Happens in both v6.0 and v7.0.1.

**Comment by Klap-in** [comment]
If this is a bug report, could you please expand it with a simple php&html test case? Thank you!

**Comment by andrews05** [comment]
```
$mpdf = new Mpdf\Mpdf(['mode'=>'c']);
$mpdf->setHtmlFooter('$123.45');
$mpdf->output('', 'I');
```

**Comment by andrews05** [comment]
Tracked this down to a regex substitution on lines 9550/9551. The footer content is being used in a replacement and `\\n` references are being escaped but not `$n` references. Fixed by changing line 9550 from:
`$os = preg_replace('/\\\\/', '\\\\\\\\', $os);`
to:
`$os = preg_replace(['/\\\\/', '/\$/'], ['\\\\\\\\','\\\\$'], $os);`

**Comment by finwe** [comment]
Will look into it, thanks for debugging!
