### ISSUE TITLE
iconv fail infinite loop

### ISSUE THREAD

**Issue by scrollup** [mpdf/mpdf#521]
### I found this bug

`$message` contains data with the offending character being `é` (from "République") which is hex code E9. This happens when `$message` goes first through `$message = utf8_decode(html_entity_decode($message));`

This results in an infinite loop of errors: `PHP Notice:  iconv(): Detected an illegal character in input string in /vendor/mpdf/mpdf/mpdf.php on line 29395`

This is do to the code starting on line 29394 which is a potentially unsafe while loop. It'll never break out if iconv fails as in this case.

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
PHP 5.6.29 (cli)
mpdf/mpdf   v6.1.4 (from composer)

### This is a PHP code snippet I use

```
<?php
....
$mpdf->WriteHTML($message);

```

**Comment by finwe** [comment]
Try mPDF 7.0.1, please. Is your input in UTF-8?

**Comment by scrollup** [comment]
I'll test on 7.0.1, but looking at the current source code I still see a while loop that isn't testing if `iconv()` fails. If it does fail, the while loop will never exit.

My input wasn't UTF-8 (I later fixed the input, but the code should handle or fail gracefully if it's not ). I used utf8_decode() which converted my input to single-byte `ISO-8859-1`, I thought I needed that encoding for a specific case.

**Comment by finwe** [comment]
Closing, superseded with the mentioned issue.
