### ISSUE TITLE
Undefined index: max_bottom on SetColumns 7.x

### ISSUE THREAD

**Issue by carstengrimm** [mpdf/mpdf#529]
Hi, 

I've upgraded my mpdf installation via composer from 6.1.3 to the latest version ( 7.0.1 ) of mpdf. 
I then transitioned using `$mpdf = new \Mpdf\Mpdf();` to use the correct (namespace?) 

in my code everything seems to be working fine - pdf file gets rendered unless i am using SetColumns() with more than one column...

```
<?php
// ....
// ....
$mpdf->SetColumns(1,'J',5);
// Works
$mpdf->SetColumns(2,'J',5);
// Error
$mpdf->SetColumns(3,'J',5);
// Error
// and so on...
```

The error i am getting is:

Undefined index: max_bottom

vendor\mpdf\mpdf\src\Mpdf.php
```
<?php
// ....
// Line 26872
                        if ($clb > $this->ColDetails[$s['col']]['max_bottom']) {
                            $this->ColDetails[$s['col']]['max_bottom'] = $clb;
```

**Comment by finwe** [comment]
Can you please post entire code snippet that causes this? I have encoutered another notice but have trouble reproducing the `Undefined index: max_bottom`.

**Comment by manukieli** [comment]
Hi, I've the same error.
I've update my mpdf 6 to 7.
And I've this code:
`        $mpdf = new \Mpdf\Mpdf([
            'mode' => 'ut-8',
            'format' => 'A4',
            'default_font' => 'dejavusans',
            'default_font_size' => '11pt',
            'margin_left' => 10,
            'margin_right' => 10,
            'margin_top' => 30,
            'margin_bottom' => 10,
            'margin_header' => 10,
            'margin_footer' => 10
        ]);
        $mpdf->WriteHTML('<p style="text-align: center;">FIRST LINE</p>');
        $mpdf->SetColumns(2, 'J', 5);
        $mpdf->WriteHTML('<p style="text-align: left;">SECOND LINE</p>');
        $mpdf->AddColumn();
        $mpdf->WriteHTML('<p style="text-align: center;">THIRD LINE</p>');
        $mpdf->SetColumns(1);
        $mpdf->Ln(2);

        $mpdf->Output('file.pdf', 'D');`

**Comment by Zidiouz** [comment]
I ran into the same problem when I set up a multiple column document and set keepColumns to true. I edited the following line in Mpdf.php:
Line 26979: if ($clb > $this->ColDetails[$s['col']]['max_bottom']) {
and changed it to:
if (empty($this->ColDetails[$s['col']]['max_bottom']) || $clb > $this->ColDetails[$s['col']]['max_bottom']) {
(Notice the empty(...) which will check whether max_bottom has been set, and if not sets it. This fixes the problem in my case.
Please include this fix in the new release.

**Comment by MatthiasKuehneEllerhold** [comment]
Seems like this issue will be fixed in the PR https://github.com/mpdf/mpdf/pull/813

Is there a release planned with this fix?
