### ISSUE TITLE
PHP 5.4 compatibility

### ISSUE THREAD

**Issue by iyasilias** [mpdf/mpdf#530]
My server is using php 5.4. Could you please tell me if there is any version of mpdf that compatible with php 5.4. Or shade me some light to where to fix so that it is php 5.4 compatible.

**Comment by Klap-in** [comment]
For support of the older versions of PHP you can still use the latest version of mPDF 6 instead of mPDF 7.

(Please note that your PHP version is not supported anymore... http://php.net/supported-versions.php . Therefore it is really recommended to update to a recenter version securitywise.)
