### ISSUE TITLE
Call to undefined function Mpdf\code2utf()

### ISSUE THREAD

**Issue by peyman-mohamadpour** [mpdf/mpdf#531]
### I found this bug

> Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "code2utf" from namespace "Mpdf"." at /vendor/mpdf/mpdf/src/Otl.php line 4946

### This is mPDF and PHP version and environment (fpm/cli etc) I am using

OS: OSX 10.12.6
PHP: 7.1.10
MPDF: 7.0.0

**Comment by finwe** [comment]
Thanks for the report. Can you please share the PHP/HTML snippet that caused this so it can be used in a test?

**Comment by Farshadi73** [comment]
maybe this in not good solution, but i try this and work for me.
in symfony => vendor/mpdf/src/functions.php
copy code2utf function
`function code2utf($num, $lo = true)
	{
		// Returns the utf string corresponding to the unicode value
		if ($num < 128) {
			if ($lo) {
				return chr($num);
			} else {
				return '&#' . $num . ';';
			}
		}
		if ($num < 2048) {
			return chr(($num >> 6) + 192) . chr(($num & 63) + 128);
		}
		if ($num < 65536) {
			return chr(($num >> 12) + 224) . chr((($num >> 6) & 63) + 128) . chr(($num & 63) + 128);
		}
		if ($num < 2097152) {
			return chr(($num >> 18) + 240) . chr((($num >> 12) & 63) + 128) . chr((($num >> 6) & 63) + 128) . chr(($num & 63) + 128);
		}

		return '?';
	}`
and Paste in : vendor/mpdf/src/otl.php 
and use this method in line 4946 Instead  
$e.= $this->code2utf($cd['char']); 
.................................................................................

**Comment by finwe** [comment]
The function is now defined as static in \Mpdf\Utils\UtfString. Fix ready, waiting for the snippet for the test.

**Comment by Klap-in** [comment]
How is the mpdf object instantiated in your code, with which options?

And a course breakdown of your html does not yet reduce the size of the html snippet?

**Comment by peyman-mohamadpour** [comment]
This is how I instantiated the `mpdf` object:

```
use Mpdf\Mpdf;

class PdfGenerator
{
    private $templating;
    private $mpdf;

    public function __construct($templating)
    {
        $config = array(
            'fontdata'           => array(
                'iran'           => array(
                    'R'          => 'iran.ttf',
                    'B'          => 'iran-bold.ttf',
                    'useOTL'     => 0xFF,
                    'useKashida' => 75,
                ),
                'lalezar'        => array(
                    'R'          => 'lalezar.ttf',
                    'useOTL'     => 0xFF,
                    'useKashida' => 75,
                )
            ),
            'setAutoTopMargin'    => 'stretch',
            'setAutoBottomMargin' => 'stretch',
            'autoMarginPadding'   => 0
        );

        $this->templating = $templating;
        $this->mpdf = new Mpdf($config);
    }
}
```

> A course breakdown of your html does not yet reduce the size of the html snippet?

I dont know which parts to keep in the summarized version

**Comment by finwe** [comment]
@peyman-mohamadpour Please, find out which part of your HTML causes the error. Try to break your code to smaller portions.

**Comment by brshinde** [comment]
Call to undefined function mb_internal_encoding()

Filename: mpdf/mpdf.php

Line Number: 1551

**Comment by brshinde** [comment]
Call to undefined function mb_internal_encoding()

Filename: mpdf/mpdf.php

Line Number: 1551

**Comment by Thoulah** [comment]
@brshinde: you need to install php-mbstring
