### ISSUE TITLE
mkdir(): File exists in Cache constructor

### ISSUE THREAD

**Issue by aluferraz** [mpdf/mpdf#534]
### I found this bug 
Hi,

I'm facing the following error:

"mkdir(): File exists"

It occurs whenever I instantiate a new MPdf object. The error occurs at:

vendor/mpdf/mpdf/src/Cache.php in __construct at line 18

### This is mPDF and PHP version and environment (fpm/cli etc) I am using

mPDF version 7.0.1
PHP Version: 7.1.10
LAMP stack

### This is a PHP code snippet I use

```
<?php

$mpdf = new Mpdf();
```

### This is a HTML/CSS code snippet I use

```

```

**Comment by finwe** [comment]
How did you install mPDF? with composer? There might be an issue with correct permissions to to the temp directory.

I strongly suggest to create your own custom temporary directory with write permissions and set it to mPDF as `$mpdf = new Mpdf(['tempDir' => '<custom temp path>']);`

**Comment by aluferraz** [comment]
Hi there,

Thank you for your reply! MPDF was installed using composer.. I've changed the folder permissions to 777 and the problem was fixed. However, shouldn`t it already 777? I mean, this folder is created by the script itself using mkdir(<tmp dir path>,777,true).

**Comment by finwe** [comment]
Yes, there is a script run after installation, but in a case your `umask` is `0002`, resulting mode is `0775` (no write permissions for `others`). When you run composer as yourself, the Apache which executes PHP script is user `www-data`, there is no mutual group and therefore Apache, as `others`, has no write permissions.

I seriously recommend to use your own custom path with correct permissions, directory owner and group.

Leaving this open until I add a patch throwing an exception instead of a warning in this particular corner case.

**Comment by finwe** [comment]
Just out of curiosity, can you send owner, group and permissions of all directories along path `vendor/mpdf/mpdf/tmp`?

**Comment by aluferraz** [comment]
`$ ls -lha`
drwxrwsr-x  3 user user 4.0K Nov  6 17:31 tmp

**Comment by finwe** [comment]
and a few directories above? I guess that this is exactly the case I described above.

**Comment by aluferraz** [comment]
Yes, I think you're right ! I've changed the tmp folder to a custom location as a fix..

`$ vendor/mpdf/mpdf/ ls -lha`

-rw-rw-r--  1 user user  33K Oct 20 19:45 CHANGELOG.md
-rw-rw-r--  1 user user 1.5K Oct 20 19:45 composer.json
-rw-rw-r--  1 user user 4.8K Oct 20 19:45 CREDITS.txt
drwxrwsr-x  6 user user 4.0K Oct 20 19:45 data
drwxrwsr-x  2 user user 4.0K Oct 20 19:45 .github
-rw-rw-r--  1 user user   23 Oct 20 19:45 .gitignore
-rw-rw-r--  1 user user  15K Oct 20 19:45 LICENSE.txt
-rw-rw-r--  1 user user  435 Oct 20 19:45 phpunit.xml
-rw-rw-r--  1 user user 3.9K Oct 20 19:45 README.md
-rw-rw-r--  1 user user 1.6K Oct 20 19:45 ruleset.xml
drwxrwsr-x 18 user user 4.0K Oct 20 19:45 src
drwxrwsr-x 3 user user 4.0K Nov 6 17:31 tmp
-rw-rw-r--  1 user user  811 Oct 20 19:45 .travis.yml
drwxrwsr-x  2 user user 4.0K Oct 20 19:45 ttfonts


`$ls -lha vendor/mpdf`

drwxrwsr-x  7 user user 4.0K Oct 25 02:04 mpdf

**Comment by finwe** [comment]
Thanks.
