### ISSUE TITLE
Compound/double class CSS selector not working?

### ISSUE THREAD

**Issue by godbout** [mpdf/mpdf#538]
I can't find much information on whether it is supported or not, sorry. Someone could confirm whether it is not or whether I'm making a mistake somewhere?

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
PHP 7.1.11 (both cli and fpm)
mPDF 6.1.3

### CSS/HTML

CSS
```
.hero.is-dark {
    background-color: #363636;
    color: whitesmoke;
}
```

HTML
```
<div class="hero is-dark">
    <h1>Trying to get some shit done</h1>
</div>
```

`.hero.is-dark` is not recognized when I generate the PDF, but works fine when I dump the normal view. If I remove `.is-dark` the class is applied (but of course my whole CSS contains a lots of those multiple classes, and therefore don't work).

Thanks!

**Comment by finwe** [comment]
I guess, if not working, that the compoud class selector is not supported.

Labelling this as a feature request.

**Comment by godbout** [comment]
Ok, thanks. I'm surprised because it seems like a standard thing to me. But at the same time maybe it's better to create a simple CSS just for the PDF, rather than using a whole framework thing. Thanks again!

**Comment by RensTillmann** [comment]
Any news regarding this feature? Would be really nice to have the option to use multiple class selector 👍

**Comment by finwe** [comment]
None.
