### ISSUE TITLE
Call to undefined method Mpdf\Mpdf::_getImage()  

### ISSUE THREAD

**Issue by pattbw** [mpdf/mpdf#539]
### I found this bug:

Call to undefined method Mpdf\Mpdf::_getImage() in mpdf/mpdf/src/Image/Svg.php:278 

Looks like there is a bug, the _getImage() method is missing

### This is a temporary fix which works:

```
// Svg.php -  line 278 
// change this:
$info = $this->mpdf->_getImage( ... );
// to:
$info = $this->mpdf->imageProcessor->getImage( ... );
// and
// change the Mpdf->$imageProcessor to public to make the above getImage() call possible.
```

I hope this helps.

**Comment by Klap-in** [comment]
Do you have an example piece of php/html, which triggers this issue? It is very welcome, so that quickly an new unittest can be created! Thanks!

**Comment by pattbw** [comment]
$html = '<svg width="100" height="100">
   <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
   </svg>';

$mpdf = new \Mpdf\Mpdf([
        'mirrorMargins' => 1,

        //defaults:
        'mode' => '',
        'format' => 'A4',
        'default_font_size' => 0,
        'default_font' => '',
        'margin_left' => 15,
        'margin_right' => 15,
        'margin_top' => 16,
        'margin_bottom' => 16,
        'margin_header' => 9,
        'margin_footer' => 9,
        'orientation' => 'P'
    ]);

$mpdf->SetDisplayMode('fullpage');
$mpdf->setFooter('{PAGENO}');
$mpdf->WriteHTML($html);
