### ISSUE TITLE
Dependancy required with setimportuse()

### ISSUE THREAD

**Issue by clockover** [mpdf/mpdf#540]
Hello,

When I use `$mpdf->SetImportUse(); `, I have a missing requirement.

`require(../pdf_parser.class.php): failed to open stream: No such file or directory in /home/tmp/app/autoloader.class.php on line 31`

I use mPDF 7.0.1 installed via composer on a Debian 9 with NGINX and PHP-FPM 7.0.

```
require_once __DIR__ . '/vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf();
$mpdf->SetImportUse();
```

Is it a missing in the documentation or an issue ?
Best regards,

**Comment by Klap-in** [comment]
I guess one of the dependencies of mPDF has some challenges with autoloading stuff.

See also https://github.com/Setasign/FPDI/issues/19

**Comment by Klap-in** [comment]
Do you use another autoloader as well, than the one via composer?

**Comment by clockover** [comment]
Yes I have another autoloader for my classes.
The error shows that php tried to use it for load pdf_parser.class.php.

Thanks for the feedback :)

**Comment by JanSlabon** [comment]
You should optimize your autoloader so that it will only load the classes it is responsible for and not everything it is asked for. With your autoloader implementation a simple `class_exists('whaever')` will raise this issue.

**Comment by finwe** [comment]
Closing this as solved.
