### ISSUE TITLE
Header/Footer not working version 7.0

### ISSUE THREAD

**Issue by clarkk** [mpdf/mpdf#547]
Header/footer isn't written to the PDF with this code

```
$mpdf = new \Mpdf\Mpdf;
$mpdf->useSubstitutions 		= false;
$mpdf->simpleTables 			= true;
$mpdf->use_kwt 				= true;
$mpdf->SetHTMLHeader('<div>Page {PAGENO} of {nb}</div>');
$mpdf->SetHTMLFooter('<div>The footer</div>');
$mpdf->WriteHTML($html);
$mpdf->Output($file_name, \Mpdf\Output\Destination::FILE);
```

**Comment by Akash437** [comment]
did you make it work ?

**Comment by finwe** [comment]
Please, post your HTML/CSS code snippet causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by finwe** [comment]
With a simple text as a HTML, your example works for me in mPDF 8.0.0

Ensure you don't use @page selector in your CSS. See https://mpdf.github.io/headers-footers/headers-footers.html
