### ISSUE TITLE
Is the design of mpdf really requires the ttfontdata folder? Can I just stream the generated pdf without having to create temp file?

### ISSUE THREAD

**Issue by iyasilias** [mpdf/mpdf#550]
1. Is the design of mpdf really requires the ttfontdata folder?
2. Can I just stream the generated pdf without having to create temp files and any folders?

I am having the issue where while generating the pdf, it seems all files in the temp folder (configured with:  `new \Mpdf\Mpdf(['tempDir' => 'folder', ...` ) are deleted. So I think maybe I can configure something somewhere to stream the pdf without having to create temp file. Is it possible?

**Comment by finwe** [comment]
No, mPDF currently cannot function without temporary files directory mainly for performance reasons.

If you are experiencing issues with content being deleted, can you please elaborate on what exactly is the problem?

**Comment by iyasilias** [comment]
Thanks for you reply.

We use the same folder for storing uploaded files. All the files were deleted when a script runs mpdf.

Just asking because I thought mdpf do have streaming and I can't find about streaming anywhere in the documentation.

So we just need to create another folder for temporary files.

Thanks.

**Comment by finwe** [comment]
I have added a notice to readme and will add a note to documentation as well.

https://github.com/mpdf/mpdf/blob/development/README.md
