### ISSUE TITLE
css text-indent not working

### ISSUE THREAD

**Issue by robertokir** [mpdf/mpdf#555]
### I found this bug / would like to have this new functionality
My CSS has an entry to get the 1st line of paragraphs to be indented (see below). The HTML looks fine but the generated PDF won't have the 1st line of paragraphs indented.

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
PHP 5.6, mPDF 6 and also 7

### This is a HTML/CSS code snippet I use

```
p { 
text-indent: 3em; 
}

```

**Comment by Klap-in** [comment]
Can you please provide a complete test case?

**Comment by marclaporte** [comment]
HTML: https://dev.tiki.org/mPDF-css-text-indent

mPDF: https://dev.tiki.org/tiki-print.php?page=mPDF+css+text-indent&display=pdf

**Comment by Klap-in** [comment]
The purpose is to make a unit test from the test case. e.g. I don't yet see what your mpdf settings are.
Could you consider if you could make a reduced case like: https://github.com/mpdf/mpdf/issues/549
Thanks!

**Comment by finwe** [comment]
text-indent works correctly in test setup with mPDF 6.x and 7.x, there must be something amiss in your set-up or environment. Unless you provide something as a MCVE, I am not able to help.

**Comment by robertokir** [comment]
It was a bug on our side. Thanks Klap-in and finwe!
