### ISSUE TITLE
Undefined index: dom in Mpdf.php

### ISSUE THREAD

**Issue by webbed88** [mpdf/mpdf#557]
I found this bug after upgrading to mPDF 7.

**mPDF Version:** 7.0.1
**PHP Version:** 7.1.10

### This is the error I am recieving:

```
Notice: Undefined index: dom in ./vendor/mpdf/mpdf/src/Mpdf.php on line 22829
```
This is specifically related to ```$celladj['border_details']['T']['dom']``` not having the `dom` array key.

### This is a HTML/CSS I'm trying to convert.

```
<style>
	table {border-collapse: collapse;}
	table tbody td {
		border-right: 1px solid #ccc;
		border-bottom: 1px solid #ccc;
	}
	table thead th {
		border-bottom: 1px solid #333;
	}
	.warning {
		border: 1px solid #cc9933;
		background-color: #ffffcc !important;
	}
</style>
<table>
	<thead>
		<tr>
			<th>Contact Person</th>
		</tr>
	</thead>
	<tbody>
		<tr class="warning">
			<td>John Doe</td>
		</tr>
	</tbody>
</table>
```

**Comment by Klap-in** [comment]
Thanks for your report! could you please add a small example of your PHP code? 
That helps a lot to create quickly a unittest of your case.
