### ISSUE TITLE
Drop JPGraph support

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#56]

**Comment by marclaporte** [comment]
Why?  Hard to maintain? Low usage?

Related: https://github.com/mpdf/mpdf/wiki/Images-generated-in-JavaScript

**Comment by finwe** [comment]
This is now just a suggestion, but: the libary is:

* Hard to maintain
* Not supported through composer
* Kind of shitty
* Parsing HTML tables itself is not the cleanest way to generate a graph

and so on.

**Comment by blueliquiddesigns** [comment]
Plus, since PHP graphing software produce images it's very easy for developers to display the graph image in the PDF.

**Comment by JanSlabon** [comment]
Plus, their licenses are [incompatible](http://www.gnu.org/licenses/license-list.en.html#QPL)!

**Comment by akamustang** [comment]
Looks like this was the associated commit: [2407f7f62a92cee2bc4cfa51d342bc749b11dd19](/mpdf/mpdf/commit/2407f7f62a92cee2bc4cfa51d342bc749b11dd19)

**Comment by JanSlabon** [comment]
JFYI: README.md still mentiones JpGraph

**Comment by finwe** [comment]
Thanks, https://github.com/mpdf/mpdf/issues/149 is the relevant issue
