### ISSUE TITLE
PHP 7.2 Warning : count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by LegendPJ** [mpdf/mpdf#562]
Hello,

I'm using the latest version of mpdf (7.0.2) with PHP 7.2 and I found a bug.
It's happening at line 5788 of Mpdf.php (very begining of the `trimOTLdata()` method) :
```php
$len = count($cOTLdata['char_data']);
```

The problem is that `$cOTLdata['char_data']` could be null in some cases, and PHP 7.2 doesn't allow `count(null)`

By changing this line to :
```php
$len = $cOTLdata['char_data'] === null ? 0 : count($cOTLdata['char_data']);
```
... it solves the problem, but I don't know enough about the project to make a pull request.

Hope this will be helpful !

**Comment by finwe** [comment]
Can you please post your PHP/HTML code? I would like to know whether the cause of this is not somewhere sooner in the code rather than just checking for NULL.

**Comment by LegendPJ** [comment]
I've isolated a piece of my HTML/PHP code that doesn't work : 

HTML :
```html
<!DOCTYPE html>
<html>
    <head>
        <style>
            div, table {
              font-size: 8.5pt;
              font-family: "Arial";
            }
        </style>
    </head>
    <body>
    <div class="bill">
        <div class="header">
            <div class="logo">
                <img src="" />
            </div>
        </div>
    </div>
    </body>
</html>
```

PHP : 
```php
$mpdf = new Mpdf([
     'format' => 'A4',
     'margin_left' => 7,
     'margin_right' => 7,
     'margin_top' => 7,
     'margin_bottom' => 7,
     'margin_header' => 0,
     'margin_footer' => 3
]);

$mpdf->WriteHTML($html);

$mpdf->Output($file, Destination::FILE);

```

If I remove the following line : `font-family: "Arial";`, the warning doesn't show up anymore.

**Comment by treadmillian** [comment]
What happens if you try: `font-family: Arial;`

**Comment by LegendPJ** [comment]
Exactly the same problem. I tried another font, but it doesn't work anymore.

**Comment by finwe** [comment]
Added the check, although I was not able to reproduce the issue.

**Comment by vukanac** [comment]
I got the same issue after upgrading to php7.2 on mac os x.

**Comment by finwe** [comment]
@vukanac Not particularly helpful. Show your code snippet causing this.

**Comment by jonnsl** [comment]
I'm having the same issue. It happens only when the CSS specifies a font that is not installed.
mpdf: 7.0.2
PHP: 7.2.0 ArchLinux

**Comment by Klap-in** [comment]
Last time when this issue was solved, the following test was added:
https://github.com/mpdf/mpdf/commit/9ac89273a7967eefe96507e537c45493a99e2859
Is this test case working for you?
Can you provide a similar example case that reproduces your situation? Thanks!

**Comment by finwe** [comment]
I've released v7.0.3 where the check for NULL is incorporated.

**Comment by shubhamnarlawar77** [comment]
I am facing this issue while installing drupal-7.56. at line 1441 of "C:\xampp\htdocs\drupal\drupal-7.56\includes\form.inc)."
 Is it the common error due to php v.7.2.3?

**Comment by Klap-in** [comment]
Please update to the last release of mpdf.
I expect it is solved in that release.

If it is not solved, than it is similar issue popping up from different location in the code.
Please open in that case a _new issue report_ and provide _an example_ of php and html to reproduce the error. Thanks!

**Comment by shubhamnarlawar77** [comment]
Yeah sure i will do that.
