### ISSUE TITLE
Undefined variable: rotate in Mpdf.php:16029

### ISSUE THREAD

**Issue by dovestyle** [mpdf/mpdf#564]
### I found this bug
Simple bug; the $rotate variable in this method (WriteFixedPosHTML) being used on line 16029 is assigned in a completely different conditional scope, on line 15466. This is causing line 16029 to error out if you have an empty $bounding arg. I just set `$rotate = 0` near the beginning of the method, outside both scopes, and it's fine.

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
mPDF 7.0.2
PHP-7.1.11 cli

### This is a PHP code snippet I use
```php
$pdf = new \Mpdf\Mpdf([
  'mode'              => 'utf-8',
  'format'            => [30, 30],
  'default_font_size' => 0,
  'default_font'      => '',
  'margin_left'       => 30,
  'margin_right'      => 30,
  'margin_top'        => 16,
  'margin_bottom'     => 16,
  'margin_header'     => 9,
  'margin_footer'     => 9,
]);

$pdf->SetImportUse();
$pdf->SetSourceFile(__DIR__ . '/app/assets/pdf/blank-test.pdf');
$tid = $pdf->ImportPage(1);

$pdf->WriteHTML('body{background:#FFF;color:#F00;}', 1);
$pdf->AddPageByArray([
  'orientation' => 'L',
  'sheet-size' => [30, 30],
]);
$pdf->useTemplate($tid);

// right here
$pdf->WriteFixedPosHTML('<div id="title">This is a Test</div>', 4.88, 4.8, 83.38, 5.19, 'auto');
//\\

$pdf->Output('mpdf-test.pdf', \Mpdf\Output\Destination::FILE);
```

**Comment by finwe** [comment]
This needs a snippet in order to incorporate it to a test to prevent regressions. Please add.

**Comment by dovestyle** [comment]
I'm sorry, I should correct myself; it's a notice, not an error, but my job queue does not discern between them and treats it as an exception.

I've added the snippet anyway, in case it's useful. It will create the PDF successfully and correctly, just throws the ugly notice..

```
$ php mpdf-test.php 
PHP Notice:  Undefined variable: rotate in ./app/vendor/mpdf/mpdf/src/Mpdf.php on line 16029
PHP Notice:  Undefined variable: rotate in ./app/vendor/mpdf/mpdf/src/Mpdf.php on line 16029
PHP Notice:  Undefined variable: rotate in ./app/vendor/mpdf/mpdf/src/Mpdf.php on line 16061
```

**Comment by Farukcoder** [comment]
hot to fix Undefined variable: cw 
![image](https://user-images.githubusercontent.com/67540985/159628993-7767e822-bbdf-4a33-8edd-83b97b46379a.png)
