### ISSUE TITLE
Bitshift by 7128 bits?

### ISSUE THREAD

**Issue by 5lava** [mpdf/mpdf#569]
https://github.com/mpdf/mpdf/blob/v5.4.0/classes/bmp.php#L93
https://github.com/mpdf/mpdf/blob/v7.0.1/src/Image/Bmp.php#L106

Looks like it's supposed to be 7 :)

**Comment by Klap-in** [comment]
Do you know a test case as well to demonstrate proper vs unproper application of this?

**Comment by 5lava** [comment]
I don't have a case. I just noticed that piece of code when was running [php7cc](https://github.com/sstalle/php7cc) against some ancient codebase.

Logic suggests that bitshift by 7128 bits (i.e. dividing by 5518348104447409206991593943942152608329205242101077213718480321180708948011963861995816006175270468934820609018643828901313864539258576746681797592803215078340171552355518579698943182413743354580862317079246184713890436855831676456221237998336218825764337271779851467721918563062949042756080004648658099769241748153039289388777700317569810353865516577921816989657579148166955632852789009179818330565438944984813772640083445453333149405008417980494276164297309273912850189776250948919122182228763633121494538479987570963007061812592014654529320152197520453173337213328155793595586688572400717035900909348447266342258174755124179452839024678962846251719845402148101445841711677965415161445327341239473605948012701299969580258637240221184670927302229016789683240061482689504283598249819255895705274237061829436816984983905451959416413050449685738330023112979857206795711532594459524866763103989253306129049918672503518259849734201143173159737358451355214167011444279255790997515984773980969716170045350769359661016525826704299490735665913187150842995373116809388098470144822666148826721421787183550173195335596073959544659668878184116236459401486453495098217982784447496334925849230241308858435319450748299173238712544697250228468771761743555008069182803984486406960740713126565885617962394134073197968456501733379735826386441548409509270801360331938130550115065848878542214434813607593817421521571371462916990697547017694772087203882794116935133914451765645840893129618626962878409352232043104789690620751166995612657725372804006574162255194116245385947974286304529616365590772194669313220921263328403822210991705222797207146962272275783729201288322032568054937954764847956093492071997219315282845834836667115172761821962051309446176768656437465591952309868492980179384859505821981969003953721058703632332236312617908341789274675362969101674738545505587310233802796297507010285978298225307478390589072920905223584910067056939311445820637043934193014641981087123013507652904844203770431115140593269313798701360856898742814267975946264561158153967167376896954349864031467763825391723292578161643712545767121029871769718859559407828916524439312531456) barely makes sense in this context.

Also, look at the code — there's another loop in `else` branch. Compare [this](https://github.com/mpdf/mpdf/blob/v7.0.1/src/Image/Bmp.php#L100-L109) and [this](https://github.com/mpdf/mpdf/blob/v7.0.1/src/Image/Bmp.php#L113-L120). The latter one is almost exactly the same, the only difference is outer loop direction (because of `$flip`) and... bitshift by `>> 7`, not `>> 7128`. Loop direction is the only thing that should be affected by `$flip` (which is a sign of a negative height in BMP, which indicates the image is stored upside down (documented [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183376%28v=vs.85%29.aspx), [here](http://en.wikipedia.org/wiki/BMP_file_format#Pixel_array_.28bitmap_data.29), [here](http://www.fileformat.info/format/bmp/egff.htm))).

So, all in all, it makes me think that `128` was copy-pasted there by an accident.

**Comment by Klap-in** [comment]
Thanks the explanation!
