### ISSUE TITLE
Move mPDF to its own namespace

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#57]
For version 7.0 I'd like to introduce mPDF namespace for all classes. So the main class would be \mPDF\mPDF, all other classes would be prefixed accordingly.

**Comment by TomK** [comment]
While we're doing this, PSR-4 compliance would be great

**Comment by finwe** [comment]
Yes, that is exactly my intent.

**Comment by finwe** [comment]
On second thougths, maybe classic PascalCase would be better - `\Mpdf\Mpdf`. Thoughts?

**Comment by blueliquiddesigns** [comment]
\mPDF\mPDF\ seems easier on the eyes. That would be my vote.

**Comment by TomK** [comment]
I'd probably go with PSR1 definition in this case `\Mpdf\Mpdf`
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md

There's some things in PSR I disagree with (mainly brace position), but this isn't one of them. With lots of imports, the uniformity is pleasant.

**Comment by garex** [comment]
\Mpdf\Mpdf + 1

**Comment by blueliquiddesigns** [comment]
I had the same second thoughts as @finwe. Keep the the standard: \Mpdf\Mpdf

**Comment by sebathi** [comment]
This is a need :D

**Comment by finwe** [comment]
I have a working cleaned up version in [namespaces](https://github.com/mpdf/mpdf/tree/namespaces) branch

**Comment by garex** [comment]
What about semantic version? As this seems to break all compatibility.

One possible workaround is to have some wrapper-retranslator in root namespace, that will translate all requests to new namespaced code. And put it in standalone repo.

Or this is too complicated?

**Comment by finwe** [comment]
All this is planned for version 7.

**Comment by sebathi** [comment]
Is there a roadmap for it? Thank you for this great work!

**Comment by finwe** [comment]
No, there is no roadmap ATM, sorry.
