### ISSUE TITLE
Error while testing updated version

### ISSUE THREAD

**Issue by Neobugu** [mpdf/mpdf#576]
Hello, I updated the mpdf version up to the latest, while doing a test, I got this error message:

> Parse error: syntax error, unexpected '/', expecting ',' or ';' in C:\Apache24\htdocs\mpdf\Mpdf.php on line 60

While reading the file, line 60 is:

> const SCALE = 72 / 25.4;

Is this any misconfiguration of my code?

Before upating, i got preg_replace error due to php version

**Comment by Klap-in** [comment]
I'm sorry, but you missed the helpful template. Could you help us at least with providing some background info? That is very useful for trying to reproduce your situation. Thanks!
Please see copy below:

    ### I found this bug / would like to have this new functionality
    
    ### This is mPDF and PHP version and environment (fpm/cli etc) I am using
    
    ### This is a PHP code snippet I use
    
    ```
    <?php
    
    
    ```
    
    ### This is a HTML/CSS code snippet I use
    
    ```
    
    ```

**Comment by Neobugu** [comment]
sorry thought it was an example, re-formating then
