### ISSUE TITLE
Error while testing updated version

### ISSUE THREAD

**Issue by Neobugu** [mpdf/mpdf#577]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md

### I found this bug / would like to have this new functionality
While testing updated version of mpdf I got this error con my webpage 

> Parse error: syntax error, unexpected '/', expecting ',' or ';' in C:\Apache24\htdocs\mpdf\Mpdf.php on line 60

### This is mPDF and PHP version and environment (fpm/cli etc) I am using

My mPDF is 

> const VERSION = '7.0.3';

& my PHP version is 

> 5.5

### This is a PHP code snippet I use
Dunno if I can do this but:

[https://jsfiddle.net/sk7652kz/1](https://jsfiddle.net/sk7652kz/1)
### This is a HTML/CSS code snippet I use

```

```

**Comment by noorcs** [comment]
mPDF 7.0 requires PHP ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0
You are using PHP 5.5. Please upgrade to at least PHP 5.6.
