### ISSUE TITLE
Feature: setasign/fpdi: 2.0 support

### ISSUE THREAD

**Issue by polukes** [mpdf/mpdf#578]
Please add support to setasign/fpdi: 2.0 version. 
For example I cannot use mPDF with newest version of iio/libmergepdf.

**Comment by finwe** [comment]
Related to https://github.com/mpdf/mpdf/issues/480

**Comment by mpochron** [comment]
+1

**Comment by hella-schu** [comment]
Yes please!

**Comment by do-while** [comment]
+1

**Comment by azbatuk** [comment]
+1

**Comment by thbl** [comment]
+1

**Comment by JanSlabon** [comment]
I'm on it: https://github.com/JanSlabon/mpdf/tree/FPDI-2-Update

**Comment by JanSlabon** [comment]
May be the case but please do not use this in production! This was my first commit to the upgrade and it was tested only with the tests suite of mPDF while this part is only covered sporadic ;-)

**Comment by Y0lk** [comment]
Looking forward to this. Any update?

**Comment by commonpike** [comment]
I cant use FPDF+PDFI when using mPDF because of these dependencies..  dropping mPDF for now I'm afraid.

**Comment by JanSlabon** [comment]
The pull request is [there](https://github.com/mpdf/mpdf/pull/899). Feedback and/or discussion is welcome.

**Comment by commonpike** [comment]
Yes, and that's great. But you said 'don't use this in production' .. 15 files changed, so I'm not sure what the status is..

**Comment by donalturrentine** [comment]
I don't use ImportPage in my application and I do extensive testing for the use cases... I'm happily using my fork in production via composer.

**Comment by JanSlabon** [comment]
@commonpike From my point of view the final pull request is stable. @donalturrentine just commented directly after I did my first commit, which was not tested nor was it working as expected! If he still uses the fork after the first commit, it is completely broken and I urgently suggest not to use it. The resulting PDFs were faulty - still some viewers were able to display them. But under the hood they were simply broken. Upgrade to the current state of the pull request and everything should be fine. Feedback is welcome!

**Comment by commonpike** [comment]
Thanks for the clarification, and the PR.

I'm trying to use it, but I can't figure it out :-/ I am stuck to using composer to get the branch of your PR into my app, which works, but somehow the psr-4 autoloaders  don't seem to pick it up. `new \Mpdf\Mpdf();` says class not found and so does `new Mpdf();` ..

.. still just hoping this is merged anytime soon, that would be great.

**Comment by davidjosephhayes** [comment]
CLI add variation of @commonpike 
```
composer config repositories.janslabon_mpdf_fpdi_update vcs https://github.com/JanSlabon/mpdf.git
composer require --prefer-source 'mpdf/mpdf:dev-FPDI-2-Update'
```

**Comment by finwe** [comment]
v8.0-RC1 with FPDI 2 dependency is out. Test away.
