### ISSUE TITLE
Undefined index: l in src/Mpdf.php on line 21256

### ISSUE THREAD

**Issue by minhnguyenerp** [mpdf/mpdf#586]
### I found this bug / would like to have this new functionality
mPDF crashed at CssManager.php line 1386 with the message "Undefined offset: -1". It seems the variable $this->tbCSSlvl cause the problem.

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
I am using mPDF 7.0.2, PHP7.0

**Comment by Klap-in** [comment]
How is Mpdf instantiated in your setup?
Which html is feeded into mPDF, such that it triggers this error?  (please provide a _small_ html example)

This is useful for reproducing your case, and allows to create the unit test for this issue. Thanks!

**Comment by jurgentreep** [comment]
I'm having the same issue.

PHP:
```
$mpdf = new Mpdf();
$mpdf->WriteHTML($html);
```
HTML:
```
<table>
	<thead>
		<th></th>
	</thead>
</table>
```

**Comment by machour** [comment]
@jurgentreep your code produce this error for me: 
```
PHP Notice:  Undefined index: l in src/Mpdf.php on line 21256
PHP Notice:  Undefined index: l in src/Mpdf.php on line 21482
```

and not a warning related to CssManager.php. Can you confirm that's the case for you too? (If so, please open a new bug report)

**Comment by jurgentreep** [comment]
@machour you're correct I'll create a new issue.

**Comment by finwe** [comment]
Closing as stale. Feel free to reopen with a code example.
