### ISSUE TITLE
Padding does not work in PDF but does work in email

### ISSUE THREAD

**Issue by cliffordp** [mpdf/mpdf#591]
### I found this bug

Padding does not render in PDF even though email viewer displays the same HTML correctly.

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
mPDF v7.0.2
PHP v5.6.20

### This is a PHP code snippet I use

Running mPDF as such:

```
<?php

ob_clean();

$mpdf = new \Mpdf\Mpdf( array( 'mode' => 'c' ) );

$mpdf->WriteHTML( $html ); // same HTML that gets sent to email content

$mpdf->Output( $file_name, 'F' ); // PDF file gets saved to server and then attached to email
```

### This is the HTML/CSS code snippet I use

Right before the closing `</head>` I have this styling:

```
<style>
		.button-green {
			background-color: #a0ce4e;
			border: none;
			color: white;
			padding: 15px 32px;
			text-align: center;
			text-decoration: none;
			display: inline-block;
			font-size: 16px;
			margin: 4px 2px;
			cursor: pointer;
		}
</style>
```

I have this directly after the opening `<body>`:
`<a class="button-green"  href="http://example.com/">A green button with padding</a>`

It renders in the email client like this **(good)**:
![image](https://user-images.githubusercontent.com/1812179/34394808-66c1d5ca-eb21-11e7-883b-9c936fc99f7b.png)

However, the mPDF result is this **(bad)**:
![image](https://user-images.githubusercontent.com/1812179/34394818-80c394fe-eb21-11e7-92a8-f3bb8bc957db.png)

Here's the actual PDF file, should you need it for debugging purposes: 
[tribe_tickets_5a441bc150dfd057314424.pdf](https://github.com/mpdf/mpdf/files/1589972/tribe_tickets_5a441bc150dfd057314424.pdf)

**Comment by finwe** [comment]
I doubt mPDF supports `inline-block`. Have you tried simple `display: block`?

Is your HTML otherwise well-formed?

**Comment by jakejackson1** [comment]
mPDF treats HTML as either block or inline. The anchor tag is an inline element which doesn't support padding. [Refer to mPDF's supported CSS for more info](http://mpdf.github.io/css-stylesheets/supported-css.html).

**Comment by cliffordp** [comment]
I couldn't find what part of the "supported CSS" link you shared is relevant here.

However, I tried both both display "block" and "inline" and they appeared the exact same. (I didn't change anything else in the CSS.)

Yes, the rest of the HTML is well-formed.

Are you able to replicate this in v7.0.2 with the given CSS or have any other suggestions to change this CSS to?

Thanks.

**Comment by finwe** [comment]
Enclose the anchor `a` in a *block-by-default* element, eg. a `div`.

Closing by quoting @jakejackson1:
> mPDF treats HTML as either block or inline (you can't change this behaviour).

**Comment by cliffordp** [comment]
This still doesn't render in the PDF with any padding. It should, right?

```
.button-green {
	background-color: #a0ce4e;
	border: none;
	color: white;
	padding: 15px 32px;
	text-align: center;
	text-decoration: none;
	display: block;
	font-size: 16px;
	margin: 4px 2px;
	cursor: pointer;
}
```

```
<div>
<a class="button-green" href="http://example.com/">A green button with padding</a>
</div>
```

**Comment by finwe** [comment]
No, the padding is on the a element which is inline and thus does not support padding. Set the padding on the div. 

31. prosince 2017 21:35:45 SEČ, Clifford <notifications@github.com> napsal:
>This still doesn't render in the PDF with any padding. It should,
>right?
>
>```
>.button-green {
>	background-color: #a0ce4e;
>	border: none;
>	color: white;
>	padding: 15px 32px;
>	text-align: center;
>	text-decoration: none;
>	display: block;
>	font-size: 16px;
>	margin: 4px 2px;
>	cursor: pointer;
>}
>```
>
>```
><div>
><a class="button-green" href="http://example.com/">A green button with
>padding</a>
></div>
>```
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/mpdf/mpdf/issues/591#issuecomment-354622789

-- 
Odesláno aplikací K-9 Mail ze systému Android. Omluvte prosím moji stručnost.

**Comment by cliffordp** [comment]
This worked. Thanks.

```
.button-green {
	background-color: #a0ce4e;
	border: none;
	color: white;
	padding: 15px 32px;
	text-align: center;
	text-decoration: none;
	display: inline;
	font-size: 16px;
	margin: 4px 2px;
	cursor: pointer;
}
```

```
<div class="button-green">
<a href="http://example.com/">A green button with padding</a>
</div>
```
