### ISSUE TITLE
page-break-after: always works but not avoid

### ISSUE THREAD

**Issue by Cipa** [mpdf/mpdf#6]
This code works

```
h2, h3, h4{
        page-break-after: always;
    }
```

but this doesn't

```
h2, h3, h4{
        page-break-after: avoid;
    }
```

**Comment by danielhjames** [comment]
Hi Cipa, avoid is a valid option according to http://mpdf1.com/manual/index.php?tid=34

Please post some samples for examination.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information.
