### ISSUE TITLE
SVG parser error in <use>-tag

### ISSUE THREAD

**Issue by brogon** [mpdf/mpdf#600]
### I found this bug / would like to have this new functionality
There is a parsing bug in the `<use>`-tag part of the SVG parser, introduced by the resolution of #338.

First, the tag itself is matched, and the most essential part (the `xlink:href` value) extracted:

    preg_match_all('/<use ([^>]*)xlink:href\s*=\s*["\']#([^>]*?)["\']([^>]*)\/>/si', $data, $links);

Other parameters are caputured with the parenteses after "<use " and before the tag's end "\/>". Those are later concatenated to a single string again:

    $inners = $links[1][$i] . ' ' . $links[3][$i];

And then additional attributes ('x' and 'y') are searched. Here the RegEx was changed to require a whitespace character before 'y=...' or 'x=...':

    // Change x,y coords to translate()
    if (preg_match('/\sy\s*=\s*["\']([^>]*?)["\']/', $inners, $m)) {
        $y = $m[1];
    } else {
        $y = 0;
    }

The issue arises, if one of those attributes are at the beginning of the tag; like here (original output of a Python matplotlib SVG):

    <use x="63.623047" xlink:href="#DejaVuSans-31"/>

Here, "$inners" gets concatenated to:

    $inners = 'x="63.623047"' . ' ' . '';
    
    ==> $inners = 'x="63.623047" ';

So the new RegEx no longer matches, as there's no (white)space in front of "x=". 

There are three options to solve this issue:

1. Include the space between tag name and first (non-href) attrbute, i.e.:

       preg_match_all('/<use( [^>]*)xlink:href\s*=\s*["\']#([^>]*?)["\']([^>]*)\/>/si', $data, $links);

2. Prefix a space to `$inners`:

       $inners = ' ' . $links[1][$i] . ' ' . $links[3][$i];

3. Modify the RegEx to allow the string beginning as alternative to a whitespace character, e.g. 
   by using non-capturing parenteses:

       if (preg_match('/(?:^|\s)y\s*=\s*["\']([^>]*?)["\']/', $inners, $m)) {

   This has to be changed in all 4 occurences.

### This is mPDF and PHP version and environment (fpm/cli etc) I am using

package | version
------------|------------
mPDF | 7.0.2
PHP | 5.6.32 (cli)

**Comment by finwe** [comment]
Thanks for the report! Can you please share an example SVG file affected by this?

**Comment by brogon** [comment]
The [demo.svg.gz](https://github.com/mpdf/mpdf/files/1600277/demo.svg.gz) rendered by the current mPDF version:
![image](https://user-images.githubusercontent.com/17986093/34520242-3095ee66-f088-11e7-929c-227fd65d1cb0.png)

Expected result:
![image](https://user-images.githubusercontent.com/17986093/34520303-71919852-f088-11e7-8092-404e6c231e59.png)

**Comment by brogon** [comment]
Below the `for` loop, there seems to be a identical copy of the `use`-tag processing, which essentially sports the same issue on [Line 2951](https://github.com/mpdf/mpdf/blob/c69e1facf8e69f2a2ede6f40469670631c96cc0f/src/Image/Svg.php#L2951):

    preg_match_all('/<use ([^>]*)xlink:href\s*=\s*["\']#([^>]*?)["\']([^>]*)>\s*<\/use>/si', $data, $links);

I don't know if that block makes sense at all (I'm not that deep into the library's logic), but if it does, you should change/correct it there as well.
