### ISSUE TITLE
mPDF update FPDI Parser to Commercial Version

### ISSUE THREAD

**Issue by fsmalaquias** [mpdf/mpdf#608]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md

Hi,

I'm trying to user FPDI Parser Commercial Version that uses FPDI 2.0.*

I updated mpdf composer file to user FPDI Parser 2.0 but I think that mPDF 7.0.3 is not prepared to use it.

How can I help?!

mPDF needs to have a version with FPDI Parser Commercial

This is the manual for upgrade
https://manuals.setasign.com/fpdi-manual/v2/migrating/

**Comment by finwe** [comment]
See also https://github.com/mpdf/mpdf/issues/480

**Comment by JanSlabon** [comment]
You can use this again as of mPDF 8. @finwe I guess you can close this one :-)
