### ISSUE TITLE
Deprecated: preg_replace()

### ISSUE THREAD

**Issue by MehGokalp** [mpdf/mpdf#61]
Hi there, i use 5.7.4 version of mpdf and my php version is 5.6.12.
I use this code
```php
$pdf->setHTMLFooter('{DATE j-m-Y}');
```
end get that error:
```
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in somefiles/_mpdf/mpdf.php on line 7333
```

Thanks.

**Comment by finwe** [comment]
Please, try to use MPDF 6.0. The branch 5.7 will probably no longer be maintained. Could you please also report if 6.0 solved things for you?

**Comment by finwe** [comment]
There is no preg_replace call on line 7333 in neither of versions 5.7.4 or 5.7.4a from this repository. Closing, can reopen when additional details are posted.
