### ISSUE TITLE
removing content-type ... charset from header (and leaving meta charset in) -> 100% system load 

### ISSUE THREAD

**Issue by OliverLeitner** [mpdf/mpdf#611]
after i removed the following line from my html content:

`<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-15">`

and just kept this one:

`<meta charset="ISO-8859-15">`

As suggested by W3C, the system experienced a 100% load and script timeouts.

mpdf: latest from github.com
Server: Windows 2008 64bit
XAMPP with php 7.1.x latest 32bit (XAMPP has 32bit versions for windows only...)

The main function for pdf generation:
```
	public function writePDF($pdfconfig,$data,$savepath,$var,$addstr="",$pdftype=""){
		//lets do the pdf
		$mpdf = new \Mpdf\Mpdf([
			'mode' => 0,
			'format' => 'A4',
			'default_font_size' => 12,
			'default_font' => 'verdana'
		]);

		//get pdf configuration options filled into pdf file
		foreach($pdfconfig AS $key => $value){
			$mpdf->$key($value);
		}
		//write our pdf file...
		$mpdf->SetCompression(true);
		$mpdf->WriteHTML($data);

               $pdf_root = "/path/to/the/pdfs";

		//special case for customer signing...
		if($pdftype == 'S'){
			$out = $mpdf->Output($var['articlenumber'].$addstr.'.pdf','S');
			return $out;
		} else if($pdftype == 'I'){
			$out = $mpdf->Output($var['articlenumber'].$addstr.".pdf",'I');
			return $out;
		} else if($pdftype == 'D'){
			$out = $mpdf->Output($var['articlenumber'].$addstr.".pdf",'D');
			return $out;
		} else {
			$mpdf->Output($pdf_root.$var['articlenumber'].$addstr.".pdf",$pdftype);
		}
	}

```

**Comment by OliverLeitner** [comment]
been a while...

do you guys need any further information...?

i did cleanup that function a bit inbetween...

**Comment by Klap-in** [comment]
The html (i.e. $data) is missing and there are a lot of variables not defined.

Could you please replace all the variables( i.e. `$data`, `$pdfconfig`, etc etc)  by its values? Thanks!

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen, if still applicable on current version.
