### ISSUE TITLE
DUMP creating pdf from html and css: PHP Warning: preg_replace(): Unknown modifier '0'

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [mpdf/mpdf#613]
### I found this bug / would like to have this new functionality

When i try to create a pdf from a css file and a html document i get the following error:

`PHP Warning: preg_replace(): Unknown modifier '0' in /mpdf/src/CssManager.php line 567`

Which is the following line in `CSSManager.php`
```php
...
 $s = preg_replace('/\"' . $ffp . '\"/', $w[0], $s);
...
```

### This is mPDF and PHP version and environment (fpm/cli etc) I am using

Php Version 7 and mPDF 7

### This is a PHP code snippet I use

```
<?php
  $mpdf = new \Mpdf\Mpdf();
  $stylesheet = file_get_contents( 'main.css' );
  $html = file_get_contents($this->tempDir . $fileName);
  $mpdf->WriteHTML($stylesheet, 1);
  $mpdf->WriteHTML($html, 2);
  $mpdf->Output(); 

```

I am not sure wheater it is a bug, or it is just my bad using falty css. With other mode options it works, but i don't get the visual output i am aiming for.

Any help is appreciated very much! Thank you very much! :)

**Comment by finwe** [comment]
Please, share your CSS and HTML contents.
