### ISSUE TITLE
Add Margin Configs to Documentation

### ISSUE THREAD

**Issue by db-dzine** [mpdf/mpdf#615]
### I found this bug / would like to have this new functionality

The config documentation missies the margin parameters. In old mpdf 6 it was mgl, mgr, mgh, mgf. This has changed in version 7 to "margin_left" etc.

I searched the whole day to find it, but it is nowhere mentioned. 

Neither here: https://mpdf.github.io/reference/mpdf-variables/overview.html
Nor here: https://github.com/mpdf/mpdf/blob/development/src/Config/ConfigVariables.php

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
Mpdf 7.0.3
### This is a PHP code snippet I use

```
<?php
			$mpdfConfig = array(
				'mode' => 'utf-8', 
				'format' => 'A4',    // format - A4, for example, default ''
				'default_font_size' => 0,     // font size - default 0
				'default_font' => '',    // default font family
				'margin_left' => 0,    	// 15 margin_left
				'margin_right' => 0,    	// 15 margin right
				// 'mgt' => $headerTopMargin,     // 16 margin top
				// 'mgb' => $footerTopMargin,    	// margin bottom
				'margin_header' => 0,     // 9 margin header
				'margin_footer' => 0,     // 9 margin footer
				'orientation' => 'P'  	// L - landscape, P - portrait
			);
			$mpdf = new \Mpdf\Mpdf($mpdfConfig);	

```

**Comment by Dasc3er** [comment]
The margin configs you are looking for are documented here: https://mpdf.github.io/reference/mpdf-functions/construct.html
Precisely, _mgt_ is now _margin_top_ and _mgb_ is _margin_bottom_.

**Comment by finwe** [comment]
Closed in https://github.com/mpdf/mpdf.github.io/commit/6c5c8eb26e9126e783ac06885de8c9831f2cd013
