### ISSUE TITLE
Creating more pdf files in one script throws an error "Undefined offset: -1" in mpdf\src\CssManager.php

### ISSUE THREAD

**Issue by pcipov** [mpdf/mpdf#617]
This works:
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML($html1);
$mpdf->Output("file1.pdf","F");

But I want to create two pdf files in one script. This doesn't work:
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML($html1);
$mpdf->Output("file1.pdf","F");
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML($html2);
$mpdf->Output("file2.pdf","F");

It throws an error "Undefined offset: -1"
in file: ... mpdf\src\CssManager.php

Do I have to reset it after first output? How?

Thank you.

**Comment by Klap-in** [comment]
Which html is feeded into mPDF, such that it triggers this error?  (please provide a _small_ html example)

This is useful for reproducing your case, and allows to create the unit test for this issue. Thanks!

**Comment by pcipov** [comment]
You are right. WhiteHTML tiggers this error. I changed the code to be simple, so $html1=$html2=$html.

$html=
`<html>
<body>
  <div style="width: 100%; text-align: center;">
    <p style="margin: 0px 0px 5px 0px; font-size: 20px; font-weight: bold;">TITLE 1</p>
    <p style="margin: 0px 0px 5px 0px; font-size: 16px; font-weight: normal;">TITLE 2</p>
  </div>
  <div style="width: 100%; margin-top: 20px; clear: both; text-align: center;">
    <p style="margin: 10px 10px 0px 10px; font-size: 42px; font-weight: bold;">VOUCHER</p>
  </div>
  <div style="width: 100%; margin-top: 30px; clear: both; text-align: left;">
    <p style="margin: 0px 0px 5px 0px; font-size: 20px; font-weight: bold;">Tourist</p>
    <table style="width: 100%; font-size: 13px;">
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Name</th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Name</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Address</th></th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Address</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Contact</th></th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Contact</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Persons</th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Persons</td></tr>
    </table>
  </div>
  <div style="width: 100%; margin-top: 20px; clear: both; text-align: left;">
    <p style="margin: 0px 0px 5px 0px; font-size: 20px; font-weight: bold;">Accommodation</p>
    <table style="width: 100%; font-size: 13px;">
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Period</th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Period</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Length of stay</th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Length of stay</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Beds</th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Beds</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Extra-beds</th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Extra-beds</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Accommodation</th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Accommodation</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">House</th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">House</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Address</th></th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Address</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">GPS</th></th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">GPS</td></tr>
      <tr><th style="width: 30%; padding: 9px; background-color: #DDDDDD; text-align: right;">Contact</th><td style="width: 70%; padding: 9px; background-color: #EEEEEE;">Contact</td></tr>
    </table>
  </div>

  <div style="width: 100%; margin-top: 20px; clear: both; text-align: center;">
    <p style="margin: 10px 0px 0px 0px; font-size: 14px; font-weight: normal;">text</p>
  </div>
  <div style="width: 100%; margin-top: 20px; clear: both; text-align: center;">
    <p style="margin: 10px 0px 0px 0px; font-size: 14px; font-weight: normal;">text</p>
  </div>
  <div style="width: 100%; margin-top: 20px; clear: both; text-align: center;">
    <p style="margin: 10px 0px 0px 0px; font-size: 14px; font-weight: normal;">text</p>
  </div>
  <div style="width: 100%; margin-top: 20px; clear: both; text-align: center;">
    <p style="margin: 10px 0px 0px 0px; font-size: 14px; font-weight: normal;">text</p>
  </div>
  <div style="width: 100%; margin-top: 20px; clear: both; text-align: center;">
    <p style="margin: 10px 0px 0px 0px; font-size: 14px; font-weight: normal;">text</p>
  </div>

</body>
</html>
`
Doesn't matter how many <div><p> elements are there.
When I delete any <tr> content, it works. As if it were a problem with buffer for <tr> element. Maybe html parser bug.

**Comment by pcipov** [comment]
My workaround:

Change this in mpdf/mpdf/src/CssManager.php from line 1510:
`//===============================================
// Cascading forward CSS e.g. "table.topic td" for this table in $this->tablecascadeCSS
//===============================================
// STYLESHEET TAG e.g. table
$this->_mergeFullCSS($this->tablecascadeCSS[$this->tbCSSlvl - 1], $this->tablecascadeCSS[$this->tbCSSlvl], $tag, $classes, $attr['ID'], $attr['LANG']);
//===============================================
`
to this:
`//===============================================
// Cascading forward CSS e.g. "table.topic td" for this table in $this->tablecascadeCSS
//===============================================
// STYLESHEET TAG e.g. table
$this->tbCSSlvl = $this->tbCSSlvl==0 ? 1 : $this->tbCSSlvl; // BUG REPAIR
$this->_mergeFullCSS($this->tablecascadeCSS[$this->tbCSSlvl - 1], $this->tablecascadeCSS[$this->tbCSSlvl], $tag, $classes, $attr['ID'], $attr['LANG']);
//===============================================
`

**Comment by finwe** [comment]
Your issue does not have anything to do with double document creation. Your HTML is not well-formed, you have extra `</th>` tags in your HTML code.

Will close in an upcoming commit.
