### ISSUE TITLE
header Content-Disposition  filename not support utf8

### ISSUE THREAD

**Issue by Cuihongsen** [mpdf/mpdf#628]
in src/Mpdf.php 9340
header('Content-Disposition: attachment; filename="' . $name . '"');

in Safari  the filename Garbled

**Comment by finwe** [comment]
Sure, feel free to pass ASCII filename only to `Output` method call as per [RFC 8187][1]. It is not in the power of mPDF to block all "invalid" user input (not mentioning that UTF-8 _can_ work on some platforms and can be of use in some use cases for some users).

[1]:https://tools.ietf.org/html/rfc8187
