### ISSUE TITLE
Config setting `'enableImports' => true` causes PHP Notices when no PDF is actually imported

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#637]
### I found this bug / would like to have this new functionality

If `enableImports` has been enabled, but no PDF is ever imported the error `count(): Parameter must be an array or an object that implements Countable /app/public/MpdfPatch/src/Mpdf.php:11451` will be triggered.

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
Mpdf development branch `c06d29e02e6dac9ba5720c284a6c96360619f9c8` and PHP7.2.

### This is a PHP code snippet I use

```
<?php
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf([
	'enableImports' => true
]);

$mpdf->WriteHTML('<div>Hello world!</div>');
$mpdf->Output();
```

PR forthcoming. Just creating an issue so I can use the ID in the unit test.

**Comment by finwe** [comment]
Closed by #638
