### ISSUE TITLE
Bug in function TOCpagebreakByArray

### ISSUE THREAD

**Issue by waltermulder** [mpdf/mpdf#655]
There is a bug in src/Mpdf.php. In the function TOCpagebreakByArray($a) (line 25576) $tocfont, $tocfontsize, $tocindent are not defined:
add:

$tocfont = (isset($a['tocfont']) ? $a['tocfont'] : (isset($a['tocfont']) ? $a['tocfont'] : ''));
$tocfontsize = (isset($a['tocfontsize']) ? $a['tocfontsize'] : (isset($a['tocfontsize']) ? $a['tocfontsize'] : ''));
$tocindent = (isset($a['tocindent']) ? $a['tocindent'] : (isset($a['tocindent']) ? $a['tocindent'] : ''));

This is for mPDF 7.0.x I  use PHP version 5.6.10

**Comment by jakejackson1** [comment]
@waltermulder please [use the issue template](https://raw.githubusercontent.com/mpdf/mpdf/development/.github/ISSUE_TEMPLATE.md) and provide a small sample that can be used to replicate this issue.

**Comment by marcospaulos** [comment]
Good night dear, I'm mPDF. When using a function: TOC pagebreak by Array, I can't disable the page numbering, even attribute the values ​​directly in their array fields.

EVEN THAT THE PAGE IS NUMBERED.``

` $mpdf->h2toc = array(
   'H1' => 0,
     'H2' => 1,
     'H3' => 2
  );

  //$mpdf->WriteHTML('<pagebreak resetpagenum="1" pagenumstyle="a" suppress="off" />');
  
 
 $mpdf->TOCpagebreakByArray(array(
    'tocfont' => '',
    'tocfontsize' => '',
    'tocindent' => '',
    'TOCusePaging' => true ,
    'paging'=> false,
    'TOCuseLinking' => '',
    'toc_orientation' => '',
    'toc_mgl' => '',
    'toc_mgr' => '',
    'toc_mgt' => '',
    'toc_mgb' => '',
    'toc_mgh' => '',
    'toc_mgf' => '',
    'toc_ohname' => '',
    'toc_ehname' => '',
    'toc_ofname' => '',
    'toc_efname' => '',
    'toc_ohvalue' => 0,
    'toc_ehvalue' => 0,
    'toc_ofvalue' => 0,
    'toc_efvalue' => 0,
    'toc_preHTML' => '',
    'toc_postHTML' => "$array_titulotulo[titulo]",
    'toc_bookmarkText' => '',
    'resetpagenum' => '1',
    'pagenumstyle' => '',
    'suppress' => '',
    'orientation' => '',
    'mgl' => '',
    'mgr' => '',
    'mgt' => '',
    'mgb' => '',
    'mgh' => '',
    'mgf' => '',
    'ohname' => '',
    'ehname' => '',
    'ofname' => '',
    'efname' => '',
    'ohvalue' => 0,
    'ehvalue' => 0,
    'ofvalue' => 0,
    'efvalue' => 0,
    'toc_id' => 0,
    'pagesel' => '',
    'toc_pagesel' => '',
    'sheetsize' => '',
    'toc_sheetsize' => '',
 ));
 
// Set a simple Footer including the page number



foreach ($arrayTexto as $titulo) {
 
    $mpdf->setFooter('{PAGENO}');

    $mpdf->WriteHTML("<h1> $titulo[titulo]</h1>");
    $mpdf->WriteHTML("<h3>$titulo[subtitulo]</h3>");
    
    $mpdf->WriteHTML("<p>$titulo[texto2]</p>");
    $mpdf->WriteHTML("<h3>$titulo[subtitulo2]</h3>");
    $mpdf->WriteHTML("<p>$titulo[texto2]</p>");
    //$mpdf->setFooter('{PAGENO}');
    //$mpdf->WriteHTML('<pagebreak   suppress="off" />');
    $mpdf->WriteHTML('<pagebreak resetpagenum="" pagenumstyle="" suppress="off" />');
    //$mpdf->AddPage();
    }`

**Comment by finwe** [comment]
Closing as stale and missing example. Feel free to open a new issue with all detail required by the issue template.

**Comment by marcospaulos** [comment]
> Use https://stackoverflow.com/questions/tagged/mpdf para todas as suas perguntas gerais ou solução de problemas!
> Para contribuir aqui, consulte a diretriz: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> * Aviso *: Deixar de fornecer as informações necessárias pode fazer com que o problema seja encerrado sem consideração

### Encontrei este bug / gostaria de ter esta nova funcionalidade
TOCpagebreakByArray 
 is not suppressing page numbering
### Esta é a versão e ambiente mPDF e PHP (server / fpm / cli etc) que estou usando
`mPDF >=7.0`
### Este é um snippet de código PHP que uso

$mpdf->h2toc = array('H1' => 0, 'H2' => 1 ,'H3' => 2);


 foreach($arrayTexto as $sumario){

 
 $mpdf->TOCpagebreakByArray("
'paging' => false,
'tocfont' => 'Arial',
 'tocfontsize' => 14,
 'toc-preHTML' => $sumario[titulo],
'resetpagenum'=> 1 ");

 //LINK PARA OS TITULOS
 //$mpdf->WriteHTML("$sumario[titulo]");

}
`` `
<? php


`` `

### Este é um snippet de código HTML / CSS que uso

`` `
![image](https://user-images.githubusercontent.com/8063871/94089381-6b710e00-fde9-11ea-9892-e50411dc30b4.png)



`` `
