### ISSUE TITLE
Data-URI not working due to incorrect filename case

### ISSUE THREAD

**Issue by RobAley** [mpdf/mpdf#660]
### I found this bug

When trying to use "list-style-image" with a data-URI encoded image, mdpf correctly creates the image in its temp dir but it doesn't appear in the final PDF.

Enabling image errors, I get the following output. /tmp/formatpump13540151947236 is the tempDir set in the config passed to the mdpf constructor. The file "_tempCSSidata8565_0.gif"  is present and correct, note the uppercase CSS in the actual filename, but lowercase in the error message :

```
Fatal error: Uncaught Mpdf\MpdfImageException: Could not find image file (/tmp/formatpump135401519472369/_tempcssidata8565_0.gif) in phar:///formatpump.phar/vendor/mpdf/mpdf/src/Image/ImageProcessor.php:1333
Stack trace:
#0 phar:///formatpump.phar/vendor/mpdf/mpdf/src/Image/ImageProcessor.php(207): Mpdf\Image\ImageProcessor->imageError('/tmp/formatpump...', true, 'Could not find ...')
#1 phar:///formatpump.phar/vendor/mpdf/mpdf/src/Mpdf.php(16868): Mpdf\Image\ImageProcessor->getImage('/tmp/formatpump...', true, true, '/tmp/formatpump...')
#2 phar:///formatpump.phar/vendor/mpdf/mpdf/src/Tag/BlockTag.php(886): Mpdf\Mpdf->_setListMarker('decimal', '/tmp/formatpump...', 'outside')
#3 phar:///formatpump.phar/vendor/mpdf/mpdf/src/Tag.php(239): Mpdf\Tag\BlockTag->open(Array, Array, 19)
#4 phar:///formatpump.phar/vendor/mpdf/mpdf/src/Image/ImageProcessor.php on line 1333
```

Unless the case is changed for the error message, it appears that something in mpdf lowercases the name, which means it fails on case-sensitive file systems.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

mpdf 7.0.0
php PHP 7.1.11-0ubuntu0.17.10.1 (cli)
Ubuntu 17.10 desktop

### This is a PHP code snippet I use

```
$mpdf = new \Mpdf\Mpdf(['tempDir' => '/tmp/formatpump13540151947236']);

$mpdf->showImageErrors = true;

$mpdf->WriteHTML($some_html_with_css]);

$mpdf->Output('output.pdf');
```

### This is a HTML/CSS code snippet I use

```
.some_div li {list-style-image : url(data:image/gif;base64,R0lGODlhEgASAKIAAP/jyvihV/aKLfmxc/////9mAAAAAAAAACH5BAAAAAAALAAAAAASABIAAAMpWLrc/jDKOQkRy8pBhuKeRAAKQFBBxwVUYY5twXVxodV3nLd77f9ASQIAOw==);}

```

**Comment by RobAley** [comment]
I've found the culprits, but I'm not confident enough that there aren't other ramifications to make a pull request. 

There are two places where the list-style-image gets strtolower'd where it shouldn't :
(line numbers from the current dev branch)

In CssManager.php at line 587 we need to add
`&& $k != 'LIST-STYLE-IMAGE'`
into the whitelist of properties not to lowercase (and also LIST-STYLE ? I haven't tried that)


In Mpdf.php at line 19805 we need to drop the strtolower from
`$this->blk[$this->blklvl]['list_style_image'] = strtolower($v);`

These let my case above work. I assume it would also permit any web urls which contain case sensitive paths.

**Comment by jakejackson1** [comment]
@RobAley I think it might be less-error-prone to adjust the temporary filename so it's all in lowercase. See https://github.com/mpdf/mpdf/pull/679

**Comment by RobAley** [comment]
@jakejackson1 @finwe While that commit fixes it in this specific case (a data URI), it won't fix it in the case that the user includes a filename/url directly in their CSS (which may not be all lowercase).

I couldn't see an immediate reason why the string was strtolower'd in the first place, and I couldn't break it with my suggest fix above, so I wonder if the lowercasing is needed at all (or does it fix a different potential issue)?

**Comment by finwe** [comment]
reopening for reconsidering

**Comment by jakejackson1** [comment]
@RobAley thanks for the feedback. Whether strtolower'd is redundant (or not) will need to be carefully reviewed. I'll need to set aside some time to go through each of its uses in the code to check that no side effects occur if we remove the case conversion.

**Comment by finwe** [comment]
Closing as resolved. Will gladly reopen, if still causing problems on current version.
