### ISSUE TITLE
Table of contents not showing all chapter names from export

### ISSUE THREAD

**Issue by beckej13820** [mpdf/mpdf#664]
### I found this bug / would like to have this new functionality

The table of contents doesn't seem to be including all chapter names. 
![screen shot 2018-02-26 at 7 44 03 pm](https://user-images.githubusercontent.com/29982981/36704897-7dba16c2-1b30-11e8-896d-d1a02c0bc706.png)

The chapter names should be:
![screen shot 2018-02-26 at 7 45 12 pm](https://user-images.githubusercontent.com/29982981/36704918-9605ce4c-1b30-11e8-8fc1-f6b7a37950db.png)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF Version 3.1.0-rc.1
PHP 7.0
Pressbooks Version 5.0.0-rc.1

**Comment by finwe** [comment]
Please add an actual example of your PHP/HTML code where this occurs.
There is no mPDF 3.1.0-rc.1
