### ISSUE TITLE
Notice thrown when using more than one TOC

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#665]
### I found this bug / would like to have this new functionality
`Exception: Undefined index: TOCbookmarkText /src/TableOfContents.php:505`

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
Tested with the `development` branch (commit ed27fb22774fbd67b41074beabe169ff8ad61c24) on PHP7.2.

### This is a PHP code snippet I use

```
<?php
$mpdf = new \Mpdf\Mpdf();

$mpdf->WriteHTML('
<tocpagebreak links="on" name="first" />
<tocpagebreak links="on" name="second" />

<tocentry content="Heading 1" name="first" />
<tocentry content="Alternate 1" name="second" />
');

$mpdf->Output();
```

I'm submitting a PR for this issue shortly.

**Comment by finwe** [comment]
Jake, was this addressed in any of your recent PRs?

**Comment by jakejackson1** [comment]
Yes. This was resolved.
