### ISSUE TITLE
`Mpdf::showStats` no longer shows debugging information

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#669]
Previously, when `Mpdf::showStats` was set to `true` the PDF would include debugging information at the bottom of the generated PDF:

```
Generated in 1.53 seconds
Compiled in 1.55 seconds (total)
Peak Memory usage 4.00 MB
Number of fonts 3
```

This functionality has been removed and in the latest `development` branch`Mpdf::showStats` is a configuration variable that doesn't actually do anything.

My question is, do we restore this functionality? Or remove the unused configuration option / variable? It's easy enough to replicate this behaviour in user-land (provided `Mpdf::time0`  and `Mpdf::fonts` are publicly accessible variables), so I'd suggest it get removed. 

Thoughts?

**Comment by finwe** [comment]
Debug information was moved to PSR logging, so I guess it should have been removed and I just missed it.

**Comment by jakejackson1** [comment]
No problem. I’ll submit a PR when I’ve a moment removing the variables.
