### ISSUE TITLE
Invalid size representation "a4"

### ISSUE THREAD

**Issue by mickgrach** [mpdf/mpdf#675]
Installed through composer, under php 7.2 (with xampp on windows)

I get this error:

`Invalid size representation "a4"`

**Comment by Klap-in** [comment]
How is Mpdf instantiated in your setup?
Which html is feeded into mPDF, such that it triggers this error?  (please provide a _small_ html example)

This is useful for reproducing your case, and allows to create the unit test for this issue. Thanks!

**Comment by mickgrach** [comment]
Now that you point that out, the problem is the feeded html.
I tried writing a simple pdf with some random text and it works.

The Html i feed into mPDF is quite complex, it's an html view generated from Yii2. It worked until i updated from Yii 2.0.1 to Yii 2.0.14 and from php 5.6 to php 7.2

So you're right, it's not an issue, i'll go to stackoverflow for troubleshooting. Thanks!

**Comment by flexjoly** [comment]
Hi,

I just replied on stackoverflow. 
I don't know if it is a problem because of Bootstrap 4 or mPdf.

BS4 uses @page and sets the size to 'a3'. I tried uppercase and 'A4', but that still gives the error. Setting the size to 'auto', helps to get rid of the error. 

Greetz, flexjoly

**Comment by Klap-in** [comment]
Just a pointer: https://stackoverflow.com/questions/49191312/mpdf-mpdfexception-invalid-size-representation-a3
