### ISSUE TITLE
Invalid interpretation of CJK characters when combined with latin

### ISSUE THREAD

**Issue by bowendai** [mpdf/mpdf#676]
`$mpdf = new \Mpdf\Mpdf();
$mpdf->useAdobeCJK = TRUE;
$mpdf->autoScriptToLang = true;
$mpdf->autoLangToFont = true;
$mpdf->WriteHTML($html);`
 
when I set   $html= '收件人：小明 。 '  , it is ok,like 
![image](https://user-images.githubusercontent.com/6072950/37136079-035f1f6e-22db-11e8-8444-09d3938855cb.png)
but when I set  $html = '收件人：helloworld 。', It is wrong,like

![image](https://user-images.githubusercontent.com/6072950/37136115-272e85f6-22db-11e8-9af8-0ca5dead1402.png)
what should i do?   mPDF  version 7.0

**Comment by jakejackson1** [comment]
I've reviewed this issue. You want to enable the `useSubstitutions` option and adjust the `backupSubsFont` configuration option:

```
$mpdf = new \Mpdf\Mpdf([
	'autoLangToFont' => true,
	'autoScriptToLang' => true,
	'useAdobeCJK' => true,
	'useSubstitutions' => true,
	'backupSubsFont' => ['dejavusanscondensed','arialunicodems','sun-exta'],
]);`

One of the backupSubs has the two characters included, and they'll be substituted automatically. 

@finwe is it worth reviewing the `backupSubsFont`? The comment included in the line above it mentions that `'dejavusanscondensed','arialunicodems','sun-exta'` will recognise most scripts.

**Comment by finwe** [comment]
@jakejackson1 Good point. What about performance impact, is there any?

**Comment by jakejackson1** [comment]
@finwe I had thought the `backupSubsFont` was only used if `useSubstitutions` was enabled, but I'll have to double check. I also wasn't aware a `arialunicodems` existed in the Mpdf codebase – something else I'll have to double check.

**Comment by jakejackson1** [comment]
@finwe I reviewed the performance impact of increasing the number of fonts available in the `backupSubsFont` setting (using `'backupSubsFont' => ['dejavusanscondensed', 'freesans', 'mingliu', 'MPH2BDamase', 'aegyptus', 'sun-exta']`) and there was no change in execution time for:

1. PDFs with `useSubstitutions` disabled
1. PDFs with `useSubstitutions` enabled where there was little-to-no substitution required using current defaults versus larger font list for `backupSubsFont`  

There was an average 22% increase in execution time for PDFs that had a significant amount of substitution required. The net result was a PDF showing all missing characters (versus a PDF showing empty squares where the characters should be). When used in conjunction with `autoLangToFont` and `autoScriptToLang` on the same document there was only an average 3% increase in execution time. 

Based on these findings I'd recommend adjusting the `backupSubsFont` defaults to `['dejavusanscondensed', 'freesans', 'sun-exta']` to cover a wider range of characters out of the box and only effect the execution time slightly under certain circumstances.

**Comment by finwe** [comment]
Great work, thanks! Can close this now, I guess.
