### ISSUE TITLE
PHP 7 Deprecated contructor

### ISSUE THREAD

**Issue by githubjeka** [mpdf/mpdf#68]
PHP Deprecated Warning – yii\base\ErrorException
Methods with the same name as their class will not be constructors in a future version of PHP; mPDF has a deprecated constructor

![image](https://cloud.githubusercontent.com/assets/874234/11418840/98f79368-9434-11e5-80d6-30b4a5b71a4f.png)

**Comment by TomK** [comment]
A fix for this was merged into development branch at the start of this month. It has not yet been versioned.
While I wouldn't recommend it, you can use the development branch by specifying the version "dev-development" in your composer.json

**Comment by githubjeka** [comment]
Thanks. Branch `dev-development` works.
Let it remain open till the new release.

**Comment by Poolaidman** [comment]
How much of a performance boost did you notice using php7? I'm just curious as I use it to generate 100+ pages per off at a time and it averages about 1 minute

**Comment by paveljanda** [comment]
:+1:

**Comment by soukicz** [comment]
FYI - version 6.1.0 was released few days ago with this fix

**Comment by liviuk2** [comment]
Hi,
I steel get this error when using php 7.0.8, if I switch php to 5.6.10 it's working correctly. Any idea how can I cat it work on php 7.0.8?

**Comment by votanlean** [comment]
to fix without update library:
https://cweiske.de/tagebuch/php4-constructors-php7.htm
