### ISSUE TITLE
mpdf - generate error when table is larger then one page

### ISSUE THREAD

**Issue by cdmathukiya** [mpdf/mpdf#682]
i am using

> mpdf 7.1
> 
> php 7.0
> 
> codeigniter 3

mpdf generate error when table is larger then one page

my code is here,

```
        $mpdf = new \Mpdf\Mpdf();
        $mpdf->shrink_tables_to_fit = 0;
        $pdfFilePath = $quotation_no . '.pdf';
        $mpdf->WriteHTML($html);
        ob_clean();
        $mpdf->Output($pdfFilePath, 'D');
```
it's working fine when table have limited row that fit in one single page, but, when row increase it generate error

**Comment by Klap-in** [comment]
Which html is feeded into mPDF, such that it triggers this error?  (please provide a html example)
Which error is thrown?

**Comment by cdmathukiya** [comment]
![pdf_generation_error](https://user-images.githubusercontent.com/18529326/37209078-cc92171c-23c9-11e8-9d3c-f6f26d4e96cd.png)

**Comment by finwe** [comment]
What is the error? Error message, line where it is being thrown?

**Comment by finwe** [comment]
Closing as stale.
