### ISSUE TITLE
Fixed position blocks don't work in htmlheaders

### ISSUE THREAD

**Issue by twinni** [mpdf/mpdf#685]
### I found this bug / would like to have this new functionality
Content in fixed position blocks are not printed when used in htmlHeader. 

It works well when written with WriteHtml(). But then this block will not repeated on every page.
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPdf version 7.0
PHP 7.2.3 

### This is a PHP code snippet I use
```
<?php
$pdf = new Mpdf();
$htmlAbsolute = '<div style="position: absolute; top: 50mm; left: 50mm; width: 100mm;">
This is text in a fixed position block element.
</div>';
$html = "<div>Hallo World." . str_repeat('<br>This is a new line.', 200);
$pdf->SetHTMLHeader($htmlAbsolute);
$pdf->WriteHTML($html);
$pdf->output();

```

### This is a HTML/CSS code snippet I use

```

```

**Comment by Klap-in** [comment]
At https://mpdf.github.io/css-stylesheets/supported-css.html is some note about when `position: ` is supported by mPDF. Did you see this?

Further: https://mpdf.github.io/what-else-can-i-do/fixed-position-blocks.html
So there are some challenges...

**Comment by twinni** [comment]
I've seen these documentation. 
As far as I understand the docu my example should work.

But you're right. There are some challenges.
I'm working on a transition from TCPDF to mPDF. The goal is to use more  OO style programming, html and css.
Right now it looks like is the same try and error procedure to get some expected result.

BTW: The line(), which I used in TCPDF doesn't work as well. 

Any hint how to print a simple line at a fixed position?

**Comment by jakejackson1** [comment]
This has been fixed in the development branch via https://github.com/mpdf/mpdf/commit/01f9bfef7e22dda596c187b59d470eb9b928284f
