### ISSUE TITLE
When use italic style in arabic language text view as square 

### ISSUE THREAD

**Issue by faroukmhammad** [mpdf/mpdf#690]
mPDF version:  5.7.1 or 6

when trying to use italic html tag (`<em>`, `<i>`) it works fine with English language but when I convert html to pdf (arabic language) example : التامين الصحي  text displays as squares:

![image](https://user-images.githubusercontent.com/15747592/37567339-4ea0a86c-2ace-11e8-9c4a-8be647bfd275.png)

**Comment by finwe** [comment]
This works OK in the last version when trying to add <i> element in arabic in the [multilingual example file](https://github.com/mpdf/mpdf-examples/blob/development/example29_multilingual_autofont.php).

Closing this. Try the last version and if the problem persists, feel free to open a new issue with all details asked for in the issue template, especially a PHP/HTML code sample to reproduce the error.
