### ISSUE TITLE
unformatted html is not able to export in pdf but html working in browser.

### ISSUE THREAD

**Issue by JoysonAnto** [mpdf/mpdf#691]
I have a issue that the html is working in browser that is not working with mpdf kindly help me with that 
the html format is dynamically fetched from user end. In browser it is working without any format rules specify but in mpdf it is maintaining some rules.

https://stackoverflow.com/questions/49378731/html-with-pdf-convertion-is-not-working-for-improper-html-format-with-mpdf-stric

**Comment by finwe** [comment]
Please note that the Issue tracker serves mainly as a place to report bugs and request new features as noted in [Contributing guidelines](https://raw.githubusercontent.com/mpdf/mpdf/development/.github/CONTRIBUTING.md). Please do not abuse it as a general questions or troubleshooting location.
