### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by kspal** [mpdf/mpdf#700]
Hi,

When generating the PDF, I get the following error:

I found this bug
PHP Warning: count(): Parameter must be an array or an object that implements Countable in XXX/vendor/mpdf/mpdf/src/Mpdf.php on line 11438

i am using php7.2 and the last version of mpdf

I have  corrected this error with this hack

`	if ($this->enableImports && (is_array($this->parsers)) && count($this->parsers) > 0) {`

**Comment by finwe** [comment]
Please, post your PHP/HTML code snippet causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by jakejackson1** [comment]
Already fixed https://github.com/mpdf/mpdf/pull/638

**Comment by kspal** [comment]
ok it fix my pb, i will wait for the next release
Thanks
