### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by huaiguoguo** [mpdf/mpdf#706]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug / would like to have this new functionality
![image](https://user-images.githubusercontent.com/1888094/38134899-bdbef4b0-3447-11e8-834f-3df1543c1c96.png)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
i am use robregonm/yii2-pdf , this repository  require mpdf/mpdf ,
![image](https://user-images.githubusercontent.com/1888094/38135032-8b477ede-3448-11e8-98a5-7327996e7004.png)

i use php version is 7.2.3, online too ,  it's work local on windows 10,  but push online ,  it's not work   , notic follows:
![image](https://user-images.githubusercontent.com/1888094/38135056-a74d2e08-3448-11e8-868c-15c353cf2df3.png)

but i am WriteHtml()  imcoming parameters is really string

### This is a PHP code snippet I use

```
<?php


```

### This is a HTML/CSS code snippet I use

```

```

**Comment by Klap-in** [comment]
Please move to a version that supports a newer version of mpdf (version 7). Your current setup supports only too old versions of mpdf. And these don't support php7.

**Comment by huaiguoguo** [comment]
@Klap-in  thanks , thank you for your reply ,  i can't remove this restriction, so the maintainer can remove it

i going to use another library  ， https://github.com/yii2tech/html2pdf
