### ISSUE TITLE
page-break-inside:avoid breaking into another page

### ISSUE THREAD

**Issue by vishaltatva** [mpdf/mpdf#708]
I have large html that is going onto PDF. I have a div with table and form and I don't want to break the page after table. I want this table and form on same page. Here I have such multiple div with table and forms. A solution is to print each div on different page, but that is space consuming. Actually I need this:

If there is only some space after table where form cannot fit, then move table onto new page, instead of page-break. So that table and form are on same page.

I have tried with page-break-after:avoid for table and page-break-before:avoid for form, But it didn't work

` <div class='parent' style='page-break-inside:avoid;'>`
`<table style='page-break-after:avoid;'>`
`CONTENT GOES HERE.....`
`</table>`
`<form style='page-break-before:avoid;'>`
`CONTENT GOES HERE.....`
`</form>`
`</div>`

I am testing this on Firefox (49.0.2) and Chrome (57.0.2987)
Here is the screenshot where table and form are on different pages. I want them on same page. I have such multiple table and forms that prints onto PDF

![screenshot](https://user-images.githubusercontent.com/13833342/38230969-117ec85e-3700-11e8-8ea1-0eeb21e0b2b3.png)

**Comment by finwe** [comment]
Please provide a full but minimal reproducible code snippet. Without it we are unable to test/fix this properly.

**Comment by jpike88** [comment]
solution: dont try to use a dive. do this instead
```
<table style="page-break-inside: avoid;">
    <tr><td>
CONTENT
 </td></tr>
  </table>
```

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen, if still applicable on current version.
