### ISSUE TITLE
Printed INLINE files are not as expected

### ISSUE THREAD

**Issue by clockover** [mpdf/mpdf#709]
Hello,

I noticed that when I generate a PDF in the browser (with Output INLINE), the file is displayed as expected on the screen.
If I save the file and print it with Adobe Reader DC, all is perfect.

But if I print it in the browser I see some little size change occurs (borders, font size...) and sometime lost font occurs (I use OCR-B on a line).

I tried with Firefox, Chrome, EDGE and I have always the same issue.
Somebody has a explain ? similar issue ? a fix ?

I used mPDF 7.03 and latest browsers/Adobe Reader version

Best regards,

**Comment by ssieb** [comment]
This happens whether the pdf was created with mpdf or not.  Don't print from the browser.  Always download it and print with a proper pdf viewer.

**Comment by clockover** [comment]
Thanks :)
Why the browsers editors don't fix that ? :'(
