### ISSUE TITLE
Request - span width

### ISSUE THREAD

**Issue by piernik** [mpdf/mpdf#717]
I have to make inline rectangle to fill in (with pen:) ). Somethink like "My name is .......... "
I can use span with border but I cannot set it's width. It is ignored. I know I can use '&nbsp;' but setting span's width would be better solution.

**Comment by finwe** [comment]
`span` is an inline element which cannot have a width. use a `div` or set `display: block` style to the `span`.

**Comment by piernik** [comment]
In css there is attribute `display:inline-block` which can have width.
Is there a mpdf equivalent?

**Comment by finwe** [comment]
inline-block is not supported. see https://mpdf.github.io/css-stylesheets/supported-css.html
