### ISSUE TITLE
Undefined index: VALUE

### ISSUE THREAD

**Issue by acabralcv** [mpdf/mpdf#720]
![mpdf](https://user-images.githubusercontent.com/11449852/38706609-ef74188a-3e94-11e8-9ce4-50b560fd5638.PNG)

By modifying vendor\mpdf\mpdf\src\Tag\Options.php,

changing the line

$this->mpdf->selectoption['currentVAL'] = $attr['VALUE'];

to

$this->mpdf->selectoption['currentVAL'] = isset($attr['VALUE']) ? $attr['VALUE'] : '';

it works normally, but the checkbox does not appear in the generation PDF.

**Comment by finwe** [comment]
Please, post your PHP/HTML code snippet causing this. Without it, we are unable to review and/or fix this correctly.

**Comment by moman13** [comment]
i have the same problem

**Comment by finwe** [comment]
you also have the same reply

**Comment by moman13** [comment]
sorry i am just beginner

**Comment by moman13** [comment]
the problem is on the blade template ,so how i display for you here

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen, if still applicable on current version.
