### ISSUE TITLE
open_basedir restriction in effect for /tmp directory

### ISSUE THREAD

**Issue by digiwirtual** [mpdf/mpdf#722]
## Description
When setting up tmp directory like $mpdf = new \Mpdf\Mpdf(['tempDir' => sys_get_temp_dir()]);
it will cause error in ./src/Cache.php line 91

First check if file !$item->isDot before $item->isFile(), because if you use isFile on '..' directory first, it will cause SplFileInfo::isFile(): open_basedir restriction in effect. File(/tmp/..) is not within the allowed path(s): (./)

### This is a PHP code snippet I use
Bug:
![obrazek](https://user-images.githubusercontent.com/5253962/38736688-254fc8a8-3f2d-11e8-8176-cb6282e227c2.png)

Fix: 
![obrazek](https://user-images.githubusercontent.com/5253962/38736661-10bdf694-3f2d-11e8-890e-5e03488e8201.png)

**Comment by finwe** [comment]
Thanks for the catch!
