### ISSUE TITLE
Table header repeat bug 7.0.3 - Undefined index: y

### ISSUE THREAD

**Issue by sreenadh** [mpdf/mpdf#724]
### I found this bug
Undefined index: y

Happens when a table has <thead> and the table does not fit on a page.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPdf version: 7.0.3
PHP 7.0.24

This has been working fine for 6.0.

#682 #516

**Comment by finwe** [comment]
Fix merged, closing.
