### ISSUE TITLE
Auto Header / Footer Height Applied to pages without a Header/Footer

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#732]
### I found this bug / would like to have this new functionality

When using the `'setAutoTopMargin' => 'stretch|pad'` and `setAutoBottomMargin => 'stretch|pad'` options, the `_setAutoHeaderHeight` and `_setAutoFooterHeight` methods apply an auto-height to pages that don't include a Header / Footer.

By default, an 11mm top/bottom margin is applied to pages that do not have any Header / Footer set.

Ian's original notes regarding the pad/stretch configuration options are as follows:

- If 'pad' margin-top sets fixed distance in mm (padding) between bottom of header and top of text.
- If 'stretch' margin-top sets a minimum distance in mm between top of page and top of text, which expands if header is too large to fit.

This suggests this functionality was only ever meant to apply when a header / footer actually exists, and not on pages that don't include them.

Opening issue to get ID for unit tests.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
Current development branch c441d4099c7a696a47af1daa820a86d91a11506d
 using PHP7.2

### This is a PHP code snippet I use

```
<?php
<style>
    @page {
        margin: 0;             
    }
    
    @page :first {
    	header: html_Header;
    	footer: html_Footer;
    }

    header {
        background: #4f4f4f;
    }

</style>

<htmlpageheader name="Header">
    Header
</htmlpageheader>

<htmlpagefooter name="Footer">
    Footer
</htmlpagefooter>

First page content

<pagebreak />

<header>
   &nbsp;
</header>

```

**Comment by finwe** [comment]
Merged #733
