### ISSUE TITLE
References to `arialunicodems` codebase/documentation

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#735]
While investigating the results of https://github.com/mpdf/mpdf/issues/676#issuecomment-372149577, I found it odd there were references to `arialunicodems` in the codebase/documentation when that particular font isn't included in Mpdf by default. 

Examples of its usage:
https://github.com/mpdf/mpdf/blob/development/src/Config/FontVariables.php#L28
https://github.com/mpdf/mpdf/blob/development/src/Config/FontVariables.php#L44
https://github.com/mpdf/mpdf/blob/development/src/Config/FontVariables.php#L310

https://github.com/mpdf/mpdf.github.io/blob/development/fonts-languages/choosing-a-configuration-v7-x.md
https://github.com/mpdf/mpdf.github.io/blob/development/fonts-languages/choosing-a-configuration-v6-x.md
https://github.com/mpdf/mpdf.github.io/blob/development/reference/mpdf-variables/backupsubsfont.md

The only hint that you actually need to install the Arial Unicode MS font yourself is in the obscure Mpdf Variables Reference for `backupsubsfont`. 

Since this font doesn't have an open source license we cannot include it with the bundled fonts. Because of the license type, my personal preference is to remove all mention of it in the codebase and documentation. The alternative is to make it explicitly clear that this font would need to be installed when ever it's referenced in the codebase / documentation. 

Does anyone have any objections to the removal of this reference? Or was there any alternate suggestions we should explore?

**Comment by finwe** [comment]
Pushed to repo and doc. @jakejackson1 Is that OK on your part?
