### ISSUE TITLE
Undefined offset: 0 Mpdf.php (line 9104) 

### ISSUE THREAD

**Issue by thehelloworld007** [mpdf/mpdf#740]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

i upgraded from mpdf 6.1.3 to mpdf 7 and am using php 7.2,
once after upgrade am getting a notice Undefined offset: 0 vendor/mpdf/mpdf/src/Mpdf.php (line 9104), am using symfony 3.4.9.
this is triggered while using 'Ln()'. as its  notice i just am currently suppressing it as mentioned in the troubleshooting section. i felt this as a bug the same happens while using multicell also.

```
<?php


```

### This is a HTML/CSS code snippet I use

```

```

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.
