### ISSUE TITLE
SVG not rendering/showing

### ISSUE THREAD

**Issue by axelra82** [mpdf/mpdf#748]
### I found this bug / would like to have this new functionality
SVG file doesn't show on PDF, i.e. on a the simplest configuration the final PDF is just blank. See code bellow.
I've tried with ~10 different SVG files. Nothing works. tmp folder is set to 777. When using < svg > element I can see the temp file being created in tmp folder. PDF i still blank.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
Apache Version | 2.4.33, PHP Version | 7.0.30, mPDF | 7 (latest, cloned ~5 days ago)

### This is a PHP code snippet I use

```
<?php
$pdfOptions = array(
	'mode' => 'utf-8',
	'format' => 'A4',
	'img_dpi' => 300,
	'dpi' => 300,
);
$pdf = new \Mpdf\Mpdf( $pdfOptions );
// Tried with and without width and height in img tag
$html = '<img src="'/path/to/file.svg'" wdith="250" height="250" />';
$pdf->WriteHTML( $html, 2 );
// Also tried Image
$pdf->Image( '/path/to/file.svg', 0, 0, 50, 50, 'svg', '', true, false);
$pdf->debug = true;
$pdf->showImageErrors = true;
$pdf->Output();
?>
```

### This is a HTML/CSS code snippet I use
Content of test "file.svg". Shows fine in any browser.
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100" height="100" viewBox="0 0 50 50">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
```

**Comment by thinkink** [comment]
If you make this, run well
the only error is **XML Declaration**

But is very easy to remove on load with regex


```

$svgString = file_get_contents(__DIR__ . '/file.svg');
$pdf->WriteHTML( $svgString  );

```
![image](https://user-images.githubusercontent.com/3516168/40447651-98a77880-5ed3-11e8-8486-5dadca3749e0.png)

**Comment by axelra82** [comment]
Thanks, but for some reason this resolved itself. I could swear I tried everything, but trying again now, it worked just fine.
If any admin could remove this issue, since it clearly was a temporary local bug.

**Comment by LordRahl90** [comment]
Please how do i remove the string "<?xml version="1.0" encoding="utf-8"?>". Thanks
