### ISSUE TITLE
PHP7: SVG handling Fatal error: 'break' not in the 'loop' or 'switch' context

### ISSUE THREAD

**Issue by danielhjames** [mpdf/mpdf#75]
Error seen when rendering SVG as part of a PDF when using PHP 7.1.0-dev (cli) (built: Dec 7 2015 12:44:25)

Commenting out the break on line 3000 of classes/svg.php works around the problem, but is too hacky.

**Comment by heldchen** [comment]
I came across this bug today and created the pull request  #89

**Comment by danielhjames** [comment]
Thanks!
