### ISSUE TITLE
Handle scientific notation in SizeConverter

### ISSUE THREAD

**Issue by yotewach** [mpdf/mpdf#753]
### I found this bug 

Mpdf\MpdfException: Invalid size representation "4.1666666646734e-5mm" 0
in /vendor/mpdf/mpdf/src/SizeConverter.php:35 

Stack trace:
#0 /var/www/com/vendor/mpdf/mpdf/src/Mpdf.php(16744): Mpdf\SizeConverter->convert('4.1666666646734...', 297) 
#1 /var/www/com/vendor/mpdf/mpdf/src/Mpdf.php(14789): Mpdf\Mpdf->SetPagedMediaCSS('', true, 'O') 
#2 /var/www/com/vendor/niklasravnsborg/laravel-pdf/src/LaravelPdf/Pdf.php(49): Mpdf\Mpdf->WriteHTML('\n \n <div cla...') 
#3 /var/www/com/vendor/niklasravnsborg/laravel-pdf/src/LaravelPdf/PdfWrapper.php(42): niklasravnsborg\LaravelPdf\Pdf->__construct('<!doctype html>...', Array)

**Comment by ssieb** [comment]
According to the CSS spec, scientific notation is valid, but the SizeConverter doesn't accept that.

I'm assuming that number is generated from a program somewhere.  I would suggest adjusting the source to round that down to 0.
