### ISSUE TITLE
Rowspan bug fix

### ISSUE THREAD

**Issue by treboralmasy** [mpdf/mpdf#757]
Update line 22194:
			if (isset($cell['rowspan'])  ){
				for ($k = $i + $cell['rowspan'] - 1; $k > $i; $k--) {
					$h += (isset( $heightrow[$k]) ? $heightrow[$k] : 0 );
				}
			}

This fixes HTML like:
```
			<table>
			<tr>
			<td rowspan="4"></td>
			<td></td>
			</tr>
			</table>
```

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.
