### ISSUE TITLE
autoload_files bug ?

### ISSUE THREAD

**Issue by Matkill** [mpdf/mpdf#763]
Hi,

I used mpdf 7.1.0 and i'm using codeigniter. I used the composer.json file from the zip file, i put it in my project folder and everything is installed correctly (vendor folder created and all the required sub-folders created) except mpdf.

Here the output console when i used composer (to show you all good):
`PS C:\wamp64\www\xxx> composer require mpdf/mpdf
Using version ^7.1 for mpdf/mpdf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 33 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2): Loading from cache
  - Installing setasign/fpdi (1.6.2): Loading from cache
  - Installing paragonie/random_compat (v2.0.12): Loading from cache
  - Installing symfony/polyfill-ctype (v1.8.0): Loading from cache
  - Installing symfony/yaml (v3.4.11): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (2.0.0): Loading from cache
  - Installing sebastian/object-enumerator (2.0.1): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/exporter (2.0.0): Loading from cache
  - Installing sebastian/environment (2.0.0): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.4.4): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (4.0.8): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.7.6): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (5.7.27): Loading from cache
  - Installing hamcrest/hamcrest-php (v1.2.2): Loading from cache
  - Installing mockery/mockery (0.9.9): Loading from cache
  - Installing squizlabs/php_codesniffer (2.9.1): Loading from cache
  - Installing tracy/tracy (v2.5.0): Loading from cache
setasign/fpdi suggests installing setasign/fpdf (FPDI will extend this class but as it is also possible to use "tecnickcom/tcpdf" as an alternative there's no fixed dependency configured.)
setasign/fpdi suggests installing setasign/fpdi-fpdf (Use this package to automatically evaluate dependencies to FPDF.)
setasign/fpdi suggests installing setasign/fpdi-tcpdf (Use this package to automatically evaluate dependencies to TCPDF.)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/yaml suggests installing symfony/console (For validating YAML files using the lint command)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
tracy/tracy suggests installing https://nette.org/donate (Please support Tracy via a donation)
Generating autoload files`

When i include MPDF in my code i have the following error:
`A PHP Error was encountered

Severity: Warning

Message: require(C:\wamp64\www\xxx\application\vendor\composer/../../src/functions-dev.php): failed to open stream: No such file or directory

Filename: composer/autoload_real.php

Line Number: 69

Backtrace:

File: C:\wamp64\www\xxx\application\vendor\composer\autoload_real.php
Line: 69
Function: _error_handler

File: C:\wamp64\www\xxx\application\vendor\composer\autoload_real.php
Line: 69
Function: require

File: C:\wamp64\www\xxx\application\vendor\composer\autoload_real.php
Line: 56
Function: composerRequireeab037956fe0dda50dc5cde99c31727b

File: C:\wamp64\www\xxx\application\vendor\autoload.php
Line: 7
Function: getLoader

File: C:\wamp64\www\xxx\index.php
Line: 315
Function: require_once`

i double checked and the problem is inside the autoload_files.php file under "vendo\composer\". there is the following code inside:
`<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '320cde22f66dd4f5d3fd621d3e88b98f' => $vendorDir . '/symfony/polyfill-ctype/bootstrap.php',
    '1d1b89d124cc9cb8219922c9d5569199' => $vendorDir . '/hamcrest/hamcrest-php/hamcrest/Hamcrest.php',
    '6124b4c8570aa390c21fafd04a26c69f' => $vendorDir . '/myclabs/deep-copy/src/DeepCopy/deep_copy.php',
    '5255c38a0faeba867671b61dfda6d864' => $vendorDir . '/paragonie/random_compat/lib/random.php',
    '7745382c92b7799bf1294b1f43023ba2' => $vendorDir . '/tracy/tracy/src/shortcuts.php',
    'bdffba51b95e502d380f6113430270a2' => $baseDir . '/src/functions-dev.php',
);`

$vendorDir = the vendor folder so all good. 
But for any reasons, for the last file required it is looking in $basedir. I checked this variable and this is the folder "applications". So i don't have any src folder inside the application folder.

I took the "src" folder from the mpdf archive and i put it inside the "application" folder and now it is working.

My question is : is it a bug or maybe i did something wrong in using the composer file ?

**Comment by Matkill** [comment]
If i want to have a dedicated folder for mpdf, like "vendor/mpdf/xxx" (because as i said, mpdf is not created with composer for any reasons) i have to modify the "autoload_static.php" and change the relative path for 2 variables:

'bdffba51b95e502d380f6113430270a2' => __DIR__ . '/../..' . '/src/functions-dev.php' ===> 'bdffba51b95e502d380f6113430270a2' => __DIR__ . '/../..' . '/**vendor/mpdf/**src/functions-dev.php'

and 
'Mpdf\\' => 
        array (
            0 => __DIR__ . '/../..' . '/vendor/mpdf/src',
            1 => __DIR__ . '/../..' . '/tests/Mpdf',
        ),
===>
'Mpdf\\' => 
        array (
            0 => __DIR__ . '/../..' . '**/vendor/mpdf/**src',
            1 => __DIR__ . '/../..' . '/tests/Mpdf',
        ),

With that it is working... maybe i've done something wrong with composer but i don't think. This is the only package where i had this problem.

**Comment by finwe** [comment]
Why are you even using some archive? All you should need to do is to run

    composer require mpdf/mpdf

in your codeigniter project. No copying files manually.

Seems to me you are just using composer incorrectly.
