### ISSUE TITLE
SVG path parser doesnt handle two consecutive decimals properly

### ISSUE THREAD

**Issue by rgpublic** [mpdf/mpdf#768]
Error is in vendor/mpdf/mpdf/src/Image/Svg.php, Function svgPath

`preg_match_all('/[\-^]?[\d.]+(e[\-]?[\d]+){0,1}/i', $arguments, $a, PREG_SET_ORDER);`

If $arguments is, for example:
`0,.14,0,.28,0,.42,0,.46-.09.92-.15,1.37-.15,1.21-.37,2.42-.61,3.63-.16.76-.33,1.51-.51,2.26`
then -.09 and .92 are not split correctly.

Improved code:
`preg_match_all('/[\-^]?(?:\d*\.\d+|\d+)(e[\-]?[\d]+){0,1}/i', $arguments, $a, PREG_SET_ORDER);`

**Comment by finwe** [comment]
Please, post your PHP/HTML code snippet causing this. Without it, we are unable to test, review and/or fix this correctly.

**Comment by rgpublic** [comment]
[logo.zip](https://github.com/mpdf/mpdf/files/2073098/logo.zip)
`
<html>
<body>
<img src="logo.svg" />
</body>
</html>
`
crashes for me.

**Comment by Klap-in** [comment]
How is Mpdf instantiated in your setup?

**Comment by rgpublic** [comment]
$mpdf=new \Mpdf\Mpdf([]);

**Comment by rgpublic** [comment]
But the error doesnt have anything to do with how Mpdf is setup or anything. Perhaps you'd like to re-read my original comment. If my example image doesn't crash on you, you are probably using an earlier PHP version (I'm using PHP 7.1) or your error_level might be different. But the error is already pretty obvious by just looking at the source code:

The string "-.09.92" should be split into "-.09" and ".92" by the regular expression. That doesnt happen. The part of the RegEx "[\d.]+" means: Either a number or a dot. Because the expression is ungreedy it collects as many of those characters at one as it can. This is why it doesnt stop after "-.09". Which is a problem even if no error is raised by PHP because the SVG is rendered incorrectly.

**Comment by rgpublic** [comment]
Seems to be fixed now with the current mpdf version (7.1.6)
