### ISSUE TITLE
Repeats thead on every page but not tfoot?

### ISSUE THREAD

**Issue by CM1990** [mpdf/mpdf#769]
<?php
	error_reporting(E_ALL);
	ini_set('display_errors', 1);

	require_once __DIR__ . '/vendor/autoload.php';
	// use Mpdf;
	$html_str=$_POST["table"];
	

	
	$pdf=new Mpdf\Mpdf();
	$pdf->WriteHTML($html_str);
		$pdf->Output();

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.
