### ISSUE TITLE
Text messes with the table

### ISSUE THREAD

**Issue by kartagis** [mpdf/mpdf#774]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug / would like to have this new functionality
I write a table, then some text. But they are overlapped.
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF version 7
PHP version 7.2.15 fpm on Ubuntu 18.04
### This is a PHP code snippet I use

```
<?php
$mpdf->WriteHTML("<table>");
    $mpdf->WriteHTML("<tr>");
    $mpdf->WriteHTML("<td colspan=2><div height='265' width='360' style='margin-top:10px;margin-right:10px;'><img height='265' width='360' src=".$first_image."/></div></td>");
    $mpdf->WriteHTML("<td><img height='130' width='190' src=".$second_image."/></td>");
    $mpdf->WriteHTML("<td><img height='130' width='190' src=".$third_image."/></td>");
    $mpdf->WriteHTML("</tr>");
    $mpdf->WriteHTML("<tr>");
    $mpdf->WriteHTML("<td><img height='130' width='190' src=".$fourth_image."/></td>");
    $mpdf->WriteHTML("<td><img height='130' width='190' src=".$fifth_image."/></td>");
    $mpdf->WriteHTML("</tr>");
    $mpdf->WriteHTML("</table>");
    $mpdf->WriteHTML("<table border=1>");
    $mpdf->WriteHTML("Sleeps up to ".$sleeps_text." persons");
    foreach ($ins as $i) {
      $mpdf->WriteHTML("<tr>.$i.</td>");
    }
    $mpdf->WriteHTML("</table>");
    $mpdf->WriteHTML("<span style='font-size:22px;'>".$title."</span>");

```

### This is a HTML/CSS code snippet I use

```

```
Please see the below screenshot to see what I mean.

![screenshot 2018-06-15 18 43 47](https://user-images.githubusercontent.com/1607518/41478045-fc06074a-70ce-11e8-94f6-33de8c47420d.png)

**Comment by jakejackson1** [comment]
```
$mpdf->WriteHTML("<table border=1>");
    $mpdf->WriteHTML("Sleeps up to ".$sleeps_text." persons");
    foreach ($ins as $i) {
      $mpdf->WriteHTML("<tr>.$i.</td>");
    }
    $mpdf->WriteHTML("</table>");
```

That is not valid table mark-up. "Sleeps up to" isn't in a table cell and `$mpdf->WriteHTML("<tr>.$i.</td>");` is not shorthand for `<tr><td></td></tr>`.

Once you are actually using valid table mark-up I'd say you'd need to write the entire table mark-up in one `$mpdf->WriteHTML` command so Mpdf can parse it correctly.
