### ISSUE TITLE
7.1.0 undefined offset x in CssManager.php line 1523

### ISSUE THREAD

**Issue by osworx** [mpdf/mpdf#775]
Using latest official release, I m getting many times the described error.
Checked other (older) installations with 6.x, this bug seems to be there for a longer time.

Line 1523 reads:
`$this->_mergeFullCSS($this->tablecascadeCSS[$this->tbCSSlvl - 1], $this->tablecascadeCSS[$this->tbCSSlvl], $tag, $classes, $attr['ID'], $attr['LANG']);`

Can only be avoided by adding this adding a check, so that section is now:
`if( isset( $this->tablecascadeCSS[$this->tbCSSlvl - 1] ) ) {
				$this->_mergeFullCSS($this->tablecascadeCSS[$this->tbCSSlvl - 1], $this->tablecascadeCSS[$this->tbCSSlvl], $tag, $classes, $attr['ID'], $attr['LANG']);
			}`

**Comment by superyetkin** [comment]
Yes, this would be a pull request I suppose.

**Comment by osworx** [comment]
Can make one if the fix is accepted.

**Comment by finwe** [comment]
Closing as stale and missing a code sample.

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.
