### ISSUE TITLE
Last pages ToC entries are not numbered

### ISSUE THREAD

**Issue by fr33ek** [mpdf/mpdf#777]
### I found this bug / would like to have this new functionality
ToC entries at last page are not calculated  after updating from `7.0.3` to `7.1.0`.

There are two cases: 
1. If you use `resetpagenum` inside ToC creation, then you get:
```
ToCName1.........1
ToCName2.........2
ToCNameLast.......
```
2. If you don't use `resetpagenum` inside ToC creation:
```
ToCName1..........
ToCName2..........
ToCNameLast.......
```

Before it was.
```
ToCName1.........1
ToCName2.........2
ToCNameLast.....75
```

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
I an using dockerized version of php7.1-fpm-jessie for now, so: `PHP 7.1.18`, 

### This is a PHP code snippet I use

```php
$mpdf->AddPageByArray([
	'suppress' => 'on'
]);
$mpdf->WriteHTML('<p>TitlePage</p>');
$mpdf->SetHTMLHeader('<p>Page {PAGENO}</p>');
$mpdf->TOCpagebreakByArray([
	'links' => true,
	'resetpagenum' => 3,
	'name' => 'main',
        'suppress' => 'off'
]);
$mpdf->TOC_Entry('1', 1, 'main');
$mpdf->WriteHTML("<h1>chapter 1</h1>");

$mpdf->AddPage();
$mpdf->TOC_Entry('1.1', 2, 'main');
$mpdf->WriteHTML("<h1>chapter 1.1</h1>");

$mpdf->AddPage();
$mpdf->TOC_Entry('2', 1, 'main');
$mpdf->WriteHTML("<h1>chapter 2</h1>");

$mpdf->AddPage();
$mpdf->TOC_Entry('3', 1, 'main');
$mpdf->WriteHTML("<h1>chapter 3</h1>");
```

I am not sure if it was a bug, and now it fixed, or it's a new one :)
The intense of this code is to suppress page numbering only on ToC's pages, but keep on chapter's.
Unfortunately, it removes page numbers from ToC links, but leaves page numbers (that you usually put in footer or header).

**Comment by jakejackson1** [comment]
@fr33ek I haven't been able to replicate the issue using the sample code provided. Please include a more complete code snippet which replicates this issue. Note: the code should be the absolute minimum required to re-produce the issue (I don't need 1000+ lines of HTML to debug).

**Comment by fr33ek** [comment]
@jakejackson1 thanks for your reply, Yes, seems I need to investigate it deeper. We have quite complicated structure so I need to dig into it and create a simple sample to reproduce the bug. We have lot's of exports done in a same manner and all of them hast last page numbers missing, so it seemed like a general bug. I will try to provide more detailed info soon.

**Comment by fr33ek** [comment]
@jakejackson1 i've updated the info with exact reproducible example.

**Comment by jakejackson1** [comment]
@fr33ek thanks. I was able to reproduce and devise a fix https://github.com/mpdf/mpdf/pull/783

**Comment by fr33ek** [comment]
@jakejackson1 thank you for your contribution! Should I close this issue then?

**Comment by finwe** [comment]
@fr33ek Will close upon merging Jake's fix. Thanks to both of you for your contributions.
