### ISSUE TITLE
WriteBarcode() does not support all documented characters

### ISSUE THREAD

**Issue by mariusklocke** [mpdf/mpdf#78]
The function `WriteBarcode()` strips the hyphen character (`-`) although the documentation says it is supported for Code39 and some other types.

If someone can explain to me why this character is removed, i will try to help providing a bugfix.

**Comment by finwe** [comment]
Are you sure you are passing plain hyphen `-` and not a dash `–` or some other similar character? Example file `example37_barcodes.php` renders Code39 with hyphen correctly.

**Comment by finwe** [comment]
Oh I see. Use method `WriteBarcode2()` to output Code39 barcodes.
