### ISSUE TITLE
PHP Notice when using $mpdf->TOCpagebreakByArray

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#781]
### I found this bug / would like to have this new functionality

Undefined PHP variable notice when using `$mpdf->TOCpagebreakByArray()`

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

PHP7.2 with mPDF 7.1.

### This is a PHP code snippet I use

```
<?php
$mpdf = new \Mpdf\Mpdf( [] );
$mpdf->TOCpagebreakByArray( [] );
$mpdf->Output();
```

**Comment by finwe** [comment]
Closed in #780, thanks, Jake!
