### ISSUE TITLE
Invalid argument supplied for foreach() in Mpdf.php line 25328 (при выводе файла собранного путем импорта сторонних pdf)

### ISSUE THREAD

**Issue by marinazima** [mpdf/mpdf#782]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug
я скачиваю файл, который создаю с помощью Mpdf - путем импортирования стронних документов.

ошибка
in /var/www/html/framework/vendor/mpdf/mpdf/src/Mpdf.php
в строке 25328
http://joxi.ru/brRZz59HJQvy8r

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
PHP: 7.1.7
MPDF: v7.1.0

### This is a PHP code snippet I use

<?php 
$this->mpdf->Output(($fileName ?: $this->fileName), \Mpdf\Output\Destination::DOWNLOAD);
?>

### This is a HTML/CSS code snippet I use
нет

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.

And, please, use English here.
