### ISSUE TITLE
Header/footer absolute position in 7.1.0

### ISSUE THREAD

**Issue by jukka-p** [mpdf/mpdf#791]
A template we're using regressed when upgrading to `7.1.0` from `7.0.3` regarding an absolute positioned element in footer. The example I created produces two vastly different renders, where `7.1.0` version seems to be worse off.

```
$mpdf = new Mpdf(['mode' => 'utf-8', 'format' => 'A4']);
$mpdf->WriteHTML('
    <html>
        <head>
            <style>
                @page {
                    header: html_myHeader;
                    footer: html_myFooter;
                    margin-top: 7cm;
                }

                #header-content {
                    background: lightblue;
                }

                #footer-content {
                    background: lightgreen;
                }

                #absolute-element-header {
                    position: absolute;
                    top: 2cm;
                    left: 1cm;
                    background: purple;
                }

                #absolute-element-footer {
                    position: absolute;
                    bottom: 2cm;
                    right: 1cm;
                    background: yellow;
                }

                #absolute-element-body {
                    position: absolute;
                    top: 50%;
                    left: 50%;
                    background: red;
                }
            </style>
        </head>
        <body>
            <htmlpageheader name="myHeader">
                <div id="header-content">' . str_repeat('HEADER DIV ', 60) . '</div>
                <div id="absolute-element-header">ABSOLUTE ELEMENT HEADER</div>
            </htmlpageheader>

            <htmlpagefooter name="myFooter">
                <div>
                    <table id="footer-content">
                        <tr>
                            <td>' . str_repeat('FOOTER TABLE ', 60) . '</td>
                        </tr>
                    </table>
                </div>
                <div id="absolute-element-footer">ABSOLUTE ELEMENT FOOTER</div>
            </htmlpagefooter>

            <div>' . str_repeat('CONTENT ', 180) . '</div>
            <div id="absolute-element-body">ABSOLUTE ELEMENT BODY</div>
        </body>
    </html>'
);
```

In `7.0.3`, the absolute element of header is missing completely:
![image](https://user-images.githubusercontent.com/5990155/41908712-9cb2c31e-794d-11e8-8b81-c04e454336e2.png)

While in `7.1.0`, the header and footer contents are gone, except for header background color:
![image](https://user-images.githubusercontent.com/5990155/41908762-c5a7db9c-794d-11e8-9ef4-b67491e647e5.png)

This change is attributable to https://github.com/mpdf/mpdf/commit/01f9bfef7e22dda596c187b59d470eb9b928284f, though I haven't got a clue on why it changes that much.

**Comment by jakejackson1** [comment]
Absolute positioning of the header/ footer in `7.0.3` is fundamentally broken. For example, if you add another page to the PDF you'll find that along with the header not displaying, the absolute-positioned footer on page 2 onwards won't display either. 

From your example, more work will need to be done to support both absolute and non-absolute positioned content in the header / footers at the same time, but your issue can be easily fixed in `7.1.0` by absolute positioning the non-positioned elements:

```
#absolute-element-footer2 {
	position: fixed;
	bottom: 0;
	left: 0;       
}

<div id="absolute-element-footer2">
	<table id="footer-content">
		<tr>
			<td>' . str_repeat('FOOTER TABLE ', 60) . '</td>
		</tr>
	</table>
</div>         
```

Until support for both positioned and non-positioned types is added to Headers / Footers, I think a note in the documentation would be a good idea.

**Comment by jukka-p** [comment]
I see, I was not aware of how it was broken on multi-pages in `7.0.3`. That is broken indeed, and the absolute positioning functionality becomes consistent in `7.1.0` with multiple pages, even though it then requires some additional conditions. In the example, adding positioning to header content with
```
#header-content {
    position: fixed;
    background: lightblue;
}
```
has the header working correctly on multiple pages instead of just the first.

If I do the same for footer content as
```
#footer-content {
    position: fixed;
    background: lightgreen;
}
```
I now have a `Warning: Division by zero at Mpdf.php:16047`. That's seems to be due to fixed elements being on on top of each other and fixed by adding bottom modifier:

```
#footer-content {
    position: fixed;
    bottom: 0;
    background: lightgreen;
}
```
Result as multiple pages:
![image](https://user-images.githubusercontent.com/5990155/41951976-55f863be-79d6-11e8-976d-fb4abc62ef42.png)
![image](https://user-images.githubusercontent.com/5990155/41951998-6734e49a-79d6-11e8-8d53-95049b78eb22.png)

**Comment by finwe** [comment]
@jukka-p Can you please create a new issue about the Warning you are getting for sake of clarity? I am going to close this one as I believe its former topic has been clarified.
