### ISSUE TITLE
Warning when missing default values with TOCpagebreakByArray()

### ISSUE THREAD

**Issue by 1manfactory** [mpdf/mpdf#797]
Hello,

great work on V7. Thank you guys.

I only would like to inform you about some undefined variable warnings when using TOCpagebreakByArray

I know it's not that important. But on development systems I am always logging everything to debug.

> PHP Notice:  Undefined variable: tocfontsize in /var/www/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 25693
> PHP Notice:  Undefined variable: tocindent in /var/www/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 25693
> PHP Notice:  Undefined variable: tocfont in /var/www/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 25693

And because so far this is the only warning I got I thought you would like to take care of it.

**Comment by jakejackson1** [comment]
Thanks, this issue has already been patched https://github.com/mpdf/mpdf/commit/4f8a378bd2626427cde7c815f97812fdc98e8807

**Comment by 1manfactory** [comment]
Oh, wasn't aware of this. Maybe I should update :-)

Sorry

**Comment by jakejackson1** [comment]
@1manfactory that's alright. The issue has only been recently fixed and isn't included in a tagged release just yet.
