### ISSUE TITLE
Empty page after tocpagebreak because of doubled page break

### ISSUE THREAD

**Issue by 1manfactory** [mpdf/mpdf#798]
Hello,

I am using _page-break-before: always;_ for **H1** style definition. And it works perfectly (thanks again for your excelent code, guys)

But it also forces a somewhat nasty behaviour when using _tocpagebreak_ right before the first H1-Header. because of the two breaks an empty page is inserted.

Is there a way to use _tocpagebreak_ without inserting a pagebreak afterwards?

This is my code

`<tocpagebreak paging="on" links="on" toc-odd-footer-name="html_tocHTMLFooter" toc-odd-footer-value="on" toc-preHTML="'.htmlentities('<p class="TOC_Heading">Inhaltsverzeichnis</p>').'" toc-bookmarkText="Inhaltsverzeichnis" toc-resetpagenum="1" toc-pagenumstyle="I" resetpagenum="1" pagenumstyle="1" odd-footer-name="html_myHTMLFooter" odd-footer-value="on" outdent="2em" />`

```
This is my definition
<htmlpagefooter name="myHTMLFooter">
<table width="100%" class="footer"><tr>
<td width="33%" class="footer"></td>
<td width="33%" align="center" class="footer"><p>{PAGENO}</p></td>
<td width="33%" style="text-align: right;" class="footer"></td>
</tr></table>
</htmlpagefooter>
```

**Comment by 1manfactory** [comment]
For those of you interested I found a not so smart workaround. I check for the very first **h1** following the TOC and set the style to _"page-break-before: avoid;"_

Something like this

```
$content=preg_replace('|<h1|ui', '<h1 style="page-break-before: avoid;"', $content, 1);
$mpdf->WriteHTML( $content );
```

**Comment by jakejackson1** [comment]
@1manfactory there's not enough code to reproduce this issue. Your code doesn't show how mPDF is initialised and configured, nor a short sample of the exact HTML your are using.

**Comment by Klap-in** [comment]
For examples, you could have a look at https://github.com/mpdf/mpdf/tree/development/tests/Issues

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen, if still applicable on current version.
