### ISSUE TITLE
Rotation not working for mpdf version 7

### ISSUE THREAD

**Issue by Rituparna007** [mpdf/mpdf#808]
my script is:

<?php

require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();

$html = '<html>
   <style>
   div.a {
    width: 300px;
    height: 100px;
    background-color: lightblue;  
	position: fixed;
    transform: rotate(90deg);
}</style><div class="a">Hello World!</div></html>';

$mpdf->WriteHTML($html);
$mpdf->Output();

?>
here the rotation of that div not working.

**Comment by finwe** [comment]
Transform is not supported on a element. https://mpdf.github.io/css-stylesheets/supported-css.html
