### ISSUE TITLE
Method mPDF::SetProtection() is gone forever? Or is a bug?

### ISSUE THREAD

**Issue by Gudabu** [mpdf/mpdf#81]
I can't find the method mPDF::SetProtection() in version 6.0... Any idea?

**Comment by blueliquiddesigns** [comment]
That method is apart of `mpdf.php` on line 28355 of the master branch. You can't search for the method in GitHub because the file is too large but if you [look at the raw source](https://raw.githubusercontent.com/mpdf/mpdf/master/mpdf.php) you will see it is still there.

**Comment by Gudabu** [comment]
You're right, but my question is about version 6. [Here is the raw source](https://raw.githubusercontent.com/mpdf/mpdf/v6.0.0/mpdf.php)

**Comment by blueliquiddesigns** [comment]
A quick search shows the method is still apart of the v6.0.0 tagged version of `mpdf.php` on line 28355.

**Comment by Gudabu** [comment]
You're right, I don't know why few minutes ago I wasn't able find it! My bad! sorry and thanks for you time!
