### ISSUE TITLE
Update changelog for 7.1.x

### ISSUE THREAD

**Issue by ShinJii89** [mpdf/mpdf#815]
What's difference between 7.0.x and 7.1.x ? Why you're not updating your changelog? 
Because of that I don't know if I can update from 7.0.x to 7.1.x without break anything.

**Comment by finwe** [comment]
mPDF mostly follows semver, so you should be safe until major version changes. I've added the most significant changes to the changelog, more information can be found in [7.1.0 release announcement][1] and in commit history (best viewed in console or some desktop tool do show the commit tree).

[1]: https://github.com/mpdf/mpdf/releases/tag/v7.1.0
