### ISSUE TITLE
How to remove the margins around the content on 7.1.1

### ISSUE THREAD

**Issue by maofree** [mpdf/mpdf#817]
Hi
how is possible to set the margins on the new 7 version? I want to remove the marigns of the pages, setting on 0. In the version 6 I set them into new mPDF( but now I don't know how is possible

on the 6 I used

$pdf = new \Mpdf\Mpdf('utf-8', 'A4'.($orientation == 'L' ? '-L' : ''), '', '', $margin_left, $margin_right, $margin_top, $margin_bottom, 0, 0);

now?

thanks

I use php 7.0 and mpdf 7.1.1

**Comment by maofree** [comment]
I show you the differences between the versions 6 and 7
the first image is on the 7 and the second with 6
it is necessary only to remove the margins around the page

![1](https://user-images.githubusercontent.com/653230/43048276-234255ba-8de5-11e8-9b5b-4be4a2e481cc.png)
![2](https://user-images.githubusercontent.com/653230/43048277-23661680-8de5-11e8-82ef-9d35dadf333a.png)

**Comment by maofree** [comment]
I set in the css code

            @page {
                margin: 0mm;
                margin-header: 0mm;
                margin-footer: 0mm;
            }

but nothing is changed

**Comment by maofree** [comment]
the margin is not possible to remove, from ConfigParameters.php and usign this code

        $pdf = new \Mpdf\Mpdf([
            'mode' => 'utf-8',
            'format' => [210, 297],
            'orientation' => $orientation,
            'setAutoTopMargin' => 'stretch',
            'autoMarginPadding' => 0,
            'bleedMargin' => 0,
            'crossMarkMargin' => 0,
            'cropMarkMargin' => 0,
            'nonPrintMargin' => 0,
            'margBuffer' => 0,
            'collapseBlockMargins' => false,
        ]);

**Comment by maofree** [comment]
I need to remove these spaces (on the version 6 was simple)

![1](https://user-images.githubusercontent.com/653230/43048847-a6547c72-8dee-11e8-8e48-1109184b7b00.png)

**Comment by maofree** [comment]
set on 0 each margin variables of ConfigVariables.php but nothing change

![1](https://user-images.githubusercontent.com/653230/43048760-1a97b268-8ded-11e8-9138-ddeefe76fcc4.png)

**Comment by maofree** [comment]
Hi
problem fixed looking inside mpdf.php to the initConstructorParams method

        $pdf = new \Mpdf\Mpdf([
            'mode' => 'utf-8',
            'format' => 'A4'.($orientation == 'L' ? '-L' : ''),
            'orientation' => $orientation,
	    'margin_left' => $margin_left,
	    'margin_right' => $margin_right,
	    'margin_top' => $margin_top,
	    'margin_bottom' => $margin_bottom,
	    'margin_header' => 0,
	    'margin_footer' => 0,
        ]);

I suggest you to add this configuration in your documentation page

thanks
bye

**Comment by Klap-in** [comment]
These margins are documented at the constructor page:
https://mpdf.github.io/reference/mpdf-functions/construct.html
and these are therefore not part of the variable overview https://mpdf.github.io/reference/mpdf-variables/overview.html ....

(And some general info, but not very specific:
https://mpdf.github.io/headers-footers/headers-top-margins.html)

**Comment by maofree** [comment]
Hi
thanks
I skipped reading this
https://mpdf.github.io/reference/mpdf-functions/construct.html

however now it is ok
