### ISSUE TITLE
Not show satellite view of Google static maps

### ISSUE THREAD

**Issue by vicsanjinez** [mpdf/mpdf#818]
I found this bug when I use https://developers.google.com/maps/documentation/maps-static/dev-guide for insert maps on pdf generated with mpdf library,

With roadmap view I use this code

```
<img width="200" height="200"src="https://maps.googleapis.com/maps/api/staticmap?center=-19.0365720000,-65.2531240000&zoom=16&size=200x200&maptype=roadmap&scale=2
&language=spanish&markers=color:red%7Clabel:Cliente%7C-19.0365720000,-65.2531240000&key=my-key">
```

but, I need satellite view, searched on documentation, and found the parameter to change

maptype=satellite

```
<img width="200" height="200"src="https://maps.googleapis.com/maps/api/staticmap?center=-19.0365720000,-65.2531240000&zoom=16&size=200x200&maptype=satellite&scale=2&language=spanish&markers=color:red%7Clabel:Cliente%7C-19.0365720000,-65.2531240000&key=my-key">
```
But the map still on roadmap view, I think is an bug of mpdf library, because when I use the code on a html file work fine,

Some idea about the error?

**Comment by finwe** [comment]
Not a bug of the library. I was succesfully able to display a satellite map in the pdf (when I used a correct API key and added a space before the `src` parameter).

![shot_180724_101132](https://user-images.githubusercontent.com/195675/43125333-f9b89754-8f29-11e8-812a-ebf6c522d935.png)

**Comment by vicsanjinez** [comment]
@finwe thanks for the example! I was using a non oficial repository of mpdf for yii2 (https://github.com/kartik-v/mpdf) after your answer a review the github of the library I was using, and read a new thing "Use the mpdf/mpdf repo instead", so, I downloaded the oficial library and test my code and is ok! thanks for the help!
