### ISSUE TITLE
mPDF PDF/A1-b add image -> mixed colour space

### ISSUE THREAD

**Issue by FrazeColder** [mpdf/mpdf#821]
Hey Guys,

I am using mPDF to create a PDF which has the PDF/A1-b format. This is required cause I want to archive those PDF files!

To get the PDF/A1-b format I am simply using: `$mpdf->PDFA = true;` according to the [documentation by mPDF][1].

However, I want to add a image. Either an jpg or png image. The problem I get whit the format is this error message by mPDF:

> PDFA1-b does not permit Images using mixed colour space

I have already tried to embed my image with html:

    $mpdf->WriteHTML("<img src='../img/myimage.jpg'>");
and also like with the [Image() function provided by mPDF][2]:

    $mpdf->Image('../img/myimage.jpg'), 0, 0, 156, 53, 'jpg', '', true, false);

However, both versions are throwing the error above.. How can I fix this error and embed my image? Google is not giving me a answer...

Kind regards and Thank You!

  [1]: https://mpdf.github.io/what-else-can-i-do/pdf-a1-b-compliance.html
  [2]: https://mpdf.github.io/reference/mpdf-functions/image.html

**Comment by FrazeColder** [comment]
Hey Thanks for the answer. I just found the problem. I have to convert the image here:
https://www.cmyk2rgb.com/

**Comment by jakejackson1** [comment]
[As per the same documentation](https://mpdf.github.io/what-else-can-i-do/pdf-a1-b-compliance.html), you can configure `$mpdf->PDFAauto = true; ` to fix many issues like this automatically. The docs mention converting CMYK to RGB, but I was pretty sure it goes the other way to.
