### ISSUE TITLE
Can't install using composer (paragonie/random_compat)

### ISSUE THREAD

**Issue by acevezwing** [mpdf/mpdf#827]
I can't install mpdf using composer. Something to do with paragonie/random_compat. Here is the installation log:

Using version ^7.1 for mpdf/mpdf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install mpdf/mpdf v7.1.2
    - Conclusion: don't install mpdf/mpdf v7.1.1
    - Conclusion: remove paragonie/random_compat v9.99.99
    - Installation request for mpdf/mpdf ^7.1 -> satisfiable by mpdf/mpdf[v7.1.0, v7.1.1, v7.1.2].
    - Conclusion: don't install paragonie/random_compat v9.99.99
    - mpdf/mpdf v7.1.0 requires paragonie/random_compat ^1.4|^2.0 -> satisfiable by paragonie/random_compat[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.x-dev, v2.0.0, v2.0.1, v2.0.10, v2.0.11
, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8, v2.0.9].
    - Can only install one of: paragonie/random_compat[v1.4.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.4.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.4.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.4.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v1.x-dev, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.0, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.1, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.10, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.11, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.12, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.13, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.14, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.15, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.16, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.17, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.2, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.3, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.4, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.5, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.6, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.7, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.8, v9.99.99].
    - Can only install one of: paragonie/random_compat[v2.0.9, v9.99.99].
    - Installation request for paragonie/random_compat (locked at v9.99.99) -> sat

Installation failed, reverting ./composer.json to its original content.

**Comment by jakejackson1** [comment]
Seems like we'll need to adjust our composer.json version restrictions for paragonie/random_compat as per https://github.com/paragonie/random_compat#version-99999

**Comment by finwe** [comment]
Should be fixed in v7.1.3
