### ISSUE TITLE
Problem to change the color of anotation 

### ISSUE THREAD

**Issue by EnguerranMeens** [mpdf/mpdf#835]
Hello,

I'm having a problem with changing the annotation color, here's what I use:

`<annotation   content=\"Paris 2h \" icon=\"Key\" title=\"\" color=\"red\" pupup=\"0\">Test</annotation>`

Screen  : http://prntscr.com/ki35co

But it's didn't work the color remains in Yellow can you help me ? Thanks  !

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially your environment details and a reusable HTML/PHP code example.

Specifying red color works for me with the last release (7.1.4) in the [annotations example file](https://github.com/mpdf/mpdf-examples/blob/development/example36_annotations_and_attached_files.php)

![shot_180813_182642](https://user-images.githubusercontent.com/195675/44044622-726780d2-9f26-11e8-8288-5e03c212ac9d.png)

**Comment by EnguerranMeens** [comment]
This is my code : 

`

require_once __DIR__ . '/vendor/autoload.php';

use Mpdf;
use Mpdf\Color;

$mpdf = new Mpdf\Mpdf(['mode' => 'utf-8', 'format' => 'A4-L', 'allowAnnotationFiles' => true]);



$first = 0;


$html = "<h3>
	Heading 3
	<annotation content=\"This is an annotation\"
		subject=\"My Subject\" icon=\"Comment\" color=\"#FE88EF\" author=\"Ian Back\" />
</h3>
<h4>Heading 4</h4>
<p>P: Nulla felis erat, imperdiet eu, ullamcorper non, nonummy quis, elit. Suspendisse potenti. Ut a eros at ligula
vehicula pretium. Maecenas feugiat pede vel risus. Nulla et lectus. <i>Fusce</i>
<annotation content=\"Fusce is a funny word!\" subject=\"Idle Comments\" color=\"red\" icon=\"Note\" author=\"Ian Back\" pos-x=\"195\" />
eleifend neque sit amet erat. Integer consectetuer nulla non orci. Morbi feugiat pulvinar dolor. Cras odio.
Donec mattis, nisi id euismod auctor, neque metus pellentesque risus, at <span title=\"This annotation was automatically
defined from the title attribute of a span element\">eleifend</span> lacus sapien et risus. Phasellus metus. Phasellus
feugiat, lectus ac aliquam molestie, leo lacus tincidunt turpis, vel aliquam quam odio et sapien.
Mauris ante pede, auctor ac, suscipit quis, malesuada</p>
<p> Note that since mPDF v7.0.0, embedded annotation files must be explicitly allowed by setting
<code>allowAnnotationFiles</code> configuration key to true. Otherwise, the file attribute of <code>annotation</code> tag
will be ignored.
<annotation file=\"circle.png\" content=\"This is a file attachment (embedded file)
Double-click to open attached file
Right-click to save file on your computer\" icon=\"Graph\" title=\"Attached File: assets/tiger.jpg\" pos-x=\"195\" />
<p>".$monmois."</p><table  cellspacing='0' style='width:100%;position:absolute;'>";

$mpdf->annotMargin = false;
$mpdf->title2annots = true;

$mpdf->WriteHTML($html);

$mpdf->AddPage();




$mpdf->Output();`

And I still have the yellow color ? 

Can you help me ? :\

**Comment by EnguerranMeens** [comment]
Sorry , i use php7.2.1 and mPDF 7.1.4 too . And i use chrome to view the PDF . I'm on MAC OS

**Comment by finwe** [comment]
I guess the PDF.js viewer (or whatever Chrome uses) does not support alternate colors for annotations. To display colors, use fully fledged PDF viewer.

**Comment by finwe** [comment]
Actually pdfium. PDF.js in Firefox supports annotation detail background, not icon color.

![shot_180814_102935](https://user-images.githubusercontent.com/195675/44080704-227f7c46-9fad-11e8-83c0-30d8fd873617.png)

Anyway, issue closed.

**Comment by EnguerranMeens** [comment]
Ok it's work when i download the pdf and open it with adobe
