### ISSUE TITLE
Textarea Size and Document Scaling

### ISSUE THREAD

**Issue by mauricekindermann** [mpdf/mpdf#837]
Here's a textarea font-size related quirk I've found. It seems the second version is more intuitive for end users, as that lets you change font sizes without scaling the document. 

**Suggested Documentation Update (Styles > Textarea):**
_width % + height % recommended. rows="" + cols="" works but can scale the document around font size_

1. Using rows="" + cols="" for Height + Width causes fonts to scale with the document, so the text inside the textareas remains somewhat the same, and the document expands or shrinks around it. For example: 

`<textarea rows='6' cols='15' style='font-size:30px;'></textarea>`

![2018-08-14_0941](https://user-images.githubusercontent.com/3828998/44064004-5847cc72-9fa6-11e8-998f-bd664ac01999.png)

2. However, using Width % + Height % stops this from happening, and gives you control over the actual font size within the textarea, for example: 

`<textarea style='font-size:30px; width: 14.28%; height: 8%;'>`

![2018-08-14_0944](https://user-images.githubusercontent.com/3828998/44064109-d06d2e5e-9fa6-11e8-8077-df746fef08c1.png)

**Comment by finwe** [comment]
How does your HTML look? Are you using tables? Because support for enhanced CSS styling inside tables is quite low in mPDF.

**Comment by mauricekindermann** [comment]
@finwe Yup I'm using complex tables and lots of CSS styling. I've had to do lots of trial and error to get it looking the way it is. 

I'll close this ticket as it's not a bug or feature, but others might benefit from the example screenshots if they run into the same problem in the future.
