### ISSUE TITLE
myclabs/deep-copy: support new version

### ISSUE THREAD

**Issue by Farshadi73** [mpdf/mpdf#842]
Hi, I try to install your awesome bundle but get face of this error 
```
 Problem 1
    - Can only install one of: myclabs/deep-copy[1.x-dev, 2.x-dev].
    - Can only install one of: myclabs/deep-copy[2.x-dev, 1.x-dev].
    - Can only install one of: myclabs/deep-copy[1.x-dev, 2.x-dev].
    - mpdf/mpdf dev-master requires myclabs/deep-copy ^1.7 -> satisfiable by myclabs/deep-copy[1.x-dev].
    - Installation request for mpdf/mpdf dev-master -> satisfiable by mpdf/mpdf[dev-master].
    - Installation request for myclabs/deep-copy 2.x-dev -> satisfiable by myclabs/deep-copy[2.x-dev].

```

please add new version of deep-copy to your composer..
tanks

**Comment by jakejackson1** [comment]
The latest tagged release of deep-copy is 1.8.1 and our composer package has `"myclabs/deep-copy": "^1.7"`, which includes versions >=1.7.0 <2.0.0. There's nothing for us to change.

**Comment by finwe** [comment]
Closing this. @Farshadi73 feel free to reopen, when the stable 2.0.0 version of deep-copy is released.
