### ISSUE TITLE
Size of package is too large

### ISSUE THREAD

**Issue by springimport** [mpdf/mpdf#844]
### I would like to have this new functionality
Folder `vendor/mdf` contains 788 objects and takes **103mb**. And the problem in fonts.
I suggest to create a new package like `mpdf/fonts` with all custom fonts and leave one-two default fonts in main package.

### This is mPDF. I am using
mpdf v7.0.

**Comment by finwe** [comment]
See 

https://github.com/mpdf/mpdf/pull/841
https://github.com/mpdf/mpdf/issues/552
