### ISSUE TITLE
Call to an undefined method Mpdf\Mpdf::Error()

### ISSUE THREAD

**Issue by drickferreira** [mpdf/mpdf#845]
I'm migrating my application from PHP 5.6 to 7.1 and using phpstan to check for possible conflicts.
It found in the DirectWrite.php at line 286 the following code:
`$this->mpdf->Error('Please use values unequal to zero for kerning (CircularText)');
`

But the Error method does not exist in the Mpdf class.

**Comment by finwe** [comment]
Thanks for the catch, fixed in development branch.
