### ISSUE TITLE
Notice: Undefined offset: 0 in /var/www/html/traffic-signs/vendor/mpdf/mpdf/src/Mpdf.php on line 4688

### ISSUE THREAD

**Issue by nekromoff** [mpdf/mpdf#850]
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
```
{
    "require": {
        "mpdf/mpdf": "^7.1"
    }
}
```

PHP 7.1.17-0ubuntu0.17.10.1 (built: May  9 2018 17:28:01) ( NTS )

### This is a PHP code snippet I use
```
<?php

$mpdf->WriteCell(70, 100, $distances[0], 0, 0, 'R');
```

### This is a HTML/CSS code snippet I use

```

```

**Comment by finwe** [comment]
Not enough information. How do you instantiate mPDF object? What does the $distances variable contain?

**Comment by nekromoff** [comment]
Sorry, I misread.

```
 $mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8',
            'format'                       => $size,
            'fontDir'                      => array_merge($fontDirs, [
                __DIR__ . '/fonts',
            ]),
            'fontdata'                     => $fontData + [
                'tern' => [
                    'R' => 'Tern-Regular.ttf',
                ],
            ],
            'default_font'                 => 'tern',
        ]);
        $mpdf->SetAutoPageBreak(false);

        $mpdf->SetImportUse();
```

**Comment by finwe** [comment]
Unable to reproduce this with given information. Please, try to create a unit test (see tests/Issues for examples) that produces the notice.

Feel free to reopen the issue then or create a PR with the test file.
