### ISSUE TITLE
Call to undefined function strcode2utf()

### ISSUE THREAD

**Issue by chanhong** [mpdf/mpdf#855]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug / would like to have this new functionality

Call to undefined function strcode2utf()

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

mPDF 7.1.x, php-5.6.32-nts-Win32-VC11-x86, Windows 2016

### This is a PHP code snippet I use

https://mpdf.github.io/reference/mpdf-utilities/strcode2utf.html
```
<?php
$mpdf = new \Mpdf\Mpdf();

$wm = strcode2utf("&#1575;&#1610;&#1604;&#1575;&#1578; &#1601;&#1610;&#1605;&#1575; 
    &#1575;&#1610;&#1604;&#1575;&#1578; &#1601;&#1610;&#1605;&#1575;");
$mpdf->SetWatermarkText($wm);

$mpdf->showWatermark = true;

$mpdf->WriteHTML('Hello World');


```

### This is a HTML/CSS code snippet I use

```
Is strcode2utf a function of mPDF or PHP?

Thanks

```

**Comment by finwe** [comment]
Use \Mpdf\Utils\UtfString::strcode2utf. Fixed in the documentation, thanks for the catch.
