### ISSUE TITLE
Different file sizes per operating system

### ISSUE THREAD

**Issue by odmyikona** [mpdf/mpdf#857]
The exact same code produces different file sizes in MacOS and Ubuntu.

At a high level the workflow is as this:

- A PDF is uploaded by a 3rd party software
- Is converted to 1.4 by ghostscript
- Using mPDF a new PDF is created that some extra pages are added to it.

MacOS
---------
Original File: 29.5MB
Ghostscript File: 15MB
mPDF file: 15.4MB

Ubuntu
---------
Original File: 29.5MB
Ghostscript File: 15MB
mPDF file: 154MB

Both environments use PHP7.1 and mPDF 7.1.1

Some sample code:

```
$command = new GhostscriptConverterCommand();
$filesystem = new Filesystem();
$converter = new GhostscriptConverter($command, $filesystem);
$converter -> convert($productFileToCopy, '1.4');

$mPdf = new \Mpdf\Mpdf( array('dpi' => 300, ));
$mPdf -> SetImportUse();
$pageCount = $mPdf -> SetSourceFile($productFileToCopy);

for ($i = 1; $i <= $pageCount; $i++) {
    $importPage = $mPdf -> ImportPage($i);
    $wh = $mPdf -> getTemplateSize($importPage);
    $orientation = $wh['w'] > $wh['h'] ? 'L' : 'P';

    $mPdf -> AddPageByArray(array(
        'orientation' => $orientation,
        'sheet-size' => array(
                $orientation === 'L' ? $wh['h'] : $wh['w'],
                $orientation === 'L' ? $wh['w'] : $wh['h'],
        ),
        'margin-left' => 0,
        'margin-right' => 0,
        'margin-top' => 0,
        'margin-bottom' => 0,
        'margin-header' => 0,
        'margin-footer' => 0,
    ));

    $mPdf -> UseTemplate($importPage);
}

$mPdf -> SetCompression(TRUE);
$mPdf -> Output($productFileFinal);
```

**Comment by finwe** [comment]
Can you please also provide the input file and the GS command used to convert it?

**Comment by finwe** [comment]
Both result files would be also helpful

**Comment by odmyikona** [comment]
Hello again and sorry for the delay, but we were testing testing several scenarios with the sys admin team.

Finally is not mPDF, but Ghostscript which produces the large files, but due to the nature of the script (we delete the converted file in the production server), we couldn't track the difference.

A slight difference in Ghostscript version (local 9.23, production 9.22) produces 10x bigger files.

Sorry for the trouble!
