### ISSUE TITLE
Merge multiple files. I do not get return.

### ISSUE THREAD

**Issue by hebriels** [mpdf/mpdf#858]
Hi there!
I'm using the latest version MPDF.
This code works. I combine several files.
I do not get return.
If you comment out foreach, then the return comes.
Maybe I'm not uniting correctly?

        list($directorySite, $shell) = explode('app', __DIR__);
        require($directorySite.'/vendor/autoload.php');
        try {
            $mpdf = new Mpdf(['mode' => 'utf-8']);
            $mpdf->SetImportUse();
            $page1 = $mpdf->SetSourceFile('public/scanInvoice/'.$resultJPGtoPDF);
            for ($i=1;$i<=$page1;$i++) {
                $mpdf->AddPage();
                $tplId = $mpdf->ImportPage($i);
                $mpdf->UseTemplate($tplId);
                $mpdf->WriteHTML('');
            }
            foreach ($pathsPDF as $item){
                $page2 = $mpdf->SetSourceFile('public/scanInvoice/'.$item);
                for ($i=1;$i<=$page2;$i++) {
                    $mpdf->AddPage();
                    $tplId = $mpdf->ImportPage($i);
                    $mpdf->UseTemplate($tplId);
                    $mpdf->WriteHTML('');
                }
            }
            $preName = $this->translit('JPEGandPDF');
            $mpdf->Output($direct.DIRECTORY_SEPARATOR.$preName.'.pdf', 'F');
            return $preName.'.pdf';
        } catch (MpdfException $e) {
            return $e->getMessage();
        }

**Comment by Klap-in** [comment]
Please post a complete, but minimal example of your php and html code. Please provide also the (examples of) source pdf files.
This example is not testable for us.
