### ISSUE TITLE
Nested tables broken since v7.1.0

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#860]
Rendering nested tables does not resize containing table correctly. Following screenshot is from [example06 file](https://github.com/mpdf/mpdf-examples/blob/development/example06_tables_nested.php), mPDF versions 7.1.4 and 7.0.3 respectively.

![shot_180903_085520](https://user-images.githubusercontent.com/195675/44971806-391cbb80-af57-11e8-8f2a-ca5cb8544926.png)

![shot_180903_085533](https://user-images.githubusercontent.com/195675/44971808-3a4de880-af57-11e8-94c0-0f7e22bcdd22.png)

Change in supported PHP version doesn't affect this.

@machour This is probably a result of the Tag refactoring, could you please have a look at this?

**Comment by finwe** [comment]
@machour Will you have time to look into this anytime soon? It would be cool to have this fixed for 8.0

**Comment by machour** [comment]
Sorry for the delay @finwe 😓 

Using `git bisect`, I see that 6cb5ddcaed56d0da49dea54d8245b01854f7faab broke nested tables.
Rolling back to 89ea84ff3d1a00001e073472adf9c1149aa0f8d0 brings back the good behavior.

Currently trying to figure out what went bad in that commit. (phew, it wasn't the tag refactoring)

**Comment by finwe** [comment]
Oh my, shame on me. Makes sense, will try to look too. I guess defining some of the array keys may have broken this? ll. 20849 and further on.

**Comment by finwe** [comment]
Yeah, with this code all seems to work OK. line. 19189 on last development branch

```php

					if (isset($c['maxs'])) {
						$c['maxs'] /= $k;
					}

					if (isset($c['w'])) {
						$c['w'] /= $k;
					}

					$c['s'] = isset($c['s']) ? $c['s'] /= $k : 0;

					if (isset($c['h'])) {
						$c['h'] /= $k;
					}

					if (isset($c['absmiw'])) {
						$c['absmiw'] /= $k;
					}

					if (isset($c['nestedmaw'])) {
						$c['nestedmaw'] /= $k;
					}

					if (isset($c['nestedmiw'])) {
						$c['nestedmiw'] /= $k;
					}

					$c['miw'] = isset($c['miw']) ? $c['miw'] /= $k : 0;
					$c['maw'] = isset($c['maw']) ? $c['maw'] /= $k : 0;

					if (isset($c['textbuffer'])) {
						foreach ($c['textbuffer'] as $n => $tb) {
							if (!empty($tb[16])) {
								!isset($c['textbuffer'][$n][16]['T']) || $c['textbuffer'][$n][16]['T']['w'] /= $k;
								!isset($c['textbuffer'][$n][16]['B']) || $c['textbuffer'][$n][16]['B']['w'] /= $k;
								!isset($c['textbuffer'][$n][16]['L']) || $c['textbuffer'][$n][16]['L']['w'] /= $k;
								!isset($c['textbuffer'][$n][16]['R']) || $c['textbuffer'][$n][16]['R']['w'] /= $k;
							}
						}
					}

```

If you haven't begun with fixing, i'll merge the patch myself. Anyway, thanks for the detective work!

**Comment by finwe** [comment]
Oh, I see you are much quicker and more elegant. Thanks!
