### ISSUE TITLE
Hyperlinks in created PDF not clickable in iOS Safari/Chrome PDF preview

### ISSUE THREAD

**Issue by sanderdewijs** [mpdf/mpdf#863]
### I found this bug 
When I create a PDF using Mpdf with hyperlinks, they work on desktop, in Acrobat reader and Android smartphone. But if I open them in Safari iOS or Google Chrome for iOS the links are no longer clickable. When I open the PDF from within What's App, the links do work.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
7.0.3.0

### This is a PHP code snippet I use
```
<?php 
$anchorLink = '<a class="homeshowUrl" style="text-decoration: none;" href="{{Url}}">{{Url}}</a>'
try {
$mpdf = new \Mpdf\Mpdf([
			'tempDir' => BASEDIR . '/tmp/pdf',
			'mode' => 'utf-8',
			'format' => [215.9,302.9],
]);
                 $mpdf->WriteHTML($anchorLink);
		$mpdf->Output($pdfSheetDir . $pdfName, \Mpdf\Output\Destination::FILE);
	} catch (\Mpdf\MpdfException $e) {
		http_response_code(500);
		echo $e->getMessage();
		die;

	}
```

### This is a HTML/CSS code snippet I use

```

```

**Comment by bradenrayhorn** [comment]
@sanderdewijs I'm experience this same issue. Did you find a solution or workaround?

**Comment by sanderdewijs** [comment]
@bradenrayhorn In my case it was an issue where the url was missing http:// or https:// . Perhaps this also applies to your usecase? For example the code of href="{{Url}}" produced href="www.example.com" while the correct html should be href="http://www.example.com"

**Comment by bradenrayhorn** [comment]
@sanderdewijs Sadly that was not it, thanks for the reply though!

**Comment by sanderdewijs** [comment]
What does your HTML look like before it's processed by MPDF?

**Comment by bradenrayhorn** [comment]
Here is what I ended up doing. This worked in my situation because this link was for a footer that would be on every page, but if the link was placed in an unknown place on the page this would not work.

```php
$mpdf->Link(PdfHelper::LINK_X, PdfHelper::LINK_Y + ($mpdf->CurOrientation == 'P' ? PdfHelper::LINK_Y_SHIFT : 0), PdfHelper::LINK_WIDTH, PdfHelper::LINK_HEIGHT, PdfHelper::LINK_PATH);
```

`PdfHelper::LINK_Y_SHIFT` exists to fix a bug that seems to exist in mPDF where it would not account for page orientation when calculating the position of links.

**Comment by mprose7** [comment]
try url_encode,
safary won't oppen url with spaces, or čćžš..
