### ISSUE TITLE
Call to undefined function Mpdf\random_int()

### ISSUE THREAD

**Issue by janstieler** [mpdf/mpdf#864]
Hi,
I updated a website from me to the last mpdf composerversion.
But now I got the error 
```
Whoops\Exception\ErrorException thrown with message "Call to undefined function Mpdf\random_int()"

Stacktrace:
#0 Whoops\Exception\ErrorException in /homepages/17/d39311005/htdocs/ape2019/site/plugins/mpdf/vendor/mpdf/mpdf/src/Mpdf.php:29289
```
and it says it comes from _…/plugins/mpdf/vendor/mpdf/mpdf/src/Mpdf.php in Line 29286
```        preg_match_all("/(<svg.*?<\/svg>)/si", $html, $svgi);
        if (count($svgi[0])) {
            for ($i = 0; $i < count($svgi[0]); $i++) {
                $file = $this->cache->write('/_tempSVG' . uniqid(random_int(1, 100000), true) . '_' . $i . '.svg', $svgi[0][$i]);
                $html = str_replace($svgi[0][$i], '<img src="' . $file . '" />', $html);
            }
        }
```

at version 6 everything worked fine on this site.
Have someone any idea how I can solve this problem?

Cheers

**Comment by MatthiasKuehneEllerhold** [comment]
Upgrade to PHP 7, `random_int()` is PHP7 only: see http://php.net/manual/de/function.random-int.php

**Comment by mehra-sandeep** [comment]
Upgrade to PHP 7 or change random_int() to with rand() function.

**Comment by finwe** [comment]
update your composer dependencies, paragonie/random_compat library provides PHP5 polyfill.

**Comment by janstieler** [comment]
Hi,
Thanks to all. It was the php 5.6 version. I thought i have activated 7.2 for the whole server but a subdomain was set on the old version. I didn't think anything of the php version :).

**Comment by DevChrisDev** [comment]
hello guys? may i ask how to update composer dependencies? I have the same problem i didnt know how to fix it.
