### ISSUE TITLE
Too long loading sometimes runtime error on simple output.

### ISSUE THREAD

**Issue by DevChrisDev** [mpdf/mpdf#869]
```
<?php 
require_once 'vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('<h1>Hello world!</h1>');
$mpdf->Output();

?>
```

**Comment by Klap-in** [comment]
Sorry, this looks so far more like troubleshooting. Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting. 

(For your post at stackoverflow, please add also more info about your setup (OS, versions of software, etc). With current description nobody could replicate your situation.)
