### ISSUE TITLE
setasign/fpdi: 1.6.* not compatible with PHP 7.2

### ISSUE THREAD

**Issue by azbatuk** [mpdf/mpdf#871]
One of mPDF's dependencies, "setasign/fpdi": "1.6.*", is using a PHP function, "each()", that has been deprecated from PHP 7.2. The latest version of fpdi is 2.1.0. Would it be possible to use the latest "setasign/fpdi" by simply replacing the version number in the composer.json with "2.1" ? If not, what other solution may we have ?

I am using mPDF 7.1.5 and PHP 7.2 running on Ubuntu 18.04.

Thanks

**Comment by finwe** [comment]
There already is a feature request for fpdi 2.x support. AFAIK major versions of fpdi are not compatible, so direct replacement is not possible.

Can you please share a simple code example demonstrating this behaviour on PHP 7.2?

**Comment by JanSlabon** [comment]
2.x support is still on our list and this issue gives it more priority. I guess we'll do this within the next 2-3 weeks (due to holidays over here).

**Comment by do-while** [comment]
+1

**Comment by finwe** [comment]
Closing in favor of #578
