### ISSUE TITLE
 undefined $odd and $even variables

### ISSUE THREAD

**Issue by EudesKeyboard** [mpdf/mpdf#872]
PHP 7.1 and mpdf 7.1.5
I am using mPdf on yii2 Framework with katik-v/mpdf.

Mpdf.php (line: 14513,14514)

I fixed the BUG with isset check.

`if (isset($odd)) {
	$oddhtml = $this->_createHTMLheaderFooter($odd, 'H');
}
if (isset($even)) {
    $evenhtml = $this->_createHTMLheaderFooter($even, 'H');
 }`

**Comment by finwe** [comment]
reference: https://github.com/mpdf/mpdf/pull/873

commented on the pull request.
