### ISSUE TITLE
page-break before after and inside not always respecting

### ISSUE THREAD

**Issue by adsherpa** [mpdf/mpdf#88]
Hi,
I am hoping someone can reply to this or start commenting on this with your idea for solution.
Problem that I am facing is that I am trying to generate multi page document that contains combination of images text, and block header (not just page header)
For example:
I may have page that contents several blocks of text each are it's on item and has sub items such as:

```
 block1 header (line of text)
text content (paragraphs)
images (2 or more but 2 images per row)
attachments (files)

 block2 header (line of text)
text content (paragraphs)
images (2 or more but 2 images per row)
attachments (files)
```

and so on.

What i am trying to do is that if the whole block 2 doesn't fit on the current page along with block1 I would like to move the entire block2 to new page.

And if there is a case where first page can take block1, block2 and half of block3 for example, I want to move block3 and it's internal content to next page.

So far I am not able to get that to the pdf when the final pdf is generated. I am however able to preview in html print view and they look exactly how I have setup in the html with all possible auto page break css3 tags.

Question is are all pagebreak supported in mpdf version 6 or later? Is there a way to do look ahead and check to see where in the page line we are when we want to detected the end of page?

Any feedback from core team would be appreciated. Also if Ian N Back can respond to me I would like to get in touch to see if we can resolve this.

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen with additional information, if still applicable on current version.
