### ISSUE TITLE
DIV in table not work

### ISSUE THREAD

**Issue by airthomas** [mpdf/mpdf#882]
### I found this bug / would like to have this new functionality
below HTML code not work during generate PDF.

```
<div style="display:table;width:80%;border:1px solid #000;" >
<div style="display:table-row-group;">
<div style="display:table-row;">
<div style="display:table-cell;border:1px solid #999999;">1</div>
<div style="display:table-cell;border:1px solid #999999;">b</div>
</div>
<div style="display:table-row;">
<div style="display:table-cell;border:1px solid #999999;">2</div>
<div style="display:table-cell;border:1px solid #999999;">d</div>
</div>
</div>
</div>
```

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF: 6.0, PHP: 5.6

**Comment by finwe** [comment]
Not supported.

https://mpdf.github.io/tables/tables.html
https://mpdf.github.io/css-stylesheets/supported-css.html

**Comment by airthomas** [comment]
Sorry, want to know is mPDF7 support it? many thanks.

**Comment by finwe** [comment]
No.
