### ISSUE TITLE
Watermark only shown on last page

### ISSUE THREAD

**Issue by Adcaelo** [mpdf/mpdf#903]
### I found this bug

Watermark (image or text) are only shown on the **last** page.

Sample PDF rendered : [sample.pdf](https://github.com/mpdf/mpdf/files/2556854/sample.pdf)

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

PHP 7.1.23-4+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov  4 2018 05:11:33) ( NTS )

mpdf/mpdf => version: v7.1.6

Framework : laravel v5.6.39

### This is a PHP code snippet I use

```
<?php

    $mpdf = new \Mpdf\Mpdf();

    $html = "<h1>Some lipsum stuff</h1>";
    $html .= str_repeat("<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>", 35);
    $mpdf->writeHtml($html);

    $mpdf->SetWatermarkText("DRAFT", 0.1);
    $mpdf->showWatermarkText = true;

    $mpdf->Output();
```

**Comment by ssieb** [comment]
Move the SetWatermarkText call before the writeHtml.

**Comment by Adcaelo** [comment]
Oh god ! so simple !
It's not obivous from the documentation even if it's always set before write HTML.

Maybe a small reminder on it could save some trouble.

Closing the issue, thanks !
