### ISSUE TITLE
Error detected. PDF file generation aborted: fopen(/uploads/2016/05/files/logo.jpg): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by attybean** [mpdf/mpdf#904]
https://github.com/mpdf/mpdf/blob/956081616fb3857f5b158a5dd9fb97f8bf0a1e46/src/Image/ImageProcessor.php#L215

PHP 7.0.31 and PHP 7.2.11
Yii 2.0.16 and Yii 2.0.15.3
MPDF mPDF 7.1.x

$orig_srcpath =  "/uploads/2016/05/files/logo.jpg"
$this->mpdf->basepathIsLocal = true (boolean)
getcwd() = "C:\myProject\frontend\web" 

url is localhost:9000/mycontroller/myaction (windows)
I tried the same thing on:
mydomain/mycontroller/myaction (linux)
same result

I am using mpdf through kartik-v/mpdf.
If I turn off debug it works, otherwise it always stops with the above error message.

The file exists and is in the right directory on both the development and server environment. When I type it into the url I can see the logo. 

But :
$this->SetBasePath(''); on line 1519 in Mpdf.php returns basepathIsLocal as true, which forces the line tagged in this issue(L215) to use $org_srcpath which is the url path not the localpath

When I change:  $check = @fopen($orig_srcpath, 'rb') (line215)
to  $check = @fopen(getcwd().$orig_srcpath, 'rb')
and
$data = file_get_contents($file); (line 220?)
to
$data = file_get_contents(getcwd().$orig_srcpath);

The code continues without error, but I do not understand the underlying problem. And do not think these fixes actually address the problem.

**Comment by finwe** [comment]
This is an expected behaviour. When basepathIsLocal is true, the path beginning with is treated as an absolute path - therefore i recommend you to use the absolute filesystem path directly in your HTML or use a path relative to your local basePath.
