### ISSUE TITLE
Critical issue IMG sizing inside TD (table cell)

### ISSUE THREAD

**Issue by mzvarik** [mpdf/mpdf#914]
**This is the content:**
`<table width="100%">`
`<tbody>`
`<tr>`
`<td width="50%"><img src="whatever.jpg" alt="" style="width:100%"></td>`
`<td width="50%">xxxxx</td>`
`</tr>`
`</tbody>`
`</table>`

This will fail with error: **"Word is too long to fit in table -"**
If you change image size to 50% it also fails.
If you change to 49% it works, but the image is half the table, not half the table-cell.

You can turn off the table errors and leave code as I mentioned above and it works, BUT the text inside table is minified (like 2 times smaller) and it doesn't matter if you "autosize=1" or set shrink_tables_to_fit=0 (both are ignored).

I don't see way around this, please make this work.

**Comment by finwe** [comment]
Closing, this is somehow an expected behaviour and will not change (table text will always be resized under certain conditions)
