### ISSUE TITLE
error_reporting corruption

### ISSUE THREAD

**Issue by rafis** [mpdf/mpdf#92]
Is it possible to remove error_reporting() corruption at:
https://github.com/mpdf/mpdf/blob/932177f87ae7b1fb0c8cd7d4161ef090f947f8a2/mpdf.php#L81-L82
Instead move those changes to error_reporting() to specific untested positions:

    // Save original error repoting level and disable notices
    $errorlevel = error_reporting();
    error_reporting($errorlevel & ~E_NOTICE);
    // Here goes bad code, presumably outputing pdf code...
    // ...
    // Restore original error_reporting
    error_reporting($errorlevel);

Also why library in single big file and only single class. Isn'it it better to do OOP+SOLID?

**Comment by finwe** [comment]
Of course that OOP+SOLID is better, but the library is old and changes have to be made a piece by piece. All these changes along with [removing other side effects from mpdf.php file](https://github.com/mpdf/mpdf/issues/32) are planned for 7.0 release (which does not have a roadplan yet).

**Comment by finwe** [comment]
Closing this as error_reporting was removed in development branch.
