### ISSUE TITLE
why i can not use CSS counter-increment:function at Mpdf?

### ISSUE THREAD

**Issue by myou0912** [mpdf/mpdf#920]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### This is a PHP code snippet I use

```
<?php


```

### This is a HTML/CSS code snippet I use

```

```

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.
