### ISSUE TITLE
Warning: unlink(C:\Windows\Temp\adobegc.log): Resource temporarily unavailable in vendor\mpdf\mpdf\src\Cache.php on line 97

### ISSUE THREAD

**Issue by mesaglam** [mpdf/mpdf#923]
```
public function clearOld()
	{
		$iterator = new DirectoryIterator($this->basePath);

		/** @var \DirectoryIterator $item */
		foreach ($iterator as $item) {
			if (!$item->isDot()
					&& $item->isFile()
					&& !$this->isDotFile($item)
					&& $this->isOld($item)) {				
						unlink($item->getPathname());
			}
		}
	}
```

I've changed this function by simply added "@" sign before unlink. 
`@unlink($item->getPathname());`
That solved the warning..

Thanks for all...

Php 7.2.4
Windows 10 x64
mpdf 7.0

**Comment by finwe** [comment]
Do not set your temp directory (directly) to the system temp dir. Use a dedicated directory (at least a subdirectory in the system temp dir) for mPDF to which you have a full access.

**Comment by aszlaga** [comment]
@mesaglem Better idea is use "@" in a final code - not in core method. So, like example try to do something like this:
`$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter( $spreadsheet, 'Mpdf' );
@$writer->save( 'php://output' );`
works4me ;]
