### ISSUE TITLE
Files in mpdf/patterns/* detected as malware by http://gotmls.net

### ISSUE THREAD

**Issue by baselbers** [mpdf/mpdf#925]
https://wordpress.org/support/topic/sos-malware/
Using mpdf 6.1
I know these files cannot do any harm, but users are thinking it is harmful so I would like to know if these files are required and how to disable them. Or even better, give me a proper solution.

**Comment by finwe** [comment]
File a false positive with gotmls.net. Not an issue of mPDF. These files are needed for hyphenation, so when hyphenation is not used, it should be safe to delete them.
