### ISSUE TITLE
Error after updating from 7.1.6 to 7.1.7

### ISSUE THREAD

**Issue by RafaelLinux** [mpdf/mpdf#926]
I just update mpd/mpd from 7.1.6 to 7.1.7 to avoid an SVG issue, but now I get other error:

`Fatal error: Uncaught exception 'Mpdf\MpdfException' with message 'Temporary files directory "/var/www/mpdf/vendor/mpdf/mpdf/src/Config/../../tmp" is not writable' in /var/www/mpdf/vendor/mpdf/mpdf/src/Cache.php:17 Stack trace: #0 /var/www/mpdf/vendor/mpdf/mpdf/src/ServiceFactory.php(60): Mpdf\Cache->__construct('/var/www/mpdf/v...') #1 /var/www/mpdf/vendor/mpdf/mpdf/src/Mpdf.php(1044): Mpdf\ServiceFactory->getServices(Object(Mpdf\Mpdf), Object(Psr\Log\NullLogger), Array, 0, Object(Mpdf\Language\LanguageToFont), Object(Mpdf\Language\ScriptToLanguage), NULL, NULL, NULL, NULL) #2 /var/www/mpdf/boletin_completo.php(33): Mpdf\Mpdf->__construct(Array) #3 {main} thrown in /var/www/mpdf/vendor/mpdf/mpdf/src/Cache.php on line 17`

Please, should I change something after updating?

**Comment by finwe** [comment]
Set a custom temporaray directory over which you have control.

https://mpdf.github.io/installation-setup/folders-for-temporary-files.html

**Comment by RafaelLinux** [comment]
Perfect. Despite I tried changing temp dir to "/tmp" folder, it doesn't worked, but it was a permissions problem. It's working now, thank you.

**Comment by lucasantoniooficial** [comment]
Error persists in PHP 7.4
