### ISSUE TITLE
problems displaying numbered as lower-alpha ol>li elements inside a table

### ISSUE THREAD

**Issue by xavi-c** [mpdf/mpdf#93]
Hi,

I have some problems rendering correctly numbers of list elements in a ordered list inside a table. No matter I specify a 'type="a"' or 'list-style-type: lower-alpha', the elements are always rendered as numbers. This only happens inside a table, out of this li numbers are rendered fine.

Can you confirm this, or am I doing something wrong?

thank you in advance.

**Comment by giginho** [comment]
Yes, I have the same problem. Does someone know any solution?

**Comment by tomtomau** [comment]
I'm facing this as well. At a guess, it'd be because tables have a limited style set.

**Comment by jengrace** [comment]
Hi, 

I'm experiencing this issue as well with lists of `<ul> <li> </li> </ul>` inside of tables. CSS styling is not being applied to lists within tables.

Thanks.

**Comment by finwe** [comment]
As being pointed here and documented, all css styles are ignored for block-level elements inside tables.
