### ISSUE TITLE
Support for PHP 7.3

### ISSUE THREAD

**Issue by Petervw** [mpdf/mpdf#933]
Currently, the composer package will throw this error:
 mpdf/mpdf v7.1.1 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.3.0RC6) does not satisfy that requirement

Can we safely upgrade this repository to 7.3?

**Comment by finwe** [comment]
The last version is compatible with 7.3. Until stable is out,  use `--ignore-platform-reqs` composer parameter to install with RC.

**Comment by Petervw** [comment]
@finwe Why not upgrade it today? The PHP 7.3 release is tomorrow.

See: https://wiki.php.net/todo/php73#timetable

**Comment by finwe** [comment]
Upgrade what? mPDF 7.1.7 already allows PHP ~7.3.0.

**Comment by finwe** [comment]
and `--ignore-platform-reqs` is not needed, I just installed 7.1.7 with plain

    php7.3 /usr/local/bin/composer require mpdf/mpdf

**Comment by Petervw** [comment]
Thnx. 👍
