### ISSUE TITLE
Box Shadow - Uninitialized string offset: 0

### ISSUE THREAD

**Issue by LucidNinja** [mpdf/mpdf#939]
### I found this bug
PHP message: PHP Notice:  Uninitialized string offset: 0 in /Users/***/project-name/vendor/mpdf/mpdf/src/Mpdf.php on line 2287

The box shadow seems to output as expected, albeit with errors in the console.

Refers to the function PrintPageBackGrounds
The line in question:  `if ($pb['col']{0} == 5) { // RGBa`

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF v7.0.2, PHP 7.2.10 on Laravel Valet, MacOS 10.14.1
### This is a PHP code snippet I use

```
<?php
$html = '<div style="box-shadow: 7px 10px 37px -6px rgba(0,0,0,0.43);">Hello</div>';

$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
$fontDirs = $defaultConfig['fontDir'];

$defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
$fontData = $defaultFontConfig['fontdata'];

$title = 'Test';
$mpdf = new \Mpdf\Mpdf([
        'mode' => 'utf-8',
        'format' => 'A4',
        'orientation' => 'P',
        'margin_left' => 0,
        'margin_right' => 0,
        'margin_top' => 0,
        'margin_bottom' => 0,
        'fontDir' => array_merge($fontDirs, [
              __DIR__ . '/../shared/fonts',
          ]),
          'fontdata' => $fontData + [
            "montserrat" => [
             'R' => "Montserrat-Regular.ttf",
             'I' => "Montserrat-Italic.ttf",
            ],
            "montserrat-bold" => [
             'R' => "Montserrat-Bold.ttf",
             'I' => "Montserrat-BoldItalic.ttf",
            ],
            "montserrat-light" => [
             'R' => "Montserrat-Light.ttf",
             'I' => "Montserrat-LightItalic.ttf",
            ],
          ],
          'default_font' => 'montserrat'
]);


$mpdf->SetTitle( $title );
$mpdf->WriteHTML($html);
$mpdf->Output('Test.pdf','I');


```

### This is a HTML/CSS code snippet I use

```

```

**Comment by finwe** [comment]
Closed in #952

**Comment by LucidNinja** [comment]
I'm just wondering what happened with this issue? I have recently upgraded to 7.1.0 and it doesn't seem to be fixed? It appears that a box shadow like this: 
`box-shadow: 7px 10px 37px -6px rgba(0,0,0,0.43);  ` simply breaks everything. Commenting it out fixes the issue. Are you not supporting it? Is there a way I can better understand the code or debug it? Or did you find a fix?

**Comment by LucidNinja** [comment]
Hi. I have now updated to version. 8.0.0 - I was hesitant to do so, but it has fixed the issue!

**Comment by bestiony** [comment]
after a lot of digging, I solved this. all I did was disable the package Laravel debug bar and the problem stopped
