### ISSUE TITLE
undefined Index  in otl function sliceOTLData  and FIX

### ISSUE THREAD

**Issue by didiergm** [mpdf/mpdf#941]
mpdf version 7.1.6 and 7.1.7 
php 7.1.25

I have an exception undefined index 'GPOSInfo'  in function sliceOTLdata. 

I changed Line 5726 
from 
`if ($OTLdata['GPOSinfo']) `
to 
`if (isset($OTLdata['GPOSinfo'])) `

and it seems to fix it for the time being

**Note** This did not happen in 7.1.4, although the sliceOTLdata is exactly the same between the 3 versions. So the root cause is somewhere else and my fix is very likely a partial fix

**Comment by Klap-in** [comment]
How is Mpdf instantiated in your setup?
Which html is feeded into mPDF, such that it triggers this error?  (please provide a _small_ html example)

This is useful for reproducing your case, and allows to create the unit test for this issue. Thanks!

**Comment by didiergm** [comment]
first declared as

class my_PDF extends \Mpdf\Mpdf {
  adds certain functions like Ellipse & Circle
}

then $pdf=new my_PDF( array( 'format' => 'A3-L', 'default_font_size'=> 12, 'default_font' => 'DejaVuSans',     'margin_left'=>6,'margin_right'=> 6, 'margin_top' => 6,'margin_bottom' => 6));

trouble is with a call to Multicell

TBH this is not the purest form of MPDF reporting. It started years ago with FPDF and as evolved to using MPDF but not all in the fairly complex report has been modified to pure HTML generation, it is a mixture of CELL, MULTICELL calls as well as some HTML. 

I also require two additional libs which could be of interest
include_once (sysclasses. "PDFMerger.php");
include_once (sysclasses. "fpdi/pdf_parser.php");


I am not sure if the above is really useful to you, but I should also point out then I never had any problems converting to mpdf 6 and 7 up to 7.1.4

**Comment by finwe** [comment]
Please, edit your posts to correctly format code.

**Comment by finwe** [comment]
Also, share your HTML/source PDF code, without it we are not able to assess and fix this correctly.

**Comment by TheDeon** [comment]
Also had this issue, it was caused by the variable passed to $pdf->MultiCell() being null. Just adding a null check fixed it in this case.
