### ISSUE TITLE
Inside block's absolute positioning not working

### ISSUE THREAD

**Issue by smileysharma** [mpdf/mpdf#946]
If we try to create a block with position absolute inside another block then its positioning is not working and element is coming at top rather than being related to outer div.

**Comment by smileysharma** [comment]
Hello, 

I am trying to position text on image so I need position abslute. For it I need outer div and then image and one more div inside it so that internal div text can be positioned above image. when I assign top and position absolute mPDF possition it top most top egardless of outr div position. 

MpDF version : 7.1.7
Initilization: $mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8','format' => 'Letter','margin_footer'=>0,'margin_left'=>0,'margin_right'=>0,'margin_top'=>20]);

HTML code : 
<div class="Header-part">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</div>
<table class="main"  style="background-color: rgb(255, 255, 255); text-align: center; width: 796px; margin: 0px auto; border-spacing: 0px; border-collapse: collapse; text-size-adjust: 100%;">
		<tbody>
			<tr>
				<td class="image image-full element-content"  style="text-align: center; padding: 10px 53px; position: relative; border-collapse: collapse; text-size-adjust: 100%;">
					<img class="content-image " height="300" style="width: 100%; height: 300px;" src="http://gconsole.com/admin/fm/source/digipay_super_admin/1.png" width="690">
					<div class="image_upper_text" style="position: absolute; bottom: 0; left:30px; font-size: 24px; padding: 10px 20px; width: 696px; text-align: center; color: white; font-weight: 700;top:30px;font-size: 32px; line-height: 40px;"><p style="text-size-adjust: 100%; margin: 0px;">Re-Design and Development of</p>Pharmedio Platform</div>
				</td>
			</tr>	
		</tbody>
	</table>

**Comment by smileysharma** [comment]
Hello, 

I am trying to position text on image so I need position abslute. For it I need outer div and then image and one more div inside it so that internal div text can be positioned above image. when I assign top and position absolute mPDF possition it top most top egardless of outr div position. 

MpDF version : 7.1.7
Initilization: $mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8','format' => 'Letter','margin_footer'=>0,'margin_left'=>0,'margin_right'=>0,'margin_top'=>20]);

HTML code : 
```
<div class="Header-part">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</div>
<table class="main"  style="background-color: rgb(255, 255, 255); text-align: center; width: 796px; margin: 0px auto; border-spacing: 0px; border-collapse: collapse; text-size-adjust: 100%;">
		<tbody>
			<tr>
				<td class="image image-full element-content"  style="text-align: center; padding: 10px 53px; position: relative; border-collapse: collapse; text-size-adjust: 100%;">
					<img class="content-image " height="300" style="width: 100%; height: 300px;" src="1.png" width="690">
					<div class="image_upper_text" style="position: absolute; bottom: 0; left:30px; font-size: 24px; padding: 10px 20px; width: 696px; text-align: center; color: white; font-weight: 700;font-size: 32px; line-height: 40px;"><p style="text-size-adjust: 100%; margin: 0px;">Re-Design and Development ofPharmedio Platform</p></div>
				</td>
			</tr>	
		</tbody>
	</table>

**Comment by jakejackson1** [comment]
As per the docs, [absolute positioning isn't supported in nested blocks](https://mpdf.github.io/what-else-can-i-do/fixed-position-blocks.html).

**Comment by smileysharma** [comment]
Don't we have any fix for it ? I need this .

**Comment by howtomake** [comment]
if i have 2 pages in pdf 
![screen shot 2019-01-25 at 14 41 08](https://user-images.githubusercontent.com/2373159/51746595-593c4b00-20af-11e9-8775-1dcec4dc4209.png)
