### ISSUE TITLE
Notice: Undefined offset: -1 in Mpdf\Mpdf->printcolumnbuffer()

### ISSUE THREAD

**Issue by mudrasamey** [mpdf/mpdf#948]
After upgrading to mpdf version 7.1.6 there are some unwanted PHP notices which are present in the log. Investigated this further and it seems not related to the implementation of the pdf generation

`Notice: Undefined offset: -1 in Mpdf\Mpdf->printcolumnbuffer() (line 24087 of /var/www/xxxx/vendor/mpdf/mpdf/src/Mpdf.php) #0`

**Comment by Klap-in** [comment]
Hi! You missed an important part of the issue template: How is Mpdf instantiated in your setup?
Which html is feeded into mPDF, such that it triggers this error?  (please provide the _smallest_ entire html and php example)

This is required for reproducing your case, and allows to create the unit test for this issue. Thanks!

**Comment by finwe** [comment]
Closing as stale and missing a reproducible example. Will gladly reopen, if still applicable on current version.
