### ISSUE TITLE
6.1 release

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#95]
@marclaporte @blueliquiddesigns @danielhjames Gentlemen, what has to be resolved and finished before we create the first "community" release and proceed to enhance mPDF in 7.0 branch? I guess we have to decide #51, are there other issues?

**Comment by marclaporte** [comment]
Not to my knowledge. Thanks for this!

**Comment by danielhjames** [comment]
I don't know of any issues that would prevent a release. Please let me know if you would like help with a release announcement, we could send it to some news sites. We should also let Ian know beforehand.

**Comment by blueliquiddesigns** [comment]
I found one small issue with the updated FPDI exception error last week. I've been testing the patch out this week but will submit it from my fork to the upstream as soon as I get the chance.

**Comment by danielhjames** [comment]
Maybe we should also ask https://github.com/kartik-v/mpdf to test as they are getting nearly 10k downloads a month of their fork. I've already made kartik-v aware of this repo, maybe they will have some insights for what is needed.

**Comment by blueliquiddesigns** [comment]
I pushed the FPDI patch I mentioned and you can see it here https://github.com/mpdf/mpdf/pull/100.

**Comment by kartik-v** [comment]
Folks - I have incorporated a redirection message on the  [kartik-v/mpdf repo](https://github.com/kartik-v/mpdf/blob/master/README.md) to use this repo instead.

The other projects have been updated to use this repo as a dependency as well.

**Comment by finwe** [comment]
@kartik-v This is awesome news, thanks!

**Comment by finwe** [comment]
Released https://github.com/mpdf/mpdf/releases/tag/v6.1.0
