### ISSUE TITLE
Minimal PHP version for v8.0

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#955]
I'm considering marking v8 PHP7.1+. Opinions? Maybe I could be convinced for 7.0+ but I am hesitant to support unsupported PHP versions.

On the other hand I do not exactly know used versions of mPDF userbase.

@machour @marclaporte @jakejackson1

**Comment by machour** [comment]
👍 for PHP 7.1, it's slowly becoming the minimal requirement of major PHP frameworks.

**Comment by jakejackson1** [comment]
Right now roughly 30% (10,000) of our users are running on PHP5.6. My plan is to continue supporting this version until November 2019, and then bump up the minimum PHP requirements. 

A couple questions / feedback:

1. Is there any features in PHP 7.0 / 7.1 you want to roll into the v8 release? Or is this *initially* about reducing the support / testing footprint from older versions? If the latter, a more inclusive option for the time being would be to update the readme and say "hey, we're only addressing bugs / support if you can replicate it in a supported version of PHP". 

2. If the minimum version was bumped up in v8, would you allow me to backport bugs / features to the v7 branch for 12 months?

The beauty of mPDF is to runs fine on the cheapest shared hosting you can get, and these hosting provides are always a little slow on the uptake of newer versions of PHP. My suggestion is to leave v8 as being 5.6 compatible and limiting the issue tracker to supported versions of PHP. In v9, bump the minimum PHP requirements, while reworking the codebase to make use new features (return types, null coalescing, grouped namespaces ect).

**Comment by finwe** [comment]
Yeah, I agree. Lets patch v8 with what is the most necessary, abandon v7, and plan to bump requirements in v9.
