### ISSUE TITLE
Set page size as "Legal" not working 

### ISSUE THREAD

**Issue by swati-clarion** [mpdf/mpdf#960]
Hello,

I am trying to create PDF with page size "Legal". But when we open PDF in Adobe Acrobat Reader and try to print , the page size defaults to last used page size.  I want to force page size to "Legal" in print view. How can we achieve this?

### This is a PHP code snippet I use
```php
// $mpdf = new \Mpdf\Mpdf(['format' => 'Legal']);		
$mpdf = new \Mpdf\Mpdf(array('mode' => 'utf-8', 'format' => array(216,356)));		
$mpdf->SetHeader($title);
$mpdf->SetWatermarkImage(asset("images/watermark3.png"),0.5,'F','F');
$mpdf->showWatermarkImage = true;

$mpdf->AddPageByArray(array(
	'orientation' => 'P',
	// 'sheet-size' => 'Legal',
	'sheet-size' =>array(216, 356),
));

$mpdf->WriteHTML($html);
$mpdf->Output($name,'I');
```

I am using PHP version 7.2 and latest mpdf version 7.0
I need PDF in Legal page size only and also want to print in same size by default. Please help on how to do this.

**Comment by finwe** [comment]
There is AFAIK no way we can influence printer page size settings from PDF. Anyway, setting Legal as page size of the PDF itself works correctly.

Closing this.
