### ISSUE TITLE
Not work child combinator

### ISSUE THREAD

**Issue by maranqz** [mpdf/mpdf#961]
### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
fpm, php 7.0.33, mpdf 6.1.0

### This is a PHP code snippet I use

```
<?php
$path = (getenv('MPDF_ROOT')) ? getenv('MPDF_ROOT') : __DIR__;
require_once $path . '/vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML($html);
$mpdf->Output();
```

### This is a HTML/CSS code snippet I use

```
<style>
    .a > .b{
        color: red;
    }
</style>
<div class="a">
    <div class="b">asd</div>
</div>
```

**Comment by finwe** [comment]
Child combinator is not supported. See https://mpdf.github.io/css-stylesheets/introduction.html and linked man pages for a list of supported CSS.
