### ISSUE TITLE
Notice: Undefined variable: codeToGlyph

### ISSUE THREAD

**Issue by sneakyx** [mpdf/mpdf#962]
### We found this bug 
Notice: Undefined variable: codeToGlyph in TTFontFile.php

We use FontAwesome and in some files, we get this error.
We have a solution, I try to upload the solution.

**Comment by Klap-in** [comment]
Do you have also a minimal, but complete php+html example please? That allows to create directly a unit test for this issue.

**Comment by Klap-in** [comment]
Sorry, I see there is already a PR.

**Comment by finwe** [comment]
Closed with 23fdefd (with mistyped issue number).
