### ISSUE TITLE
Mpdf Undefined offset: -1

### ISSUE THREAD

**Issue by aapeliltd** [mpdf/mpdf#965]
Mpdf was working fine. but when i have large data... it give this error

A PHP Error was encountered
Severity: Notice

Message: Undefined offset: -1

Filename: src/Tag.php

Line Number: 4371

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.

**Comment by aapeliltd** [comment]
I figured it out already... Is now fixed. Thanks On Feb 1, 2019 09:50, Matěj Humpál <notifications@github.com> wrote:Closing as per issue template warning.
Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.
