### ISSUE TITLE
Mulitple replaceable aliases are not replaced in header

### ISSUE THREAD

**Issue by finwe** [mpdf/mpdf#969]
### I found this bug / would like to have this new functionality

When using multiple replaceable aliases, ony the first is replaced.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

PHP 7.2, dev-development mPDF

### This is a PHP code snippet I use

```
<?php

$mpdf = new \Mpdf\Mpdf([]);

$mpdf->setHeader('{PAGENO} of {nb​}');
$mpdf->WriteHTML('aaa');
$mpdf->WriteHTML('<pagebreak resetpagenum="1" pagenumstyle="1" suppress="off" />');
$mpdf->WriteHTML('aaa');

$mpdf->Output('example001.pdf', 'F');
```

**Comment by peterdevpl** [comment]
The example with `{nb}` alias you posted has some strange bytes underneath. I copied your code into a hex editor. Between `nb` and `}` there are three additional bytes, not rendered as any Unicode character: `E2 80 8B`.

Try re-entering `{nb}` from your keyboard and you'll see. It works for me :)

**Comment by finwe** [comment]
Oh. Really. Thanks!
