### ISSUE TITLE
Font displaying differently between pdfs with images and without images.

### ISSUE THREAD

**Issue by devtaher** [mpdf/mpdf#971]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> For contributing here, please see the guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md
>
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

### I found this bug  - The fonts are getting squished and blurry when we add Images.

Please see the following screenshots of the 2 different PDF's generated using the [standard method ](https://mpdf.github.io/getting-started/creating-your-first-file.html)described in the docs.

This issue is more evident on screens having resolution of 2560x1600  or lower.

<img width="1429" alt="page_1_comparition" src="https://user-images.githubusercontent.com/3863292/53618303-c6904e00-3c10-11e9-8916-5089c8f3b732.png">
<img width="1412" alt="page_2_comparition" src="https://user-images.githubusercontent.com/3863292/53618304-c728e480-3c10-11e9-923f-61bbec3f7645.png">

The HTML and CSS for both these css is same but the font rendering is not the same. The fonts being used here are from https://github.com/IBM/plex/tree/master/IBM-Plex-Sans/fonts/complete/ttf loaded using the instructions mentioned [here](https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html)

I think mpdf is rendering them differently. Any inputs on this is very much appreciated.

TIA

### This is a PHP code snippet I use

I use the standard code to create PDF as per the documentation at - https://mpdf.github.io/getting-started/creating-your-first-file.html

### This is a HTML/CSS code snippet I use

Sample HTML for Paragraphs

```

<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

```

CSS for Paragraphs

```

p {
    font-size: 12pt;
    color: #3D3D3D;
    line-height: 16pt;
    font-family: ibmplexsans,"Helvetica Neue",Arial,sans-serif;
    font-weight: 400;
}


```

Sample HTML for Images

```

<div class="datasheet__image--wrapper">
	<strong>
		<img data-img-width="210" data-img-height="139" src="http://sample.com/system/files/styles/datasheet_2_cols_sup_img/private/datasheet/2019-02/1_0.jpg?itok=h7Bjqoim&amp;auth_token=wJgOvTqu8JaYBgmLCvinbjIjKGMIvy1N5p2gxZcyyG8" class="datasheet__image">
	</strong>
</div>

```

CSS for Images

```

.datasheet__image--wrapper, .infographic_image {
    text-align: center;
    margin-bottom: 20px;
    margin-top: 20px;
    font-family: ibmplexsans,"Helvetica Neue",Arial,sans-serif;
    font-weight: 400;
}

.datasheet__image--wrapper .datasheet__image, .infographic_image img {
    max-width: 100%;
    height: auto;
}

```

**Comment by JanSlabon** [comment]
You should check if this is the case for all viewer/reader applications. At the end mPDF does not really render the things but this is the task of the viewer/reader application. They also come with several settings which may be different depending on the content. In Acrobat you may try to play with these settings: 
Edit > Preferences >Page Display
![grafik](https://user-images.githubusercontent.com/12390057/53563487-73f15c00-3b54-11e9-91c8-3bb5a9cc739f.png)

**Comment by devtaher** [comment]
@JanSlabon Thanks for your valuable insights. 

Turns out the font distortion was due to the font being used at the time. Updating the font with the latest seems to be working fine. Closing this issue for now.
