### ISSUE TITLE
File Including Iss

### ISSUE THREAD

**Issue by upendraalwafaa** [mpdf/mpdf#972]
Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /home/demosoftwarecomp/public_html/rasti_lari/application/third_party/mpdf22/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 5
![mpdf issue](https://user-images.githubusercontent.com/32842147/53324217-b5d29600-38f9-11e9-9c2a-47052b80d63d.PNG)

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by finwe** [comment]
You have installed composer dependencies on PHP7.1+ and are trying to run them on older PHP. Not a mPDF issue.
