### ISSUE TITLE
Bug with utf8 character

### ISSUE THREAD

**Issue by fglueck** [mpdf/mpdf#979]
I found this bug:
MPDF produce the Error: Class Mpdf\Tag\ not found if I have the follow content inside any html:
💾
It doesn't matter if I use HTML Entity (hex/dec) or native.

I use:
$mpdf->WriteHTML($html, 0);

PHP Version 7.2 and MPDF v7.1.9

### This is a PHP code snippet I use

```
<?php
$html = <<<HTML
<html>
<body>
💾
</body>
</html>
HTML;
$mpdf->WriteHTML($html, 0);
```
Same problem with all character from this page:
https://www.fileformat.info/info/unicode/block/miscellaneous_symbols_and_pictographs/utf8test.htm

**Comment by finwe** [comment]
Unable to reproduce with a phpunit test. Please provide additional information.

**Comment by fglueck** [comment]
I found the bug, the method getTagInstance try to load any content.
The array after 
$a = preg_split('/<(.*?)>/ms', $html, -1, PREG_SPLIT_DELIM_CAPTURE);
Will contain like:
span
xyz <--- or any UTF8 Char
/span
getTagInstance now try's to load a class "xyz". This is not a valid TAG.
It seems to be a problem with different autoloaders, if one throws an exception if the class can't load...
I make a little, not perfect, workaround in getTagInstance. But I think it would be better to fix the preg_split... or is the content inside necessary?
It is also possible that:
```
		for ($i = 0; $i < $cnt; $i++) {
			$e = $a[$i];
			if ($i % 2 == 0) {
```
is not correct?, because why its try to load an empty class?
The array after regex_split look good:
```
array (
  0 => '',
  1 => 'html',
  2 => '',
  3 => 'body',
  4 => '🗿',
  5 => '/body',
  6 => '',
  7 => '/html',
  8 => '',
)
```

**Comment by fglueck** [comment]
the calling line is:
```
	$tag = (isset($a2[0]) ? strtoupper($a2[0]) : '');
....
       $this->tag->OpenTag($tag, $attr, $a, $i); // mPDF 6
```
OpenTag will call with an empty $tag ('')

But the utf8 Symbol is no tag....

**Comment by finwe** [comment]
This is alrigt and all, but I still cannot reproduce this. This leads me to believing there is some side condition to this. What are your Mpdf object config options?

**Comment by fglueck** [comment]
```
   $settings = [
      'mode'          => $dest=='F' ? 'UTF-8-c' : 'UTF-8',
      'format'        => $layout,
      'default_font_size' => 0,
      'default_font'  => '',
      'margin_left'   => 10,
      'margin_right'  => 10,
      'margin_top'    => 17,
      'margin_bottom' => 8.5,
      'margin_header' => 3,
      'margin_footer' => 3,
      'orientation'   => $orientation,
      'tempDir'       => COCKPIT_TEMP.'/pdf',
    ];
    $mpdf=new \Mpdf\Mpdf($settings);

    $mpdf->displayDefaultOrientation = true;
    $mpdf->keep_table_proportions = true;
    $mpdf->use_kwt = true;
    $mpdf->useSubstitutions=true;
    $mpdf->backupSubsFont = array('dejavusanscondensed', 'arialunicodems','freesans', 'sun-exta'); 

    $mpdf->title2annots=false;
    $mpdf->bookmarkStyles = array(
        0 => array('color'=> array(85, 157, 208), 'style'=>''),
        1 => array('color'=> array(0,0,0), 'style'=>''),
        2 => array('color'=> array(0,0,0), 'style'=>'I'),
    );

    $mpdf->SetDisplayMode('fullpage');
    $mpdf->SetAuthor('Cockpit');
    $mpdf->SetCreator('Cockpit');
    $mpdf->dpi = 96; 
    $mpdf->img_dpi = 150;

    $mpdf->SetHTMLHeader('<table width="100%" border="0" cellspacing="0" cellpadding="0"<tr><td><h1>'.$title.'</h1></td><td align="right"><img align="right" width="150" src="img/logo.png" border="0" /></td></tr></table>');

    $mpdf->SetFooter("{DATE d.m.Y H:i:s} by Cockpit|$filename|Seite {PAGENO}/{nb}");

    $mpdf->setBasePath(WEBSITE_URL);

    $mpdf->WriteHTML($html, 0);

```

**Comment by finwe** [comment]
The test with this code still passes on current development branch.

**Comment by finwe** [comment]
Can you try to make a PR with a test failing in Travis? See my attempt with your code https://github.com/mpdf/mpdf/commit/7bdd881073956730b6e36f5d65bbdc1857e9a7c9
https://travis-ci.org/mpdf/mpdf/builds/503066779

**Comment by fglueck** [comment]
I found the "Exception" it comes from an other autoloader:
```
function autoLoader($className, $checkonly=false) {
  $classes = new stdClass();
  $cachename = COCKPIT_TEMP.'/path.cache';
  if(file_exists($cachename)) {
      $classes = json_decode(file_get_contents($cachename));
  }
  ...
  if(isset($classes->$className) and file_exists($classes->$className)) {
    include $classes->$className;
  }
  else {
    throw new ErrorException("Class {$className} not found"); # <----- !!!
  }
  return false;
}

spl_autoload_register('autoLoader');
```
But, if MPDF not only loads "" (empty) Tags it will cost a lot of time. Every empty Tag will be tried to be loaded. So I made this changes:
  ```
private function getTagInstance($tag)
  {
    if (!empty($tag)) {
      $className = self::getTagClassName($tag);
      if (class_exists($className)) {
        return new $className(
          $this->mpdf,
          $this->cache,
          $this->cssManager,
          $this->form,
          $this->otl,
          $this->tableOfContents,
          $this->sizeConverter,
          $this->colorConverter,
          $this->imageProcessor,
          $this->languageToFont
        );
      }
    }
  }
```

**Comment by finwe** [comment]
Why even call the method rather than enclose all of its contents with an if?

**Comment by finwe** [comment]
Furthermore, there is no difference in getInstance call count in Tag.php with

    $tag && $object = $this->getTagInstance($tag)

and 

    $object = $this->getTagInstance($tag)

(tested with example61 from examples repository) - getTagInstance is not being called for any code portion. With your example code, getTagInstance is not being called at all.

**Comment by fglueck** [comment]
I check this in 2 weeks, when I'm back at office...

**Comment by finwe** [comment]
@fglueck Any update?

**Comment by finwe** [comment]
Closing as worksforme/stale. Feel free to create a new issue/PR reproducing the issue preferably in a unit test.
