### ISSUE TITLE
top: 50% ignored ?

### ISSUE THREAD

**Issue by Yamakasi** [mpdf/mpdf#98]
I have a div with a fixed heigth and I want to vertical center text in it.

I tried:  

#container {
  height: 200px;
  width: 200px;
  position: relative;
  background-color: hotpink;
}

#inner-container {
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  position: absolute;
  display: block;
  background-color: lime;
}

<div id="container">
  <div id="inner-container">
    <span>hello</span><br>
    <span>world</span><br>
    <span>such multiline</span>
  </div>
</div>

Is this not possible using mpdf ?

**Comment by blueliquiddesigns** [comment]
No. This isn't possible the way you are doing it.

Absolute positioning is only possible as a top-level HTML element of the `<body>` tag. It cannot be nested. I also don't believe the `transform` attribute will work with mPDF.
