### ISSUE TITLE
Search feature request

### ISSUE THREAD

**Issue by elb98rm** [mpdf/mpdf#981]
## Functionality Request

The current version of mPDF doesn't offer a simple search. It is actually is part of OverWrite() method, but it would be exceptionally easy to simply abstract this out.

This is useful as part of functional testing. I've created multiple scripts to automate PDF creation. In order to prove this works we have automated unit tests (technically functional test, but I'm not going into that here!).
If I write a pdf, there's no way to confirm that the content I've edited has actually been changed, at least programatically.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

* vagrant linux box
* lumen 5.4

### Original code suitable for moving to search/find function:

`Mpdf.php` : line 26960

```
		if (!$this->onlyCoreFonts && !$this->usingCoreFont) {
			foreach ($search as $k => $val) {
				$search[$k] = $this->writer->utf8ToUtf16BigEndian($search[$k], false);
				$search[$k] = $this->writer->escape($search[$k]);
				$replacement[$k] = $this->writer->utf8ToUtf16BigEndian($replacement[$k], false);
				$replacement[$k] = $this->writer->escape($replacement[$k]);
			}
		} else {
			foreach ($replacement as $k => $val) {
				$replacement[$k] = mb_convert_encoding($replacement[$k], $this->mb_enc, 'utf-8');
				$replacement[$k] = $this->writer->escape($replacement[$k]);
			}
		}
```
This could be removed, moved to something like:  `Mpdf::search($search)`, with the write being hooked onto a successful search.

As I mentioned, mpdf could then be integrated into functional testing.

Thanks

**Comment by finwe** [comment]
The intent of mPDF is to generate PDF documents from HTML, not to search in documents. You`d probably want to use a different tool in the functional test.

**Comment by elb98rm** [comment]
So.. how do I prove it works?

**Comment by finwe** [comment]
Eg. by comparing the result with a reference document.

**Comment by elb98rm** [comment]
I have proved this visually with some existing PDFs, but the point is to automatically test it and prove that a customer. How do you compare your output, with a desired PDF? And to be clear: the idea is to prove you got it correctly. 

Imagine having to make 2000 unique pdfs, all procedurally generated, with customer details. Being able to automatically validate that you got it correct is not only important, it's quite possibly a legal requirement.

Does anyone know how to parse a PDF for basic text using mpdf? If it's a no-goer, then so be it. But to create code/documents which you can't test isn't a good approach in my opinion.

My suggestion was to expose the existing functionality for users. I'm surprised this isn't a commonly requested feature.

**Comment by finwe** [comment]
The intent of mPDF is not to parse PDF files. Even the replace feature is sort of a hack and does not always work correctly. 

Another point: How do you validate that your validation validates properly? Validating results with the same tool used to receive these results does not make sense.

**Comment by elb98rm** [comment]
Yes it does? Following that logic, you shouldn't use php to test php.
"I used .net to unit test my php code" is something you wont hear.

"Who tests the unit tests?" is minimalist argument... you can go right down to the question "who is to say what is real?".
Every normal person draws an acceptable line on this grade. 

It is totally normally to use a system as part of the system testing, whether that be PHP, classes or systems. 

Checking something wrote sensitive customer details is pretty close to the "important side".
I'm not being over the top when I say that, particularly when you're going to send sensitive emails to the customer in an automated fashion!

**Comment by finwe** [comment]
Yes, I draw this line no further than between mPDF and the documents generated by it.

**Comment by elb98rm** [comment]
"and the documents generated by it."... so how do I check those documents automatically?

**Comment by finwe** [comment]
Not with mPDF.

But, generally, I doubt you would want to check _every_ document you will ever generate. Basically, it would be enought to check a reasonable number of different (static) inputs and compare them byte-for-byte with pre-generated reference documents. You don't need to search for a string in a PDF file.
