### ISSUE TITLE
Error InsertIndex()

### ISSUE THREAD

**Issue by fabiozech** [mpdf/mpdf#983]
I am trying to make an index using the documentation settings but the page numbering does not correctly display used code:

`
    $mpdf->WriteHTML($html);
    
    $canti = ['Jonas, Fabio, Teste'];
     
     foreach ($canti as $canto) {       
       $mpdf->IndexEntry($canto);
     }
    
    $mpdf->AddPage();
    $mpdf->WriteHTML('<h2>Sumario</h2>');
    $mpdf->InsertIndex(0, false, "pt_BR.utf8", "Portuguese_Brazil"); 
`

The code that generates this PDF test is this:

`$i = 1;
                        while ($i <= 250) {
                            echo $i++;
                            echo '<br/>';
                            if($i == 100){
                                echo 'Jonas';
                                echo '<br/>';
                            }
                            if($i == 50){
                                echo 'Fabio';
                                echo '<br/>';
                            }
                            if($i == 140){
                                echo 'Teste';
                                echo '<br/>';
                            }
                            }`

On the index page it looks like this:
Jonas, Fabio, Test 6, but these words are distributed in the pages the correct one should be

Fabio 2
Jonas 3
test 3

The version I am using is 7

**Comment by jakejackson1** [comment]
To correctly debug this issue, we'll need a simple completed working-example of the code used to generate this problem (i.e we should be able to copy and paste the code to a file that has access to the `Mpdf\Mpdf()` object and replicate the issue. 

You should also be more specific about the version of Mpdf you are using. Is it version `7.0.0`? If so, does this issue occur with version `7.1.9`?

**Comment by fabiozech** [comment]
Follow the code used in the test, remembering that the problem is presenting in version 6.1 and version 7.1.9, am I doing something wrong?

```
$html = "<html><body> 
<?php
                        
                        $i = 1;
                        while ($i <= 250) {
                            echo $i++;
                            echo '<br/>';
                            if($i == 100){
                                echo 'Jonas';
                                echo '<br/>';
                            }
                            if($i == 50){
                                echo 'Fabio';
                                echo '<br/>';
                            }
                            if($i == 140){
                                echo 'Teste';
                                echo '<br/>';
                            }
                            }
                        ?>
</body> </html>"

require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('$html');
$canti = ['Jonas, Fabio, Teste'];
 
 foreach ($canti as $canto) {       
   $mpdf->IndexEntry($canto);
 }

$mpdf->AddPage();
$mpdf->WriteHTML('<h2>Sumario</h2>');
$mpdf->InsertIndex(0, false, "pt_BR.utf8", "Portuguese_Brazil");

$mpdf->Output();
```

**Comment by Thoulah** [comment]
You are trying to define `$html` before `<?php`.

**Comment by fabiozech** [comment]
I did not express myself well I work with codeigniter and I have an html file and by codeigniter I call this file and step to this variable $ html and from that comes into action the code below.

I think it was clearer to understand.

html ( relTest.html )

```
<html>
<body>
<?php
                        
$i = 1;
while ($i <= 250) {
    echo $i++;
    echo '<br/>';
    if($i == 100){
        echo 'Jonas';
        echo '<br/>';
    }
    if($i == 50){
        echo 'Fabio';
        echo '<br/>';
    }
    if($i == 140){
        echo 'Teste';
        echo '<br/>';
    }
    }
?>

</body>
</html>
```
the codeigniter transforms the content of the relTest.html page and places it within the variable $html

MPDF

```
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('$html');
$canti = ['Jonas, Fabio, Teste'];
 
 foreach ($canti as $canto) {       
   $mpdf->IndexEntry($canto);
 }

$mpdf->AddPage();
$mpdf->WriteHTML('<h2>Sumario</h2>');
$mpdf->InsertIndex(0, false, "pt_BR.utf8", "Portuguese_Brazil");

$mpdf->Output();
```

**Comment by finwe** [comment]
This is not a bug, more likely wrongly used InsertIndex. As described in the documentation:

> Insert an Index entry for the document Index, referencing the current writing position in the document.

The `InsertIndex` method has to be called when writing the content, it always displays the page number current when called. So you have to write the name with WriteHTML, call the method and continue writing html.

Or, you'll be much better off using `<indexentry content="Jonas"/>Jonas` markup in your HTML directly.
