### ISSUE TITLE
punctuation 

### ISSUE THREAD

**Issue by xuxuxia** [mpdf/mpdf#987]
If Chinese punctuation is followed by letters or numbers, punctuation will not be displayed. What is displayed is unrecognizable symbols，
Give an example: ‘《aaa ’ and ‘、12313’ ， ‘《’ and ‘、’ will not displayed，Chinese symbols in front of you can not be displayed unless they are followed by Chinese

**Comment by xuxuxia** [comment]
Give an example:    ‘《aaa ’  and   ‘、12313’  ， ‘《’ and ‘、’ will not displayed

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by xuxuxia** [comment]
> Closing as per issue template warning.
> 
> Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.



> Closing as per issue template warning.
> 
> Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.
please run 
$mpdf->WriteHTML('《aaa》 <br> 《123》 <br>《你好》');
