### ISSUE TITLE
Speed issue divs vs tables

### ISSUE THREAD

**Issue by jangreis** [mpdf/mpdf#99]
Hi,
Sorry, I'm not sure if this is the right way/place to ask this question and I apologize if it isn't. I'm trying to generate a relatively complex layout and originally I went with nested tables, but I'm trying to precisely control the size of each element and with tables it could happen that one cell had too much content and then the entire table had to be resized by mpdf to fit the page. There were around 2.5k cells over 3 pages and mpdf was relatively slow (~10 seconds which pushed against the max execution time of my server, thankfully I now have one with 30 seconds), so I figured I could make it faster using divs for the structure instead of tables as I can control the sizes of these precisely via css. However, it turns out the pdf creation is now much slower still. Could you perhaps provide some guidance as to what kind of structure might make things easier on mpdf?
Many thanks
J

**Comment by jangreis** [comment]
For reference, this is the kind of structure I'm trying to place on each page about 100 times:
`
_______________________
|      |____|____|____|
|______|___________|__|
|______|_______|______|
`

**Comment by bencun** [comment]
I'm having a real issue here with tables, it's super slow - even with simple table layouts. Did you perhaps try implementing everything with DIVs? Did you manage to speed up things somehow?

**Comment by finwe** [comment]
Closing as stale.
