### ISSUE TITLE
Cannot use custom stream wrappers for images

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf#991]
Due to the effect of https://github.com/mpdf/mpdf/pull/950, custom stream wrappers like that registered with the [Amazon S3 SDK ](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html), which registers `s3://` can no longer be used. 

Should we consider allowing the supported streams for images to be configured (with a warning about using insecure streams), while defaulting to the current allowed streams?

**Comment by finwe** [comment]
If there's a use case and a will, why not?
