### ISSUE TITLE
Fatal Error - setasign\Fpdi\FpdiTrait' not found

### ISSUE THREAD

**Issue by tbba** [mpdf/mpdf#995]
After updateing to V.8 I get this:
Fatal Error - setasign\Fpdi\FpdiTrait' not found
File: .../vendor/mpdf/mpdf/src/FpdiTrait.php:21

PHP 7.2

**Comment by finwe** [comment]
Update dependencies with composer.

**Comment by superdeeid** [comment]
same error with version 8.0.0, 8.0.3 & 8.0.4 (php7.3). i've deleted all my vendor dir just to be sure and it keeps telling this error.
Trait 'setasign\Fpdi\FpdiTrait' not found in {path}\vendor\mpdf\mpdf\src\FpdiTrait.php on line 21

**Comment by moikzz214** [comment]
anyone resolve this issue coz i have the same problem
